### ISSUE TITLE
BlenderBIM: output Blender and BlenderBIM version number in error message

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1009]
Would be nice if the error message printed out Blender and BlenderBIM version number to help narrow into troubleshooting.

**Comment by Moult** [comment]
I don't know if there is an easy way to do this (I haven't looked too deeply? Maybe Python has a way to override the global traceback printing?). Right now error reporting is very "raw", which makes it easier for me to debug, but scarier for users - but is necessary for the 0.0.X series.

If I don't find a way to do this, I'm closing this bug, since it won't be a reality until the 0.X.X series when I'd probably set out building proper error reporting.

In general, I haven't faced issues where I'm uncertain about the Blender and BlenderBIM version number, so it isn't a big issue for me. The Blender version doesn't matter, and the add-on version number usually plays a small part - either the feature is built, or isn't.

**Comment by civilx64** [comment]
One option would be to subclass the Python builtin Exception class to always prefix or suffix the error message with the BlenderBIM version. Pardon my ignorance as I'm not super familiar with this part of the IFCOS codebase - is there currently a global variable that tracks version number? I've heard about (but never implemented) a python package to "bump" the version number as a pre-commit hook.

**Comment by Moult** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/Makefile#L303
https://blender.stackexchange.com/questions/2797/how-can-i-get-a-list-of-the-installed-addons-using-the-api

@civilx64 that sounds right :) Would you like to have a shot at tackling this one?

**Comment by Moult** [comment]
Closing out bug, since I don't see an easy way of doing this without hacky monkey-patching, and based on personal experience debugging people's issues, the version number is rarely useful right now.
