### ISSUE TITLE
[BlenderBIM] Add-on preferences have no default (v0.0.200912)

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#1011]
The preferences:
 * __SVG to PDF Command__
 * __SVG to DXF Command__
 * __SVG Command__
 * __PDF Command__

All begin unfilled. As there is no example, it is not immediately obvious how to fill them out.

**Comment by Moult** [comment]
Currently only a feature for power users, as it essentially runs a command:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/operator.py#L2354
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/operator.py#L2366
https://github.com/IfcOpenShell/IfcOpenShell/blob/44306b036d5c356872e9428bd0a927f3127438e7/src/ifcblenderexport/blenderbim/bim/operator.py#L67

In the future, will need to write it so that you can select from a dropdown or such, e.g. Inkscape / Browser.

Feel free to hack on it :)

**Comment by theoryshaw** [comment]
noob question is this the proper syntax? 

![image](https://user-images.githubusercontent.com/507113/154809682-2ca72edb-0625-478a-abd3-b315aad5f7c2.png)
