### ISSUE TITLE
Sphere (revolved circle) is not rendered properly

### ISSUE THREAD

**Issue by giovannivelludo** [IfcOpenShell/IfcOpenShell#1030]
I'm using Blender 2.90.1 and BlenderBIM 200912 on Linux.
The following .ifc file contains a sphere obtained by rotating a circle around an axis, but what is displayed in Blender after the import is just a circle:

[sphere.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/5343297/sphere.txt) (I changed the extension to be able to upload it on GitHub)

**Comment by aothms** [comment]
Yes, this is buried deep inside the descriptive text of the standard.

> The axis shall be in the plane of the surface and the axis **shall not intersect the interior of the bounded surface**.

https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcgeometricmodelresource/lexical/ifcrevolvedareasolid.htm

So to construct a sphere this way, you need to use half of a circle so that it doesn't intersect and sweep it 2 pi.

I have implemented a check for this in the code to emit a warning at least.
