### ISSUE TITLE
BlenderBIM: add/remove/reassign 'attributes', or 'Property Sets' or 'Object Quality Sets', etc. to multiple objects at the same time

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1060]
Is it possible to add/remove/reassign 'attributes', or 'Property Sets' or 'Object Quality Sets', etc. to multiple objects at the same time?

Thought 'alt' would work, but it doesn't seem to.

**Comment by Moult** [comment]
You can add / reassign attributes, properties by adding/assigning to the active object, and then selecting multiple, with the active one being the one you want to propagate, then pressing the `Copy Property` button.

Quantities are kinda different as usually you don't want to copy them, you want to calculate them for multiple objects. This works in a very similar way, simply by pressing the guess quantity button with multiple selected.

There is no way to remove attributes on multiple. Maybe I should make this work so that if you have multiple selected and press remove, it deletes it for all? What do you reckon?

![image](https://user-images.githubusercontent.com/88302/97637211-55143d00-1a8e-11eb-8bf0-a7b45170126d.png)

**Comment by theoryshaw** [comment]
Yes, would be super helpful to have a way to remove or add attributes in bulk.  Already had a couple painful times where this would have been awesome. 

Also, it would be nice if when you changed an object's IFC class, that it asked if you if you want to delete the associated pset and attributes as well.  I had changed the class of a number of objects and had a lot of 'dross' that I need to manually remove. :)

**Comment by Moult** [comment]
You can add attributes in bulk. Did you try what I suggested?

I'll add a feature to remove attributes, psets, qsets, properties, and quantities in bulk.

I'm not a fan of dialog boxes in general. I'll find a way to improve the situation when changing object classes.

**Comment by theoryshaw** [comment]
It appears you can add the value of the attribute in bulk, but you can't add the attribute in bulk.  Is that correct?

Maybe a UI like this?



![image](https://user-images.githubusercontent.com/507113/97788176-f1207000-1b84-11eb-856a-eac4a90124b3.png)


...or maybe even remove ![image](https://user-images.githubusercontent.com/507113/97788195-24fb9580-1b85-11eb-99c9-bc67ae88159c.png) altogether and just have the value automatically propagate to all the selected objects.

---

I agree about dialog boxes.

**Comment by Moult** [comment]
@theoryshaw what is the purpose of adding a blank attribute in bulk?

**Comment by theoryshaw** [comment]
A lot of times i'll add objects and modify them as I design, not worrying about metadata at first, once things settle down enough, then i'll add classes and descriptions, etc. 


Current approach... 
- Add description attribute
 - add 'foo' value
- Add description attribute
 - add 'bar' value
- Add description attribute
 - add 'baz' value
- Add description attribute
 - add 'qux value

compared to a more efficient approach...
- Add description attribute (to multiple objects) and then...
 - add 'foo' value
 - add 'bar' value
 - add 'baz' value
 - add 'qux value

Similarly adding(and removing) 'property sets' and 'quality sets' in bulk would improve efficiency as well.

**Comment by Moult** [comment]
Everything can now be done in bulk. Closing bug.
