### ISSUE TITLE
Log error line ...

### ISSUE THREAD

**Issue by Nevermind3r88** [IfcOpenShell/IfcOpenShell#1063]
Hi guys and thanks for your great work!
Maybe is a similar problem solved before but I want to open a new 3d to be sure.
I see a strange log with several errors when I try to export my file to IFC extension.
The last version works well, only some problems exporting objects before imported from other BIM softwares.
Now, I'm not able to export every object in my file.
This path doesn't exist on my pc:
C:/Program Files/Blender Foundation/Blender\2.90\scripts\addons\blenderbim\libs\site\packages\lark
I updated using your guide: remove folders in AppData, next addon and then install new version.
THANKS!

Windows 10 - BlenderBIM 0.201025.

Traceback (most recent call last):
File "C:\Users...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 107, in execute
ifc_exporter.export(context.selected_objects)
File "C:\Users...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 1350, in export
self.ifc_parser.parse(selected_objects)
File "C:\Users...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 86, in parse
self.projects = self.get_projects()
File "C:\Users...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 886, in get_projects
'attributes': self.get_object_attributes(obj)
File "C:\Users...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 170, in get_object_attributes
attributes = {'Name': self.get_ifc_name(obj.name)}
AttributeError: 'NoneType' object has no attribute 'name'

location: :-1

**Comment by Moult** [comment]
I responded here: https://github.com/IfcOpenShell/IfcOpenShell/issues/1031#issuecomment-719909379

**Comment by Moult** [comment]
So it turned out this is not really a bug in the add-on, luckily, but I've added new error logs so it becomes easier to figure out what the issue is.

The first issue was the lack of the `IfcProject/X` and spatial objects, like `IfcSite/School` and so on.

The second issue, about the `IfcReinforcingElement` is that `IfcReinforcingElement` is actually "abstract" in the IFC4 specification. This means you are not allowed to use that IFC class. You have to use a different class. I think you mentioned that you exported this element from Revit. If so, that means that Revit somehow allowed you to export an illegal class. The solution is to use a different class. The dropdown of IFC classes in the add-on are already filtered by non-abstract classes, so picking a class from there is a good way to go.

The third issue, where the site was exported in a different location to the walls was a bug that was fixed 4 days ago, I believe: https://github.com/IfcOpenShell/IfcOpenShell/commit/970f735b7693b11733a8aa70d0c100c6819761d9

So hopefully all good to go now! :)

**Comment by Nevermind3r88** [comment]
I'll try as you suggest :) thanks a lot!!!
