### ISSUE TITLE
Unable to set IfcLogical to UNKNOWN?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1086]
Am I missing something? Is there an `UNKNOWN` option, or did I mess something up?

```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> f.createIfcMaterialLayer(None, 1, True)
#1=IfcMaterialLayer($,1.,.T.,$,$,$,$)
>>> f.createIfcMaterialLayer(None, 1, False)
#2=IfcMaterialLayer($,1.,.F.,$,$,$,$)
>>> f.createIfcMaterialLayer(None, 1, None)
#3=IfcMaterialLayer($,1.,$,$,$,$,$)
>>> f.createIfcMaterialLayer(None, 1, "UNKNOWN")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/ifcopenshell/file.py", line 88, in create_entity
    e[idx] = arg
  File "/usr/lib/python3.7/site-packages/ifcopenshell/entity_instance.py", line 145, in __setitem__
    real_attr_type, self.is_a(), self.attribute_name(idx), value))
ValueError: Expected Bool for attribute IfcMaterialLayer.IsVentilated, got 'UNKNOWN'
```

**Comment by aothms** [comment]
Congratulations. Within 10 years you're the first to notice IfcOpenShell never implemented anything for Logical and simply silently mapped it to bool. The proper solution is to map it to boost.tribool in C++ and work from that. There are a couple of schema things that need to be addressed but for backwards compatibility it'll probably have to wait for 0.7

**Comment by Moult** [comment]
Maybe a quick solution would be to silently map it to enum?

**Comment by aothms** [comment]
Ok, my plan is the following:

I'm going to push back the 0.7.0 version branch we have now to 0.8.0 because it would take a long time for that to get stable.

We create a new 0.7.0 branch with a couple of (backwards incompatible or invasive) changes (but otherwise fairly stable):

* Logical -> boost tribool
* C++ Optional attribute access function to return boost::optional<> as opposed to hasName() etc.
* Link IfcOpenShell/svgfill into IfcConvert
* Caching of breps and triangulations using HDF5
* Fairly extensive restructuring and renaming mostly on the C++ side to get things finally a bit consistent (this would also allow users to wet their toes into the naming already used in current 0.7)
* More efficient inverse attribute mapping. Now we have a map `int -> int`, so the attribute index and entity type need to filtered later on and make this `(int, int, type) -> int`, so that the mapping can feed the inverse attribute function directly.
* Proper handling of inverse attributes on attribute reassignment (only deletion was recently fixed)

What else should be shoved into this?

**Comment by aothms** [comment]
And @Moult do you think we can do a simultaneous BlenderBIM alpha and IfcOpenShell v0.6 final release? Or are the timelines too different?

**Comment by Moult** [comment]
What did you have in mind for a simultaneous release? Given that the BlenderBIM Add-on is still in alpha, I still see frequent releases (i.e. every 2-3 weeks - in fact I plan to release tomorrow). My current plans are to fix as many bugs as possible after the refactor, and then attempt to fix some UX issues to make it easier to use (the refactor makes the workflow a little less fluid as actions need to be explicitly taken to reflect changes in the IFC), and then I'll be back to focusing on drawings.

**Comment by aothms** [comment]
> What did you have in mind for a simultaneous release?

Nothing much, the weight you give it would be up to you, but practically since we work in the same branch, it would also mean that we update the default branch on the repo and we would both be committing there. That kind of stuff.

**Comment by Moult** [comment]
Ah probably no need to stress about it too much whilst the BlenderBIM Add-on is still in alpha. When it is ready for beta, more weight can be given. Let me know when to make the switch :)

**Comment by Moult** [comment]
Just a quick comment to link this issue to #95.

**Comment by Moult** [comment]
```
>>> f.createIfcMaterialLayer(None, 1, "Unknown")
#3=IfcMaterialLayer($,1.,.U.,$,$,$,$)

>>> f.createIfcMaterialLayer(None, 1, "UNKNOWN")
#4=IfcMaterialLayer($,1.,.U.,$,$,$,$)
```

Woohoo! Closing as fixed!
