### ISSUE TITLE
BlenderBIM - IFC Nodes - 'IFC Get Attribute' not pulling value at a certain level

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1089]
IFC Get Attribute doesn't pull out value at a certain level. 

File: https://www.dropbox.com/s/z9dpag6f4ilm5dw/20201107%20-%20sv%20ifcwall_dumb%20wall%2002.blend?dl=1

![image](https://user-images.githubusercontent.com/507113/98454084-1fbebd80-2126-11eb-8e07-2e95b1079bbf.png)

**Comment by htlcnn** [comment]
I'm wondering how "Location" attribute of IfcLocalPlacement could be retrieved when it is relative placement. Could you show me the code @theoryshaw @Moult ?

**Comment by htlcnn** [comment]
@Moult @theoryshaw 
It took me a while to understand the code base of the node Ifc Get Attribute. I think these lines were the cause to improper operation:
- Firstly, `SvIfcGetAttribute.process()` calls to its parent's (SvIfcCore) `process()`
https://github.com/IfcOpenShell/IfcOpenShell/blob/877bf3207a120672fe1af89f068ab2e983f590ce/src/ifcsverchok/nodes/ifc/get_attribute.py#L24
- Secondly, `zip_longest_repeat` apply `list` function to all inputs. In the case that an entity_instance can be converted to list, it will become another data type. In the case of IfcCatersianPoint, it turns to a tuple, so a tuple can not be `get_info()` again. Exception raised.

I think it will be more explicit and match to Ifc data structure if we bash `zip_longest_repeat` and handle the nested inputs for this specific node instead of doing it generally in SvIfcCore. I propose a solution below:
```python
def process(self):
        self.sv_input_names = ["entity", "attribute_name"]
        self.value_out = []
        entity_nested_inputs = self.inputs["entity"].sv_get()
        attribute_name = self.inputs["attribute_name"].sv_get()[0][0]
        for entities in entity_nested_inputs:
            if hasattr(entities, "__iter__"):
                for entity in entities:
                    self.process_ifc(entity, attribute_name)
            else:
                self.process_ifc(entities, attribute_name)
        self.outputs["value"].sv_set(self.value_out)
```
This is the result:
![image](https://user-images.githubusercontent.com/931924/103145037-31a40080-4766-11eb-9de6-a501b46c285b.png)

If we're not expecting a list of attributes provided into `attribute` socket, I think this is ok.

**Comment by Moult** [comment]
This looks great @htlcnn ! If you send a PR I'll approve it!

**Comment by htlcnn** [comment]
@Moult sure https://github.com/IfcOpenShell/IfcOpenShell/pull/1212

**Comment by Moult** [comment]
Awesome! Closed bug! Thank you so much!
