### ISSUE TITLE
IfcOpenShell representation missing in IfcConvert output

### ISSUE THREAD

**Issue by arzezniczak** [IfcOpenShell/IfcOpenShell#109]
Hello.
I have some IFC file from DDS-CAD.
[bluberry_hvac.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/380864/bluberry_hvac.zip)
I'm using IfcConvert to output OBJ file. I found that there are missing IfcOpenShell entities in output OBJ file.
This is OBJ output: 
![obj](https://cloud.githubusercontent.com/assets/20474251/17092284/c9c7a9ee-5241-11e6-8505-3c9d639c8a47.png)
And this is the original IFC file opened in BIM Vision:
![ifc](https://cloud.githubusercontent.com/assets/20474251/17092364/60696a9a-5242-11e6-9d7c-479046522250.png)

In these snapshots I'm showing you only one missing element but there is more (some of them you can spot in background). Every of them (or at least all that I've checked) have IfcOpenShell 3d representation in IFC file.

**Comment by aothms** [comment]
Thanks for this report. The reason why some elements are not converted (there is not even an error or warning) is that they are not attempted since they are in a different representation context.

There are three in this file.

~~~
#4=IFCGEOMETRICREPRESENTATIONCONTEXT($,'model view',3,$,#11,$);
#5=IFCGEOMETRICREPRESENTATIONCONTEXT($,'detail view',3,$,#11,$);
#6=IFCGEOMETRICREPRESENTATIONCONTEXT($,'sketch view',3,$,#11,$);
~~~

While according to the standard [1]:

> The inherited attribute ContextType shall have one of the following recognized values: 'Sketch', 'Outline', 'Design', 'Detail', 'Model', 'Plan', 'NotDefined'.

[1] http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcrepresentationresource/lexical/ifcgeometricrepresentationcontext.htm

So, `'model view'`, `'detail view'` and `'sketch view'` are in fact invalid. IfcOpenShell knows about some versions of DDS-CAD emitting this `'model view'` ContextType and therefore the representations in this context are attempted. The elements you are referring to have representations in the `'detail view'` context.

With `'detail view'` added here [2] the file converts completely.

[2] https://github.com/aothms/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomIterator.h#L165 

![schermafdruk 2016-07-25 10 47 10](https://cloud.githubusercontent.com/assets/1096535/17095550/4b528782-5255-11e6-8179-81e21096d393.png)

Concluding, I consider this more of an issue with the file. This file is from 2009. Do you know the status of recent versions of DDS-CAD?

**Comment by arzezniczak** [comment]
Thank you for very fast and detailed reply.
Unfortunately I don't have access to recent versions of DDS-CAD.

**Comment by aothms** [comment]
Ok, well I added the additional representation type. Doesn't really hurt anyway.

**Comment by Stinkfist0** [comment]
Could maybe show a warning if unsupported/nonstandard representation context is encountered?

**Comment by aothms** [comment]
Sure!
