### ISSUE TITLE
Fatal error with empty items in attribute set

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1131]
This looks like an invalid IFC (coming from ArchiCAD), but do you reckon it should terminate the way it does? Or should it instead return `(None, None)`? Happy either way, just thought I'd bring it up.

```
>>> store.get_file().by_id(11392)
#11392=IfcMaterialProperties('Pset_MaterialThermal',$,($,$),#11377)

>>> e = store.get_file().by_id(11392)
>>> e.Properties
Traceback (most recent call last):
  File "/home/dion/drive/blender/blender-2.90.0-linux64/2.90/python/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 60, in __getattr__
    self.wrapped_data.get_argument(self.wrapped_data.get_argument_index(name)))
  File "/home/dion/.config/blender/2.90/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 1548, in get_argument
    return _ifcopenshell_wrapper.entity_instance_get_argument(self, *args)
RuntimeError: Unknown attribute type
```

**Comment by aothms** [comment]
Yeah sets cannot contain NULL. So the file is definitely invalid. The issue is that in C++ we don't have generic lists. The parser needs to know the type of the elements in the list to map to the appropriate type (e.g. std::vector<int>). So while I agree there are better solutions. And I think in the current code base it can be fixed as we have quite a bit more schema information now then at the time the parser was first written. Adding a try catch for this is surely painful though (but you've already done that ;))

**Comment by Moult** [comment]
Happy to close this as it seems to be a bit of work just to support what is simply invalid behaviour. If it starts cropping up more frequently from the major vendors, it might be worth reopening, but until then... :)
