### ISSUE TITLE
Attribute Error missing RelativePlacement

### ISSUE THREAD

**Issue by Teak02** [IfcOpenShell/IfcOpenShell#1133]
I get this ifc file but if I want to open it, this happens

Traceback (most recent call last):
  File "E:\Steam\SteamApps\common\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 134, in execute
    ifc_importer.execute()
  File "E:\Steam\SteamApps\common\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 416, in execute
    self.auto_set_workarounds()
  File "E:\Steam\SteamApps\common\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 503, in auto_set_workarounds
    if self.is_ifc_class_far_away("IfcSite"):
  File "E:\Steam\SteamApps\common\Blender\2.90\scripts\addons\blenderbim\bim\import_ifc.py", line 523, in is_ifc_class_far_away
    or not site.ObjectPlacement.RelativePlacement
  File "E:\Steam\SteamApps\common\Blender\2.90\scripts\addons\io_import_scene_ifc\ifcopenshell\ifcopenshell_wrapper.py", line 1590, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, entity_instance, name)
  File "E:\Steam\SteamApps\common\Blender\2.90\scripts\addons\io_import_scene_ifc\ifcopenshell\ifcopenshell_wrapper.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'entity_instance' object has no attribute 'RelativePlacement'

location: <unknown location>:-1

**Comment by Moult** [comment]
It is likely I've made the poor assumption that local placements are always used. Is it possible for you to share your IFC file so that I can confirm this? Feel free to share to dion@thinkmoult.com if it is private.

**Comment by aothms** [comment]
> site.ObjectPlacement.RelativePlacement

IfcOpenShell C++ also only has local placement implemented. Depending on version it can either be Grid Placement or Linear Placement.

**Comment by Moult** [comment]
I must say I'm curious, since I've never personally come across a file that uses grid or linear placements.

**Comment by Teak02** [comment]
@Moult I´ve send you an email to dion@thinkmoult.com. The file is 50mb big so I shared it for you on drive.

**Comment by Moult** [comment]
Are you sure you sent me the right file? I expected to find an IfcSite that didn't use local placement, but the IfcSite was using a local placement, and so I didn't get your error.

I did get another error though about invalid IfcGrids. Can you please ask your architects to check their Revit export IFC mapping settings and make sure they don't have strange categories exported as IfcGrid? In particular, they have a Revit family called "ZZZ_do not use_grating for Profiline" that is being incorrectly exported as a grid, which is invalid since there are no axes. I've added a workaround.

**Comment by Teak02** [comment]
Yeah, I´m sure it was the right file. It´s the first time I tried to import an ifc file and it´s the only one I got.

I try to import the file with the new version tomorrow. Thank you for your quick help. And I will also talk to the architects. I think they never export to ifc before.

**Comment by Moult** [comment]
@Teak02 cheers, you'll need to use the latest v0.6.0 branch to get the fix. Otherwise, you'll need to wait for the next release, which will probably be in 1 weeks time.

You can help point the architects to this page: https://wiki.osarch.org/index.php?title=Home_of_OSArch there are helpful guides on setting up Revit for IFC exports.

**Comment by Moult** [comment]
If it is tricky to get the latest branch and you can't wait for the next release, let me know and I'll just send you the imported Blend file. I assume you're using this for archviz?

**Comment by Teak02** [comment]
If u could send me the imported blend file it would be amazing. 

I use it in first place as a background for a building management system/Scada (Supervisory Control and Data Acquisition) . Usually I make more or less accurate models of buildings and render some images but this is a new building where we have the opportunity to use the BIM modell. 

Maybe we will use some cross sections to show the ventilation system and things like that.

**Comment by Moult** [comment]
@Teak02 cool - I've emailed you the file.
