### ISSUE TITLE
BlenderBIM: Crashing when printing a drawing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1148]
When printing a drawing with [this](https://www.dropbox.com/s/74d061mz78t7evq/20201206%20-%20Dimension_with_Walls.zip?dl=0) file, I get [this](https://www.dropbox.com/s/2w3jjbq71lb99rk/20201206%20-%20Dimension_with_Walls.mp4?dl=0) behavior

Blender: 2.91
BlenderBIM: 0.0.201115

**Comment by Moult** [comment]
Cannot reproduce in latest master. There will be a release today, so hopefully you can retry it?

**Comment by theoryshaw** [comment]
It works on 2.83 and 2.90, but not on 2.91 or 2.92.

**Comment by Moult** [comment]
Confirmed that this is a Windows-specific issue caused by upstream changes. Relevant links:

 - https://developer.blender.org/T57657
 - https://developer.blender.org/D7815
 - https://developer.blender.org/rB04c5471ceefb41c9e49bf7c86f07e9e7b8426bb3
 - https://blender.stackexchange.com/questions/8530/how-to-get-python-multiprocessing-module-working-on-windows/32779#32779

I have a few routes to proceed from here.

 1. Option 1 is to open an upstream bugreport and figure out how to get this working again.
 2. Option 2 is to detect if it's Windows and fall back to non-multiprocessing (probably useful as a stopgap measure)
 3. Option 3 is to ping @aothms and see if I can get this into a multicore C++ thing that I can call instead. This is the preferred longer term solution, and was proposed in the Epic games grant application. Maybe this is easy to do since the full functionality is not yet required... just the ability to perform an OCC BRepAlgoAPI.BRepAlgoAPI_Section call effectively. I'm happy to try and code this in C++ but I need a teacher since I don't know C++ but I'm happy to use this as a learning experience. Maybe it can be a stepping stone to me helping out on the C++ side of things too? Ping @aothms what are your thoughts on this - would you be available to help me do this? I will need hand-holding at the beginning but once I get going I think I can do most of my homework myself. This is pretty much the [main code](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/cut_ifc.py#L90-L138) to be migrated. If this is achieved, maybe PyOCC can also be purged from the BlenderBIM Add-on packaging, thus decreasing the filesize a lot?

**Comment by aothms** [comment]
> I'm happy to use this as a learning experience
> would you be available to help me do this?

I think that's a great idea.  Sure :) I'd say set up an dev environment, find a place to implement this, tinker a bit and then have a call.

There's probably a risk in implementing this in C++ in that on that side there is a risk that underlying shape data is reused between elements and mutating them concurrently might blow up. But that can be fixed later.

**Comment by Moult** [comment]
I have implemented option 2 as a stopgap to close the bug, whilst option 3 is perused as a longer term solution, which will take time.

@aothms cheers, I'll draw up what I think needs to be built and where and continue the discussion on #1153.
