### ISSUE TITLE
BlenderBIM: roundtrip wall and retain its 'screw' and 'solidify' modifiers. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1152]
Have a wall roundtrip and retain its 'screw' and 'solidify' modifiers. 

I know this is in the roadmap, just posting here for tracking.

**Comment by Moult** [comment]
Note to self that the best way to implement this is to first implement automatic Axis representation generation.

**Comment by Moult** [comment]
Note to self that the best way to implement automatic Axis representation generation is to first implement a standard for "object generators" as an extension to "dumb" IFC geometry.

**Comment by theoryshaw** [comment]
It seems, with the latest BlenderBIM [refactoring](https://github.com/IfcOpenShell/IfcOpenShell/issues/1222), and [gizmo](https://github.com/IfcOpenShell/IfcOpenShell/issues/1324) roadmap, that recreating Blender modifiers, upon import, is not that important anymore. Is that a correct perception, or do you think it's still a good idea to use these modifiers still?

**Comment by Moult** [comment]
Hmm, no it is still important. IFC supports parametric modelling, yes, but only to an extent. There are many things that Blender can do parametrically that IFC is not able to do. We shouldn't let IFC hold users back to using cool software tricks. IFC should be seen as a baseline and foundation, but we should also be able to build on top of it. If we want to build Acme Blender Stair Generator Pro 2.0 which uses Computational Artificial Intelligent Generative Evolutionary Buzzword Bingo, we should be able to.

The solution, is to not only support all of the baseline parametrics that IFC does - which is the purpose of the gizmo roadmap - but also to support the concept of what I've decided to call an "Object Generator". An object generator is an object that stores a little identifier about the generator and whatever it needs in IFC alongside the IFC geometry, but then the original app that understands that flavour of generator can reliably parse the IFC object and convert it into an "Object Generator" object. An example of this which already occurs is Revit Walls. Due to a number of undocumented special rules in the IFC, Revit can detect walls that were originally created in Revit, and turn them from extruded area solid profiles (which they actually are in IFC) into Revit walls which have a start/end handle that you can drag. Same story with Revit slabs. It is simply a matter of documenting the special rules that make a Revit wall a Revit wall, and storing a little "identifier" that says "btw, Mr. Authoring App, you could if you wanted to adhere to these rules, offer users a special way of manipulating me". These object generators could be either be special to a single app (e.g. if you are building the Beijing Water Cube Proprietary Steel Lattice Generator), or agnostic (e.g. Revit Walls are pretty common, and we should be able to recreate functions to edit them in Blender / FreeCAD).

Hope this kinda makes sense.

So much to do, 24 hours in a day.

**Comment by Moult** [comment]
To give credit where credit is due, @fbpyr has done a good amount of work in determining the undocumented rules that Revit uses to generate objects as native objects. I suspect Revit Object Generators will be one of the first that I plan to support, simply due to the monopoly of Revit files that users need to deal with.

**Comment by Moult** [comment]
Closing bug, as new parametric engine makes this obsolete. Dumb walls (which happen to include most standard case walls from any IFC software) now can be manipulated.
