### ISSUE TITLE
Development and building under Linux

### ISSUE THREAD

**Issue by jibasig** [IfcOpenShell/IfcOpenShell#1257]
Hello, I am new to the project and I am interested in the typical development workflow under Linux. 
I am currently working in Visual Studio Code and build with the build-Script in the "nix"-Folder. Building on my hardware takes about 2 hours. Am I doing something wrong? Can I somehow do incremental builds to speed this up? What am I missing to get a more productive development workflow?
How is your development environment setup?
@ysangkok @dleverton @Moult Maybe you can give a hint?

**Comment by aothms** [comment]
That's a very good question that we indeed need to document (or better facilitate). This is exactly the difference between the win build script and the nix one. The win build script generates a MSVC solution file predominantly for development, the nix build script builds the full matrix for publishing on the website. The long term aim is for these two scripts to converge, but so far it has not happened.

The first thing to realize for now, is that the nix build script will get you a ./build/ subdirectory where there is probably something like a `./build/x86_64/build/ifcopenshell/executables/build` directory. In this folder is a Makefile and you can just navigate to this directory to do a `make`/`make install`/`make -j8` after editing files in the `./src/` directory. Opposed to the build script (which will `rm -rf` the directory and always start with a fresh build) this will use `make`'s wisdom to decide what to rebuild.

I think the long term aim should be to have a development option:
* ability to target system python or interpreter of choice, instead of a full python version matrix
* ability specify cmake generator
* make sure the cmake generator output is easily discoverable and includes IfcConvert as well as IfcOpenShell-Python

Using the `BUILD_CFG` environment variable you can already switch on `-g` and `-O` levels using CMake's options Debug|RelWithDebInfo|Release (I typically use the middle option (default), but it may be that for Linux/gcc) another option gives you a more ergonomic development experience.

**Comment by jibasig** [comment]
Hello @aothms , I can't express how much you helped me!
I just tried it out and it worked within seconds. Thank you very much, I think I can go on from here!
If there will be more questions about build I will just comment here.

**Comment by jibasig** [comment]
I got one more question. I set BUILD_CFG=Release
using
`export BUILD_CFG=Release`
 before 
`make && make install && make -j8`
But still cmake will build the big binary for IfcConvert (575,3 MB) I think this is the debug-Version. If I call the long running nix/build-all.py with this environment variable set, I get the release-Version of IfcConvert (ca 41MB).
What am I doing wrong here?

**Comment by jibasig** [comment]
@aothms There is another question. Currently, if I build IfcConvert it uses the boost library as a shared library. How can I link it static into IfcConvert?

**Comment by aothms** [comment]
> big binary for IfcConvert (575,3 MB) 

The nix build script does install/strip if cfg=Release https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/nix/build-all.py#L724

> boost library as a shared library

It shouldn't. Is that really in the output of e.g. `ldd IfcConvert`? Can you double check here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/nix/build-all.py#L648 ? Otherwise it's probably CMake that picks up some system wide boost lib instead of the one from the build script.

What are the messages from the cmake script? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/cmake/CMakeLists.txt#L173 You should have a log in (all output from commands) in `./build/x86_64/logs/...`

**Comment by jibasig** [comment]
Good morning,
I tried the build from the build-folder with the cfg=Release flag set, but still the big binary gets build. Somehow it seems that this env. variable is ignored.

If I build the small binary from the nix folder with BUILD_CFG=Release, ldd will show me the following output for ldd
`	linux-vdso.so.1 (0x00007ffde9581000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f52bac40000)
	libboost_program_options.so.1.71.0 => /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.71.0 (0x00007f52babb1000)
	libboost_regex.so.1.71.0 => /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.71.0 (0x00007f52baab1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f52ba8d0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f52ba781000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f52ba766000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f52ba572000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f52bd50a000)
	libicui18n.so.66 => /usr/lib/x86_64-linux-gnu/libicui18n.so.66 (0x00007f52ba273000)
	libicuuc.so.66 => /usr/lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007f52ba08d000)
	libicudata.so.66 => /usr/lib/x86_64-linux-gnu/libicudata.so.66 (0x00007f52b85cc000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f52b85c6000)
`
So the system library of boost and other dependencies is used instead of static linking. Is there any way to force the static linking even if I have to edit the build-script?
I have attached the log output of my build at this comment.
[20210114.log](https://github.com/IfcOpenShell/IfcOpenShell/files/5834449/20210114.log)

**Comment by aothms** [comment]
> but still the big binary gets build

yes, you need to explicitly call `make install/strip` or run the `strip` executable yourself on your exe.

> /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.71.0

Hm, yes I really struggle sometimes with CMake (don't wel all....) I explictly set the boost_root https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/nix/build-all.py#L682 so I think cmake should respect that.

> if I have to edit the build-script?

It'd be interesting to add a -DBoost_DEBUG=On maybe to see why it comes to that conclusion. 

From browsing on the internet it also appears this user is having the same issue and he advises changing `cmake_minium_required(VERSION)` to 3.12. Maybe that's something to try. https://stackoverflow.com/a/54524707/1556435 Be sure to clean the cmake cache (rm CMakeCache.txt) or run the build script (as it will wipe the entire directory) as cmake caching is another layer of hard to debug issues.

**Comment by Moult** [comment]
@jibasig ping, did the resolution work for you?

**Comment by jibasig** [comment]
> @jibasig ping, did the resolution work for you?
Yes, it worked for me. Thank you!
