### ISSUE TITLE
Build errors - might be boost version?

### ISSUE THREAD

**Issue by theliam** [IfcOpenShell/IfcOpenShell#1260]
Building this from scratch in Ubuntu 18.04 with CFLAGS=-O3 CXXFLAGS=-O3 BUILD_CFG=Release python build-all.py

It says it finds the boost libraries, then has several warnings about boost version having incorrect or missing dependancies.

Then a few thousand lines of warnings and notes then some undefined references to do with boost program options.

`IfcConvert.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i]+0x3b): undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'`

I have the whole build log here - https://pastebin.pl/view/bccf4227

Any insight?

**Comment by aothms** [comment]
One thing that immediate comes to mind is:

```
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
```

Maybe try upgrading CMake.

But I think the issue seems to be related to `std::__cxx11::basic_string`. This is probably related to the `_GLIBCXX_USE_CXX11_ABI` flag. https://stackoverflow.com/questions/45417707/glibcxx-use-cxx11-abi-gcc-4-8-and-abi-compatibility Which I guess you can try to set or unset. A newer distro/gcc/stdlib would solve this out of the box where the entire system is C++11 (there were some breaking changes in the C++ std::string in C++11 which causes this issue)

**Comment by theliam** [comment]
I did a release upgrade to Ubuntu 20.4. gcc / g++ are 9.3 and cmake is now 3.16.3 
Still getting the undefined references to do with C++11
I tried setting _GLIBCXX_USE_CXX11_ABI in the cmake_args but get this warning
`CMake Warning:
  Manually-specified variables were not used by the project:

    BOOST_ROOT
    _GLIBCXX_USE_CXX11_ABI`

Where should I set this in build-all.py? I also tried setting --std=c++11 but didn't seem to have any effect.
Alternatively, can you recommend an environment?

**Comment by aothms** [comment]
> Manually-specified variables were not used by the project: BOOST_ROOT

That is also interesting. Perhaps there is something else going on then duplicate to the #1257 issue on linking to system boost.

In CMake you'd need to add

`add_definitions(-D_GLIBCXX_USE_CXX11_ABI=1)`

or

`add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)`

but it seems as if the issue is related to BOOST_ROOT not being respected.

It appears that this is related to some change in cmake and boost after 1.70 https://cmake.org/cmake/help/v3.15/module/FindBoost.html#boost-cmake But I really don't comprehend what is written there.  Maybe -DBoost_NO_BOOST_CMAKE=On magically solves everything?

**Comment by theliam** [comment]
So before your response I got it built but it wouldn't link boost statically. It was referencing some .so files from /usr/lib/ rather than the build directory. So I removed the package manager version with 
`apt-get remove libboost-all-dev && apt purge && && apt autoremove`

I put -DBoost_NO_BOOST_CMAKE=On and now links properly with the static boost libraries but now the executable is linking to a higher version of glibc than I have on my server where I run this.

The vm I built this on is now ubuntu 20.4 but the server is 18.4 and a release upgrade isn't an option. Is there a quick fix for this or will I need to get it built on one with the same version?

**Comment by aothms** [comment]
> Is there a quick fix for this or will I need to get it built on one with the same version?

Not that I know, these kind of threads confirm that https://stackoverflow.com/questions/4032373/linking-against-an-old-version-of-libc-to-provide-greater-application-coverage

> The vm I built this on is now ubuntu 20.4 but the server

Yes that was my recommendation I guess. Can you just revert to an older snapshot or boot up a new VM? It doesn't seem the fix is related to that?

> I put -DBoost_NO_BOOST_CMAKE=On and now links properly with the static boost libraries

So to confirm, this is the fix that worked after all. Can you add it to the nix build script then?

**Comment by theliam** [comment]
Ok thanks, you reminded me I did back it up before upgrading to 20 and the build worked and I ran a test conversion fine.

Yeah with the package mangager version gone it was giving errors about not finding the cmake files until I added that.

I've created a pull request that adds the flag to build-all.py
