### ISSUE TITLE
BIMTester, use quotes in step strings or not?

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#1266]
ATM bimtester step strings do use a mix of quoted and no quotes even in one module. See https://github.com/IfcOpenShell/IfcOpenShell/blob/45bba127ff56/src/ifcbimtester/bimtester/features/steps/ifcdata.py#L13 and https://github.com/IfcOpenShell/IfcOpenShell/blob/45bba127ff56/src/ifcbimtester/bimtester/features/steps/ifcdata.py#L45 Same module, similar context (both about schema). One uses quotes and one not. 

IMHO we should only use one of them in all step definitions if possible. Since behave does the filtering AFAIK the quotes are not needed.

What do others think?

@Moult, @rbertucat, @ihabelaghoury

**Comment by berndhahnebach** [comment]
any opinions on this?

**Comment by rbertucat** [comment]
I think it would make sense to use single quote everywhere as it is in the behave documentation: https://behave.readthedocs.io/en/stable/tutorial.html

**Comment by Moult** [comment]
@rbertucat you mean double quotes? Like: `"`

The advantage of quotes is that it removes ambiguity to human readers on what is a human-decided variable and what is part of the definition. Given that we are using BIMTester in contracts, this sounds like an important benefit because then it is clear to people what is defined for the project and what is part of the contractual template.

Let's go for quotes everywhere.

**Comment by berndhahnebach** [comment]
OK.
