### ISSUE TITLE
Cannot readd an element to another file twice, and removal causes segfault

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1272]
Hopefully the code example explains the situation :)

```
import ifcopenshell

f = ifcopenshell.file()
g = ifcopenshell.file()

w = f.createIfcWall(ifcopenshell.guid.new())

w2 = g.add(w)
g.remove(w2)

w3 = g.add(w)
print(w3) # This returns #1=IfcWall('1R6cuJYeL0$A0sUVac$JSy',$,$,$,$,$,$,$,$) which seems like the operation succeeded
print(len([e for e in g])) # this turns up zero suggesting the operation failed?
g.remove(w3) # Produces error
```

```
Traceback (most recent call last):
  File "/Text", line 13, in <module>
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/file.py", line 181, in remove
    return self.wrapped_data.remove(inst.wrapped_data)
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 1489, in remove
    return _ifcopenshell_wrapper.file_remove(self, entity)
RuntimeError: Instance #1 not found
```

**Comment by Moult** [comment]
In terms of the usecase for this, I'm adding elements to the IFC file (the project) from another IFC file (a project library). In this case, a classification. So if the user adds the classification from the library, then removes it, then changes his mind and wants to add it again...

**Comment by aothms** [comment]
Yes, good one, 37fe54d2476d9cf3e74998f533035c68cb30eb3f fixes this case at least. This is a job for `std::weak_ptr`, maybe we should go back to shared_ptr for all entity instances.

**Comment by Moult** [comment]
@aothms fantastic! Thanks for the quick response! I'll test and close when the bot awakens!

**Comment by Moult** [comment]
Closing bug as fixed :) I don't know the meaning weak_ptr and shared_ptr but thought I'd mention it in this comment, in case it has any relevance to any plans in v0.7.0.

**Comment by aothms** [comment]
> the meaning weak_ptr and shared_ptr

shared_ptr and weak_ptr are both smart pointers. A shared pointer does automatic memory management. By means of a reference counter it counts how many references to the object exist and when this reaches 0 it deterministically knows the object can be deleted. So no manual `delete` anymore. A weak_ptr can be created from a shared_ptr, but it doesn't increase the reference count, so whenever accessing the object through a weak_ptr a test happens whether the object is still alive. This would have solved our issue, but would have changed the majority of APIs. That's why in 0.7 we added a bit of information (the auto incrementing id) in the actual object itself.
