### ISSUE TITLE
Drawing creation error

### ISSUE THREAD

**Issue by Jjavier1475** [IfcOpenShell/IfcOpenShell#1280]
Working with version 2.93 it is not possible to create the drawing, the application crashes and does not open any browser, I tested it with version 2.91 and the result is the same, I thought it could be due to the amount of information but when testing with only one cube the result is the same

**Comment by Moult** [comment]
@Jjavier1475 this was fixed as part of #1148 - you can apply just that patch if you are using the old version. Else, you could upgrade, but drawings are in a bit of a limbo state right now due to a bunch of work being prepped for #1153. Sorry - not much I can offer other than "really sorry but drawing generation is really unstable right now".
