### ISSUE TITLE
Missing fcl dependency for Blender 2.93 alpha (python 3.9)

### ISSUE THREAD

**Issue by ecke101** [IfcOpenShell/IfcOpenShell#1357]
Blender has upgraded to Python 3.9 and now it says ifcopenshell is not built for that version. Not sure if this is an easy fix or not. Would it be possible for me to build ifcopenshell myself for 3.9 just by editing some config file or so?

**Comment by aothms** [comment]
Inside the folder of the installed addin you can simply replace the ifcopenshell folder with the appropriate one downloaded at http://ifcopenshell.org/python

**Comment by ecke101** [comment]
I tried that now but now it says it can't find OCC.Core when I try the load the addon.

**Comment by Moult** [comment]
Just to track progress on this there are now builds available on https://blenderbim.org/builds/

I've migrated:

 - PythonOCC 0.17.3 to PythonOCC 7.4.1
 - OCE 0.17.2 to OCCT 7.4.0
 - tbb 2019.5 to tbb 2020.2

I have not yet migrating fcl, so it is likely that IfcClash is totally broken.

I noticed crashtastic behaviour - some IFC files would load, some wouldn't and would crash. It is clearly crashing at some point in the import process, but @ecke101 are you able to help troubleshoot whether or not this is due to a Blender operation causing the crash (e.g. because it is an alpha Blender build), or if it is an IfcOpenShell/PythonOCC/OCCT call causing the crash?

@aothms is there anything I should know about the migration for PythonOCC versions and OCE->OCCT? Is one more stable than the other? Is one much more outdated than the other, or is it simply a different version numbering scheme due to one being upstream and another being community?

**Comment by Moult** [comment]
Posted comment for fcl: https://github.com/BerkeleyAutomation/python-fcl/issues/17

**Comment by aothms** [comment]
> is there anything I should know about the migration for PythonOCC versions and OCE->OCCT? Is one more stable than the other? Is one much more outdated than the other, or is it simply a different version numbering scheme due to one being upstream and another being community?

OCE is basically stuck at OCCT 6.9, The latest PythonOCC is back on track with wrapping 7.4, so that's one major and several minor versions worth of improvements. 7.4 is not my favourite OCCT, I find 7.3 and 7.5 more stable.

But if it's during the import process, are you actually using PythonOCC? Isn't it IfcOpenShell's statically linked OCCT version (7.3p3) at work? Is it some sort of DLL hell symbol problem, that if you don't import PythonOCC the import runs fine?

**Comment by Moult** [comment]
@aothms ahh, sorry this shows my complete ignorance for how the C++ stuff works! Yes, you're right - the import process does not use any OCC classes, it uses ifcopenshell only, and so this must be unrelated to OCC.

I think it's just me - others have not been able to replicate this issue and it isn't crashy for them. Maybe I was just unlucky with the alpha Blender build I got.

Hopefully once the new drawings system is in place, I can drop bundling OCC, since that's the only thing it's used for.

I'll consider this issue solved except for fcl, unless someone else can replicate crashy behaviour.

**Comment by CyrilWaechter** [comment]
Main fcl repo is dead. See https://github.com/IfcOpenShell/IfcOpenShell/issues/919

**Comment by Moult** [comment]
New attempt to resolve this by migrating to hpp-fcl here: https://github.com/humanoid-path-planner/hpp-fcl/issues/235

**Comment by Moult** [comment]
Just for the record @CyrilWaechter has managed to build binaries! https://github.com/CyrilWaechter/python-fcl/releases/tag/v0.6.1 - will be excited to test soon!

**Comment by Moult** [comment]
@CyrilWaechter I got this from Linux trying out py39. Ideas?

```
>>> import fcl
Traceback (most recent call last):
  File "/home/dion/drive/blender/blender-2.93/2.93/python/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/2.93/scripts/addons/blenderbim/libs/site/packages/fcl/__init__.py", line 2, in <module>
    from .fcl import (
ImportError: liboctomap-41bf7e95.so.1.8.0: cannot open shared object file: No such file or directory

```

**Comment by CyrilWaechter** [comment]
On windows it looks like we need a specific version of numpy… Is numpy packaged with Blender ? Which version ?
See: 
* [ValueError: numpy.ndarray size changed, may indicate binary incompatibility](https://stackoverflow.com/questions/65974718/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility)
* [ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp)

On Linux liboctomap is shipped in the wheel so it should not be missing. Did you use `pip` to install it ?

**Comment by Moult** [comment]
Yes, numpy is packaged with Blender, no idea which version. As discussed in chat I forgot to copy over the fcl-libs, and then hit another error.

Also for the record, I have found out that hpp-fcl has implemented clearance checks, which is vital for clash detection, whereas vanilla fcl has not.

A heads up that I have just implemented a much simpler version of IfcClash based on hpp-fcl to do the narrowphase collisions and aabbtree to do the broadphase collisions here: https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcclash/ifcclash - hpp-fcl's broadphase functions haven't yet reimplemented, which is why I am using aabbtree instead, as recommended by the hpp-fcl devs as a stopgap solution.

Although it works, there are a  couple issues I am facing:

 1. "Touching" contacts (i.e. shapes that touch but do not truly protrude / intersect) are considered as collisions. I haven't yet worked out how to exclude these. I will follow up with the hpp-fcl devs.
 2. It does not scale. Testing on the duplex MEP models worked well. However, an attempt on a larger-scale project (200mb of IFC) had my computer running for an hour and still stuck at the broadphase stage.

I will do more tests, but I think IfcClash shouldn't be a Python utility. My initial tests show that after the iterator finishes its job, running a single core to take those python lists of verts and faces and create hpp-fcl collision objects one by one and setup the aabbtree took about 30 minutes, and then the Python aabbtree-based broadphase took another 30 minutes before I gave up and it hadn't finished. In other words, I didn't even get to the C++ clashing stuff - the slow stuff was all in Python, looping one by one on a single core. I see no reason why it can't be multicore, as it is simply creating objects which no dependency to one another. Also, I reckon when I do get to the C++ narrowphase clash, it'll still be super slow, since again I'm looping one object at a time.

Maybe it is time to take the plunge and learn C++? Ping @aothms

**Comment by aothms** [comment]
Any reason why you're not using ifcopenshell.geom.tree instead of a python-based aabb tree? tree has a `select_box()` method that does only bbox-bbox interference. I think the graph here is seconds over number of elements for building the tree https://github.com/IfcOpenShell/IfcOpenShell/pull/130 but it's a bit embarrassing that it isn't printed.

> "Touching" contacts

Yes that's the tough part. If you just stay in OCCT this is solved pretty well using tolerances and oriented solids. OCCT has tri state logic for this, IN, OUT, but also ON using a configurable tolerance. But performance would also be quite bad (but still linear in number of pairs from the bbox-bbox intersection). Perhaps you can experiment a bit with https://dev.opencascade.org/doc/refman/html/class_b_rep_extrema___dist_shape_shape.html BRepExtrema_DistShapeShape or even better BRepExtrema_ShapeProximity https://dev.opencascade.org/doc/refman/html/class_b_rep_extrema___shape_proximity.html (I think this one is new I haven't seen it before)

> Tool class for shape proximity detection. For two given shapes and given tolerance (offset from the mesh) the algorithm allows to determine whether or not they are overlapped. The algorithm input consists of any shapes which can be decomposed into individual faces (used as basic shape elements). High performance is achieved through the use of existing triangulation of faces. So poly triangulation (with the desired deflection) should already be built. Note that solution is approximate (and corresponds to the deflection used for triangulation). 

> https://dev.opencascade.org/doc/refman/html/class_b_rep_extrema___shape_proximity.html

Postprocessing fcl output with a naive vertex-face distance check unfortunately doesn't help you. As it cannot distinguish these two cases (both have small vertex-face distance in red). So I think this has to be something implemented in the fcl library, or you need more information on intersecting primitives. If you have the intersection point and related surface normals (green), you might be able to find the furthest protruding point orthogonal to the surface normal.

![afbeelding](https://user-images.githubusercontent.com/1096535/127765333-55a4fcfd-3376-4340-91e2-23533b64f5a6.png)

But even then there are difficult cases like below

![afbeelding](https://user-images.githubusercontent.com/1096535/127765434-a786aace-c2fe-4028-a707-45cd48f84a6d.png)

I haven't given this much thought, but I think I recall there are papers on how to classify mesh-mesh (possibly open even) intersections. But like I said I think this has to come from the library itself, it probably has some convex decompositions or sth that makes this simpler.

**Comment by Moult** [comment]
> Any reason why you're not using ifcopenshell.geom.tree instead of a python-based aabb tree?

Because I didn't know it existed :)

Let me try rewrite it with `ifcopenshell.geom.tree` and see what happens!

Also, wow, #130 considered FCL back in 2017!

**Comment by Moult** [comment]
@aothms I had a quick peek at `ifcopenshell.geom.tree` and had a few questions - I've commented on the various uncertainties below :)

```
f = ifcopenshell.open('1.ifc')
tree = ifcopenshell.geom.tree(f) # Creates a tree from all elements in the file, I think

# But usually we only want a subset... let's try this
tree = ifcopenshell.geom.tree()
it = ifcopenshell.geom.iterator(ifcopenshell.geom.settings(), f)
it.initialize() # Is this needed?
tree.add_iterator(it) # Uh oh, segfault.

# Assuming that's solved, I think it kinda goes like this - here's a typical scenario where we clash between two separate IFCs
f2 = ifcopenshell.open('2.ifc')
tree = ifcopenshell.geom.tree()
tree.add_file(f, ifcopenshell.geom.settings()) # This seems to work? But no way to pass include/include in iterator?
tree.add_file(f2, ifcopenshell.geom.settings())

# Let's attempt to clash an element. I think this is a detailed selection?
e = f.by_id(148)
tree.select(e)
# But I think we don't want to use that, we want to use select_box which is essentially our broadphase collision filter
results = tree.select_box(e)

print(results[0].wrapped_data.file) # Hmm, no way to tell which file it originally came from?

# So, now we've done our broadphase, let's move to narrowphase
for result in results:
    magic_clash_function_maybe_hppfcl_maybe_occ(e, result) # uh oh, we've lost our "shape.geometry.{verts,faces}". How do we clash?
```

**Comment by aothms** [comment]
> Is this needed?

No, called in add_iterator() https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomTree.h#L306

> Uh oh, segfault.

Yeah this is brittle. The settings need to match the settings here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomTree.h#L296 In particular DISABLE_TRIANGULATION because we need an opencascade compound for the tree.

> But no way to pass include/include in iterator?

No you need to use add_iterator() consider comments above

> we want to use select_box

yes, there are three modes: bounding box / distance / boolean intersection. but let's stick to select_box() for now.

> Hmm, no way to tell which file it originally came from?

That's true, I've also been bitten by this. I just create a mapping now like below and pray that there are not duplicate ids (actually I typically use very narrow type selections like IfcSpace, so it's bit less risky then this, but still)

```
id_to_inst = {}
for f in files:
  for x in f.by_type("IfcBuildingElement"):
    id_to_inst[x.id()] is x
```

> uh oh, we've lost our "shape.geometry.{verts,faces}". How do we clash?

Yes this should be solvable, but for now maybe just iterate twice... If you end up using this we'll adapt this to your needs.

**Comment by Moult** [comment]
@aothms the new results with `ifcopenshell.geom.tree` are far superior to aabbtree :) Testing on a particularly nasty file where everything down to the washers are modeled as separate objects, I was able to perform a clash detection in 23 minutes, of which 13 of those minutes were from iterating twice, so 10 minutes for a nasty file is very acceptable performance to me :)

Here's the code with the second iteration hack:

https://github.com/IfcOpenShell/IfcOpenShell/blob/557f8e6d69cc0061015551d16f5b245b4faae77c/src/ifcclash/ifcclash/collider.py#L18-L31

... how would you propose to fix it?

**Comment by Moult** [comment]
A heads up that we are getting closer to closing this bug - I've just repackaged the new hppfcl based IfcClash, and in doing so, we now also have MacOS support (in theory, I haven't actually tested it though, need to find a Mac machine!). Also the results seem to be quite a bit more reliable than the previous version (which had the most horrific "is_optimistic" variable used when checking clashes).

@aothms the hppfcl guys got back and agreed that it might require a post process on the results to weed out touching contacts. I'm going to ignore the problem for now until it returns, but your suggestion on using OCC sounds good. The problem of course, is that we don't ship OCC anymore which is holding me from trying it out :)

I think once there is a solution to prevent the double iterator, this can be closed as "good enough for now".

**Comment by CyrilWaechter** [comment]
> Yes, numpy is packaged with Blender, no idea which version. As discussed in chat I forgot to copy over the fcl-libs, and then hit another error.

Blender's numpy is `1.19.5`. There was a C ABI change between numpy `1.19.5` and `1.21.1`. I found no way to compile `python-fcl` for `python 3.9` using `numpy 1.19.5`. I get the same error when compiling using `1.19.5`... (`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

But anyway now that I see that time spent was useless for blenderbim project… At least it works outside of Blender if anyone needs it…

**Comment by Moult** [comment]
@aothms in the old version, is `self.tree.add_iterator(iterator)` adding breps to the tree using all cores? If so, does this mean that if we use `while True: self.tree.add(it.get_native()) ...` then adding breps will be done one at a time and therefore significantly slower?

If this isn't a concern, happy to try it out :) I guess `self.tree.add()` is the new feature that needs to be added?

@CyrilWaechter sorry that it didn't work out, but I really appreciate your efforts trying! And yes, hopefully someone will find it useful, especially now that nobody is maintaining python-fcl.

**Comment by aothms** [comment]
> adding breps to the tree using all cores

I hadn't considered that at all, but no it's not really the case the multiprocessing happens as black box inside the iterator it doesn't affect usage in the tree.

> is the new feature that needs to be added?

Yes, but not really, just making sure that it's properly exposed.

**Comment by Moult** [comment]
@aothms cool :) Is it by any chance an easy C++ task? I recently updated my system so I'm now able to compile IfcOpenShell :)

**Comment by aothms** [comment]
@Moult woops sorry missed that comment. that's good news. I already went through it. maybe the "good first issue" ones are nicer, self contained tasks. this one wasn't hard but required a bit of prior knowledge on how the header file and swig interrelate. https://github.com/IfcOpenShell/IfcOpenShell/commit/0087fa875bb3908d2080ce1aff0be4fc6bebe903

**Comment by aothms** [comment]
Edit: the following script now worked for me:

```
import ifcopenshell
import ifcopenshell.geom

f = ifcopenshell.open(r"files\nibs\d.ifc")
st = ifcopenshell.geom.settings()
it = ifcopenshell.geom.iterator(st, f)
assert it.initialize()
tree = ifcopenshell.geom.tree()
while True:
  elem = it.get_native()
  print(elem)
  tree.add_element(elem)
  shape = it.get()
  print(shape.geometry.faces)
  if not it.next():
      break
```

**Comment by Moult** [comment]
Confirming that it works and performance seems to be pretty awesome still :) Thanks so much!
