### ISSUE TITLE
IfcPatch doesn't extract elements inside an IfcElementAssembly

### ISSUE THREAD

**Issue by ecke101** [IfcOpenShell/IfcOpenShell#1388]
I'm trying to extract all IfcBeam-elements from an IFC where they all reside in an IfcElementAssembly.
I get the IfcElementAssembly-elements but they are all empty.

The command I ran is:
`ifcpatch -i myifc.ifc -o out.ifc -r ExtractElements -a ".IfcElementAssembly | .IfcBeam"`

This is the tree of out.ifc:
![bild](https://user-images.githubusercontent.com/249736/111230097-51212b80-85e7-11eb-99b9-c41f93f2545b.png)

This is the tree if myifc.ifc:
![bild](https://user-images.githubusercontent.com/249736/111229794-d7893d80-85e6-11eb-99cd-a1449e3a0d77.png)

**Comment by aothms** [comment]
This is one of the trickier things in IFC, knowing where one "object" begins and the next one ends. I think it makes sense to hardcode this for IfcElementAssembly specifically to follow the IsDecomposedBy relationship. So similarly to how there is a recursive `add_spatial_tree()` and how openings are traversed.

Instead of looking at the 'parent' IfcElementAssembly it makes sense in addition to look at the 'children', so that if an element contains IfcBuildingElementParts that they are also followed. Is this something you'd like to contribute?

**Comment by ecke101** [comment]
@Moult has started looking into this. Maybe he can get some ideas from your input.

**Comment by Moult** [comment]
Hopefully that helps - I'm not 100% convinced it's the right behaviour (for now you still need to explicitly tell it to include element assemblies), but time will tell as this gets battle tested in more real life scenarios. @aothms is right its a bit blurred.
