### ISSUE TITLE
Support apple silicon (M1)

### ISSUE THREAD

**Issue by xydian** [IfcOpenShell/IfcOpenShell#1402]
Hi, 

is there any support planned for the M1 processor of apple? At the moment i can't use this library on M1 as there is an error that the platform is not supported

Thanks in advance!

**Comment by aothms** [comment]
At this moment I don't think there are plans. These kind of things often depend on individual contributors. Even the major modules such as numpy don't have excellent support it seems https://github.com/numpy/numpy/issues/17964 I personally don't own an M1 machine so don't have the means to test things.

If you're interested in contributing support for this I'd be happy to advise. In our case we need to setup cross-compiling so that our x86_64 mac build machine can output ARM64 instructions for M1. 

You can also just try to run the build script on your machine ./nix/build-all.py and see if it works. If you have installed XCode Developer Tools there is a good chance it'll work.

**Comment by xydian** [comment]
alright, thanks for the fast reply!

**Comment by twisker** [comment]
I tried to run the build script today. failed on the first step.  it seems the hdf5-1.8.22.tar.gz was incomplete.  Anyway, I attacked the log file and the screenshot.  anyone can help?  thanks
![截屏2021-09-26 上午1 44 32](https://user-images.githubusercontent.com/16277077/134781101-775e21ed-aaf5-416a-97f1-d232f2259ef8.png)
[hdf5.log](https://github.com/IfcOpenShell/IfcOpenShell/files/7230136/hdf5.log)

.

**Comment by aothms** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/issues/1702#issuecomment-927591713

**Comment by Moult** [comment]
@xydian  hey there! Great news! We're doing a fundraiser to try and raise 70USD per month (unfortunately yes, a recurring payment, not a one-off) to afford an Apple M1 buildserver which will provide regular builds for Apple M1 devices! If you're still keen, perhaps you can help us out maybe for the price of a cup of coffee or two per month?

Details are here: https://opencollective.com/opensourcebim/projects/apple-m1-build-server - looking forward to when we can provide this with your help!
