### ISSUE TITLE
Request for functionality: Option to include empty floors in SVG

### ISSUE THREAD

**Issue by motjokk** [IfcOpenShell/IfcOpenShell#1407]
Hi,

Regarding IfcConvert

This would be very useful when merging multiple disciplines.  

Top floors are often not included, because the "cut-height" is set too high (as it needs to be for other floors).

**Comment by aothms** [comment]
Can you elaborate on this workflow? Do you use --bounds or --scale when converting? How do you ensure the SVGs from different inputs align? I think only without --bounds or --scale this would work but means you end up with a SVG in meter units which is not really suitable for display on screen.

Another option is to use the brand new `--svg-project` so that you also get a projection of the elements under the cut height.

**Comment by motjokk** [comment]
The idea here is to combine two (or more) floorplans generated by IfcConvert. I use --bounds here, because I`m displaying this in a plane SVG js viewer. 

I will try the --svg-project. Sounds like this could work. Thanks

**Comment by motjokk** [comment]
It worked :)
