### ISSUE TITLE
How to test exact entity type?

### ISSUE THREAD

**Issue by ahladik** [IfcOpenShell/IfcOpenShell#1412]
Hello,
let's say I have something like:

`const IfcParse::entity&	ent = Schema::IfcArbitraryProfileDefWithVoids::Class();`

since the following tests both return true:

```
ent.is(Schema::IfcArbitraryClosedProfileDef::Class())
ent.is(Schema::IfcArbitraryProfileDefWithVoids::Class())
```

I can only rely on their order to check if ent is actually a IfcArbitraryProfileDefWithVoids.
Is there a better way?

**Comment by aothms** [comment]
These declaration/entity things are constructed at runtime during the schema initialization code as static global objects https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/Ifc2x3-schema.cpp

So I guess it's safe to just do `&ent == &Schema::IfcArbitraryClosedProfileDef::Class()` this is also what the current code base actually does https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcSchema.cpp#L20

I'm open to alternatives like adding operator==

Or (equivalently in python there is a) is() overload without parameters that returns the declaration so that rewrite it as ent.is() == Schema::IfcArbitraryClosedProfileDef::Class()

**Comment by ahladik** [comment]
Probably a specific function would be more elegant, but that's enough for me. Thank you!
