### ISSUE TITLE
BlenderBIM mvd in header

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#1429]
I was told that the BlenderBIM writes out files as CoordinationView when using IFC4, which isn't properly defined for IFC4 (it's ReferenceView) https://technical.buildingsmart.org/standards/ifc/mvd/mvd-database/

Maybe this needs to be fixed in IfcOpenShell, it's a default that comes from there probably?

@Moult thoughts?

**Comment by Moult** [comment]
Ever since the refactor, MVDs make a lot less sense in general for BlenderBIM Add-on users, since IFC is the native dataset, and the user can author IFC data to the full capacity of the spec. Catering for MVDs for other vendors who rely on it to define their scope took a back seat - so the view description was just left as-is.

A proper long term solution is to then build an IfcMVD tool - which takes an IFC dataset, and extracts subsets and potentially performs data massaging for the other vendors - but this is a low priority, since most vendors I've come across kinda don't pay much attention to MVDs and just take whatever you give them.

In the meantime, I guess I could fix the file_description, but this is merely a cosmetic fix - users are still at the liberty of including whatever data they want, and no integrated tool exists to "correct" or "audit" the scope of entity usage.

Just tried, and get this:

```
>>> f.wrapped_data.header.file_description.description = ('asdf',)
Traceback (most recent call last):
  File "/home/dion/drive/blender/blender-2.91.0-linux64/2.91/python/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 1139, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, FileDescription, name, value)
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 71, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 63, in _swig_setattr_nondynamic
    object.__setattr__(self, name, value)
  File "/home/dion/.config/blender/2.91/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 1154, in description
    return _ifcopenshell_wrapper.FileDescription_description(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'FileDescription_description'.
  Possible C/C++ prototypes are:
    IfcParse::FileDescription::description() const
    IfcParse::FileDescription::description(std::vector< std::string > const &)
```

**Comment by DrShawnOKeeffe** [comment]
@Moult Thanks for the "technically correct" fix. It helps for when engineers choose to use this tool on real projects where they are contracted to deliver and use specific specified requirements, e.g. coordination, FM handover, etc. The "long term solution" mentioned above is less for other vendors, than it is for contracting information exchanges on real projects. The MVD itself is the specification these "vendors" should follow (it is the explicit min reqs and prescribes what can/cannot be added for particular exchanges), therefore, a "generic" IFC implementation for serialisation is not the answer. As you already know. No one can test "generic." The exchanges are to be exact for meeting specified works...No different than a slump test for concrete, i.e. must meet the spec exactly or tit must be torn down! Same with data. I cannot sign off on data without testing it, and it is tested against agreed standards with agreed tools that are confirmed by the public to indeed preform as required. Same as ASTM standards for concrete. Software developers must grasp hold of this concept to solve the "vendor" conundrum you mentioned, i.e. they are not (for the most part) licensed practising AEC/FM professionals. All of the above is even more so for web-based transactions of this data, which you I and others are preparing for, right! Must have verification gates on the serialisation and deserialisation of all these exchanges and we can only do that with proper MVD/IDS specifications. So a solution could be easier to meet technical standards for developers, but we cannot diminish quality or standard of care against out professional duties. Looking forward to what BlenderBIM has to deliver next! and, maybe once some of these issues are ironed out, more licensed partitioners will be able to use it on more real projects.

**Comment by Moult** [comment]
Correct, to clarify, MVDs make no sense when used in an environment where IFC is native (e.g. BlenderBIM Add-on). They only make sense if they are to be exchanged by someone who relies on these MVDs as a contractual requirement.

Currently, the BlenderBIM Add-on is actively discouraged to be used as an authoring tool due to its alpha status. Instead, the more stable cases manipulate existing IFC datasets, which inherit the view definition passed in - so therefore the view definition is still correct in most practical scenarios.

In practice, MVDs have demonstrated little applicability to project requirements, so we have instead foregone MVDs in favour of MicroMVDs (and in the future, a combination of MicroMVDs and IDS). An easy example is mandating CSGs for Design Transfer - all our construction projects require surveyed dilapidation meshes, and that's what we design to - so the MVD cannot be applied. So yes, we rigorously define exchange requirements, but MVD is not the tool we use. We use MicroMVDs with BIMTester. The BlenderBIM add-on is already used daily on real projects, and the simple fact is that MVDs are not applicable or useful in these particular scenarios, or, they are inherited, so we play by the rules of what we inherit.

In the future, as authoring with the BlenderBIM Add-on grows more mature, we will indeed still cater for users who rely on MVDs, but right now, those users are the minority.

**Comment by DrShawnOKeeffe** [comment]
Thanks @Moult. Very interesting. Can you please provide a real world project example where a MicroMVD specification is standardised, contacted on that project, and BIMTester is used to verify the data specification? Also please explain how the data is validated, i.e. meets the contractual agreement, which is different than automated verification tool utilisation. BTW: by saying "standardised" above, this means that the MicroMVD specification work the same on any project anywhere in the world, as randomly specifying bits of data/information on singular projects is not suffice for AEC/FM standards, e.g. the concrete slump test, steel standards, etc. While the mix/ingredients may vary, the testing and outcome for stable built environments remain the same. For example, in the IFC world, and MVD such as the FM Handover - Equipment Maintenance  MVD allows for different equipment in different building types anywhere on the planet, but the procedure and output remain the same. Alos, keep in mind during the development of BlenderBIM, that use cases for IFC data in formats other than ISO 10303 parts, are required for consumption by other machines, e.g. IBM Maximo and the like, and these use cases require an MVD to specify the data to be exchanged, tested, and consumed. So how will tool utilised in these regards by NASA, GSA, etc benefit from removing MVDs, which they have required on all projects for over a decade, from their contracts? How will MicroMVD specified data benefit the scenario of Maximo consuming FM data from Design and Construction phases? You see, in a properly specified MVD, there already exist the the "Micro" level MVD requirements and "plain language." For example, in the contract, saying "we want all scheduled items for the drawings during design phase at 90% design completion in an FM Handover MVD file" is plain language and as basic as it gets. IT actually the same as saying "print me the drawing pages with the equipment schedules at 90% design completion." Anyhow, food for thought from the real world of current projects using IFC and BIM...Take care. Looking forward to more discussions. 

PS: It would be helpful to know what exactly does "environment where IFC is native" mean? While I fully understand the intensions and context, I'm fully clear that this is in fact true in the way it is being presented. Using an Add-On does not cinder the full application to being based and functioning on ISO 16739. Again, I understand the intensions, and direction this is going, but it is a bit misleading for the AEC/FM community who have used IFC since the 90's to replace the light table (CV MVD), etc. etc. IFC native application would need to fully function solely on IFC and allow us to still deliver what we have always delivered under the scope and duty of our profession, which firstly is coordinated drawings that match specifications, etc. In my opinion, MVDs are fully relevant and will not go away as they are already in major contracts, software applications, etc. for coordination... What does one call the final project serialised/exported from a fully IFC native application? It cannot simply be IFC File or similar, as the full data schema is never utilised in its entirety for any given project.

**Comment by Moult** [comment]
@DrShawnOKeeffe this is a discussion perhaps best held outside this Github issue. All current contracts I am involved with specify MicroMVDs. In short, a contract that says "deliver Reference View" is less meaningful than "We expect all pipe segments to be extruded area solid" or "All heritage objects must be represented as simplified tessellations corresponding to scanned point cloud data" - the latter implies the existence of aspects of the former (shape representations, etc), but goes into more project-specific detail, and considers aspects which MVDs as an international and "lowest common denominator" may not consider. You can see some examples here, as well as an explanation of how we automatically validate datasets: https://wiki.osarch.org/index.php?title=Using_MicroMVDs_for_exchange_requirements - this does not mean that MVDs should be removed! Building further tools for MVD extraction is important and will happen - but not a high priority for me right now.

For the situation where you have described for FM, indeed, if the client contractually requires that, then we will follow MVDs. This was not the case in our reality, which I cannot say much more here. The additional sad reality is that most authoring platforms aren't even capable of providing the IFC-SPF form, but that's neither here nor there. There are tools like IfcCOBie, which convert IFC-SPF into SpreadsheetML, to address your example, and in doing the conversion, also does some validation of the IFC-SPF side of things.

To address your question about "environment where IFC is native" - it is surprising but true - the BlenderBIM Add-on actually uses the IFC schema natively as its internal data model in memory. Even down to geometry editing, we actually function solely on ISO 16739. There is no translation, no mapping, no "export" function at all. We are delivering projects 100% with IFC, even drawing generation with annotations. In theory (not yet - we are still in alpha) you do not ever need to save any Blender file - everything is in IFC. We actually use the full data schema - now, we are actually prototyping projects which are natively authored in IFC which go across structural analysis, construction sequencing, and cost scheduling. In fact, you can run the entire BlenderBIM Add-on... without Blender! Just pure IFC data manipulation. So what do we call this full dataset? I'm not sure - the concept of MVDs start to break down in this uncharted territory.

So yes, we are functioning solely on IFC, and have actually delivered everything we have needed to produce a full commercial physical building (a very small prototypal one, to be sure). We are certainly in the minority, but hopefully soon we can enable the industry to also, use IFC natively.

**Comment by DrShawnOKeeffe** [comment]
Thanks for the explanation @Moult. Again, very interesting! We will hopefully catch up where we leadoff here on up coming bSI projects. 

PS: We do not deliver COBie SPFF files because machines do not read them. It was envisioned long ago they would, but do not. Yes, we do have converters (to meet nonsense UK-COBie based contacts), there is a difference between verification and validation (talk about this more later), and it is understood that vendors do not support COBie in STEP formatted files, why should they when the machines that require the data do not read SPFs. A better argument is why do vendors not properly implant IFC in general? But I spoke about that already above previously. 

Take care

**Comment by Moult** [comment]
Cheers @DrShawnOKeeffe ! The industry certainly is progressing into interesting territory!
