### ISSUE TITLE
BlenderBIM: wall doesn't export to IFC

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1435]
Any clues on how I can get that wall circled above, to export to the ifc file?
https://www.dropbox.com/sh/o9bgn19k27f741n/AAD-GrTadp6Wde4_IMU2hvo7a?dl=0
![image](https://user-images.githubusercontent.com/507113/114892858-c2185680-9dd2-11eb-92e9-ae07b312f5d5.png)

**Comment by Moult** [comment]
There were a few bugs I noticed whilst fixing this, however what triggered the error in the first place is the "Roofing" Blender material was not correctly linked to an IFC style. The way to "recover" this file is to "unlink" the broken "Roofing" style by clicking the "Unlink Style" button in the Blender Material IFC Style panel, then add a new Body Representation (with my additional fixes in the commit).

Unfortunately, I have no idea how the root problem (i.e. the borked style link) happened, so I cannot yet fix the root cause. There are a number of potential culprits, including:

 1. You perhaps were saving the Blender file as different file names, or exported different IFC files with different filenames whilst testing.
 2. Some combination of pressing the undo button whilst testing might've triggered this.

None of this is your fault, and I am making it a priority to improve link stability during authoring. First I will focus on making "export" the same as "saving". This is one of the easiest ways for links to break. Keep the bugreports coming - they are super helpful!
