### ISSUE TITLE
Include cityjson2ifc in this repo?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1441]
There's a party of little file converters and data massagers blossoming in `src/*` :) Like there is a hidden dxf2ifc, ifccsv, ifccobie (effectively a tailored ifc2spreadsheetml, and ifc2ooxml), ifc2ca, and more recently, for p6 integration, p62ifc (and later, will also have ifc2p6). I guess ifcblender and ifcmax and ifcconvert also kinda count.

@aothms what do you reckon of adding https://github.com/LaurensJN/CJ2IFC ? What do you reckon should be the long term strategy on advertising the plethora of IfcOpenShell ecosystem tools available to the public? Should they be split into many small repos? Or are they small enough to be OK to be part of this repo? Right now, since I'm authoring many of them, and they all kinda integrate into a big package in the Blender authoring environment, it is more convenient to be in one repo. Perhaps inclusion in this repo means that we maintain / quality-assure it as an offering?

Ping @LaurensJN who is the original author.

**Comment by aothms** [comment]
I think a mono repo makes sense, but I'm also open to other options. I think including the code into this repo is probably our best chance of making sure the it stays maintained, update with future versions of IfcOpenShell and distributed in e.g linux package managers.

But we should advertise them, document and distribute them more as independent tools. Make them installable from CMake, etc. So that when you do `make install` / `apt-get ifcopenshell`  you have a `cj2ifc` in your path.

For the website I think there is a roadmap to get these tools listed (It's really also a great opportunity I think to get some more traffic to the website) but I'm really really struggling myself to find the time for this.

**Comment by Moult** [comment]
Agree they should be distributed as independent tools. Over time, we can develop a standardised way of bundling, doing pyexes, as well as CLI args and user docs across this toolkit.

I'll ping tetov on the forum about the site :)

@LaurensJN I've just invited you to get access to this repo - do you mind committing your code to `src/cj2ifc`? Another thing we should consider if whether or not it is named `cj` or `cityjson` - I'm not sure if `cj` is a common name for it. In addition, do you have plans for an `ifc2cityjson`? If so, maybe we should do something like `ifccityjson`, and within it, it has a ifc->cityjson util and a cityjson->ifc util, and who knows what else. Let's see how it evolves :)

**Comment by LaurensJN** [comment]
`cityJSON` and `CJ` are both used I believe, but I have no opinion regarding that, so maybe for clarity we'll use the first one. I believe `ifccityjson` will be the best option, if I look at the other modules in there. 
I will add it somewhere this weekend!
