### ISSUE TITLE
use TravisCI to deploy to PyPi

### ISSUE THREAD

**Issue by thorade** [IfcOpenShell/IfcOpenShell#146]
This is just a copy of https://sourceforge.net/p/ifcopenshell/feature-requests/24/

It would be awesome if you could use PyPi to distribute IfcOpenShell,
because then users could install it much more easiyl using pip:
`pip install -U IfcOpenShell`

This should even be possible in a partly or fully automated way using TravisCI:
http://5minutes.youkidea.com/howto-deploy-python-package-on-pypi-with-github-and-travis.html

**Comment by jf---** [comment]
@thorade , due to the OCCT / OCE dependency ( the CAD kernel ) shipping such a module is no small feat. More realistic is to install though `conda`, which acts as a package manager and can handle this on most platforms. We're using this route for pythonocc, and its been saving us major headaches.

With conda pushing packages from builds to production is relatively straightfwd too.
Recommended ;)

**Comment by thorade** [comment]
As you are aware of this possibility I'll just close this issue, thanks for considering.

**Comment by thorade** [comment]
@jf--- Probably pip wheels could solve the problem as well!?
http://pythonwheels.com/
https://www.python.org/dev/peps/pep-0427/
https://pypi.python.org/pypi/wheel
