### ISSUE TITLE
Reset welding map causes OCC booleans to return strange results

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1472]
Thanks to @s-leger to bringing to my attention. See attached file: 

[weld-bool-bork.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6493684/weld-bool-bork.zip)

The wall is a tessellation made out of two representation items. There are two representation items due to two different styled by items being applied. The full shape representation (step id 174, see breakdown of "A" in diagram) is shown below. The first rep item is shown as "B", and the second is shown as "C".

![2021-05-17-221852_1493x827_scrot](https://user-images.githubusercontent.com/88302/118487510-232ea380-b75e-11eb-8d46-8d1727914cf4.png)

When an opening is present in the wall, the result shown in the bottom left is returned, which looks like a broken wall.

I think this is potentially a regression from https://github.com/IfcOpenShell/IfcOpenShell/commit/ffb8c016b670901ac39407f0f8b2bbd4d283fdc4 due to #1287.

Sorry, must be very "whack-a-mole" :(

**Comment by aothms** [comment]
Sorry quick question. Is my understanding correct that you're using the Blender boolean for this and not OCCT?

Ultimately I think Openings on Tesselations is a bit frowned upon. Splitting the Tesselation into separate surfaces so that you do not have a Solid is even more tricky. Thirdly you can probably use the styling mechanisms specific for tesselations to achieve the style difference (although I'm also not a fan of that, and it's not yet supported in IfOpSh).

**Comment by s-leger** [comment]
No, it does rely on OCCT.

**Comment by aothms** [comment]
Ok thanks for clarifying @s-leger I was a bit confused by Dion's reference to welding across shape items. This welding happens after meshing, not before the boolean subtraction is applied. So it couldn't make a real difference except when the booleans were processed by Blender, which takes the meshed output. But conceptually the things are very related of course.

I think in the end what may have affected this is the "improvement" of the tesselated face set helper which now through various unrelated mechanisms results in a Solid for the non-closed face sets (which is perfectly fine in OCCT, a solid does not need to be a bound volume, see half space solids e.g).

In this case though it causes the boolean operations to behave weirdly. The side faces disappear. And the top/bottom faces get the opening geometry appended to it. It probably makes total sense when you look at the algorithm and boolean logic, but probably not so much for an end-user.

I did a couple of experiments, and it's not that hard to get it to work a little bit better, but than still you have the boolean subtraction as Face - Solid, so what you do not get is the additional faces from Solid - Solid subtractions.

![afbeelding](https://user-images.githubusercontent.com/1096535/119262102-4df37e80-bbda-11eb-90a0-2aa239478abf.png)

I was a bit hesitant to do this, because it might result in regressions for not-that-strictly-manifold shells, but I think it's relatively safe as we only enable this retrial using Face-Solid when first operand is non-manifold and the result is empty or gets the second operand added to it.

**Comment by s-leger** [comment]
This is the point of vertex merging, as despite being separate set of faces to allow styling, the representation overall shape is a solid. So in the end you'll get solid / solid boolean operation.

But you probably are right about a better (correct) way to achieve polygon representation styling using IfcIndexedColourMap / IfcIndexedTextureMap.
So may instead request support for those entity.

At some point, would not make much sense to support things nobody else do in the industry and make our models fail to import properly anywhere else.

**Comment by Moult** [comment]
Given the many ways to have colours in IFC, I think the future of IFC should have less colour methods, so I'm not super keen to support yet another colour method :)

**Comment by aothms** [comment]
> This is the point of vertex merging

Yes, but not in how it was implemented in IfcOpenShell. I think arbitrarily joining vertices between representation items would do more harm than good (imagine several extrusions for door post next to oneanother for example) creating a lot of non-manifoldness.

Merging vertices in the case of IfcOpenShell meant after meshing joining vertices so that e.g the 8 corners of a cube are 8 vertices in Blender as opposed to 24 vertices (position, normal) pairs.

But again, I understand the confusion. Something like that just never existed in IfcOpenShell.

> IfcIndexedColourMap 

Yes, ideally we should, it exists many many years now, just we never bothered to track styles on a sub-item level. In 2x3 it could also be the case that an IfcFace has a style association in a IfcClosedShell, it also not considered currently. So that's why it's additional effort to implement this.

> so I'm not super keen to support yet another colour method :)

Another annoying bit about indexed colors is that it is only colors and not the styles so we can't map it to full materials as easily.

---

How about using IfcCovering? Isn't that also a way to have a higher chance of having the quantities carry over correctly? And matches better what's constructed in reality?

**Comment by Moult** [comment]
Closing as fixed.
