### ISSUE TITLE
BlenderBIM: mirrored objects don't export

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1496]
Mirrored objects don't export to IFC.

**Comment by Moult** [comment]
Ah yeah long story short is that they used to be supported but after the rewrite I didn't get back to it. Mirroring is tricky, and ideally needs to be more thought out in the IFC spec.

**Comment by aothms** [comment]
Yes from my point of view, a mirrored object is not the same as it's base, because it's not an operation you can do on the construction site. You can use IfcMappedItem obviously, but I dislike them. I don't know how this is handled in BlenderBIM, but perhaps you could create two sets of instances? one for where the matrix_world.determinant is negative (meaning mirrored), the other positive.

**Comment by Moult** [comment]
In the past, I have done a mapped item with a non uniform cartesian transformation. However, it is a nasty, nasty situation, and probably even breaks on import (I suspect the iterator will just treat it as a separate shape).

The mapped item thing is something I strongly wish to simplify.

Obviously we can't ignore mirroring, since that's how architects work, but we need a smarter approach in the authoring environment. I propose to treat it like any other "smart parametric object" - i.e. tag it with a pset, IFC considers it a totally distinct, separate shape, but the client-side knows how to regenerate the mirrored relationship.

**Comment by aothms** [comment]
> (I suspect the iterator will just treat it as a separate shape)

True..

**Comment by Moult** [comment]
Just revisiting this, there are two interpretations of this. @theoryshaw there is 1) a regular object mirror (i.e. with a scale along one or more axes of -1), or, 2) a mirror modifier, which generates a mirrored object flipped along the local object origin. Which one were you referring to in this bug report, or both?

If it's option 1, we can solve it again using the cartesian transformation, but tag it with a pset and when we import we handle it specially to preserve the mirroring.

If it's option 2, we can solve it using a cartesian transformation but per representation item, and tag it with a pset too, but it'll be handled not at import type but at edit mode switch.

**Comment by Moult** [comment]
Bump?

**Comment by theoryshaw** [comment]
Hi, would be option 1, mostly...

Example files: https://www.dropbox.com/sh/r0eeu1w5f0cb2gt/AADtidfR8VPuGuORBnLyJyR3a?dl=0


![2021-11-08_08-20-50_Blender_ DDropboxGitLabThe_SteadModels_and_C_blender](https://user-images.githubusercontent.com/507113/140759117-df19d70c-53be-4efd-98d3-f00b8cca287f.png)
![2021-11-08_08-22-36_Blender_blender](https://user-images.githubusercontent.com/507113/140759131-e013ea2c-2f7f-45a7-a0e6-637a0b573727.png)

**Comment by Moult** [comment]
Option 1 is now implemented. Basically it will auto detect and apply the scale transformation.

**Comment by theoryshaw** [comment]
It doesn't seem to work on my side, but maybe we're not talking apples to apples...

blenderbim-211109-py39-win
Vid: https://www.dropbox.com/s/7rh6lklx5gfhz7c/2021-11-09_09-50-31.mp4?dl=0
files: https://www.dropbox.com/sh/c8cxy3rjqqwk2es/AABce-1DuKEFcafEtW4E7uUya?dl=0

**Comment by Moult** [comment]
@theoryshaw whoops, my bad. Hopefully https://github.com/IfcOpenShell/IfcOpenShell/commit/c1c50f886819ec54879f4ef8deaf1593dd581c75 sorts it out.

By the way, mirroring non geometric types (e.g. typically walls, slabs, coverings, etc) should work. However, if you have a geometric type, such as a door, window, or table, mirroring will be canceled out. This is because a mirrorring a table creates a different product. In theory, this is a little nuanced, for example mirrored doors and windows are the same, but because it is so nuanced, it deserves attention as a problem in itself.

**Comment by theoryshaw** [comment]
changing the `IfcExtrudedAreaSolid/Depth` springs from different location.
vid: https://www.dropbox.com/s/u3efwjnjpflepzv/2021-11-14_16-46-25.mp4?dl=0

files: https://www.dropbox.com/sh/ci46lm01eaal8s7/AABMT8fPAFDkVSktbcrrq67ua?dl=0
