### ISSUE TITLE
IfcConvert fails to open file if the file names contains non-ASCII characters (Windows)

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#15]
As a workaround, rename the file.

```

>IfcConvert.exe ä.ifc

Log:
[Error] Unable to parse .ifc file or no geometrical entities found


>ren ä.ifc a.ifc

>IfcConvert.exe a.ifc
Scanning file...
Done scanning file
Creating geometry...
Done creating geometry

Conversion took 6 seconds
```

**Comment by aothms** [comment]
What do you think of this https://github.com/aothms/IfcOpenShell/commit/4d46ccf673008aa045a491900a6f6905de1855c3 ? It seems like a whole lot of work for some trivial unicode support on windows. Do you have better ideas?

Complications include that for all serialized formats unicode file names need to be supported. `IGESControl_Writer` can write to an `ostream&` (which we can open on msvc from a `wchar_t*`), but `STEPControl_Writer` cannot, so a temporary file is used, which is moved with `_wrename`.

I don't like to obscure function prototypes that take a filename with some unicode-aware typedef switching between `std::string` and `std::wstring` as it might confuse novice users, especially on non-windows where everything is happily utf-8. That is why there are many redundant `#ifdefs`. Maybe this is a bad idea.

I think I forgot to update the .dae because I don't have opencollada here. But I think this is enough to get a 2nd pair of eyes on this.

**Comment by Stinkfist0** [comment]
Hi Thomas. Some more elegant solution should be possible, maybe something like this: https://dl.dropboxusercontent.com/u/16413694/WindowsUtf8IoStream.cpp

**Comment by Stinkfist0** [comment]
FYI, I've started working with this.

**Comment by Stinkfist0** [comment]
My original plan was to implement Windows-friendly UTF-8 wrappers for file IO (fopen, remove, rename, ifstream, and ofstream) but I wonder if this would be a good solution for IFCOS: http://cppcms.com/files/nowide/html/ This library would also help to achieve UTF-8 console I/O for all platforms.

**Comment by aothms** [comment]
Interesting find. I see this is not under review yet and it's three (not sure?) years old. Not sure if it will generate more traction. I wonder whether ICU has something to brighten our day, as it certainly more tested by time. Maybe something like `u_fopen_u()` is remotely useful [1]? 
[1] http://icu-project.org/apiref/icu4c/ustdio_8h.html#a845d75a2c9abb3ba8fa73fd286973213

**Comment by Stinkfist0** [comment]
Using ICU for this would mean making it a mandatory dependency + if it only helps with fopen() calls for text files it doesn't sound really compelling. I'll probably start toying around with the nowide library first.

**Comment by aothms** [comment]
I agree, especially since ICU doesn't offer anything like modern c++ it would be a bit painful. On the other hand it wouldn't necessarily make it mandatory. Just mandatory for opening files with special character names on Windows. We can still make it degrade nicely for ASCII files on windows.

What's your plan in this regard, do you intend to make NoWide mandatory? It seems that with some `typedef`s and a `#ifdef`'ed call to `boost::nowide::args()` we can have the code degrade nicely. But naturally it doesn't read as nicely. Just not sure if we would need to bother *nix developers with another dependency that doesn't really help them.

**Comment by Stinkfist0** [comment]
I have postponed my work for this for now (vacation and other stuff).

**Comment by aothms** [comment]
Enjoy your holidays!

**Comment by ysangkok** [comment]
It is really confusing now, because I can read the file outside IfcOpenShell with ifstream because I already did the conversion. But because IfcOpenShell tries to convert again on Windows, it breaks.

It is really unintuitive if a function takes an `istream` or string (filename) and it works if I pass it `ifstream(filename)` but not with the string.

**Comment by aothms** [comment]
@ysangkok what is exactly the contents of your string, what system codepage, etc.?

Mostly for the sake of the Python wrapper, there is the assumption now that filename is a UTF8 encoded string, because typically on nix filepaths are UTF8, and because it essentially a superset of 7-bit ascii.

What do you propose instead? I think a conversion to `wchar_t` is necessary in order to be able to open filenames with characters outside of the system codepage. But perhaps make `CodePage`, the first argument to `MultiByteToWideChar()` configurable? Feel free to send in a PR if you have sth.

**Comment by ysangkok** [comment]
Making it configurable would make sense . If I understand it correctly , no
conversion would effectively be done if I pass CP_ACP. And CP_UTF8 would be
the default ?

**Comment by aothms** [comment]
> If Win32 ANSI APIs are used to get filenames from a Windows NT system, use CP_ACP when converting the string. Windows NT retrieves the name from the physical device and translates the OEM name into Unicode. The Unicode name is translated into ANSI if an ANSI API is called, then it can be translated back into Unicode with MultiByteToWideChar().
> 
> If filenames are being retrieved from a file that is OEM encoded, use CP_OEMCP instead.

From: https://support.microsoft.com/en-us/help/108450/multibytetowidechar-codepages-cp-acp-cp-oemcp

Not sure, just whatever works apparently between `CP_ACP` and `CP_OEMCP`.

> If I understand it correctly , no conversion would effectively be done if I pass CP_ACP

A conversion from a windows codepage to UCS-2 / UTF-16 would still occur. Just one that doesn't break.

> And CP_UTF8 would be the default?

Probably, if you mean default arguments to a function yes, so that we don't pollute that function signature on non-windows systems.

Note to self: regardless of this, we probably still need to compile with `-DUNICODE` and provide a `int _tmain(int, wchar_t**)` in order to support characters out of the current windows code page (?)

**Comment by aothms** [comment]
See #258 comments welcome.

@ysangkok I didn't implement anything related to OEM codepages. All file path strings are assumed to be utf-8 encoded. This requires some work in the client side code to create a utf-8 encoding for oem paths on Windows. IMHO this is much more clear than having to deal with these ancient code pages in the public IfcOpenShell API specs.

**Comment by Moult** [comment]
Not sure if this is possibly related, but on Windows:

```
>>> f.write('C:/tmp/a.ifc') # works fine
>>> f.write('C:/tmp/03 diseño/a.ifc') # no file is created, but no errors either
```

**Comment by CyrilWaechter** [comment]
Following have been tested in 0.7.0:
```powershell
IfcConvert.exe ä.ifc
```
```python
f.write('C:/tmp/03 diseño/a.ifc')
```
Both works so I assume this issue can be closed.
