### ISSUE TITLE
ifcopenshel.api: autocompletion and static code analysis

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#1507]
> Sweet!
> To refrain from magic, one other approach I can imagine is to do some sort of code generation during packaging. That we just print our own quick python file with proper function signatures for autocompletion and static typing with e.g mypy
> Feel free to assign something to me btw.

_Originally posted by @aothms in https://github.com/IfcOpenShell/IfcOpenShell/issues/1399#issuecomment-808691413_

I am very much interested by this topic as I am not comfortable at all with current `ifcopenshell.api.run("<module>.<use_case>", **settings)` where you have to check each time what parameters are expected and be sure to have no typo in your string. Can you elaborate a bit more ?

**Comment by Moult** [comment]
There are a few things I'd like to achieve ultimately with the API:

 1. Allow for event listeners. This allows parametric relationships when one thing is changed to affect another or trigger another usecase to be run in an authoring environment.
 2. Allow for version control. An API call should represent a relatively high level change that can be understood by powerusers that doesn't need to deal with the details of the spec, and is useful for meaningful logs within a VCS.
 3. Allow for a client-server model. For multiple users to collaborate via the IfcOpenShell API, the calls should be able to be recorded (i.e. serialised), mirrored on a server, or both (i.e. sent to a server, first being serialised, then sent, then actioned on the server).

Those three intentions made me think it would be desirable to centralise all API calls into a "run" function.

This breaks code analysis, and breaks autocompletion unfortunately.

I don't know what the final solution looks like, and out of those three, only the first is achieved, the second has some very naive serialisation code, and the third hasn't been attempted. So in other words, an attempt was made, but everything is still moving, and I'm open to suggestions, keeping in mind the ultimate 3 intentions of the API.

Hope it made sense.

**Comment by aothms** [comment]
I think code generation during packaging is potentially best of both worlds:

for example in project/ (https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/project) we could generate a file:

__init__.py

```
def create_file_now(version="IFC4"):
    from .create_file import Usecase
    return Usecase(version=version).execute()
```

We just have to think about naming so that the submodule doesn't collide with the function name. 

@Moult come to think of it. If every action is recorded like this, maybe we don't even need the file based undo/redo. You just have a stack of Usecase invocations that you can apply to a file. And undo means start from 0 and apply until n-1.

**Comment by Moult** [comment]
@aothms at risk of getting off topic, yes, this could in theory solve the undo problem. However, it means you need two copies of your file in memory - first is the latest and greatest, and the previous one HEAD^n, where n is the size of your undo stack. With every new undoable action, we need to bump HEAD, which happens anyway, and _also_ "bake" the results of HEAD^n+1. I've no idea how to make these two copies in memory, nor how efficient it is to hold both of them and bump both simultaneously.

**Comment by aothms** [comment]
Yeah it's not very practical. Let's not derail the discussion :)

> that copy of the geometry 

Yes, there's that and also references to other IFC entity instances are not valid anymore between different copies of the file.

**Comment by Krande** [comment]
> There are a few things I'd like to achieve ultimately with the API:
> 
> 1. Allow for event listeners. This allows parametric relationships when one thing is changed to affect another or trigger another usecase to be run in an authoring environment.
> 2. Allow for version control. An API call should represent a relatively high level change that can be understood by powerusers that doesn't need to deal with the details of the spec, and is useful for meaningful logs within a VCS.
> 3. Allow for a client-server model. For multiple users to collaborate via the IfcOpenShell API, the calls should be able to be recorded (i.e. serialised), mirrored on a server, or both (i.e. sent to a server, first being serialised, then sent, then actioned on the server).
> 
> Those three intentions made me think it would be desirable to centralise all API calls into a "run" function.
> 
> This breaks code analysis, and breaks autocompletion unfortunately.
> 
> I don't know what the final solution looks like, and out of those three, only the first is achieved, the second has some very naive serialisation code, and the third hasn't been attempted. So in other words, an attempt was made, but everything is still moving, and I'm open to suggestions, keeping in mind the ultimate 3 intentions of the API.
> 
> Hope it made sense.

I thought I might throw out a suggestion (although I haven't had much time yet to dig into the api implementation). But could perhaps the functionality you describe be covered using a decorator?

**Comment by Moult** [comment]
Returning to this topic, I think it makes sense to in the API:

 1. Specify keyword args in the init signatures of all usecases
 2. Introduce type hints, at the expense of breaking some lower Python version support, which I'm totally fine with.

Though these two are a step in the right direction, it doesn't solve the issue that it's still recommended to use ifcopenshell.api.run() to take advantage of the listeners and usecase serialisation code.

I'm not sure if code generation or decorators are a solution either, because the point of the API is to create a separated client<->server model. Yes, one option (which is the only one right now) is to modify a file held in memory from your script or app. However, I do want to explore an option where the API forwards calls to an IfcOpenShell API server, which then enables some form of multi-user, live editing with support for multiple clients.

But of course, I have no idea what makes sense in that context until this multi-user experimental thing is actually coded. Right now it's just ideas.

But I suspect it is always a good idea to have explicit kwargs instead of **settings so let's start with that :)

**Comment by Moult** [comment]
A heads up that thanks to the recent documentation work everything except for the geometry module now uses kwargs instead of a generic **settings.

**Comment by aothms** [comment]
Oh oops, also relevant 2693

**Comment by cvillagrasa** [comment]
> I'm not sure if code generation or decorators are a solution either, because the point of the API is to create a separated client<->server model.

@Moult I'm quoting this from two years ago, but still seems relevant. I'm having a hard time understanding this take. Why are code generation, decorators, or even inheritance against pre/post listeners or serialization?

**Comment by Moult** [comment]
I was wrong, they are not mutually exclusive - so long as there is a way for the code to intercept the actual usecase.

**Comment by Moult** [comment]
Finally closing this. We now have autocompletion and static code analysis.
