### ISSUE TITLE
Blenderbim - How can we import 3d object and assign them an IFC Class?

### ISSUE THREAD

**Issue by vuicBABS** [IfcOpenShell/IfcOpenShell#1518]
Hi,

If I import an element from a blender file (withouht link on a ifc file) I can't assign it an IFC Class. Take a look on the image with a power generator. I can import the geometry but it's not possible to assign the IFC class althought I created an element type for it.
![Capture](https://user-images.githubusercontent.com/40517234/121522161-1fa4da00-c9f5-11eb-924a-6e8a1f817374.PNG)

I already try CTRL+E and Assign_IFC Class but it doesn't work.
How can we assign a class to object (.blend, .obj, ...) that we import?
You'll find our power generator in the zip file.
[power_generator.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6637558/power_generator.zip)

I found a way to solve the problem. I have to create a new object (cube, sphere, ...) join it with the power generator. After that I can assign an IFC Class and I just have to remove the vertices of the cube or sphere. But it's not really a nice solution in production...

Thank you

**Comment by Moult** [comment]
I suspect that object came from another Blender file which originated from an IFC. Therefore, you get the message "IFC Element Not Found" and you are not able to assign a class, since it thinks it should still be able to be linked to an IFC element.

All you have to do is say "nope, Blender, I know what I'm doing, I stole this from another file" and "Unlink" the element. You can do this by pressing the unlink button to the right of your blue arrow. Then you can assign a class again.

**Comment by vuicBABS** [comment]
I tried to unlink but I get an error message
![20210613](https://user-images.githubusercontent.com/40517234/121798919-56fbcc80-cc29-11eb-974a-8431b40eb1e1.PNG)
