### ISSUE TITLE
style.add_style transparency sets opacity, and same-named styles are merged on import

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1529]
If I try and create a very transparent entity by setting 'transparency' to '0.9':

    style = ifcopenshell.api.run(
        "style.add_style",
        ifc,
        name="My Style",
        surface_colour=[1.0, 0.0, 0.0],
        diffuse_colour=[1.0, 0.0, 0.0],
        transparency=0.9,
        external_definition=None,
    )

I get a style with the Transparency attribute set to '0.1':

    #13160=IFCSURFACESTYLERENDERING(#13158,0.1,#13159,$,$,$,$,$,.NOTDEFINED.);

Which renders in blenderbim as nearly opaque (blenderbim is interpreting the IFC correctly I think).

Also, if I create two styles using different colour attributes but the same 'name', to apply to different entities, blenderbim clobbers one of them and applies a single blender material to both entities. In this situation I would expect blenderbim to create 'My Style', 'My Style.001', 'My Style.002' etc... blender materials.

**Comment by Moult** [comment]
Yeah transparency is defined opposite to how most apps present it. Most apps present "opacity" = 1 as opaque, whereas IFC does the opposite and presents "transparency" = 1 as transparent. From the docs:

> The transparency field specifies how "clear" an object is, with 1.0  being completely transparent, and 0.0 completely opaque. If not given,  the value 0.0 (opaque) is assumed. NOTE The definition of 1 being transparent and  0 being opaque is the opposite of the definition in alpha channels,  where 0.0 is completely transparent and 1.0 is completely opaque. This  definition is due to upward compatibility to previous versions of this  standard in different to the definition in IfcIndexedColourMap.

The IfcOpenShell API generally is designed to accept more "human" inputs and normalise (i.e. flips, in this case) the various quirks of IFC. This is one of them. But although I thought I was doing the right thing, maybe it's just leading to more confusion. Dunno :) Should I change it?

The clobbering is because I came across many IFC files where surface styles were generated per object. This led to a crazy number of styles, which killed Blender, and were clearly because whatever vendor was exporting was simply generating a bunch of styles instead of them being meaningful. But that was a while ago, I guess I should revisit it and see what I can do to faithfully reproduce it without clobbering, and perhaps detect when there are too many styles and activate "clobber" mode.

**Comment by brunopostle** [comment]
@moult the IFC spec makes sense, clear glass is 'more transparent'. The confusion is that the api has a 'transparency' parameter which translates into an IFC 'Transparency' parameter, but they do the opposite thing. Maybe rename the api parameter to 'opacity'.

The clobbering was unexpected, but I can see that some IFC files might have a hundred thousand styles, so you have to merge them, and comparing all the parameters is impractical - I'd keep the code as it is.

**Comment by Moult** [comment]
Kept it as transparency, it's OK. See fixed commit.

I'll revisit the clobbering, just in case, so let's keep this issue open until I do. Perhaps there is a smarter solution.

**Comment by Moult** [comment]
Sorry to be a pain, do you have a sample IFC file where I can recreate the clobbering?

**Comment by brunopostle** [comment]
Sure, this IFC has six styled objects, each with a separately defined style. But there are only two unique style names, so only two styles appear in the blender materials list:
[tmpwlof5oom.ifc.gz](https://github.com/IfcOpenShell/IfcOpenShell/files/6719786/tmpwlof5oom.ifc.gz)
