### ISSUE TITLE
GeomServer ignore errors / unsupported items

### ISSUE THREAD

**Issue by dmdm22** [IfcOpenShell/IfcOpenShell#153]
I'm using ifcopenshell to import geometry using GeomServer inside a java wrapper (pretty much the same as the BimServer plugin). If you are interested, find some pics of the viewer app here: http://www.combcomp.de/c2/pdhs_threedee.htm#doc-viewer

First i have to thank you, what a great work on this library. GeomServer flawlessly loads hundreds of models in a row without crashing at all (892 models with sizes from 2MB to over 200MB per IFC-file was the highest workload i tested so far). 

But some IFC models cannot be loaded, GeomServer does not load them at all. Also unprocessable with IfcConvert, which fails with errors.

```
Log:
[Error] {BOCAD_2011-12-14T11:43:35_1323860481/102834} No operation defined for:
#427=IfcBoundingBox(#430,3300.,160.,160.)
```

Nobody needs bounding boxes in IFC, me neither. No problem if these are not going to be supported, but they should be ignored instead of discarding the whole ifc imho.

Also a wrong representation context leads to an error:

```
Log:
[Error] ContextType 'Sketch' not allowed:
#17=IfcGeometricRepresentationContext('Plan','Sketch',3,0.1,#14,$)
[Error] ContextType 'Design' not allowed:
#23=IfcGeometricRepresentationContext('Plan','Design',3,0.1,#20,$)
```

I know these are not valid context names (anymore), but the ifc still contains all geometry needed, just a wrong naming here. Wouldn't it be better to print out a warning instead of failing with the whole model?

If ignoring such errors is no option for default processing, what about adding a 'ignore-errors' / 'ignore-unsupported' parameter to GeomServer / IfcConvert?

It would be very useful to have these option to get as much geometry as possible.

**Comment by aothms** [comment]
Hi, glad to hear this IfcGeomServer is useful to you. It doesn't seem to be used a lot outside of the BIMserver itself, but I think it has potential.

You're assumption that IfcOpenShell would terminate processing after encountering such errors is not correct. On the contrary, IfcOpenShell tries to be as permissive as possible. 

In the first fragment you posted I see a curious GlobalId `BOCAD_2011-12-14T11:43:35_1323860481/102834` which does not even remotely resemble what it should look like [1]. This might be an indication of some other flaws in the model as well.

Perhaps you can share some of these models in order to have a more detailed look what is going on. Either publicly here or privately to models@ifcopenshell.org.

[1] http://www.buildingsmart-tech.org/implementation/get-started/ifc-guid

**Comment by dmdm22** [comment]
Yes, the ids in the model are crap, they are not near a valid GUID. But these kind of formal errors are found in some of my clients models (these are from 2011, current IFC exports are better).

And you are right, those errors printed do not seem to be the cause for the failed import. After switching my IfcGeomServer binary to that from the BimServer plugin ... it works.

So i assume it had to do with the self compiled binary from master branch.

Do you have any plans of releasing some precompiled (stable) builds? Just asking, as compiling for linux and windows is quite a pain for someone not so familiar with c++ ...

**Comment by aothms** [comment]
> Do you have any plans of releasing some precompiled (stable) builds? Just asking, as compiling for linux and windows is quite a pain for someone not so familiar with c++ ...

Well, actually compiling should be a breeze with the build scripts https://github.com/IfcOpenShell/IfcOpenShell#compiling-on-windows and https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.py

It could be that you stumbled no a recent change that just doesn't work out well for a particular file you test on. The usage of the IFC standard in the industry is evolving and therefore sometimes older files might work less well with a more recent version of the software. Did you happen to investigate more?
