### ISSUE TITLE
Type conversion operators not implemented

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#1537]
For many of the XXX_TypeEnum classes, the `operator Value() const;` is not implemented. The IfcAlignmentHorizontalSegmentTypeEnum is an example.

![Capture](https://user-images.githubusercontent.com/37087370/123357454-64b12c00-d51e-11eb-8a7d-6958df819e23.PNG)

The following code snippet compiles but doesn't link. 

```
bool IsTransitionCurve(Ifc4x3_rc2::IfcAlignmentHorizontalSegment* horizontal_segment)
{
   static std::vector<Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum> transition_curve_types
   {
      Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::IfcAlignmentHorizontalSegmentType_BLOSSCURVE,
      Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::IfcAlignmentHorizontalSegmentType_CLOTHOID,
      Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::IfcAlignmentHorizontalSegmentType_COSINECURVE,
      Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::IfcAlignmentHorizontalSegmentType_CUBIC,
      Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::IfcAlignmentHorizontalSegmentType_CUBICSPIRAL,
      Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::IfcAlignmentHorizontalSegmentType_HELMERTCURVE,
      Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::IfcAlignmentHorizontalSegmentType_SINECURVE,
      Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::IfcAlignmentHorizontalSegmentType_VIENNESEBEND
   };

   auto found = std::find(transition_curve_types.begin(), transition_curve_types.end(), horizontal_segment->PredefinedType());
   return (found == transition_curve_types.end() ? false : true);
}
```
The linker error is:
```
1>IfcAlignmentConverter.obj : error LNK2019: unresolved external symbol "public: __cdecl Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::operator enum Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::Value(void)const " (??BIfcAlignmentHorizontalSegmentTypeEnum@Ifc4x3_rc2@@QEBA?AW4Value@01@XZ) referenced in function "class Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum * __cdecl std::_Find_unchecked1<class Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum *,enum Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::Value>(class Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum *,class Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum *,enum Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::Value const &,struct std::integral_constant<bool,0>)" (??$_Find_unchecked1@PEAVIfcAlignmentHorizontalSegmentTypeEnum@Ifc4x3_rc2@@W4Value@12@@std@@YAPEAVIfcAlignmentHorizontalSegmentTypeEnum@Ifc4x3_rc2@@PEAV12@0AEBW4Value@12@U?$integral_constant@_N$0A@@0@@Z)

```
If you give me a little guidance as to how I would revise the code generation scripts and access the underlying _data object, I will take a shot at putting together a pull request.

**Comment by aothms** [comment]
> If you give me a little guidance as to how I would revise the code generation scripts and access the underlying _data object, I will take a shot at putting together a pull request.

Thanks, but the code generation bit is rather messy. I've fought my way through it and committed the fix. The reason why this was missing is that 4.3rc2 or rc3 for the first time introduced selects of enumerations. This required some changes in the schema handling. Apparently the implementation of the case function was left out. Thanks for the report.

Edit: but wait a second!

`horizontal_segment->PredefinedType()` doesn't return `Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum`. It returns `Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::Value` so I think you need to make that the element type of your vector.

Because C++ enums don't retain a lot of information we needed wrap the enum Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum::Value in a class (previously namespace) Ifc4x3_rc2::IfcAlignmentHorizontalSegmentTypeEnum.

**Comment by RickBrice** [comment]
You are right about the XXXEnum::Value being the type. That fixed my issue.
