### ISSUE TITLE
testing "Create Project" undo operation

### ISSUE THREAD

**Issue by Jesusbill** [IfcOpenShell/IfcOpenShell#1544]
I tested creating a project in BlenderBIM and then using `undo`.
The scene objects are correctly removed but the UI panel does not change back to the one before creating a project.
After some debugging it looks to me that although `IfcStore.file = None` is called in the [rollback function](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/module/project/operator.py#L68), `IfcStore.get_file()` still gets a reference to a file and is not None [in the ui](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/module/project/ui.py#L17)

**Comment by Moult** [comment]
Ah yes undo in project is a bit funny because for it to work, it depends on all the sub operators to have undo correctly implemented. However that's not the case right now. So in other words, all the code changes are correct in the project operator file, but you won't actually see it working until some other modules get fixed too.

If you want to see it working, comment out root/operator/assign_class's call to add_representation and assign_container. Let's keep this issue open until we get around to fixing the other modules, and then it should work.

**Comment by Jesusbill** [comment]
> If you want to see it working, comment out root/operator/assign_class's call to add_representation and assign_container.

Nice, indeed it works after commenting these two calls, it feels great :)

> Let's keep this issue open until we get around to fixing the other modules, and then it should work.

Ok sounds good

**Comment by Jesusbill** [comment]
it now works as expected
