### ISSUE TITLE
api: creating a project without an 'application' fails

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1547]
This code used to work before b4a422c:

        run = ifcopenshell.api.run
        ifc = run("project.create_file")
        run("owner.add_person", ifc)
        run("owner.add_organisation", ifc)
        project = run(
            "root.create_entity",
            ifc,
            ifc_class="IfcProject",
            name="My Project",
        )

Now I get an error because there is no IfcApplication entity:

    File "/usr/lib64/python3.9/site-packages/ifcopenshell/api/owner/create_owner_history.py", line 20, in execute
      application = ifcopenshell.api.owner.settings.get_application(self.file)
    File "/usr/lib64/python3.9/site-packages/ifcopenshell/api/owner/settings.py", line 13, in get_application
      return ifc.by_type("IfcApplication")[0]
    IndexError: list index out of range

The solution should be to add an application:

    run("owner.add_application", ifc)

..but this fails because owner.add_application doesn't seem to work:

    File "/usr/lib64/python3.9/site-packages/ifcopenshell/api/owner/add_application.py", line 10, in execute
      return self.file.create_entity("IfcApplication", **self.settings["attributes"])
    TypeError: ifcopenshell.file.file.create_entity() argument after ** must be a mapping, not NoneType

If I change `add_application.py` like so, it seems to be ok, but I don't really understand this:

    class Usecase:
        def __init__(self, file, **settings):
            self.file = file
            self.settings = {}
            for key, value in settings.items():
                self.settings[key] = value

        def execute(self):
            return self.file.create_entity("IfcApplication", **self.settings)

**Comment by Moult** [comment]
Sorry that was a recent regression caused by https://github.com/IfcOpenShell/IfcOpenShell/commit/b4a422c2b82fbaa516eb4335ba6d7c13c19b1f40 with @johltn .

Basically some new defaults were put in ifcopenshell.api.owner.settings to find a person / organisation / application. However, I forgot that this only applies in IFC2X3, not IFC4. So I made the defaults less strict, so you're free to go without any person / org / app if you wish.

I also redid the add_application usecase to match the same pattern as add_organisation and add_person and added some defaults so it can be run without thinking for tests.

**Comment by brunopostle** [comment]
Thanks, though now, if I `add_organisation` without `add_application`, it later fails creating IfcOwnerHistory entities:

    File "/usr/lib64/python3.9/site-packages/ifcopenshell/api/__init__.py", line 46, in run
      result = usecase_class(ifc_file, **settings).execute()
    File "/usr/lib64/python3.9/site-packages/ifcopenshell/api/root/create_entity.py", line 19, in execute
      "OwnerHistory": ifcopenshell.api.run("owner.create_owner_history", self.file)
    File "/usr/lib64/python3.9/site-packages/ifcopenshell/api/__init__.py", line 46, in run
      result = usecase_class(ifc_file, **settings).execute()
    File "/usr/lib64/python3.9/site-packages/ifcopenshell/api/owner/create_owner_history.py", line 21, in execute
      return self.file.create_entity(
    File "/usr/lib64/python3.9/site-packages/ifcopenshell/file.py", line 231, in create_entity
      e[idx] = arg
    File "/usr/lib64/python3.9/site-packages/ifcopenshell/entity_instance.py", line 138, in __setitem__
      self.wrapped_data.setArgumentAsNull(idx)
    File "/usr/lib64/python3.9/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 1379, in setArgumentAsNull
      return _ifcopenshell_wrapper.entity_instance_setArgumentAsNull(self, i)
    RuntimeError: Attribute not set

It is fine if I don't `add_organisation` at all (but I don't get IfcOwnerHistory, which is expected).

..also, it doesn't seem to be possible to set any parameters via `add_appplication`, i.e. ApplicationFullName here doesn't do anything:

    run("owner.add_application", ifc, ApplicationFullName="Homemaker")

**Comment by Moult** [comment]
Ah sorry, the error is not very friendly. Fixed in latest commit. However, failing to create the owner history is expected behaviour. Basically, for a owner history, you need a person, org, and app. However, the IfcOpenShell API does not know who your person, org, or app is, especially if your app allows things like switching persons / orgs / sub-apps. Therefore, you need to tell the API.

To tell the api, you basically overload the `ifcopenshell.api.owner.settings` functions. Here's an example of how the BlenderBIM Add-on overloads it: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/handler.py#L173-L183 - if you don't overload it, it'll default to finding the first person, org, and app it comes across, which may or may not be correct, but at least saves you overloading it when you're doing quick scripts and tests.

Also try:

```python
ifcopenshell.api.run("owner.add_application", ifc, application_full_name="Homemaker")
```
