### ISSUE TITLE
BlenderBim display link duct not working

### ISSUE THREAD

**Issue by Asgatlat** [IfcOpenShell/IfcOpenShell#1551]
hi,
when i open a IFC file with BlenderBim (210705 test version and before) i can't see the corner of the duct :
![blenderbim](https://user-images.githubusercontent.com/86599367/124467272-ed8a5c00-dd97-11eb-99ef-093f21fe93b5.jpg)

the same file displays better with BimVision software : 
![bimvision](https://user-images.githubusercontent.com/86599367/124467342-0135c280-dd98-11eb-9b1a-eb5da2d01135.jpg)

**Comment by Moult** [comment]
Can you share your file please?

**Comment by Asgatlat** [comment]
here is the wetransfer link to donwload the ifc file (link valid for 7 days) : 
https://we.tl/t-Scs6Bir90j

**Comment by aldomontanari** [comment]
All missing objects are far away from the origin
![imagen](https://user-images.githubusercontent.com/32773354/124481304-83b18880-dd7e-11eb-93de-070a86b14f66.png)

**Comment by aldomontanari** [comment]
![imagen](https://user-images.githubusercontent.com/32773354/124481698-f458a500-dd7e-11eb-847e-a0b662428c64.png)

**Comment by Asgatlat** [comment]
hmmm i see, the file was export by the architect from Revit
btw, why does it seemed better look on BimVision ?

**Comment by Moult** [comment]
Not at a computer now but will check out why in the morning. Perhaps due to geolocation issues.

**Comment by aldomontanari** [comment]
It looks fine on bimcollab zoom
![imagen](https://user-images.githubusercontent.com/32773354/124488411-30433880-dd86-11eb-8b86-50f191667174.png)

**Comment by Moult** [comment]
The issue is indeed to do with poor georeferencing. It is now fixed.

In short, Revit doesn't do georeferencing correctly. There are two known workarounds to invalid georeferencing that BIM apps use in lieu of correct georeferencing. The BlenderBIM Add-on accommodates for these invalid methods, but previously could only accommodate either one workaround or the other - but not both combined.

I've rewritten the invalid georeferencing detection methods to allow for both known workaround methods to be accommodated simultaneously. Your file now works, but let's keep an eye out in case I missed something.

I've written a bit about georeferencing which might help explain https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/docs/blenderbim/georeferencing.rst

**Comment by Asgatlat** [comment]
thank you ! i confirm that it's fixed for me :)
