### ISSUE TITLE
BlenderBIM: surfacestyle attributes (e.g. Name) not shown nor editable, nor can they be removed

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1557]
@Moult Can you give @Jesusbill and I some pointers. 

We'd like to link [this](https://gitlab.com/openingdesign/mudroom/-/blob/af06ff3a4cc6e6603462cfe582c7bb98bf272be0/Models%20and%20CAD/mudroom_structural_new.ifc) into revit and use the material tag.

video: https://www.dropbox.com/s/g881uzf66xatrk0/2021-07-07_21-16-03.mp4?dl=0

As we just discovered, per the video, revit's material tag pulled the IfcSurfacestyle, which is okay, but we're not sure (or at least i am) how to translate the ifcmaterial name into IfcSurfacestyle.

ahhh materials in IFC. :|

**Comment by Moult** [comment]
So the solution is to apply the style to the material - so unlink the current style, switch to the Blender material that has the IFC material, then add a style to that.

Let's keep this issue open because 1) Style attributes aren't shown, which is poor, and 2) Styles cannot currently be removed, only unlinked. When those are fixed, I'll close this issue.
