### ISSUE TITLE
Python: Creating an IFC from scratch yields unfindable objects

### ISSUE THREAD

**Issue by noamgat** [IfcOpenShell/IfcOpenShell#1567]
Installed ifcopenshell via conda.
The following code snippet fails:

```
import ifcopenshell
ifc = ifcopenshell.file(schema='IFC4')
ifc.create_entity('IfcRoot', GlobalId='AAA')
ifc.by_guid(ifc[1].GlobalId)
```

I get the following error:

`
RuntimeError: Instance with GlobalId 'AAA' not found
`

How come?
Note that `ifc[1]` returns a valid object

**Comment by aothms** [comment]
> How come?

Good question, my first inclination would be that it might be related to the transaction work we have been doing lately, but going back through history I can't seem to see where this issue was introduced? @Moult do you know whether this has ever worked?

The issue appears to be that the attributes are set on the instance **after** adding it to the file. One way to work around that in your code would be to use the following snippet instead:

```
import ifcopenshell
ifc = ifcopenshell.file(schema='IFC4')
inst = ifcopenshell.create_entity('IfcWall', GlobalId=ifcopenshell.guid.new())
ifc.add(inst)
ifc.by_guid(ifc[1].GlobalId)
```

To fix this in the file.create_entity() call we should probably move these two lines [0] to the end of the function. @Moult would that interfere with the transaction logic?

```
self.wrapped_data.add(e.wrapped_data, eid)
e.wrapped_data.this.disown()
```

[0] https://github.com/IfcOpenShell/IfcOpenShell/blame/37a61c549f51f6b8290c6fe905fcb7834b8ed4ed/src/ifcopenshell-python/ifcopenshell/file.py#L84-L85

**Comment by Moult** [comment]
From memory, I have also come across this before so I think it never worked. Also, no transaction is active in your test code, so the transaction system is never triggered.

In fact, check this out: https://github.com/IfcOpenShell/IfcOpenShell/issues/1246

**Comment by aothms** [comment]
In #1246 by_guid() is never used so it's not 1 on 1 related. But the attribute change thing to update the maps is a beast we have to tackle.

The instance is now added after the values are set. This seems to resolve the issue.

@Moult can you double check if/how this affects the transaction logic?

**Comment by Moult** [comment]
@aothms are you sure? Can you check this comment: https://github.com/IfcOpenShell/IfcOpenShell/issues/1246#issuecomment-757132361 ? The example seems identical to what @noamgat posted.

Yep, I can check if this affects transaction :)

**Comment by aothms** [comment]
you're right sorry, I read only the text which mentioned "attribute changes", but the code snippet is indeed exactly the same

**Comment by Moult** [comment]
Tested and did a minor tweak so that transactions work. I reckon this can be closed!

**Comment by Moult** [comment]
Sorry for the reopen, I noticed a regression due to this change.

Here's sample code which works:

```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> c = f.createIfcColumn()
>>> m = f.createIfcMaterial()
>>> r = f.createIfcRelAssociatesMaterial(**{"RelatedObjects": [c], "RelatingMaterial": m})
>>> c.HasAssociations
(#3=IfcRelAssociatesMaterial($,$,$,$,(#1),#2),)
```

However, I have more complex code (which I haven't yet simplified into a minimum working example) which does similar to the above code, but the result is that `c.HasAssociations` returns an empty tuple. If I revert https://github.com/IfcOpenShell/IfcOpenShell/commit/0f39b0939628660c5705f7b7b4917c16bb9e4fa0 then it works again.

Note that I haven't yet tested the impact of https://github.com/IfcOpenShell/IfcOpenShell/commit/99e74533c3c45c90238c7c07ee4439aefb4eb888 so perhaps when the bot build is ready it may "just work" again.

Thoughts? Any ideas what might trigger it? I will continue to try and isolate it on my end too.

**Comment by aothms** [comment]
> Note that I haven't yet tested the impact of 99e7453 so perhaps when the bot build is ready it may "just work" again.

I noticed a very similar issue. tests.py failed on Travis related to inverse attributes https://app.travis-ci.com/github/IfcOpenShell/IfcOpenShell/builds/232998583#L1429 So I'm pretty optimistic it'll be resolved.

**Comment by Moult** [comment]
Awesome! Will test again when the bot build is up and will close if all good!

**Comment by Moult** [comment]
Confirming that latest build fixes it! Hooray!

**Comment by aothms** [comment]
thanks for checking @Moult
