### ISSUE TITLE
IFCConvert: Unable to write output file error with ├ character in filename

### ISSUE THREAD

**Issue by btourman** [IfcOpenShell/IfcOpenShell#1572]
Hi,

I tried to convert an ifc file to dae with ifc-convert with ├ character in filename, but I have this output error :
`Unable to write output file '/IfcFiles/exa├mple.dae', see '/IfcFiles/exa├mple.dae.tmp.ifcopenshell.XBIQEQND.tmp' for the conversion result.`

If I remove this character, it works fine !

Is it possible to fix that or it may not be possible ?

Thanks

[exa├mple.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6831230/exa.mple.ifc.zip)

**Comment by aothms** [comment]
You're right, this was a bug. Introduced here https://github.com/IfcOpenShell/IfcOpenShell/commit/fd9ba0d2431d0a153abb75133454e6b2b633b11a where the temporary filename was actually appended to it instead of replacing the unicode name.

Thanks. This is fixed now and will be available in the next 0.6 build.
