### ISSUE TITLE
Should IfcHierarchyHelper::getSingle<> assert if there are multiple instances?

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#1573]
IfcHierarchyHelper::getSingle<> returns 0 if the list of instances by type does not have exactly one element.

Would adding an assert be helpful to developers? If you think there is exactly one instance of a type but there isn't an assert would help you detect that situation and avoid bugs.

```
	template <class T>
	T* getSingle() {
		typename T::list::ptr ts = instances_by_type<T>();
		if (ts->size() != 1) {assert(false); return 0;}
		return *ts->begin();
	}

```

**Comment by aothms** [comment]
I guess we shouldn't change the behaviour like this of an existing function.

Developers might be using things like `if(getSingle<T>()) {}` and we don't want that to suddenly break.

Feel free to add another function or add an argument like `force`/`required` or whatever defaulting to false that does the `assert()` then true.

Ultimately I think a C# LINQ (that's syntax so not quite) or Java stream api would be quite nice, so that we don't need this so hardcoded and constrained, but we would write something like:

```
IfcWall* my_wall = file.instance_by_type<IfcWall>()
    .filter(...)
    .sort(...)
    .first()
    .orThrow();
```

**Comment by RickBrice** [comment]
Good point about breaking existing code. I guess if the caller is making an assumption then the assert should be in the calling code. 

`
auto object = getSingle<T>;
assert(object != nullptr);`
