### ISSUE TITLE
Creating a drawing

### ISSUE THREAD

**Issue by flashroyal88** [IfcOpenShell/IfcOpenShell#1574]
Creating a drawing is giving following error 
![BIM](https://user-images.githubusercontent.com/87669489/126210740-72a3bcc7-558c-4feb-b3ec-b2f65d8a05c3.jpg)

**Comment by Moult** [comment]
I've come across this before, are you using the stable or the daily builds?

**Comment by flashroyal88** [comment]
> I've come across this before, are you using the stable or the daily builds?

I’m using stable builds

**Comment by Moult** [comment]
So it is likely that I have already fixed this, but I will double check. If so, I'll close this issue.

But as a whole, creating drawings right now is a huge state of change because the underlying system is being swapped out for a new core. So even if this did work, you probably wouldn't get very far with drawings.
