### ISSUE TITLE
Creating new instances of Enum types causes crash

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#1579]
I'm trying to create a new IfcFacilityPart object. Parameter 10 is an IfcFacilityPartTypeSelect of which I'm trying to use the IfcBridgePartTypeEnum.

```
   auto superstructure = new Schema::IfcFacilityPart(IfcParse::IfcGlobalId(), owner_history, std::string("Superstructure"), boost::none, boost::none, bridge_placement, nullptr, boost::none, 
      Schema::IfcElementCompositionEnum::IfcElementComposition_PARTIAL, 
      new Ifc4x3_rc3::IfcBridgePartTypeEnum(Schema::IfcBridgePartTypeEnum::IfcBridgePartType_SUPERSTRUCTURE), 
      Schema::IfcFacilityUsageEnum::IfcFacilityUsage_LONGITUDINAL);
```

The following causes a crash because the `data_ `object has not been allocated.
` new Ifc4x3_rc3::IfcBridgePartTypeEnum(Schema::IfcBridgePartTypeEnum::IfcBridgePartType_SUPERSTRUCTURE)`

The generated implementation is 
```
Ifc4x3_rc3::IfcBridgePartTypeEnum::IfcBridgePartTypeEnum(Value v) {
    IfcWrite::IfcWriteArgument* attr = new IfcWrite::IfcWriteArgument();
    attr->set(IfcWrite::IfcWriteArgument::EnumerationReference(v,ToString(v)));
    data_->setArgument(0,attr);
}
```

and `data_ `is NULL. The base class does not allocate (which seems to be by design).

This appears to be a problem in all `Ifc__TypeEnum `classes for both the `Value `and `std::string` version of the constructors.

Should the implementation be changed by adding the following before `data_->setArgument(0,attr);` ?
`_data = new IfcEntityInstanceData(IFC4X3_RC3_IfcBridgePartTypeEnum_type);`

**Comment by RickBrice** [comment]
To follow up, I've been trying to work around this issue by creating a new `IfcBridePartTypeEnum `object using the constructor that takes `IfcEntityInstanceData `as an argument - basically trying to simulate the constructor that is accessing a null `data_ `object.

```
   //auto bridge_part_type = new Schema::IfcBridgePartTypeEnum(Schema::IfcBridgePartTypeEnum::IfcBridgePartType_SUPERSTRUCTURE);
   IfcWrite::IfcWriteArgument* attr = new IfcWrite::IfcWriteArgument();
   attr->set(IfcWrite::IfcWriteArgument::EnumerationReference(Schema::IfcBridgePartTypeEnum::IfcBridgePartType_SUPERSTRUCTURE, Schema::IfcBridgePartTypeEnum::ToString(Schema::IfcBridgePartTypeEnum::IfcBridgePartType_SUPERSTRUCTURE)));
   auto data_ = new IfcEntityInstanceData(&Schema::IfcBridgePartTypeEnum::Class());
   data_->setArgument(0, attr);
   auto bridge_part_type = new Schema::IfcBridgePartTypeEnum(data_);
```

Deep inside `data_->setArgument(0,attr)` a call to `attribute_by_index(i)` is crashing. This suggests my proposed solution above isn't valid.

Perhaps I'm creating the IfcFacilityPart incorrectly.

Any ideas?

**Comment by aothms** [comment]
You're fully correct. There was just one piece of the puzzle missing f2f4057c98338170277708453a676bcbc0371843. It has to do with the fact how enumerations in C++ are basically just ints. But for serialization we need to reconstruct the string representation from it. This is impossible from just the C++ enumeration value itself. That's were this attribute_by_index thing came in to look up the string representations from the schema. The assumption was there was when an enumeration value was set on an EntityInstanceData, it would mean that it we're dealing with an entity type (this was the case until 4x3rc3 or 2). Hence the `type()->as_entity()` there in the enumeration case of the switch handling. 

When I regenerated code, it seemed I introduced some changes in the RC3 code. Which version did you use? I didn't regenerate code for RC4, because it isn't really finalized yet. This is something you apparently have to deal with in bSI that an RC is never just an RC. I took this version of RC3 from May https://github.com/bSI-InfraRoom/IFC-Specification/blob/main/IFC4x3_RC3.exp

**Comment by RickBrice** [comment]
I'm going to be away from my computer for a week and a half. I'll report back on the schema I used for RC3. I tried to regenerate the code for RC4 but it has a bug and crashes the Python code. I posted the issue on bSI-Intra Documentation GitHub site.

**Comment by RickBrice** [comment]
Sorry for the delay - I used the RC3 schema dated 17 Feb 2021.
