### ISSUE TITLE
BlenderBIM: alt-D doesn't seem to work

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1587]
'duplicate linked' doesn't seem to work.

video: https://www.dropbox.com/s/u6ajo99sqfqn9qh/2021-07-25_11-28-46.mp4?dl=0

**Comment by Moult** [comment]
This is intentional. Roughly, Blender linked duplicates = IFC mapped representations. The only time IFC allows mapped representations (up for debate, but from experience in the side effects in authoring, it seems this was the intention) is when a type has a representation.

So in other words, if your type (e.g. IfcWallType) has a representation, all instances of that type will have linked meshes. If not, then the BlenderBIM Add-on purposely breaks the connection.
