### ISSUE TITLE
BlenderBIM: arrays not exporting

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1591]
video: https://www.dropbox.com/s/9g1m1ra2ncfcn7q/2021-07-25_20-07-32.mp4?dl=0

**Comment by Moult** [comment]
Yep, array support was dropped when the new parametric system was put in place, because it could be handled in a much more intelligent way than in the past. Similar to how now we can recreate certain parametric behaviour with walls and slabs.

I have yet to fully work out the best way to describe an array in IFC, but I'll crack it!

**Comment by theoryshaw** [comment]
Yes, would be awesome to translate an array into IFC!.. that and mirroring. :)

**Comment by Moult** [comment]
Note to self: reuse the geometric representation item with a cartesian transformation, but with a pset describing the array attributes. This could work in FreeCAD too.

**Comment by theoryshaw** [comment]
Could we use [IfcLinearPlacement](http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcLinearPlacement.htm) to recreate array modifiers in Blender, upon import?

**Comment by aothms** [comment]
Linear placement is actually still only one placement. I think that's the fundamental issue, there simply isn't a trick in IFC for multiple instantiation. It is being talked about though because the problem is apparent in linear placement, e.g the sleepers in a railway track, ideally you'd want some array-along-curve placement, but it doesn't exist. A single placement places a single object.

**Comment by Moult** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/commit/62229b032ec708d2753c33fda787d13a653b490c

**Comment by theoryshaw** [comment]
wow... i think i cried a little.
