### ISSUE TITLE
BlenderBIM: interconnecting the names for IfcMaterials, IfcStyledItems, and Blender Materials. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1592]
It would be nice if the IfcMaterial name changed, that it changed the Blender names, and IfcStyledItem name as well.  Or at least have an option/preference where all these names are interconnected.  I have a feeling, a majority of times, users will want all these names to be the same.

---

Would be nice if the IfcMaterial name is over 64 characters, it just truncates the blender material name to 64 characters--since that's the character limit for Blender material names.

**Comment by theoryshaw** [comment]
in our 3D detailing workflows, a lot of times we have material names over 64 characters long
![image](https://user-images.githubusercontent.com/507113/126924029-8fdb512e-e28a-4698-a026-61cfc106aeb0.png)

**Comment by Moult** [comment]
Yeah I guess this scenario comes because material names are not really correctly used when trying to integrate with Revit. The "correct" way is for the material name to be a short tag / label (e.g. CON01, PNT01) etc, and the long name be in the description. Unfortunately with Revit the only thing they read is the style name, hence this issue becomes a lot more prevalent.
