### ISSUE TITLE
Question: Can I use CLI IfcConvert to convert IFC4 to IFC2x3?

### ISSUE THREAD

**Issue by Begalov** [IfcOpenShell/IfcOpenShell#1593]
Since blenderbim can create and export both type of projects I assume that it is possible some how. But I had read CLI help output and cant find options for IFC2x3 conversion.

**Comment by Moult** [comment]
@Begalov the IfcPatch migrate script (accessible via the BlenderBIM Add-on UI in the scene properties) lets you convert from IFC2X3 to and from IFC4. However, although I have successfully used it to upgrade on full projects, downgrading is not fully complete, and does not support certain entities. Currently, I only use downgrading for partial snippets where I know the contents. Since you likely are dealing with a full project, there is a high chance you may have those entities and so it will not work for you.

The biggest entity to deal with is the tessellations, which IFC2X3 doesn't have. Would you be interested in helping write code for it? The code is in the ifcopenshell.util.schema migrate class.

**Comment by aothms** [comment]
IfcConvert mostly does only conversion of geometry from IFC to certain geometry formats. There isn't a lot (yet) for IFC to IFC conversion.

These kind of tasks often require a high amount of customization, like mapping tables. For that reason a scripting language that can be easy adapted is more suitable.

**Comment by Moult** [comment]
Bump. @Begalov would you mind trying the IfcPatch recipe and see if it works for you? If you're lucky, you're not using any complex new IFC4 entities. If not (which is more likely) perhaps you can provide a test file for us to make a checklist of downgrades to build?

**Comment by Moult** [comment]
Closing as it's solved in theory, but we won't know of case by case problems with downgrading until we get them reported.
