### ISSUE TITLE
BlenderBIM : IFC Patch panel : Improve UI/UX for arguments field

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1622]
I've stumbled upon https://community.osarch.org/discussion/447/import-and-merge-ifc
Regarding
![image](https://user-images.githubusercontent.com/25156105/127863824-b2b59906-67ab-4348-b016-1c539376fa28.png)
The UI is pretty straightforward apart from the `Arguments` field which requires the user to manually input a file path with square brackets and quotations marks, and I assume needs to escape \  or use /. (converted afterwards using json deserializer)
`["c://path/to/file.ifc"]` 

- Might be better UX wise to instead provide the user with a file directory viewer (like the 2 other fields) to look for their file and take care of escaping characters and adding the extra brackets and quotations backstage
- The field is plural, meaning there might be multiple arguments ? In this case could be something akin to this solution for multi input string fields :
![image](https://user-images.githubusercontent.com/25156105/127770128-8c9d0b49-ef2e-475a-a71e-c64752ff0607.png)

I'd like to help on this topic if you think it's relevant to tackle this now.

**Comment by Moult** [comment]
This is a great idea! By the way, I've sent you an invite for write access so you can commit directly instead of PRs. Feel free to commit throughout the Python portion of the code. If you are going to commit to the C++ portion, submit a PR so that @aothms can review first :)

So how IfcPatch works is that you can distribute a small contained IfcOpenShell script to manipulate a file and it's a very minimal wrapper that provides a standardised way to run, input a file, and args, and get a file out. This means that some IfcPatch scripts (which I've been calling recipes) have zero arguments, and some have quite a few.

Therefore, creating a JSON parsed args input was the lazy way to support it, but not very user friendly.

The more user friendly approach I would propose is to:

 1. Add docstrings and type hints to the IfcPatch recipes themselves so that arguments are well documented. Here's an example of docstrings and type hints used in a similar manner for the IfcOpenShell API: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/project/create_file.py
 2. Write a function that parses these docstrings and type hints, if they exist. Here's similar code which extracts docs for the IfcOpenShell API code, which you can massage for this purpose: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/__init__.py#L102-L149
 3. If the parsing is successful, upon update of the IfcPatch recipes CollectionProperty, it can show a little description of the IfcPatch for user guidance, as well as dynamically generate zero or more arguments in a CollectionProperty with the correct data types. The collection property can use this property group: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/prop.py#L154 - as it supports all of the primitives. Of course, if the type hint of a property suggests a file path, perhaps a new operator needs to be added - but keep the Attribute property group simple, as it is used everywhere for generated typed fields.

Hope this approach I'm proposing makes sense. Hopefully this will result is 1) documentation for the IfcPatch recipes, 2) improved static code analysis, and  3) improved UX in Blender :)

**Comment by Gorgious56** [comment]
OK, thanks for the explanation, I understand more and that's not as simple as I first thought, as always ! I'll check this out.
My C++ skills are very limited so I'll stick to the python portion for now. :)

**Comment by Gorgious56** [comment]
First draft of the `Attribute` CollectionProperty new User Interface !

![BSE_35](https://user-images.githubusercontent.com/25156105/128026213-d374d69f-76f5-4c58-beaa-ad596a7b04f1.gif)

Next up :
- Provide an enum for the user to generate auto-filled arguments names and types (will need to parse arguments like you hinted)
- Add a file browser operator next to the output file argument ?
- Polishing UI

**Comment by Gorgious56** [comment]
After nosing a bit around in the files, I'm confident I can achieve steps 2, 3, 4 but step 1 is really out of my league. I'm not educated enough on ifcopenshell / patching workflow and don't have the data to test the code so I'm navigating by sight...

I could use a dummy Patcher class that does exactly what I want and iterate over that, and in the end people knowledgeable enough with the actual patcher recipes could add to the docstring and type hints, linking everything together.

**Comment by Moult** [comment]
Isn't this a bit overcomplicated? I think the "Data type" field does not need to exist, it'll simply be generated based on the auto detected type hint. Same with the name field - it should not display as an editable field - the name can be used in place of the "value" text label, though. There probably isn't a need to have the "+" or "-" either since the number of arguments will be autodetected and the user shouldn't be adding or removing.

E.g. if it detects a single argument, it could just show this:

![image](https://user-images.githubusercontent.com/88302/128098621-30657d16-b723-4959-90ad-f13f340d9258.png)

And yes, I agree that step 1 might be a bit too much, so, ping @kaiaurelienzhu would you be up for it? I've done one as a sample: https://github.com/IfcOpenShell/IfcOpenShell/commit/4184cff1a0b790694923cace8eeb105dc6fba953 - in this sample, basically it should detect the argument named "query" (skip the first three: src, file, logger, those are all boilerplate), the data type "str", and default value of .IfcWall.

@kaiaurelienzhu it's basically the exact same drill as the API.

**Comment by Gorgious56** [comment]
Yeah that was overcomplicated, the type bindings and number of arguments will be taken care of internally. That was just to a warm up exercise ^^
Thanks for the example, I'll iterate on that then !
If it's possible to detect default arguments, do we initialize the fields with them filled in or keep them blank ? (or let the user decide, maybe with an operator to auto-fill with defaults ?)

**Comment by Moult** [comment]
it's initialise the fields with them filled in I reckon.

In the code I linked to above, these two lines detect default args: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/__init__.py#L121-L122

**Comment by Moult** [comment]
@Gorgious56 I'd prefer an explicit "Load recipe" operator button if it avoids doing "update" magic.

**Comment by Gorgious56** [comment]
Progress report 2 : We're getting there !

I've modified slightly your example code to accommodate for different scenarii :

```
    def __init__(self, src, file, logger, query: str = ".IfcWall", number_of_elements: int = 2, wall_height: float = 3.15, is_void: bool = True):
        """Extract Elements

        Extract a subset of elements from an existing IFC data set and save it to a new IFC file.
        This creates a new line of description
        And a new one
 
        :param query: A query to select the subset of IFC elements.
        :param number_of_elements: Max number of exported elements
        :param wall_height: Target height the walls should be set to
        """
        self.src = src
        self.file = file
        self.logger = logger
        self.query = query
```

Using the Panel with the completed docstring Patcher :

Note the class description is filled in just after the recipe selector.
If an argument has a description in dosctring, it is filled alongside the value field. Otherwise (like the last argument, the argument name is used)

![BSE_36](https://user-images.githubusercontent.com/25156105/128195360-0bda9fa1-51b0-41e6-bc21-6c961b8cc4b3.gif)

I think it's pretty much working as expected until that point.
Todo list :
- Flatten the args into a json parsable string
- Improve UX
- Polish UI

Update :
After recording the GIF I realized the actual argument name is supposed to be semi-human readable, so why not display the description instead when it's available. Since the user doesn't have to fill a list with the argument name, they don't HAVE to know the backstage argument name.

![image](https://user-images.githubusercontent.com/25156105/128196387-834e4b35-a35b-4ccf-b8f7-df70380284fe.png)

**Comment by Moult** [comment]
Looking much better! I'm not sure about the label since it may get rather long.

Can the recipe's prop update method refresh the patch arguments? Then we don't need the "Update IFC Patch arguments" button?

**Comment by Gorgious56** [comment]
OK, I think I managed to get the final draft as intended !

![BES_32](https://user-images.githubusercontent.com/25156105/129474594-52d6ded1-92c0-460e-90df-23145999498f.gif)

The gist of it :
- On the first iteration, the Recipe enumerator will fetch all recipe files and retrieve the description of each Patcher class if it exists. It will then use this as a description for each individual recipe enum item, which is displayed when hovering over the field for a second or two.
- When changing the recipe enum item manually, it will automatically call the "UpdateIFcPatchArguments" operator which will take care of initializing and displaying the arguments if they are correctly type hinted and set attribute default if they are filled in too. Otherwise it will display the default "Arguments" field which is supposed to be filled in using a json list syntax `["a","b","c"]`

I think this solution is intuitive, doesn't require more user interaction and doesn't add too much space on screen.

However I'd like to point out I refactored the Attribute code as I felt handling the different type switching to get the correct value should not be delegated to the different modules. Managing it directly in the Attribute class leads to fewer lines of code, and total agnosticity from the other modules to the way attributes operate under the hood. 

Example :

    def draw_editable_ui(self, context):
        for attribute in self.props.constraint_attributes:
            row = self.layout.row(align=True)
            if attribute.data_type == "string":
                row.prop(attribute, "string_value", text=attribute.name)
            elif attribute.data_type == "enum":
                row.prop(attribute, "enum_value", text=attribute.name)
            if attribute.is_optional:
                row.prop(attribute, "is_null", icon="RADIOBUT_OFF" if attribute.is_null else "RADIOBUT_ON", text="")

becomes

    def draw_editable_ui(self, context):
        draw_attributes(self.props.constraint_attributes, self.layout)

Or 

    def load_from_pset_data(self, pset_data):
        for prop_id in pset_data["Properties"]:
            prop = Data.properties[prop_id]

            value = prop["NominalValue"]
            if isinstance(value, str):
                data_type = "string"
            elif isinstance(value, float):
                data_type = "float"
            elif isinstance(value, bool):
                data_type = "boolean"
            elif isinstance(value, int):
                data_type = "integer"
            else:
                data_type = "string"
                value = str(value)

            new = self.props.properties.add()
            new.name = prop["Name"]
            new.is_null = prop["NominalValue"] is None
            new.data_type = data_type

            if data_type == "string":
                new.string_value = "" if new.is_null else value
            elif data_type == "integer":
                new.int_value = 0 if new.is_null else value
            elif data_type == "float":
                new.float_value = 0.0 if new.is_null else value
            elif data_type == "boolean":
                new.bool_value = False if new.is_null else value

becomes


    def load_from_pset_data(self, pset_data):
        for prop_id in pset_data["Properties"]:
            prop = Data.properties[prop_id]

            value = prop["NominalValue"]
            new = self.props.properties.add()
            new.set_value(value)
            new.name = prop["Name"]
            new.is_null = value is None
            new.set_value(new.get_value_default() if new.is_null else value)


I know you instructed me not to touch the Attribute class too much but I really feel this refactor is good in the long run. If you think it's not needed, I'll go back and revert the changes. That's why I'll propose this as a Pull Request in order for your to feel the scope of these changes.

**Comment by Moult** [comment]
@Gorgious56 just skimmed through your post because it's late here so ignore this if it doesn't make sense: but did you see https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/helper.py#L11-L34 and is it useful to you?

**Comment by Moult** [comment]
Ah yes I just read through a bit more (will do a proper read tomorrow) and I 100% agree with your refactor - the old bunch of if-statements are a remnant of the old code when the Native IFC system was prototyped earlier this year. I tend to refactor "as-I-go" rather than waterfall.

From what I've read so far, I really like your changes, but I will do a final sanity check tomorrow morning before merging! Thanks so much and this is really great work!

**Comment by Gorgious56** [comment]
One last thing I forgot to ask while writing this, is there a preferred way to use relative or absolute imports ? 
`from . import helper` or `import blenderbim.bim.module.patch.helper` 
Also, do we import module, then pick the functions we want, or do we directly import the functions from the module
`import blenderbim.bim.helper`
then
`blenderbim.bim.helper.draw_attributes()`

OR

`from blenderbim.bim.helper import draw_attributes`
then
`draw_attributes()`

Sorry if it's already written somewhere, please point me in the right direction if there are such guidelines ^^

**Comment by Moult** [comment]
This has never been documented, but I think we should prefer absolute imports as per PEP 8.

As for importing, I also prefer `blenderbim.bim.helper.draw_attributes()` instead of `draw_attributes()`, because the latter loses its context and presents itself as a global. Especially because Python as a language lets you mix functions and classes in the same file I like to differentiate between imported functions and those from within the same file.
