### ISSUE TITLE
BB: error when importing from Demo Library

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1656]
vid: https://www.dropbox.com/s/hjtysdbtgsrjj6a/2021-08-15_09-47-14.mp4?dl=0
blenderbim-210815

**Comment by Gorgious56** [comment]
Sorry I intended to add a message but got distracted in the process ^^

I took the initiative to fix this, from the code I gathered this particular operator (and a few others in the same file) need a IFC file to be setup before being executed, hence the error. I added a check when displaying the button to prevent it.

The panel could do with a label displaying why the operators are now grayed out from a user perspective. Food for thought

**Comment by Moult** [comment]
Thanks and the fix is correct! (I added a note about project libraries though)

**Comment by theoryshaw** [comment]
So i created a new file, and saved it.  I was able to import objects from the library. 

I then closed the file, and then opened it again, but the types in the library were grayed out.

![image](https://user-images.githubusercontent.com/507113/129574650-cb38397c-0d8d-4086-bad3-2fddacfe1a5f.png)

**Comment by Gorgious56** [comment]
Hehe, that's why I suggested the user should get notified why it is grayed out. Maybe in the operator tooltip that gets displayed when hovering over the button ?

The solution is to initialize a new file by clicking on "Create Project" in the IFC Project panel right on top of the Project Library panel. It will also automatically be setup if you go File > import > ifc

**Comment by theoryshaw** [comment]
gotcha.. 

was weird, i had created the project before, but it didn't 'take'.  Whatever. :) 
Thanks!

![image](https://user-images.githubusercontent.com/507113/129580305-44171909-ab00-4ee1-b8b6-53cb1ee8b35b.png)
