### ISSUE TITLE
BlenderBim : Batch-adding Objects to a system and system inspection in the Object properties

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1685]
Currently the operator used to assign an object to a system only does so to the active object. 
![image](https://user-images.githubusercontent.com/25156105/130433133-1769bf35-60a1-4591-877d-f8659ae9aad1.png)

It may be desirable to add a big number of objects to a system, which is cumbersome with this behaviour. Is it worth tweaking the operator to add every selected object or was it designed that way on purpose ?

Secondly, it may be nice to have a panel in the object's properties to see which systems it belongs to and similar interface to assign/unassign them. That way we a many/many interface.

I can work on it if you feel like it's relevant.

**Comment by Gorgious56** [comment]
I think the same question applies to IFC Groups :
![image](https://user-images.githubusercontent.com/25156105/130440445-1f8726cb-9596-41dd-9653-91d4e864b2fb.png)

**Comment by Moult** [comment]
Yes, definitely worth tweaking the operators for both, as well as adding a panel in the object properties. Go for it :)

**Comment by Gorgious56** [comment]
Nice ! Given a blender object, what's the most graceful way to retrieve all the systems or groups it belongs to ? I'm a little lost on the ifcopenshell api.

**Comment by Gorgious56** [comment]
During refactoring I arrived to a slightly different approach. I removed the possibility to assign objects to systems from the scene properties interface, and created a new panel in the object properties. I think this is more in line with the other types of data that can be linked, like constraints, documents...
So the scene panel is used only for adding / removing systems, changing their properties, and selecting all objects related to the system because that makes sense.

![image](https://user-images.githubusercontent.com/25156105/130467826-27e4d8ad-71ce-4667-99c4-7385ca6e4c1d.png)

And in the object properties, 

![image](https://user-images.githubusercontent.com/25156105/130468649-76be0cd6-2e5f-4d76-b004-5e41059d1b47.png)
-->
![image](https://user-images.githubusercontent.com/25156105/130468787-902ad0ce-6006-4af7-ab40-63a711ec67d3.png)

Very similar to how it works with the Constraints and Documents panels in the object properties, however there are small caveats :
The interface is updated relatively to the active object. (That's expected I think)
But the operators will be applied on all selected objects. (Assign / Unassign) I think that may or may not be the expected behaviour, depending on who you're asking, but we should commit to one behaviour or the other because using the + icon in the Constraints or Documents panel will only add the selected item to the active object, which would feel inconsistent.

As an aside question, I'm a little worried about Panel bloat, because I'm planning to add another one for groups. Would there be a point in grouping these into their own subpanel or do you think it's still manageable ?

Would be glad to know your pov on this one. :)

**Comment by Moult** [comment]
Actually operators applied on all selected objects is something already done on a variety of operators in the object panel already. I think this is good expected behaviour.

Don't worry about panel bloat for now. Panels are segregated per discipline. Sooner or later, a "UI Config" needs to be built (perhaps in the add-on preferences?) which lets you enable or disable panels altogether. There will be presets for certain disciplines. For example, if you're an architect, the systems, cost, LCA, scheduling, documents, etc can all be hidden. This will drastically cut down the number of panels. If you choose the "cost planner" preset, similarly, it will hide a whole bunch of panels too. (well, more likely the system will be designed inversely - i.e. everything is invisible by default, and enabling a discipline's preset will make those panels visible).

When extracting data from IFC, the IfcOpenShell API "Data" class is used. It is a static class that has three purposes: 1) it's effectively acts as a dumb cache of IFC data for the UI so that the UI doesn't fetch new IFC data on every draw() call and doesn't need to bloat the Blend file with Blender properties, and 2) it casts intelligent complex IFC data into dumb primitives so that the Blender code doesn't need to be smart (e.g. entities turn into integer IDs. IFC DateTimes turn into Python datetimes, units turn into symbols, etc) and 3) it performs auxiliary useful calculations that make sense when retrieving a bunch of data (e.g. in cost schedules, it'll calculate totals, subtotals, aggregate component costs, etc). Note that I have some reservations about its system design as a static class and its subsequent evolution into a "god class" for data retrieval. But I haven't mustered the motivation to rearchitect it yet.

Nevertheless, it does work for now. Each module has its own Data class. Here is system Data class: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/api/system/data.py

So if you wanted a list of systems, you could check `Data.systems`. If you want to find a list of systems that a product is part of, you can use `Data.products[obj.BIMObjectProperties.ifc_definition_id]`, which will give you system ids can you can then get more data from `Data.systems[system_id]`.

**Comment by Gorgious56** [comment]
Ok duly noted, thanks for the explanation ! It makes total sense. I'm about to PR the changes.
I think afterwards I'll work on making sure all operators apply to selected objects in the object properties panel then.
