### ISSUE TITLE
BlenderBim Library : Issues in IfcProfileDef hierarchy

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1707]
I think there's a problem in the tree structure of IfcProfileDef types in the demo library :
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/libraries/blenderbim-demo-library.ifc

![BSE_41](https://user-images.githubusercontent.com/25156105/131330411-81417ae4-09f4-4d3e-bc76-7a9b9a151a73.gif)

IfcCircleProfileDef and IfcRectangleProfileDef are apparently referencing themselves, leading to possibly infinite recursion when traversing the tree. Also their children IfcCircleHollowProfileDef and IfcRectangleHollowProfileDef are also present at the same level as themselves.
I nosed around the Ifc file but I'm not fluent enough in ifc to solve the problem by tweaking values :)

**Comment by Moult** [comment]
Yeah having their children at the same level isn't an issue, but the self referencing certainly is.

IFC entity classes (e.g. IfcRectangleProfileDef) have a hierarchical nature. The way the project library works is it lists all subtypes (regardless of how deep the subtype is) of the class you filter by. This "regardless of how deep" means that you may see both children and grandchildren, if applicable - however, it sure beats clicking through a heavily nested tree! So if you start with `IfcProfileDef` you will see all subtypes. In the majority of practical cases, the IFC class tree is abstract until you hit a leaf class. But not always. This "not always" is where the bug comes from.

**Comment by Gorgious56** [comment]
Alright, that's interesting to know ! Quick fix :)
