### ISSUE TITLE
BlenderBim WorkSchedule : Removing a parent task while editing a children doesn't disable task edition

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1717]
Here are two gifs of the problem :
![BSE_46](https://user-images.githubusercontent.com/25156105/131670602-b77de638-4757-4d39-afc1-89c025abd45c.gif)
![BSE_47](https://user-images.githubusercontent.com/25156105/131671808-60d1227c-eb0b-4728-9016-f276d5987e49.gif)

Removing a parent task from a Work Schedule deletes all its children. However if one of its children is being edited at the same time, the "editing state" is never disabled, leaving the UI List in a broken state since we need to access the now-deleted task to disable it.

I don't know how to fix this since I understand there can be complicated hierarchical relationships between tasks.
So either maybe :

- Prevent removing parent tasks while a children is being edited
- Force-disable the "editing state" when the currently-edited task has been removed
- Display the "Disable Editing" button at all times, not only when the currently edited task is selected

Depending on how easy it is to fetch hierarchical relationships between tasks using the API,

**Comment by Moult** [comment]
Yes known issue and there are similar problems in cost and resourcing. I'm still experimenting with the UI right now so as I explore options there are these "incomplete" states which occur - those buttons used to show on every single row in the UIList which although worked, was extremely ugly. Not just hierarchical relationships, there are also cross-discipline relationships (e.g. a resource may be linked to a task, or a task may be linked to a cost item), and I haven't yet confirmed all the relationships (even in the IFC schema, this is unexplored territory).

Due to the complexities of these layouts, I'd also like to explore whether or not unit tests are practical to cover all scenarios.

**Comment by Gorgious56** [comment]
Alright so I'll hold off stress-testing cost & work resources interface for now then. :)
Do let me know if I can be of help once it's stabilized enough

**Comment by Moult** [comment]
To prevent this dragging on forever, I'm happy if you'd like to help implement solution 2 or 3 :)

**Comment by Gorgious56** [comment]
Sure I'll start poking around :)
