### ISSUE TITLE
Feature Request: BIM IFC Viewer

### ISSUE THREAD

**Issue by Mannshoch** [IfcOpenShell/IfcOpenShell#1726]
According to the [Discussion](https://github.com/IfcOpenShell/IfcOpenShell/discussions/1724). I create this Request. I know It's not a current Focus but hope is all around. 

## Why do I need this Feature?
Because of the BREP data. Currently, there are some Viewers available but none of these Viewers currently support the ability to determine between Tessellation and BREP data inside the IFC. IF I get IFC Data I have to check if I get the BREP oft the correct part of the Building. Most sender of IFC Files do not know how to export Data for CAD user, so I often have to reject the files and phone with them until the time I finally get the correct data. (so annoying!)

To be able to use IFC inside a CAD Software you need BREP data. Many times you get a whole Building as IFC but to be able to find out if that IFC file contain all needed data as BREP you need to Import that data in CAD Software. Depending on the Size of the building, you need much time to convert the file because CAD Software fully precess the BREP data. 

## What ability does that Viewer should have
According to my knowledge about IFC, there are three objects that could be inside an IFC. The Information about the bodies, Tessellation Data of the bodies and the BREP data of the bodies.
The Viewer need:

### Priority 1:
- A Graphic area where you could show the IFC
- Buttons to switch between Tessellation and BREP data.
- On Installing on Windows the viewer should associate at least IFC to the viewer.

For my use case that would be enough.

### Priority 2:
- A Cut feature to cut through the Bodies  
- A Measure tool 
- Info pane that show IFC data according to a selection
- If right-clicking on such an Information allow showing only files with the same Value
- A Button to temporary switch the IFC-Viewer to a full Blender. 
(Sort of Easter Egg for normal user that are not familiar with Blender)

#### Other Ideas:
- If GPS Data is available, render sunlight at Noon
- Allow exporting the IFC to another BREP file type e.g. STEP/SAT/... . 
Either the whole file or according to the currently showing Data .

**Comment by Moult** [comment]
Ping @Gorgious56 any ideas on how the BlenderBIM Add-on might be packaged as a viewer associated with a filetype?

**Comment by Moult** [comment]
@Mannshoch by the way for the cut feature, have you tried the Temporary Section Cutaway feature in the output properties tab? Also, for the Measure tool, have you tried Blender's built in measure tool, or the CAD Transform Add-on?

**Comment by Gorgious56** [comment]
That honestly surpasses my skillset ^^

Although as noted in the discussion linked to this thread, the whole blender package is already pretty lightweight and portable compared to other packages. 

There were talks about a "Blender 101" project before 2.8 :

https://code.blender.org/2016/12/the-blender-101-project-and-you/

The idea is to selectively strip blender from the features you don't want and distribute only that for your users. I thought the project was dead but it seems to have been revived recently since I saw Pablo talk about it in a recent today live stream.

**Comment by Moult** [comment]
I'm thinking an application template, a little exe (Pyinstaller?) that simply calls blender with a background python script which preselects the application template. I haven't had the time to test the theory though.

**Comment by Moult** [comment]
I'm closing this because I think this is now implemented:

 - This was in 2021 before the big UI redesigns. Most of the Blender UI is tucked away neatly now, and we only show IFC stuff by default.
 - We have a graphical area to show the IFC
 - You can switch between representations
 - We have a file type association feature that is cross platform
 - We have a cutting plane feature
 - We have a measure tool
 - We have an info pane
 - You can search similar, or click on property values to select elements with the same value
 - Workspaces can switch to other Blender layouts
 - We have solar analysis with connections to site long/lats
 - We have the extract elements patch recipe, and IfcConvert for STP conversion.

**Comment by Mannshoch** [comment]
May publish a Blender installation package at
https://ifcopenshell.org/downloads.html
### If you need an IFC Viewer
