### ISSUE TITLE
v0.7.0 inverse attribute is empty

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1734]
Example code - the `HasSubContexts` should not be empty, but it is.

```python
import ifcopenshell

class Usecase:
    def __init__(self, file, **settings):
        self.file = file
        self.settings = {
            "context": None,
            "subcontext": None,
            "target_view": None,
        }
        for key, value in settings.items():
            self.settings[key] = value

    def execute(self):
        print('adding context')
        parent = [
            c
            for c in self.file.by_type("IfcGeometricRepresentationContext")
            if c.ContextType == self.settings["context"]
        ]
        if not parent:
            self.create_origin()
            context = self.file.createIfcGeometricRepresentationContext(None, "Model", 3, 1.0e-05, self.origin)

            project = self.file.by_type("IfcProject")[0]
            contexts = []
            if project.RepresentationContexts:
                contexts = list(project.RepresentationContexts)
            contexts.append(context)
            project.RepresentationContexts = contexts
            return context
        parent = parent[0]
        return self.file.create_entity(
            "IfcGeometricRepresentationSubContext",
            **{
                "ContextIdentifier": self.settings["subcontext"],
                "ContextType": self.settings["context"],
                "ParentContext": parent,
                "TargetView": self.settings["target_view"],
            }
        )

    def create_origin(self):
        self.origin = self.file.createIfcAxis2Placement3D(
            self.file.createIfcCartesianPoint((0.0, 0.0, 0.0)),
            self.file.createIfcDirection((0.0, 0.0, 1.0)),
            self.file.createIfcDirection((1.0, 0.0, 0.0)),
        )

ifc_file = ifcopenshell.file()
ifc_file.createIfcProject()
Usecase(ifc_file, context="Model").execute()
Usecase(ifc_file, context="Model", subcontext="Body", target_view="MODEL_VIEW").execute()

print(ifc_file.wrapped_data.to_string())

for context in ifc_file.by_type("IfcGeometricRepresentationContext", include_subtypes=False):
    print('Context', context)
    print('Subcontexts', context.HasSubContexts) # This is empty, but shouldn't be
```

**Comment by Moult** [comment]
I should mention I also get segfaults when doing other operations (including a small file import test case) which I haven't isolated yet, but it may be related to this bug, so maybe when this is fixed others will also be fixed.

**Comment by Moult** [comment]
Just confirming that although the segfaults are fixed, this bug is still present. I struggled a bit to get a "big picture" view of how the C++ code fits together and how inverses are handled after reading IfcParse. Anything you can help direct me to read? No promises I'll be able to understand and solve this bug, but it's no excuse not to try :)

**Comment by aothms** [comment]
> it's no excuse not to try

If you insist.. So during parsing a mapping is built up of `(instance id, instance type, attribute index) -> instance id` https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/IfcFile.h#L78. It's a bit tricky because the parser is lazy, rooted instances are parsed immediately https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/IfcParse.cpp#L1503 but for the other instances we basically count the commas and register the inverses when find instance ids https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/IfcParse.cpp#L1555

In the end then whenever an inverse attribute is requested you always end up in this function https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/IfcParse.cpp#L2277 to resolve the attribute.

IfcOpenShell has only a single pass parser, so both forward references by identifier and inverse attributes always need to be looked up.

**Comment by aothms** [comment]
Ok, I didn't read well. I assumed this was related  to the tricky bits pertaining to the change. It was actually in the blatantly simple bits. I defined a nice inline function and changed the instance attribute visitation mechanism, but just didn't tie the two together :( should be fixed now.

**Comment by Moult** [comment]
Confirming as fixed! Closed! The explanation makes some sense, and hopefully in the future I can refer back to your explanation.
