### ISSUE TITLE
blenderbim import error creating aggregates

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#1735]
This is new from the last few days, I can't import any IFC file, a build from 8th September is ok.

[ifc file that fails to import](https://github.com/IfcOpenShell/IfcOpenShell/files/7153881/tmpaoz1efay.ifc.zip)

blender 2.93

Error message:

```
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/2.93/scripts/addons/blenderbim/bim/module/project/operator.py", line 587, in execute
    ifc_importer.execute()
  File "/usr/share/blender/2.93/scripts/addons/blenderbim/bim/import_ifc.py", line 212, in execute
    self.create_collections()
  File "/usr/share/blender/2.93/scripts/addons/blenderbim/bim/import_ifc.py", line 976, in create_collections
    self.create_decomposition_collections()
  File "/usr/share/blender/2.93/scripts/addons/blenderbim/bim/import_ifc.py", line 982, in create_decomposition_collections
    self.create_aggregate_collections()
  File "/usr/share/blender/2.93/scripts/addons/blenderbim/bim/import_ifc.py", line 1014, in create_aggregate_collections
    self.create_aggregate_tree()
  File "/usr/share/blender/2.93/scripts/addons/blenderbim/bim/import_ifc.py", line 1033, in create_aggregate_tree
    self.spatial_structure_elements[aggregate["container"].GlobalId]["blender"].children.link(
KeyError: '0s0uG6saf9b94dCNiM1Auo'
```

**Comment by brunopostle** [comment]
git bisect blames this commit:

a9f76fc8c0c36d9918fdc488fab2ab133c24ffb3 is the first bad commit
commit a9f76fc8c0c36d9918fdc488fab2ab133c24ffb3
Author: Dion Moult <dion@thinkmoult.com>
Date:   Sun Sep 12 15:25:03 2021 +1000

    You can now partially load an IFC filtered by spatial containers.

**Comment by Moult** [comment]
@brunopostle sorry for the delay. At a glance it seems a though your data doesn't quite seem correct.

```
#35=IFCBUILDINGSTOREY('0s0uG6saf9b94dCNiM1Auo',#34,'0','Storey 0',$,#42,$,'Storey 0',.ELEMENT.,-1.);
#53=IFCRELAGGREGATES('1tv5SISzj4$OSej7KeNLJw',#52,$,$,#35,(#51,#772,#914,#488,#630,#1043,#1190,#183,#1083));
#51=IFCWALL('03ECBIotrDAeQy84O7NGmi',#50,'exterior',$,$,$,$,$,$);
```

To describe your spaces and subspaces, use aggregation. This is correct: `IfcSpatialElement -> IfcRelAggregates -> IfcSpatialElement`.

To describe your objects and subobjects, also use aggregation. This is correct: `IfcProduct -> IfcRelAggregates -> IfcProduct`.

To describe objects _contained_ in a spatial element, which is a semantically different thing to aggregation, use containment: `IfcSpatialElement -> IfcRelContainedInSpatialStructure -> IfcProduct`.

It seems you are using aggregation when you should be using `IfcRelContainedInSpatialStructure` in the third scenario. It is invalid to aggregate two objects of different types, since the purpose of aggregation is to show object and subobjects.

Hopefully that fixes the issue, although I didn't test.

**Comment by brunopostle** [comment]
Thanks that's an easy fix (though it didn't trigger an `ifcopenshell.validate` error).

I now have an `import_ifc()` failure, but I'll update to the latest code before I investigate.

**Comment by brunopostle** [comment]
Closing, as fixing my invalid files cleared the error
