### ISSUE TITLE
BB: a few errors with voids

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1737]
video: https://www.dropbox.com/s/9ivntqwuwj7myjw/2021-09-14_09-36-40.mp4?dl=0

- name of void object doesn't show up in the list
- a residual void is left, after a undoing a number of steps.

**Comment by Gorgious56** [comment]
First issue is because the opening object is set to active instead of the slab after the void operation, so you're actually seeing the opening's voids panel, not the slab's. Notice the yellow outline (active object) and the orange outline (selected, but inactive object) are swapped. I think it's unintentional since it's caused by the call to another operator here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/module/void/operator.py#L46 and it happens only when one of the openings has not previously been assigned the correct IFC type. 
I'll go ahead and fix it.

@Moult Would it be a good idea to implement an optional BoolProperty parameter to operators that reset the active object to only do so when it's explicitely needed to avoid this kind of unintended consequences ?

I think the second issue is more complicated so I won't venture a guess :)

**Comment by Moult** [comment]
@Gorgious56 a better fix rather than polluting operator arguments is to decouple the operators from the actual implementation. That fixes the problem, as well as numerous other problems with operator arguments and lack of flexibility of operator returns values.

It's just a huge amount of work, and if you recall our session on TDD decoupling that layer, I haven't yet figured out a nice, incremental way that this could be migrated. Happy to resume pair programming on a solution for this layer, though.

I'm in the middle of a backlog of bugs related to my office work, I'll get around to investigating this undo issue as soon as I can.
