### ISSUE TITLE
BB: manually changing the IfcExtrudedAreaSolid/Depth for a beam

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1748]
I know about the [roadmap](https://github.com/IfcOpenShell/IfcOpenShell/issues/1324) of using a gizmo to change the IfcExtrudedAreaSolid depth--which is still in the works. 

Is there an intermediate solution, however, were we can change this depth manually, and have it registered in the IFC file?

video: https://www.dropbox.com/s/xmww20mqdmfyp7k/2021-09-23_10-33-35.mp4?dl=0

**Comment by theoryshaw** [comment]
I just had an ahah moment, of using these after a manual change...
![image](https://user-images.githubusercontent.com/507113/134539958-75b34636-491f-4244-8aae-720dc3cc5e60.png)

Wondering how involved it would be, however, to have these update actions automatically applied to an object where the depth is changed.

**Comment by theoryshaw** [comment]
Also noticed that if you manually 'update mesh' with an attached profile like IfcIShapeProfileDef, you loose that profile.  Would be nice to have something like 'Update Mesh extrusion, but preserve profile definition'. Or something more terse than that. ;)

**Comment by Moult** [comment]
So I think this already works, in your video, make that edit, then instead of refreshing, just either export the file (which will sync all edited objects) or update the representation of just those two objects.

Even if this does work, let's keep this bug open so I write a test case for it.

**Comment by theoryshaw** [comment]
It doesn't seem to update, when exported.
vid: https://www.dropbox.com/s/hddopzot756lkfq/2021-09-25_15-47-23.mp4?dl=0

Here another approach:
vid: https://www.dropbox.com/s/p1veuybmw4ce9r9/2021-09-25_15-54-20.mp4?dl=0
as you can see updating the representation, deletes the other type for some reason.

**Comment by theoryshaw** [comment]
After further investigation, i think it's because that file was exported from Revit and imported into BB. File [here](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/tree/273b1adf32a781a6b6429d91c2dbbef6cb425c13/Random_Tests/Beam_W_section/from_Revit)

I tried a clean file, [here](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/tree/273b1adf32a781a6b6429d91c2dbbef6cb425c13/Random_Tests/Beam_W_section/from_Blender) and what you suggested, worked.
vid: https://www.dropbox.com/s/1hmbbq1x6vrn5w4/2021-09-25_16-22-21.mp4?dl=0

**Comment by theoryshaw** [comment]
Related issue: https://github.com/Autodesk/revit-ifc/issues/350

**Comment by theoryshaw** [comment]
>  _export the file (which will sync all edited objects)_

It's probably worth mentioning this approach did not work.

**Comment by theoryshaw** [comment]
whoops, forget you wanted to keep this open.

**Comment by Moult** [comment]
Yeah this does work I believe, but there is an artificial restriction in place for the moment. If you try it out with any parametric Blender asset, like a DumbProfile (e.g. from a column) it will work as you expect. However, I suspect that I-Beam is not a DumbProfile - it comes from elsewhere such as Revit. In those scenarios, for the moment I have told it to always cast to a tessellation by default to be safe until I am more certain about the maturity of the system. Because it turns into a tessellation, the parameters don't refresh.

**Comment by Moult** [comment]
I've taken the plunge for global parametric intelligence (hah!). Here's the new lay of the land:

 1. When you load an existing IFC, geometry may take all forms, from non-parametric tessellations / breps, to parametric extrusions of arbitrary profiles, to clever parametric profiles like circles and rectangles.
 2. Whenever you make a change (e.g. in edit mode by moving vertices), Blender will automatically mark it as edited. It will then attempt to update the representation, using the existing geometric paradigm. For example, if it was a circular extrusion, it will try to coerce your updated geometry to still be a circular extrusion. It's not clever enough for everything (just yet), but it is capable of doing extruded profiles (e.g. I-beams or any standard profile like SHS, RHS, CHS, Zeds, Cees, etc), extruded circles and rectangles and arbitrary polylines (lines only, not polycurves). Note that if you manually move the vertices to a nonsensical position (e.g. it was a circular column but you put an I-beam in its place) it will still attempt to make it a circle and probably fail fantastically and create funky shapes. It doesn't matter where the file comes from, it will attempt to be as clever parametrically as possible.
 3. If, however, you decide that you really don't want it to be the existing geometry type as per rule 2, you can model your new shape, then explicitly choose its new geometry type (e.g. from parametric->mesh, or mesh->parametric). Then, it will not try to coerce anything, and it'll do what you've told it to do. To explicitly choose a new geometry type, you need to press the relevant "Update Representation" command.

How does that sound? In contrast, this was the _old_ behaviour:

 1. (Same) When you load an existing IFC, geometry may take all forms, from non-parametric tessellations / breps, to parametric extrusions of arbitrary profiles, to clever parametric profiles like circles and rectangles.
 2. If you make a change to a dumb wall, slab, or profile that was created in the BlenderBIM Add-on (and therefore marked as such), it will maintain parametric geometry intelligently. Otherwise, progress to rule 3.
 3. If it was a mesh, then update automatically as a mesh. You don't need to press anything manually.
 4. If it was not a mesh, then do not make any updates unless you manually press the relevant "Update Representation" command.

Hopefully this explains a lot of the undocumented behaviour you have experienced. Let me know if it makes sense, and have a play around and see if you like the new approach.

**Comment by Moult** [comment]
So - how's the new system working out? Can this bug be closed?

**Comment by theoryshaw** [comment]
Yes!... the only other suggestion, i noted here: https://github.com/IfcOpenShell/IfcOpenShell/issues/1756#issuecomment-962485367
