### ISSUE TITLE
Python validate does not support IfcLogical simple type

### ISSUE THREAD

**Issue by rbertucat** [IfcOpenShell/IfcOpenShell#1787]
Unknow values of type IfcLogical are properly created (#1086) but there are not properly validated.

```python
ifc = ifcopenshell.file(schema="IFC4X3_RC4")
ml = ifc.createIfcMaterialLayer(None, 1, "Unknown")
ml2 = ifc.create_entity(
    'IfcMaterialLayer', LayerThickness=2, IsVentilated='U')
logger = ifcopenshell.validate.json_logger()
try:
    ifcopenshell.validate.validate(ifc, logger)
    if logger.statements:
        for statement in logger.statements:
            print(f"{json.dumps(statement, default=str)}")
except RuntimeError as error:
    print(str(error))
```

returns:
```json
{"level": "error", "message": "'UNKNOWN' not valid for <attribute IsVentilated?: <type IfcLogical: <logical>>>", "instance": "#2=IfcMaterialLayer($,2.,.U.,$,$,$,$)"}
{"level": "error", "message": "'UNKNOWN' not valid for <attribute IsVentilated?: <type IfcLogical: <logical>>>", "instance": "#1=IfcMaterialLayer($,1.,.U.,$,$,$,$)"}
```

Seems like this is not implemented: https://github.com/IfcOpenShell/IfcOpenShell/blob/84fc198bbec5c98b12bdd6a5b68a34c0b2153c4b/src/ifcopenshell-python/ifcopenshell/validate.py#L50

**Comment by aothms** [comment]
Good point. Recently in 0.7 we added this, but we didn't update `validate.py`.

It's of course a bit ugly. In C++ we have a nice class for this boost::tribool. In Python we just have { True False "UNKNOWN" } where "UNKNOWN" has truethiness of True..  (which is probably undesirable). `None` would have been an option, but than you cannot distinguish all cases in an `optional logical`.

But yeah, back on topic. We currently depend on `type()` for the simple type validation which won't do in this case as { True False "UNKNOWN" } doesn't have a uniform type. What would you propose?

* Proper type for logical so that validate.py is straightforward and we can tune the truethiness of .U.
* As is. And hack our way around it in validate.py

For the latter I would probably change the `simple_type_python_mapping["logical"]` to `{True, False, "Unknown"}` and where the actual check happens https://github.com/IfcOpenShell/IfcOpenShell/blob/84fc198bbec5c98b12bdd6a5b68a34c0b2153c4b/src/ifcopenshell-python/ifcopenshell/validate.py#L82 first do a test whether `if type(simple_type_python_mapping[attr_type.declared_type()]) == set: invalid = val not in simple_type_python_mapping[attr_type.declared_type()]`

Thoughts? Do you have time to work on this?
