### ISSUE TITLE
BB: copy and pasting assets from one blender session to another

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1802]
Bug (i think) at 2:01
https://gitlab.com/openingdesign/The_Stead/-/blob/68ba61ff79f3805ae5f785c0ada53626dd34cc0a/Tutorial%20Videos/10300~Importing%20Assets%20-%202021-10-15_07-59-56.mp4?expanded=true&viewer=rich

**Comment by Moult** [comment]
The good news is that both this bug and the previous bug are not regressions - they were existing issues :) The actual issue is that although you have cleared the connection of the object to IFC, the material is still linked. So in theory if you unlinked both the object and the material, then you could copy it over without issues.

Let me think of how to make this work with a good user experience.

**Comment by Moult** [comment]
By the way, use the "Unlink" button not the "Remove" button. The unlink button severs the link between Blender and IFC. The Remove button actually deletes the element from IFC.
