### ISSUE TITLE
BCF : Reference ifc element by guid

### ISSUE THREAD

**Issue by Nitschi** [IfcOpenShell/IfcOpenShell#1816]
From what I understand BCF is mainly used to track problems relating to different elements or possibly groups of elements within an ifc file. I'm trying to automatically create BCF Topics that relate to specific elements in ifc files.

As I understand it it's necessary to create a "Topic", add a "Header" to that topic and add "HeaderFiles" to the Header.

I used the following code, but the HeaderFile does not show up if I load it in BlenderBIM. The other info is correctly shown.
Question 1: Is there anything wrong in the code below?

My hope (and I don't know if this is part of BlenderBIM or not)  would be that I could navigate to the element specified by the GUID from the BCF topic somehow.
Question 2: Is this a sensible workflow and can this be done with BlenderBIM or other tools?

```
from bcf.v2 import bcfxml
from bcf.v2.data import HeaderFile
from config.paths import data_path

def create_bcf_report():
    mybcf = bcfxml.BcfXml()
    mybcf.new_project()
    mybcf.project.name = "BCF PROJECT NAME HERE"
    my_topic = mybcf.add_topic()
    my_topic.title = "TOPIC TITLE HERE"
    my_topic.description = "DESCRIPTION OF ISSUE HERE"
    my_topic.topic_status = "IN PROGRESS"
    my_topic.topic_type = "TOPIC TYPE HERE"

    header_file = HeaderFile()
    header_file.reference = r'C:\Users\anitsch\Downloads\space_example.ifc'
    header_file.filename = r'C:\Users\anitsch\Downloads\space_example.ifc'
    header_file.ifc_project = "01fGZyzsrabcpisV5dsb$3"
    header_file.ifc_spatial_structure_element = "2cPcv0Ctrec8cewdxIuyzw"

    mybcf.add_file(my_topic, header_file)
    mybcf.edit_topic(my_topic)

    mybcf.save_project(data_path.joinpath("TestBCFv2.bcfzip"))


if __name__ == "__main__":
    create_bcf_report()

```

Thank you very much!

**Comment by Moult** [comment]
Q1: At a glance (been a long time since I checked up on BCF) you need to run mybcf.edit_topic with your topic.Header = header with all your header files in the header. Right now you have header files, but no header.

Q2: Yes indeed, you can navigate to elements specified by the topic. The topic highlights elements using viewpoints. It has the ability to select elements, hide / isolate elements, as well as specify element colour overrides and other annotation.

**Comment by Moult** [comment]
I plan to do a release next weekend :)

**Comment by Nitschi** [comment]
I have achieved what I wanted with this Code:

```
    def _add_viewpoint(self, topic, element_guids):
        viewpoint = Viewpoint()
        viewpoint.components = Components()
        for element_guid in element_guids:

            component = Component()
            component.ifc_guid = element_guid
            viewpoint.components.selection.append(component)

        viewpoint.components.visibility = ComponentVisibility()
        viewpoint.components.view_setup_hints = ViewSetupHints()
        viewpoint.components.view_setup_hints.spaces_visible = True
        viewpoint.components.view_setup_hints.space_boundaries_visible = True
        viewpoint.components.view_setup_hints.openings_visible = True

        viewpoint.components.visibility.default_visibility = True
        self._bcf.add_viewpoint(topic, viewpoint)
```

Unfortunately Blenderbim gives an error if no camera is defined:
<img width="420" alt="blenderbim-error-camera" src="https://user-images.githubusercontent.com/5908114/145220363-f0e5d115-38e4-474e-aeef-78a527d1bd96.png">

A simple check if a camera is defined should suffice to skip this Error.

**Comment by Moult** [comment]
@Nitschi are you sure this is a bug? Although in BCF XML 2.1 in theory you can omit cameras altogether (https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Schemas/visinfo.xsd#L11-L12) I suspect this was not actually the intention of the BCF specification. For example in BCF 3.0 it is now a choice in the XSD: https://github.com/buildingSMART/BCF-XML/blob/release_3_0/Schemas/visinfo.xsd#L14-L17

Strictly, we should allow it, but sometimes I tend to favour the "intentions" rather than the strict implementation. What's your opinion?
