### ISSUE TITLE
Error in build-all.py

### ISSUE THREAD

**Issue by Gochip** [IfcOpenShell/IfcOpenShell#182]
The build-all.py uses PCRE_VERSION=8.38 which is not found. I believe it should use 8.40.

**Comment by aothms** [comment]
Apparently the download location we used only retains the last two versions. With the release of 8.40 last week the 8.38 release was removed. I changed the download location to sourceforge, which didn't have 8.40 yet, but which will retain the older builds so that we do not need keep updating the build script for every version change. Thanks for the report.
