### ISSUE TITLE
Iterator progress always returns 50 with multiprocessing

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1866]
I can't remember if this was borked a long time ago or just recently, but it seems as though calling `it.progress()` doesn't make any sense because the _progress variable is updated during it.initialize().

One solution is to expose the tasks_.size() so that after initialize finishes, i can get_task_size() or something and then create my own progress bar?

Sample code:

```python
import ifcopenshell
import ifcopenshell.geom

def yield_from_iterator(it):
    while True:
        yield it.get()
        if not it.next():
            break

print("START")

f = ifcopenshell.open("/home/dion/Downloads/JudgesReception.ifc")

geom_settings = ifcopenshell.geom.settings()
it = ifcopenshell.geom.iterator(geom_settings, f, 2) # multicore = 2
it.initialize() # progress all happens here, opaque to python?
# Proposed solution: task_size = it.get_task_size()
for elem in yield_from_iterator(it):
    # Proposed solution: progress = count / task_size
    print(it.progress()) # always says 50
```

**Comment by Moult** [comment]
If it helps, I seem to recall this working in v0.6.0.

**Comment by aothms** [comment]
> I seem to recall this working in v0.6.0.

Probably not, in order to maximize code reuse between single and multi threaded and at that time C++ didn't have nice coroutines, currently the main thread blocks in initialize() until all processing is done. I think this has been reported elsewhere. I don't have time to finish this up today, but I'll start a PR to fix this. Feel free to take over :)

This now crashes on calling get() because there isn't a result ready yet. So get() should call future<>::wait(). And process concurrently should probably get some sort of std::list<future<void>> to populate.

**Comment by Moult** [comment]
Confirming as fixed with PR :) Thanks so much!
