### ISSUE TITLE
Failed to process shape

### ISSUE THREAD

**Issue by devngc** [IfcOpenShell/IfcOpenShell#1882]
Hi All,

I have been using ifcopenshell-python to parse IFC files and I received an exception error, "**Failed to process shape**" on several of the elements in a file. The following script shows two methods that I am aware of to extract elements from IFC. 
```
import ifcopenshell
import multiprocessing
from ifcopenshell.util.selector import Selector
from ifcopenshell import geom


def method_1(ifc_file, settings):
    """Method to seralize using the Iterator."""

    iterator = ifcopenshell.geom.iterator(
        settings, ifc_file, multiprocessing.cpu_count(),
        include=('IfcWall', 'IfcWallStandardCase'))

    walls = []
    if iterator.initialize():
        while iterator.next():
            shape = iterator.get()
            element = ifc_file.by_guid(shape.guid)

            if element.is_a() == 'IfcWindow' or element.is_a() == 'IfcWallStandardCase':
                walls.append(element)

    print(f'Total number of extracted walls is {len(walls)}')


def method_2(ifc_file, settings):
    """Method to serealize using the Selector."""

    selector = Selector()
    elements = selector.parse(ifc_file, '.IfcWall | .IfcWallStandardCase')

    walls = []
    for element in elements:
        try:
            shape = geom.create_shape(settings, element)
        except Exception as e:
            print(f'Element {element.GlobalId} was not extracted. {e}')
            continue
        else:
            walls.append(element)

    print(f'Total number of extracted walls is {len(walls)}')


def serialize(ifc_path, method):
    # settings
    settings = ifcopenshell.geom.settings()
    settings.set(settings.USE_WORLD_COORDS, True)

    # file
    ifc_file = ifcopenshell.open(ifc_path)

    if method == 1:
        method_1(ifc_file, settings)
    else:
        method_2(ifc_file, settings)
```

Method one does not raise the exception but silently ignores certain elements I believe. Method two will show the exception error I am referring to. I am more interested in method two here.

The method one extracted 628 walls.
The method two extracted 905 walls.
As per Solibri the model has 2510 walls.

The file needs to be confidential. So I can email you if you are interested in taking a look.

**Comment by aothms** [comment]
please send to models@ifcopenshell.org

**Comment by aothms** [comment]
> silently ignores certain elements I believe

Not entirely silently, you can get information with `ifcopenshell.get_log()` although unfortunately it's not structured it's just a text dump.

Unfortunately it also doesn't distinguish between data errors and processing errors (we try a bit with severity) Warning means data error and Error means internal processing error.

IfcOpenShell could also be a bit more informative in this case.

The issue here is illustrated by the following:

~~~
>>> from collections import Counter
>>> f = ifcopenshell.open(fn)
>>> Counter([frozenset(sr.RepresentationIdentifier for sr in w.Representation.Representations) for w in f.by_type("IfcWall")])
Counter({frozenset({'Axis'}): 1605, frozenset({'Axis', 'Body'}): 905})
~~~

Here we look for the walls at what kind of representations they have. Exactly the amount of walls that you miss only have an Axis representation. These walls are then in fact Decompositions. 

One of the walls is `#7274`

~~~
>>> [x.is_a() for x in f[7472].IsDecomposedBy[0].RelatedObjects]
['IfcBuildingElementPart', 'IfcBuildingElementPart']
~~~

So it has two parts. And these two parts themselves have a Body representation that you can call create_shape() on.

Tools like Solibri typically present these kind of aggregated elements as a single element, but you can still see the parts if you manage to find them in the tree view.

The difference between method 1 and 2 is probably this typo

~~~
if element.is_a() == 'IfcWindow' or element.is_a() == 'IfcWallStandardCase':
                      ^^^^^^^^^
~~~

**Comment by devngc** [comment]
Thanks @aothms, Is there no way to get the Wall's body representation in that case. I am creating FreeCAD shapes for these elements. WIth this solution, I will have to create multiple shapes for each of those walls.

**Comment by devngc** [comment]
Tools like Solibri typically present these kind of aggregated elements as a single element

Can we not do that with ifcopenshell too?

**Comment by aothms** [comment]
You could do a boolean union of the parts I suppose. Or combine them into a
compound. But in the data there is no wall body.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op vr 26 nov. 2021 07:13 schreef Devang ***@***.***>:

**Comment by Moult** [comment]
Closing as there isn't actually a bug here, the wall itself has no body, only the parts do.
