### ISSUE TITLE
Adding elements from one file to another results in segfault

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1885]
I suspect this might be a regression from v0.6.0 to v0.7.0? Using the JudgesReception IFC I've shared from the drawing generation issue, this snippet might help replicate it.

```python
import ifcopenshell
f = ifcopenshell.open('/path/to/JudgesReception.ifc')
g = ifcopenshell.file(schema=f.schema)
for e in f:
    g.add(e)
```

**Comment by aothms** [comment]
Yes it was the logicals. Previously there was always a one-to-one mapping from parsed type to schema type (not considering null at the moment). But now when we encounter .F. we don't know if on the schema level it's a boolean or logical. For a long time we were very permissive with attribute types, just parse what we get and return in schema type when requested - possibly throwing an error. But, with my latest change, we will no longer silently propagate invalid attributes values when copying because from now we are making a copy based on schema type, not parsed type.

**Comment by Moult** [comment]
Confirming as fixed! Thanks so much!
