### ISSUE TITLE
ifcopenshell python, new get_layers() does not work for files exported with Allplan

### ISSUE THREAD

**Issue by berndhahnebach** [IfcOpenShell/IfcOpenShell#1886]
https://github.com/IfcOpenShell/IfcOpenShell/pull/1869

https://github.com/IfcOpenShell/IfcOpenShell/commit/41486ba08a3ddcbd5dd40a086dd9b96ca6a3fbaa

attached a simple file and the error message ... 

```
>>> 
>>> import ifcopenshell
>>> from ifcopenshell.util.element import get_layers
>>> 
>>> ifc = ifcopenshell.open("C:/Users/BHA/Desktop/box.ifc")
>>> element = ifc.by_type("IfcBuildingElement")[0]
>>> 
>>> get_layers(ifc, element)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.20.xxxxx\bin\lib\site-packages\ifcopenshell\util\element.py", line 116, in get_layers
    layers.extend(subelement.LayerAssignment or [])
  File "C:\0_BHA_privat\progr\FreeCAD\FreeCAD_0.20.xxxxx\bin\lib\site-packages\ifcopenshell\entity_instance.py", line 67, in __getattr__
    raise AttributeError(
AttributeError: entity instance of type 'IfcAxis2Placement3D' has no attribute 'LayerAssignment'
>>> 
```

**Comment by berndhahnebach** [comment]
[box.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/7568350/box.ifc.txt)

**Comment by berndhahnebach** [comment]
get_layers(ifc, element) has the file as parameter. all other methods in util not. It woulds be good if get_layer() would wiork like get_material() in the regard of parameter.

cheers bernd

**Comment by aothms** [comment]
> AttributeError: entity instance of type 'IfcAxis2Placement3D' has no attribute 'LayerAssignment'

This is the beauty of IFC. At some point the attribute was renamed from LayerAssignments to LayerAssignment so that needs to be handled in the code. Using hasattr or by checking the schema name of the file.

That's because it depends on file.traverse() and in python that's a member function of file. In C++ we have a bit more freedom as member or free function. But in principal these methods don't really work well if a instance isn't added to a file. There is a long discussion elsewhere on whether we can get the file from the instance, but it's a bit complicated.

I see moult just fixed this btw.

**Comment by Moult** [comment]
Sometimes it's quite frustrating when it isn't listed when changes happen between IFC2X3 and iFC4, especially rather tiny changes like `LayerAssignment` vs `LayerAssignments`.

The ifc parameter is required because it needs to traverse and check schema version.

In theory thanks to the undo/redo system we can access the file via element.wrapped_data.file but I don't know how much I can trust it. What do you think @aothms

**Comment by aothms** [comment]
> I don't know how much I can trust it. What do you think @aothms

Yes it's the "undecorated" file, so it won't have the methods implemented in file.py. Plus it will then also return undecorated entity_instance objects. It's a bit leaky. We talked about this elsewhere. The only way to properly solve this is to have a global mapping python from "undecorated" file to decorated file or sth. Which is annoying and memory leaky, unless we can somehow weakref them in python. Alternative is to completely remove the file.py and entity_instance.py and do everything in SWIG.

**Comment by berndhahnebach** [comment]
Thanks guys for the fast fix and the background informations.

:-)
