### ISSUE TITLE
Crash with EXCEPTION_ACCESS_VIOLATION when processing shape

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1906]
Not sure if this is a bug or a result of a bad ifc file.  Every time I try to import Blender crashes with the following message:
`Starting import process :: 0.00
Loading file :: 0.00
Calculate unit scale :: 0.00
Calculate model offset :: 0.00
Set units :: 0.00
Create project :: 0.00
Process element filter :: 0.01
Process context filter :: 0.00
Create collections :: 0.02
Create opening collection :: 0.00
Create materials :: 0.00
Create styles :: 0.00
Create annotation :: 0.00
Parsing native elements :: 0.11
Done creating geometry
Create native elements :: 0.00
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF93CC68346
Module  : _ifcopenshell_wrapper.pyd
Thread  : 000059f0
Writing: C:\Users\vpaji\AppData\Local\Temp\blender.crash.txt
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF93CC68346
Module  : _ifcopenshell_wrapper.pyd
Thread  : 00003960
Writing: C:\Users\vpaji\AppData\Local\Temp\blender.crash.txt
The terminal process "c:\Program Files\Blender Foundation\Blender 2.93\blender.exe '--python', 'c:\Users\vpaji\.vscode\extensions\jacqueslucke.blender-development-0.0.16\pythonFiles\launch.py'" terminated with exit code: 11.`

**Comment by vulevukusej** [comment]
I`m happy to provide the ifc file if it helps..

**Comment by Moult** [comment]
Yes, please share the IFC file. dion@thinkmoult.com if it is private. I think we should definitely write a guide for how to debug these types of issues.

**Comment by vulevukusej** [comment]
> Yes, please share the IFC file. [dion@thinkmoult.com](mailto:dion@thinkmoult.com) if it is private. I think we should definitely write a guide for how to debug these types of issues.

Just sent you an email with the file.  Cheers mate.

**Comment by Moult** [comment]
It loads fine here without crashing. Exception access violation sounds interesting. Perhaps something to do with a Windows thing where it tries to access a cache it can't access?

Try to comment out these lines for cache: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/import_ifc.py#L630-L632 and https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/import_ifc.py#L778-L780 and that should disable caching. See if that helps. If it helps, try deleting all `.h5` files in `blenderbim/bim/data/cache/`.

**Comment by vulevukusej** [comment]
So I commented out the lines as you suggested, still no luck - I get the same error message.

**Comment by Moult** [comment]
What happens if when importing, you enable advanced mode (in the settings in the file browse dialog) then you use the filter tool to import just a portion of the model? Maybe try non multicore? Are you using the latest IfcOpenBot build?

**Comment by vulevukusej** [comment]
- I tried disabling multicore processing - no luck
- I copied the latest ifcopenshell into \Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell  (is this what you meant) - no luck

**Comment by Moult** [comment]
I mean copying the latest IfcOpenBot build from here: https://github.com/IfcOpenBot/IfcOpenShell/commits/v0.7.0

Maybe we can screenshare and try a few things together. Give me a ping on IRC. Alternatively, we can see if someone else can replicate the crash.

**Comment by Moult** [comment]
Hey did you manage to isolate that object and send it off to @aothms to take a peek? I've just run into another client model which has the same error as yours.

Since it works on my machine and not on the Windows build on other people's computers, I assume either this is Windows specific, or OpenCascade version specific. I compile with OpenCascade 7.5.2 locally. I'm not sure what IfcOpenBot uses.

**Comment by vulevukusej** [comment]
No not yet, I'll get around to it today or tomorrow though.

**Comment by aothms** [comment]
> I'm not sure what IfcOpenBot uses.

7.5.3

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/nix/build-all.py#L77
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/win/build-deps.cmd#L173

> I compile with OpenCascade 7.5.2 locally

That would be first thing to check. It's not the first time that a minor OCCT version difference caught some incidental issues for us. We also stayed on 7.3.3 instead of 7.3.4 for ex.

**Comment by vulevukusej** [comment]
@aothms - Do you have an email I can send you the file?  It's not something I can share publicly.  The crash happens just before this boolean operation: 
![image](https://user-images.githubusercontent.com/83825269/144853891-07c9d6d7-3049-4f46-9c40-e0a017ea3d85.png)

with the following error message:
![image](https://user-images.githubusercontent.com/83825269/144853988-635a21e8-897f-412f-9d33-987ac1e706c0.png)

**Comment by Moult** [comment]
I have narrowed down the issue further, and I don't think it's limited to the OpenCascade version after all, since I can now recreate it with IfcOpenBot builds. Basically I took the stable BlenderBIM Add-on code 0.0.211031 and I swapped out the ifcopenshell module with different IfcOpenBot builds to see what would break it on Windows.

Results:

WORKING:

- Blender 2.93, BlenderBIM Add-on 0.0.211031, v0.7.0-93c5906a (29th Oct)
- Blender 3.0, BlenderBIM Add-on 0.0.211031, v0.7.0-05256fc0 (2nd Nov)


FAIL:

- Blender 3.0, BlenderBIM Add-on 0.0.211031, -61e510e4 (7th Nov)
- Blender 3.0, BlenderBIM Add-on 0.0.211031, -e0e8281a (8th Nov)

I don't have tests for any more recent bot builds, since they aren't available for Windows. So in theory, this might've been fixed since then. I also noticed something suspicious, the bot builds `ifcopenshell.version` outputs `-commithash` with no `v0.7.0` prefix in the 7th Nov build and 8th Nov build (and perhaps onwards). Maybe this is a symptom of the problem?

So, I guess what changed between 2nd and 7th Nov?

I've sent a sample model which contains this crash to models@ifcopenshell.org

**Comment by Moult** [comment]
@aothms I have isolated a crashing element here: [exception-access-violation.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/7682887/exception-access-violation.ifc.txt)

By the way, do you know where @johltn is with the test suite? Perhaps this file could be added to the test suite if this is a real bug?

**Comment by vulevukusej** [comment]
^^^ Unfortunately I don't have permission to share the file in that capacity..

**Comment by Moult** [comment]
Happy for the extract I shared to be added. I'll add it.

Since it works on my dev environment and in yours, either its a bot build bug (perhaps the truncated version string is a symptom?) Or it has already been fixed I reckon. The next bot build will narrow it down :)

**Comment by aothms** [comment]
Ok, yeah then I start that right away before looking into it... ;)

**Comment by aothms** [comment]
New builds are up fyi https://github.com/IfcOpenBot/IfcOpenShell/commit/b9ea741e5eb3a0a020c9d36fa8e15deb1fc87dd0#commitcomment-61696305

**Comment by Moult** [comment]
Awesome! My tests show that it seems to work using the latest build. The `ifcopenshell.version` is still only the truncated `-hash` but that's a minor issue.

@vulevukusej let me know if it is also fixed on your end, and then I think we can safely close this bug :)

**Comment by Moult** [comment]
@vulevukusej bump - would you mind testing to see if this is now fixed? Because crashing bugs, especially one that seems quite frequent like this one are often a showstopper for a public stable release.

**Comment by vulevukusej** [comment]
I'll test it tomorrow ;)

**Comment by vulevukusej** [comment]
@Moult @aothms - Can confirm I no longer have crashes after updating to the latest ifcopenbot build.
