### ISSUE TITLE
IFC Patch - ExtractElements strips objects of psets

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1908]
As the description says - IFC Patch seems to strip the objects of psets.  Is this the intended behaviour? (tested on multiple files)
![image](https://user-images.githubusercontent.com/83825269/144069445-6eddeee3-3e57-4c6e-b7c6-4a780d28d031.png)

**Comment by Moult** [comment]
Probably at the time it was written it was the easiest thing to do. Happy for a PR to modify the patch to extract objects including psets.

**Comment by vulevukusej** [comment]
Nice - Will add it to my todo list

**Comment by aothms** [comment]
One idea would be to look at `element.wrapped_data.get_inverse_attribute_names()` and whitelist a couple of them, instead of listing just a single inverse attribute https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcpatch/ifcpatch/recipes/ExtractElements.py#L61

You definitely don't want all of them, e.g ConnectedTo would lead you to a clearly different element. But probably the other Associations and Declarations could be added.

**Comment by Moult** [comment]
Agreed, a default list of whitelisted inverse attributes, with potentially the user able to override it, will be useful.

**Comment by Moult** [comment]
ExtractElements now uses the append_asset API, so we now get easy inverse attribute whitelisting for free.
