### ISSUE TITLE
IfcConvert how to use Z Up axis?

### ISSUE THREAD

**Issue by AsheKR** [IfcOpenShell/IfcOpenShell#1932]
I tried to use it like this but failed.

```
IfcConvert --model-rotation z -yv small_size.ifc converted.glb

[Error] Invalid use of --model-rotation
```

how can i convert to z up axis?

**Comment by aothms** [comment]
It's not implemented for .glb. In .glb I think it's really written in the standard that Y is supposed to be up.

There's a --y-up flag for .obj, which otherwise uses z as up. But that's no help to you unless you're interested in implementing this yourself and looking for guidance.

My advise would be to convert to Collada and figure out a way to do this in one of the many collada to gltf converter.

**Comment by Moult** [comment]
> glTF uses a right-handed coordinate system, that is, the cross product of x and y yields z. glTF defines the y axis as up.

From [here](https://github.com/KhronosGroup/glTF/tree/main/specification/1.0).
