### ISSUE TITLE
Integers in enumerations cause an error

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1943]
So I'm not sure if this is an error in the way I'm defining the .ifc file, or if its an issue with BB.  When I attempt to load this template file and then add the pset to an object, I get the following error message:
`File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\prop.py", line 83, in getAttributeEnumValues
TypeError: EnumProperty(...): expected a tuple containing (identifier, name, description) and optionally an icon name and unique number`

Here is the .ifc file I was importing:
```
ISO-10303-21;
HEADER;
FILE_DESCRIPTION((),'2;1');
FILE_NAME('Pset_Custom.ifc','2020-01-01T00:00:00',(),(),'Sample','Sample',$);
FILE_SCHEMA(('IFC4'));
ENDSEC;

DATA;
#1= IFCPROPERTYSETTEMPLATE('05N2Dhepb9ouTCSmWBh22D',$,'Custom_Pset','An example custom pset.',.PSET_TYPEDRIVENOVERRIDE.,'IfcObject',(#2,#3,#4));
#2= IFCSIMPLEPROPERTYTEMPLATE('37EpTDq4v96gTZh196BBXQ',$,'NumericProperty','An example numeric property',.P_SINGLEVALUE.,'IfcCountMeasure','',$,$,$,$,.READWRITE.);
#3= IFCSIMPLEPROPERTYTEMPLATE('22H7CzDvz1XfVHKkGWoYUK',$,'StringProperty','An example string property',.P_SINGLEVALUE.,'IfcLabel','',$,$,$,$,.READWRITE.);
#4= IFCSIMPLEPROPERTYTEMPLATE('0p00ORU2nCnPA8UyQg2ZY$',$,'porr_Ganzzahl_E05','Impraegnierung',.P_ENUMERATEDVALUE.,'IfcInteger',$,#5,$,$,$,.READWRITE.);
#5= IFCPROPERTYENUMERATION('Impraegnierung',(IfcInteger(1), IfcInteger(2), IfcInteger(3), IfcInteger(4), IfcInteger(5), IfcInteger(6), IfcInteger(0)),$);
ENDSEC;

END-ISO-10303-21;
```

**Comment by vulevukusej** [comment]
@Gorgious56 - Is this something you've also encountered?  Perhaps it can also be fixed with the same method as in #1941

**Comment by Gorgious56** [comment]
So it's `#5` that's causing the error ? `EnumProperty`'s `items` attribute expects an iterable of elements with at least a unique identifier, a display name and a description. Maybe it's using a format that's not supported by BB or ifcopenshell when reading the file ?

**Comment by vulevukusej** [comment]
yeah its #5.  The thing is, if I change each IfcInteger(#) to IfcInteger('#'), the enum works, however I can't select a value then since BB is expecting an integer value, not a string..

**Comment by Gorgious56** [comment]
I forgot to add that the identifier must be of type `str`. Just a wild guess, does it still throw error if you replace https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/prop.py#L88 with     `return [(str(e), e, "") for e in data]`

**Comment by aothms** [comment]
I was about to comment that

ifc -> blender

`str(3)`

blender -> ifc

~~~
>>> type_str = f.createIfcInteger().attribute_type(0)
>>> type_fn = {'INT':int, 'STRING':str, 'REAL':float, 'BOOL': bool}[type_str]
>>> type_fn('3')
3
~~~

^ note mapping not complete, misses, logical and all, but should get us started.

**Comment by vulevukusej** [comment]
@Gorgious56 - hmm, I tried that but I still get an error..

**Comment by vulevukusej** [comment]
So it turns out this is what fixed it:
    `return [(str(e), str(e), "") for e in data]`
since the identifier **AND** the description need to be strings.  []((https://docs.blender.org/api/current/bpy.types.EnumPropertyItem.html#bpy.types.EnumPropertyItem))

**Comment by vulevukusej** [comment]
@aothms I'm not familiar with the syntax in this line:
`type_fn = {'INT':int, 'STRING':str, 'REAL':float, 'BOOL': bool}[type_str]`

Could you point me in the python docs I can find this?

**Comment by Gorgious56** [comment]
Haha yes indeed, missed that too sorry. Good catch ! Now do you think you can test if exporting these doesn't overwrite the types as @aothms suggested ?

**Comment by vulevukusej** [comment]
Yeah I'm testing it right now :)

**Comment by Gorgious56** [comment]
> @aothms I'm not familiar with the syntax in this line: `type_fn = {'INT':int, 'STRING':str, 'REAL':float, 'BOOL': bool}[type_str]`
> 
> Could you point me in the python docs where I can find this?

This is a fancy way to use a switch pattern in python since it doesn't support it by default ([yet](https://www.python.org/dev/peps/pep-0622/)). You create a dictionary where keys are your possible input values, and the values are what you expect as the output. It's basically a one liner way of defining :
```
if val == "INT":
    type_fn = int
elif val == "STRING":
    type_fn = str
elif val == 'REAL':
    type_fn = float
etc.
```

**Comment by aothms** [comment]
It's not specific syntax. Just creating a dictionary and immediately
indexing it. Like a lazy multiple branch if statement.

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op di 14 dec. 2021 12:38 schreef Vukas Pajic ***@***.***>:

**Comment by vulevukusej** [comment]
Ok so I edited the bim.prop.Attribute class, and now it works fine:
```
class Attribute(PropertyGroup):
    name: StringProperty(name="Name")
    data_type: StringProperty(name="Data Type")
    string_value: StringProperty(name="Value", update=updateAttributeValue)
    bool_value: BoolProperty(name="Value", update=updateAttributeValue)
    int_value: IntProperty(name="Value", update=updateAttributeValue)
    float_value: FloatProperty(name="Value", update=updateAttributeValue)
    is_null: BoolProperty(name="Is Null")
    is_optional: BoolProperty(name="Is Optional")
    enum_items: StringProperty(name="Value")
    enum_value: EnumProperty(items=getAttributeEnumValues, name="Value", update=updateAttributeValue)
    **enum_data_type: StringProperty(name="Enum Data Type")**

    def get_value(self):
        if self.is_null:
            return None
        **if self.data_type == "enum":
            type_fn = {'IfcInteger':int}[self.enum_data_type]
            return type_fn(self.enum_value)
        else:    
            return getattr(self, str(self.get_value_name()), None)**
```

**Comment by vulevukusej** [comment]
Now I just need to reference https://github.com/IfcOpenShell/IfcOpenShell/blob/dbc6f521fe991d8a9732b10640f79191205157dc/src/blenderbim/blenderbim/bim/schema/ifc_types_IFC4.json and I should be on the home straight.  What do you think?

**Comment by vulevukusej** [comment]
Or is there an easier, quicker way of converting the ifc data type to python data type?

**Comment by Gorgious56** [comment]
Nice !

> type_fn = {'IfcInteger':int}[self.enum_data_type]
>             return type_fn(self.enum_value)

 Be aware that this will throw an error if the key is not found in the dictionary. You can try `{'IfcInteger':int}.get(self.enum_data_type, int)` for instance to have a fallback return value.

I don't really know what's the best way to tackle this. Maybe we could expand upon how it's done in the other `Attribute` instance methods, similar to https://github.com/IfcOpenShell/IfcOpenShell/blob/dbc6f521fe991d8a9732b10640f79191205157dc/src/blenderbim/blenderbim/bim/prop.py#L156-L166
Something like :

    def ifc_python_type_mapping(self, value):
        if self.data_type == "integer":
            return int
        elif self.data_type == "float":
            return float
        elif self.data_type == "bool":
            return bool
        else:
            return str

and then 

    def get_value(self):
        if self.is_null:
            return None
        if self.data_type == "enum":
            return self.ifc_python_type_mapping(self.enum_data_type)(self.enum_value)
        else:    
            return getattr(self, str(self.get_value_name()), None)

Or maybe it's worth refactoring how we define enums, and instead of having `data_type = "enum"` and then a sub type attribute, we could use `data_type = "enum_str"`, `data_type = "enum_bool"` etc. and get the value accordingly.

I'm just worried we're expanding the `Attribute` class every time there is an edge case and it starts looking like an unmaintainable Frankenstein monster. >< Also I don't know ifc schema well enough to say if this philosophy is logical.  

Maybe we can see if you'd like to make a pull request and we can expand upon that and see how it works / doesn't work ?

**Comment by Moult** [comment]
OK sorry it took a while but I just reviewed this and I believe @aothms had the preferred approach here: https://github.com/IfcOpenShell/IfcOpenShell/issues/1943#issuecomment-993325728

In short, Blender is just UI stuff and so IFC->Blender is as simple as str(whatever.wrappedValue). Going from Blender->IFC in the past we never had any problems since we preserved primitives (str,int,float,bool) in the UI ... except for enums because Blender enums enforce string data type. This exception is what you're running into which caused this bug.

Your solution is preserving the data type in a new enum_data_type works for enums, but I think we can do better. Because, your solution puts the responsibility on the UI to preserve the primitive data type. However, what if we have other UIs, like IFCCSV which needs to handle CSVs which could be unclean and have all sorts of stuff as strings, or a IfcSverchok where who knows what the data type could come across as. Instead, I think it's preferred to use @aothms' approach of getting attribute_of_type() and casting it on the IfcOpenShell API layer.

I'll commit a fix :)
