### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by ssg3d** [IfcOpenShell/IfcOpenShell#1953]
Hi, am not sure what changed recently, but I am now getting the following error for v0.7.0. The last time I built it was a couple weeks ago, and it was building fine.
```
In file included from /home/username/ifcopenshell/src/ifcgeom/../ifcgeom/../ifcgeom/IfcGeomElement.h:29,
                 from /home/username/ifcopenshell/src/ifcgeom/../ifcgeom/IfcGeom.h:57,
                 from /home/username/ifcopenshell/src/ifcgeom/IfcGeomCurves.cpp:80:
/home/username/ifcopenshell/src/ifcgeom/../ifcgeom/../ifcgeom/../ifcgeom/IfcGeomRepresentation.h: In constructor ‘IfcGeom::Representation::Triangulation::Triangulation(const IfcGeom::Representation::BRep&)’:
/home/username/ifcopenshell/src/ifcgeom/../ifcgeom/../ifcgeom/../ifcgeom/IfcGeomRepresentation.h:212:31: error: ‘class Poly_Triangulation’ has no member named ‘Node’; did you mean ‘Nodes’?
  212 |         coords.push_back(tri->Node(i).Transformed(loc).XYZ());
      |                               ^~~~
      |                               Nodes
/home/username/ifcopenshell/src/ifcgeom/../ifcgeom/../ifcgeom/../ifcgeom/IfcGeomRepresentation.h:217:36: error: ‘class Poly_Triangulation’ has no member named ‘UVNode’; did you mean ‘UVNodes’?
  217 |          const gp_Pnt2d& uv = tri->UVNode(i);
      |                                    ^~~~~~
      |                                    UVNodes
make[2]: *** [CMakeFiles/IfcGeom_ifc2x3.dir/build.make:63: CMakeFiles/IfcGeom_ifc2x3.dir/home/username/ifcopenshell/src/ifcgeom/IfcGeomCurves.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:382: CMakeFiles/IfcGeom_ifc2x3.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by ssg3d** [comment]
Additional note: This error is on Ubuntu. It builds fine on Windows.

**Comment by aothms** [comment]
After https://github.com/IfcOpenShell/IfcOpenShell/pull/1930 the 0.7 branch isn't compatible anymore with OCCT version < 7.2. It wasn't recommended anyway, because without multi-argument and fuzzy boolean you don't get great results all the time. From a code point of view, OCCT 7+ plays along much better with the stl.

That includes the `liboce` that's found in debian (derivatives), which is OCCT 6.9 or even less.

If you use the package manager, you'll have to use `libocct` which is OCCT 7.3 in most cases now I think, or compile OCCT from source (such as what the build scripts do).

Probably the readme should be updated for this. If you find the time to update the readme for this it'd be greatly appreciated.

**Comment by ssg3d** [comment]
[README.md](https://github.com/IfcOpenShell/IfcOpenShell/files/7787728/README.md)
Thanks, @aothms. Am attaching the modified MD file here with some changes from our previous threads as well when I was trying to move from 06 to 07.

**Comment by aothms** [comment]
@ssg3d awesome, could you please provide it as a Pull Request (in Github it's rather automatic if you press the edit button on the readme in the web interface) that way we can easily see the changes and record the authorship info. Thanks again.

**Comment by ssg3d** [comment]
@aothms done! Hope its in order - it's my first PR, future contributions should be quicker.
