### ISSUE TITLE
Two test files failing

### ISSUE THREAD

**Issue by iras** [IfcOpenShell/IfcOpenShell#198]
Hi @aothms ,

I found two IFC test files from the opensourceBIM repo that fail converting with IfcOpenShell (they are probably meant to). Do you know the precise reason why they fail?

https://github.com/opensourceBIM/TestFiles/blob/master/TestData/data/Paolo.ifc
https://github.com/opensourceBIM/TestFiles/blob/master/TestData/data/RioleringTestArkey.ifc

Many thanks.

**Comment by Stinkfist0** [comment]
```
Log:
[Error] No geometries found
[Error] No geometrical entities found
```
Should be rather self-explanatory.

**Comment by iras** [comment]
Thanks Ali.

An empty IFC file should produce an empty geometry file in my books. Not just returning an error.

**Comment by iras** [comment]
Solibri loads them up just fine for instance although showing no geometry.

**Comment by iras** [comment]
According to:

http://www.buildingsmart-tech.org/ifc/IFC2x4/rc2/html/schema/ifcsharedbldgserviceelements/lexical/ifcflowterminal.htm

http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcrepresentationresource/lexical/ifcproductrepresentation.htm 

it's valid not to have one.

**Comment by Stinkfist0** [comment]
Ah yes, so it would appear. Note that currently IfcOpenShell supports  IFC2x3 TC1 and IFC4 Add1.

**Comment by iras** [comment]
I think it was optional in 2x3 too.

http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcsharedbldgserviceelements/lexical/ifcflowterminal.htm

I agree. Having an IFC entity with no geometric representation will yield no geometry data therefore an empty geometry file and not an error an no geometry file.

Do you reckon this would be a quick fix?

**Comment by Stinkfist0** [comment]
Ah weird, I'm looking at the actual IfcOpenShell code which is generated from the schema and it doesn't have it marked as optional.

Personally I don't have a strong opinion how IfcConvert should perform in this case, maybe best to wait for Thomas' opinion.

**Comment by iras** [comment]
Thanks for taking the time to look at the code, Ali.

Yes, I agree. Let's wait for @aothms's opinion.

**Comment by aothms** [comment]
Sorry, I came a bit late to the party. I agree with your reasoning in this particular case: nothing went wrong so a non-zero exit code should not be returned.

However (and this is the annoying thing about the way the code is setup currently, and the quality of IFC files out there), you cannot really deduce that from the state the `IfcGeom::Iterator` is in. For all we know there have been exceptions throughout the processing of every representation and in that case we definitely should return a non-zero exit code.

Then the question arises, what exceptions are severe enough to trigger a non-zero exit code. As there are many forgiveable flaws in many IFC files.

All in all, I think the safest choice is the current behaviour, if no geometry is written, assume something is wrong. Plus, a successful processing is hard to capture in a single value. What we could work towards is a machine readable logging format and well-defined error codes. So that users themselves can properly judge the result.

**Comment by iras** [comment]
Thanks @aothms.

I think that categorising the various levels of severity of the exceptions should not be IfcOpenShell's concern. The current IfcOpenShell's error logging system already does a good enough job in pointing at what objects (GUIDs) have been deemed problematic as far as IfcOpenShell's validation and processing goes. The rest should be up to the IfcOpenShell users and, in particular, BIM managers to chase the problem down to the original Revit (or else) file and see if that is only a problem with a slightly malformed geometry or a missing representation altogether.

On the other hand, an empty IFC file should be strictly associated with an empty geometry file and _no error thrown_, otherwise such IfcOpenShell's _exception_, will impact downstream codebases in terms of users having to deal with such inconsistency themselves.

**Comment by CyrilWaechter** [comment]
@iras `IfcConvert Paolo.ifc` and `IfcConvert RioleringTestArkey.ifc` now both works so I assume it has been fixed at some point.
