### ISSUE TITLE
When to Release a Stable Version？

### ISSUE THREAD

**Issue by hxboxy-xh** [IfcOpenShell/IfcOpenShell#1992]
Dear author：
The BlenderBIM is released automatically everyday，when will you release a stable version？
I use IfcConvert on nix，my company needs me to use a stable version, do you have any suggestions？

Thanks

**Comment by Moult** [comment]
IfcConvert follows a different release schedule to the BlenderBIM Add-on. The BlenderBIM Add-on gets built automatically every day by Github, for testing purposes. IfcConvert, and the core IfcOpenShell, gets built perhaps a couple times a month on average triggered manually by @aothms also generally for testing purposes. The last time this happened for all three operating systems was in December.

The "stable" release for the BlenderBIM Add-on typically happens every month and is available on the BlenderBIM.org website. However, sometimes (like now) it is delayed because we need to wait for a new build for the core IfcOpenShell.

The "stable" release for IfcOpenShell, I'm not quite sure. In general I personally find anything released by the bot is pretty stable.

Because the BlenderBIM Add-on is alpha software, in general the latest release is always more "stable". However, if you want some assurances that it won't crash immediately upon booting up, the release on the blenderbim.org website is what you want to use.

**Comment by hxboxy-xh** [comment]
> n

Thanks very much for your reply.
Have a nice day!

**Comment by aothms** [comment]
>  I use IfcConvert on nix，my company needs me to use a stable version, do you have any suggestions？

Just one or two more comment on this.

You basically have two choices:

* use 0.6 https://github.com/IfcOpenBot/IfcOpenShell/commit/721fe4729aa5302efe1602971aae2558934ad098#comments
* use 0.7 https://github.com/IfcOpenBot/IfcOpenShell/commit/4c40fc1629b37230a3d7ad823f23d064ffbaee92#comments

0.6 is closed for new features so if you report serious issues on 0.6 they'll be fixed without new features (with potential other issues) interfering.

0.7 will have the latest improvements such as improved boolean operations (by performing in 2d where possible) and various other things.

This is our best effort at a stable vs development version. I must say though that the community isn't very eager to get fixes into 0.6 so it's also interaction between the dev team and the community where the development emphasis goes.

So currently latest 0.6 is what most stable, but at the same time, new features (such as the 2d boolean ops in 0.7) will also enhance robustness of geometric processing. So stable is not always necessarily most robust.

Lastly, it also depends on the version of open cascade. The provided builds use occt 7.3 for 0.6 and occt 7.5 for 0.7. There basically the same applies with robustness vs stability. Some occt releases have been a bit more risky to upgrade to such as 7.4 (which we skipped in the official builds) buy in general the higher the occt version the more robust processing.

**Comment by Mannshoch** [comment]
@aothms 
Is there a way to follow the builds from IfcOpenBot. It would be nice to be able to use beta builds of IfcConvert.
