### ISSUE TITLE
BB import 2x3 RevitMEP no Styles

### ISSUE THREAD

**Issue by cadgiru** [IfcOpenShell/IfcOpenShell#1998]
When importing Revit MEP file (2x3) coloring disappears. (is present in other viewers(Solibri, BimSync)
![MEPstylesMagiCADForRevit2021UR-2](https://user-images.githubusercontent.com/42599252/150629196-dc481437-d024-4720-99b6-43ee9a7b43b4.JPG)

**Comment by Moult** [comment]
Can you provide a sample file? Perhaps dion@thinkmoult.com if private

**Comment by CyrilWaechter** [comment]
Strange. It works on my sample file:
![image](https://user-images.githubusercontent.com/9622862/150770890-63653478-0ab8-4580-833e-5d1d4666e917.png)

**Comment by Moult** [comment]
Oh I see what's going on here. I've fixed it, but this does raise an interesting point.

In the past, I only considered StyledByItem on the _actual_ geometric representation items, not the mapped items. This particular sample file you have (not sure which vendor) applies styles on the mapped item.

This seems a little interesting, what happens when both the item and the mapped item specifies a style? Which overrides which? This is one of the areas of IFC I (and others, I would bet) feel pretty unhappy about.

![2022-01-25-133551_502x439_scrot](https://user-images.githubusercontent.com/88302/150900433-01d14627-33a7-4334-ad48-ad7bfe8c692d.png)

**Comment by Moult** [comment]
Maybe ping @aothms

**Comment by aothms** [comment]
Yes and potentially factor in material definition styles.

I'd say though the closer to the product wins, consider it as procedurally applied operations in the reversed order of the forward attributes, overwriting each other's result. So mapped item wins in this case.
