### ISSUE TITLE
IfcConvert enhancements

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#20]
Hi. Thought to open up a discussion of the enhancements I have made to IfcConvert in https://github.com/Tridify/IfcOpenShell-SourceForge before I start to reimplementing and cleaning up these to the new fork. Here's what I have done:
- new functionality for IfcConvert (taken from the `--help` output):

```
  --names arg                     A list of names or wildcard patterns that 
                                  should be included in or excluded from the 
                                  geometrical output, depending on whether 
                                  --exclude or --include is specified. The 
                                  names are handled case-sensitively. Cannot be
                                  placed right before input file argument.
  --no-normals                    Disables computation of normals. Saves time 
                                  and file size and is useful in instances 
                                  where you're going to recompute normals for 
                                  the exported model in other modelling 
                                  application in any case.

  --use-names                     Use entity names instead of unique IDs for 
                                  naming objects and materials upon 
                                  serialization Applicable for .obj and .dae 
                                  output.
  --use-guids                     Use entity GUIDs instead of unique IDs for 
                                  naming objects upon serialization. Overrides 
                                  possible usage of --use-names for objects but
                                  not for materials.Applicable for .obj and 
                                  .dae output.
  --center-model                  Centers the models upon serialization by the 
                                  applying the center point of the scene bounds
                                  as an offset. Applicable only for .dae output
                                  currently.
  --generate-uvs                  Generates UVs by using simple box projection.
                                  Requires normals. Applicable only for .dae 
                                  output currently.
```
- new `IFCCONVERT_DOUBLE_PRECISION` build option: typedef real_t either to double (ON) or to float (OFF) and use real_t throughout the IfcConvert codebase

In hindsight, `--no-normals` might not be that useful after all. Also while I started adding new options, I did this: https://github.com/Tridify/IfcOpenShell-SourceForge/commit/b5725e2b4703a87a03585e869e791a2cd3cfec78 Does this seem good idea to you? Also, thinking more about it, majority of the new options are not really geometry iterator settings, but serializer settings, so maybe we should add a new class or enum/field for the serializer settings that are used only in IfcConvert?

**Comment by aothms** [comment]
Hi,

Thanks for raising this discussion. As you have read, people are already eager to get their hands on these improvements.

--names | good addition I think. Maybe the wildcard expansion can be added to --entity as well, so that one can type --include --type *, to work around infamous issue here [1]

[1] https://sourceforge.net/p/ifcopenshell/discussion/1782718/thread/d6365537/#92ae/707f/a76f/69f9/e4e3/4ffc

--use-names and -guids | maybe could use a more verbose name.

I think --no-normals can also be useful.

--center-model is also a great addition and your way of implementing it is clean, precise and unobtrusive. But there can still be a placement somewhere in the hierarchy with an offset close to the amount of significant digits in double precision floats, which would get the precision of the actual geometry get truncated. If all the placements are inspected in advance, also this case can alleviated maybe, but resulting in a less accurate center position, because only placements and not geometry would be considered for the model bounding box. Thoughts?

--generate-uvs | interesting addition. Curious to see if there is going to be more use of textures in IFC4 at some point.

I see in https://github.com/Tridify/IfcOpenShell-SourceForge/commit/b5725e2b4703a87a03585e869e791a2cd3cfec78 `disable_triangulation` gets renamed to `USE_WORLD_COORDS`. Is that intentional? Other than that I think your suggestion is good. Keep in mind though, that `WELD_VERTICES` used to be `true` by default. Also we could consider using a `std::bitset` instead, maybe that's bit more idiomatic C++, but I have no strong objections using the `unsigned` as is.

Kind regards,
Thomas

**Comment by Stinkfist0** [comment]
The accidents that occurred in that one commit are now fixed https://github.com/Tridify/IfcOpenShell-SourceForge/commit/c91c8d598936ae5cddfc552cd06e975b62f61e39

**Comment by Stinkfist0** [comment]
Also one thing we found useful https://github.com/Tridify/IfcOpenShell-SourceForge/commit/dc8494b3b0ce1699ec665d9557a32bd344367401 Does this seem OK for you?

**Comment by aothms** [comment]
Definitely. That's quite an oversight that it's not there now. Note though that other elements can have openings as well, maybe not as commonly, but at least for IfcSlab IIRC their usage is described in the implementers guide. Is there a reason to cast to IfcWall and not simply IfcElement?

**Comment by Stinkfist0** [comment]
AFAIK there's no specific reason, just an oversight I'd say.

**Comment by Stinkfist0** [comment]
I might also be looking into adding support for serializing only selected stories. I'm currently running into problems as the serialized DAE for a rather big IFC file results in 500 megabytes of DAE which Unity fails to import.

**Comment by aothms** [comment]
Something else that might alleviate that is the "Instances for identical geometry" feature that is scheduled for 0.5.0 [1]. Assuming your IFC contains such `IfcMappedItem`s (as they are called) it might cut another significant part off of your DAE files as typically detailed geometry (e.g doors windows) will be reused.

[1] https://sourceforge.net/p/ifcopenshell/discussion/1782718/thread/b5e3ee85/

**Comment by Stinkfist0** [comment]
Aye. Although support for instancing will be a great feature, in this case it would not probably save the day as the test case model is rather complex and irregular (and it's not even the full model) and I'm getting 4,914 hits of mapped items out of 4,419,285 items.

**Comment by aothms** [comment]
Ok, still would be interesting to know where this amount of geometry comes from and how it can be simplified in order to save bandwidth.

As for the filtering storeys, another fork has implemented a generic mechanism for filtering [1]. I was not completely happy with it because of the function pointer (which I am not sure how to do in Python, where this filtering should also work when wrapped). But something like this would be quite cool, especially if these filters can be combined and created from the command line, like `--include --entities IfcWall --include-with-children --product-guids <some_storey_guid>`.

[1] https://github.com/VTREEM/IfcOpenShell/commit/f07e18bb750262dbfcaac7b0dac53c540e54dc93#diff-2

**Comment by Stinkfist0** [comment]
We will be inspecting the model closer in the coming days. I was able to produce OBJ of one floor (the heaviest floor) which Unity succeeded to import.

Yeah, my use case could be generalized into using e.g. `--include-with-children --names NameOfTheFloor1 NameOfTheFloor2...`

**Comment by Stinkfist0** [comment]
I was able to produce a nice "slim" DAE around 90 MBs when using --weld-vertices (unfortunately my --generate-uvs and --weld-vertices don't play nice together). BTW --include-with-children would be a useful option too when wanting to separate different buildings to separate output files so I can definitely see how addition of that feature could be justified.

**Comment by Stinkfist0** [comment]
OK, I think I have finally some time to start working these features into a PR, https://github.com/Tridify/IfcOpenShell-New/tree/ifcconvert_enchancements

**Comment by aothms** [comment]
Nice! I already like those two commits :)

**Comment by Stinkfist0** [comment]
@aothms Does this approach look for you? https://github.com/Tridify/IfcOpenShell-New/commit/5c14376fe15f9b90917599b69859794b7bc626ab

**Comment by aothms** [comment]
This is nice! Thanks. As mentioned in the comments I mainly have two questions:

- Why the separate IfcConvertSettings? It seems it functionality is beneficial to others as well, such as the blender addon.
- Your rename of BOOST_FOREACH threw me off a bit. Is this common? I agree it's quite readable, but it took me a while to figure out what was going on (due to the way git ordered the files, but I can imagine most people don't end up reading this header file, so potentially being as confused as I was).

**Comment by Stinkfist0** [comment]
My idea was that polluting "generic" settings with serialization/IfcConvert-specific stuff didn't look nice, but agreed that pretty much all of these can be reworked into the "generic" settings, if we don't mind having maybe one or two "oddballs" there.

**Comment by aothms** [comment]
I wouldn't mind and prefer them to be merged :)

**Comment by Stinkfist0** [comment]
`#define foreach BOOST_FOREACH` is probably somewhat common in projects that use Boost, even the official documentation has this http://boost.cowic.de/rc/pdf/foreach.pdf

**Comment by aothms** [comment]
Ok that convinced me. I will add it to the infamous IfcOpenShell Style Guide.

**Comment by Stinkfist0** [comment]
OK, I took a fresh start here https://github.com/Tridify/IfcOpenShell-New/tree/ifcconvert_enhancements  also the branch name is now typo-free :)

**Comment by aothms** [comment]
Good to hear. Looking forward.

**Comment by Stinkfist0** [comment]
Was thinking that --use-names and --use-guids could be renamed to --use-entity-names and --use-entity-guids and implicit behavior of --use-names affecting material names could have an explicit --use-material-names. How does that sound?

**Comment by aothms** [comment]
I agree. But I would vote for 'element' rather than 'entity'. Entity is a bit confusing in the express/ifc world as it can also refer to the entity definition in the schema.

**Comment by Stinkfist0** [comment]
Aight.

**Comment by Stinkfist0** [comment]
I'm adding `--model-offset x,y,z` to accompany the `--center-model` option. Does this sound good? E.g. model.ifc is converted using --center-model and then extras_for_model.ifc is converted using e.g. `--model-offset -500000,0,0` (value gotten from the --center-model conversion of the model.ifc)

**Comment by aothms** [comment]
I was thinking something like that. Do we need special arrangements for localization? I.e whether the `,` or `.` is the decimal separator? Maybe choose `;` for the separation of the numbers?

**Comment by Stinkfist0** [comment]
Yeah, let's use ';' to prevent such issues.

**Comment by Stinkfist0** [comment]
Hi. Here's some stuff I've been pondering of adding to IfcConvert:
- `--with-children` to extract only e.g. desired storey(s) or building(s), `--include --with-children --names "Level 1" "` - I made an initial version of this already a while ago, does this look OK? https://github.com/Tridify/IfcOpenShell/commit/91051f020a0763a74313585ecb34bf739b8d33ec
- `--model-offset x;y;z` to complement `--center-model`
- making `--include (--names/entities)` and `--exclude (--entities/names)` not mutually exclusive, e.g. `--include --with-children --names "Level 1" --exclude --entities IfcOpeningElement`
- `--guid`, for making `--include --with-children` (using names can be a bit of error-prone)
- entity, name (and potentially guid) filtering would be nice to achieve in a generic fashion, maybe geom iterator could have some kind of add_filter() function for adding filters, geometry_filter, current filtering implementing using type_filter, name_filter, and guid_filter and IfcConvert would feed these to the geom iterator by default if needed.

**Comment by Stinkfist0** [comment]
I'm also thinking of some kind of `--write-float` option: if the IFC model happens to have a big offset, converting it using `IFCCONVERT_DOUBLE_PRECISION=0` (even if `--center-model` used) results in imprecision in the DAE output, but using `IFCCONVERT_DOUBLE_PRECISION=1` will result in a file too big for Unity to import successfully.

**Comment by aothms** [comment]
More informative to me would be `--digits=n` where `n` is directly fed to `std::setprecision`. This is probably not feasible for collada at the moment, but we could initially accept only 7 and 15 for example.

**Comment by Michal-sk** [comment]
Is it correct to say that `--center-model` does not work?

**Comment by Stinkfist0** [comment]
`--center-model` has been working for me without problems so far.
