### ISSUE TITLE
Regressions with IfcOpenHouse and IfcAdvancedHouse examples : ground shape is not generated anymore.

### ISSUE THREAD

**Issue by sylvainmarie** [IfcOpenShell/IfcOpenShell#200]
Commit [aebb9e3](https://github.com/IfcOpenShell/IfcOpenShell/commit/aebb9e324b0128503dde95bf9eb166c0ff9fb470#diff-6017059461ea51ae44daa8a8df4b6a42L268) includes a regression, causing a missing ground shape in IfcOpenHouse and IfcAdvancedHouse examples. 

Fixing that regression is easy, but commit [e8ae491](https://github.com/IfcOpenShell/IfcOpenShell/commit/00215867c06269b28a11acffb32baa730812a728) introduces another regression (causing the same problem) by shifting enum indices without updating ifcexpressparser/mapping.py (and others ??) and without regenerating the IFC headers using the EXPRESS parser.

More details on the [sourceforge forum](https://sourceforge.net/p/ifcopenshell/discussion/1782718/thread/337b2b46/).

**Comment by aothms** [comment]
Many thanks for your detective work. The issue indeed was related to a misalignment between the enumeration value, not with the python code, but with the `boost::variant` container index for the assignable attributes. Ironically I didn't forget about this, but somehow I have only checked it in into the pull request I was somewhat simultaneously working on [1].

What happened is that when adding the `ground_representation` to the file, the `IfcProductDefinitionShape.Representations` was not recognized as a aggregate of entity instances (due to the misalignment), and therefore were not traversed and added to the file recursively.

[1] https://github.com/IfcOpenShell/IfcOpenShell/pull/190/files#diff-b74cff1eb78dd804ddc8227d13b2bcb8

**Comment by FragColor** [comment]
Thanks for your response and your fix :)

However, I still have a question in mind : why don't you update `mapping.py` and generate IFC headers ? especially these lines :

```cpp
    supported_argument_types = set([
        'INT', 'BOOL', 'DOUBLE', 'STRING', 'BINARY', 'ENUMERATION', 'ENTITY_INSTANCE',
        'AGGREGATE_OF_INT', 'AGGREGATE_OF_DOUBLE', 'AGGREGATE_OF_STRING', 'AGGREGATE_OF_BINARY', 'AGGREGATE_OF_ENTITY_INSTANCE',
        'AGGREGATE_OF_AGGREGATE_OF_INT', 'AGGREGATE_OF_AGGREGATE_OF_DOUBLE', 'AGGREGATE_OF_AGGREGATE_OF_ENTITY_INSTANCE',
    ])
```
In the future, it could be problematic, don't you think ?

**Comment by aothms** [comment]
Hi, thanks for your interest. Admittedly this all not very clear. This supported `supported_argument_types` is an unordered set of attribute types that defines the types of attributes defined in C++. In particular here [1].

All attribute types in the 2x3 4 and Alignment schemas are supported, but arbitrary aggregations of attributes are not always implemented. Suppose somebody is working on a custom schema, which introduces a new attribute with type `LIST OF LIST OF LIST OF LIST OF STRING`. The the code generator for the schema will happily emit a function that returns `std::vector<std::vector<std::vector<std::vector<std::string> > > >` for that attribute, but as there is no cast function defined in [1], it will result in a compiler error when actually using the code. This `supported_argument_types` will then filter out code generation for this attribute, so that the code will still compile, just this particular attribute will not be accessible through the statically typed schema.

The commit that caused havoc earlier that introduces the `EMPTY_AGGREGATE` type is only relevant when parsing data. In the schema, every attribute will have an element type, but the parser can encounter things like `( )`, in which case it cannot determine the type of the element. The `EMPTY_AGGREGATE` allows it then to be mapped to any aggregate (say, `AGGREGATE_OF_INT`) when the untyped parse data (namespace `IfcParse::`) is connected to the statically typed schema data (namespace `Ifc2x3::`).

Hopefully in the next 0.6 release we'll have time to work on a better approach where arbitrarily typed attributes can be paired to the parse trees.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcUtil.h#L290
