### ISSUE TITLE
Aggregate relationships QOL features

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#2004]
The goal is to streamline managing project aggregates with the addition of buttons in the interface, to abstract as much as possible the low-level relationships from the user.

I'm keeping this issue open so I can keep improving it and to have a chance to get feedback if people start using the features :

- [x] Add IfcBuilding to IfcSite button
- [x] Add IfcSite to IfcProject button
- [x] Use popup panel to let user choose a name for their new spatial structure ?
- [x] Display Related objects in the Aggregates panel
- [x] Add button to select the related object or relating object
- [ ] Add all these to the right click context menu in the outliner ?
- [ ] Find a good place for these operators in the 3D viewport
- [ ] Test suite
- [ ] UI Polish
- [ ] Bug hunting and fixing

**Comment by Moult** [comment]
Completely agree. There are a number of processes that are intuitive in other BIM applications, but not intuitive in the BlenderBIM Add-on. Handling spatial elements is one of them, since although in IFC they are just objects like anything else, most BIM users expect dedicated interfaces for handling things like storeys and buildings.

Another example would be adding opening elements. Right now, I tried by adding an "opening element" entry in the shift-A menu, but although that's good enough for me, I suspect it's a pretty poor UX for others.

A third example would be adding types. Same thing - you could just use arbitrary objects or empties, but users don't realise that.

The whole drawings / sheet / annotation management needs a lot of love in the UI too.

I started writing this as a "yes I agree" and accidentally started ranting about the really poor UX throughout :) so much to do!

**Comment by Moult** [comment]
Closing as all core features mentioned in the OP are now implemented.
