### ISSUE TITLE
Module visibility doesn't quite work with grouped panels

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2006]
In the add-on settings, if I change the module visibility mode, the "Group" panels are still there even though they have no children

**Comment by vulevukusej** [comment]
I'm admittedly a little torn on this one.  Ever since creating the panel groups I havent gone back to the ui preferences again, it just didnt seem necessary, even though a lot of the panels aren't useful to me specifically.  

I guess my concern is that, yes we are offering customization to each individual user, but at the cost of usage consistency.  It's the kind of thing I think will hurt curious users, who can't understand why their BB doesn't look anything like what they see in videos, forums etc.   An example of this would be iTWO, which has literally hundreds of menus and options that can be toggled on and off in abstracted settings menus -> It's ugly.

Anyway, maybe I just woke up and I'm getting too philosophical 😁 - Let me know your thoughts @Moult , also what do you think @Gorgious56, you seem to have a nice sense of aesthetic/ui?

**Comment by Gorgious56** [comment]
I like the current implementation of the module visibility. I think, to solve the actual problem raised by this issue you would just need to parse in the panel `poll` method whether any of the childs of the parent panel are registered and not draw it if not.

I am personally not the biggest fan of the panel design of Blender so I'm biased against it, but we're stuck with it so... 

The million dollar question is how to offer the most functionality with the least visual pollution and the least resistance path to the desired tool, feature or property. But I believe that it's not the UI layout that really matters, but visual contrast, mnemonic devices and the brain plasticity and muscle memory will do the rest in the long run.

Other areas we can explore :

We have a lot of real estate in the 3D view header

![image](https://user-images.githubusercontent.com/25156105/151324425-fc7e94e1-0a96-40f2-8de4-78f38a7a9df3.png)

Also, I really like the right click context menu in other CAD softwares :

![image](https://user-images.githubusercontent.com/25156105/151324574-1ffcd068-07d8-41dc-86b1-291b938d05d1.png)

It's already very crowded in some modes but I think we can leverage it for some tools. also true for right-clicking in the outliner.

Also we can explore the [gpu module](https://docs.blender.org/api/current/gpu.html) to draw things directly in the viewport.

Your concern about new users getting confused while following tutorials is very valid, it's also a big problem of Blender as a whole since it changes so much between each version and the customization possibilities make it possible to have an unrecognizable interface. To top if off, the preferences layout of Blender is also confusing, and most people don't even know you can customize addons that way.

I'd say it's on the teachers to make sure they provide an experience as close to "vanilla" as possible when they make entry-level content. Afterwards, the community as a whole is responsible for helping each other out. At least in my mind that's how it should work ?

I guess it's one of these features we have to wait for more broad usage and see if there are any constructive complaints about it, since by design no one person will need to use all the individual UI presets.

Sorry for long post, it's an interesting discussion for sure :)

**Comment by vulevukusej** [comment]
@Gorgious56  - As far as I know there's no way to return a list of panel children is there?  It means the solution involves hardcoding a check for all children which will hurt code maintainability won't it?

**Comment by Gorgious56** [comment]
You're right, it isn't viable to do that in the `poll` method. However it might be OK to check this on update when the modules are individually toggled on or off in the preferences, you would need to add some logic there to unregister parent panels : https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/prop.py#L62-L82

I posted a Q on BSE regarding possible optimization : https://blender.stackexchange.com/q/251888/86891

**Comment by vulevukusej** [comment]
Thanks for posting that question.  Yeah your idea seems reasonable, cheers.

**Comment by Moult** [comment]
To answer the philosophical question, if indeed we can group the panels in a way that doesn't overwhelm, then maybe it's not necessary to have these user configurable visibility.

I'm enjoying the panel grouping so far. I've made some tweaks after a few things got in my way after trying to learn the system. Ambiguous words like util / misc confused me, and I also did some reordering based on project sequences (arch + struct first, mep second, 4d/5d after that, etc). Hopefully the changes I made make sense.

Right now, I feel OK with removing the panel visibility feature, but I'm happy to sleep on it and see how it feel after a few more weeks of usage.

As for other screen real estate, I suspect we'll start using those a lot more when modeling tools (e.g. wall modeling, inserting assets, attaching ducts, creating holes, etc) get a better UX.

**Comment by vulevukusej** [comment]
Ok so I was playing around with the idea of updating the panel group visibility after the user changes the addon preferences: https://gist.github.com/vulevukusej/8edb21c844211730b98771335cda39c9

This code works, but has some unfortunate disadvantages -  The panel groups will only be hidden if all the children are currently not registered.  This seems ok at first, but there are often contexts in which the child panels are polling false, but are still registered.  In this scenario the group is still visible, even though it seems as if there are no sub-panels..

**Comment by Moult** [comment]
Trying to get some closure on this, what's the current feel for toggling module visibility. Is this a feature people use? Do we just wait until Blender Apps becomes more mature? Is it working / not working?

**Comment by Moult** [comment]
Bump @vulevukusej @Gorgious56 what do you guys reckon?

**Comment by vulevukusej** [comment]
@Moult I've developed enough muscle memory that my hands always find the tab I'm looking for, so I haven't been using the toggles at all.  Other users I've worked with appreciate being able to turn off a majority of the panels, however this is usually becaused they are using BBIM for very specific workflows, something that I think the Blender Apps will help a lot with.

**Comment by Gorgious56** [comment]
I've used it successfully to disable panels in the N panel of the 3D viewport, they don't leave a lot of space for other addons. I don't remember needing to disable modules for other parts of the UI (I think the panel grouping did a good job of reducing cluttering). I do think it's nice to have the functionality like it is, it lets admins and power users select what the users can and cannot interact with. We're trying to shoehorn a rather expansive toolset into a rather specific user interface, so we're bound to have to make compromises. 

I wouldn't count too much on Blender Apps for the foreseeable future, usually the timeframe between the announcement of a feature and it becoming a thing is quite long. :)

**Comment by Moult** [comment]
OK, let's keep the group panel functionality. @vulevukusej do you mind checking whether or not this bug is still relevant, and if so what needs to be done to fix it so we can get some closure?

**Comment by vulevukusej** [comment]
sure ill take a look when i get a chance

**Comment by Moult** [comment]
Closing as module visibility is now removed in favour of the new tabbed interface.
