### ISSUE TITLE
Memory usage keeps rising after selections

### ISSUE THREAD

**Issue by htlcnn** [IfcOpenShell/IfcOpenShell#2014]
Hi,
I'm not sure if this is a BlenderBIM issue or Blender itself.
Blender's Memory usage keeps rising after each selection. With basic objects in General startup template, after a few selections memory stops around 19MB. When I import an ifc file and try to select/deselect objects, and keep looping that behaviour, I notice that Blender Memory goes up very quickly.
Please take some time to view the video: https://www.youtube.com/watch?v=v2VMBHvSio8

I'm using portable Blender 3.0.1 with BlenderBIM v 0.0.220130 installed.
P.S: ifc import is now much much faster than older BlenderBIM versions. Great!

**Comment by Moult** [comment]
I don't think this is a bug. Disable the BlenderBIM Add-on and see if you have the same effect. It's more pronounced with your BIM model because there are 13,000 separate objects. Array a cube and split it into 13k objects and you'll get a similar effect.

At a guess it's probably the built-in Blender undo system recording your actions.

When working with models between 30k to 100k+ objects, isolating your model into portions becomes more important, just like how Revit has worksets. In IFC, we need to move into a future where we can treat cities and buildings in those cities as large database where we can query and manipulate subsets. This is a big topic to tackle, but doesn't change the fact that that's how Blender seems to handle 13k objects. A bunch of optimisations were done for large model manipulation in the last release, so it was much worse in the past.
