### ISSUE TITLE
Ifcpatch OffSetObjectPlacements: moving IFC location question

### ISSUE THREAD

**Issue by ghost** [IfcOpenShell/IfcOpenShell#2028]
Hello, I have trouble with aligning an ifc model in solibri. I have a cube that is moved 1x1m1 positive axes and turned 45gr in solibri. 
Now I changed the same ifc with Ifcpatch-recipe and then loaded it in solibri. I would expect the cubes are then in the same place but that’s not how it turns out. Look at my picture. 
Does anyone know how this can be?! Thnx in advanced. 

![52AD2418-EBAB-4D16-8727-052506A6F07C](https://user-images.githubusercontent.com/99127312/152852622-53a1c265-eee7-4921-8390-52b49ae8b1ed.jpeg)

**Comment by Moult** [comment]
There is no right or wrong here I believe. You can either rotate first, then translate, or vice versa. Depending on the convention you choose, you get different results.

IfcPatch actually changes the object placements, meaning that the rotation affects the rooted placements in the graph - this may have a semantic implication on the model in terms of project east and project north. Solibri as a viewer, not a full authoring platform that IfcPatch assumes, may overlook this and so there isn't really clear definition of what Solibri could do to your model - whatever Solibri decides, goes.

**Comment by hvn74** [comment]
I discovered what the difference is between moving and rotating in solibri and recipe OffSetObjectPlacements.
First it makes no difference if an object is first rotated or first moved and then rotated.

But:
- When solibri moves an ifc-model it also moves the belonging "centralpoint" of the IFC. So when rotating it then rotates around the moved "centralpoint".
- The recipe OffSetObjectPlacements also moves an IFC but the "centralpoint" doesn't move along. So when rotating the ifc gets rotated along the 'original centralpoint'.  So then you get moved ifc-model moved with solibri and moved with recipe OffSetObjectPlacements  on different places in a solibri-projectfile.

See below picture for clearifying.

Question know is how can i mimick the OffSetObjectPlacements-recipe to do the same rotation as in Solibri?

Any help would be really great, thnx in advanced.

![Knipsel](https://user-images.githubusercontent.com/99127312/152945247-e32205a9-e8ea-4803-96af-8cfb0c67a3a2.JPG)

**Comment by hvn74** [comment]
I think solution for me (working with files in solibri) would be that the recipe OffSetObjectPlacements would **first** turn and then move. Because when it first turns then it always turns around the same centralpoint as solibri. 
Is this something what can easly be changed in OffSetObjectPlacements ?

**Comment by Moult** [comment]
The "centralpoint" you refer to is the absolute 0,0,0 in the IFC coordinate system. 0,0,0 is always 0,0,0 - it doesn't move. You "see" it moving because Solibri is visualising that 0,0,0 embedded in a "federated" model.

In any case, OffsetObjectPlacement moves, then rotates. Here's some pictures.


![2022-02-08-192532_322x295_scrot](https://user-images.githubusercontent.com/88302/152947323-481caf52-ed19-4842-bbbb-cdb2ce2120e6.png)
![2022-02-08-192605_335x364_scrot](https://user-images.githubusercontent.com/88302/152947319-ce13dc93-8154-4585-8856-7c28c704f4f2.png)

Solibri does the opposite, it rotates, then moves.


![2022-02-08-192710_219x231_scrot](https://user-images.githubusercontent.com/88302/152947552-65dc5e16-6fd7-45f1-a4ab-07307665add9.png)
![2022-02-08-192743_285x268_scrot](https://user-images.githubusercontent.com/88302/152947546-d7d02429-c38b-467e-bfcb-88e3e563f93e.png)

**Comment by hvn74** [comment]
Hello Moult, many thanks for youre time!!
We have the same conclusion. 
But is it possible to change the recipe so it also first turns and then moves? (just like solibri?).

Would be big timesaver for me and my company.....

Thnx in advanced.

**Comment by hvn74** [comment]
Hello Moult,
I managed to alter the code my self. 
I can send it to you if you wan’t. I’m a beginner and I think it can be optimized, but I’m proud I managed to work it out.

**Comment by Moult** [comment]
Hey @hvn74 ! Yes, I was going to write code for it this morning (it was late last night) but if you already have please send it and I'd be more than happy to add it as a feature! You can send it as a pull request or if you feel more comfortable you can just attach the files here or email dion@thinkmoult.com :D Thank you so much!

**Comment by hzm74** [comment]
Hello Moult, I mailed you the coding. I'm new on GitHub that's why I mailed it. New name is HzM74. 
Thank you very much.

**Comment by Moult** [comment]
@hzm74 Thanks so much! I've implemented it (I think) in hopefully a much simpler way than what you sent. Would you mind testing it? The new default is to follow Solibri's method, which I think you're absolutely right it's more intuitive. If you want to use the old behaviour, you can do [x,y,z,a,"True"] - the fifth parameter lets you enable the old method. Omitting the fifth argument uses the Solibri approach of rotating then moving.

Let me know if it works!

**Comment by hzm74** [comment]
@Moult, I tested it with and without true and both gave the right expected position.
Thank you too. (and thanx for mentioning me, my first contribution ;) )
