### ISSUE TITLE
Read xml with XSD Schema

### ISSUE THREAD

**Issue by TomBethoule** [IfcOpenShell/IfcOpenShell#203]
Hello,

I use Ifc OpenShell for convert ifc file to xml file. I would like read the xml file in JS with [JSONIX](https://github.com/highsource/jsonix).
But for this I needs a XSD schema file.
Do you have a schema XSD to read your generated xml file ? Or is it possible to create it please ? Thanks

King Regards Tom

**Comment by aothms** [comment]
Hi,

Currently there is not something like that. Due to the way the hierarchy is described in XML (using entity names as the XML tags) it wouldn't be completely trivial. I personally have little experience with authoring XSD, but I would certainly welcome contributions towards this.

In case you can provide the main structure of the XSD. We can help with extracting the necessary data from the IFC schema, like what kind of products can be part of the hierarchy and what their attribute names are.

Kind regards,
Thomas

**Comment by boroczkigabor** [comment]
2024 and still no schema definition? 😞

**Comment by aothms** [comment]
Contributions welcome :) Even if it's just a starting point. I personally don't have experience authoring XSD and I don't think there are people in the community who depend on this.
