### ISSUE TITLE
Segfault performing boolean on invalid entities

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2037]
Basically, the error in the file is a doomed attempt to do a boolean intersection of two Shape Representation entities (which is invalid), this segfaults IfcConvert:

```
#2324=IFCEXTRUDEDAREASOLID(#2320,#2322,#2323,0.4);
#2325=IFCSHAPEREPRESENTATION(#13,'Body','SweptSolid',(#2324));
#2336=IFCEXTRUDEDAREASOLID(#2332,#2334,#2335,1.);
#2337=IFCSHAPEREPRESENTATION(#13,'Body','SweptSolid',(#2336));
#2338=IFCBOOLEANRESULT(.INTERSECTION.,#2337,#2325);
```

[_test.crash.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8037000/_test.crash.ifc.zip)

**Comment by Moult** [comment]
This is plain invalid, so I personally don't think IfcOpenShell should support this at all.

**Comment by brunopostle** [comment]
It shouldn't support this kind of thing, but it also shouldn't segfault on reading untrusted data - open this file in blenderbim and it kills blender.

**Comment by aothms** [comment]
I agree with both. It's relatively straightforward to handle on a generic level. Since this boolean operand is a select, it's also now possible in v0.7 as they are handled in the type system. Getting readable error messages in the end was a bit more involved, but now we have this in the output:

~~~
[Error] [2022-02-10 13:03:36] {0SNrzTvlr6iQ$YZVUwPnah} Instance of type IfcShapeRepresentation cannot be cast to IfcBooleanOperand
Failed to convert:
#2338=IfcBooleanResult(.INTERSECTION.,#2337,#2325)
~~~
