### ISSUE TITLE
BB: Types not importing in Revit 2020

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2045]
[this](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/4926e662c0bddd8533b6799a4a51d98be19748de/Random_Tests/Types_Generic/from_Blender/Types_Generic_02.ifc) file doesn't link or open in Revit.

**Comment by Moult** [comment]
You've hit a TODO I never fixed :) https://github.com/IfcOpenShell/IfcOpenShell/commit/4d6eba0a0614013d43c375d32aae479890f0b763#diff-3d2bb522952b9394ac48b9c60b1d0d2abe43e6ec3b49924d606f3bc3edca0458L38-L39 IFC2X3 never properly denoted a mapping between types and occurrences (e.g. a WallType should create Walls) this has been fixed in IFC4, but that's life.
