### ISSUE TITLE
BB: be able to filter when adding types

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2060]
Type lists get big.  Would be nice to filter down.
![image](https://user-images.githubusercontent.com/507113/155262893-a9f28670-af7f-44be-a004-8b7138eac109.png)

**Comment by Gorgious56** [comment]
I think this particular UI element doesn't allow for text search field, but maybe a text box below it or a search box that opens when clicking on a magnifying glass icon or similar would do it ?

**Comment by Moult** [comment]
A minor note, not what you want to hear probably, but according to the IFC spec the type name is meant to be a short code that you'd tag it with on a drawing, e.g. `02d-15ga`, so this is technically misuse of the attribute, and on larger projects I don't think you'd actually use that many types but these are just excuses, we should come up with a proper UX solution to this.

**Comment by brunopostle** [comment]
Also, there can be more than one Project Library, so this would probably need to be exposed as a heirarchy (can Project Libraries be nested?)

**Comment by Moult** [comment]
Giving some thought on this, since you have the same issue with materials, I can think of a few UX solutions. Which would you prefer?

1. When there are too many items (maybe a global setting), another "filter" icon will appear. You can then type in a text filter, and the dropdown will update to only show elements that contain that text.
2. When there are too many items, it doesn't even show the dropdown and uses a UI list. You can see an example of what a UI list looks like in the Scene Properties > IFC Geometry > IFC Profiles. A UI list is scrollable and comes with a filter.
3. Forget the dropdown and always use a UI list.
4. Show a dropdown, but the dropdown will only show up to MAX_ITEMS, then after that it will have a "Next page" or a "Previous Page" so you can paginate your way through a long list.
