### ISSUE TITLE
BB: IfcUShapeProfileDef's Flange Slope going in the opposite direction

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2104]
files: https://gitlab.com/osarch/FreeMVD_WorkFlow/-/tree/5cdf3154417b3f44549867b9c2873fdf1a8788e8/Random_Tests/Beam_C_Channel/from_Blender

not sure if this is a BB/ifcopenshell or a Revit problem. :)

If i make the `Flange Slope` negative in BB it shows up correctly in Revit.

![image](https://user-images.githubusercontent.com/507113/160219339-830943e1-a5b0-482a-899f-94a11f5d0658.png)

![image](https://user-images.githubusercontent.com/507113/160219355-59032d1d-0e78-442b-bcd3-ef7edd1cb0e7.png)

**Comment by Moult** [comment]
Cheers, I can replicate this and I suspect it is an IfcOpenShell bug since we rely purely on IfcOpenShell to generate these profiles - I've attached a sample file which maybe can help @aothms debug

[ushapedprofile.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8354871/ushapedprofile.txt)

**Comment by aothms** [comment]
FlangeSlope is an IfcPlaneAngleMeasure, but there is no plane angle unit in the file. Could that be related to this issue? I can look into this, but I'll do it after the units are complete.

**Comment by Moult** [comment]
Ah yes, indeed when an angle measure unit is defined it works as expected. I guess Revit must be making assumptions.

At the time of writing there is only a UI for adding / assigning SI Units but not conversion units so you can only specify radians but not degrees, so I'll keep this issue open until we can manage conversion units.

![2022-03-27-094145_576x216_scrot](https://user-images.githubusercontent.com/88302/160259529-acc54fba-9db5-4763-9740-871474240abe.png)

**Comment by Moult** [comment]
OK - you can now add / remove conversion based units for any "normal" conversion unit defined in the buildingSMART conversion table (usual stuff like inches, degrees, fahrenheit, etc). Still no support for "abnormal" invented conversion units but that's probably not important now.

**Comment by theoryshaw** [comment]
If you import the [ifc file](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/5cdf3154417b3f44549867b9c2873fdf1a8788e8/Random_Tests/Beam_C_Channel/from_Blender/Beam_C_Channel_02.ifc), and then add the IfcConversionBasedUnit, it works, but if you try with the opened [Blender file](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/5cdf3154417b3f44549867b9c2873fdf1a8788e8/Random_Tests/Beam_C_Channel/from_Blender/Beam_C_Channel_01.blend) you get the following error.



video: https://www.dropbox.com/s/z5z6l0crme3zur5/2022-03-27_12-24-56_Blender_%5BDDropboxGitLabFreeMVD_WorkFlowRando_blender.mp4?dl=0

**Comment by Moult** [comment]
That error is most likely unrelated unfortunately, and I can't determine the root cause.

Basically, sometimes when errors occur, the Blend file and the IFC goes out of sync, that causes errors like what you see. The Blend file was already out of sync even before doing anything to the conversion based unit. You can test this by opening the Blend and clicking the leftmost beam and clicking "Get Representation IFC Parameters". You'll see it works on 2 of the beams, but one is out of sync already, so it will fail.

Unfortunately, the root cause of what made it out of sync has already occurred and we missed that error message. Over time, with the additional test cases and slowly increasing stability, this type of error will become less common.

The only sure way to "resync" Blender and IFC is to import fresh, as you did. Alternatively, you can click on the unsynced beam, and in Object Tab > IFC Geometry > IFC Representations, click the triangle next to the swept solid representation - this will reload the beam's extruded geometry and thus bring it back in sync.

Hope it helps.
