### ISSUE TITLE
IfcConvert: Failed to convert curve: IfcTrimmedCurve

### ISSUE THREAD

**Issue by bvantholt** [IfcOpenShell/IfcOpenShell#2115]
Hi all,
I'm trying to convert .IFC files into .OBJ and/or .GLTF files using the latest version of IfcConvert but unfortunately I'm getting the errors as shown below. I'm trying to figure out why these errors occur, so I thought why not ask here. Has it got anything to do with the schema being used for example? The .IFC files I'm trying to convert have IFC2X3 set as schema.

The command I'm using is maybe too simple, am I missing some important parameters here? IfcConvert BLOK_A.ifc BLOK_A.obj

[Error] {1I0NP3bnvFqB_BULGu2dZp} Failed to convert curve:
#3568771=IfcTrimmedCurve(#3568770,(IfcParameterValue(90.0000000000001)),(IfcParameterValue(180.)),.T.,.PARAMETER.)
[Error] {1I0NP3bnvFqB_BULGu2dZp} Failed to convert curve:
#3568786=IfcTrimmedCurve(#3568785,(IfcParameterValue(180.)),(IfcParameterValue(270.)),.T.,.PARAMETER.)
[Error] {1I0NP3bnvFqB_BULGu2dZp} Failed to convert curve:
#3568801=IfcTrimmedCurve(#3568800,(IfcParameterValue(270.)),(IfcParameterValue(360.)),.T.,.PARAMETER.)
[Error] {1I0NP3bnvFqB_BULGu2dZp} Failed to convert curve:
#3568857=IfcTrimmedCurve(#3568856,(IfcParameterValue(90.0000000000001)),(IfcParameterValue(180.)),.T.,.PARAMETER.)
[Error] {1I0NP3bnvFqB_BULGu2dZp} Failed to convert curve:
#3568872=IfcTrimmedCurve(#3568871,(IfcParameterValue(180.)),(IfcParameterValue(270.)),.T.,.PARAMETER.)
[Error] {1I0NP3bnvFqB_BULGu2dZp} Failed to convert curve:
#3568887=IfcTrimmedCurve(#3568886,(IfcParameterValue(270.)),(IfcParameterValue(360.)),.T.,.PARAMETER.)
[Error] {0f0w3bNe53EQnpBLLNo2Er} Failed to convert curve:
#3983303=IfcTrimmedCurve(#3983302,(IfcParameterValue(87.9999999995671)),(IfcParameterValue(258.486660875586)),.T.,.PARAMETER.)
[Error] {0f0w3bNe53EQnpBLLNo27o} Failed to convert curve:
#3985912=IfcTrimmedCurve(#3985911,(IfcParameterValue(88.0000000000062)),(IfcParameterValue(258.486660875616)),.T.,.PARAMETER.)
[Error] {0f0w3bNe53EQnpBLLNo21_} Failed to convert curve:
#3986232=IfcTrimmedCurve(#3986231,(IfcParameterValue(88.0000000000062)),(IfcParameterValue(258.486660875616)),.T.,.PARAMETER.)
[Error] {2PFWqMu6b2mxqavbpzEK5X} Failed to convert curve:
#4000995=IfcTrimmedCurve(#4000994,(IfcParameterValue(88.0000000000601)),(IfcParameterValue(258.486660875586)),.T.,.PARAMETER.)

_P.S. my goal is to convert .IFC files into at runtime importable models in Unity_

Hoping to find answers here.
Thanks in advance.

**Comment by aothms** [comment]
Some comments:

- IfcConvert is quite verbose, where most viewers silently discard erroneous data. An error might not necessarily mean that data is missing compared to other IFC implementations.
- Usually IfcConvert is a bit more verbose in terms of what's actually the cause of the failure. Unfortunately not in this case. So I can't really see what's the code path. One code path that doesn't actually log an informative message appears to be https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/IfcGeomWires.cpp#L481 So a trimmed curve over a non-curve entity. Could you attach the file (or a failing element thereof such as 1I0NP3bnvFqB_BULGu2dZp) or look into the file what's the definition of e.g #3568770
- Otherwise, running IfcConvert can and should be as simple as that. Typically I'd recommend Collada (.dae) instead of .obj because .obj doesn't support object coordinate systems, so instanced geometries have to get duplicated.

**Comment by bvantholt** [comment]
Hi,

Thanks for the quick response.
Ah that explains a lot. And thanks for the Collada tip!

I included a part of the IFC file containing the failing element (1I0NP3bnvFqB_BULGu2dZp)
[model.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8387142/model.txt)

The failing element is (1I0NP3bnvFqB_BULGu2dZp):
#3569179= IFCRAILING('1I0NP3bnvFqB_BULGu2dZp',#41,'Railing:34_aluminium_lamellen_hekwerk_galerij:1505870',$,'Railing:34_aluminium_lamellen_hekwerk_galerij',#3567461,#3569177,'1505870',.NOTDEFINED.);

..and the definition of #3568770:
#3568770= IFCCIRCLE(#3568769,0.999999999999999);
#3568771= IFCTRIMMEDCURVE(#3568770,(IFCPARAMETERVALUE(90.0000000000001)),(IFCPARAMETERVALUE(180.)),.T.,.PARAMETER.);

**Comment by aothms** [comment]
IFC is a quite a dense graph structure, copying just a fragment like this creates a lot of dangling references. With the following python script you can quickly isolate the problematic element into a new file. Otherwise please attach the full file (or send to models@ifcopenshell.org) thanks.

~~~py
import ifcopenshell
f = ifcopenshell.open('BLOK_A.ifc')
g = ifcopenshell.file(schema=f.schema)
g.add(f.by_type('IfcProject')[0])
g.add(f['1I0NP3bnvFqB_BULGu2dZp'])
g.write('element.ifc')
~~~

**Comment by bvantholt** [comment]
I understand, sorry for that. 

I ran the python script which resulted in the following file:
[element.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8387483/element.txt)

**Comment by aothms** [comment]
Thanks.

It looks like the element is processed reasonably, the error is about the fillet (the trimmed circle) of the vertical bars

![afbeelding](https://user-images.githubusercontent.com/1096535/161015116-b99cab4c-aee2-4a63-90a5-1dc1ecde2681.png)

I've implemented a "fix" so that you can now use `IfcConvert` with `--strict-tolerance` and process the fillets correctly. IfcOpenShell is a bit overcautious in small details for stability and strict-tolerance eliminates that caution.

![afbeelding](https://user-images.githubusercontent.com/1096535/161023356-8865b38e-8695-4c2c-b0a4-cef5982ad23e.png)

**Comment by bvantholt** [comment]
Oh wauw, thanks a lot, I'll try it out.

Issue can be closed then I suppose :)
