### ISSUE TITLE
Erronous geometry from IFCCLOSEDSHELL

### ISSUE THREAD

**Issue by larsmoa** [IfcOpenShell/IfcOpenShell#212]
I have a wall modeled with `IFCCLOSEDSHELL` that is triangulated erroneously. In Solibri (and SimpleBIM) the wall is rendered correctly:

![image](https://cloud.githubusercontent.com/assets/6741854/25802164/60fef9a2-33f1-11e7-8c8c-440b8b2be245.png)

IfcConvert fails to convert the file correctly (to OBJ), the result ending up to be:

![image](https://cloud.githubusercontent.com/assets/6741854/25802199/82a3c538-33f1-11e7-9dbd-38c5b8599245.png)

`IfcConvert` outputs an error during conversion:

> [Warning] {02TlSS1wf8HP5Dv3KTuiAq} Multiple components in IfcConnectedFaceSet

The file that fails to convert correctly is [deformed_wall_offset.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/983274/deformed_wall_offset.ifc.zip).

**Comment by aothms** [comment]
Thanks for your report.

This seems to be caused by some duplicate faces in the first operand geometry. Just some of them below, there are more:

~~~
#463=IfcCartesianPoint((954.,-236.,750.))
#467=IfcCartesianPoint((2634.,-236.,750.))
#597=IfcCartesianPoint((2634.,236.,750.))
#601=IfcCartesianPoint((954.,236.,750.))

#727=IfcPolyLoop((#463,#467,#597,#601))
#739=IfcPolyLoop((#463,#597,#601))
#742=IfcPolyLoop((#597,#463,#467))
~~~

This is invalid as faces are not supposed to overlap within in a shell. In itself this is not so much a problem though for IfcOpenShell as it keeps these faces as separate constructs if `--sew-shells` is not specified.

The problem though is that later on, this geometry is used as a boolean operand (in a meaningless operation as the opening volumes do not intersect with the closed shell geometry to begin with) and for that purpose the topology needs to be reconstructed and an invalid volume is obtained. From there on all bets are off.

In this case this would be fairly easy to resolve as overlapping faces can be easily eliminated. The general problem is much harder to solve as you need to consider the possibility of multiple cartesian points with the same coordinates or the proximity of segments within the precision criterion of the model.

This will be fixed at some point, but considering the issues with the model, it might be a while until I get to it.

**Comment by larsmoa** [comment]
I do not think this needs fixing as the input is invalid.
