### ISSUE TITLE
[IfcConvert] No geometry iterator registered for IFC4X3_RC4

### ISSUE THREAD

**Issue by ketourneau** [IfcOpenShell/IfcOpenShell#2127]
Hi,

I try to convert a IFC4X3_RC4 ifc file but i got this error :
`No geometry iterator registered for IFC4X3_RC4`

Why 4x3_rc4 schema version is defined in cmake if there is no geometry iterator ?
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/cmake/CMakeLists.txt#L582

[IFC4X3_RC4.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8425475/IFC4X3_RC4.ifc.zip)

**Comment by aothms** [comment]
Indeed apparently we only went as far as rc2 for the geometry. You can still use the schema to parse files though. Feel free to create a PR with the required changes. But it's not very meaningful because no effort has yet been invested in the implementing the geometry definitions introduced in 4x3.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom_schema_agnostic/Kernel.cpp#L63-L68

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom_schema_agnostic/IteratorImplementation.cpp#L26-L32

Bootstrapping the kernel/iterator modules is unfortunately still hardcoded. We should instead rely on sth like boost pp foreach https://www.boost.org/doc/libs/1_78_0/libs/preprocessor/doc/ref/seq_for_each.html

**Comment by BD-Bloc** [comment]
Hi @aothms, is there any update on this issue? Do you know if someone is working to implement the geometry definitions for the rc4?

**Comment by ketourneau** [comment]
It's work with this version : https://github.com/IfcOpenBot/IfcOpenShell/commit/fa6bbf2d4a69cb8d1f793b3d4ca86571e9b414e8
