### ISSUE TITLE
BB: Open sheet doesn't work right out of the gate

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2144]
'Open sheet' doesn't work right out of the gate, but if you create a new sheet, add a drawing, then it works. 

video: https://www.dropbox.com/s/12ys3d0l7o962sk/2022-04-16_19-05-30.mp4?dl=0

**Comment by Moult** [comment]
I can't recreate this. Potentially it is already fixed?

**Comment by Moult** [comment]
Bump @theoryshaw

**Comment by theoryshaw** [comment]
Hi, sorry, was off this weekend. 

Still seems to have a glitch.  Perhaps i'm using it wrong. 
https://www.dropbox.com/s/jtinn1infp4q4sp/2023-02-06_09-39-33_Blender_blender.mp4?dl=0

Using this file, from `BlenderBim - Step by Step Tutorial- Model - Part 5.ifc` from...
https://community.osarch.org/discussion/1279/blenderbim-beginner-tutorial-step-by-step-project-part-4-5-2d-detail-layout

**Comment by Moult** [comment]
I see, so right now the sheet data itself is not stored in the IFC, so having the IFC is not itself, you need to have the SVG as well.

**Comment by Moult** [comment]
I don't think it makes sense for the IFC to fully encode what can be stored in an SVG. At best, we could probably capture "this is a view on a document, which is placed at these X Y coords with a width and height", but that barely captures the full breadth of what is needed to store a document (e.g. client logos in titleblocks, random custom branding and fonts, etc). I think it's best to leave the SVG data in SVG, and not make it so that the IFC has the capability of "generating" the SVG from nothing.
