### ISSUE TITLE
Included file (IfcGeomObjects.h) no longer exists

### ISSUE THREAD

**Issue by dushyant-basson** [IfcOpenShell/IfcOpenShell#2145]
https://github.com/IfcOpenShell/IfcOpenShell/blob/c79eb609598dbeda0c2c2caeb4c73550b05ea586/src/qtviewer/mainwindow.h#L9

The file included in qtviewer/mainwindow.h on line#9, does not exist anymore. It seems the qtviewer code has not been updated for a long time and it requires qt4 (which is hard to find now). I am interested in a viewer that uses IfcOpenShell. This one looked something I could work on. What are your plans with qtviewer?

**Comment by aothms** [comment]
IfcGeomObjects is from IfcOpenShell version 0.4

- 0.4: IfcGeomObjects: geometry handling as static functions, i.e works only on single file, single threaded
- 0.5: IfcGeom: iterator introduced, geometry handling encapsulated in class
- 0.6: support for multiple schemas at runtime

The incentive for native application development got a little bit reduced over time due to:

- ifc-pipeline: https://github.com/AECgeeks/ifc-pipeline MIT licensed web-based
- blenderbim: blenderbim.org/ Blender Add-on that uses IfcOpenShell supports viewing editing, Blender is easily extensible
- ifcopenshell python app: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/geom/app.py

But I think there is still space for a native tool based on IfcOpenShell, so if you have an interest in taking the initiative on this I'd definitely help out where ever I can.

**Comment by dushyant-basson** [comment]
Thanks for the info @aothms . I am interested in a native IFC viewer.
So can IfcGeom.h now replace IfcGeomObjects.h in the qtviewer? Also I'm trying to edit the CMakeLists.txt to use Qt5 (I think it should be upgraded now to Qt5 / Qt6). 
Please could you write to me at: onizu dot db at gmail dot com. Thanks.

**Comment by aothms** [comment]
> So can IfcGeom.h now replace IfcGeomObjects.h in the qtviewer?

Indeed, maybe there are some useful bits here:

https://github.com/IfcOpenShell/IfcOpenShell/discussions/1933

> I think it should be upgraded now to Qt5 / Qt6

I agree, note that I'm not at all familiar with Qt though

**Comment by Moult** [comment]
@dushyant-basson #2224 might interest you.

**Comment by dirkolbrich** [comment]
@dushyant-basson can be closed due to https://github.com/IfcOpenShell/IfcOpenShell/pull/3574?

**Comment by dushyant-basson** [comment]
> 

Yes, certainly. Thanks!
