### ISSUE TITLE
Blenderbim svgwrite 1.4.2 incompatible with behave due to elementtree monkey patching

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2159]
If I click the Create Drawing button after loading this [untitled.ifc](https://github.com/IfcOpenShell/IfcOpenShell/issues/1153#issuecomment-1105876816) file, I get this error:

```
Error: Python: Traceback (most recent call last):
  File "/usr/share/blender/3.1/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 131, in execute
    annotation_svg = self.generate_annotation(context)
  File "/usr/share/blender/3.1/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 445, in generate_annotation
    svg_writer.write("annotation")
  File "/usr/share/blender/3.1/scripts/addons/blenderbim/bim/module/drawing/svgwriter.py", line 94, in write
    self.svg.save(pretty=True)
  File "/usr/lib/python3.10/site-packages/svgwrite/drawing.py", line 120, in save
    self.write(fileobj, pretty=pretty, indent=indent)
  File "/usr/lib/python3.10/site-packages/svgwrite/drawing.py", line 108, in write
    xml_string = self.tostring()
  File "/usr/lib/python3.10/site-packages/svgwrite/base.py", line 189, in tostring
    xml_utf8_str = etree.tostring(xml, encoding='utf-8')
  File "/usr/lib64/python3.10/xml/etree/ElementTree.py", line 1109, in tostring
    ElementTree(element).write(stream, encoding,
  File "/usr/lib64/python3.10/xml/etree/ElementTree.py", line 748, in write
    serialize(write, self._root, qnames, namespaces,
  File "/usr/lib/python3.10/site-packages/behave/reporter/junit.py", line 130, in _serialize_xml3
    return orig(write, elem, qnames, namespaces, short_empty_elements)
TypeError: _serialize_xml_with_CDATA_support() takes 4 positional arguments but 5 were given
```

![image](https://user-images.githubusercontent.com/1747315/164968861-a6982469-e069-44bf-9529-824196ffa38a.png)

I'm using local system libraries:

- ElementTree is from python 3.10.4
- svgwrite 1.4.2 (the blenderbim ZIP has 1.3.1)
- behave 1.2.6 (same version as in the blenderbim ZIP)

It looks like something has changed in svgwrite between 1.3.1 and 1.4.2.

**Comment by aothms** [comment]
As you can see the stacktrace is very odd. From ElementTree it jumps to behave:

~~~
  File "/usr/lib64/python3.10/xml/etree/ElementTree.py", line 748, in write
    serialize(write, self._root, qnames, namespaces,
  File "/usr/lib/python3.10/site-packages/behave/reporter/junit.py", line 130, in _serialize_xml3
    return orig(write, elem, qnames, namespaces, short_empty_elements)
~~~

Seems like everybody is patching etree globally and it's bound to cause problems:

https://github.com/mozman/svgwrite/blob/master/svgwrite/etree.py#L49

https://github.com/nschloe/meshio/issues/806

So yes, it might well be due to one of the dependency version.

**Comment by Moult** [comment]
What happens if behave is not included as a module (try just stub it out perhaps)? I think I ran into similar really strange bugs with svgwrite in the past and I failed horribly to debug them (only random trial error and git reverting got it back into a sane state)

**Comment by brunopostle** [comment]
Yes, if I remove behave completely, the SVG gets rendered:

![image](https://user-images.githubusercontent.com/1747315/164970374-a6a3cc3d-3fb6-4992-9385-ab96dd69b378.png)

There is a new warning on blender startup:

    Failed to load BIMTester. Try disabling other add-ons, in particular Blender-OSM. See bug #1318.

**Comment by brunopostle** [comment]
Also there is a file missing from git, I can create all the drawings, but not the sheets:

    FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/blender/3.1/scripts/addons/blenderbim/bim/data/sheets/A01 - UNTITLED.svg'

**Comment by Moult** [comment]
@brunopostle yes, that is by design, the IFC is not enough for sheet layouts. The SVG sheet is also required, which I didn't bother to upload.

The add-on comes bundled with fonts, default CSS, default SVG markers, symbols, and titleblock templates. Assuming you use whats bundled, that allows it to generate drawings. The moment you use custom CSS or markers or whatever, distributing the IFC is not sufficient, you also need to distribute your CSS / SVG defs.

A sheet in IFC is nothing more than a document. The presentation of the sheet is all in SVGs which uses template tags and use tags to embed / place drawing SVGs, drawing title SVGs, titleblock SVGs, schedule SVGs or any other generic embeddable thing. This is all in SVG, and IFC only holds a document URI reference to it. So if I don't distribute that SVG layout, then yes, you will be unable to create the sheets unfortunately.

Coming up with good ways to package this IFC+SVG+CSS combo, and properly reference the difference between templated layouts and fully compiled (i.e. any variables replaced such as revision and document names, and inlined into a single distributable SVG / PDF / DXF rather than a collection of SVG references) is still on the todo list.

For the moment, you can create a new sheet and place drawings on them using the built-in titleblocks :) Then, you can edit that sheet in Inkscape to lay the drawings and drawing titles out the way you want.

**Comment by brunopostle** [comment]
I have the font installed in the blender addons folder, I guess it needs to be installed using the system font installer:

    /usr/share/blender/3.1/scripts/addons/blenderbim/bim/data/fonts/OpenGost Type B TT.ttf

![OpenGostTypeBTT-Regular](https://user-images.githubusercontent.com/1747315/164973405-929ce703-6a2f-4bef-b4d3-45b9de04055c.png)

**Comment by Moult** [comment]
Indeed, it is after all just a vanilla SVG so it looks in your system for fonts. There are a few glyphs missing in that font I'd love to find the time to add, such as degrees, and diameter. For the moment though it's largely equivalent to the famous proprietary CAD Gost font :)

**Comment by brunopostle** [comment]
It looks like SVG fonts can be referenced with a URI.

A use case would be dynamically building and updating a (PDF for the foreseeable future) drawing set using git commit hooks, this would likely be on a headless server without a blender installation.

In this situation, all the standard hatches, symbols and fonts could either be shared (literally in /usr/share or equivalent), or they could be duplicated into every repository. For 100% reproducibility, these files would need to duplicated.

**Comment by Moult** [comment]
Oh fantastic I'd have to investigate that. Would you like to try hack on this or investigate further / make proposals on a good packaging strategy?

**Comment by brunopostle** [comment]
@Moult If I can come up with anything I will, so much to do, so little time to do it

**Comment by Moult** [comment]
OK trying to get some closure on this I suspect this is the offending code in behave: https://github.com/behave/behave/blob/61781ede2e701aec6dc0314478ab52a58b2e09b0/behave/reporter/junit.py#L111-L140

Both libs are being naughty, probably because ETree itself has problems. Potential solutions:

 1. Monkey patch _serialize_xml a _third_time (woo! here there be dragons!) in the BlenderBIM Add-on that has a compatible signature and behaviour with both libs.
 2. Scrap behave, maybe in favour of pytest-bdd? Does the same thing really.
 3. Scrap svgwrite, not sure what would replace it?
 4. Patch either behave or svgwrite in our packaging.

Opinions?

**Comment by Moult** [comment]
I ended up with option 4 because Behave was already patched, and Behave was only using it for JUnit support. I figure advanced users using JUnit XML won't be running it through the BlenderBIM Add-on UI anyway so simply disabling JUnit support in Behave is easy and doesn't hurt anyone.
