### ISSUE TITLE
Does IfcPropertyEnumeratedValue::EnumerationValues break compatibility?

### ISSUE THREAD

**Issue by ssg3d** [IfcOpenShell/IfcOpenShell#2166]
`IfcPropertyEnumeratedValue::EnumerationValues` yields `boost::shared_ptr<x>` for Ifc2x3 while it yields `boost::optional<boost::shared_ptr<x>>` for Ifc4. 

It seems to break my template code where I want to call
```
auto values = ifcenumvalue->EnumerationValues();
values->size(); // will not work for Ifc4 where I need to do (*values)->size();
```

Agreed that this has been made optional in the new spec, but that can be easily achieved in code by returning a null pointer.  Is there another way to elegantly do this without resorting to a schema check in if-then statements?

**Comment by aothms** [comment]
Yes, buildingSMART considers compatibility mostly a matter of exchange files, so broadening type modifications like this are generally considered compatible, but compatible source code is less of a concern unfortunately.

I'd propose to just wrap the call to `ifcenumvalue->EnumerationValues()` in a function. Like below:

~~~C++
template <typename T>
struct is_optional : std::false_type {};

template <typename T>
struct is_optional<boost::optional<T> > : std::true_type {};

template <typename T>
typename std::enable_if<!is_optional<T>::value, boost::optional<T>>::type conditionally_make_optional(T t) {
	return boost::make_optional(t);
}

template <typename T>
typename std::enable_if<is_optional<T>::value, T>::type conditionally_make_optional(T t) {
	return t;
}


int main(int argc, wchar_t** argv) {
	int i;
	boost::optional<int> ii;

	auto x = conditionally_make_optional(i);
	auto y = conditionally_make_optional(ii);

	static_assert(std::is_same<decltype(x), decltype(y)>::value, "types equal");
}
~~~

conditionally_make_optional(T t) returns optional<T> in case T is not a boost::optional and otherwise just returns t;

Maybe there's a more readable way using just overloads instead of SFINAE but I couldn't come up with it just now.

Hope that helps.

**Comment by Moult** [comment]
Sounds like this can be closed?

**Comment by ssg3d** [comment]
@Moult yes it can and I see you have.
