### ISSUE TITLE
IfcConverter - IFC To glb problem 

### ISSUE THREAD

**Issue by Takieddinex** [IfcOpenShell/IfcOpenShell#2167]
Hello !
I'm doing an ifc to glb file conversion with the latest ifcConverter version but the result is not correct as you can see on the pictures.
NB: The conversion of building files is done correctly but for networks like these are not good.
Thank you ! 

![image](https://user-images.githubusercontent.com/95845810/165491932-4fbcd674-07d8-4966-8e1b-a96c42d30fb2.png)
![image](https://user-images.githubusercontent.com/95845810/165492000-af80b77a-fc85-4428-94c0-544c309ccc65.png)
![image](https://user-images.githubusercontent.com/95845810/165492096-45a45641-7e6c-4e48-a716-16e0b711b8fe.png)

**Comment by Moult** [comment]
Have you considered that it may be a coordinates issue in your IFC? Your IFC may use map coordinates which are typically large, and viewers may not be capable for displaying those large coordinates properly. I suspect many glb viewers deal with small coordinates. If it is a civil model perhaps you may choose to use a false origin with an XYZ offset? If it is a vertical construction which is non-civil, perhaps you can georeference your model using IfcMapConversion instead?

**Comment by aothms** [comment]
Try --site-local-placement or --building-local-placement as options in IfcConvert to eliminate large offsets introduced in the placement hierarchy

**Comment by Takieddinex** [comment]
if the writing of the command is correct, I find the same result.  
![image](https://user-images.githubusercontent.com/95845810/165514782-69023a5e-63ba-4f81-838d-25d82d547fec.png)

**Comment by Moult** [comment]
@Takieddinex have you got a file to share? By the way you can inspect coordinates, georeferencing, and autodetect offsets using the BlenderBIM Add-on (https://blenderbim.org) that might help debug. IfcPatch also contains a few recipes to adjust coordinates, like OffsetObjectPlacements or ResetAbsoluteCoordinates.

**Comment by Takieddinex** [comment]
I have never used belender, but yes I can share the file with you. 
I get the file in ifc and convert it with ifcConvert to glb and then do the web visualization. 

https://filesender.renater.fr/?s=download&token=bd7ab855-24cd-4964-8cf0-b26c4a1f5118

**Comment by Takieddinex** [comment]
I think I misunderstood your answer? do you mean that I have a file to share or do you want me to share it with you? 
Sorry I'm a beginner

**Comment by Amoki** [comment]
@Moult and @aothms are right, your model has big coordinates (`aabb =  [ 1028630.3125, -2.0999999046325684, -6868575, 1028794, -0.5, -6868418 ]`).
The problem is not in IfcConvert, which converts correctly the file, but in the glb viewer you're using which does not support high precision/float64 values.

**Comment by Moult** [comment]
Sorry for the delay indeed your coordinates are large, which is fairly typical of civil style models. Nothing wrong with that and especially in IFC2X3 options are limited. However if you want to you can create a false origin so that your glb viewer can handle it.

Let's say we create a false origin at eastings and northings of 1028650,6868420,0, you can use the "ResetAbsoluteCoordinates" IfcPatch recipe to offset your coordinates:

![2022-05-02-103655_498x167_scrot](https://user-images.githubusercontent.com/88302/166171624-c869cb37-9cf9-402e-9e43-88bfcf8e2b3d.png)

For your convenience I've included your patched file here:

[psr-patched.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8600049/psr-patched.ifc.txt)

Note to self: I really need to create a new IFC patch with the improved BlenderBIM Add-on import capabilities that can handle models that have a combination of both cartesian point offsets and object placement offsets.

**Comment by Moult** [comment]
Some further reading on georeferencing that might interest you: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/docs/blenderbim/georeferencing.rst in particular the strategy of a false origin used when displaying in Blender will be the same technique you will need to use in your GLB viewer, or any other viewer not designed for large coordinates.

**Comment by Takieddinex** [comment]
I would like to thank you for all your answers !! :)
