### ISSUE TITLE
BB: have contexts available under IFC attributes

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2174]
Intuitively it seems like contexts should be down here, as well. 

![image](https://user-images.githubusercontent.com/507113/165788518-caf49fdc-3749-410e-87b0-686211285ddd.png)

**Comment by Moult** [comment]
No, the context is not an attribute, so it shouldn't belong there. The context is the category of the geometry being added. So when you first create an object with geometry, this is the context it uses. Later on you can find the contexts under the IFC Geometry panel.

But you're right it shouldn't be in the reassign dialog since reassigning only affects classes not geometry.
