### ISSUE TITLE
Import/Export BlenderBIM can't install

### ISSUE THREAD

**Issue by fjdr** [IfcOpenShell/IfcOpenShell#2191]
Hello:

I tried several times to activate the plugin BlenderBIM giving only errors.

Please there are some successfully installed and working?

I use MacOS 12.4 Monterrey and Blender 3.1.2

<img width="673" alt="Screen Shot 2022-05-05 at 09 11 31" src="https://user-images.githubusercontent.com/20794545/166934109-a94e9cf3-a2ac-4c55-b3a8-213249b65c7c.png">

<img width="720" alt="Screen Shot 2022-05-05 at 09 16 33" src="https://user-images.githubusercontent.com/20794545/166934138-18ad6abc-52ee-4643-a5d5-089df962aa28.png">

**Comment by Moult** [comment]
Is this a Mac with an ARM chip? If so you're out of luck we don't use provide packages for that. I'm not quite sure what's involved to make it happen, either money for a mac machine or time or both :(

Otherwise, if it's not ARM, download a py310 version from here: https://github.com/IfcOpenShell/IfcOpenShell/releases
