### ISSUE TITLE
Is it possible to create IfcFlowFitting parts with IfcOpenShell-Python?

### ISSUE THREAD

**Issue by CrossStyle** [IfcOpenShell/IfcOpenShell#2192]
Hello! I am going to create some IfcFlowFitting parts (such as u, y and t fittings as shown below) by specifying some parameters. My idea is to use FreeCAD or Python-OCC to create a 3D mesh and then pass this mesh to IfcOpenShell to build IfcFlowFitting. I didn't consider using Revit because I wanted the process to be automated.

Is this possible? If not, can you tell me other solutions? Thank you!

![U-shape](https://user-images.githubusercontent.com/43562257/167232825-2bc4c3cb-ee03-4b28-b5b8-404537c92645.png)
![Y-shape](https://user-images.githubusercontent.com/43562257/167232826-0dd1c2e1-7c82-461a-993e-765fd3a1a066.png)
![T-shape](https://user-images.githubusercontent.com/43562257/167232823-99914dea-418a-4bb7-a89b-81ac8eb54bb4.png)

**Comment by Moult** [comment]
I'm not aware of code which generates these fittings in pure OpenCascade accessible via the IfcOpenShell-Python lib but it's on the todo list to build such a geometry generator in Blender if that interests you. See also #2181 which establishes local axes conventions (e.g. +X points in direction of bend for elbows) that helps automatically insert fittings into generated duct/pipe runs.

Also, are you aware that IFC has psets available to store the fitting parameters? Such as the angles of the various fitting connection points? I had a look and it's not quite 100% enough to generate a fitting from scratch, but pretty close. You also have to read it in conjunction with the flow segment type's pset for its shape (e.g. rectangular / circular / oval) and shape dimensions (the pset has stuff like width / height).

**Comment by CrossStyle** [comment]
@Moult Thanks for your answer. If I manage to generate a mesh of a flow fitting, is there a way to convert the mesh to IfcFitting instead of creating the representation of flow fitting from scratch?

**Comment by Moult** [comment]
If you use Blender's mesh objects, yes. Otherwise, no. That's where the API comes in, right now the API handles Blender as a "geometry object model" for the functions like add_representation, but ideally we want to support more geometry models, like if you used trimesh, or opencascade, etc.

How were you planning to create the mesh data? Perhaps now is the time to build that API.

**Comment by aothms** [comment]
Some quick pointers if you end up using (python) opencascade.

Your first image is a revolution of circle. So you'd use Geom_Circle BRepBuilderAPI_MakeFace BRepPrimAPI_MakeRevolution

The second ones are unions of extrusions, so circle and face is the same but then BRepPrimAPI_MakePrism and BRepAlgoAPI_Fuse

Once you have a python occ shape you can use ifcopenshell.geom.tesselate to create a IfcProductDefinitionShape. Or use ifcopenshell.geom.serialize on IFC4 for advanced brep.

Instead of using OpenCASCADE to do the calculation you can also build the shapes using IFC constructs directly and depend on the viewer to construct the appearance. IfcCircleProfileDef IfcRevolvedAreaSolid IfcExtrudedAreaSolid IfcBooleanResult

**Comment by CrossStyle** [comment]
@aothms Thank you for the suggestions. I can now create these fittings.
