### ISSUE TITLE
Boolean operations create_shape

### ISSUE THREAD

**Issue by agonzalezesteve** [IfcOpenShell/IfcOpenShell#2202]
I tried using create_shape for an IfcBuildingElement with IfcBooleanResult in an IFC with DesignTransferView, but the boolean operations are not applied.

```
settings = ifcopenshell.geom.settings()
settings.set(settings.USE_BREP_DATA, True)
settings.set(settings.SEW_SHELLS, True)
settings.set(settings.USE_WORLD_COORDS, True)
settings.set(settings.DISABLE_OPENING_SUBTRACTIONS, True)

shape = ifcopenshell.geom.create_shape(settings, product)
```
![topologicBoolean](https://user-images.githubusercontent.com/38532229/168585861-a015c316-b615-49a0-8513-0bde6d297ec2.png)

I also tried importing it in Blender with BlenderBIM, but the boolean operations are not applied neither.

![blenderBoolean](https://user-images.githubusercontent.com/38532229/168586056-cdb71fb7-3539-44bc-b44b-e72883df500b.png)

Here you have the IFC file:
[muroDTV_parametrico.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8699734/muroDTV_parametrico.txt)

**Comment by aothms** [comment]
There was an issue with the handling of the compound originating from the composite profile. They cause self intersections in the boolean result, so the individual parts of the compound are to be booleaned separately with the results merged back into a compound. Somehow this wasn't detected properly in this case because there was an additional layer of compound (compound of compound of solid). This is now handled properly.

**Comment by Moult** [comment]
Closing as fixed :)
