### ISSUE TITLE
Incorrect geometry with boolean and opening using v0.7.0

### ISSUE THREAD

**Issue by andy-5** [IfcOpenShell/IfcOpenShell#2218]
I recently updated to IfcOpenShell 0.7.0 and, in one of our projects, I noticed an element where the extracted geometry was not right.

Attached is a minimal example extracted from that project to demonstrate the error: 
[incorrect-geometry.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8802625/incorrect-geometry.ifc.zip)

### Correct/desired output (using v0.6.0)

Extracting the geometry with `IfcConvert` v0.6.0 by running
```
IfcConvert.exe incorrect-geometry.ifc correct.glb
```
produces the correct geometry:

![Correct result using v0.6.0](https://user-images.githubusercontent.com/2477826/171110732-44dd4f89-9b6a-48e1-afa4-b30ef75ed6d3.png)

### Incorrect output (v0.7.0)

But using `IfcConvert` v0.7.0 results in wrong geometry.

```
> IfcConvert.exe --version
IfcOpenShell IfcConvert v0.7.0-1b1fd1e6 (OCC 7.5.3)
```
```
IfcConvert.exe incorrect-geometry.ifc wrong.glb
```
![Wrong result using v0.7.0](https://user-images.githubusercontent.com/2477826/171112679-d104378b-537a-439f-84eb-dc06bd0ee29d.png)

Part of the problem seems to be the opening. If the last line in the example file
```
#108408= IFCRELVOIDSELEMENT('3T7cf5qORnRpXpcRyqyf$s',#12,$,$,#108345,#108405);
```
is removed, the generated geometry is *almost* correct (but of course without the opening):

![Geometry without opening](https://user-images.githubusercontent.com/2477826/171113609-9f810327-f570-4afe-81f5-907cdfdf6216.png)

But interestingly, using v0.7.0 there is some *border* geometry in the upper-left part (only slightly visible in the image above), that should be cut away. Using v0.6.0 results in a clean mesh, without any superfluous geometry along the border.
So I guess the problem is actually the boolean operation to cut away part of the wall, the opening just makes the wrong result more visible.

I also tried importing the example IFC with the latest BlenderBim Addon (blenderbim-220529-py310), which resulted in the same problems as described above.

**Comment by aothms** [comment]
Indeed, in v0.7 the boolean operation code has been rewritten to process boolean subtractions in 2d when possible. When the 2d faces do not overlap we just use the occt face builder to construct a face with inner bounds. When the 2d faces do overlap we perform the boolean operation in 2d and then extrude back into a 3d volume. This can be done only when all operands are extrusions in the same direction and the openings create a through hole.

The cause of the issue here was that the face of the first subtraction (the triangular one) was not precisely co-planar. This caused issues with the intersection detection. Causing the face to be processed as an interior bound (hence the border geometry, thanks for the tip). So for now I simply reduced the tolerance for co-planarity.

One issue though is that the co-planarity check is an angular tolerance, and this is a pretty large face, so small angular deviation result in larger linear deviation at the edges. The edge-edge intersection is using linear tolerance. It'd be better to use linear tolerance also in the first case to make this invariant of face dimension.

**Comment by andy-5** [comment]
I tried your change with the latest [build v0.7.0-e508fb4](https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-31-v0.7.0-e508fb4-win64.zip) and can confirm that it works now as expected (at least for this case).

Many thanks for the quick fix!
