### ISSUE TITLE
Create IFC from external OCCT data

### ISSUE THREAD

**Issue by Vilo176** [IfcOpenShell/IfcOpenShell#2238]
Hi friends,

I'm trying to create an IFC file with Python IOS, and all the geometry is coming from an external process that produces OCCT 7.6 BREP files.
IFC objects creation is OK.
What I need now, is a way to inject the TopoDS_Shape into IOS.

I know IOS is optionally using OCCT as a geometry kernel, when reading IFC data, to produce TopoDS_Shape, that can then be retrieved with `shape.geometry.brep_data`

Is it possible to do the opposite ?
Give IOS a string containing a BREP serialized OCCT shape, and have IOS automatically create an IfcShapeRepresentation ?

Here and there I've seen people talking about `ifcopenshell.geom.serialize()`, but I cannot figure out where this function is.
Moreover, it seams that this function is partially linked to PythonOCC.
PythonOCC is only on OCCT 7.5, and BREP file format has changed with 7.6, which is the version I'm using IOS with.

In the meantime, I'm wondering why IOS needs PythonOCC to read a BREP with the above function, whereas it is perfectly capable of producing a BREP without PythonOCC inside the geom.iterator ?

Thanks a lot !

**Comment by aothms** [comment]
> it seams that this function is partially linked to PythonOCC.

> In the meantime, I'm wondering why IOS needs PythonOCC to read a BREP with the above function, whereas it is perfectly capable of producing a BREP without PythonOCC inside the geom.iterator ?

It doesn't, it's just typically used side by side, because otherwise we're dealing with just string serializations and they're a bit of a black box.

When you feed serialise()/tesselate() a PythonOCC shape, it will serialize to string first and then pass it to ifcopsnehll, because IfcOpenShell and PythonOCC do never talk directly to each other anyway.

> but I cannot figure out where this function is.

It seems we're using british spelling here:

~~~py
>>> import ifcopenshell, ifcopenshell.geom
>>> ifcopenshell.geom.serialise
<function make_shape_function.<locals>._ at 0x000001E746C2E310>
>>> ifcopenshell.geom.tesselate
<function make_shape_function.<locals>._ at 0x000001E746C2E430>
~~~

**Comment by Vilo176** [comment]
Thanks Thomas !
