### ISSUE TITLE
IfcConvert can't properly convert IfcOpenHouse.ifc to IfcOpenHouse.obj

### ISSUE THREAD

**Issue by FragColor** [IfcOpenShell/IfcOpenShell#224]
Hello,

Today I've been playing with IfcConvert and I haven't been able to properly convert IfcOpenHouse to an obj file. In fact, some transformations aren't considered : the two part of the roof are at the same place and its the same for some other parts such as some walls. However, it works well with other geometric exports I've tested (STEP and IGES).

It doesn't work with the latest commit on master, nor with the official latest build 0.5.0-preview2 on linux, windows or osx.

**Comment by Stinkfist0** [comment]
Seems perfectly fine for me (simply `IfcConvert.exe IfcOpenHouse.ifc` and opening up IfcOpenHouse.obj in a viewer application), although I must double-check with the very latest code:
![image](https://cloud.githubusercontent.com/assets/227876/26591454/645dc44e-4566-11e7-9655-668a73b89438.png)

**Comment by FragColor** [comment]
I've done an investigation in order to understand the problem.

First of all, I've generated a new `IfcOpenHouse.ifc` from master. It doesn't work but its another story/issue. So, I've generated a new `IfcOpenHouse.ifc` from the commit before the last one. I have to admit you are right, it works and I have the same rendering as yours !

Then, I've compared my previous `IfcOpenHouse.ifc` and the new generated one and there is two things I can say :
- my file is an old one (from 2012) according to what is written in the file,
- it still doesn't work with `obj`, but works well with `iges` and `step` and it is well considered by IFC viewers such as Solibri.

It may seem useless to find out what happens with this file but on the other hand what causes that issue could be found in other models.

You can get my file here : [https://uploadfiles.io/9rjh5](https://uploadfiles.io/9rjh5)

**Comment by aothms** [comment]
> It may seem useless to find out what happens with this file but on the other hand what causes that issue could be found in other models.

That turned out to be quite right

> First of all, I've generated a new IfcOpenHouse.ifc from master. It doesn't work but its another story/issue.

That appears to be right, there were still some `boost::none`s around after d7c275e941d8f7c15e8a58eaa82aaaac7d622513. I am not going to commit this, because it would conflict with #190 which will be merged soon. For reference there is a patch below that can be applied to d7c275e941d8f7c15e8a58eaa82aaaac7d622513.

Interestingly there was something wrong with the way reuse of geometry was determined 1704862d0d467634b673710b56fc4cfae985d75a

I have also now included the generation at least of IfcOpenHouse on Travis, as it covers the write functionality pretty well 1751cf1c95b3d72ca7ee5cfa0fea48198c0c2f62

Then there is still one issue remaining with Collada files, created #225 for that.

~~~diff
diff --git a/src/ifcparse/IfcWrite.cpp b/src/ifcparse/IfcWrite.cpp
index 1fcc97b..af30bc1 100644
--- a/src/ifcparse/IfcWrite.cpp
+++ b/src/ifcparse/IfcWrite.cpp
@@ -141,7 +141,7 @@ template <typename T> void IfcWritableEntity::_setArgument(int i, const T& t) {
 }

 void IfcWritableEntity::setArgument(int i) {
-       _setArgument(i, boost::none);
+       _setArgument(i, boost::blank());
 }

 void IfcWritableEntity::setArgument(int i, Argument* a, IfcUtil::ArgumentType attr_type) {
@@ -263,21 +263,21 @@ void IfcWritableEntity::setArgument(int i,IfcUtil::IfcBaseClass* v){
        if ( v ) {
                _setArgument(i, v);
        } else {
-               _setArgument(i, boost::none);
+               _setArgument(i, boost::blank());
        }
 }
 void IfcWritableEntity::setArgument(int i,IfcEntityList::ptr v){
        if ( v.get() ) {
                _setArgument(i, v);
        } else {
-               _setArgument(i, boost::none);
+               _setArgument(i, boost::blank());
        }
 }
 void IfcWritableEntity::setArgument(int i,IfcEntityListList::ptr v){
        if ( v.get() ) {
                _setArgument(i, v);
        } else {
-               _setArgument(i, boost::none);
+               _setArgument(i, boost::blank());
        }
 }
 void IfcWritableEntity::setArgument(int i,const std::vector<double>& v){

~~~
