### ISSUE TITLE
PsetTemplate search shows ID instead of Name

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2257]
![image](https://user-images.githubusercontent.com/83825269/177111816-58edef94-3fda-43c4-ae70-506106a4264b.png)

**Comment by Gorgious56** [comment]
Yeah that's one bug I noticed and I am looking for a good solution. Unfortunately since the displayed name must be exactly the same as the identifier of the `EnumProperty`, in the case where they are not the same it becomes ugly. 

I think I have to pass it through another dummy property that will translate between the two. 

Thanks for the feedback !

**Comment by Gorgious56** [comment]
what whaaaat
![capture](https://user-images.githubusercontent.com/25156105/177216787-ad6abe8d-13e7-4ff5-a99b-d88036403012.gif)

It's a bit hacky but it works like that so good enuff for me ><
 
Cheers
