### ISSUE TITLE
Duplicate code for adding/removing collection properties

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#2259]
I've noticed (and i've personally contributed to a lot of this 🤦‍♂️) that there is a lot of duplicate code related to adding/removing collection properties.  This issue serves as a reminder to address this !

**Comment by Gorgious56** [comment]
Hey could you add a link to an example of the problem ? I'd like to take a look too :)

**Comment by vulevukusej** [comment]
Here's just one example:  https://github.com/IfcOpenShell/IfcOpenShell/blob/87f110bae50f2bbbbda4867d1a5493c5fcc5597b/src/blenderbim/blenderbim/bim/operator.py#L410-L428

I think the easiest solution is to create a single operator, with something like the collection path defined as an attribute.  What do you think? Something like this: 
class AddOrRemoveCollectionItem(bpy.types.Operator):
    bl_idname = "bim.add_new_col_item"
    bl_label = "Add new collection item"
    bl_options = {"REGISTER", "UNDO"}
    collection = bpy.props.StringProperty()
    add_or_remove = bpy.props.StringProperty()

    def execute(self, context):
        getattr( getattr(context, self.collection), self.option)()
        return {"FINISHED"}

**Comment by Gorgious56** [comment]
Alright I understand. I think it would be a great opportunity to reduce code overhead.
Would be nice to add a way to add properties to new items, sometimes default values or a default name are provided by the operator. It's not straightfoward to pass arbitrary values to an operator though. You can pass blender properties with [layout.context_pointer_set](https://docs.blender.org/api/current/bpy.types.UILayout.html?highlight=context_pointer_set#bpy.types.UILayout.context_pointer_set) but not plain python types.

One thing to keep in mind is that although this would decrease the overall code duplication it may increase the dependencies between the different modules and it might be a little bit less clear where these features are defined in code. But since they're really simple atomic operations I don't think it should be a problem.

Could be nice to also have an option to `clear` the collection in the operator parameters.

Actually I think it would be cleaner to define 3 base operators, `bim.collection_add`, `bim.collection_remove`, `bim.collection_clear` because although that will be a bit of overhead the actual `execute` code will be simpler.

```
class BIM_OT_collection_add(bpy.types.Operator):
    bl_idname = "bim.collection_add"
    bl_label = "Add new collection item"
    bl_options = {"REGISTER", "UNDO"}
    name: bpy.props.StringProperty()

    def execute(self, context):
        new = context.bim_collection.add()
        if self.name:
            new.name = self.name
        return {"FINISHED"}
```

and in the `draw` method of the panel :
```
layout.context_pointer_set(name="bim_collection", data=props.collection)
op = layout.operator("bim.collection_add")
op.name = "Default Name"
op = layout.operator("bim.collection_remove")
op.index = 2
layout.operator("bim.collection_clear")
```

Just a little bit more than my 2 cents ;)

Cheers

**Comment by vulevukusej** [comment]
Always a pleasure mate 😉

**Comment by vulevukusej** [comment]
@Gorgious56 oooh just noticed something i've never seen before:  "context_pointer_set" - This looks interesting :)

**Comment by Moult** [comment]
I think over time there will be more specific domain logic to be added and the benefit from a generic operator will decrease, so not 100% convinced here.
