### ISSUE TITLE
IfcOpenShell python on PyPi

### ISSUE THREAD

**Issue by YaroslavKormushyn** [IfcOpenShell/IfcOpenShell#2269]
Hello!

I have a couple of questions regarding the PyPi package of IfcOpenShell.
1. Who is the maintainer of the `python-ifcopenshell` package on [PyPi](https://pypi.org/project/python-ifcopenshell/#description)? Is this the repo of the maintainer?
2. I see that the conda package in `conda-forge` and `python-ifcopenshell` package in PyPi lack some modules (missing `api` and `mvd` folders) when comparing with the official .zip file [here](http://ifcopenshell.org/python). I'm comparing the 0.6.0 version since this is the version published to these package indexes. Why is that? Where can I get the build scripts for these packages (preferably for PyPi) to build them myself?
3. I've seen a couple of issues with proposals for CI builds for PyPi and conda here: #1356, #935, and #1666. Are there any updates on that? If there aren't any, how could one help with the PyPi package?

**Comment by aothms** [comment]
1. I don't know.
2. Missing API maybe because of date (v0.6 has been around for a while, at some point in which api/ was introduced). Missing MVD is probably because it's a submodule or because the CMake python install script was updated at some point to include it?
3. The latest activity re conda is here https://github.com/conda-forge/ifcopenshell-feedstock/pull/20

So, we have build scripts in the nix/ and win/ folders. There is also some automation (which provides the somewhat automated builds like https://github.com/IfcOpenBot/IfcOpenShell/commit/e44e03f02e1cf948ad452866da44ba9757d5703b#comments) https://github.com/IfcOpenShell/IfcOpenBot

What would you propose? The conda approach with reused dependencies works well in theory, in practice there seems to be easily unresolvable conflicts. So perhaps on PyPi an alternative can be provided that is all statically linked (by default the win/ and nix/ build result in self contained statically linked archives).

I think the easiest would be if https://github.com/IfcOpenShell/IfcOpenBot is updated to push to PyPi. That'd guarantee that it remains somewhat up to date. I don't have any knowledge on how to interact with PyPi so any help on that front is appreciated.

**Comment by fedelaport** [comment]
If somebody is interested, we are hosting am ifcopenshell 0.7.0 pip installable public package.

`pip install https://woodwall-public.s3.eu-central-1.amazonaws.com/ifcopenshell.zip`

**Comment by Moult** [comment]
Closing as resolved :) See #2132 #2293
