### ISSUE TITLE
Optimisation strategies for applicability in IDS

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2279]
I started with a brute force `for element in ifc: if applicable: then check requirement`. However as expected `for element in ifc` is a very, very slow way of doing things proportional to filesize. For example, a 13MB IFC took 23 seconds to process for say 20 specs.

I'm lucky that all my specs have an entity facet with a simple string as one of its applicability. As a result, that can by used to do ifc.by_type(entity.name, include_subtypes=False). This cuts down the 23 seconds to 0.005 or something more sensible :) Right now the IDS code is heavily modified on my local machine only and this works well for my needs but I want to clean it up and commit and part of that means I want to optimise some other scenarios too.

I want to make sure I was doing the best strategy to filter down elements as efficiently as possible. So a few questions :)

 1. If I have an applicable entity facet, I can do ifc.by_type(name, include_subtypes=False), but what if I have 2 entity facets? Can I do elements.by_type(?) somehow? I guess I can profile the difference between doing ifc.by_type() twice and then doing the set intersection, vs looping through the results of the first entity facet and manually checking is_a() == name for the second entity facet. Thoughts?
 2. If the entity name is a restriction, then I can't do by_type() immediately. Instead, I can do ifc.wrapped_data.types() and filter those, then with the results do ifc.by_type(). However, again if I have a second entity facet, then I have to see the tradeoff between doing a set intersection or merely looping through the results of the first entity facet.
 3. I've written code to prioritise applicable entity facets before performing other applicability facets. I assume this is a smart approach.
 4. Another common scenario is to use classification facets as applicability instead of entities. In this case, I should detect this and build a map between classification systems/references and elements as appropriate, then that would give me something like by_system().by_reference() or whatever. Or is there a smarter approach?
 5. Similarly for materials I can build an element->material map (by using my ifcopenshell.util.element.get_elements_by_material()) if necessary. Alternatively I can just do a very cheap but broad filter of by_type() by anything that can have a material (which would eliminate all the boring unrooted classes)
 6. For attributes, I could probably build a map of of schema declarations and their types, maybe shipped as a JSON with the IDS module.
 7. For property, I haven't got any code right now which builds a map from property back to element, but I guess I can do a very broad by_type() filter for anything that can have properties/quantities assigned which would exclude boring unrooted classes.
 8. For partof, dunno, haven't thought it about it much since it's still not yet stable in the spec.

Thoughts? Are my approaches sound? Have I missed any tricks?

**Comment by aothms** [comment]
* How can the set intersection between two entity facets ever return something interesting? Isn't it always the case that the result is equal to the one of the facet outcomes or empty set?
* Regardless of that, set intersection in python would probably be a little bit quicker because you don't have to do string comparison. ifcopenshell.entity_instance can be used directly in python sets and dicts as they have __hash__ and __eq__ defined (they don't take into account attribute values just identity of the instance)
* I think that's clever. Do the pattern on a set of type strings in the file and use that to lookup entity instances!
* I think the priority is natural also in the file, because it's a xs:sequence?
* Nothing for properties or classifications is natively indexed in ifcopenshell. Not sure the map is necessary. Looping over all classification instances would be fairly minimal compared to the total number of instances. But I guess you could wrap it in a function and cache that.
* I guess. If you look at the things that can have materials it's actually retrained a lot more than just ifcroot http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcRelAssociatesMaterial.htm#5.4.3.46.4-Formal-propositions
* > For attributes, I could probably build a map of of schema declarations and their types
  Don't we have this baked in already, what else do you need?
* "exclude boring unrooted classes" excluding IfcMaterialDefinition and IfcProfileDef. We should not forget to have tests for this and have this properly written out in the docs.

**Comment by Moult** [comment]
> How can the set intersection between two entity facets ever return something interesting? 

Agreed that in sensible scenarios, it doesn't make sense at all to use two entity facets. However, there is a chance the user can create two entity facets in the applicability.

> But I guess you could wrap it in a function and cache that.

Yes an lru_cache on a function that loops through references / systems would probably be sufficient, you're right.

> Attributes map ... Don't we have this baked in already, what else do you need?

I assumed (perhaps a wrong assumption?) that looping through schema_by_name('ifc4').declarations() if declaration is entity, then loop all_attributes() and get attribute.name() is slow, and that it would be faster to do preprocess a JSON dict of attribute name -> entities names that can be looked up. Or is there another method that lets me look up attribute names --> entity types faster?

> exclude boring unrooted classes

Ah yes sorry I was wrong, I intended to mean filtering out the majority of unrooted classes except for those two :) (minor side rant: they probably should be rooted, eh?)

**Comment by aothms** [comment]
> slow, and that it would be faster to do preprocess a JSON 

But we already do something similar at module init. So I think it'd just be a matter of getting the data you need at this step.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/entity_instance.py#L56

> Or is there another method that lets me look up attribute names --> entity types faster?

I must say though, that I find that this use case creates unnecessary complexity (if you want to do it efficiently). Maybe we should change the spec to either require `{entity_name}.{attribute_name}` kind of attributes, or that we somehow don't allow attribute facet to be the most dominant applicability. But this is more or less the case anyway as the entity facet has minOccurs 1. Maybe we don't have to worry too much about the performance of the attribute in the applicability.

**Comment by Moult** [comment]
> So I think it'd just be a matter of getting the data you need at this step.

That step seems to go from entity --> attribute whereas I'm looking to do the reverse, attribute --> entity.

> But this is more or less the case anyway as the entity facet has minOccurs 1.

https://github.com/buildingSMART/IDS/blob/master/Development/0.6/ids_06.xsd#L61 entity facet is optional, so a user can use attributes as their applicability. One example would be to use two applicabilities 1 being classification (all Uniclass doors) and another being the attribute Name.

But yes, sensibly we'd _assume_ that there would always be another facet (typically entity or classification) that filters things down first.

**Comment by aothms** [comment]
>That step seems to go from entity --> attribute whereas I'm looking to do the reverse, attribute --> entity.

Ok, I was just suggesting to just sneak that code in there instead of more json fragments in the source tree,

> entity facet is optional

Ok that changed then..

> But yes, sensibly we'd assume that there would always be another facet (typically entity or classification) that filters things down first.

Yes, it seems to me as something we don't have to worry much about in terms of performance. If it turns out that in rare cases the attribute facet does become the most restrictive facet in terms of applicability we can address the performance consequences then.

**Comment by Moult** [comment]
Closing as runs seem to be acceptably optimal for now using these strategies.
