### ISSUE TITLE
Update IfcOpenShell version on pypi

### ISSUE THREAD

**Issue by alfiejfs** [IfcOpenShell/IfcOpenShell#2293]
The latest version is still currently 3.9, 3.10 would be ideal - https://pypi.org/project/python-ifcopenshell/

Not sure if this is maintained here - someone please let me know with what I could do or potentially alternate solutions. Thanks!

**Comment by aothms** [comment]
I think this is why anaconda is a bit more favoured by the python projects that wrap large C++ code bases. With the conda-forge build automation this is much more automatic.

See https://github.com/IfcOpenShell/IfcOpenShell/issues/2269#issuecomment-1176244965

**Comment by alfiejfs** [comment]
@aothms the version they are hosting is not compatible with Python 3.10. This isn't much use for us unfortunately!

**Comment by Moult** [comment]
I cobbled something together so that at least now there is something on PyPi. It may have issues (first time learning how Pypi works), and in the future should probably merge with the Conda build process, but it's a start and perfect is the enemy of the "OK" :)

Can you try this and see if it works? https://pypi.org/project/ifcopenshell-python/

I tried making the package named `ifcopenshell` but apparently the name was rejected. I've filed an issue [here](https://github.com/pypa/pypi-support/issues/2197).

**Comment by Moult** [comment]
Closing unless the PyPI build is reported as faulty :)
