### ISSUE TITLE
BB Object Property related: Wrong Pset Preselection / Psets awailable that dont exist in IFC Schema

### ISSUE THREAD

**Issue by frisoBUW** [IfcOpenShell/IfcOpenShell#2310]
**How the Problem occurs:**

1. Navigate to "Object Properties"
2. Assign Class (for example IfcWall) to Element
3. When adding Psets under "IFC Object Property Sets" there are some Suggestions, which arent related to the assigned IFC class

**Picture:**

- The yellow Psets are from other IFC Entities and dont apply to IfcWall for example
- The red Psets dont exist according to the IFC 4 Documentation

![image](https://user-images.githubusercontent.com/96592011/180422824-e81e8ed9-784d-447c-b8c1-8ac86d57b2db.png)

**Comment by Moult** [comment]
This is actually a bug in IFC itself. I need to patch the pset templates to fix this. I hope this type of stuff has been fixed for IFC4.3.

**Comment by Moult** [comment]
I was hesitant to fix this since it's technically upstream's responsibility, but I don't know how or when they're going to fix it so oh well.

BTW this is the upstream file that we use that has those issues: https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/annex/annex-a/general-usage/IFC4_ADD2.ifc

**Comment by frisoBUW** [comment]
Thank you Dion!
