### ISSUE TITLE
BCF - proposal to manipulate DOM instead of file I/O per operation to improve performance

### ISSUE THREAD

**Issue by sanzoghenzo** [IfcOpenShell/IfcOpenShell#2321]
I there a reason why the `BcfXml` class directly writes to/reads from disk instead of having an in-memory parser and writer?

In one of my tests I had to create many (~46k) topics - not something that we will (hopefully) encounter in production, but it still... - and I have very long running times (748seconds),  60% of it spent `open` ing files for writing the files.

I realized that the various methods of `BcfXml` are completely reliant on I/O operations, and I wonder why is it the case...

Wouldn't it be better if all the operations were made on the `minidom.Document` objects (or even better, using something like [`xsdata`](https://xsdata.readthedocs.io/en/latest/) to generate the dataclasses from the BCF XSD and using them), then dump the resulting XMLs into StringIO objects and feed them to the `ZipFile` object?

I will work on a I/O-less version the next week for my project; if I'll got it right, I'll be happy to provide a PR, if it's of any interest!

**Comment by sanzoghenzo** [comment]
I just finished implementing a MVP that works on my specific case, and the execution time is now 146 seconds!

The BCF creation went from 632 seconds to 94 seconds (bear in mind that these are measured with cprofile inside PyCharm, so there's some overhead).

My specific case is to generate topics for parameters validation (ie. check if required values are there and not empty or part of a list), so I only generate (many) Topics (one for each element +parameter pair) with a single viewpoint.
There are no other files/documents/comments.

Here's what I've done:

- replaced the `bcf.vX.data` classes with dataclasses automatically generated by `xsdata` using the various `xsd` files; the classes now need to be initialized with the required attributes;
- `BcfXml` holds the dataclasses and the `bytes` objects to be written in the BCF zip file;
- parsing and serializing is demanded to `xsdata`'s `XmlParser` and `XmlSerializer` (using a support class to hold the context and speedup the serialization process)
- `BfcXml` is split into various `Handler` classes for simpler topic, visinfo and document management (they are still tightly coupled, but I think I'm headed in the right direction)
- I only added `BcfXml.add_topic(title, description, author, type, status)` and `TopicHandler.add_viewpoint(ifc_element)` methods  other than the parsing/serializing methods, so it's definitely not a feature parity with the existing one.

Since this implementation would be a huge breaking change, I'm not sure if I should do a PR with it or just create a new library (with all the copyright notices in place, of course)!

If you think it should be merged: is there any (unit)test for the current implementation? I can't find any, and it would be useful to avoid regressions...

**Comment by aothms** [comment]
Thank you for taking the initiative on this. I'm not familiar with the BCF code base, for a more authorative answer I'll defer to @Moult.

I'd definitely prefer a PR over starting something new. There's enough fragmentation already and what your describing here is a very significant contribution.

In the other parts of the code base (IDS - information delivery specification, another XML based bSI standard under development) we've used xmlschema [0] instead of xsdata. It would make sense to quickly see if we can unify that, because they seem really comparable in aim.

[0] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifctester/ifctester/ids.py#L21

**Comment by Moult** [comment]
> I there a reason why the BcfXml class directly writes to/reads from disk instead of having an in-memory parser and writer?

No. It should be recoded to be in-memory (but maybe we shouldn't load _everything_ in memory, as otherwise that would make loading a BCF with 46k topics very slow), so maybe it should keep only changes in-memory, and just like email clients, just lightweight load the topic IDs in memory upon the first BCF load.

I 100% support your approach, and also think @aothms 's suggestion about xmlschema makes sense, but I don't know enough about either package to know if it's a drop in replacement or what the side effects will be, so happy for you to make the call.

> If you think it should be merged: is there any (unit)test for the current implementation? I can't find any, and it would be useful to avoid regressions...

Definitely should be merged. There is no value in a non-unit-tested, slow implementation when there is a better alternative :) Happy also to give you commit access and for you to "own" the BCF codebase rather than wait for us to do PRs :) The BCF code was written by students across a couple of GSoC years and so is better than zero support, but alas it now lacks proper ownership and is clearly in need of more mature direction.

**Comment by sanzoghenzo** [comment]
> No. It should be recoded to be in-memory (but maybe we shouldn't load everything in memory, as otherwise that would make loading a BCF with 46k topics very slow), so maybe it should keep only changes in-memory, and just like email clients, just lightweight load the topic IDs in memory upon the first BCF load.

Agreed. As of now, I load everything in memory to be able to get rid of the zipfile as soon as possible and make the classes "self-contained", but I can see that it's not the best way to handle this (especially if a BCFzip has many related documents/files/snapshots/snippets in it).
I'll try to figure out an elegant way to solve this!

> In the other parts of the code base (IDS - information delivery specification, another XML based bSI standard under development) we've used xmlschema [0] instead of xsdata. It would make sense to quickly see if we can unify that, because they seem really comparable in aim.

Well, I also have rewritten the IDS part using xsdata 😉 This is what I use to generate the validation errors to be written in the BCF file...
It's all still experimental, and also a massive breaking change (I didn't test it against `ifcbimtester`, and completely ignored that integration), so I didn't advertised it yet.

(by the way, as of now `ids`, is incorporated in `ifcopenshell-python`, but requires the `bcfclient` package, not listed in the dependencies... I think it should be split into a separate package just as bcf)

> Happy also to give you commit access and for you to "own" the BCF codebase rather than wait for us to do PRs :) The BCF code was written by students across a couple of GSoC years and so is better than zero support, but alas it now lacks proper ownership and is clearly in need of more mature direction.

Honestly, I don't know if I can commit on the ownership of the project... I have done this to solve a need arose in my own company (that is, create BCF files from IDS validation results), and I should quickly move on my next task...
I will try my best to provide a decent PR, let's discuss ownership later on 😉

**Comment by aothms** [comment]
> Well, I also have rewritten the IDS part using xsdata 

(Neither xsdata nor xmlschema are very authorative, but xmlschema has a bit more contributors. Essentially both are one person bands.)

I'm fine either way too.

**Comment by sanzoghenzo** [comment]
> > Well, I also have rewritten the IDS part using xsdata
> 
> (Neither xsdata nor xmlschema are very authorative, but xmlschema has a bit more contributors. Essentially both are one person bands.)
> 
> I'm fine either way too.

Well, I went with the `xsdata` route because it can automatically generate dataclasses from one or more XSD files, which can then be used to parse the XMLs and serialize the objects back to XML, no need for dicts manipulations (that make the majority f the current `bcfxml` implementation).

[All of this is because I now - after 7 years of python programming, and with an increase of C# programming over the last few years - tend to define my data into typed dataclasses, especially when the schema is well defined, so I can use static type checking and other analyzers on my code.]

Anyway, yesterday I took a quick look at the entire codebase to see what is needed to make this refactor work:

- `ifcopenshell.ids` and `ifctester`: this goes hand in hand with the IDS refactoring, after that the `BcfHandler` will be substituted with simpler method calls (the `emit` method is in fact already part of my bcf module, split into smaller functions).
- `ifcclash`: almost there, maybe we can transfer some `clasher.export_bcfxml()` logic into new `BcfXml` methods (viewpoint generation)
- `blenderbim`: essentaily all the bcf operator needs to be taken care of, since it accesses many objects/attributes. Also, the `BcfStore` could use global `XMLParser`, `XMLSerializer` and `XMLContext` (from `xsdata`) to cache the schema/dataclasses to use (with a huge performance boost).

Let's see if I can justify this as work related stuff with to my boss 😅

**Comment by Moult** [comment]
I should mention that ifcopenshell.ids has been moved to ifctester as part of a bunch of work I did to refactor it and separate formatting vs validation. I've removed the old code to prevent confusion.

Note it's not necessary to solve everything all at once. More than happy for xmlschema and xsdata to run side by side for a while. So don't feel pressured to fix everything :)

**Comment by Moult** [comment]
@sanzoghenzo bump :) how'd it go justifying to your boss? It would be super awesome to get your improvements merged :)

**Comment by sanzoghenzo** [comment]
Hi, these days I'm on holiday enjoying some paragliding 😉  the weather for tomorrow doesn't seem good, so I can focus on this task! I already forked the repo and started making changes a few days ago, also adding the "on demand" loading of files from the zip file.
 
One thing, though: is there a common build/dev environment for this repo that I can use to do the testing (and maybe automated CI)?

**Comment by Moult** [comment]
Cheers :) the bcf code has no tests, so there is no environment :) Github actions run for stuff that does have tests. I also tend to create a Makefile with phony targets just for convenience to run tests, such as https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/Makefile#L527-L551 or https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/Makefile#L1-L3

So if you set up some tests that can be run with pytest happy to add it to the Github actions.

**Comment by sanzoghenzo** [comment]
Thanks for the pointers!

May I ask you why you don't use virtualenv/[pipenv](https://pipenv.pypa.io/en/latest/)/[conda](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file)/[tox](https://tox.wiki/en/latest/) virtual environments or even [conda-lock](https://conda-incubator.github.io/conda-lock/) files to create them?

This should simplify the makefile (and make it almost universal for all the project, as long as they add the Pipfile/environment.yml/conda-lock file...

**Comment by Moult** [comment]
The BlenderBIM Add-on makefile had to pull from multiple sources, and at once point, it took packages from IfcOpenBot, which was not available on pip/conda, some packages which were available on pip but not conda, and some packages which were available on conda but not pip, some packages which also had some custom patches applied, as well as some random dylib/dlls I self-hosted. At the time, due to the early nature of the project and my unfamiliarity with Blender's rules on packaging things in a ZIP it was easier to just go direct to source.

Things have calmed down since and the majority of the download lines can be replaced with some pip commands (I think the cjio dep already does this), but it isn't a super high priority for me and there are still deps spread around pip/conda and custom patches.

Locally I use virtualenv of course and I assume others do the same.
