### ISSUE TITLE
IFCEXTRUDEDAREASOLID wrong Position

### ISSUE THREAD

**Issue by ninichki** [IfcOpenShell/IfcOpenShell#2332]
Hello,

In this case some IfcCovering has a wrong place. Here with ID: 3J2XeDAq14tANzHxSwtyxf
![image](https://user-images.githubusercontent.com/1086380/182605225-0fff1a7b-2779-4511-99d1-c8fde39d5a8c.png)

Solibri is showing it on the right position.

It's a model from Allplan.

I tested it with the latest v0.7.0. And OCCT 7.6.3

kind regards,

Christian
[Domus_ohne Sockelleiste.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9251166/Domus_ohne.Sockelleiste.zip)

**Comment by Moult** [comment]
In the attached IFC, your geometry is invalid because the extruded area is set to 0. If however I set that to 0.1 arbitrarily, then it seems to work as expected, tested with the latest IfcOpenBot release on the BlenderBIM Add-on:

![2022-08-22-163922_891x553_scrot](https://user-images.githubusercontent.com/88302/185855366-92f6ba21-bfa4-470c-be85-a8de7f04f0f9.png)

Can you try and recreate your issue with the latest version from https://github.com/IfcOpenBot/IfcOpenShell/commit/dc67287d4b083cabae39ee4f92fa93b6f74cae11#commitcomment-78799114 ? If not it seems to be fixed and we can close this.

**Comment by Moult** [comment]
Closing as fixed :)
