### ISSUE TITLE
BB: mirroring not registering

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2372]
video: https://www.dropbox.com/s/58tmuuaqlf0tijz/2022-09-01_14-25-33_Blender_blender.mp4?dl=0
blenderbim-220831-py310-win.zip

**Comment by Moult** [comment]
This is by design. The rule in IFC is that an occurrence of a type with geometry must have geometry that matches the type exactly.


So if you have a single object which you mirror, the mirror is applied. If you have multiple objects tied to a single type of which one is mirrored, there is a discrepancy, so the BlenderBIM Add-on "auto fixes" it.

**Comment by Moult** [comment]
The issue here is that mirroring geometry may mean that it is a completely different product, like asymmetrical furniture. I'm not sure what the right solution is, but the approach I'd take is to improve the specificity of mirroring tools for users, e.g. explicit mirroring (i.e. create a new product) or mirroring the position only but keeping the geometry the same, or mirroring = 180 degree rotation.
