### ISSUE TITLE
IfcConvert Export Types

### ISSUE THREAD

**Issue by gar-syn** [IfcOpenShell/IfcOpenShell#2386]
Is it possible to export property types like IfcAreaMeasure and IfcVolumeMeasure to XML? 

On testing these types are lost and become NominalValue

```text
#1561238= IFCPROPERTYSINGLEVALUE('Fl\X2\00E4\X0\che',$,IFCAREAMEASURE(2.02386393274),$);
#1561239= IFCPROPERTYSINGLEVALUE('Volumen',$,IFCVOLUMEMEASURE(0.146341),$);
```

**Comment by aothms** [comment]
Would this be something you'd like to work on?

The offending logic is here:

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/serializers/schema_dependent/XmlSerializer.cpp#L107-L110

Where we blindly take argument 0 from the NominalValue type instance, without doing anything with `f->declaration().name()` which would provide a string encoding of the simple type name.

Tricky bit is of course that it only returns a single value. So somehow it'd have to return two in order to provide NominalValue and NominalValueType here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/serializers/schema_dependent/XmlSerializer.cpp#L189-L190

(prefer to have it in a backwards compatible fashion by simply adding another xml attribute side by side)

**Comment by Moult** [comment]
@gar-syn is there a reason you closed this?
