### ISSUE TITLE
Improve the calculus of all qtos

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#2401]
This is not an issue but a feature request.

The goal is to improve the calculus of all qtos so i start to list all of them.
This is extracted from IFC 4x3 schema [here](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/listing-references.html)

All qtos quantities:

- GrossWeight
- Width
- Perimeter
- GrossArea
- NetArea
- GrossVolume
- NetVolume
- NetWeight
- Height
- Depth
- Area
- Volume
- Length
- CrossSectionArea
- OuterSurfaceArea
- GrossSurfaceArea
- GrossCrossSectionArea
- NetCrossSectionArea
- Thickness
- Weight
- EavesHeight
- FootPrintArea
- GrossFloorArea
- NetFloorArea
- SignArea
- UsageTime
- OperatingTime
- NumberOfGangs
- PlanLength
- GrossPerimeter
- ProjectedArea
- CompactedVolume
- LooseVolume
- InnerDiameter
- OuterDiameter
- GrossSideArea
- NetSideArea
- TotalSurfaceArea
- GrossHeight
- NetHeight
- NumberOfCircuits
- NetSurfaceArea
- UndisturbedVolume
- GrossFootPrintArea
- NetFootPrintArea
- Diameter
- FinishCeilingHeight
- FinishFloorHeight
- NetPerimeter
- GrossWallArea
- NetWallArea
- GrossCeilingArea
- NetCeilingArea
- SurfaceGenusBeforeFeatures
- SurfaceGenusAfterFeatures
- Mass
- PlanArea
- Count
- StandardWork
- OvertimeWork

**Comment by aothms** [comment]
Just a reminder that IfcopenShell C++ has a bunch of tools to calculate also (projected) areas https://ifcopenshell.github.io/docs/rst_files/class_ifc_geom_1_1_representation_1_1_b_rep.html#_CPPv4NK7IfcGeom14Representation4BRep32calculate_projected_surface_areaERK6gp_Ax3RdRdRd

Since you don't deal with facetations in OCCT, most of these things are slightly easier to calculate. Inner bounds are easily discarded for example to calculate the difference between gross and net (although maybe not every window opening is an inner bound really...)

In case of curved elements, calculating in OCCT will be a bit more accurate.

**Comment by Moult** [comment]
I guess this is relevant to #1040 as right now Python doesn't seem to have access to would be pretty sweet C++ functions.

Were you planning on developing some heuristics for some of these? Keep in mind that some are special, like surface area of a beam (or presumably generically any extruded profile set?) excludes the ends, whereas surface area of a slab doesn't.

**Comment by vulevukusej** [comment]
I'm also keen to see what is available through python - at the moment I'm working on expanding @Moult's QTOs using external libraries, I'll set up a draft PR today..

**Comment by aothms** [comment]
What I hope to do is provide a really light weight interface to occt from python through ifcopenshell, like for a shell you'd just get a list of faces with some properties (like bounds, orientation and area). But feel free to get started of course in python 👍
