### ISSUE TITLE
Is there an efficient way to reassign class?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2408]
I currently use this method https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/schema.py#L51-L66 to reassign a class, e.g. from an IfcWall to an IfcSlab. It involves creating a new entity, copying attributes as best it can, swapping all inverse references from the old to the new entity, then removing the old entity.

It's a lot of steps, and I'm running it on large models with many tens of thousands of objects, and it gets impractically slow. Basic profiling shows https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/schema.py#L64 replace_attribute to be guilty, which I have no idea how to make simpler (https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/element.py#L398-L402 the walk is the bottleneck, it seems, but it is necessary).

Note that it's not just a speed issue, the speed seems to slow down over time, and memory climbs. By the time I've done about 7000 elements I'm starting to run out of memory.

I wonder if there is a more fundamental trick that can be applied here, without the whole recreate and replace, but instead just edit-in-place and even keep the same STEP ID. Any ideas? Maybe old could get a new STEP ID without changing references, and new could use the previous STEP ID?

**Comment by aothms** [comment]
Well, there's the little things:

It seems you're basically iterating twice, with `has_element_reference` and `walk`. Maybe that can be quicker? Although it could also be that it would be slower, if you have to build new attribute values even if they're not changed. Maybe there's a simple copy on write trick that could help.

We could give you the attribute indices of the attributes that correspond to the inverse relationships, so that you don't have to iterate over all attribute values of the inversely related instances.

We could implemented it in C++, which I think combined with the above, would easily give you a 30x speed increase.

I don't see anything clever we could do fundamentally. Swapping step ids, is not helpful because in most cases it's not the id that constitutes the relationship, but a C++ pointer. Changing class names is also not an option since we're dealing with underlying strongly typed C++ data. But if it's really really slow, and you have to do these operations in bulk, I guess the most clever way is switching parsing paradigm. You could serialize the ifcopenshell model, parse using a more flexible latebound parser (https://github.com/IfcOpenShell/step-file-parser), change class there, which is just a string label then probably, serialize that out, and parse again using ifcopenshell.

**Comment by Moult** [comment]
> It seems you're basically iterating twice

I am, but I profiled it to check and the has_element_reference isn't the slow part. The reason it's done twice is because in a transactioned environment recording the assignments is slow.

> We could implemented it in C++ ... 30x speed increase.

This sounds very attractive, and also something I might not be capable of doing :)

I'd prefer not to change the paradigm (one way I considered was treating step as text, and swapping it out as text) because although it might temporarily solve it in this script I'm running, it's still an operation I'd like to run in a graphical native authoring, and if replace_attribute was implemented in C++ then it'd give speed increases across many usecases (in particular geometry updates where the old shape rep is swapped for a new shape rep).

**Comment by brunopostle** [comment]
Probably not the answer you are looking for, but direct text manipulation
would do it in seconds:

    sed -i 's/=IFCWALL(/=IFCSLAB(/i' file.ifc

**Comment by Moult** [comment]
@brunopostle yeah, which would also lead to invalid predefined types :( but yes, treating it as text would be really fast, and can be done in Python to ensure validity (i.e. create the new entity, read it as a string, and replace it as a string...)

Depending on how easy / quick it takes to implement in C++, I might have to resort to doing that type of hack for my current project, but ideally a solution would lead to speedups in quite a few other usecases.

**Comment by brunopostle** [comment]
Again, probably not what you're looking for, but in File::IFC entity
classes are just a 'type' attribute and can be changed easily. You could
then search for all the predefined types and change these etc..

**Comment by Moult** [comment]
So although a C++ issue would be preferred, I created a batch reassign function in the meantime. Because the walking and attribute setting is what takes time, it batches the necessary edits and does it at the end. E.g.

```
reassigner = ifcopenshell.util.schema.BatchReassignClass(ifc)
for element in elements:
    reassigner.reassign(element, ifc_class)
reassigner.unbatch()
```

The usage constraint is that I reckon you should only batch unrelated elements (i.e. elements that don't reference one another), since whilst the batch is occurring the inverses are not yet updated.

**Comment by aothms** [comment]
Great news, as promised I wanted to at least try and supply you the attribute indices that allow to trace back the forward relationship. That way you can get rid of the walk() which I suspect could be a considerable time sink.

See the test for how you can use it https://github.com/IfcOpenShell/IfcOpenShell/commit/f9391f80c46cff2007ee5e8628d058458072d55c

**Comment by Moult** [comment]
Awesome thanks! I tried it out but unfortunately I didn't get much performance gains on top of the batch method I had written. I assume though that for non-batched it'd be a much more significant performance gain but I haven't got something ready to test with.

Closing :)
