### ISSUE TITLE
Error in activation of BlenderBIM

### ISSUE THREAD

**Issue by diwa130** [IfcOpenShell/IfcOpenShell#2414]
I have imported the model blenderbim-220516-py310-macos.zip on my Blender (vsn. 3.2). When I click on the checkbox I get an Import error , see attached.

[Error.docx](https://github.com/IfcOpenShell/IfcOpenShell/files/9578227/Error.docx)

**Comment by Moult** [comment]
@diwa130 Unfortunately we do not provide builds for Mac ARM because we can't afford a Mac buildserver. We're doing fundraising for it. Would you please help chip in 5$ per month so we can rent a buildserver? https://opencollective.com/opensourcebim - we're currently at about 20$ per month out of the 70$ per month goal.

**Comment by Moult** [comment]
We're still a little short of recurring funds to sustain building this in the long term, so donations are still very much needed, but there are now Apple M1 builds for both IfcOpenShell and the BlenderBIM Add-on! Closing bug :)
