### ISSUE TITLE
Question regarding the supported python version

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2428]
So each new python release brings in with new functionality. Like the python 3.10 which brought the new powerful [match case statement](https://towardsdatascience.com/the-match-case-in-python-3-10-is-not-that-simple-f65b350bb025).

However i saw that even python 3.7 is supportend, so do we limit ourselves in our coding just to the level of python 3.7 functionality and don't use for example match case statement in the python script?

**Comment by aothms** [comment]
It depends a bit. For core modules, I'd say all non-eol python versions should be supported. But recently for example in https://github.com/IfcOpenShell/IfcOpenShell/pull/2355 we also decided on using 3.10+ features.

**Comment by Moult** [comment]
Maybe we should make an official statement about this and I can add it to the docs. How about:

 - ifcopenshell, and ifcopenshell.{express,geom,util} namespace should support back to 3.6 (ifcopenbot builds 3.6 it seems)
 - blenderbim and everything else (ifcdiff, patch, ifctester, etc) should support back to 3.9 (right now we provide builds back to 3.7, but I reckon a good policy is to follow Blender's LTS releases, of which the oldest one has just expired in June 2022, so I'm happy to move with the times)

The reason for "everything else" is because everything else is also usually exposed in a GUI in Blender. The BCF one is an odd-one out since it's 3.10 but maybe in the future we should be a bit more prudent.

**Comment by Martin15135215** [comment]
Thanks for clarifying it. 

I think also for IfcOpenShell with his relativ long history, it makes sense to support more than just 3.10.

However as BlenderBIM is still alpha software, even if it supports for example 4D Animation directly from the IFC, that's unheard of in the AEC industry, it makes more sense to me now to support only 3.10 and focus our scarce resources more on development, so we can show the AEC industry how badass we are.

That's just my newbie opinion.

**Comment by Moult** [comment]
> can we see that directly in GitHub

Wow, how do you do that?

Keep in mind there is not just the BlenderBIM Add-on code, there is all the other libs: ifcdiff, ifcclash, ifcpatch, bcf, ifctester, ifc4d, etc and people use these outside Blender on all sorts of different Python environments which have different versions, so I think it would be kind to at least also support back to 3.9.

Which part of the codebase were you keen on using a bunch of 3.10 features? I admit I'm not very well versed in what's new in Python and maybe I'm missing out on a lot.

**Comment by Martin15135215** [comment]
> Wow, how do you do that?

I did a research in the internet and i found something. It is possible the get the download count from the release API -> see this [stackoverflow](https://stackoverflow.com/questions/4338358/github-can-i-see-the-number-of-downloads-for-a-repo)

And based on this, someone even created a [website service](https://somsubhra.github.io/github-release-stats/?username=IfcOpenShell&repository=IfcOpenShell&page=1&per_page=5) out of that:

![image](https://user-images.githubusercontent.com/110968398/191426399-446d102e-2e09-47c0-83bf-baa54a34da7e.png)

![image](https://user-images.githubusercontent.com/110968398/191426454-35ebde2a-689c-4f2a-93a0-c299c1639747.png)

> Which part of the codebase were you keen on using a bunch of 3.10 features?

I also admit being an rookie in python and programming (My background is civil engineering -> still in bachelor). However when i last saw an article about the [union |](https://realpython.com/python310-new-features/#type-unions-aliases-and-guards) or the match case statement, i thought it would increase the readability from the code.

For example here https://github.com/IfcOpenShell/IfcOpenShell/blob/79bb40092f80f4413e0002a293db92019a17f77a/src/blenderbim/blenderbim/bim/module/sequence/operator.py#L1157-L1167

We could do:

```
def animate_output(self, obj, product_frame): 
	match product_frame["type"]:
		case ["CONSTRUCTION", "INSTALLATION", "NOTDEFINED"]:
			self.animate_creation(obj, product_frame) 
		case ["DEMOLITION", "DISMANTLE", "DISPOSAL", "REMOVAL"]: 
         	self.animate_destruction(obj, product_frame) 
		case ["ATTENDANCE", "MAINTENANCE", "OPERATION", "RENOVATION"]: 
         	self.animate_operation(obj, product_frame) 
     	case ["LOGISTIC", "MOVE", "DISPOSAL"]: 
         self.animate_movement_to(obj, product_frame) 
    	 case _: 
         	self.animate_operation(obj, product_frame) 
```

I agree that for this example this is not a great bonus in using the match case statement, however like in this [article](https://towardsdatascience.com/the-match-case-in-python-3-10-is-not-that-simple-f65b350bb025) explained, you can do some sophisticated logic with it.

**Comment by Moult** [comment]
Looking at the download stats it looks as though py37 is still relevant. I'm personally not a fan of switch case statements :)

**Comment by aothms** [comment]
(though that the capabilities of structural pattern matching combined with destructuring can be really convenient for ifc https://peps.python.org/pep-0636/#matching-multiple-patterns)

**Comment by Moult** [comment]
I guess the main reason this hasn't been formalised is because we don't have enough devs or users to warrant the need for it. If we have more devs wanting to use later features, they get priority. If we have more users with varying environments, they get priority I feel. Right now, there seem to be more users than devs. However, if you're a dev reading this, and start committing 3.10 stuff consistently, the priority starts to swing the other way.

The other day I saw a walrus operator somewhere, so vote with your code :) Once we get to a certain arbitrary level of maturity, we'll make a call. But right now, I'd like to make the call that we stick to supporting 3.7 until June 2023, then most likely jump to 3.9.

**Comment by Martin15135215** [comment]
@aothms I think your right. i did not test my code, before publishing it here, my bad 😅

**Comment by aothms** [comment]
no worries :)
