### ISSUE TITLE
BB: prevent adding redundant geometric representation contexts. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2432]
Not sure how it happened, but as you can see [here](https://community.osarch.org/discussion/comment/12701/#Comment_12701) @Plae-Blue-Dot added many redundant geometric representation contexts to the file. 

It seems like BB should not allow this to happen. 

@Moult if you agree, i can try to put together some code to prevent this.

**Comment by Moult** [comment]
I think this has already been fixed a while back: https://github.com/IfcOpenShell/IfcOpenShell/commit/af4cb22756ffd44ebb6eeaf5d6a62d22c75973fb - it was a pretty nasty bug.

**Comment by theoryshaw** [comment]
cool.. good to know. 
Shouldn't we also prevent adding the same context here, as well? 


![2022-09-21_22-57-13_Blender_ CUsersOwnerDesktopTesty blend _blender](https://user-images.githubusercontent.com/507113/191655255-4fd93530-7d45-4177-a338-b015eff7cf17.gif)

**Comment by Moult** [comment]
At the moment, no because the identifier (e.g. body) and target view (e.g. MODEL_VIEW) is not the only unique identifying factor. There is also target scale (currently not exposed in the UI for scale dependent representations) and custom target views, which we need to also build a UI for. Once that is supported, then we can prevent the duplication contexts.
