### ISSUE TITLE
[BlenderBIM] Create PropertySingleValue in Custom_PropertySets in UI

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#2459]
I did download the latest BlenderBIM zip https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-220930

When i create an object and after i assign them a ifc class, and want to add a custom Property, it's hard to create new PropertySingleValue in the PropertySet:

![image](https://user-images.githubusercontent.com/110968398/193268422-5f3a1541-a697-4967-8454-cb59be8190d0.png)

![image](https://user-images.githubusercontent.com/110968398/193268467-738e8207-2156-420d-8b1f-ce4c31b156b6.png)

**Comment by Moult** [comment]
So the BlenderBIM Add-on is one of the few that actually use property set templates (if you've used Revit, think of it as shared param files). So that Custom_Pset is just an example of how you might define your own pset template. It is always recommended to use a template so that the entire project always uses the right data types, property names, value enumerations, etc. That's why you aren't given the choice to create your own arbitrary property in Custom_Pset ... it's locked to what's defined in the template.

You can edit/create your own templates in Scene > IFC Project Setup > IFC Property Set Templates. It's saved to a file so you can share it as a project library with your friends.

If you really want to go wild with arbitrary stuff, for now the interface for that is pretty hidden, but you can do it user Object > IFC Utilities > IFC Bulk Property Editor.

We really need to upgrade the UX in this portion since it's a constant source of confusion for those who just want to slap on a random property and not go through the trouble of templates.

**Comment by Martin15135215** [comment]
Yeah, i already thought that the option is hidden, so that user don't make data mess. I did not know about the template. Thanks for the information.

Btw i am not a revit user. i just know a litte bit of ifcopenshell-python :)

**Comment by Moult** [comment]
Cheers, if you're not a Revit user, think generically about how it's a good idea to have a template of properties, data types, and which properties can apply to what, and recommended values for every project / company / local government / etc rather than every user creating their own random properties :)
