### ISSUE TITLE
BlenderBim - Angle annotation tool does not relate to drawn angle?

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2490]
I have tried to understand it but I think it might not be right

a 90 degree angle drawn in model:
![image](https://user-images.githubusercontent.com/78321676/194749411-80018dc8-5cfe-4c69-93f9-681cecbbe9fc.png)
Becomes 180 degrees:
![image](https://user-images.githubusercontent.com/78321676/194749425-d9836db4-945e-4b3a-8412-c8a05ca9c71a.png)
Unless there is something obvious I am missing, I think this is not correct.
Here is the Ifc test file
[Angle anno test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9741226/Angle.anno.test.ifc.txt)
remove the .txt

**Comment by Moult** [comment]
So the feature is working as expected but at the same time the feature was built so ridiculously badly so after I finish my first pass upgrading the modeling tools I will definitely go through all these drawing module bugs and give it a upgrade too.

The angle tool requires 3 points, which represents 3 points of a 3-point arc, not 2 points + center. So this:

![2022-10-09-223632_256x218_scrot](https://user-images.githubusercontent.com/88302/194754800-bb1a788a-13b8-40c1-bd7d-32143aaa7000.png)

... will produce this:

![2022-10-09-223637_221x184_scrot](https://user-images.githubusercontent.com/88302/194754834-ea28aa3a-c2b3-4632-ab42-5eef264fc15e.png)

... because it actually resembles this (3-point arc generated using the cad arc tool):

![2022-10-09-223655_266x266_scrot](https://user-images.githubusercontent.com/88302/194754853-8f2faef2-376b-4e4f-8f9b-75eae0bf373f.png)

**Comment by Plae-Blue-Dot** [comment]
Ah alright thanks for the clarity Moult, atleast now I can use it haha,

But ja that is incredibly difficult to line up unless you have already drawn an arc to reference,
![image](https://user-images.githubusercontent.com/78321676/194757736-4d3d67cd-a462-4fe6-99f0-4f2b28b52d64.png)

I've attached the 90 degree file working according to that
[Angle anno test_working.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9741591/Angle.anno.test_working.ifc.txt)

**Comment by Moult** [comment]
Agree it is the absolute worst I have no idea why I thought it was a good idea to build it that way at the time :)

**Comment by theoryshaw** [comment]
related: https://github.com/IfcOpenShell/IfcOpenShell/issues/2254

**Comment by Andrej730** [comment]
Changed the angle operator for more intuitive one in d88510b91961dc3e1bef7f40478b2e66bc58d73a - please check it out.

**Comment by Plae-Blue-Dot** [comment]
Works brilliantly thanks @Andrej730 !

**Comment by Andrej730** [comment]
> and simple:
> ![image](https://user-images.githubusercontent.com/78321676/204803702-55995573-0476-4ce1-9f6b-e77ff54858b0.png)

Not sure if it's okay that it's not using rectangle for 90 degree angle. Though it seems readable because it's labeled "90 deg" anyway. 

Any other opinions?

**Comment by Andrej730** [comment]
I'm closing the issue as resolved.
