### ISSUE TITLE
keeping thickness the same, even after 'x angle' is used.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2523]
for IfcSlabType & IfcRampType that uses IfcMaterialLayerSet, when the 'x angle' is used, it would seem that all these dimensions should be equal.. that is, not change.

![image](https://user-images.githubusercontent.com/507113/197361527-f520e78c-867b-426c-a22f-007f11727cde.png)

**Comment by Moult** [comment]
Yep this is definitely a bug and is actually invalid to the "standardcase" behaviour described in IFC, just gotta do one more step in the math... :)

**Comment by theoryshaw** [comment]
can i try to fix this?

**Comment by Moult** [comment]
Yes please!

**Comment by theoryshaw** [comment]
took at stab: https://github.com/IfcOpenShell/IfcOpenShell/pull/2525

**Comment by Moult** [comment]
Whilst you're chipping away, you might also want to have a play with maintaining the perpendicular wall height for sloped walls. Right now the height represents the extrusion vector's magnitude, which is also not quite right. This would involve checking the code in two places, one for the operator which does ChangeExtrusionXAngle (which should maintain the height) and ChangeExtrusionDepth (which should interpret the depth as the perpendicular depth instead of the non-perpendicualr depth which it does now)
