### ISSUE TITLE
Slab doesn't survive edit mode modifications

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2540]
I might be doing something wrong...
https://www.dropbox.com/s/tlbs7d2atpywtb5/2022-10-26_20-05-47_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
Yeah the previous method of reverse engineering data from meshes was disabled because it was brittle. If you're dealing with a parametric axis extrusion (e.g. walls) or parametric profile extrusion (e.g. slabs) then use the dedicated modeling tools (edit profile, edit thickness, etc). It will ignore any "mesh" based edits as the mesh based edits could be arbitrary and incompatible.

If the object is non-parametric, you can convert it to a mesh (update mesh as tessellation) and then you are allowed to edit it as a mesh.
