### ISSUE TITLE
UI Papercuts

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#2568]
Following a comment from @Moult on the OsArch forum I'm opening this thread to centralize the problems (papercuts, not backend or missing features) users have with the interface and find a sensible way to fix them. I don't know if a github issue is the right format but I'll try to update it as we go.

For now, concerning the Type Manager / Type instancer, I have noted :
- [x] The type manager can't be reached from within the N panel UI. I expected the same features to be present in both places
![image](https://user-images.githubusercontent.com/25156105/200129887-c5028423-12ca-4860-b4e8-2391aa724e74.png)
- [x] The type manager and type instancer can't be reached from the properties editor. You can't add an IfcElement from there but you can modify the instance settings
![image](https://user-images.githubusercontent.com/25156105/200129942-f582940e-1130-4936-b0ad-41305b730272.png)
- [x] I would change the current BIM tool SHIFT + S shortcut which overwrites a pretty usefull vanilla shortcut to move the 3D cursor or move objects to the cursor. On a side note i think overriding SHIFT + R is fine since this vanilla function seems to mess up with the addon stability.
![image](https://user-images.githubusercontent.com/25156105/200130500-62f45ecc-1264-4b75-b6eb-8173556b0837.png)
- [x] I'd like to be able to drag-select multiple objects (or circle select) in the BIM tool and it's currently not possible. The other tools allow it so there might be a setting that overwrites it somewhere ? 
![image](https://user-images.githubusercontent.com/25156105/200130794-228ae65e-1e05-4023-90ed-ac89853b9df2.png)
- [x] Next a papercut that's been posted on the forum but I can't find it anymore to reply. Not really something that can be solved by Blenderbim since it's a feature of Blender. The "Region Overlap" setting in the preferences prevents you from scrolling horizontally to get to the settings on the right when there are many. Granted it's bad UX in the first place but disabling it solves _this_ problem.
![capture](https://user-images.githubusercontent.com/25156105/200131405-36a9882a-cf82-4973-9568-a3aacab62f04.gif)
- [ ] The type manager has thumbnails. It would be nice if the profile manager also had thumbnails.

**Comment by Moult** [comment]
Shift-S is currently split (i.e. split wall). Any recommendations of other keys to use? Shift-K for Cut(Kut?)? The "K" letter with some imagination could be like a cut at the middle of the |<.

**Comment by Gorgious56** [comment]
Well, as a matter of fact K is used for the knife tool in edit mode and "Split Strips" in the video sequence editor so I don't think it's too far fetched to associate split and the shortcut K. 

An issue with this is that the letter is on the right side of the keyboard...

**Comment by Moult** [comment]
Splitting walls is a relatively rare operation, so I'm OK for it to be on the right side of the keyboard. Other more common ones I aim to be on the left side / home row.

**Comment by Andrej730** [comment]
1) Added type manager to N-panel. Actually made side-panel and header layout logic more similar. 68bbb4d7a19947770ea155219f159dbfd2689e6b

2) Added interface from sidebar to properties too 68bbb4d7a19947770ea155219f159dbfd2689e6b

3) Changed "Split" hotkey to Shift-K for now. Shift-S was really counter-intuitive, especially when you need to move cursor around to do Split 😅 c7d1f5efc0ed5a15e2140ffeb78a69f7cfffbbb1

4) Figured it out, now it should work just as default blender tools (85bba9d5f8340dfdd594d48b3f548ec6ad6c9b64)
BTW what else I've found that there is "B" hotkey that can be used from any tool which brings box selection.

5) --

6) WIP

Side issue:

Noticed that description for split operator wasn't showing when you hover on operator button because button is linked to `bim.hotkey` instead of `bim.split_wall`. Added a way to display operator's description in that kind of cases in 8e696cbf02f1d6e8971c8660ea60d64227d68923. I guess this solution won't work for all hotkeys because some have multiple operators based on context. So I guess the next step will be to implement similar logic to display correct description.

**Comment by Gorgious56** [comment]
Awesome ! I cant wait to test this out :) 

Cheers

**Comment by Andrej730** [comment]
@Gorgious56 Added thumbnail for profile manager in f01900bdb (turn out you can create your own preview collection with `bpy.utils.previews.new()` and store images there, could be useful for some other features in the future).

Currently previews are generated as you change active profile in profile manager - it happens really fast so it shouldn't be a problem.

https://user-images.githubusercontent.com/9417531/215722067-67ac4d13-f35d-45e0-8b69-d210745209db.mp4
