### ISSUE TITLE
My addon dont work when blenderBIM is active

### ISSUE THREAD

**Issue by dnk53** [IfcOpenShell/IfcOpenShell#2575]
This method fails:
bpy.ops.object.duplicate_move_linked(...)
[test.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/9953812/test.zip)

**Comment by theoryshaw** [comment]
Your script is not BlenderBIM specific... it can work with just native blender.

regardless, it seems to work for me...
video: https://www.dropbox.com/s/1epgvfcflxjyzf5/2022-11-07_13-06-20_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
I can recreate the issue, this is because we monkey patch the duplicate_move_linked (and non linked) operators. I'm not quite sure how to support OBJECT_OT_duplicate as it's a dictionary. Maybe this is something @Gorgious56 might know the incantation to?

Alternatively, your addon can do the operation without calling ops which is preferred anyway:

```
for obj in bpy.context.selected_objects:
    new = obj.copy()
    new.matrix_world[0][3] += 5
    for col in obj.users_collection:
        col.objects.link(new)
```

**Comment by dnk53** [comment]
Thank you very much for fast response!
Hope you can solve it because it might be a little annoyans when your script suddenly don't run and you don't know why.
(At the moment I use blenderBIM only to import ifc-files)

**Comment by Gorgious56** [comment]
I think the problem is that it's not an operator per se, but a [macro](https://docs.blender.org/api/current/bpy.types.Macro.html) of 2 operators (duplicate, then translate) and in blenderbim it's monkey patched as a regular operator, which can only take one override dictionary as input. I don't really know how to override a macro, maybe redefining https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/geometry/operator.py#L557 as a macro instead of an operator ?

There is unfortunately not much doc online about macros... Maybe this can help ? https://blender.stackexchange.com/a/27182/86891

But that goes to my previous cautionary point that Blenderbim is such a big overhaul of the interface and API that it should not be enabled when the user is not specifically using it. It's impossible to enforce, of course, but it would prevent this kind of problem.

**Comment by Moult** [comment]
Ah OK I had no idea macros existed, here's a useful link I dug up: https://blender.stackexchange.com/questions/44971/how-to-use-bpy-ops-macro-defining-macro-steps

@dnk53 would you like to have a shot at fixing this?

**Comment by dnk53** [comment]
Hi,
Yes I think it would be nice if someone could fix it. Otherwise someone else will run into this problem. Now when I know the reason it is no problem for me anymore. But it was only by chance that I found out that it had anything to do with blenderBIM.

**Comment by Gorgious56** [comment]
This issue raises an interesting question, with Blender V3.2 dictionary overrides have been officially deprecated (but still work for an unknown number of versions). See https://developer.blender.org/rBf438344cf243632e497772cf1f855b9c8856fd37 and https://wiki.blender.org/wiki/Reference/Release_Notes/3.2/Python_API

But there is AFAIK no way to override a macro without using dictionary overrides.

**Comment by Moult** [comment]
Given that dictionary overrides have been deprecated and even if we did redefine as a macro there doesn't seem to be any way to accept a dictionary as input (so that we could support it). It might be an unfortunate thing but we might just have to make a call that "too bad, we don't support it" and just document it? Thoughts?
