### ISSUE TITLE
BlenderBIM: Collections as Selection sets

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#2580]
Just found out about the feature that you can assign an object to multiple collections (yes, very sweet!).

So, a lot of new possibilities came to my mind´:
* classifications: auto-create collections for each classification (hierarchically) for easy selecting
* type: select elements by class/predefined type
* systems
* layers
* linked to IfcSelectors?
* reuse of annotations?

![image](https://user-images.githubusercontent.com/9949323/200526449-00bfd6ef-99a3-49a6-8396-30a6ba3eb247.png)

**Comment by TZwielehner** [comment]
What doesn't work now is showing/hiding object with the eye symbol. But with select elements / hide it works, too.

It would be awesome if we could add a query to a collection that updates the content (including sub collections):
FIlter: IfcElement[Pset_*Common.Status != '']
Grouping: Pset_*Common.Status> @Storey > Class > ...

**Comment by Gorgious56** [comment]
Yes that is an awesome feature of collections that is often overlooked. You can also link collections into other collections. However it does bring some problems that I've [dug up in my projects](https://devtalk.blender.org/t/unique-identifier-for-layer-collections/23966) in the past.

Coupled with the view layer system it helps creating specific layouts and view setups of your project with just a few clicks.

Theoretically if you click on the eye icon of a collection, all its objects are hidden from the viewport. In reality, the rule is that an object is automatically hidden by its collections if and only if all the collections it is linked to are hidden. So if your object is still part of a collection that is not hidden, it will display.

The solution here is to SHIFT + Left Click the collection icon which will force its children objects to also be hidden. This is destructive though, and will change the visibility state per object.

![Animation3](https://user-images.githubusercontent.com/25156105/200769766-9e2a68c2-c18e-49b6-9ab4-477350f1ae29.gif)

**Comment by TZwielehner** [comment]
When would you use different view layers in Blender? Do you have any examples?

**Comment by vulevukusej** [comment]
@TZwielehner - I played around with collections a while back to create automatically generated selection sets, based on permutations of a chosen class/property.   I ran into some performance problems though and this is why I ended up being more interested in using IfcGroups.  IfcGroups also have the benefit of being "shareable" and can be linked to IfcSelector syntax (albeit a little dodgily if you look at my code..)

**Comment by Gorgious56** [comment]
@TZwielehner view layers "retain" the collections exclusion state. That means that for example you can have only your Ventilation collection enabled in one view layer, then only your structural elements in another, and you only have to toggle between them to pass from one to the other. IF you use only one view layer, you'll have to manually enable / disable the collections which is time consuming and error prone.

One other possibility is to use different scenes, where you can link collections as you wish and simply not link the ones you don't want. However in Blender it's really hard to manage addon data across multiple scenes since you can't reliably store data at the file level. Also, I consider it an advanced user feature since you have to dig into the blend file data and master the fake user system to not lose your objects in the process. Most important properties are stored on the current scene custom properties, so you'll lose them if you create a new one.

But right now as @vulevukusej experienced it isn't viable to use collections like that, because blenderbim relies on certain objects being in certain collections, and objects are automatically moved to their expected collections on export. I agree that this should first be tackled with the IFC schema if possible and then updated to work with Blender's grouping systems.

**Comment by Moult** [comment]
This can now be closed because we've decoupled our organisation from Blender's collection tree, and now support multiple "element breakdown" modes. Go nuts! :)
