### ISSUE TITLE
Eyedropper type of functionality, where you can apply the type of one object instance to another object instance.  

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2581]
Eyedropper type of functionality, where you can apply the type of one object instance to another object instance.  

![image](https://user-images.githubusercontent.com/507113/200704307-2316bad7-9aa5-43ab-bb9d-bc87eb3a6f03.png)

**Comment by Plae-Blue-Dot** [comment]
That would be amazing an equivalent of 'match properties' from Autocad

**Comment by Moult** [comment]
This is not too tricky to implement (@Gorgious56 do you know if there is any way to trigger the eyedropper without a pointer property field that shows as a large text field?) but I'd like to highlight that there are other similar features elsewhere like "Copy Property to Selected". I'd like to try to ensure that these features are consistent so that users can recognise a "pattern" of how things are meant to work.

Can you envision any other situations where the eyedropper paradigm might be used? Is it only types? Or can it be generalised?

**Comment by theoryshaw** [comment]
> Can you envision any other situations where the eyedropper paradigm might be used? Is it only types? Or can it be generalised?

could see this being applied to things like matching ifcclass, property sets, storage containers, material assignments, and profiles.

**Comment by Moult** [comment]
In that case I'd propose not building the UI you have mocked up but instead having a separate UI sort of like how archicad as a match properties window. The user could activate it in the BIM tool, eye drop various objects then decide what to transfer over.

In theory that could then supersede the individual property copy buttons which would make the UI much neater.

Anyone can do a little mockup?

**Comment by theoryshaw** [comment]
a mock up like this?
Maybe stuff like `materials` and `profiles` can not be selected if you choose `type`, as they will come over with the type.

I'm sure there's other stuff that could be added to this list as well.

![match attributes](https://user-images.githubusercontent.com/507113/223004973-8b14c20a-07bc-4c27-a09e-43b80d103029.jpg)
