### ISSUE TITLE
Ifcopenshell geom: Generate the polygon of  the outer boundaries in a storey

### ISSUE THREAD

**Issue by gpastal24** [IfcOpenShell/IfcOpenShell#2589]
Hi,

I am trying to get the outer curve of a building storey. For this I use ifcopenshell.geom to get the vertices of the slabs that are contained in the said storey. The problem arises when there are holes in the shape representation. Is it possible to identify the which vertices are part of a hole ? I am using shapely Polygon for the polygons

`  storey = slab.ContainedInStructure[0].RelatingStructure.Name

  settings = ifcopenshell.geom.settings()
  shape = ifcopenshell.geom.create_shape(settings, slab,repr=slab.Representation.Representations[0])
  faces = shape.geometry.faces # Indices of vertices per triangle face e.g. [f1v1, f1v2, f1v3, f2v1, f2v2, f2v3, ...]
  verts = shape.geometry.verts # X Y Z of vertices in flattened list e.g. [v1x, v1y, v1z, v2x, v2y, v2z, ...]
  grouped_verts = [[verts[i], verts[i + 1], verts[i + 2]] for i in range(0, len(verts), 3)]
  grouped_faces = [[faces[i], faces[i + 1], faces[i + 2]] for i in range(0, len(faces), 3)]
  poly_pts =[]
  for i in grouped_verts:
        poly_pts.append((i[0],i[1]))
  space_points = Polygon(poly_pts)
  self.storeys[storey].append(space_points)
`

**Comment by aothms** [comment]
These kind of operations are easier in PythonOCC (`settings.set(settings.USE_PYTHON_OPENCASCADE, True)`) because it gives you a higher level data model with inner and outer boundaries. In short: use TopExp_Explorer to iterate over the `TopoDS_Face`s and use `OCC.Core.BRepTools.breptools_OuterWire` to get only the outer wire of the face and then again TopExp_Explorer to only get the vertices of that face.

If you don't want to go that route then you can reconstruct a similar higher order view from the mesh. Find connected components (faces with different surface normals will not share vertices when settings.WELD_VERTICES is False). Group all triangles (a b c) to edges {a,b} {b,c} and {c,a} and remove the duplicates. That way you eliminate all internal edges that originate from the triangulation. Then find all cycles in the remaining edges and take the one e.g the largest x-coordinate for a vertex.

**Comment by gpastal24** [comment]
Thanks for the quick reply and concise reply. I am closing this.  Many thanks again

**Comment by gpastal24** [comment]
Hi I am reopening this. I have a few more questions.
First, I am using the following code with pythonOCC since I have failed miserably using the second approach.
The code for the vertices extraction per element face is the following.

```
                exp_face = OCC.Core.TopExp.TopExp_Explorer(shape.geometry, OCC.Core.TopAbs.TopAbs_FACE)
                # wires =[]
                verts=[]
                while exp_face.More():
                    
                    face = OCC.Core.TopoDS.topods_Face(exp_face.Current())

                    wire = OCC.Core.BRepTools.breptools_OuterWire(face)

                    exp = OCC.Core.TopExp.TopExp_Explorer(wire, OCC.Core.TopAbs.TopAbs_VERTEX)
                    verts_=[]
                    
                    while exp.More():
                        
                        vertex = OCC.Core.TopoDS.topods_Vertex(exp.Current())
                        pnt = OCC.Core.BRep.BRep_Tool_Pnt(vertex)

                        verts_.append([pnt.X(), pnt.Y(), pnt.Z()])
                        exp.Next()
                    verts.append(verts_)
                    exp_face.Next()
```
Is this process correct? 

My approach after that was to use the 5-th or 6-th lists in the verts nested list to get the 2D vertex coordinates in the plane that I wanted i.e facing from top or down.
One issue is that there multiple identical points in each face's vertices (all three of the coordinates not just 2d).
Secondly the slab with a hole in it has 5 faces instead of 6 (??) .

**Comment by aothms** [comment]
> multiple identical points in each face's vertices

Yes, if you explore like this, you get the start + end vertex of each edge and therefore the connected verts are repeated. You can use BRepTools_WireExplorer which has a CurrentVertex. It also guarantees that the edges are explored in the correct order.

>  Secondly the slab with a hole in it has 5 faces instead of 6 (??) .

For a slab with hole I would expect `6 + number of edges of inner bound` faces. So something must be wrong.
