### ISSUE TITLE
Changes in the type of an element are not applied to the intstances of that type

### ISSUE THREAD

**Issue by lfcastel** [IfcOpenShell/IfcOpenShell#2599]
I'm not sure if i'm doing something wrong, but when i change the material on a type level it gets applied to the instances of that type. But if you delete the material of a type, it is not applied to the instance.

Louis

**Comment by lfcastel** [comment]
Looks to be fixed in the latest daily built

**Comment by Gorgious56** [comment]
Hello, could you tell us more about your exact workflow ? 
I assume you're using the Blenderbim addon since you didn't post any code ?

AFAIK geometry isn't automatically updated when you change an ifc type material, however you can force regenerating the geometry with SHIFT + G while using the BIM tool in the 3D viewport.

**Comment by lfcastel** [comment]
https://www.loom.com/share/4504850eebf24c9c8d7c4f41006ce230

It's not about the geometry, it's about deleting the material on a type level, then going to a typed object and the material is still there (see loom)

**Comment by theoryshaw** [comment]
> But if you delete the material of a type, it is not applied to the instance.

I don't think this functionality is there, yet. 

At present, i think, when you delete the IfcMaterialLayerSet assigned to the type, the instance is still assigned that residual 'blender material'.  

Yes, intuitively, the UI, should remove the 'blender material' too.

...

@Gorgious56 suggestion ( SHIFT + G) above works, for removing this residual material.
