### ISSUE TITLE
IfcConvert fails at converting buildingSMART sample files

### ISSUE THREAD

**Issue by rajanbrussels** [IfcOpenShell/IfcOpenShell#2623]
IfcConvert does not find the geometry of some official buildingSMART sample files (https://github.com/buildingSMART/Sample-Test-Files), for example [this file](https://github.com/buildingSMART/Sample-Test-Files/raw/master/IFC%202x3/SDK%20-%20S1/1.%20IFC%20models%20-%20modellen/01%20Engineering%20models%20-%20Engineeringsmodellen/E-S1-RWB-Geelen-Beton%2001%201e%20verdieping.ifc). 

```
./IfcConvert-0.7.exe E-S1-RWB-Geelen-Beton\ 01\ 1e\ verdieping.ifc E-S1-RWB-Geelen-Beton\ 01\ 1e\ verdieping.glb -v
IfcOpenShell IfcConvert v0.7.0-e508fb44 (OCC 7.5.3)
Scanning file...
Done scanning file
Parsing input file took 0 seconds

Log:
[Notice] [2022-11-28 09:16:51] exclude entities IfcOpeningElement IfcSpace
[Warning] [2022-11-28 09:16:51] Precision lower than 0.0000001 meter not enforced
[Notice] [2022-11-28 09:16:51] No geometrical elements found or none succesfully converted
```

Strangely, the file can be correctly converted to XML with a proper file structure. The file can also be visualized in BIMCollab (see below) or Autodesk A360.

![image](https://user-images.githubusercontent.com/107267287/204241755-929fb1cf-bf28-4dd4-86b9-90cfb45c0013.png)

Thanks!

**Comment by Moult** [comment]
It seems as though that file does not specify geometry appropriately, I've reported it upstream: https://github.com/buildingSMART/Sample-Test-Files/issues/128

In viewers that can support other representations, you can see it, but I suspect IfcConvert focuses on 3D body representations which is pretty sensible and that's why you don't get results.

I think we'll need to wait for upstream to fix their data.

![2022-11-30-225815_1920x1080_scrot](https://user-images.githubusercontent.com/88302/204790559-f3f697c6-955f-4406-8bb8-6586719e4327.png)

**Comment by rajanbrussels** [comment]
@Moult : OK, thanks a lot for your quick reply!
