### ISSUE TITLE
Colors aren't all properly rendered

### ISSUE THREAD

**Issue by FragColor** [IfcOpenShell/IfcOpenShell#265]
Hello,

I've found a case where colors aren't all properly rendered although it seems not to be a specific case.

To demonstrate this, let's consider the Schependomlaan model. You can find it on GitHub at [https://github.com/openBIMstandards/DataSetSchependomlaan](https://github.com/openBIMstandards/DataSetSchependomlaan) in the `Design model IFC` folder.

As you can see on the GitHub page (or directly in Solibri) the expected result looks like : 

![](https://raw.githubusercontent.com/SvSchaijk/DataSetSchependomlaan/master/figure%202.png)

However, what I've got using IfcConverter (with `APPLY_LAYERSETS` or not) looks like :

![Imgur](https://i.imgur.com/7h7mEd2.png)

I've done some investigation and found that IFCOS doesn't consider colors from materials not declared into a layer set. Here, representation items of most walls aren't associated with a style and so they can't be associated with a color by this way. The only other way I know IFCOS uses to associate color to elements is by material association. However, as I said before, IFCOS only considerers it possible through layer set.

Basically, IFCOS is able to interpret these lines: 

```
#2291=IFCMATERIAL('Brick');
#2292=IFCMATERIALLAYER(#2291,360.,$);
#2293=IFCMATERIALLAYERSET((#2292),'Wall');
#2294=IFCMATERIALLAYERSETUSAGE(#2293,.AXIS2.,.POSITIVE.,-180.);
#2295=IFCRELASSOCIATESMATERIAL('0eDzaK6d93t9658vnoDtFP',#5,$,$,(#35,#220,#293,#300),#2294);
```

but not these:

```
#33032= IFCMATERIAL('03 mw-baksteen - bruin (liggend)');
#655836= IFCRELASSOCIATESMATERIAL('2mCXec$NZJNBivhafKeW$a',#25,$,$,(
#655832),#33032);
```

FYI the equivalent of what I've written above in terms of code lines is:

```
bool IfcGeom::Kernel::convert_layerset(const IfcSchema::IfcProduct* product, std::vector<Handle_Geom_Surface>& surfaces, std::vector<const SurfaceStyle*>& styles, std::vector<double>& thicknesses) {
	IfcSchema::IfcMaterialLayerSetUsage* usage = 0;
	Handle_Geom_Surface reference_surface;

	IfcSchema::IfcRelAssociates::list::ptr associations = product->HasAssociations();
	for (IfcSchema::IfcRelAssociates::list::it it = associations->begin(); it != associations->end(); ++it) {
		IfcSchema::IfcRelAssociatesMaterial* associates_material = (**it).as<IfcSchema::IfcRelAssociatesMaterial>();
		if (associates_material) {
			usage = associates_material->RelatingMaterial()->as<IfcSchema::IfcMaterialLayerSetUsage>();
			break;
		}
	}

	if (!usage) {
		return false;
	}

[....]
```

Here, a paradox is apparent with on one hand the name of the method and the other hand the cast you do to get the relating material which let suppose that other cases are possible.

So, why doesn't IFC consider a case like this one ? Haven't you seen something like this ? Am I missing something ?

**Comment by aothms** [comment]
Hi, thanks for the detailed investigation. Indeed, this case was not considered. Usually authoring tools apparently made sure that surface styles related to associated materials where also related to the individual representation items.

The reason why the fix is a bit elaborate is that we need to account for the case that products have the same representation but different material associations, in which case the geometry cannot be reused (similar restrictions were already in place for for example opening elements which are also associated on a product level). See https://github.com/IfcOpenShell/IfcOpenShell/blob/master/test/input/same_wall_different_material.ifc

It's a large commit in a central part of the code base, let's hope it doesn't have unintended side effects.
