### ISSUE TITLE
CRS IFC conversion

### ISSUE THREAD

**Issue by PerspectivesLab** [IfcOpenShell/IfcOpenShell#2682]
Hi @Moult 
i am trying to use ifcopenshell to convert an IFC file from a src CRS to another one
for that i included PyProj to convert all cartesian point, and reproject them, this was unsuccessfull. ( EPSG:3944 to EPSG:4978 )
is there a simplier way to do so ? if such could you provide a python sample code, or any hints ?
thank you

**Comment by Moult** [comment]
So this is a bit of a tricky topic, and disclaimer that I am not a surveyor.

I guess the first question is what is your IFC model? Is it vertical construction (i.e. a building) or horizontal construction (e.g. linear infrastructure)? If it is vertical, it _should_ be designed in local engineering coordinates. I would therefore think that you should _not_ ever reproject every single geometry / coordinate from one CRS to another. Instead, you should simply change the helmert transformation parameters in IfcMapConversion to change it from the previous projected CRS to your newly desired projected CRS. I.e. only a few key points (the origin, as well as others used to average the combined scale factor) need to be reprojected to recalculate the helmert transformation.

If it is linear infrastructure designed in map coordinates directly (EPSG:3944), only then it makes sense to reproject everything. In this case, you don't want to loop through every cartesian point, since cartesian points may be used in different scenarios. Instead, you either want to loop through all object placements, or all geometric coordinates only. Which to choose, or even if you do both, depends on how your file in structured. Unfortunately, a common problem especially with civil applications is that they still treat the object placements at zero whereas the geometry is in map coordinates, which is incorrect (from the concept that object placements are a semantic insertion point or pivot point or faux-centroid-UX-thing for the object).

If you can share your file, I can also help provide more advice.

**Comment by Moult** [comment]
Bump @PerspectivesLab

**Comment by PerspectivesLab** [comment]
Hi @Moult, sorry for the late reply,
the idea behind the conversion is needed for a plateform we are building in order to view in augmented reality models vs real world. ( Location-based Augmented Reality )
we are trying to match large scale IFC models with the idea of => 1 vertices of the model matches the real world, i beleive this would be linear infrastructure
on the plateform we are trying to provide CRS conversion from multiple sources, meaning any provider could upload their IFC with a given explicit CRS, and internally we convert it to the target EPSG:4978

in the process:
- a surveyor creates a point cloud mapped on earth in EPSG:X coordinates ( from eather lidar, or fixed stations )
- a modeler creates a IFC model based on that point cloud ( multiple buildings, etc ) => much like a geojon would do, but IFC has more details
- on the later => we convert the IFC file to EPSG:4978 => then tranform vertices global to local ( bbox centered ) => we use this model + associated matrix for the projection in Augmented Reality

we are able to project the object placement, but due to the complexity of IFC schema, managing rotations are needed, and the solution seems more complex,
if you would have any hints that would be awesome

```
ifc_file = ifcopenshell.open('')

settings = ifcopenshell.geom.settings()

#settings.set(settings.USE_WORLD_COORDS, True) #Translates and rotates the points to their world coordinates

transformer_3d = Transformer.from_crs( CRS("EPSG:3944").to_3d(), CRS("EPSG:4978").to_3d(), always_xy=True )
 
iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
if iterator.initialize():
    while True:
        shape = iterator.get()
        
        
        element = ifc_file.by_guid(shape.guid)
        matrixLocal = ifcopenshell.util.placement.get_local_placement(element.ObjectPlacement)
        
        matrixGlobal = shape.transformation.matrix.data
        
        new_matrix = [
           [ matrixGlobal[0], matrixGlobal[3], matrixGlobal[6], matrixGlobal[9]],
           [ matrixGlobal[1], matrixGlobal[4], matrixGlobal[7], matrixGlobal[10]],
           [ matrixGlobal[2], matrixGlobal[5], matrixGlobal[8], matrixGlobal[11]],
           [0, 0, 0, 1],
        ]
        new_matrix = np.array(new_matrix)        
                 
        xyz = transformer_3d.transform( matrixGlobal[9], matrixGlobal[10], matrixGlobal[11]  )
 
        new_matrix[0][3] = xyz[0]
        new_matrix[1][3] = xyz[1]
        new_matrix[2][3] = xyz[2]
 
        #https://blenderbim.org/docs/users/georeferencing.html
        #ifcopenshell.util.geolocation.local2global(matrix, eastings, northings, orthogonal_height, x_axis_abscissa, x_axis_ordinate, scale=None)
 
        
        faces = shape.geometry.faces
        edges = shape.geometry.edges
		#how to manipulate verts here, needed ?
        verts = shape.geometry.verts
        materials = shape.geometry.materials
        material_ids = shape.geometry.material_ids
        
        #https://community.osarch.org/discussion/648/ifcopenshell-api-geometry-edit-object-placement
        ifcopenshell.api.run("geometry.edit_object_placement", ifc_file, product=element, matrix=new_matrix, should_transform_children=True)
        
        
        # ... write code to process geometry here ...
        if not iterator.next():
            break
            
            

            
ifc_file.write('test_4978_done.ifc')
```

provided file: [test_3944.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/10445287/test_3944.zip)

**Comment by Moult** [comment]
Ah OK, so if it's horizontal construction and you're trying to make it convert to EPSG 4978 then that makes sense. I might recommend using the geometry iterator to tessellate everything with global coordinates, then converting all of the individual XYZ coordinates to EPSG 4978. At this point, either you need to write a new IFC (to preserve all the data) or forego IFC altogether since you're effectively left with a bunch of points and no instancing of data.

The geometry data size will increase dramatically since you can no longer instance data as the reprojection could mean that objects used in multiple locations are distorted in different ways (this is with a generic approach, naturally you might consider blending a fusion of "convert all geometry" for larger objects like road segments and "convert only placements" for smaller objects like street signs, single poles). Similarly, things that were defined parametrically as circles in IFC can _only_ ever be reprojected via tessellation, as the circle definition will be warped so it's impossible to describe as a circle anymore.

Does that make sense?

**Comment by Moult** [comment]
Hey I just saw your test file and it's not a horizontal construction project like I assumed it was. It's a tiny project, for that scenario I wouldn't reproject anything except for a false origin and introduce a map conversion. That way you preserve the built surface dimensions of all objects yet can "place it" accurately in the virtual world.

**Comment by Moult** [comment]
Bump?

**Comment by PerspectivesLab** [comment]
Hi @Moult , yes it makes sense,
we finally just tessellated all to geometry as proposed and from there applied the projection with pyproj for the conversion,
we lost all IFC metadata, now we are trying to figure out a way to export a "batch table" while exporting the sub meshes, but that is another topic
thanks again
