### ISSUE TITLE
Ifc Patch: OffsetObjectPlacement | rotation in wrong direction?

### ISSUE THREAD

**Issue by smr02** [IfcOpenShell/IfcOpenShell#2684]
when rotating in positive direction, the result is rotated in negative direction. 

<img width="469" alt="Screenshot 2023-01-10 125919" src="https://user-images.githubusercontent.com/67860835/211547737-8619863d-c391-408c-95af-1cb7e0d3799b.png">

<img width="457" alt="Screenshot 2023-01-10 130201" src="https://user-images.githubusercontent.com/67860835/211547746-5e64bb7d-5d19-4a45-ae1b-6eb8b7c10341.png">

**Comment by Moult** [comment]
Don't think this is a bug, the OffsetObjectPlacement positive angle rotates things anticlockwise (as in the convention in certain mathematics). So let's assume a model with no georeferencing (like your model). Project North (PN) is always +Y in IFC, so if we rotate by 30 degrees anticlockwise via OffsetObjectPlacement, then we get the result on the right (PN* represents the rotated PN)

![2023-01-11-092446_831x486_scrot](https://user-images.githubusercontent.com/88302/211675292-2750153e-f826-4221-a9ea-40c5d92e7061.png)

Since you have large coordinates, the BlenderBIM Add-on assumes you are working directly in map coordinates. (there is no way to know for certain, as you have no georeferencing data). However, we apply a false origin and false rotation called the Blender Offset to try and heuristically detect the intended project north (no longer assumed to be +Y). This gives us the result below (similar to your screenshot). As you can see, the Grid North (GN) is autodetected to be clockwise (i.e. negative) to the right of PN. This is what gives us the negative number.

![2023-01-11-091904_928x539_scrot](https://user-images.githubusercontent.com/88302/211675874-4a9ed5f3-9a8d-487c-a001-120ab00064be.png)
