### ISSUE TITLE
IfcPropertySet::HasProperties throws exception when it gets a $

### ISSUE THREAD

**Issue by ssg3d** [IfcOpenShell/IfcOpenShell#2717]
Consider a property set as follows:

> #111 = IFCPROPERTYSET ( '9kjfif3kp8cc0kS7q$Dhot',#2,'Custom Properties','',$ ) ;

An exception is thrown when this propertyset is queried for HasProperties.
It should return a null pointer instead so it can be checked easily and handled.
I do recall seeing somewhere a comment "handle $", maybe that needs to be implemented.

**Comment by aothms** [comment]
`IfcPropertySet.HasProperties` is not an optional attribute, so $ is invalid.

We don't want to add if-else statements for all possible schema violations and returning null-pointers requires a lot of additional effort to check in the client-side code, rather than catching an exception at the location where is desired (but error-code-return-values vs exceptions is a continuous ongoing discussion of course).

Currently we have focussed on implementing this in python. There is ifcopenshell.validate that can check schema compliance. In the future we'll implement this in C++ as well, so that there is a generic mechanism to deal with this.

**Comment by ssg3d** [comment]
Parsing errors are more logical at the parsing stage. If that stage is past and we now have to query data, it should not throw errors. Potentially that means i have to encapsulate each data query call in a try catch, because potentially anything can be bad data and throw exceptions. A try catch at the outermost level means the while thing bombs because of one invalid piece of data. A better approach would be to not read the entire property set if its bad schema, so querying it does not arise in the first place. On the parsing side, there can be some approaches to handling bad data - error out entirely at a single hint of bad data (bad), treat bad data as absent and try to glean as much as possible (good), park the bad schema into “invalid” data with errors (better). The IFC format is complex and well known companies make such mistakes. Not everyone goes for IF  certification but create IFC content. A more informative and tolerant system is necessary.

**Comment by ssg3d** [comment]
I wonder, if HasProperties is not optional, probably a less misleading name would be getProperties which returns a list by ref rather than a ptr. Ofcourse, a paet with no properties should not exist in the first place (as i suggested above)

**Comment by aothms** [comment]
> I wonder, if HasProperties is not optional, probably a less misleading name would be getProperties

Yes, these names come from the IFC schema and are not always consistent. I also don't really understand where the Has- comes from.

> A better approach would be to not read the entire property set if its bad schema

But skipping over the property set doesn't really help, because we then have a dangling relationship (IfcRelDefinesByProperties) that should be skipped over as well. Maybe this case is manageable, but doing this arbitrarily, figuring out which subgraph needs to be culled upon encountering invalid data is a bit of an adventure.

> Parsing errors are more logical at the parsing stage. If that stage is past and we now have to query data, it should not throw errors.

In an ideal world yes. But as I said above, handling invalid data gracefully in a generic way in the library is very hard. And terminating on any kind of invalid data is not an option, because most files are invalid in some way (the situation is improving, but 12y ago when we started it was an utter mess). Especially since the schema violation might actually not even be significant to the use of the file.

> Potentially that means i have to encapsulate each data query call in a try catch, because potentially anything can be bad data and throw exceptions.

It means that the client application can control where it makes sense to try-catch, granularly or globally. It's simply the best we can offer at this point in time.

But as I said, we have extensive validation tools in Python, you can also use these as a warning up front to your users to inform them that a file has issues and that the application might perform suboptimally.

You can also use these validation reports to implement your own data massaging. When you encounter a property set without properties remove it from a file along with all the relationships. If we implement these kind of rules (based on the validation output) as a community it also helps us to figure out how we can later implement this in C++ in the library itself.

**Comment by ssg3d** [comment]
> But skipping over the property set doesn't really help, because we then have a dangling relationship (IfcRelDefinesByProperties) that should be skipped over as well.

Ah I see the problem.

>Maybe this case is manageable, but doing this arbitrarily, figuring out which subgraph needs to be culled upon encountering invalid data is a bit of an adventure.

Culling and pruning is certainly not a good idea, for a wide variety of reasons. I agree with your current approach and accept that the PSET will be there despite bad schema.

> It means that the client application can control where it makes sense to try-catch, granularly or globally. It's simply the best we can offer at this point in time.

Fair enough. I just happen to be in the camp of error returns rather than try-catch-throw, so I will have to mould my personality to work with IfcOpenShell, that's all :)

Thanks for your detailed clarifications.
Am closing this issue, no action needed please.
