### ISSUE TITLE
Blenderbim - no warning on closing ifc file with unsaved data

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#2719]
I've noticed that it's possible to save .blend file with ifc project and close it without knowing that there was some ifc unsaved data.
Is it a bug or there never was a warning about that some data might be lost?

Steps to reproduce:
1) Create new ifc project from demo library
2) Ctrl-S to save both .blend and .ifc
3) Use Bim Tool and place a beam (it's going to be like `#1064` in ifc)
4) If you use Ctrl-S now it will save only .blend file. You can close Blender and `#1064` won't be saved to ifc and you won't get any warnings about it.

**Comment by theoryshaw** [comment]
Although not very intuitive, that is how it currently works. 

To save both the .blend file and .ifc file use 'Save Project'...

![image](https://user-images.githubusercontent.com/507113/214326645-f8c80801-2a6d-411c-909d-b958d653e480.png)

see discussion here: https://community.osarch.org/discussion/comment/7358/#Comment_7358

**Comment by Gorgious56** [comment]
On large files saving the ifc can take several minutes, when blend files usually take at most a few seconds even on very large files.

I think one solution would be to detect when the user is about to close Blender, and display a prompt to save the ifc if the ifc file is not up to date. With a callback on exit. See https://blender.stackexchange.com/a/31539/86891

This of course doesn't take into account the autosave feature which would be a neat option, and it doesn't prevent loss of data in case of a crash to desktop. But IMO it would warrant finding a way to incrementally save an ifc file so that it is not completely rewritten every time the user saves, because the save process can be very long.

In the long run IMO since we're aiming for completely native IFC editing, saving in Blender should *only* save the ifc file, and not a .blend file. The blend file should only contain display and interface settings, not any meaningful data or geometry. I don't think this is feasible today, but that would provide a very clear indication to the users that they're not working on a blend file, but on a native ifc file, *via* a blender interface.
