### ISSUE TITLE
BlenderBim - 2d representation of door and window modifiers also show model when cut

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2742]
Here alongside a normal door and window, the door modifier and window modifier objects are with arrows:

SVG:
![image](https://user-images.githubusercontent.com/78321676/217189687-6f96b17d-71e6-46aa-a983-288894a1e5ca.png)

model view:
![image](https://user-images.githubusercontent.com/78321676/217188935-f877af1b-058a-4c72-accc-13b2285195af.png)

Amazing tool btw I can't believe the door swing updates with the size!

**Comment by Moult** [comment]
Yes, this is still a work in progress. @Andrej730 can you help fix this one? In short the plan view symbol should be under the Plan/Body/PLAN_VIEW subcontext, not the Plan/Annotation/PLAN_VIEW subcontext as things have recently changed, and the new behaviour is that annotations are drawn in addition, rather than in replacement of the body. It should be a one line fix.

**Comment by Andrej730** [comment]
Windows currently don't have any 2d representation - so this is the way they look in plan view for now. Will add it in the future though.
Fixed in 0122fe438 for doors.

![image](https://user-images.githubusercontent.com/9417531/217212103-2a53157d-6866-4850-a3f6-adf222727695.png)
