### ISSUE TITLE
Removing entities with python wrapper

### ISSUE THREAD

**Issue by andersgb** [IfcOpenShell/IfcOpenShell#275]
Not really an issue, just a howto question.

I want to open an existing IFC, remove entites that meet some criteria, and write out a new filtered IFC. My initial attempt was along the lines of

```python
import ifcopenshell

def filter(ifc_in, ifc_out):
    f = ifcopenshell.open(ifc_in)
    products = [x for x in f.by_type("IfcProduct") if "Something" in x.Name.lower()]
    print('Removing {} IfcProducts marked with "Something"'.format(len(products)))

    for x in products:
        f.remove(x) # Hm, this fails on second iteration
    f.write(ifc_out)
```

But, this fails on second iteration (maybe because original entity ID was invalidated?).

**Comment by aothms** [comment]
> Not really an issue

No this is an issue. The code you posted should work as is. The issue was that inverse relationships were not correctly updated (IfcOpenShell maintains an inverse mapping regardless of the official `INVERSE` attributes in the schema). Both products point at the same owner history, when processing its inverse relationships it was still trying to reference to first deleted product.

Do you compile the python wrapper yourself? Should be good to go with the latest fix.

**Comment by andersgb** [comment]
Oh, thanks for the quick fix. All good with latest master.

**Comment by sstevea** [comment]
Hello, I am also having a problem deleting entities.  In my case the problem is deleting entities that I have created myself.  The entities were created using the following code:

`import ifcopenshell
import uuid

file = ifcopenshell.open("temp2/IfcOpenHouse.ifc")

productToAddPropertyTo = file.by_id(189)

prop_set_guid = ifcopenshell.guid.compress(uuid.uuid1().hex)
property_values = [
file.createIfcPropertySingleValue("My own property", "Description of My Own Property", file.create_entity("IfcText", "some textual Value"), None),
file.createIfcPropertySingleValue("isMadeUp", "whether or not this is a made up valeue", file.create_entity("IfcBoolean", True), None),
]
property_set = file.createIfcPropertySet(prop_set_guid, productToAddPropertyTo.OwnerHistory, "MyOwnPropSet", None, property_values)
rel_guid = ifcopenshell.guid.compress(uuid.uuid1().hex)
file.createIfcRelDefinesByProperties(rel_guid, productToAddPropertyTo.OwnerHistory, None, None, [productToAddPropertyTo], property_set)

file.write("temp2/IfcOpenHouse_out.ifc") 
`

I then try to delete one of the 4 entities created as follows:

`import ifcopenshell

file = ifcopenshell.open("temp2/IfcOpenHouse_out.ifc")
toDelete = file.by_id(2877)

file.remove(toDelete)`

When I execute this in Spyder I get the message "Kernel died, restarting".  If I use this method to remove any entity other than the ones I created it works fine.  I have attached the IFC files before and after adding the entities.  Any help you can give would be much appreciated, thanks.


[temp2.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/2415122/temp2.zip)
