### ISSUE TITLE
Ifc Schema IFC2X_FINAL not recognized

### ISSUE THREAD

**Issue by nathalie-raffray** [IfcOpenShell/IfcOpenShell#2752]
This file fails to convert with IfcOpenShell since its schema IFC2X_FINAL isn't recognized. However I am able to visualize with other programs, such as BIMVision. 

When I change the schema inside the IFC file to IFC2X3 it works successfully.

[261110ADT-Smiley-West-5-Buildings-14-10-2005.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/10688960/261110ADT-Smiley-West-5-Buildings-14-10-2005.zip)

**Comment by aothms** [comment]
I don't think there will be an attempt to provide support for schema versions prior to ifc2x3. 

You might think that 2x3 and 2x are fairly compatible, but it's not really the case. Take note e.g of these kind of details:

> IFC2x Edition 3 CHANGE  All profile origins are now in the center of the bounding box. The attribute CentreOfGravityInX has been made OPTIONAL. Upward compatibility for file based exchange is guaranteed.

https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcprofileresource/lexical/ifcushapeprofiledef.htm

In other words, in 2x3 some behaviour regarding profile positioning has changed, but since the documentation for 2x is not recoverable, we don't know exactly how.
