### ISSUE TITLE
Weight qto is not calculated based off material MassDensity

### ISSUE THREAD

**Issue by arunkvijay** [IfcOpenShell/IfcOpenShell#2758]
Hi,
I am trying to define the `MassDensity` in `PSet_MaterialCommon` and assign the same to `IfcMaterial` defined in my ifc file. My goal is to get the GrossWeight and NetWeight Properties through, say for ex., `Qto_ColumnBaseQuantities`.
Currently, I am able to assign density of the material, however, while populating the Ifc Object Quantity Sets, the weights are not calculated as is shown as 0.0

**Comment by vulevukusej** [comment]
Hey @arunkvijay I don't think weight is calculated yet, right @maxfb87 ?

**Comment by maxfb87** [comment]
Yes, weight is not calculated afaik.
At the moment, weight is just a property, independent from density and volume.
I"m still thinking about how to create custom properties defined by a rule (for example weight = density x volume)

**Comment by vulevukusej** [comment]
Shouldn't be too difficult though, you'd just to check that the units are compatible or convert accordingly.

**Comment by maxfb87** [comment]
There is something i don't know how to approach... for example, have i to define a new pset with the custom properties(something like "DerivedPset")? Also, i would define every derived property with 3 columns: name, rule and value but i don't know if this is correct, maybe there is something better... i don't know, i'm still confused :-/

**Comment by arunkvijay** [comment]
I was referring to this [post](https://forums.buildingsmart.org/t/confusing-documentation-on-ifcmaterialproperties/2253/3) by Moult on a similiar issue. Here the `IfcMaterialProperties` from `Pset_MaterialCommon` do appear to be linked to `ifcMaterial` and then to the element through `IfcRelAssociatesMaterial`

As an example, the [Qto_SlabBaseQuantities](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/Qto_SlabBaseQuantities.htm) has 'IfcQuantityWeight` defined as 
> It is normally derived from the physical properties of the element under the specific measure rules given by a method of measurement

similar to any other `IfcQuantityLength` or `IfcQuantityArea` or `IfcQuantityVolume`

I am also confused on this and not sure if my understanding is correct too.

**Comment by maxfb87** [comment]
So, i'm not an expert but i tried to better understand the issue.
@arunkvijay: like what is written in the post you linked, a material can have properties, like an object can have properties.
Following your case, there could be a material named "Steel" that can have a Pset associated to it named "Pset_MaterialCommon" that have a defined property named "MassDensity" that have defined value (for example 10).
Similarly, there could be an object "IfcBeam/Beam1" that has a Pset associated to it named "Qto_BeamBaseQuantities" that has a defined property named "GrossWeight" that has a defined value (for example 50).
Also, the object "IfcBeam/Beam1" can be associated with the material "Steel", but this, afaik, doesn't mean that "MassDensity" is related to "GrossWeight". These properties are _independent_.

The only thing that can be done is to _calculate_ the "GrossWeight" value, like @vulevukusej suggested.
At the moment, "GrossWeight" can't be calculated automatically (like volume or height for example) but ... now i understool also @vulevukusej suggestion and i agree with him that calculating the GrossWeight can be done,  multiplying "MassDensity" with "Volume" checking the unit of measurement ... in my previous answer i was thinking about a more generic way to define automated custom properties, but, in order to solve this issue, it is not necessary.

So, i think i can try to implement this function, i'll keep you updated :-)

**Comment by maxfb87** [comment]
Hi, with this commit
 https://github.com/IfcOpenShell/IfcOpenShell/commit/93519c1c6398087817bd59a7407d8c3a37b7364e

the feature has been added.
There are some restrictions btw, but it is a start :-)
