### ISSUE TITLE
BlenderBim-230213 - Adding Door or Window does not create IfcOpening

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2765]
![image](https://user-images.githubusercontent.com/78321676/218399675-d62aed7d-b3ca-419b-9c01-c9368dcd2c7b.png)
Door and/or Window do not create IfcOpening when being added to wall

**Comment by Andrej730** [comment]
Can you help reproduce it? Just tried it with demo library wall, door and window and it works.

Are you sure you're selecting the wall before adding door and window?

![image](https://user-images.githubusercontent.com/9417531/218423775-51a9e51b-e52d-4714-b25d-7d1ea147377f.png)

**Comment by Plae-Blue-Dot** [comment]
Yes I am selecting the wall before adding
I've tried it on Blender 3.3LTS and 3.4
both give the same result:
![image](https://user-images.githubusercontent.com/78321676/218426188-14ce2cc9-8e29-427b-b16f-c4083920e524.png)

I am using millimetres as my default unit, it seems when I switch to metres it resolves the issue:

![image](https://user-images.githubusercontent.com/78321676/218426716-c31f75be-4a8f-4ece-b443-fbbbeb07f7b8.png)

**Comment by Andrej730** [comment]
Caught it - basically openings were there but just very small 😅 Fixed in e088a10aa
![image](https://user-images.githubusercontent.com/9417531/218430701-abfec950-aaba-4696-97e0-5e0231a8a25c.png)

PS wish there was automatic way to check all those different unit size bugs but for now
<img src="https://user-images.githubusercontent.com/9417531/218434148-d9e518bb-e1d8-4a84-bbcc-cca1ab163434.png" width=50% height=50%>

**Comment by Plae-Blue-Dot** [comment]
Hahahah thanks @Andrej730 , for now I am your auto check until further notice

**Comment by Moult** [comment]
D'oh that was my bad! I keep on screwing this up.

There are very few unit tests for the modeling module. It's on the todo list to add a basic list, maybe they should be written always with millimeters that way we can catch them.
