### ISSUE TITLE
Door Modifier Origin

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#2784]
Attempting to add doors with the type manager/modifiers:

The door origin is slightly shifted so when placing doors, a cavity appears on walls as result:
![image](https://user-images.githubusercontent.com/79010126/219616558-831377c1-ba50-47a9-8abc-625a5b0fd66d.png)

**Comment by Moult** [comment]
@myoualid does this door 1) have an overlapping lining and 2) do you have a Model/Profile/ELEVATION_VIEW context in your project? That will determine how this is solved.

**Comment by Andrej730** [comment]
Opening height is also incorrect:

![image](https://user-images.githubusercontent.com/9417531/219853930-9be54ddc-be6f-4471-b417-2241b1afcfcd.png)

Doors have some casing overlap over the wall - so adding new door with BIM Tool sets opening dimensions incorrectly because it's Blender object dimensions based.
Adding `Model/Profile/ELEVATION_VIEW` context to the project or reapplying modifier (start and finish modifier editing when opening are recalculated) solves the issue.

As a solution we can check somewhere in the code below whether filling has `OverallWidth` and `OverallHeight` properties and use them for the opening `x` and `z` dimensions. 

https://github.com/IfcOpenShell/IfcOpenShell/blob/ab9a4856abf34ef5d1b89101c45c330b8cbee6a3/src/blenderbim/blenderbim/bim/module/model/opening.py#L225-L232

Not sure if it's a good idea to apply that idea to all objects or use it only for doors and windows for now (windows modifier currentlydon't have casing but some other windows might have it). What do you think?

![image](https://user-images.githubusercontent.com/9417531/219854370-94779c09-a235-4955-839f-1cd17dd0571d.png)

**Comment by Moult** [comment]
Yes in that case there are two possible solutions here, maybe both should be done:

 1. As you suggest, if we detect an OverallWidth/OverallHeight, prioritise that before falling back to the filling_obj.dimensions
 2. If we do fall back to filling_obj.dimensions, make sure the position correlates is offset accordingly with min_x (only local X direction, ignore Y and Z I think). I have a suspicion that right now it's just placed at the local origin.

**Comment by myoualid** [comment]
> @myoualid does this door 1) have an overlapping lining and 2) do you have a Model/Profile/ELEVATION_VIEW context in your project? That will determine how this is solved.

@Moult I have no idea about the lining, I'm just a civil engineer, wannabe architect, simply trying to add a door to a wall :D For this example I simply created this door type with the default options from the door modifier & then added the doors to the wall. I have not manually added any contexts apart from those existing in the template

**Comment by Moult** [comment]
Hehehe no worries @Andrej730 answered my question for me. I guess a third thing we can fix too is 3) add Model / Profile / ELEVATION_VIEW as one of the default contexts we start new projects with.

@Andrej730 if all this makes sense do you think it's something you can help tackle? Note that fixing the third will also likely require updating a bunch of tests.

**Comment by Andrej730** [comment]
@Moult sure!

I've noticed something fixing this issue. With windows and doors we have some divergency with ifc specs - ifc Types doesn't have OverallWidth and OverallHeight, Types are kind of defnining overall lining and panel properties but not the actual size of the thing (which is kind of contradicting with having transom and mullion offset but that's another conversation...).

But in BlenderBIM all occurences of windows and doors share the same overall dimensions too and it's not possible to create two windows of the same type but with different width or height. So, now to keep all OverallHeights and OverallWidths in sync I for-loop through all type occurences every time representation changes. 

Not sure if it's an issue really, just wanted to note.

<img src="https://user-images.githubusercontent.com/9417531/219856945-9edac7a1-8047-4144-be37-1df9aff70e10.png" width=75% height=75%>
<img src="https://user-images.githubusercontent.com/9417531/219856964-82294771-694c-447b-a9c9-425fbd566b01.png" width=75% height=75%>

**Comment by Andrej730** [comment]
>If we do fall back to filling_obj.dimensions, make sure the position correlates is offset accordingly with min_x (only local X direction, ignore Y and Z I think). I have a suspicion that right now it's just placed at the local origin.

The position is correct - it's the same as window's position and it's placed at the beginning of the opening, not the beginning of the casing. 

Or do you mean to correct the opening position with `min_x` like in the example below? Sounds reasonable. But we probably should take `min_z` into account too (for example if there was casing at the bottom of the window). But not sure if we should apply that correction if `min_x` > 0 or `min_z` > 0.

```python
min_x = min([v[0] for v in obj.bound_box])
min_z = min([v[2] for v in obj.bound_box])
obj.location = obj.location + Vector([min_x, 0, min_z)
```

**Comment by Moult** [comment]
Ah yes good point min_z should be considered too. I think the fallback bounding box dimensions generation should encompass the entire shape in the X and Z axes. So I think the dimensions are right, but the opening position should slide to wherever min_x/min_z is, regardless of >0 or <0.
