### ISSUE TITLE
Build time tripled 

### ISSUE THREAD

**Issue by Amoki** [IfcOpenShell/IfcOpenShell#2802]
Hello,

We're updating our IfcOpenShell version from e508fb44 (Jun 2, 2022) to the latest and the build time went from ~2 hours to 5 hours on the same computer. We use `build-all.py` and the parameters didn't change.
The build of occt, swig, cgal, etc don't seem to take longer than before, but the build of IfcOpenShell (binaries and python wrapper) is way longer.

Is it normal? Is there new feature taking long to build we could disable?

Thanks!

**Comment by aothms** [comment]
This is likely due to the increased number of schema versions. You can
configure them in cmake using SCHEMA_VERSIONS. Due to the structure of the
project code generated for a schema is rather significant. In 0.8 this will
be somewhat improved because we will not do geometry interpretation for
every schema version individually. (Also splitting the geom code into
smaller files actually had a negative impact on compulsion time..)

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op do 23 feb. 2023 09:24 schreef Hugo Duroux ***@***.***>:

**Comment by Amoki** [comment]
Thanks, I'll look at it!
