### ISSUE TITLE
SVG serialiser creates empty group elements

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2822]
It seems as though the SVG serialiser creates empty group elements even if the element is never cut in section (i.e. it is only seen in projection), like this:

```
<g id="product-9c3e7347-d879-4dd7-80c3-5ac65104beff-body" class="IfcActuator" ifc:name="Cube" ifc:guid="2SFdD7s7bDru33MiPH1Bx$" >
"/>
        </g>
```

If it were cutting through, then we'd get a path like expected:

```
<g id="product-9c3e7347-d879-4dd7-80c3-5ac65104beff-body" class="IfcActuator" ifc:name="Cube" ifc:guid="2SFdD7s7bDru33MiPH1Bx$" >
            <path d="M240,260 L240,240 L260,240 L260,260 L240,260"/>
        </g>
```

Shouldn't it only create a group when there is actually an element? And are there scenarios where there will be more than one path in a group?

**Comment by aothms** [comment]
I'm not surprised to see this issue, but still I have a hard time reproducing this. Can you give an example?

I made a promise to myself never to build an xml file by concatenating string, but here I am.

The biggest problem with this codebase is that at first is was strictly following the serializer paradigm (one element in IFC corresponds to 1 element in SVG (like the 3d or xml format)) but since then it changed drastically and it's really hard to oversee all different code paths.

> And are there scenarios where there will be more than one path in a group?

I would be tempted to think so. I think it would roughly correspond to representation items.

Note they are also not necessary path nodes. `<circle>` and `<ellipse>` are also possible.

**Comment by Moult** [comment]
This file should reproduce the issue, it has one drawing and one cube not being cut.

[empty-groups.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10894411/empty-groups.ifc.txt)

**Comment by aothms** [comment]
Thanks, not sure why I wasn't able to reproduce it, maybe it was only for the explicit drawing objects (which I find hard to believe tbh) Anyway should be fixed now.

**Comment by Moult** [comment]
Closing assumed fixed.
