### ISSUE TITLE
BlenderBIM - UI Visibility Preferences do not reapply on launch.

### ISSUE THREAD

**Issue by oeykmiih** [IfcOpenShell/IfcOpenShell#2825]
Steps to reproduce the bug:

1. in BlenderBIM Addon Preferences change UI visibility.
2. Restart Blender
3. the Preferences reset! :(

Expected Result: BlenderBIM visibility preferences saved over different sessions.
Actual Result: BlenderBIM visibility preferences resets on every session.

![230212_201820](https://user-images.githubusercontent.com/69322448/222447427-6f0b4097-33b6-4363-a77c-3dd71f63961b.gif)

**Comment by Moult** [comment]
@vulevukusej maybe one for you?

**Comment by vulevukusej** [comment]
I won't have time for at least a couple of months unfortunately.

**Comment by maxfb87** [comment]
@oeykmiih i think that this is not really a bug... you can save the visibility status with File -> Defaults -> Save Startup File .
In this way, every time you start a new fresh file, the visibility configuration is what you have saved.
On the other hand, if you are working on a file, the session is stored in the .blend file.

Your video btw shows an error on the console: i tried to investigate and it seems that the error is that a not visible module is unregistered 2 times (when the it becomes unvisible and on the blender exit) ...

**Comment by Gorgious56** [comment]
As @maxfb87 said this is not a bug since the system was designed to store the parameters on the active Scene, so the visibility states are stored per file. Or more exactly, per scene. At least theoretically since there is no callback to actually change the enabled tabs to reflect the current scene properties on scene change. Also, the BlenderBIM addon is not designed to support multiple scenes per file as far as I know (like most addons, since we can't efficently store settings per file, we have to use the current scene, but that is another debate...). 

It is arguably misleading to have this feature accessible from the addon preferences which are usually where blender-wide settings are displayed. Maybe the solution is to move the visibility popup into the BIM scenes properties panels, that way it is clear these are settings that belong to the current scene.

**Comment by maxfb87** [comment]
@Gorgious56 it is a good suggestion but honestly i don't imagine where it could be moved...

Have you seen the related bug about already unregistered module? I have done also a PR to solve it but i don't know if it correct. Have you got any ideas?

**Comment by Moult** [comment]
Agreed, this is not actually a bug.
