### ISSUE TITLE
IFC attributes

### ISSUE THREAD

**Issue by Judithlourde** [IfcOpenShell/IfcOpenShell#2826]
Is it possible to get Ifc attributes from API?
https://wiki.osarch.org/index.php?title=IFC_attributes_and_properties.

**Comment by Judithlourde** [comment]
Thanks for the reply. I am only using your API as an end-user on the client side, not familiar with backend coding.

**Comment by aothms** [comment]
> I am only using your API as an end-user on the client side

Can you clarify what you mean here? Which API which language?

**Comment by Judithlourde** [comment]
> This one, 

https://bs-dd-api-prototype.azurewebsites.net/swagger/index.html
Is it possible to get attributes like properties as well?

**Comment by aothms** [comment]
I think you'd better recreate your issue here https://github.com/buildingSMART/bSDD/issues/

IfcOpenShell is a specific open source software module for mainly IFC (but we do have modules for IDS bSDD mvdXML etc.).

Coincidently I was involved though in the data generation for the bSDD API and the issue here is that most of the IFC attributes are very specific types. Think for example of the geometric representation of an element. There is no way that we can in bSDD represent the domain of those kind of attributes. Others are more like simple values (such as RefLatitude on IfcSite), but express the value as a list of integers, making a direct mapping also somewhat difficult. That's the background. What information are you missing specifically?

**Comment by Judithlourde** [comment]
Ok, I will do that.

I am quite new to the IFC world. When I am fetching data for example: 
https://identifier.buildingsmart.org/uri/buildingsmart/ifc-4.3/class/ifcDoor. It gives properties like Pset, Qto, and Attributes. But attributes do not contain names, owner history, and so on mentioned here https://identifier.buildingsmart.org/uri/buildingsmart/ifc-4.3/class/ifcDoor.
This information I am missing.

**Comment by Moult** [comment]
Thanks for posting upstream, it is not something we can solve on our end unfortunately: https://github.com/buildingSMART/bSDD/issues/48

**Comment by Moult** [comment]
A note @Judithlourde that you might want to consider learning a bit of Python just to use some of the utilities, because they can very easily get you attribute and property lists that you're after. https://blenderbim.org/docs-python/ifcopenshell-python/hello_world.html will help you get started.

**Comment by Judithlourde** [comment]
Thank you very much!
