### ISSUE TITLE
Memory Leak when exporting/saving IFC Project causing IFC export failure/non-termination

### ISSUE THREAD

**Issue by flashsturz** [IfcOpenShell/IfcOpenShell#2845]
**Issue:**
---
When I load an .ifc file into blender using blenderbim, the contents are displayed as expected. I can make changes (e.g. delete some elements).
But when I want to save/export the changed .ifc data, blender seems to be stuck in an endless loop including a memory leak (e.g. the export function is running for a veeeery long time, with constantly increasing memory utilization, until the PC is OOM, where the export fails.
The .ifc model I want to modify is originally ~120 MB size, so not really gigantic. (Unfortunately I cannot share the .ifc model)

I do not get an error message in the blender terminal window, so I am unsure about what might cause this issue.
There don't seem to be many complaints about the IFC export being slow or causing a memory leak, so I am not really sure where the error might be.

**Possibly connected issues:**
---
- GeomIterator Memory Leak: https://github.com/IfcOpenShell/IfcOpenShell/issues/2653 and https://github.com/IfcOpenShell/IfcOpenShell/issues/2704
- BlenderBIM IFC Export on OSArch: https://community.osarch.org/discussion/687/blenderbim-ifc-export and https://community.osarch.org/discussion/37/blenderbim-problems-to-export-ifc

**What I tried:**
---
- The issue persists on both Windows and Linux. I also tried with a completely new installation, with only blenderbim as add-on.
I am on Blender 3.4.1 with the blenderbim add-on version 230304.
- I tried both the *Save Project* button in the IFC control panel as well as *Export-> .ifc* from the *File* menu section.
- I attempted the approaches discussed in the links and sublinks provided above in the connected issues section. No luck so far.
- The points discussed about[ large models](https://blenderbim.org/docs/users/dealing_with_large_models.html) did not resolve the issue.

**Comment by Moult** [comment]
I don't think this is due to a memory leak problem. It's very hard to debug this unless I have your file unfortunately and can see what it's trying to do, and know how you're trying to modify it. You can send your model to dion@thinkmoult.com if it's private, and / or we can screenshare during the debug session so you have peace of mind that I delete it immediately.

Can you describe more what you're doing to edit? Are you moving geometry? Changing geometry? What type of geometry is it? Meshes? Solids? How many objects? Have you tried an immediate load and save-as without any edits? How long does that take?

**Comment by Moult** [comment]
A number of fixes have been made to export time syncing which could've probably caused this. I'm closing this, unless @flashsturz can help retest to make sure this is still relevant.
