### ISSUE TITLE
BlenderBim - feature request - slab/covering edit line to match profile position in profile mode

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2873]
At present the slab/covering editing tool preserves the length of the slab when at an angle.

So if a 1m slab has a 5deg angle it ends up having a cover of 996mm along it's length from an overhead plan:

![image](https://user-images.githubusercontent.com/78321676/225575385-18ab3832-25a2-4277-8be0-a72267f7ec4d.png)

However when editing, the desired effect is that the profile covers what is seen from above and how it currently works makes the tool difficult to use for angled slabs/coverings

Example one: how it works now
Attempting to line up a roof ridge with two angle slabs

model before editing:
![image](https://user-images.githubusercontent.com/78321676/225576576-e677d22b-5135-4fbb-ad24-7be7d8ca49a9.png)

editing profile to line up:
![image](https://user-images.githubusercontent.com/78321676/225576655-4750639f-c458-463f-a71b-aacbf8fd40b5.png)

result does not line up:
![image](https://user-images.githubusercontent.com/78321676/225576775-bd58f44b-8b01-4ea4-9659-d5aeee489643.png)

In this example it is small but the bigger the roof the bigger the gap

Would it be possible to adjust the tool to have both options? Sometimes I want a roof that is the exact length of a sheeting and for how the tool works currently that is prefect, but a lot of the time I need a fixed overhead distance and roof line and it's very difficult at present to do that

I'm getting around this by using pythag so not essential but it's just slow

**Comment by Moult** [comment]
From an overhead plan, yes, but I guess there is an assumption that the +Z is what applies to the slab (which it does in most cases, but perhaps not all?).

The appropriate way is to actually edit the profile in 3D instead of from above I think. You might like to check out the CAD Tool in edit mode which has extend and trim functionalities which make stuff like this pretty easy to model. In this demo I create a few temporary construction lines then use the trim tool (but maybe the extend tool will look less weird) ... does that help?

![Peek 2023-03-16 21-46](https://user-images.githubusercontent.com/88302/225594695-efbb0437-4861-44ef-a463-820dded0032a.gif)

**Comment by Moult** [comment]
Here's another way with the extend CAD tool.

![Peek 2023-03-16 21-52](https://user-images.githubusercontent.com/88302/225595733-52a36b69-98da-4ea6-a1e3-c38df4ae15d6.gif)

Or another way with edge sliding and snapping.

![Peek 2023-03-16 21-53](https://user-images.githubusercontent.com/88302/225595762-baa7e88f-5d0c-436c-b86e-054b59740f7f.gif)

**Comment by Plae-Blue-Dot** [comment]
That's perfect actually Moult thanks so much, the edge sliding I didn't think to use in that mode, that will probably be my go to!
