### ISSUE TITLE
Seems `{{material.Name}}` is not working in the IFC text literal. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2881]
Might be doing something wrong, but doesn't look like `{{material.Name}}` is working in the IFC text literal. 

video: https://www.dropbox.com/s/ji7xae7yv3s9vp3/2023-03-19_13-11-07_Blender_%5BCUsersOwnerDesktopuntitled.blend%5D_blender.mp4?dl=0

**Comment by theoryshaw** [comment]
There was a product assigned to that text.  In the first part of that video `{{material.LayerSetName}}` worked, but `{{material.Name}}` did not.

Or perhaps i misunderstood you.

**Comment by Moult** [comment]
Yeah this is due to a clean up of the selector. Previously, `material` would fetch either the assigned material, and if that was a material set, it would then also select ... arbitrarily one of its materials in its set items. That to me is pretty poor (i.e. random) behaviour and it showed in the code ... the code was pretty nasty in that area.

So LayerSetName works because that's the actual attribute of the material layer set whereas Name doesn't exist.

So... this begs the question, how should we redesign it so that you could select a material set item within a material set, or a material within a material set item within a material set? What would you intuitively expect to appear if you typed `material.Name`?

I think @mdjska (or someone else?) brought up the same issue in the OSArch chat, I asked if she could help design an intuitive syntax to select subparts of a material set. Maybe she has a solution?

**Comment by mdjska** [comment]
I think your approach could be fine. I find it maybe a tad confusing that material sets would also be called/fall under material in this scenario. When I looked at it a couple of weeks ago, I thought of something like this:
- If you type `material.Name` and it is a single material - you just get the material name
- If it is a material set - you get a list of all the materials included in the material set. Following the logic in https://github.com/IfcOpenShell/IfcOpenShell/pull/2503, so `material`= (single) IfcMaterial.
- `materialset.Name` gives the name (or other attributes) of the material set, no matter if its a layer set, profile set or constituent set.
- `materialset.item.Name` gives a list of names of all items. `materialset.item[0].Name`/`materialset.item[-1].Name` to get the first/last item names
- `materialset.material.Name` would be the same as `material.Name`. If there are multiple items, it gives a list of all. 
- `materialset.item[0].material.Name` gives the material name of the first item. (I don't think you can have multiple materials pr. one item, but in case, you could do `materialset.item[0].material[0].Name`)
- As fas as I know, a material in a material set, will always be added through an item, so it wouldn't make sense to have `materialset.material[0].Name` (because it wouldn't know which item to choose, so instead you would do `materialset.item[0].Material.Name`, but maybe you could say `material[0].Name` since `material.Name` would be a flat list of all materials in a set. 

But this was just something I thought of with the use case of material quantity take-off in mind, it might be too complicated/complex for other use cases. So feel free to disregard this and go with a simpler approach.:)

**Comment by Moult** [comment]
`mat.i.Material.Name`

It returns a list, so afterwards you can use regular Python list indices like [0].

**Comment by theoryshaw** [comment]
cool. `{{mat.i.Material.Name}}` works, but this doesn't `{{mat.i.Material.Name[0]}}` 
I'm probably missing something obvious.

**Comment by Moult** [comment]
``{{mat.i.Material.Name}}[0]``

**Comment by theoryshaw** [comment]
Thanks!
summarized it here:
https://wiki.osarch.org/index.php?title=BlenderBIM_Add-on_Adding_labels_linked_to_properties_and_quantities

**Comment by mdjska** [comment]
Seems like using `item`doesn't work in the IFC CSV panel, but maybe you don't need it there? Also is it possible to use indexes there? I couldn't get it to work
