### ISSUE TITLE
Void not added to roof element

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#2887]
Steps to create:

Select roof element
Add void
Position void in roof (void created at 0,0,0)
Select void and roof
Add void to roof element
**Void not addded**
Show void in roof element
Apply void

Following error is received: -

Python: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/tool/ifc.py", line 122, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/ifc.py", line 427, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/module/model/opening.py", line 696, in _execute
    element = tool.Ifc.get_entity(obj)
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/tool/ifc.py", line 76, in get_entity
    props = getattr(obj, "BIMObjectProperties", None)
ReferenceError: StructRNA of type Object has been removed

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/26485679/226537907-ef09f9c0-a74c-49a0-bdaf-e4a6181f8c2f.png">

**Comment by Andrej730** [comment]
Tried and couldn't reproduce the error.
1) Is there any errors in console after you try to add void to roof element?
2) Can you share .blend/.ifc files for debugging?

**Comment by Moult** [comment]
I can recreate a similar issue where for meshes only the representation is not updated prior to adding the void, but it doesn't result in the error message you've gotten (though it does revert to an outdated representation, so it's still a bug... but not _your_ bug). So +1 to @Andrej730 , can you help provide instructions / files to reproduce?

**Comment by ChubbyQuark** [comment]
This is the console error. You're right, the mesh seems to convert to another representation before the error.

Export finished in 0.28 seconds
Done creating geometry
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/tool/ifc.py", line 122, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/ifc.py", line 427, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/module/model/opening.py", line 696, in _execute
    element = tool.Ifc.get_entity(obj)
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/tool/ifc.py", line 76, in get_entity
    props = getattr(obj, "BIMObjectProperties", None)
ReferenceError: StructRNA of type Object has been removed
Error: Python: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/tool/ifc.py", line 122, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/ifc.py", line 427, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/bim/module/model/opening.py", line 696, in _execute
    element = tool.Ifc.get_entity(obj)
  File "/Users/user/Library/Application Support/Blender/3.4/scripts/addons/blenderbim/tool/ifc.py", line 76, in get_entity
    props = getattr(obj, "BIMObjectProperties", None)
ReferenceError: StructRNA of type Object has been removed

**Comment by Andrej730** [comment]
It seems to be the same log from attempt to show the voids you've sent earlier.

Can you please check if there is any errors when you hit "Apply void"?

**Comment by ChubbyQuark** [comment]
After hitting 'apply void' the void disappears, with not cut in the roof element.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/26485679/226821684-a738a0aa-ab80-4145-bdb2-8d69b8f2a135.png">

Nothing in the consoles after applying but hitting the eye icon and then the tick icon produces the error above.

**Comment by ChubbyQuark** [comment]
The roof element seems to have lost representations, if body context is re-applies the void cuts as expected: -

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/26485679/227040848-06334812-ea7d-4be4-862b-51177bb9755f.png">

**Comment by Moult** [comment]
There seem to be three issues:

 1. Somehow the object had a Model representation assigned which is not something we wish to support. This is most likely due to bad UI design on our end which makes it possible to users to unintentionally create those representations.
 2. It is not currently possible (it was in the past, but removed for performance reasons) to edit voidless meshes, which therefore can ensure that meshes are updated before voids are repositioned.
 3. It seems to be possible to create multiple temporary openings of a single object via a UI oversight.

**Comment by Moult** [comment]
The commits introduces a new override for hitting the "Tab" key (i.e. toggling edit mode), which does a few things specific to mesh representations. this is potentially a big nasty breaking change so keep an eye out for weird behaviour 🙂

 1. does not allow you to enter edit mode for parametric objects (e.g. walls, beams which have parametric definitions) since that would then allow you to change the mesh to something invalid
 2. it calculates a quick checksum of the current verts/edges/faces so then when you toggle back to object mode,it knows whether you've actually made changes / edited the mesh or if you've just toggled the modes. this is very powerful and we can use it for all sorts of things later on.
 3. if it is a mesh object (i.e. you are allowed to go into edit mode) then it regenerates the mesh without opening booleans, this way you can edit the unbooleaned mesh. this is pretty critical.
 4. when toggling back into object mode, you are given the option to save your changes / discard changes. save will update the IFC immediately, whereas discard will revert to the previous state. this will help improve save performance (previously, we assumed anything you toggled edit mode was edited and updated it all which was very, very inefficient)
