### ISSUE TITLE
BlenderBIM - Material Property Sets get overridden

### ISSUE THREAD

**Issue by mdjska** [IfcOpenShell/IfcOpenShell#2898]
When creating multiple IFC materials, material property sets doesn't get properly duplicated, so they end up "sharing" the pset. Procedure to replicate:
- Create two IFC materials
- Give one of them a pset with a certain property value
- Go to the other material and give it the same pset & property but with a different value
- Go back to material 1 - the value has now been changed to the same as in material 2

Another little thing is that using the "New Material" button in material tab (the one that looks like a copy of two files) only copies the Blender material. Seems that a new IFC material is not being made and the same issue as described above with psets, happens with other attributes/material info. The only thing that fixes that is to:
- Make a new material with the "New Material" button
- It appears with an IFC material already present (which is presumably the old material not being copied properly)
- Remove and unlink IFC material
- Create a new IFC material

This works for creating a new, separate material with its own attributes, but it doesn't fix the property set issue.

**Comment by Moult** [comment]
So the first bug is more of an illusion that we don't redraw the UI, that's now fixed.

As for the second, there are a few built in Blender features that we simply can't override until Blender lets us in a future version :) So the best we can do is provide another button elsewhere that we rely on users to press (or if there is a common hotkey, we override the hotkey) instead of the built-in Blender version. I've now added a new feature to copy the material in the IFC Material panel which should do what you're intending to do.

**Comment by mdjska** [comment]
Nice, it seems to mostly work now. There is still a slight issue of the psets only updating if you click on another element and go back, but not if you just change the material.

https://user-images.githubusercontent.com/16716147/228822454-e9cc321c-181b-451e-8faf-5c3bfb265de9.mp4
