### ISSUE TITLE
BlenderBim - Sliding door -  request

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2919]
The new sliding door modifier is very awesome!

Works great and intuitive!

![image](https://user-images.githubusercontent.com/78321676/228774879-0da9442c-3de0-4bf5-83a9-073b74e59e2e.png)

My request is if it would be possible to include a little arrow indicating the direction of the slide?

I'm not certain if it's not used internationally but we use it as a 2d indicator similar to the door swing of a swing door

![image](https://user-images.githubusercontent.com/78321676/228775389-3af5f1fd-be0d-4c8b-89f8-851ec92e09cc.png)

This can always be added as an annotation so not an essential feature

**Comment by Moult** [comment]
Indeed, @Andrej730 the arrow should be added to the Plan/Annotation/PLAN_VIEW context.

**Comment by Andrej730** [comment]
Added an arrow.

@Moult shouldn't it be `Plan/Body/PLAN_VIEW`? We don't use `Plan/Annotation/PLAN_VIEW` for the door.

**Comment by Moult** [comment]
@Andrej730 I also noticed that in this case the door panel is drawn as a line, it should be drawn as a rectangle. It should be no different to other 2D door bodies except that the door panel should be offset by 1/2 of its width in the direction of the slide.

**Comment by Andrej730** [comment]
@Moult fixed.

It was based on the one from [IfcDoor page](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcDoorTypeOperationEnum.htm)
![image](https://user-images.githubusercontent.com/9417531/229811201-67ac1e4d-6da5-43ac-8931-89f6a0d9f50b.png)

Previously:
![image](https://user-images.githubusercontent.com/9417531/229811320-3c5d0cbe-b6a5-4720-a8a0-d9564beb6c88.png)

Rectangle doors:
![image](https://user-images.githubusercontent.com/9417531/229811377-4f8d93fd-8618-4d24-b6b2-1f344e95323f.png)

Rectangle doors + offset 0.5 width instead of 0.3:
![image](https://user-images.githubusercontent.com/9417531/229811515-a715fd22-8ea1-40b2-bf58-593f47ae59e1.png)

**Comment by Moult** [comment]
Cheers, maybe a little explanation is warranted. In the hand-drawn days, depending on the scale of the drawing architects would draw doors (and other things) in a simple way. This is actually supported in IFC (contexts have a TargetScale, which we don't yet expose in the UI).

So what is shown in the buildingSMART docs is a very simplified representation (say for 1:200 and smaller). In practice, I'd say this is less relevant nowadays because the computer draws it for us.

So yeah, the sliding door should be drawn the same way as a regular door, so the 2D lining should be drawn the same way as a swing door. The only difference is that the panel instead of being 90 degrees, is offset 50% in the sliding direction (the exact offset percent is arbitrary).

In the future, sooner or later we need to add support for TargetScale but it isn't critical.
