### ISSUE TITLE
Circular shapes not supported in SVG conversion

### ISSUE THREAD

**Issue by andersgb** [IfcOpenShell/IfcOpenShell#292]
I'm using `IfcConvert` to get SVG 2D geometry from my IFC, but I'm struggling with circular shapes. I have boiled the problem down to [this IFC file](https://github.com/IfcOpenShell/IfcOpenShell/files/1450549/cylinders.ifc.zip). The converted SVG result is included below and will typically render nothing in browsers, or will give an error if loading into a validating SVG library. 

Since `SvgSerializer.cpp` uses `<path>` Arcs for circular segments, it will not give valid SVG output for *complete* circles. The SVG standard says `If the endpoints (x1, y1) and (x2, y2) are identical, then this is equivalent to omitting the elliptical arc segment entirely.` [source](https://www.w3.org/TR/SVG/implnote.html#ArcOutOfRangeParameters)

I guess complete circles should use `<circle>` instead of `<path>`. The same goes for a complete ellipse.

-----

`./IfcConvert --bounds 1024x1024 cylinders.ifc cylinders.svg`
```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="product-34d87c32-c3cf-11e7-8e5b-80193481049d">
        <g id="product-product-34d87c2c-c3cf-11e7-8e5b-80193481049d-body">
            <path style="stroke:black; fill:none;" d="M0,0 A256,256 0 0,0 0,6.27019e-14"/>
        </g>
        <g id="product-product-34d87c2d-c3cf-11e7-8e5b-80193481049d-body">
            <path style="stroke:black; fill:none;" d="M0,512 A256,256 0 0,0 0,512"/>
        </g>
        <g id="product-product-34d87c2e-c3cf-11e7-8e5b-80193481049d-body">
            <path style="stroke:black; fill:none;" d="M0,1024 A256,256 0 0,0 0,1024"/>
        </g>
        <g id="product-product-34d87c2f-c3cf-11e7-8e5b-80193481049d-body">
            <path style="stroke:black; fill:none;" d="M1024,0 A256,256 0 0,0 1024,6.27019e-14"/>
        </g>
    </g>
</svg>
```

PS: When creating this simplified cylinders.ifc, I discovered another related issue. The bounding box `(xmin, xmax, ymin, ymax)` used for scaling according to `--bounds` will not include circular shapes correctly. One circle gives a *point*, not a bounding rectangle. That's why I added 4 cylinders spread around, not just 1.

**Comment by andersgb** [comment]
BTW I tried looking at the SVG serializer code, seems like complete circles can be identified by `Geom_Circle` parameterized in the entire `[0, PI2]` range. But all of these OCC abstractions on geometry are not familiar to me, don't know what's the best approach to fix this.

**Comment by aothms** [comment]
> The SVG standard says If the endpoints (x1, y1) and (x2, y2) are identical, then this is equivalent to omitting the elliptical arc segment entirely

Ah, I wasn't aware of that. Many thanks for the detailed report and test case.

> parameterized in the entire [0, PI2] range

Probably [t, t+PI2] range, it doesn't need to start at zero I think. There is already an `fmod()` statement that does roughly this [1] but compares to `> PI` rather than `ALMOST_THE_SAME(PI2)`

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/SvgSerializer.cpp#L104

> The bounding box (xmin, xmax, ymin, ymax) used for scaling according to --bounds will not include circular shapes correctly

That's true. `growBoundingBox()` should probably be called with `conic->Position().Location() +- {r1, r2}` (at least in case of a full circle/ellipse) although in case of an ellipse it is a little bit trickier when rotated, probably `max(r1, r2)` along both axes is easier and good enough. Better be too conservative than too optimistic which is the case now. You could also sample the curve at regular or irregular intervals (e.g. `GCPnts_QuasiUniformDeflection`).

> But all of these OCC abstractions on geometry are not familiar to me, don't know what's the best approach to fix this.

Well you did all of the most important ground work, turning it into a Pull Request is within arm's reach from here. You can also wait for me to pick this up, but I have a bit of a back log. Also, a PR with the test case you created put here [2] would also be appreciated :)

[2] https://github.com/IfcOpenShell/IfcOpenShell/tree/master/test/input
