### ISSUE TITLE
rotate after 'extend' is a little weird. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2926]
rotate after 'extend' is a little weird. 

https://www.dropbox.com/s/slsoqxb88uu27do/2023-04-01_23-11-56_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
It's technically correct. By choosing extend, you are also creating a parametric connection that tells the beam to try to extend one end of it as best as it can to the other object. You can see it always attempts to clip at the wall.

Maybe ... it isn't very intuitive? Maybe after rotating we should clear all parametric connections since it's now going to be perpendicular and so in 90% of cases existing connections will no longer be relevant?

**Comment by theoryshaw** [comment]
In that case, i guess this 'glitch' is really not a big deal.  I guess, i would prefer keeping it as is, then.  Bigger fish to fry.
