### ISSUE TITLE
Outdated ifcopenshell version on PyPi

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#2932]
Just updated ifcopenshell from pypi and it's seems to be a bit outdated - the latest package is based on 476ab506d (15 Feb)
Even though wheel names suggest that the package is based on the repository from 29 March.

Current version from PyPi:

![image](https://user-images.githubusercontent.com/9417531/229508103-acc7a3e8-183d-4e60-aed0-e953ac8c1d71.png)

PyPi packages:

![image](https://user-images.githubusercontent.com/9417531/229508213-7ccf1823-e7b3-4f1f-9bc7-a1bf5c66bba4.png)

The last time @IfcOpenBot made builds on it's fork is also for 476ab506d0c6281f42dbc8bdb36c5cb1d98b525d, guess it's related.

![image](https://user-images.githubusercontent.com/9417531/229508868-2e91f82e-64aa-4e04-8a22-75ffe051052b.png)

**Comment by Moult** [comment]
Yep this is by design. PyPI simply "reships" the IfcOpenBot binaries but uses the latest Python code. It's documented here https://blenderbim.org/docs-python/ifcopenshell-python/installation.html#pypi

**Comment by Moult** [comment]
Just a heads up in case anybody finds this bug via search, it turns out that PyPI has a 10GB filesize limit per project. We hit that pretty quickly (each release is ~1GB - 4 operating systems x 6 Python versions). So unfortunately we'll have to manually delete older releases to keep our filesizes in check.

I also wonder whether we should continue to support Python 3.6 :)
