### ISSUE TITLE
IFC4

### ISSUE THREAD

**Issue by rubendel** [IfcOpenShell/IfcOpenShell#295]
Not sure if it's already supposed to be supported, but this looks like a very basic file, not using any of the new geometry types, but it does not seem to convert well.

[IfcPipeFitting-45.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/1456995/IfcPipeFitting-45.ifc.txt)

**Comment by aothms** [comment]
It is supported by an IFC4 build of IfcOpenShell, we really need to start shipping those with BimServer. Would you be happy with the plugin getting twice as big, i.e. two executables, or do we need to do that a bit smarter?

The problem here is indeed not the geometry, but the product class http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/schema/ifchvacdomain/lexical/ifcpipefitting.htm which is new in IFC4. So IfcOpenShell does not know it is a product it needs to generate geometry for.

An other way to fix this is to replace all product types (not in IFC4) with something generic before passing it to IfcOpenShell. But obviously IFC4 IfcOpenShell builds would be much better.

**Comment by rubendel** [comment]
Hmm it's already a pretty heavy plugin compared to the other plugins. A few other options:
- Download the executables on the fly (if a user never uses IFC4, no executable is downloaded). The downside is that there seems to be quite a (BIMserver) user base with no working internet connection (don't ask me)
- Extract the bulk to a library that can be reused by both versions, I would presume the biggest part is OpenCascade?
- Make a build that supports both schemas, no idea where the difficulty lies, can imagine this would be a lot of work

Your hack would work too and be easy to implement, but obviously won't work for the new geometry types.

**Comment by Moult** [comment]
Making an assumption here that this bug can now be closed since IFC4 is well supported now :D
