### ISSUE TITLE
Hole in doorstep on IfcDoor (see example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#297]
**Steps to reproduce:**
1. Convert [297--door--wrong-geometry--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/297--door--wrong-geometry--augmented.ifc)
2. Experience that the doorstep has a a hole:
<img width="1202" alt="gl-error-in-mesh-lab" src="https://user-images.githubusercontent.com/4601554/32725997-9bbc6b18-c877-11e7-97e9-c32bec3f4ab6.png">

In Solibri and DDS viewer the door opens without warnings and without a hole in the doorstep:
![dds_and_solibi](https://user-images.githubusercontent.com/4601554/32727135-b77e240a-c87b-11e7-828a-784de11e288d.png)

This happens on both of these versions of IfcOpenShell:
1. `IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev (OCC 7.2.0)` – built from commit 8d0c95a9391f887e262e95cec646dca2c59ceadf
1. `IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev (OCC 7.2.0)` – built from commit 6463690a8b76451e6cfeded340d75f05119f5ffd

Additional info (not 100% sure if this is related): From other conversions it may seem like when there are many doors of the same geometry placed around in a building, all of the doors get a vertex in one common point, leading to a seemingly "exploded geometry" in some web GL drivers (e.g. [Samsung Galaxy s7](https://www.gsmarena.com/samsung_galaxy_s7-7821.php):

![common_vertices_on_samsung_galaxy_s7](https://user-images.githubusercontent.com/4601554/32727030-5902b9ea-c87b-11e7-9238-e3d224f13745.png)

**Comment by aothms** [comment]
Odd, in my dev environment with occt 6.8 the door renders fine. Sorry it's taking a while to look into your issues. I need to allocate a good chunk of time for them, build occt 7.2., etc.

**Comment by johanrd** [comment]
Update: I have now tried with 5d0c04a, and the hole in the doorstep is still present with both OCCT v7.2.0 and OCCT v7.1.0 on Linux Debian (I have not tried with 6.8):
<img width="200" alt="screen shot 2018-02-26 at 16 54 16" src="https://user-images.githubusercontent.com/4601554/36680326-bdd26be4-1b15-11e8-8502-edafebd15831.png">

**Comment by aothms** [comment]
Ok, the issue appears to be that the bottom face is self intersecting, e.g. `#54` lies on the edge between `#43` and `#50`.

~~~
#53 = IFCPOLYLOOP((#43, #50, #54, #55, #56, #44));
#43 = IFCCARTESIANPOINT((407., -44., 14.));
#44 = IFCCARTESIANPOINT((395., -44., 14.));
#50 = IFCCARTESIANPOINT((-407., -44., 14.));
#54 = IFCCARTESIANPOINT((-395., -44., 14.));
#55 = IFCCARTESIANPOINT((-395., -92., 14.));
#56 = IFCCARTESIANPOINT((395., -92., 14.));
~~~

In this particular case OpenCascade's shape healing can fix this, because the offending edges are consecutive. I'm a bit worried about the performance implications of a general healing operation (including edge parametrization) after every loop creation (especially since explicit face based geometries already take a long time in IfcOpenShell).

~~~diff
diff --git a/src/ifcgeom/IfcGeomWires.cpp b/src/ifcgeom/IfcGeomWires.cpp
index ec59436..65c5b7c 100644
--- a/src/ifcgeom/IfcGeomWires.cpp
+++ b/src/ifcgeom/IfcGeomWires.cpp
@@ -443,7 +443,11 @@ bool IfcGeom::Kernel::convert(const IfcSchema::IfcPolyLoop* l, TopoDS_Wire& resu
        }
        w.Close();

-       result = w.Wire();
+       TopoDS_Face planar_face = BRepBuilderAPI_MakeFace(w.Wire(), true).Face();
+       ShapeFix_Wire fix(w.Wire(), planar_face, getValue(GV_PRECISION));
+       fix.Perform();
+       result = fix.Wire();
+
        return true;
 }

~~~

Regardless though the mesher should probably not emit invalid geometry, but I don't see that occuring. It seems there are more vertices emitted than referenced, but I don't think the "exploded geometry" is a natural consequence of that.

~~~xml
    <geometry id="representation-23">
      <mesh>
        <source id="representation-23-positions">
          <float_array id="representation-23-positions-array" count="18">0.852 0.03899999999999992 0.0139999999999999 0.03799999999999992 0.03899999999999992 0.0139999999999999 0.04999999999999993 0.03899999999999992 0.0139999999999999 0.04999999999999993 -0.008999999999999896 0.0139999999999999 0.84 -0.008999999999999896 0.0139999999999999 0.84 0.03899999999999992 0.0139999999999999</float_array>
          <technique_common>
            <accessor source="#representation-23-positions-array" count="6" stride="3">
              <param name="X" type="float"/>
              <param name="Y" type="float"/>
              <param name="Z" type="float"/>
            </accessor>
          </technique_common>
        </source>
        <source id="representation-23-normals">
          <float_array id="representation-23-normals-array" count="18">0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1</float_array>
          <technique_common>
            <accessor source="#representation-23-normals-array" count="6" stride="3">
              <param name="X" type="float"/>
              <param name="Y" type="float"/>
              <param name="Z" type="float"/>
            </accessor>
          </technique_common>
        </source>
        <vertices id="representation-23-vertices">
          <input semantic="POSITION" source="#representation-23-positions"/>
        </vertices>
        <triangles material="IfcDoor" count="1">
          <input semantic="VERTEX" source="#representation-23-vertices" offset="0"/>
          <input semantic="NORMAL" source="#representation-23-normals" offset="1"/>
          <p>3 3 4 4 5 5</p>
        </triangles>
      </mesh>
    </geometry>
~~~

**Comment by johanrd** [comment]
Hi. Ok, thanks, makes sense. The exploded geometry is, as you say, probably not directly related to ifcopenshell (I just added it as a symptom that may have been related).

**Comment by Stinkfist0** [comment]
Just a side note: in the past I noticed that e.g. Solibri goes above and beyond in order to show erroneous and/or poor geometry so it's not maybe the best reference viewer.

**Comment by aothms** [comment]
> Just a side note: in the past I noticed that e.g. Solibri goes above and beyond in order to show erroneous/invalid IFC/geometry so it's not maybe the best reference viewer

Well exactly, we were actually discussing this last week. In my opinion these fixes (deviations from standard compliance) in the long run will hurt interoperability as proprietary implementations over time will diverge.

On the other hand it might also just be that a mesh based viewers are generally more forgiving than full brep modellers so it actually takes time to write logic to reject geometry that violates the formal or informal propositions in the schema.

**Comment by johanrd** [comment]
Yes, that is very true: I'm not sure either whether Solibri's forgiveness is a curse or blessing for the construction industry:)

However, in this particular case both DDS, Solibri and SimpleBIM seems to agree.

**Comment by johanrd** [comment]
Closing, as this is not reproducible anymore when building from commit 1f68d9d5bcfda6ce6b7ff6e86733faf835247242 :tada:

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
