### ISSUE TITLE
build  structure using 2D coordonate

### ISSUE THREAD

**Issue by fotsing365** [IfcOpenShell/IfcOpenShell#299]
Hi every one.
   I would like to know if it possible to draw structure elements like walls, opening , ground and other just by indicating the 2D coordinates in X-Z plane of the contour points and the height along Y axis? For more understanding take a look on image in attached file
![capture](https://user-images.githubusercontent.com/24406778/32940541-3ac2de28-cb83-11e7-83c5-0f98f9c4d85f.PNG)
  If yes please could somebody show me how to? thanks

**Comment by aothms** [comment]
Hi,

Certainly something like this is possible. Have a look at the SVG serializer which essentially does exactly this:
https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/SvgSerializer.cpp

Kind regards,
Thomas

**Comment by fotsing365** [comment]
Thanks Thomas

**Comment by fotsing365** [comment]
Excuse me Thomas I have just read it. According to my C++ skill I have understood but I don't know how i could use it to build wall, opening, ground, space and other. Could you please show me an example  if you have one? Thank you

**Comment by aothms** [comment]
> build wall, opening, ground, space and other

What do you mean by that? Are you trying to create/export or read/import IFC?

**Comment by fotsing365** [comment]
I want to create a simple IFC with walls, floors, openings, spaces and roof having particular shapes like image above

**Comment by fotsing365** [comment]
I have seen the example IfcOpenHouse but it could not really help me because my structures don't have a pavement shape

**Comment by fotsing365** [comment]
after my search in the code I think it could be done using function
 IfcSchema::IfcProductDefinitionShape* IfcHierarchyHelper::addExtrudedPolyline(const std::vector<std::pair<double, double> >& points, double h, 
	IfcSchema::IfcAxis2Placement2D* place, IfcSchema::IfcAxis2Placement3D* place2, IfcSchema::IfcDirection* dir, 
	IfcSchema::IfcRepresentationContext* context) 
but I don't really  know how to. Please  could someone know how to use this function to create structural elements like walls, floors, spaces ? Thanks

**Comment by aothms** [comment]
Sorry for the late reply.

> my structures don't have a pavement shape

I don't understand what you mean by that.

One thing you still need to clarify is, do you want the IFC file to have 2d geometry? Or do you want extrusions of these 2d shapes? Ie. what do you want to see when you open the model in a standard IFC viewer?

If you start from the IfcOpenHouse example and stop around here [1]. I.e. it creates a 3d volume for the first wall, based on an extruded polyline and axis representation (both are nice to have for importing applications to reconstruct the element, see also [2]). How different is that from what you want?

Instead of `addAxisBox()` you can indeed also use `addExtrudedPolyline()` which does not include the axis representation.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/examples/IfcOpenHouse.cpp#L107
[2] http://www.buildingsmart-tech.org/implementation/ifc-implementation/ifc-impl-guide/ifc-impl-guide-summary

**Comment by Moult** [comment]
This is now possible with the variety of API functions available in IfcOpenShell-Python, so closing.
