### ISSUE TITLE
Set dimensions digits number

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#2993]
It would be nice to change the number of dimension digits like how it's described [here](https://community.osarch.org/discussion/1440/blenderbim-how-to-set-dimensions-digits-number).
Maybe something like the "IFC Text" menu available for IfcAnnotation[TEXT] objects?

**Comment by Moult** [comment]
Do you want to try and tackle this? It would be similar to https://github.com/IfcOpenShell/IfcOpenShell/commit/03d9efb79092f1e12e334057607cb19aa66a0b9d how we set a new property in EPset_Drawing to store digits, but most likely we'd store some sort of formatting string https://docs.python.org/3/library/string.html#format-specification-mini-language

**Comment by maxfb87** [comment]
Ok, thanks for the hint!
I just have done something, i'll do a PR.

**Comment by maxfb87** [comment]
@Moult i got the format method, but, maybe, it is simpler for user to input only an integer number that represents the number of digits after comma. It could be "decimals digits" value.
Indeed it's more flexible that the user can input a string representing the format, something like "%1.2f", but i think that it's not easy for an user to understand how to write the string format so it would be necessary to write also documentation about it and so on...
I would go only with a new integer property called "decimal digits" that represents the number of digits after the comma.
Is it ok for you?

**Comment by Moult** [comment]
Sure, go for it. I recall in highschool it was called "Decimal places" or "Decimal points", which I think is what you're after (as opposed to significant figures).

**Comment by c1symeon** [comment]
Can you ommit trailing decimal zeroes?  example 10.0 = 10  vs 10.1=10.1

**Comment by c1symeon** [comment]
ok! I modified the ...\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\helper.py file so that it does exactly this for cm units (I don't want this for meters or mm)  
Centimeters is a special case of detail drawings, eg for carpenters, where centimeters with decimal for mm is the norm.  For clearness and compactness of drawing, trailing zeros are omitted for round cm values.
```
        # Centimeters
        elif unit_length == "CENTIMETERS":
            if decimal_places is None:
                fmt = "%1.1f"
            if hide_units is False:
                fmt += " cm"
            d_cm = value * (100)
            tx_dist = fmt % d_cm
            # --- ADD THESE TWO LINES DIRECTLY HERE TO STRIP TRAILING ZEROES---
            if "." in tx_dist:
               tx_dist = tx_dist.rstrip("0").rstrip(".")
```

Like this:

<img width="793" height="536" alt="Image" src="https://github.com/user-attachments/assets/e8f9dd12-1ec9-44f2-bf5b-edded7466009" />

-vs-

<img width="655" height="569" alt="Image" src="https://github.com/user-attachments/assets/f3b639fd-a013-4067-96fc-41dd81ce3827" />

[A400 - ΝΤΟΥΛΑΠΑ ΥΠΝΟΔΩΜΑΤΙΩΝ 1 2.pdf](https://github.com/user-attachments/files/32336692/A400.-.1.2.pdf)

**Comment by theoryshaw** [comment]
You can set it via each drawing to "EPset_Drawing"."DecimalPlaces" = "0"
The value was 'null' before.

https://github.com/user-attachments/assets/03f28ed6-8865-4f83-aa74-592cc00e4852

**Comment by theoryshaw** [comment]
Might make sense to have the default be something like '3' just so it's obvious.  Thoughts?

**Comment by c1symeon** [comment]
> You can set it via each drawing to "EPset_Drawing"."DecimalPlaces" = "0"

aha aa  I missed that, but still: I want trailing zeroes to go away, it's not just about how many decimal places

<img width="1380" height="840" alt="Image" src="https://github.com/user-attachments/assets/c1079795-df87-499c-b85e-d3497e63e5d6" />

**Comment by c1symeon** [comment]
> Might make sense to have the default be something like '3' just so it's obvious. Thoughts?

a checkbox for trailing zeroes?
