### ISSUE TITLE
glitch with the status psets as it relates to 'excludes' in drawings

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3000]
[Clothing_Boutique.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11242451/Clothing_Boutique.txt)

video: https://www.dropbox.com/s/ecntcfgo7uga3ld/2023-04-16_08-56-19_Blender_blender.mp4?dl=0

**Comment by theoryshaw** [comment]
sorry, ignore that video.  That worked correctly. 

What is weird, however, is there are some walls in the following video that do not 'turn off' relative to the 'excludes' parameter. 
https://www.dropbox.com/s/ztm8yd5elu8vv4u/2023-04-16_09-07-20_Blender_blender.mp4?dl=0

@brunoperdigao Any ideas why these walls don't behave correctly?

**Comment by theoryshaw** [comment]
If i delete the pset, and add the same pset, it works. 
https://www.dropbox.com/s/ovzrwfm359gjc4g/2023-04-16_09-10-27_Blender_blender.mp4?dl=0

**Comment by theoryshaw** [comment]
It looks like it happens when you duplicate an object:
https://www.dropbox.com/s/upxq94icyjc8abv/2023-04-16_09-16-27_Blender_blender.mp4?dl=0

**Comment by Moult** [comment]
Happy bug 3,000! :tada:

**Comment by theoryshaw** [comment]
![magic](https://user-images.githubusercontent.com/507113/232360493-399442fa-a631-449a-b263-9d07293ef151.gif)

**Comment by Moult** [comment]
I think this, #3007 and #3009 are all related. The root cause seems to be that for some reason your wall/door/whatever has its Status property set as a single IfcText data type.

In contrast, the proper way for the Status property to be set is via an enumerated IfcLabel data type. When you add a property set via the IFC Property Sets panel, it detects whether the pset you're adding is part of the buildingSMART standard. If it is, it uses the standard template to set data types correctly.

In contrast, if you edit a property set, it tries to preserve whatever data type you already had. This means that once you somehow give it a bad data type, it'll stay that way until you either null it or completely purge the pset and re-add the pset.

So the question is, how did you manage to set that Status data using such a weird data type in the first place? I'm really struggling to think how you managed to do that, especially as IfcText is not really a common data type (i.e. our primitive text fallback is IfcLabel, not IfcText).

The only thing I can think of is that you've used the bulk property editor and manually set it to that invalid value (the bulk property editor let's you break all the rules). Something like in this screenshot:

![2023-04-17-182430_909x117_scrot](https://user-images.githubusercontent.com/88302/232430575-aa802844-2fe4-4cf8-bec6-49ef1a0da102.png)

... if I guessed wrongly, any hints about how you're setting these Status properties?

**Comment by brunoperdigao** [comment]
@Moult That's on me. You're right, it was the bulk editor. I used IfcText and it worked so I thought it was ok.

**Comment by Moult** [comment]
Righto, so unfortunately now you have a mix of good statuses and bad statuses in your model. You can this script to clean it up (just edit the paths):

```python
import ifcopenshell
import ifcopenshell.util.element

f = ifcopenshell.open('/home/dion/Clothing_Boutique.ifc')
for prop in f.by_type("IfcPropertySingleValue"):
    if prop.Name != "Status":
        continue
    value = eval(prop.NominalValue.wrappedValue)
    print(prop, value)
    new = f.createIfcPropertyEnumeratedValue(Name="Status", EnumerationValues=[f.createIfcLabel(v) for v in value])
    for inverse in f.get_inverse(prop):
        ifcopenshell.util.element.replace_attribute(inverse, prop, new)
f.write('/home/dion/fixed.ifc')
```

You can still use the bulk add/edit tool in the future, just be sure to select the enumerated IfcLabel option:

![2023-04-17-220913_851x145_scrot](https://user-images.githubusercontent.com/88302/232479972-6b54a91e-3572-440d-bab5-3a68f17528bd.png)
