### ISSUE TITLE
A way to override a dimension string measurement, but keep dimension too.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3005]
A way to override a dimension string measurement with text

user case, overriding with things like `V.I.F` or `EQ.`, etc.

did some brainstorming, here...
https://community.osarch.org/discussion/comment/12317/#Comment_12317

![image](https://user-images.githubusercontent.com/507113/232335686-2e97d033-a767-43bf-9730-ada54cf545cd.png)

**Comment by Moult** [comment]
I think this can already be done.

 1. Set the Description attribute of that dimension. This means that that dimension needs to be separate from other dimensions.
 2. Add BBIM_Dimension pset and enable "DescriptionOnly". Otherwise the description is shown in addition, instead of replacing the dimension.

**Comment by theoryshaw** [comment]
cool. Didn't know. 

worth keeping this open as a feature request to create more fine grained overrides, whereby using prefix/suffix text.

and the use of `\n`, perhaps.

![image](https://user-images.githubusercontent.com/507113/233064227-8e77c90c-96e4-48e5-9a62-2a57d9f8448f.png)
