### ISSUE TITLE
These wall tags, for some reason, are not working. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3007]
These wall tags, for some reason, are not working. 

[Clothing_Boutique.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11245198/Clothing_Boutique.txt)
![2023-04-16_19-39-18_Blender_blender](https://user-images.githubusercontent.com/507113/232353975-cf2cb36c-0e75-4a27-b13a-d8e943ab33a8.png)

**Comment by Moult** [comment]
Your tag is ``{{Pset_WallCommon.Status}}[2:4]`` which means show the 2nd to the 4th status which naturally doesn't exist so it defaults to an empty list. What is the intention here?

Why not just tag it as `{{Pset_WallCommon.Status}}` ?

**Comment by theoryshaw** [comment]
that annotationtype is working on other walls, however.  Not sure why these particular walls it's not working. 

I'm just abbreviating it to 'EX' to make it cleaner.

**Comment by Andrej730** [comment]
Not sure how this happened but in your file Pset_WallCommon Status property has different types (one is enum property and another isn't) which leads to different output for the same expression `{{Pset_WallCommon.Status}}[2:4]`. 🤔🤔

Any ideas if it was caused by blenderbim and how to reproduce it?

![image](https://user-images.githubusercontent.com/9417531/232478322-d43b4faf-191d-46b0-90ed-078ed82df55a.png)

![image](https://user-images.githubusercontent.com/9417531/232478435-b2e31fb6-6734-490b-8196-f93ea87b0804.png)

![image](https://user-images.githubusercontent.com/9417531/232480099-6a33e19d-79d4-4ccc-888a-1b3d20721d3d.png)
