### ISSUE TITLE
\n not showing correctly in svg

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3022]
[Clothing_Boutique.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11265557/Clothing_Boutique.txt)

show correctly in blender, not in the svg

![image](https://user-images.githubusercontent.com/507113/232884228-f58a876c-f107-4626-84bb-320afddcecb4.png)

![image](https://user-images.githubusercontent.com/507113/232884261-6f649d72-11c7-4dd5-8e96-8d30ab9d42d5.png)

**Comment by Andrej730** [comment]
Newlines doesn't really work if you're using some custom tag that's expecting text that'll be used as part of template (<text> tag with attribute data-type="text-template" inside the symbol).

Space-tag is one of those tags that's expecting three literals:
![image](https://user-images.githubusercontent.com/9417531/232978943-5a940060-9b5a-4c0c-bc3f-cc9d3b9fa5bb.png)

So instead of:
![image](https://user-images.githubusercontent.com/9417531/232978443-35176179-d750-4192-b5f6-e8fd6ffa526b.png)

Text should have 2 literals:
![image](https://user-images.githubusercontent.com/9417531/232979546-fd65e619-59a6-4f0e-a247-f33a0665d859.png)

**Comment by theoryshaw** [comment]
Gotcha!  Thanks @Andrej730
