### ISSUE TITLE
color/fill discrepancies between isolated drawings and drawings on the sheet

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3047]
Clothing_Boutique.ifc
from this commit:
https://gitlab.com/openingdesign/clothing_boutique/-/tree/63303bdde9daa6a3eeb31c61c5afd6a3feb393a8

color fills missing in sheet below.

![image](https://user-images.githubusercontent.com/507113/233501377-0c67b042-0108-4383-9e3f-159ef003937a.png)

![image](https://user-images.githubusercontent.com/507113/233501434-c011c133-89ac-49a2-b4a1-0b7bede6293a.png)

**Comment by theoryshaw** [comment]
In the layout, it shows the colors.. 

![image](https://user-images.githubusercontent.com/507113/233503285-461ca070-02fc-4fc4-9341-30766bb7c872.png)

**Comment by Moult** [comment]
Probably https://github.com/orgs/IfcOpenShell/projects/4?pane=issue&itemId=24997335 (haven't investigated yet)

**Comment by Andrej730** [comment]
Haven't found yet any way to separate namespaces for ids and classes in svg besides saving each drawing to separate .svg and bringing it up with `<image href="..."/>`

But there is a workaround - currently issue happens because one of the drawings on the sheet were printed before changes to styles or patterns were made and it's old styles used for other drawings too. So reprinting all drawings should solve the issue.

**Comment by Andrej730** [comment]
@Moult any ideas how to solve this? 
The only solution I've found is not to add actual drawing's svg to the sheet but just link the separate drawing file with `<image href="..."/>`. But that would mean that you won't have a single file for the entire sheet at the end which seems undesirable.

**Comment by Moult** [comment]
An autogenerated prefix to namespace everything when building the sheet?
