### ISSUE TITLE
If you duplicate a type, and unlink it, and save, if you open that IFC again, the type will be in the project. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3050]
If you duplicate a type, and unlink it, and save, if you open that IFC again, the type will be in the project. 

Would expect it not to be.

**Comment by Moult** [comment]
Unlink only removes the Blender-IFC connection, it doesn't actually delete the IFC element. So this is expected behaviour I think?

**Comment by theoryshaw** [comment]
Wouldn't expect it to be deleted immediately while in the live blender session, but would expect it not to be there on a fresh ifc import.

**Comment by theoryshaw** [comment]
...so yes would expect it to be removed from the ifc file.

**Comment by Moult** [comment]
Right, unfortunately the purpose of the "Unlink" operator is only to... break the Blender-IFC link, not to affect the IFC in any way. It's typically never used unless for more advanced purposes to play around with objects detached from IFC.

What exactly is the workflow you're trying to achieve? Maybe the Unlink operator is not relevant?

**Comment by Moult** [comment]
Bump?

**Comment by Gorgious56** [comment]
I agree that this may be a point where non-savvy users are lost because of the whole interface-over-ifc with blender objects and ifc elements.

It makes sense to me that this severs the link between a blender object and the ifc element while keeping the ifc element in memory. But where it leads to unsuspected behaviour is that it introduces a state in Blender where not all of the ifc is represented or accessible via the interface. Since the whole purpose of the native ifc workflow is to always be in a WYSIWYG state (unless I'm mistaken), clicking this button will irremediably make Blender display less than 100% of what's available in the file to the user, until they reload the file from scratch. I think this will lead to bug reports in the future, and we should disallow that. While still offering the possibility in an "Advanced mode" or something similar.

A solution might be to prompt the user with a popup saying this will NOT delete the ifc type definition, and suggest to do it at the same time ?

I use this feature regularly to duplicate IFC Opening Elements. I duplicate the opening, unlink the ifc element, and go out of the void interface. Poof, the duplicated element is still there, I know it's not supported but that's the only way I found to duplicate an opening after it's been applied to an element. I also know that it can lead to errors or corrupted data, since it also systematically duplicates the opening when I go out of the "Void" interface.

On the other hand I find it pretty straightforward that when deleting a type, both blender objects AND the type definition are deleted.

**Comment by Moult** [comment]
> A solution might be to prompt the user with a popup saying this will NOT delete the ifc type definition, and suggest to do it at the same time ?

Agreed, it needs to have a setting for the user to choose.

In the future, I expect more workflows where the user doesn't have 100% of the IFC loaded (when working on larger models).
