### ISSUE TITLE
When i try and delete this particular object, BB freezes. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3052]
When i try and delete this particular object, BB freezes. 
file: [merged.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11301252/merged.ifc.txt)

![2023-04-22_07-00-29_Blender_blender](https://user-images.githubusercontent.com/507113/233783488-23d2f92e-81b5-400b-b3a7-10329ad0f6e2.gif)

**Comment by Moult** [comment]
Surprisingly it's actually working, it's just working incredibly slowly until it freezes. If you ordered a pizza and watched a Seinfeld episode it'll probably finish.

The root cause is that removing an element X that is referenced in a very long list is very slow. Potentially @aothms knows of a more fundamental fix on the IfcOpenShell end, but for now the solution recognises that is a problem and preemptively clears those huge list attributes.

**Comment by Moult** [comment]
Probably worth mentioning that the object you're trying to delete has 10,000 polygons which is completely ridiculous in the first place, but alas that's what Revit tends to do: https://wiki.osarch.org/index.php?title=Revit_setup_for_OpenBIM/Revit_and_IFC_Geometry#Reducing_curves_in_profiles_that_are_swept.2C_revolved.2C_or_blended

The worst offender is a little glazed panel detail further along with over 30,000 polygons. Thankfully this fix now means that it now merely takes seconds to delete these objects. Hooray!
