### ISSUE TITLE
blenderbim mangles aggregates on save

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#3069]
I tried reducing this file, but the error went away, so attached are the original files that show the problem:

[demo.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11347028/demo.ifc.txt)
[demo-saved.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11347026/demo-saved.ifc.txt)

To reproduce, open `demo.ifc` in blenderbim and save as a different filename. The saved file is different.

These entities in the original file:

    #24738=IFCSLAB('1gU0ONfLjAQh5emRKTXKka',$,'stair-floor',$,$,#24830,$,$,.NOTDEFINED.);
    #24831=IFCSLAB('1Vv2lgFDn9f8o0niJLwNwr',$,'stair-floor',$,$,#24923,$,$,.NOTDEFINED.);
    #24881=IFCVIRTUALELEMENT('2luAs$fcn3zBNXWOiJGxkn',$,'stair-floor',$,$,$,$,$);
    #24974=IFCSLAB('3KNJ0sIeT86O0A8anSpbjp',$,'stair-floor',$,$,#30058,#25029,$,.NOTDEFINED.);
    #24789=IFCRELAGGREGATES('3TkYyoNWfAWASwsWytsUTm',$,$,$,#24738,(#24881));
    #24882=IFCRELAGGREGATES('0tbmV$1TXBCedd1i3oPikc',$,$,$,#24831,(#24974));

..become these in the saved file:

    #24738=IFCSLAB('1gU0ONfLjAQh5emRKTXKka',$,'stair-floor',$,$,#24830,$,$,.NOTDEFINED.);
    #24831=IFCSLAB('1Vv2lgFDn9f8o0niJLwNwr',$,'stair-floor',$,$,#30069,$,$,.NOTDEFINED.);
    #24881=IFCVIRTUALELEMENT('2luAs$fcn3zBNXWOiJGxkn',$,'stair-floor',$,$,$,$,$);
    #24974=IFCSLAB('3KNJ0sIeT86O0A8anSpbjp',$,'stair-floor',$,$,#30064,#25029,$,.NOTDEFINED.);
    #24789=IFCRELAGGREGATES('3TkYyoNWfAWASwsWytsUTm',$,$,$,#24738,(#24974,#24831));
    #30070=IFCRELAGGREGATES('1Mp5fV4aD8UgWlP3tJ5tTs',$,$,$,#24831,(#24881));

The first aggregate (`#24789`) is rewritten with the children replaced by the parent and child of the second aggregate.

The second aggregate (`#24882`) is replaced by another aggregate (`'#30070`) where the child is now the child of the first aggregate.

This mangling is not always the same, sometimes an aggragate loop is created, and sometimes the saved file is identical.

**Comment by brunopostle** [comment]
Some more investigation:

All the elements getting mangled here have the same *Name* attribute.

`#24974` is an *IfcSlab* element with a representation named `stair-floor`, this is contained within an aggregate `#24831` that is also an *IfcSlab* element named `stair-floor`.

(Homemaker spaces can have multiple slabs forming the floor, so these are aggregated together)

If I rename `#24974` then the problem goes away. So, the bug appears to be that the *Name* attribute is being used as a key somewhere in the code. It is probably a bit more complicated than this as this IFC file has lots of aggregate relationships sharing the *Name* attribute, but only this one gets mangled.

**Comment by brunopostle** [comment]
Further: If I change the class of `#24974` (the element with representation) from *IfcSlab* to *IfcCovering* the bug disappears.

But if instead I change the class of `#24831` (the aggregate element) from *IfcSlab* to *IfcElementAssembly* the bug still mangles the other *IfcSlab* aggregate (`#24738`) and child (`#24881`). If I then also switch the class of this aggregate to *IfcElementAssembly* the bug goes away.

**Comment by Moult** [comment]
Thanks for catching this. This is a dangerous subtle bug.

In short, we want to be able to support showing Blender objects in some form of collection-based hierarchy in the outliner for convenience. This hierarchy ideally shouldn't be hardcoded (e.g. the user might prefer collections based on class, or spatial containment, or spatial + aggregates as is the current default, or based on zone, or system, etc). In the future, we want to support more custom hierarchies and decouple the Blender collection hierarchy from the objects.

Depending on the chosen collection hierarchy mode, objects (such as spatial containers or aggregates) may have a corresponding collection. When this feature was first built in early 2.5 days, Blender collections were a rather new concept and didn't even have their own properties tab, and so the link was pretty weak - there was an assumption that if the collection name matched the object name, it was its "own" collection.

This assumption of name matching is mostly true and mostly works and we've got a few spots in the code that try to continue to make it true, but as you've now demonstrated, there seems to be an element of randomness to Blender's name uniqueness methods, which means that it is impossible to guarantee that the object name matches the collection name at all times. I'm sure this has led to subtle bugs that were impossible to debug in the past.

As a result, rather than relying on names (which is always bad) we now have a pointer property of the object pointing to its collection (only if it has its own collection) and a pointer property of the collection pointing back at the object.

This represents a fundamental shift in how we manage collection hierarchies. This probably introduces bugs (but is necessary for longer-term maturity). Naturally I'm checking the test cases, but please be on the lookout and _watch out_. Ping any users like @theoryshaw @plae-blue-dot @Gorgious56

**Comment by Gorgious56** [comment]
I agree that the current design of hardcoding collection and object names will introduce bugs when the user does something they shouldn't but are not prevented to do. It also forces the user to use the outliner hierarchy with reduced features.

Collections in Blender are a powerful concept and limiting each object to only one and forcefully moving objects between collections to enforce a hierarchy is definitely a reduction in user customization.

The question I have now is whether it is possible to use the ifc schema to save the user-created hierarchy so that loading the ifc file recreates a custom outliner hierarchy instead of (or in addition to) the hardcoded one, because if we can't do that, IMO there is no point in creating a custom hierarchy as a user knowing that it won't survive a roundtrip through ifc.

**Comment by Moult** [comment]
Totally agree, which is why this helps move away from the restriction of hardcoded collection names, 1:1 collection:object ratio restriction, and the current two modes for collections (we should allow a "completely custom collection" mode).

It is possible to use IFC for user created hierarchies by using the appropriate IFC equivalent of how the user attempts to organise things, such as classification systems, library references, zones, or more generically ... just arbitrary IFC groups (and yes, can be nested).

Initial steps were already made when the Collector tool was designed to slowly move away from name based things, but alas this is bit of legacy that takes time to clean up.

**Comment by Gorgious56** [comment]
Ooh nice. So this begged a question in my head  : 
Since it's a one-to-one relationship, and I assume we want the two-way link to always be respected we may want to add an `update` callback to `BIMCollectionProperties.obj` and `BIMObjectProperties.collection` so they fill in the other one if it's not already setup ? That way we don't have to explicitely set both relations ? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/import_ifc.py#L1341-L1342

To be clear here's what I think 

```
def update_collection_obj(self, context):
    if not self.obj:
        return
    if self.obj.BIMObjectProperties.collection != self.id_data:  # Avoid infinite recursion
        self.obj.BIMObjectProperties.collection = self.id_data


class BIMCollectionProperties(PropertyGroup):
    obj: PointerProperty(type=bpy.types.Object, update=update_collection_obj)

# And same thing for BIMObjectProperties.collection
```

Come to think of it we may want to use `get` and `set` instead, because this does not sever the previous relationships when a new one is created. 

Maybe it's too much hassle and we should enforce always explicitely setting up or removing the relationship ?

**Comment by Moult** [comment]
Yes, that looks great. I was debating whether it was enough to just do an Obj->Collection link or whether the Collection->Obj link was also needed. After initial tests it looks as though there are some usecases where it's useful to know the Collection->Obj  link, such as when the user arbitrarily moves an object to a random collection, we can update the IFC data as well.

Give me a moment to finish the WIP code I'm in the middle of editing, then go ahead and add your get/set :)

**Comment by Moult** [comment]
So the good news is that grepping the codebase for `users_collection[0]` no longer yield any results. So in theory we no longer hardcode "this object must only have one collection and that collection is magic". A step in the right direction, but still a long road ahead but I'm closing it since the bugs will turn up as expected in the future.
