### ISSUE TITLE
[Error] IfcGradientCurve Not Implemented

### ISSUE THREAD

**Issue by civilx64** [IfcOpenShell/IfcOpenShell#3098]
Per recent discussion with @aothms I have spun back up on IFC 4x3 implementation with an initial focus on `IfcAlignment` geometry parsing.

Testing with [UT_AWC_1.ifc](https://github.com/bSI-RailwayRoom/IFC-Rail-Sample-Files/blob/main/1_Alignment%20with%20Cant%20(AWC)/UT_AWC_1/IFC%20reference%20files/RC4/UT_AWC_1.ifc) and using the representation only (not segment parameters) I get the following error:

```
RuntimeError: [Error] [2023-04-30 04:20:35] Not implemented
#511=IfcCurveSegment(.CONTSAMEGRADIENTSAMECURVATURE.,#517,IfcNonNegativeLengthMeasure(0.),IfcParameterValue(61.6732236801535),#520)
[Error] [2023-04-30 04:20:35] Failed to convert:
#510=IfcGradientCurve((#511,#524,#536,#549,#561,#574,#586,#599,#611,#624,#636,#649,#661,#674,#686,#699,#711,#724,#736,#749),.F.,#204,$)
```

I suspect that this means exactly what it says: `get_shape` is not implemented for `IfcGradientCurve`.  If so then I will proceed with a python implementation that can be ported to C++ once working and tested for correctness.

**Comment by aothms** [comment]
Welcome back. Your suspicion is fully correct. For myself a long time back I basically broke down the work required in:

- transition curves / spirals
- horizontal+vertical (IfcGradientCurve)
- cant (IfcSegmentedReferenceCurve)
- sweeps - we can't rely on opencascade because of cant (occt only has tracking along surface normal (cfr IfcSurfaceCurveSweptAreaSolid) and efficiency (feeding a segmented 3d polyline from hor+ver would not perform).
- linear placement

**Comment by RickBrice** [comment]
How can I help? I'm generating slab on beam superstructure models and the geometry doesn't display in BlenderBim. My guess is the need for alignment and linear placement support.
@civilx64 
@aothms

**Comment by aothms** [comment]
So where we currently stand:

We have wonderful work by @civilx64 to implement support for the business logic side of alignment in python using numpy. https://github.com/IfcOpenShell/IfcOpenShell/pull/3148

Basically the ball is in my court now to translate this to C++ so that it becomes generally available in all of ifcopenshell.

I'm still a bit hesitant on where to begin. The work in #3148 is top-down, start from the alignment business logic and work your way down to the various items. But in IfcOpenShell C++ we have typically worked bottom up with stateless conversion functions that take individual IFC instances and map them to something equivalent in the geometry library. As I have no direct experience in the field of infra geoms I haven't really grasped whether it makes sense to use a bottom-up approach for infra as well or whether I need to make architectural changes to the core in order to bring this in. Since linear placement and sweep are based on the geometry definitions and not the business logic I'm also a bit shy if I'm able to figure out precisely how these two sides relate. But my working assumption is that a bottom-up approach would work still fairly well for the geometry side (because e.g IfcSegmentedReferenceCurve will reference the IfcGradientCurve whereas on the business logic side they are side by side) so I plan to focus on the representation items in C++. 

The other more practical concern is that it makes little sense to implement this in C++ using Open CASCADE because of the immense overhead of the BRep data model and lack of linalg support in their API. The good news is that in v0.8 we have an abstraction over the geometry library so we can essentially build IFC support using Eigen, CGAL or Open CASCADE. But getting this to production quality is still a rather monumental effort that proceeds rather slowly as I also need to work on things that put bread on the table and somehow those things always come with deadlines :(

> How can I help?

Back to your question. Thanks for asking. I'm very eager to collaborate on this and hear feedback. If there's anything basic on what I said that stands out as something you'd like to contribute to or give feedback on, then let me know :)

**Comment by RickBrice** [comment]
I looked through the alignment.py and transition_curve.py files. My python is a little rusty, but I use C++ almost every day so after being pointed in the right direction, I can attempt the C++ port.

Full disclosure - my IfcOpenShell experience is limited to creating new IFC alignment and bridge models using IfcParse. I have a good grasp on the math for horizontal and vertical alignments, clothoid transition curves, and superelevation transitions.

@aothms @civilx64

**Comment by aothms** [comment]
That sounds very exciting. I'll setup a bit of scaffolding over the weekend to have some starting points we can further discuss.

**Comment by aothms** [comment]
See https://github.com/IfcOpenShell/IfcOpenShell/commit/88ef7c75b830e0d8795a4c7b6d4779a179c19f14

I've made a start with some example of the handling of IfcCurveSegment+IfcClothoid.

I've set as goals for myself that it should be somewhat convenient to select other transition curves if there ever are schema additions and making it dispatch somewhat automatic like we have in python with the point_on_{PredefinedType} trick, which is obviously a bit harder in C++. So I ended using boost::mpl::for_each which kind of blindly tries to apply all types in `curve_seg_types` onto `curve_segment->ParentCurve`, so within the functor we still need to actually check whether the parent curve is of that particular type. Not ideal, but somewhat workable for now.

The other point of question is whether we want this tight coupling between IfcCurveSegment and spiral, or whether should we map IfcClothoid et al to something like a taxonomy::clothoid class to have more isolation. I didn't really see how to get that to work since the actual evaluation seems to depend on the Length which we only get at the segment level.

With the `std::function<Vector3d(double)>`, we've at least some way future potential to defer evaluation to when we have the full sequence of segments. But currently it evaluates to a polyline for each curve segment individually. We can add something like a taxonomy::piecewise class, which would be `std::vector<std::function<Vector3d(double)>>` (somehow accounting for the segment start u values). Or maybe we should implement the mapping simply one level higher at the composite/gradient/segmented reference curve?

Then lastly I'm still not very clear on what would be the return type of these functors and how to compose cant and vertical onto the horizontal segments.

I didn't really find a way to test this, but hopefully the structure of the code is clear enough to continue discussion.

**Comment by RickBrice** [comment]
@aothms I think I've got the general idea of what you've put together. I haven't spent much time in the IfcGeom library so I'm struggling with the details. Is the big picture something like:
1. IfcParse reads the file and creates entities for all the stuff in the IFC file
2. IfcGeom goes through all the representation entities and creates a kernel agnostic (generic) representation
3. Something (not sure what) processed the generic representation into kernel specific representations (ie. CGAL or OCCT).
4. A graphical program (like BlenderBIM) uses the kernel specific representations to get graphics on the screen

The framework you put together is processing the IfcCurveSegment instances and creating a generic representation that is basically a function that given a distance _u_ from the start, returns an xy point on the segment.

I see the challenge with the tight coupling between the IfcCurveSegment and the ParentCurve as well as the mapping challenges. Having a bunch of code blocks with "if(are you this type)... else (are you this type)..." can be difficult to maintain.

I'm too green to offer any suggestions for improvement. I'll keep digging into the IfcGeom library and your framework for dealing with alignment curves to improve my understanding. If these is something specific you need me to do, let me know.

**Comment by RickBrice** [comment]
@aothms I found the #2977 post. That answers a lot of my questions.

**Comment by aothms** [comment]
Even before reading #2977 it was already a good summary.

> Something (not sure what) 

That'd be:

- https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.8.0/src/ifcgeom/kernels/cgal
- https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.8.0/src/ifcgeom/kernels/opencascade

But to summarize:

- The mapping removes schema dependency in the geometry libraries. Otherwise the product of Num_schemas x Num_geom_libraries would really result into (even more) excessive compilation times and binary size.
- The mapping resolves some synonyms such as IfcClosedShell, IfcTriangulatedFaceSet, IfcPolygonalFaceSet all to taxonomy::shell so the effort to implement a geometry library is reduced.
- The mapping resolves IFC-specific idioms such as IfcIShapeProfileDef to taxonomy::loop so also there the effort to implement a geometry library is reduced.

The alignment geometries can pragmatically also be nicely placed in this mapping layer, because:

- The Open cascade brep data model would provide a lot of overhead for storing and sweeping the evaluated alignment curves
- The mapping layer uses Eigen, which is a bit easier to work with in terms of linear algebra.

What is still missing is:

- An 'identity' geometry kernel that would just output the mapped items to triangulations where possible (so no booleans, maybe no triangulations of polygons).
- A 'hybrid' geometry kernel that would pick the most appropriate kernel for a given item or retry using another kernel if e.g a boolean operation fails in one or the other.

**Comment by civilx64** [comment]
> The other point of question is whether we want this tight coupling between IfcCurveSegment and spiral, or whether should we map IfcClothoid et al to something like a taxonomy::clothoid class to have more isolation. I didn't really see how to get that to work since the actual evaluation seems to depend on the Length which we only get at the segment level.

I would recommend something like `taxonomy::transition_curve` because all of the transition types including clothoids can be calculated on the basis of curvature variation over the length of the segment.  Then utilize numerical integration to calculate the x,y coordinates at desired intervals.

> We can add something like a taxonomy::piecewise class, which would be `std::vector<std::function<Vector3d(double)>>` (somehow accounting for the segment start u values). Or maybe we should implement the mapping simply one level higher at the composite/gradient/segmented reference curve?

The piecewise approach makes sense based on our findings with the python implementation.  Which (I think) would also mean implementing the mapping one level higher at composite/gradient/segmented reference curve.

> Then lastly I'm still not very clear on what would be the return type of these functors and how to compose cant and vertical onto the horizontal segments.

If we're talking purely about the geometry then I believe `taxonomy::edge` is appropriate with `x, y, 0` for composite curve and `x, y, z` for gradient and segmented reference curves.

As for composing cant and vertical on the segments, I'd recommend thinking in terms of calculating the entire alignment at once at specific distances along the entire length of the horizontal alignment.  Then each distance is mapped to its relevant segment firstly to calculate (x, y) for the horizontal and then z for vertical and (if applicable) cant.  In other words, vertical and cant can be thought of as completely independent of the horizontal segments.

> I didn't really find a way to test this, but hopefully the structure of the code is clear enough to continue discussion.

Still struggling personally to grok the C++ but the isolation in v0.8.0 makes sense now... I think.  At the minimum I understand your recommendation re: sweeps and using a generic `loop` versus a specific `OCCT` data structure.

**Comment by RickBrice** [comment]
> The piecewise approach makes sense based on our findings with the python implementation. Which (I think) would also mean implementing the mapping one level higher at composite/gradient/segmented reference curve.

Do we expect the piecewise geometry to be used for anything other than graphical representations? In the sample code from https://github.com/IfcOpenShell/IfcOpenShell/commit/88ef7c75b830e0d8795a4c7b6d4779a179c19f14 an approximation of 64 segments is used. For alignments that are several miles long, there could be considerable error. Also, for straight segments, using fixed segments would be inefficient since only the first and last points are needed.

The x,y and x,y,z values at any distance along the composite and gradient curves, along with their tangent and normal directions, will need to be accurate for linear placement.

**Comment by civilx64** [comment]
> Do we expect the piecewise geometry to be used for anything other than graphical representations? 

It would also be the basis for linear positioning as well as sweeps.

>In the sample code from [88ef7c7](https://github.com/IfcOpenShell/IfcOpenShell/commit/88ef7c75b830e0d8795a4c7b6d4779a179c19f14) an approximation of 64 segments is used. For alignments that are several miles long, there could be considerable error. 

Agree.  We should calculate points at intervals of a distance, not based on `n` segments.

>Also, for straight segments, using fixed segments would be inefficient since only the first and last points are needed.

If you are dealing solely with Horizontal / Composite Curve e.g. 2D I would agree.  But as soon as you introduce vertical curvature within the range of a `.LINE.` segment then you need to calculate additional points.  Also if you are calculating earthwork cut and fill you would want to have multiple points spaced at a reasonable distance along the alignment to properly model the design.  In preliminary corridor design that might be as much as 200 ft between points, whereas in final design it might be 10 or even 5 ft.

Do you see any value in generating multiple representations?  E.g. 2D simplified version with only beginning and end of straight segments as you had noted along with a second 3D representation?  This would be similar to Bentley OpenRoads where the user typically works in the 2D `Default` model and the software generates the geometry behind the scenes in the `Default-3D` model.

> The x,y and x,y,z values at any distance along the composite and gradient curves, along with their tangent and normal directions, will need to be accurate for linear placement.

Agree 100%.  Ideally this would account for rotation about the local x axis such that the "up" vector is normal to the profile grade, not merely following the global Z as most current tools do.

**Comment by RickBrice** [comment]
Should this line https://github.com/IfcOpenShell/IfcOpenShell/blob/3bc9f81b6a2dde6dc33b1976b9d9de9b4bbfb8bc/src/ifcgeom/mapping/IfcCompositeCurve.cpp#L69C1-L69C86  be this?

`auto crv = map(segment->as<IfcSchema::IfcCurveSegment>()->ParentCurve());`

**Comment by aothms** [comment]
Yes, fully correct, sorry. That's exactly why I normally want to use visitor functions.

**Comment by RickBrice** [comment]
I think that line should be

`auto crv = map(segment->as<IfcSchema::IfcCurveSegment>());`

Otherwise the trimming information in IfcSegmentCurve is lost. If ParentCurve is IfcCircle, you don't know where the arc of a horizontal curve begins and ends. The ParentCurve of IfcSegmentCurve does not need to be a bounded curve. Also, if you call map with ParentCurve, where ParentCurve is an IfcCircle, the mapping code will crash.

**Comment by RickBrice** [comment]
I've made a fair amount of progress on mapping IfcCompositeCurve and IfcCurveSegment to geometry::taxonomy. You can see the progress in my forked repository [https://github.com/RickBrice/IfcOpenShell]() on the 0.8.0 branch. I can create a PR if you like (just didn't want to PR something that isn't complete).

I have a small driver program that dumps the converted geometry along with plots of the geometry in excel files at [https://github.com/RickBrice/IfcAlignmentDriver]().

Clothoid spirals are working well. The implementation of the other spiral types should be fairly easy in principle.

I would like to take a stab at implementing the geometry conversion for `IfcGradientCurve`. My guess is that a `map_impl(IfcSchema::IfcGradientCurve* inst)` method is needed which will (1) process the `BaseCurve` using `map_impl(IfcSchema::IfcCompositeCurve)` and (2) the `IfcCurveSegment` will need to be updated to handle `IfcPolynomialCurve` for parabolic vertical curves.

Since the horizontal `IfcCompositeCurve `can be used both for a FootPrint/Curve2D representation and an Axis/Curve3D representation, is there a way for a `IfcGradientCurve `to retrieved previous processed geometry for an `IfcCompositeCurve`?

The number of `BaseCurve `segments and profile Segments can be different in the definition of `IfcGradientCurve`. Any thoughts on how this might be handled? The` boost::icl` library might be helpful in dealing with overlapping regions of the horizontal and vertical representations.

@aothms 
@civilx64

**Comment by aothms** [comment]
Yes, I think a PR would be great. Nothing to worry about being work in progress. I'm a bit busy this week, but would love to pitch in again. 

>     auto placement = position->as<IfcSchema::IfcAxis2Placement2D>();
>
> https://github.com/IfcOpenShell/IfcOpenShell/compare/v0.8.0...RickBrice:IfcOpenShell:v0.8.0#diff-be0a3e3e00f8d8a24a29c355bd022eb663c4310e27251191374b9aa6d05ab4b4R83

How sure are we position is an axis 2d placement? The type in the schema is just general placement. What we can also do is:

```C++
Eigen::Vector3d placement_x = taxonomy::cast<matrix4>(mapping->map(position))->ccomponents()->col<0>().head<3>()
```

(this is untested, just to give an idea). That way we can convert any placement to a 4x4 and extract the first column / might have to be row (I always forget).

edit: I see you've made a similar comment (`// @todo add support for other IfcPoint subtypes`). Maybe my approach is the way to solve that as well. `ccomponents()->col<3>().head<3>()` for the point.

>     auto x = xl * cos(theta) - yl * sin(theta) + Cx;
>     auto y = xl * sin(theta) + yl * cos(theta) + Cy;
>
> https://github.com/IfcOpenShell/IfcOpenShell/compare/v0.8.0...RickBrice:IfcOpenShell:v0.8.0#diff-be0a3e3e00f8d8a24a29c355bd022eb663c4310e27251191374b9aa6d05ab4b4R118-R119

edit: reading along further, I wonder if it's necessary at all to decompose the placement like that?

We can probably do (?):

```C++
taxonomy::cast<matrix4>(mapping->map(position))->ccomponents() * Eigen::Vector4d(x, y, 0., 1.);
```

If multiplying with matrix is a generic thing for all curves (except polyline) we can also move it to the function `Eigen::Vector3d operator()(double u)` and do it there once for every type.

I really like how you did the polyline implementation. But I wonder two things. (a) It might be easier again to use abstract_mapping::map() to give you a sequence of Eigen::Vector3d points and also does some potential error correction (maybe remove degenerate segments) (b) What you've built here is actually what in Open Cascade is called `BRepAdaptor_CompCurve` (https://dev.opencascade.org/doc/refman/html/class_b_rep_adaptor___comp_curve.html). I wonder if this could be a generic function of taxonomy::loop for example. It'll probably cannot evaluate it for things like b-spline curves, but in the majority of cases it might be useful.

None of these things are urgent, don't want to slow you down. Just some thoughts I had when reading along.

**Comment by aothms** [comment]
> Since the horizontal IfcCompositeCurve can be used both for a FootPrint/Curve2D representation and an Axis/Curve3D representation, is there a way for a IfcGradientCurve to retrieved previous processed geometry for an IfcCompositeCurve?

This is indeed the fundamental architectural issue we still need to solve. I didn't know about `boost::icl`, interesting, thanks.

The idea I had was the following:

```C++

// taxonomy

namespace taxonomy {
    // An implicit geometric item, that can be evaluated to something explicit.
    class implicit : public item {
        virtual item::ptr evaluate() const = 0;
    }

    // A piecewise defined function defined as a sequence of length, function pairs (see @civilx64 implementation).
    // Function return type is VectorXd so we can return something like `{u, x, y, z}` for horizontal up to some Xd tuple for cant.
    class piecewise : public implicit {
        std::vector<std::pair<double, std::function<VectorXd(double u)>>>;
    }
}

// abstract_kernel

virtual bool convert_impl(const taxonomy::implicit::ptr p, IfcGeom::ConversionResults& rs) {
    // kernels can provide dedicated implementation functions for alignment geometries if they want to (like map to some domain model if they have to). If they don't provide a dedicated function handler, the abstract kernel will automatically evaluate it for them.
    return convert_impl(p->evaluate(), rs);
}

// mapping

taxonomy::ptr mapping::map_impl(const IfcSchema::IfcGradientCurve* inst) {
    // here in the mapping we know we get the implicit piecewise (the kernel is not activated here yet, so we can bypass the automatic evaluation that the kernel provides). 
    taxonomy::cast<taxonomy::piecewise>(inst->BaseCurve());
}
```

So to reiterate:

- We exploit the fact that we have actually three layers: (1) mapping layer (2) abstract geometry kernel and (3) specific geometry library kernel
- Within domain of mapping layer we retain implicit description of alignment geometry to compose horizontal+vertical+cant and precisely evaluate a placement at a specific length along the piecewise defined curve
- If one of these implicit geometry descriptions seeps through to layer 2 because (as @RickBrice exemplified it can be used as a representation item of horizontal or segment - what about segment?) it gets automatically evaluated to an explicit representation in layer 2 and layer 3 needs to have no knowledge of this.

On icl:

If instead of `std::vector<std::pair<double, std::function<VectorXd(double u)>>>;` @RickBrice thinks it's better to use a boost interval_set or interval_map I'm fully in favour of it. But I haven't been able to completely piece the things together yet. I just thought we compose by means of return {u, x, y, z} tuples from horizontal and reusing the u as input on vertical. I think maybe interval_map might be interesting in the sense that we can overlay multiple piecewise functions and use the resolution that makes sense (as we discussed if horizontal is al line, in the piecewise function composition approach, we would create intermediate points at fixed interval anticipating that vertical might be curved; whereas if we overlay multiple interval_sets we defer this decision to when we have all information and can make a more informed choice).

**Comment by RickBrice** [comment]
> How sure are we position is an axis 2d placement?
Not at all sure, I was working with something I understood. An IfcAxis2Placement3D is similar but there is some handling of the X-axis that I wasn't sure how do deal with. Assuming the curve is in an X-Y plane, and I can get the X-axis right, then dealing with 2D or 3D placement should be about the same.

> auto x = xl * cos(theta) - yl * sin(theta) + Cx;
> auto y = xl * sin(theta) + yl * cos(theta) + Cy;

I knew this wasn't great, but it's what I understand. I'll look into your proposed solution, it makes sense. I don't have enough experience with this codebase yet to even think of a solution like that.

You've made a lot of excellent points - it will take some time to dig in and understand them. My next couple of weeks will be busy as well. 

A RP is coming soon.

@aothms

**Comment by RickBrice** [comment]
> I really like how you did the polyline implementation

This implementation bothers me because there is already the map_impl(IfcPolyline*) implementation. This seems like duplicating code. 

However, the IfcCurveSegment::operator()(IfcPolyLine*) needs to know about start_ and length_ because the segment curve can be a subset of the parent curve (that's something I missed), so the two methods are somewhat different.

A good solution might be to delegate IfcCurveSegment::operator()(IfcPolyLine*) to map_impl(IfcPolyline*) then trim the start and end as needed.

**Comment by RickBrice** [comment]
Regarding IfcPolyLine

> It might be easier again to use abstract_mapping::map() to give you a sequence of Eigen::Vector3d points and also does some potential error correction

I implemented this - it seems to work well. The IfcCurveSegment does trimming with the start point (u = 0) and length (start + length -> u = 1.0) so it doesn't matter if the polyline starts before and is longer than the segment.

> This is indeed the fundamental architectural issue we still need to solve

Is there a cache of geometry stored somewhere? I'm thinking about IfcGradientCurve as well as IfcAxis2PlacementLinear with Location being of type IfcPointByDistanceExpression. In both cases, it may be useful to lookup a previously created curve (or create it on demand). In infra projects, elements are located relative to an alignment (station and offset). It would be really inefficient to map the IfcPointByDistanceExpression.BasisCurve every time something was positioned with an IfcAxis2PlacementLinear.

Ideally, the cached geometry could be used as taxonomy::loop for graphics and it could accurately compute points along the curve on demand (and probably the "up" direction as well). The cached object would need to have the points for the piecewise approximation and the equations that computed the points.

Just thinking out loud here - When mapping an IfcAxis2PlacementLinear the map (or is it map_impl) method could 
1) go to the cache look up the .BasisCurve based on its ID (I don't think it has a GUID), 
2) if the curve isn't yet cached, map it and cache it now
3) using the cached object, call methods like GetPoint(distance_along), GetAxis(distance_along), GetRefDirection(distance_along) and use the returned information to create the mapped placement matrix (probably not the right way to say it, but I think you can guess my meaning).

The next IfcAxis2PlacementLinear that uses the same .BasisCurve follows the same procedure, but the .BasisCurve has already been cached so that doesn't need to happen again. The GetPoint(...) and other methods are called to create the placement matrix for this placement, and so on.

If the .BasisCurve of the placement is an IfcGradientCurve, the IfcGradientCurve.BaseCurve might have already been process as a horizontal curve.

Or maybe I'm just talking nonsense here...

**Comment by civilx64** [comment]
> Is there a cache of geometry stored somewhere? 

This was the next step I had identified for the python implementation.  You are exactly right; we'd want to calculate once and then retrieve from the cache for calculating sweeps and linear placement.

>     1. go to the cache look up the .BasisCurve based on its ID (I don't think it has a GUID),

Correct; SPF-ID is present but not a GUID.  Thinking ahead to IFC5 where (potentially) the IDs are no longer present, is there benefit in being forward-thinking and generating an internal guid such as a hash of the segment entity & properties?
 
> Or maybe I'm just talking nonsense here...

Not at all!

**Comment by aothms** [comment]
You're both spot on. That's one of the reasons why I've rewritten the taxonomy to use shared pointers. The thing with caching and hashing though is that the created items should be immutable and this is not always the case yet. But it's the plan.

We'll then have immutability and hashing and can also easily detect identical duplicate geometry definitions in the model (mostly an advantage for building models instead of infra). See example hash functions here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcgeom/taxonomy.h#L238-L247

This is **after** the mapping though. For building geoms this made sense as the computation to evaluate happened in the geometry kernel (expensive boolean operations for example). Maybe this is a hint that doing the evaluation in the mapping layer is wrong, but I propose to keep it like that for now, caching (in the mapping layers) based on spf-id is sufficient for now and even if spf-ids disappear the parsed instances will always have some sort of identity or pointer address in memory.

**Comment by RickBrice** [comment]
@aothms the implementation of IfcTrimmedCurve seems quite robust. IfcCurveSegment is also a trimmed curve. Is there any consideration to delegate the implementation of IfcCurveSegment to IfcTrimmedCurve?

**Comment by aothms** [comment]
In v0.8 IfcTrimmedCurve simply gets mapped to the equivalent class in the taxonomy. Whereas for IfcCurveSegment we do a lot more in the mapping layer because the domain models of the kernels (cgal opencascade) don't define the transition curves. As we discussed in the other thread: It could be that we later decide to move the transition curve handling to a custom geometry kernel and keep the mapping layer cleaner. In that case indeed IfcCurveSegment and IfcTrimmedCurve become more alike in the the way they are handled. For now I would propose to first work towards a working implementation incl sweeps and linear placement so that we have a clear understanding of all challenges we still get to encounter.

I also questioned actually in IFC4X3 why to introduce IfcCurveSegment, and not extend TrimmedCurve and embed the placements into the curve (that anyway some already have such as Circle). But my recommendation came a bit late in the process and compatibility with STEP was deemed more important. This is just to say that I agree with your statement.

**Comment by RickBrice** [comment]
Thanks for the feedback - I was brainstorming what looked like an opportunity to save some work. I'm ok staying with the game plan for IfcCurveSegment. I know very little about the custom geometry kernels, so I defer to your experience.

**Comment by RickBrice** [comment]
@aothms Not sure if this is an architectural issue or if it's just my lack of understanding. I'm working on implementing IfcAxis2PlacementLinear and the ifcopenshell::geoometry::taxonomy::cast isn't compiling.

```
auto linear_placements = file.instances_by_type<Ifc4x3_add1::IfcAxis2PlacementLinear>();
for (auto& linear_placement : *linear_placements)
{
auto m = ifcopenshell::geometry::taxonomy::cast<ifcopenshell::geometry::taxonomy::matrix4::ptr>(mapping->map(linear_placement));
//auto m = std::dynamic_pointer_cast<ifcopenshell::geometry::taxonomy::matrix4::ptr>(mapping->map(linear_placement));
m->get()->print(std::cout);
}
```

```
1>F:\IfcOpenShell\src\ifcgeom\taxonomy.h(1063,26): error C2039: 'ptr': is not a member of 'std::shared_ptr<ifcopenshell::geometry::taxonomy::matrix4>'
1>F:\IfcOpenShell\src\ifcgeom\taxonomy.h(307,5): message : see declaration of 'std::shared_ptr<ifcopenshell::geometry::taxonomy::matrix4>'
1>F:\IfcOpenShell\src\ifcgeom\taxonomy.h(1098,29): message : see reference to class template instantiation 'ifcopenshell::geometry::taxonomy::loop_to_face_upgrade<ifcopenshell::geometry::taxonomy::matrix4::ptr>' being compiled
1>F:\IfcAlignmentDriver\main.cpp(288,46): message : see reference to function template instantiation 'std::shared_ptr<ifcopenshell::geometry::taxonomy::matrix4::ptr> ifcopenshell::geometry::taxonomy::cast<ifcopenshell::geometry::taxonomy::matrix4::ptr,ifcopenshell::geometry::taxonomy::item>(const std::shared_ptr<ifcopenshell::geometry::taxonomy::item> &)' being compiled
1>F:\IfcOpenShell\src\ifcgeom\taxonomy.h(1100,6): error C2440: 'return': cannot convert from 'ifcopenshell::geometry::taxonomy::loop_to_face_upgrade<ifcopenshell::geometry::taxonomy::matrix4::ptr>' to 'std::shared_ptr<ifcopenshell::geometry::taxonomy::matrix4::ptr>'
1>F:\IfcOpenShell\src\ifcgeom\taxonomy.h(1100,6): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called

```

The compiler is happy if I use `std::dynamic_pointer_cast`

Thoughts?

**Comment by RickBrice** [comment]
@aothms @civilx64 I'm implementing IfcLinearPlacement and need a little help understanding the IfcLinearPlacement documentation.

First the easy question. What is IfcLinearPlacement.CartesianPosition? The Description is "No description available". My guess is this attribute provides a way for vendors who have not yet implemented support for IfcLinearPlacement to deal with linear placements. If CartesianPosition is provided, then that is the placement to be used and there is no need to compute placement based on RelativePlacement. What do you think? Should we compute RelativePlacement and compare to CartesianPosition and broadcast a message if they are different?

I'm having a little trouble making sense of IfcLinearPlacement.PlacementRelTo. It looks like there are 4 cases to consider.

1. PlacementRelTo is omitted. This is easy (I think), Placement is relative to the start of the alignment. That is to say, RelativePlacement.Location is an IfcPointByDistanceExpression and the DistanceAlong attribute is taken to be the distance from the origin of IfcPointByDistanceExpression.BasisCurve
2. PlacementRelTo is an IfcLinearPlacement. DistanceAlong is the incremental distance from the relative placement. If you go up the hierarchy of IfcLinearPlacement.PlacementRelTo -> IfcLinearPlacement.PlacementRelTo-> and so on, eventually, one of the relative placements will omit PlacementRelTo. This would allow you to layout objects along a curve at constant or varied distance increments. An example might be IfcReferent for mile markers (this marker is 1 mile after the previous marker, which is 1 mile after its previous marker, and so on). Each IfcAxis2PlacementLinear could use the same IfcPointByDistanceExpresion with DistanceAlong being the incremental distance. If this is a valid interpretation, I don't see any requirement that all of the IfcPointByDistanceExpression.BasisCurve attributes must reference the same curve. Can I assume they all reference the same curve? If not, what is the interpretation if different curves are referenced?
3. PlacementRelTo is an IfcLocalPlacement. To me, this seems invalid, but I don't see any restrictions preventing it. How do deal with this case if it is valid?
4. PlacementRelTo is an IfcGridPlacement. To me, this seems invalid, but I don't see any restrictions preventing it. How do deal with this case if it is valid?

Maybe IfcLinearPlacement needs some where rules on the type of PlacementRelTo.

Back to IfcLinearPlacement.CartesianPosition - Does IfcParse save the placement? I doubt it since IfcLinearPlacement isn't supported yet. So, should it be saved? How would I go about doing that?

**Comment by aothms** [comment]
Ok, I filed an issue on CartesianPosition, I agree with your intuition, but this needs to be stated in the docs.

@civilx64 that would be another rule then in the validation service :) to compute that these are actually equivalent.

Regarding PlacementRelTo, I assumed you can be agnostic to how the placement is defined, but simply premultiply (in occ vocabulary) the resulting matrix into the matrix you'd be computing.

Regarding case 3 and 4 I don't think these are invalid. And especially case 3 might be used in practice rather frequently. Where the IfcAlignment is positioned using a LocalPlacement to position it globally and then objects placed linearly based on that alignment will need to have that same LocalPlacement in RelTo in order for them to line up.

**Comment by RickBrice** [comment]
> Ok, I filed an issue on CartesianPosition, I agree with your intuition, but this needs to be stated in the docs.

I just discovered that it was defined in 4x2 https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/ as 

> Indicates the calculated global location and orientation in Cartesian coordinates as a fallback which may be used by applications that do not support linear placement.


> Regarding PlacementRelTo, I assumed you can be agnostic to how the placement is defined, but simply premultiply (in occ vocabulary) the resulting matrix into the matrix you'd be computing.

Yes

> Regarding case 3 and 4 I don't think these are invalid

OK - I see what you mean. Alignment does not need to defined relative to a global origin. I can be defined relative to a local placement. For example an alignment could start at a local point (10,10,0) from a survey control point that is positioned somewhere within an IfcSite.

**Comment by aothms** [comment]
> Indicates the calculated global location and orientation in Cartesian coordinates as a fallback which may be used by applications that do not support linear placement.

Thanks that's a nice find. Just out of curiosity since I'm proposing these definitions to the spec: Do you consider 'Cartesian' as a meaningful qualifier as opposed to linear. On the one hand I see the point in the sense that you have an non-linear axis that you're moving along. On the other hand you're still in Cartesian space just implicitly defined along a curve. Do you consider the reference of a curve as a coordinate system or as a function to define a coordinate system? Sorry if this doesn't make any sense, just hoping to get a sense of how you think of this in the domain.

**Comment by RickBrice** [comment]
> Do you consider 'Cartesian' as a meaningful qualifier as opposed to linear

In this context, yes. The CartesianPosition is an alternative to the position defined by the linear placement. Is Cartesian the best qualifier? Probably not - the CartesianPosition attribute is an alternative placement to be used when linear placement is not supported. AlternativePosition or AlternativePlacement would work just as good.

> global location and orientation

I'm not 100% sure, but I think global may be correct. Alignments aggregate to Project [4.1.4.1.1](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/concepts/Object_Composition/Aggregation/Alignment_Aggregation_To_Project/content.html) and Alignments are referenced in spatial structure [4.1.5.1](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/concepts/Object_Connectivity/Alignment_Spatial_Reference/content.html). I think this makes all alignments in a project global. An alignment can be referenced into more than one site as illustrated [here](https://bimcorner.com/wp-content/uploads/2022/09/ifcSite.png).

>Do you consider the reference of a curve as a coordinate system or as a function to define a coordinate system?

It seems like a function to define a coordinate system. The properties of the curve define a local relative coordinate system for placement. Properties such as (XYZ) at some distance along the curve, and a tuple of vectors tangent, perpendicular, and "up".

**Comment by RickBrice** [comment]
I don't know if you've seen this before, but it does a pretty good job explaining how bridge engineers think about alignment geometry. [Bridge Geometry Manual - USDOT FHWA](https://www.fhwa.dot.gov/bridge/pubs/hif22034.pdf). @civilx64 might be familiar with it. I think his company wrote the sections for steel bridges.

**Comment by RickBrice** [comment]
@aothms @civilx64 Can this be closed?
