### ISSUE TITLE
Keep vertices separated in Types

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3120]
Is there a way to have the vertices not merge by distance? 

for example, would it be possible to get the following (2) cubes to remain separate? 

_There's a bonus bug in that video too. ha.  (which i haven't tracked down how to replicate... it just popped up coincidentally during this videocast)_

https://user-images.githubusercontent.com/507113/236916848-4eae07f7-acf8-4ef7-8028-58724a6af4a9.mp4

**Comment by aothms** [comment]
It'd would also allow more purely to create a collection of closed shells. Edges should only be referenced twice. Merging by distance without considering connected components will likely create non-manifoldness.

**Comment by theoryshaw** [comment]
I might be missing something, but it seems vertices still merge. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c4354edc-0da9-49e6-a9cd-ec481fb067fb

**Comment by Moult** [comment]
I had a closer look and this is actually a bit trickier to handle.

Right now, there is no interface for the user to control how many representation items a shape representation can have. This means that for extrusions, you can only at the moment edit the 0th extrusion (arbitrarily). For meshes (tessellations, breps), this means that you don't have control over whether the mesh ends up being one item or two.

Sort of. In IFC, if you have two portions of a geometry with different styles / colours, you need to have those two as separate representation items. Therefore, there is a "loose" mapping between Blender's mesh material slots and IFC representation items. So if you had those two touching cubes with two different materials, then they would be stored as two separate items in Blender, and therefore not weld vertices between them. In this scenario, it's all good - you can keep them separate as you want.

![2023-06-05-163024_604x299_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/bbc20c88-fba9-4216-9031-b73972e1820d)

However, what if you had a window frame and a window sill, both of the same material? Then, you can cheat by using this "loose" mapping by creating two material slots referencing the same IFC style / material but assigned to different portions of the mesh. Therefore, it creates two separate cubes as two items.

![2023-06-05-201957_736x387_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/e70b5d18-4e42-4527-b324-75bb255181b1)

... which sort of works, until you reload the IFC. Then, because material slots are just a "loose" mapping to items, it merges back into one slot. However, it doesn't weld vertices, so it still works... until you edit that mesh and save it and whoops it's welded again. Darn.

![2023-06-05-202043_691x309_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/2234a02d-44ea-4a25-8a12-b8e8857d8566)

So, the cheap(ish?) solution is to enforce that loose parts are separated prior to saving meshes and each loose part gets its own material slot. That way we start enforcing the mapping between Blender material slots and IFC representation items.

However my gut feel tells me that this isn't a very good solution. Firstly because 1) the user no longer has control over items, which can lead to an explosion of items if the user decided to do some splitting tasks or model non manifold stuff, and 2) larger numbers of material slots can lead to a slowdown in Blender I believe, and 3) the fact is pretty fundamental that we need to start enabling users to control items not just for meshes, but for extrusions too ... we want to model multiple extrusions in a single object right?

So alas I'm sorry I don't think I can provide a quick fix (unless the explanations help). This falls under the umbrella of more detailed IFC modeling tools which needs to be built.

**Comment by aothms** [comment]
> So, the cheap(ish?) solution is to enforce that loose parts are separated prior to saving meshes and each loose part gets its own material slot.

Just reading a long here, but why is this:

> because material slots are just a "loose" mapping to items, it merges back into one slot

Should we just add e.g instead of material_ids a part_ids to the mesh element? That'd be quick from my side and it seems it would solve some headaches?

**Comment by Moult** [comment]
> Should we just add e.g in addition to material_ids a part_ids vector to the mesh element? That'd be quick from my side and it seems it would solve some headaches?

That would really help a lot! It doesn't solve this particular issue since the reason Blender material slots doesn't map exactly is for Blender efficiency (if an IFC railing has 100 parts, Blender chokes on 100 slots) as well as for easy material fallback.

But it would definitely help solve a lot of other problems in the future when we build more "item" aware modeling / editing tools.

**Comment by aothms** [comment]
Done. Welding also doesn't happen anymore now across items. I figured that's more sane.

**Comment by theoryshaw** [comment]
Thanks guys, Is there a work around for this yet, or still outstanding?

**Comment by theoryshaw** [comment]
Use separate materials, as Dion suggested above?

**Comment by Moult** [comment]
There's still work to be done on the Blender side :( As a workaround you can use separate materials.

**Comment by theoryshaw** [comment]
@Moult i have a feeling your work [here](https://github.com/IfcOpenShell/IfcOpenShell/commit/5fe85e71bbe795efe5f447bc2e1f420f4c691033), will help solve this problem.  Is that a correct interpretation?

**Comment by Moult** [comment]
Correct - the ability to edit at the item-level of granularity fixes this problem and quite a number of others too.
