### ISSUE TITLE
IfcConvert SVG does not generate <path d=""> for IfcSpace.

### ISSUE THREAD

**Issue by Xsoiou** [IfcOpenShell/IfcOpenShell#313]
I have git cloned this project and trying to generate SVG from an IFC-file that consists entirely of IfcSpaces. Everything runs fine, except that the path-element doesn't get genereated:

![image](https://user-images.githubusercontent.com/32762440/34030990-a8cf0052-e16f-11e7-9c0c-7789637ee7ff.png)

I've downloaded the .exe file (0.5.0 preview version) from ifcopenshell.org/ifcconvert.html to test the SVG generation there, and it generates the SVG for that IFC-file with no issues. I have also tested the git cloned converter with another IFC-file, with successfull SVG generation. I'm having trouble identifying where in the code the issue persists. Has anyone experienced anything similar? Any help is appriciated!

**Comment by aothms** [comment]
Is it possible for you to attach the file to this issue or otherwise send it confidentially to models@ifcopenshell.org. Then I can have a look.

Did you try running IfcConvert with the `-v` switch to have more detailed logging information? Is there anything interesting in the log?

**Comment by Xsoiou** [comment]
Hi aothms, and thanks for the answer. 

Unfortunately we are not able to provide the file. But i ran the IfcConvert again now with `-v` switch, but there was no information in the logs. We do get this error though 
`[Error] {24SlhkccLAJgziJ$e6qEr9} Flattening face boundary. `
But we also get this error when we are converting other files that are generated correctly.

**Comment by aothms** [comment]
> We do get this error though

It shouldn't affect svg conversion as you noted.

Then I see two options:

* run `git bisect` to find the offending commit. Should be fairly doable if you can stay on the command line.

* step through the code. There have been some recent changes starting here [1]. If a regular conversion to DAE/OBJ works without problems, the issue is likely somewhere there. If not, then your best bet is to start here [2].

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/SvgSerializer.cpp#L78
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeomFunctions.cpp#L1158

**Comment by Xsoiou** [comment]
We have found the problem:
In the commit 9be413a308017ec0c3a36b38cad04055086bd50e there seams to be a problem with the `	cut_z = storey_elevation.get() + 1.;` part. This breaks our svg generation. If we remove it, everything works perfectly. Not sure why this is happening, maybe somone else does?

**Comment by aothms** [comment]
Ah I see now, there's actually two flaws:

* we never check whether `zmin < (storey_elevation.get() + 1.) < zmax`
* `(zmax - zmin) < 1.` does not need to be true in case `section_height` or `storey_elevation` is true.

Here's what I would propose:

1 `if (zmin == inf) continue` (just to early on filter out empty geometry)
2 set `cut_z` according to current 3-branch logic [0]
3 if (zmin > cut_z || zmax < cut_z) continue;

[0] with one addition, `if (storey_elevation)` should probably read `if (storey_elevation && !(zmin > *storey_elevation || zmax < *storey_elevation))` in order to fall back to `zmin + 1.` in case the elevation of the storey somehow does not align with the element geometry.

If it's not too much to ask, can you check whether this would work for your files? Thanks.

**Comment by Xsoiou** [comment]
That worked perfectly! I have created a pull request with the changes if you wanto use that. #315
