### ISSUE TITLE
When changing classes, should inappropriate psets be removed?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3136]
If you have an IfcWall with a Pset_WallCommon, and later change the class to an IfcWindow for example, the Pset_WallCommon is still attached.  Would expect it to remove this Pset_WallCommon, as it no longer applies.

**Comment by Moult** [comment]
I find changing classes to be an advanced user tool, and so I don't think it should remove it even if it no longer applies because:

 1. The user might want to copy over the pset properties to another pset
 2. The user might have custom psets where we don't know their applicability.
 3. It's difficult to know what the behaviour should be for quantities too - different qtos might use different quantity names for the same concept or vice versa.

I would prefer to simply improve the UX around bulk changing / removing / adding props / quantities.
