### ISSUE TITLE
Clipping Errors in attic

### ISSUE THREAD

**Issue by ninichki** [IfcOpenShell/IfcOpenShell#3141]
Hi,
I have an Archicad 26 model with some clipping errors.
Some walls in the attic are not correctly clipped.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/1086380/f6b176dd-cdce-4457-98d4-c6588a212e87)
IfcOpenShell IfcConvert v0.7.0-476ab506d (OCC 7.5.3)

Is it possible to fix it?

[Building.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11462827/Building.zip)

kind regards

**Comment by Moult** [comment]
FYI strict_tolerance fixes some issues but creates others:

![2023-05-17-121038_766x616_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/7e25c45f-fac1-46a7-bbf9-e6400a787b00)

**Comment by aothms** [comment]
I think all issues are solved with the latest commits. With Open CASCADE making tremendous improvements in robustness and our pre-filtering and data massaging in IfcOpenShell, we're getting to point where if things fail there is either a logical reason or a straight forward fix (or both).

In this particular case the issue was very narrow operands within the set of subtraction second operands

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/9e738130-1e7e-44b0-b16a-b2f7231d2be6)

`IfcConvert --include+ entities IfcWall` now renders as:

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/bc3b01e3-11d4-47df-bd2d-236de389690e)

The protruding element on the right I think is faithfully represented as modelled. You can clearly see the wall in gray extending beyond the second operands in red.

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/e1da1fe2-e3a0-4705-b3ff-3d7aafc2639c)

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/0fc35d70-fb6f-433f-afbd-e77090306681)

**Comment by ninichki** [comment]
Wow, that sounds fantastic

**Comment by ninichki** [comment]
So do I need a newer Version of Opencascade or is 7.5 ok for this?

**Comment by Moult** [comment]
You'll just need to either compile IfcOpenShell yourself or wait for the next bot build which usually happens every few weeks.

**Comment by aothms** [comment]
7.5 is ok :) I was just making a general statement, thinking back of they occt 6 days..
