### ISSUE TITLE
Any way to judge if 2 IfcRepresentation have the same geometry without creating TopoDS_shape using OCC?

### ISSUE THREAD

**Issue by cathty** [IfcOpenShell/IfcOpenShell#317]
Due to 3D geometry generation performance is poor with OCC, I'd like to reuse  geometry if IfcRepresentation  geometry are the same(not mappedRepresentation).
Any way to judge if 2 IfcRepresentation has same geometry representation? 

Thanks

Kevin

**Comment by cathty** [comment]
For example,  2 IfcRepresentation, each one contains a box with same length, height, width, but base point location is different.

**Comment by aothms** [comment]
The Python code has an option to recursively generate a dictionary of attributes and values (with the option of excluding numeric step instance names). That way you could simply compare the dictionaries for equality [1].

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcopenshell-python/ifcopenshell/entity_instance.py#L156

In C++ there is no such utility function (and would be a bit more difficult to fill a dictionary due to static typing (perhaps `Boost.Any`?).

An `operator==()` for `IfcBaseClass` or `IfcEntityInstanceData` would not be overly hard to implement and very nice to have. In case you'd like to work on that I'd happily assist, but I don't have time to work on this personally now. For the latter simply, compare entity type, iterate over the vector, for every attr compare `type()`, cast appropriately and check equality.

**Comment by cathty** [comment]
Thanks very much. 

By the way,  VS2015 profile indicates that function 
bool IfcGeom::Kernel::convert(const IfcSchema::IfcObjectPlacement* l, gp_Trsf& trsf)
performance is very poor. 
I wonder this function is used to calculate object global transform matrix. any room to polish its performance?

**Comment by cathty** [comment]
I already done some test,  type() and Name() can't guarantee geometry are the same.

**Comment by aothms** [comment]
> I wonder this function is used to calculate object global transform matrix

That's correct

> any room to polish its performance?

Probably, do you have a more detailed call graph?

> I already done some test, type() and Name() can't guarantee geometry are the same.

I meant the contents of this vector:
https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcparse/IfcEntityInstanceData.h#L42
