### ISSUE TITLE
Remove `IFC Mode Set Object` warning?

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3174]
Is it possible to remove this warning? :)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/8377edc7-c975-4f0e-9c02-7e8574407560)

I click on this a lot. :)

**Comment by Gorgious56** [comment]
FWIW clicking anywhere in the screen will validate the popup, so you can click away when it shows up :)

I think this could be improved by 
1- adding a more descriptive name to the property, "Should Save" doesn't give much information about what will be happening if we click OK or not. Is it the ifc file ? the blend file ? the mesh representation ? the IFC element ? The IFC Storey ? ...
2- transforming the popup into a YES / NO button instead of just "OK" because now if the user doesn't want to save they have to click 2 buttons : the checkmark and the OK button. 
3- add an option like "Do not ask again" that will save a property in the addon preferences to auto-save automatically and silently validate this popup ?

**Comment by theoryshaw** [comment]
Dumb question, why ask it at all?
For example in vanilla blender, when you exit the tab mode, it doesn't ask if you want to save it.

**Comment by Moult** [comment]
The reason we ask is because any geometry writing is potentially an expensive operation (especially dense meshes). We want to give users the chance to go "no thanks, I was just messing around".

Another solution would be not to ask at all, but instead offer a way to "discard changes" elsewhere as a button or whatever. Like Shift-Q? That way usual usage will not be interrupted but there the discard option isn't removed.

**Comment by theoryshaw** [comment]
How about `Esc`?.. to not save.

**Comment by Gorgious56** [comment]
FWIW, same as vanilla delete operator, you can tweak the keymap and disable "Confirm" in the ifc delete entry. Treading in power user territory, but in the meantime it's a valid solution I think

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/b899e29e-e0eb-491e-9343-cf800b4a0150)

**Comment by Gorgious56** [comment]
Wait sorry I completely mistook the delete confirmation with the tab edit operators, so it's definitely not a solution yet but could be implemented likewise ?

**Comment by Ta-b** [comment]
I will pre-face this by saying I'm not on the latest version of BBIM, but is there any option to avoid this pop-up yet?
I would really appreciate if there was a way to control it, even if it's an "advanced" setting somewhere. Thanks :)

**Comment by Gorgious56** [comment]
If you're not against a bit or manual tinkering there should be a way to automatically accept the changes by removing a few lines of code

**Comment by Ta-b** [comment]
I am not against the idea at all. I have tried to hunt it down in the code myself but no luck.

**Comment by theoryshaw** [comment]
![levelup](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f452b0b0-870f-42a6-b56f-3dbd585ea627)

**Comment by Gorgious56** [comment]
Haha ! I do hope it doesn't break everything horribly, but Im 95% sure it doesnt. Please test it on a test file beforehand.

**Comment by Ta-b** [comment]
Ah sweet sweet release. Thanks. In the long-term it would be neat to have it in the Options somewhere but then again I also don't see many people moaning about it so ¯\_(ツ)_/¯

**Comment by trhyder** [comment]
To be more descriptive maybe the popup should say something like:

Confirm Save
Your change will update all instances.
Do you want to save changes?
[ Yes ] [ No ] [ Canel ]

Where "Yes" saves the change and disables edit mode, "No" doesn't save the change and disables edit mode, and "Cancel" doesn't save and remains in edit mode.

Would it be possible to show this confirmation only if an overly taxing situation is estimated to occur?
