### ISSUE TITLE
Can't install plugin on Mac M1

### ISSUE THREAD

**Issue by evgeniyamg** [IfcOpenShell/IfcOpenShell#3179]
Last Blender, Last plugin.

May be you know what's happening? 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/70819226-45c1-499f-98e0-f8950dda1120)

**Comment by Andrej730** [comment]
Can you please send us full traceback (there seems to be more after this down-arrow at the end of the error message) and try to run just `git` in terminal? Is it showing the same error? Found [here](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a) that it might be for command line tools that can be installed with `xcode-select --install`.

@brunopostle 
Can you please take a look too - in the code do we currently require that git is installed and functional by default to use BlenderBIM or it supposed to work without git until you try to start a repository?

**Comment by brunopostle** [comment]
I believe this problem is caused by a [broken xcode](https://apple.stackexchange.com/questions/374744/how-do-i-solve-the-problem-of-invalid-active-developer-path-when-attempting-to) installation.

Anyway, d98b076 is a workaround for blenderbim, so the latest [230521 release](https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/blenderbim-230521) should be ok. Please report back if this does not work.

**Comment by brunopostle** [comment]
@Andrej730 It was setup so that blenderbim required GitPython (ie. `import git` needed to work), but the Git panel was disabled if the `git` executable wasn't in the `PATH`. This was ok on Linux/Windows, ie. it did the right thing with or without a local git install.

It seems this xcode problem is at a lower level, git is installed, but GitPython isn't able to run it, so `import git` fails. d98b076 should ensure that blenderbim runs even with a broken/missing GitPython module.

**Comment by evgeniyamg** [comment]
Thanks a lot. Xcode installation solved this problem.
