### ISSUE TITLE
Iterating on geometry, is it possible to get sub shapes of the current mesh ? [C++]

### ISSUE THREAD

**Issue by Baruchware** [IfcOpenShell/IfcOpenShell#3180]
Hello!

I am trying to figure out how I could get the sub shapes of an instance when iterating on geometry, in order to get their geometry (seems like current mesh which contains sub meshes is considered as only one shape).

I've looked into this documentation but I'm not sure if there's anything that works for me: [https://blenderbim.org/docs-python/ifcopenshell/geometry_settings.html](url).

is this possible with IfcOpenShell? 

Thank you in advance!

**Comment by aothms** [comment]
When you say "submeshes", do you mean the various IfcRepresentationItems that make up the IfcShapeRepresentation? It depends on your exact code and settings. `BRepElement` has those as begin() end() https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom_schema_agnostic/IfcGeomRepresentation.h#L76C1-L77 `TriangulationElement` with WELD_VERTICES=true will give you connected components. Otherwise you have associations to individually coloured items in material_ids(). What do you intend to get precisely?

**Comment by Baruchware** [comment]
Thank you for the detailed answer, Yes I meant the IfcRepresentationItems.
I am using triangulation mode, I will try disabling it and check what happens exactly for shapes and colors using BRepElements. (thanks a lot for the suggestion).

I would like to have both submeshes geometries in order to reuse the same geometries, but also the colors.
I ended up using the material_ids() for the colors, which works very fine.

But I am getting weird results with a specific test file which I can share with you:

These are the colors I would expect to see:

These are the colors I expect:
![immagine](https://github.com/IfcOpenShell/IfcOpenShell/assets/53627894/968e33c2-9e31-4a08-a035-09abbf218044)

There are the colors I get:
![immagine](https://github.com/IfcOpenShell/IfcOpenShell/assets/53627894/18d2c5b1-cb4f-4b5d-8394-542eee00fe85)


I can give you this simplified file: 

[Pulsantiera.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11546054/Pulsantiera.zip)


Thank you so much aothms!
