### ISSUE TITLE
Duplicating a layered object, and changing its type to another layered object type breaks the profile

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#3184]
When I:
Duplicate an object made up of horizontal layers, say a slab,
Then I change the object type another IfcSlabType, 
--> The previously drawn profile is lost and the object is no longer controlled as expected.

Would it be possible to retain the profile and other relevant dimensions when changing the type? 

In other scenario, let's assume I'd like to duplicate the slab because I need to copy its footprint - and turn this into an IfcCovering with horizontal layers.  Could we duplicate/ change the type to do the trick here?

**Comment by Andrej730** [comment]
Can you please give an .ifc example?

**Comment by Moult** [comment]
I can't recreate the first issue. Note that there are a few valid situations where the old extrusion profile will be lost:

 1. If the old layer did not use an extruded area solid.
 2. If the old representation does not properly follow the Model Body MODEL_VIEW context.

Those are not bugs, unless you can demonstrate a file which suggests otherwise.

For the latter, as of the latest commit you can:

 1. Duplicate the slab
 2. Change the IfcSlab to an IfcCovering
 3. Change the type from an IfcSlabType to an IfcCoveringType.

**Comment by myoualid** [comment]
Okay, so.. it all works smoothely now ! Sweet new time saving feature ! Woop Woop !
