### ISSUE TITLE
Support inch fractions

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3194]
Love the latest units support. 

Possible to add support for fraction inches?
Is typically how peeps enter in units on imperial projects. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9c5e54f5-332d-4eb5-9944-befe2bb3480a

**Comment by Andrej730** [comment]
Not sure because this feature is completely Blender's thing and we don't have much power here.
I've googled a bit and it's seems to be general problem with Blender that it's not showing imperial fractions.
If you have seen it somewhere else in Blender interface or other addons we sure can replicate it here too.

**Comment by Andrej730** [comment]
Btw if just need to type fractions of inches like `0' 6 1/4"` - you can do it like `0ft 6in 1/4in` as I explained here #3037

**Comment by theoryshaw** [comment]
yes, that will work!  Thanks @Andrej730.
