### ISSUE TITLE
Ifcopenshell-python bounding_box

### ISSUE THREAD

**Issue by whsqjss** [IfcOpenShell/IfcOpenShell#320]
Hello,I'm new here,I'm trying to parse IFC files with Ifcopenshell-python, 
My question is: 
  Is there any way to get the IfcProduct's bounding_box by using Ifcopenshell-python?

Thanks for your early reply.

Best Regards,
Hu Quan

**Comment by aothms** [comment]
Sure, but you need to do the full geometry interpretation using `result = ifcopenshell.geom.create_shape()`. Depending on your needs you can do this using PythonOCC (with `settings.set(settings.USE_PYTHON_OPENCASCADE, True)`, `BRepBndLib_Add()`, ...) or the default mesh (look at the `result.geometry.verts`).

**Comment by whsqjss** [comment]
Thank you for your reply, I want to do this using the default mesh.here is part of my python code to get AABB bounding_box, I want to know if I do it correct?

Best Regards,
Hu Quan

Python Code：
   verts = geometry.verts
   vertsX = [];
   vertsY = [];
   vertsZ = [];
   for index in range(len(verts)):
       if index%3 == 0:
         vertsX.append(verts[index])
       if index%3 == 1:
          vertsY.append(verts[index])
       if index%3 == 2:
           vertsZ.append(verts[index])
   minX = None
   minY = None
   minZ = None
   maxX = None
   maxY = None
   maxZ = None
   # sort the array
   vertsX = self.bubble_sort(vertsX)
   minX = vertsX[0]
   maxX = vertsX[len(vertsX)-1]
   # sort the array
   vertsY = self.bubble_sort(vertsY)
   minY = vertsY[0]
   maxY = vertsY[len(vertsY)-1]
   # sort the array
   vertsZ = self.bubble_sort(vertsZ)
   minZ = vertsZ[0]
   maxZ = vertsZ[len(vertsZ)-1]
   bounds_boxing = {0:minX,1:minY,2:minZ,3:maxX,4:maxY,5:maxZ}

**Comment by aothms** [comment]
If you use `settings.USE_WORLD_COORDS` you get an AABB, otherwise it is a local bounding box and you need to take into account `transformation.matrix.data`.

Other than that the code looks ok, not the most efficient, probably `sort()` is less efficient than `min(), max()` for large meshes.

You can also think about using numpy, e.g.

~~~py
import numpy

shp = ifcopenshell.geom.create_shape(...)

arr = numpy.array(shp.geometry.verts).reshape((-1,3))
minX, minY, minZ = numpy.min(arr, axis=0)
maxX, maxY, maxZ = numpy.max(arr, axis=0)

mat = numpy.eye(4)
mat[:3,:].T.flat = shp.transformation.matrix.data
numpy.dot(mat, numpy.array([maxX, maxY, maxZ, 1.]).T)
~~~

**Comment by whsqjss** [comment]
Thank you very much for your reply. It has benefited me a lot.
