### ISSUE TITLE
Library for steel shapes in the States

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3203]
Would be nice to translate the following into a profile library for US steel shapes...
https://www.aisc.org/globalassets/aisc/manual/v15.0-shapes-database/aisc-shapes-database-v15.0.xlsx

**Comment by Moult** [comment]
This is awesome! @theoryshaw do you by any chance have access to a US structural engineer who can confirm that this data source can be trusted?

Also ping @berndhahnebach do you know if bolts already has US data? I took a look and couldn't find any.

**Comment by theoryshaw** [comment]
this link is from https://www.aisc.org, The American Institute of Steel Construction (AISC)--which is 'the' organization around steel construction. 

The best way, probably, to confirm the data, is to spot check certain values from others on the internet.

**Comment by theoryshaw** [comment]
Ran across this fun little site in my searches: https://sections.app/catalogue/us/i_beam?units=fps

**Comment by theoryshaw** [comment]
...and this site: https://www.dlubal.com/en/cross-section-properties/

**Comment by theoryshaw** [comment]
I cross checked about 10 different shapes across various sites, and the data was consistent.

**Comment by Moult** [comment]
Awesome, assigning to @Andrej730 - that's a pretty awesome website too, but I couldn't find details about licensing, so best to grab it straight from the most official source.

We should definitely have clear documentation on how this information is parsed, what the sources are, how to update it in the future, and double check if we need to provide any more legalese related to "if the data is wrong and the building collapses it's not our fault". I wonder if @aothms has any suggestions on this.

**Comment by Andrej730** [comment]
Turned out US W profiles are [already part of bolts library](https://boltsparts.github.io/en/parts/standards/AISCShapesDatabaseV150.html) and by mistake I added them to EU Steel 🤦

Working on adding other types to https://github.com/boltsparts/boltsparts/ https://github.com/boltsparts/boltsparts/issues/11 and then to `IFC4 US Steel.ifc`.
Everything seems pretty straightforward and no need for arbitrary profiles but wanted to clarify on double L profiles (2L) - how should they be represented in IFC - `IfcCompositeProfileDef` of two `IfcLShapeProfileDef` or by some other way? @Moult 

Type |	Example url	| IFC Profile
|---|---|---|
W |	[W1100X499 - W44X335 (sections.app)](https://sections.app/section/bQ95BziOMUyLjMPhqMaa-Q/W1100X499)	| IfcIShapeProfileDef
M |	[M318X18.5 - M12.5X12.4 (sections.app)](https://sections.app/section/KO0KoC_VuEuW8ZyiQhApfw/M318X18.5?language=zt&units=si)	| IfcIShapeProfileDef
S |	[Structural Steel I-Beam Universal Flange Section Properties Sizes S3 to S24 (engineersedge.com)](https://www.engineersedge.com/standard_material/Steel_ibeam_s_properties.htm)	| IfcIShapeProfileDef
HP |	[HP460X304 - HP18X204 (sections.app)](https://sections.app/section/HwNWmOdW30Oc8SANBx2JXg/HP460X304)	| IfcIShapeProfileDef
C |	[C 15x50 Dlubal Software](https://www.dlubal.com/en/cross-section-properties/c-15x50-aisc-15)	| IfcUShapeProfileDef
MC |	[MC460x86 - MC18x58 (sections.app)](https://sections.app/section/eBYx8aRuR9yv0AAcSQ3Ryw/MC460x86)	| IfcUShapeProfileDef
L |	[L12X12X1-3/8 - L305X305X34.9 (sections.app)](https://sections.app/section/qIj86Xg0TH-yQ1dG6fRPrA/L305X305X34.9?language=en&units=fps)	| IfcLShapeProfileDef
WT |	[WT550X249.5 - WT22X167.5 (sections.app)](https://sections.app/section/AgET2BR4g0iPglBkzb94DQ/WT550X249.5?language=en)	| IfcTShapeProfileDef
MT |	[MT159X9.25 - MT6.25X6.2 (sections.app)](https://sections.app/section/RUHawF74DUO2UOvIB9Befw/MT159X9.25)	| IfcTShapeProfileDef
ST |	[ST12X60.5 - ST305X90 (sections.app)](https://sections.app/section/haxD-hvKAkesK9vndHp_kw/ST305X90?language=ko&units=fps)	| IfcTShapeProfileDef
2L |	[DoubleLShapeTable.pdf (cecalc.com)](https://www.cecalc.com/SteelShapes/Tables/DoubleLShapeTable.pdf)	| ???
HSS |	[Rect HSS 6x3x0.250 Dlubal Software](https://www.dlubal.com/en/cross-section-properties/rect-hss-6x3x0-250-aisc-14)	| IfcRectangleHollowProfileDef
PIPE |	[Pipe50XS - Pipe2XS (sections.app)](https://sections.app/section/IOtTMlkIDEmZn0txhn7hkQ/Pipe50XS)	| IfcCircleProfileDef

PS https://github.com/boltsparts/boltsparts/issues/11

**Comment by Andrej730** [comment]
Found a possible bug for W-type profiles in bolts library - https://github.com/boltsparts/boltsparts/issues/22

**Comment by Moult** [comment]
@theoryshaw is this something you can find a US structural engineer to help clarify?

**Comment by Moult** [comment]
@Andrej730 yes, I think a composite of two Ls is correct.

**Comment by Andrej730** [comment]
Added all profiles from AISC15. The issue mentioned above about W-type profiles problems also fixed.

Though data is not yet commited to official bolts repo: https://github.com/boltsparts/boltsparts/pull/24 https://github.com/boltsparts/boltsparts/pull/23
