### ISSUE TITLE
BlenderBim - Custom drawing scale on camera is not saved on reload of IFC 

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3209]
When setting a custom drawing scale size, it works fine but does not save on reloading/ reopening the Ifc 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/b7e4e7c0-3d1a-4221-aa89-910fcdc903dd)

**Comment by Moult** [comment]
Look related to this change which is incomplete https://github.com/IfcOpenShell/IfcOpenShell/commit/73a3cc2cc5e4783ee03519e94337ae81a0c716e3

**Comment by Moult** [comment]
@brunoperdigao FYI there were a few places where this custom scale parsing was used, so I migrated the scale parsing to tool.Drawing which means that now there is only one place to change the code and it'll work in other places too.

Rather than your string parsing, I also used Lark instead which is a very powerful and flexible token parsing library which means we can parse all sorts of imperial descriptions like `1' - 2 1/2"` etc.

**Comment by brunoperdigao** [comment]
@Moult Good to know. Thanks for the heads-up
