### ISSUE TITLE
Option to store relative path to .ifc in .blend

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#3219]
Seems very small thing but still - when you move your project folder with .blend and .ifc around (or send it someone else) then when you open .blend you need to load .ifc again from the new path. 

If we would support relative path for .ifc path it would make .blend file portable too.

**Comment by Moult** [comment]
Indeed, that's why the drawing system now prompts you to save (the IFC) before you can create a drawing.

I guess we can allow relative IFCs, but only if the Blend file is saved first. So if it detects that its saved, allow an "Is Relative Path" checkbox when loading a model similar to how we handle relative paths elsewhere.

Anybody feel free to help implement this :)

**Comment by Andrej730** [comment]
> Could relative paths be used for storing reference images with the .ifc as well?

@C-Claus what references do you mean?

**Comment by C-Claus** [comment]
@Andrej730 

For example a ```.png``` or ```.jpg``` which could be loaded with an image as plane in Blender, with the relative or absolute path of the file stored in IFC as a propertyset with the scaling, rotation and locationed also saved in an IfcPropertySet. Or maybe there is a way smarter way of doing things?

**Comment by Moult** [comment]
@C-Claus it's a good idea, can you open a new issue for it? With the work @Andrej730 has done with textures it should be trivial to do an "image as plane" option to support this.
