### ISSUE TITLE
Error after Shift-d

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3242]
If you shift-d anything object you get the following error

files: [Restaurant_Livingston.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11640199/Restaurant_Livingston.zip)

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 496, in execute
    context.view_layer.objects.active = self.new_active_obj
RuntimeError: Error: ViewLayer 'View Layer' does not contain object 'IfcWall/Wall.077'


```

**Comment by theoryshaw** [comment]
you warned :) .... i think it from this commit: https://github.com/IfcOpenShell/IfcOpenShell/commit/586707dd28d51d2d5f1bdc931a40e199e3f2f98c

**Comment by Gorgious56** [comment]
I cannot reproduce. This error means that you're trying to activate an object that is in a collection that is excluded in the current view layer. I don't think it's supposed to happen. 

Can you reproduce reliably ?

**Comment by theoryshaw** [comment]
Hi. Did you open the blender file first? We're  keeping the blender/ifc connection for this project  since we need to use blenders rendering/material capabilities.

**Comment by theoryshaw** [comment]
@Moult you wanted to know critical bugs, as it relates to this restaurant project.  This is one of them--well, that is, I can't update BB past https://github.com/IfcOpenShell/IfcOpenShell/commit/586707dd28d51d2d5f1bdc931a40e199e3f2f98c

**Comment by Gorgious56** [comment]
Yup, it's definitely a breaking change due to this commit. If you go to blend file view inside the outliner you'll notice some duplicated collections.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/71a3f385-b913-49c9-8cb3-f6e535a7fa5c)

 I think when you reimport the ifc file the ifc definitions are duplicated so the target wall is in an unlinked collection. The duplicated object with SHIFT + D is placed in collection that was not linked to the current view layer, hence unselectable, hence the error when trying to make it active. 

I don't think there is a trivial way to recover from it, I think you have to finish your project with the commit prior to this one.

You can try Right clicking on all the collections that finish with .001 in the outliner and choosing "Link to Scene" this should resolve the error but there is a high chance it will corrupt the file or lead to strange shenanigans, plus you'll lose your materials.

Maybe we can begin either thinking about serializing blender materials in property sets - or in [python scripts](https://blender.stackexchange.com/questions/214911/whats-the-most-reliable-way-of-converting-a-material-into-reusable-code-blocks), enforcing certain material on load per element type (like BIMVision does) or setting up a way to keep principled materials in ifc material styles (with transparency, roughness, etc.) - maybe we already can ? I've only tested simple diffuse color materials.

**Comment by brunopostle** [comment]
My understanding is that IFC already supports most of the blender material model. BlenderBIM needs some work to handle UV mapping, but otherwise it is nearly there.

**Comment by theoryshaw** [comment]
This is me behind https://github.com/IfcOpenShell/IfcOpenShell/commit/586707dd28d51d2d5f1bdc931a40e199e3f2f98c
;)

![giphy](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/96251e21-a0a5-46c7-92ac-05ee49c5bc28)
