### ISSUE TITLE
BlenderBIM Profile/ELEVATION_VIEW opening definitions

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#3256]
BlenderBIM supports defining a Profile/ELEVATION_VIEW representation in the Window/Door type that gets extruded for use as an opening (see #2474).

Something changed and now some of these are not working for me. See attached library containing a wall, window and door types: [profile-representation.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11646710/profile-representation.ifc.zip)

Two out of three of these openings have a broken opening geometry:

![Screenshot from 2023-06-04 22-15-07](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/c857ec1a-c1ca-4b02-a59b-a3020868f35c)

The difference is that the broken Profiles are defined by multiple `IFCINDEXEDPOLYCURVE` entities. I *seem* to remember that this used to work, at least BlenderBIM won't allow me to create a new Profile Representation that consists of a single `IFCINDEXEDPOLYCURVE`, so either way this functionality is non-functional.

**Comment by Moult** [comment]
You're right that this did work once upon a time at the very first implementation. This is because the first implementation actually created dummy objects and geometry which was crazily inefficient but at least it picked up on the entire shape. However it's been broken since Feb 10: https://github.com/IfcOpenShell/IfcOpenShell/commit/47e6352350835a72b9394e18a77fffa9ad1c00c1#diff-3bbed010d7096c14d7e13bc0aab593441241c39bacf2c180da29ddde305c7aa0R218

Good catch :)

**Comment by brunopostle** [comment]
Thanks, seems to be ok now:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/e0eb71bf-7eed-4f2c-98a7-db2e1ef30dd6)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/1747315/414d3ee6-62d0-41b2-9831-b34e2f099374)
