### ISSUE TITLE
BlenderBIm - Railing disaapears when adjusting in Z direction

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3262]
Using the new 'tab' function to edit profiles the railing normally looks like this:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/31eea4bb-56bb-46ce-bc8f-c860f10d85ed)

When adjusting the z direction it starts ok:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/7f4bf4d5-47f3-435d-adfb-49a3f24000eb)

But eventually disappears:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/be835a77-ab4b-4e99-bcda-8bb9418f4b37)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/4165cca0-57bb-4db0-937c-650f1a3a1cbd)

It you adjust it back it gets fixed, an dthe issue is only apparent on the wall mounted panel, the framless panel works in any direction:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/ab869562-d4d3-4262-8430-de78665eede3)

**Comment by Gorgious56** [comment]
I think there are 2 problems here.

The new tab workflow doesn't register that the object was modified if the underlying geometry wasn't modified. In this case it's wrong because if you double TAB it won't register that the geometry changed, because it didn't, but it also won't trigger a re-construction of the smart railing geometry, which it should. So when you go out of edit mode, the path geometry is kept. I can add a fix for that.

Second issue I don't think it has to do with the new "TAB" workflow. After a bit of testing the wall mounted railing produces mangled geometry when either of the ends of the paths does not end horizontally (on the same XY plane)

eg. good 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/6430b003-ee4f-4015-b316-8a437b76b40c)

bad

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/a3eb0d32-bee4-4ed7-9a28-c97801cdfa7d)


+ I uncovered a bug when trying to add a vertical segment to the railing path. #3263

**Comment by Plae-Blue-Dot** [comment]
Thanks @Gorgious56 for the quick changes! 
And thanks for the new tab edit, it has made doing, railings especially, so much faster!

**Comment by Gorgious56** [comment]
I believe this bug is still present with wall mounted handrails

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/a3eb0d32-bee4-4ed7-9a28-c97801cdfa7d)

**Comment by Andrej730** [comment]
It seems that IFCARCINDEX right IFCLINEINDEX that was climbing by Z is creating this bugged representation with IFCSWEPTDISKSOLID. If I add some straight segment that doesn't change Z before the arc it seems fine.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/9b0a3993-af20-42e9-a74a-c73035cd0537)
[railing_bug.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12081548/railing_bug.ifc.txt)

@Moult can you please take a look - any ideas what can cause this?

**Comment by Moult** [comment]
I think this is why:

> Directrix given as IfcIndexedPolyCurve, having linear and circular arc segments, **that are tangent continuous between each segments**

Also

> Informal proposition restricts the permissible angle between two non-tangent continuous segments.

That probably explains why it "works up to a point" and then breaks. I think @aothms will know for sure.

There are a few ways I can think to solve this:

 1. Disable railing end turndowns if the end is not horizontal (not a fan)
 2. Change the calculation of the end turndown to be the appropriate angle if the end is not horizontal (my preference)

Thoughts?

**Comment by Andrej730** [comment]
>Change the calculation of the end turndown to be the appropriate angle if the end is not horizontal (my preference)

What do you mean? To add some small segment before turndown to compensate the difference in tangents?

- That's how it is currently:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/cb42597c-5aee-414a-a359-9096aaf8c9de)

+ segment to compensate non-tangent segments:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/ed3896f7-afde-46ae-aaec-f0ad5aac2eab)

**Comment by Gorgious56** [comment]
I think it depends a bit on the disability requirements in different countries, I don't know if this would be accepted in mine (France). As a matter of fact ending railings diagonally like that in public spaces is not authorized AFAIK. At least I don't remember having seen them. Intuitively I'd rather have a small horizontal segment so that the ends are always tangentially horizontal

**Comment by theoryshaw** [comment]
Like this...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/1fa9c80b-f3ee-404f-a31f-735d29b724ee)

**Comment by theoryshaw** [comment]
This..
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/aa1e3278-cf48-4fe7-b7ad-2dba9a529d94)
 
and this?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d0b51dd0-4b9d-4e70-b9a4-e86563ee0470)


are the same, are they not?

**Comment by Andrej730** [comment]
@theoryshaw 
first one implies there will some straight segment right after the vertical segment so that it will possible to insert horizontal end

the second one is kind of like this - last vertex of the vertical segmented has a bit of an offset to insert the terminal

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/8794a1ff-1ad4-4fc0-8575-f9c42391253b)

**Comment by Moult** [comment]
> I think it depends a bit on the disability requirements in different countries

Agreed, in Australia you need a 300mm horizontal past the last tread (so it ends up usually being around >=550mm).

However if the user hasn't modeled this horizontal... we can't insert it for them, so we assume their intention is to terminal diagonally (which may or may not be legal ... maybe its allowed in industrial projects? They've got different rules) If we do insert a horizontal, how long should it be?

The picture I proposed is not the same as Andre's. Notice how in mine the 180deg semicircle is rotated to be tangent-continuous with the railing. In Andre's picture, the 180deg semicircle is not rotated.

![2023-07-20-094124_461x444_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/14a0fa16-0117-4f2a-a997-ff79117668dd)

**Comment by Gorgious56** [comment]
Yup after a bit of thinking it makes sense having diagonal ends, we shouldn't enforce arbitrary disability code if the user doesn't explicitely want it.

**Comment by Andrej730** [comment]
Fixed it to be the similar to this

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/04eae0f4-d55e-4556-858b-7687b09c96af)
