### ISSUE TITLE
How to port pythonocc-core funtion to C++ occ for speedup : python extension, swig, ?

### ISSUE THREAD

**Issue by cvoivret** [IfcOpenShell/IfcOpenShell#3269]
Hi, I have written a function to compute shadows on a BIM model. In addition of ifcos, it rely heavily on opencascade boolean operations and I have a python implementation that is functionnal and can be seen here : https://github.com/cvoivret/shadow_bim_code/.
I'm thinking to implement this function directly in C++ with opencascade to have better performance.
The idea is to replace a function composed of multiple call of pythonocc-core by a single function written in C++ and wrapped in python.
Since the python API and C++ API are very close, writing the code would not be a problem (I hope).
After some digging, I not sure about to the good ways to wrap the c++ function code back to Python.
My main concern is that pythonocc-core is based on swig and all occ object are exposed trough swig object.
I feel that, if I do not wrap my c++ function with swig, the returned OCC object will not be compatible with those generated with pythonocc-core...
Since I am a total noob in wrapping, I ask for guidance on this point.

btw :if you are interested by the code itself, I will be happy to share how it for to compute shadow or find exterior wall of a BIM model.

**Comment by aothms** [comment]
Hi, this is very cool. I am not convinced that porting the code to C++ is the best way forward. The libraries you use are all already C++ libraries, so you need to be really sure the computation time is spent within the "glue" i.e the actual python code and the interaction between the various APIs and not within one of the function calls that is already written in C++ itself.

The approach you have taken (I've only scrolled through the code) is simply fundamentally computationally expensive. First use a profiler to really see where the processing time is spent.

Some random comments:

- Typically people use shadow maps for this. I.e render from light source direction to a depth texture and then for every element fragment relate the 3d distance to light source to the value from the depth texture.
- You can take a look at what we do here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/draw.py We use OpenCASCADE's hidden line rendering (which only gives you unconnected edges) and then a routine to fill the network of edges with cells. You can use a similar approach to draw from the light source direction and unproject those cells again to 3d
- Alternatively you could use BRepOffsetAPI_NormalProjection to more early on your process get solids to 2d faces and perform boolean operations on the faces. This kind of dimensionality reduction will speed up the process significantly.
- Have a look at what https://twitter.com/topologicBIM/status/1649109676955402264 is doing

If you really want to go the C++ route I would probably recommend to write it in C++ altogether and forget about the wrapper. Open CASCADE is actually more pleasant to write in C++ because of various implicit casts and you get static typing.

**Comment by cvoivret** [comment]
Hi @aothms, thanks for the quick and (very informative) answer.
A little bit of context to explain my choice for costly boolean operators : a french regulation use average exact shadow area to assess solar protection. My goal, as "researcher" funded by a public project was to design a method that can be implemented in most of the BIM authoring tools. The idea was to design an algo that can be implemented with API (REVIT, ifcos...). The boolean operations is a common features of such APIs and make it quite simple to implement. The price to pay is the speed of execution that depends heavily on the kernel performances itself. I currently finalizing a paper on that (ifcos cited !).

Concerning your random but pertinent comments : 

- as far as I understand the concept, the shadow map is used to render pixel  values. In other words, discretized object. Since I'm interested in exact shadow area, I don't know if it suit my purpose.
- I will take a look at HLR... I would never have thought to use such algorithm but it make sense. It was only for me a visualization tool.
- BRepOffsetAPI_NormalProjection : I will take a look and keep in minds the tips about faster 2D boolean operations.
- I was aware of topologicBIM and the impressive showcases. I was (quite) fine with occ so I have decided to not dig into another library. Btw, I must have missed something because I do not see the benefit of topologicbim for  boolean operations...
