### ISSUE TITLE
Regression when converting IFC4 – objects missing

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#328]
There seems to be a regression when converting IFC4:

Steps to reprocuce:
1. Convert [AC20-FZK-Haus.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1736299/AC20-FZK-Haus.ifc.zip) with IfcOpenShell 162b665d073be260d06b742734ab40ff1e72a5cc OCCT v7.2.0.
Experience that walls are missing:
<img width="804" alt="screen shot 2018-02-19 at 11 16 59" src="https://user-images.githubusercontent.com/4601554/36373126-71c022ae-1567-11e8-9de5-8af9253d45d7.png">
2. Convert the same file with IfcOpenShell 8d0c95a9391f887e262e95cec646dca2c59ceadf, OCCT v7.2.0. Experience that the walls are not missing:
<img width="718" alt="screen shot 2018-02-19 at 11 20 55" src="https://user-images.githubusercontent.com/4601554/36373217-aaae7188-1567-11e8-98c7-f3915b75560c.png">

**Comment by aothms** [comment]
Interesting, thanks. I didn't know there were IFC4 version of these Karlsruhe models.

The representation reuse detection in IfcGeomiterator is very fragile. It picked up the IfcWallTypes with RepresentationMaps as an indication that the representations were shared instances that cannot be reused due to the openings. That's why exactly the walls with openings were missing.

I didn;t get a missing roof though initially, is that an issue specific to OCCT 7.2?

Your other issues are still on my list btw, just taking more time as I still dont have 7.2 on my system.

**Comment by aothms** [comment]
5d0c04a0770be81fc8efe2f39cda440d0550284d

**Comment by johanrd** [comment]
Thanks! I can verify that commit 5d0c04a solves this.

I can try to se if i can set up another OCCT (e.g. 7.1), and se if the other issues happens with with other versions than 7.2 as well.
