### ISSUE TITLE
Regression: `Error in: gp_Dir() - input vector has zero norm` (reproducible example files)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#329]
Steps to reproduce:
1. Convert [ReinforcingBar.ifc.zip ](https://github.com/IfcOpenShell/IfcOpenShell/files/1751736/ReinforcingBar.ifc.zip) or [ReinforcingMesh.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1751798/ReinforcingMesh.ifc.zip)  with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0)
2. Experience error: 
```[Error] ContextType 'Annotation' not allowed:
#26=IfcGeometricRepresentationContext($,'Annotation',3,1.E-2,#19,#21)
[Error] {3QhkDhZf9ADgvXKJk4QgqZ} Closed gap on:
#32=IfcCompositeCurve((#33),.F.)
[Error] {3QhkDhZf9ADgvXKJk4QgqZ} Error in: gp_Dir() - input vector has zero norm
Failed to convert:
#31=IfcSweptDiskSolid(#32,8.,$,0.,1.)
[Error] No geometrical entities found

FATAL: An error occured, status code 1.
```

There are no errors when converting with 8d0c95a9391f887e262e95cec646dca2c59ceadf (OCCT v7.2.0 or v7.1.0), so this is seemingly a regression.

**Comment by johanrd** [comment]
The same thing also seems to happen with this object: [ReinforcingMesh.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1751795/ReinforcingMesh.ifc.zip)

**Comment by aothms** [comment]
Well this is truly a bug I introduced myself :) In order to fix invalid boolean operands I implemented code to automatically close composite curves #270. Naturally, this should not happen for all composite curves. This is the downside of the generic approach of converting representation items. Ideally you would want different conversion options based on the context in which an item is used (e.g. face boundary or sweep axis), but the current architecture does not allow that. I do a quick check for inverse attributes now, but might need additional work.
