### ISSUE TITLE
Regression: Segfault on ReinforcingBar (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#330]
Steps to reproduce:
1. Convert [ReinforcingBar--segfault.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1751847/ReinforcingBar--segfault.ifc.zip) with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0 or v7.1.0)
2. Experience segfault: 
```FATAL: An error occured, status code 139.```

There are no errors when converting with 8d0c95a9391f887e262e95cec646dca2c59ceadf (OCCT v7.2.0), so this is seemingly a regression.

**Comment by johanrd** [comment]
FYI: The same thing also happens with [Beam--segfault.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1751878/Beam--segfault.ifc.zip). Not sure if the regressions are related, though. Feel free to split into two issues if not related)

**Comment by aothms** [comment]
For the reinforcing bar there is a gap in the composite curve of 3.80561e-04 m, which is above the modelling precision, so this gets filled now with an edge. I bet this small edge is causing issues though in OCCTs modelling algorithms when a swept disk is created out of the wire. I guess for small gaps, edge end points need to be moved rather than segments added.

**Comment by aothms** [comment]
The beam processes correctly for me on latest code base.
