### ISSUE TITLE
Creating an IfcSpatialZone does not create a blender collection

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3326]
Creating an IfcSpatialZone does not create a blender collection.  Not sure if that was indented, or not.

![2023-06-19_16-42-16_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/1b9a66b6-32c5-40f3-af00-8e75bb75e836)

**Comment by theoryshaw** [comment]
I created a manual collection and renamed it to `IfcSpatialZone/Empty` and tried to assign an object to that container.  Didn't seem to work...
![2023-06-19_16-45-02_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/e48dc53f-98dc-4c42-ba41-98f85de3d75c)

**Comment by Moult** [comment]
Spatial zones are not hierarchical so they are not meant to create a collection.

You are not meant to "contain" an object in a spatial zone, but instead "reference" the spatial zone (since it is non-hierarchical and potentially overlapping, that's why it's merely a reference). You can reference it by in the IFC Spatial Container panel browsing to it, using the checkbox to select it, then pressing the paperclip to reference (or dereference with the broken clip icon). Then press "cancel" (yeah it's weird) and you should see it's referenced.

So the functionality works, but the UI is clearly not obvious. How would you propose we improve it?

**Comment by theoryshaw** [comment]
Even though it's not hierarchical, why not have the UI act the same way as IfcSpatialStructureElement?  That is, use collections, since vanilla blender allows an object to be in multiple collections. 
Perhaps i'm missing something.

**Comment by theoryshaw** [comment]
I figured there was more to it. 
If all things being equal..
:)
