### ISSUE TITLE
Weird shading on import to Blender 3.6

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#3336]
Haven't investigated it yet but when you load .ifc in Blender 3.6 it loads with broken shading.

Example file (just a cube) [cube_blender_36.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11833201/cube_blender_36.ifc.txt)

![Screenshot 2023-06-22 160538](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/9b12b54d-c6f7-4752-980b-97dcc7f00538)
![Screenshot 2023-06-22 160452](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/03fbae38-e85c-4056-8084-a65afe4b6faf)

**Comment by Gorgious56** [comment]
3.6 is still in Beta so it might be a bug, in which case you can report it to the devs. Can you share the .blend after importing the ifc ?

**Comment by Andrej730** [comment]
@Gorgious56 sure [cube36.blend.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11833775/cube36.blend.txt)
Blender 3.6 is in beta but it's now in "Prepare Release" stage and they are going to release it next week

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/3b57a725-8c83-41eb-a8dd-8ed53e6b1643)

**Comment by Gorgious56** [comment]
So it's not really broken shading, it is smoothed shading, you can fix it with right click > shade flat or enabling normals auto-smooth in the geometry properties. As to why the polygons of the mesh are imported with smooth turned on is a good question. , that is a good question. I think it is due to this commit which ported the smooth / flat flag to an attribute

https://projects.blender.org/blender/blender/commit/5876573e14f434a4cd8ae79c69afbe383111ced9

**Comment by Andrej730** [comment]
Reported it to blender - https://projects.blender.org/blender/blender/issues/109252
Added some fix 4a36893
