### ISSUE TITLE
When converting models, data is lost

### ISSUE THREAD

**Issue by MrSpock45** [IfcOpenShell/IfcOpenShell#3344]
After convert part of elements disspaier.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/87139614/903563dc-5fb4-40cc-867e-b1290adef0c5)
Example files
[example files.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11859145/example.files.zip)

Notes
1.Element tree structure disappears
[marriage registry.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11859150/marriage.registry.txt) (maby it's help)
2.Not only the number of elements, but also the characteristics (lower right panel properties in https://openifcviewer.com/) of elements + name in elements

**Comment by Moult** [comment]
IfcConvert is a app that converts between different data schemas. Therefore, what is converted depends very much on the settings you provide as well as the capabilities of the output data schema / format (e.g glb)

glTF/glb can only store a very small percentage of the data that IFC can store. It is impossible to keep all the IFC data. It's like saying saying you're taking a screenshot of a spreadsheet, and the screenshot loses cell formulas.

This is true for any other conversion / import / export. For example if you import IFC into Revit / ArchiCAD / Tekla / 12D / Navisworks / etc, you will lose a huge amount of information too.

If you want to work with IFC without losing information, you can either work directly in native IFC software, or you can also "reserialise" (which is very similar to conversion, except there is no data loss) to another IFC format. For example, you can "reserialise" .IFC to .JSON or .SQLITE and you won't lose any data. Alternatively, most native IFC software, like most IFC viewers will also preserve all the information. The ODA viewer as you've noticed is one such software. Another example is the BlenderBIM Add-on or FreeCAD. If you want to edit, not just view, you can use the BlenderBIM Add-on: https://blenderbim.org/

**Comment by aothms** [comment]
In addition, when converting to the geometrical formats such as DAE/GLB/OBJ no effort is made to present any form of meta-data (also because it would be either inefficient or unstructured). But you can convert to XML. See https://github.com/AECgeeks/ifc-pipeline / view.ifcopenshell.org/ which can take a GLB+XML to recreate the typical bim viewer you are referring to.

**Comment by arpu** [comment]
How would a  GLB/Gltf extensions and spezification work for all the Ifc data?  tahn this could be a good standard in glb/gltf world 

https://github.com/KhronosGroup/glTF/blob/main/extensions/README.md

**Comment by aothms** [comment]
Well, the extensions are more for data that would result in extra graphic features. I think for supplementary meta-data you would use:

> All glTF object properties allow adding new properties to an `extras` object sub-property, e.g.,
>
>```
>{
>  "asset": {
>    "version": 2.0,
>    "extras": {
>      "guid": "9abb92a3-39cf-4986-a758-c43d4bb4ab58",
>    }
>  }
>}
>```

An I would use that guid to reference an external database.

As I said earlier, transporting all meta-data into the glTF would be rather inefficient.

**Comment by aothms** [comment]
The geometric output formats use the hexadecimal encoding of the guid
because xml doesn't allow $ characters in ids. It's prefixed with product-
because xml ids cannot start with a numeric char. Postfixed with context
identifier, typically "body".

See https://github.com/AECgeeks/IFC-pipeline for a working example
including JS to do the matching.

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op ma 3 jul. 2023 13:42 schreef chupalovaa ***@***.***>:
