### ISSUE TITLE
Regression: Segfault on beam with OCCT 7.2.0 (3 example files)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#336]
Steps to reproduce:
1. Convert [beam--segfault2.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1758248/beam--segfault2.ifc.zip), [beam--segfault3.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1758249/beam--segfault3.ifc.zip) and [beam--segfault4.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1758252/beam--segfault4.ifc.zip) with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0)
2. Experience segfault: 
```FATAL: An error occured, status code 139.```

**There are no errors when converting with:**
• 5d0c04a0770be81fc8efe2f39cda440d0550284d + OCCT v7.1.0
• 8d0c95a9391f887e262e95cec646dca2c59ceadf + OCCT v7.2.0. 

Conclusion: This is seemingly a regression when using 5d0c04a0770be81fc8efe2f39cda440d0550284d with OCCT v7.2.0 specifically.

**Comment by aothms** [comment]
![2018-03-10 11](https://user-images.githubusercontent.com/1096535/37242324-d7c53008-2467-11e8-847a-c7db02d8a15e.png)

This is interesting.

The issue appears to be OCCT splitting a face into two, but not realizing it and therefore at some point writing a compound to the face structure, instead of two separate faces.

But there's more going on

The triangles actually consist of 4 points. 

~~~
#29 = IFCCARTESIANPOINT((0., 0.));
#44 = IFCPOLYLINE((#29, #45, #46, #47, #29));
#45 = IFCCARTESIANPOINT((2.52953220167547, 8.14907252788544E-10));
#46 = IFCCARTESIANPOINT((1.91052950204175, 2.45261812326498));
#47 = IFCCARTESIANPOINT((2.08844534063246E-3, -4.58190671633929E-3));
~~~

`#47` and `#29` are close, but above modelling precision.

~~~
#16 = IFCGEOMETRICREPRESENTATIONCONTEXT($, 'Model', 3, 1.E-5, #17, $);
~~~

Even under a higher tolerance, it seems `remove_duplicate_points_from_loop()` ends up deleting `#29` instead of `#47`, because it's a poly**line** and not a poly**loop** so in theory not closed necessary. This ought to be fixed.

But even with `#47` eliminated from the loop, the geometry does not render complete correctly.

**Comment by johanrd** [comment]
Closing, as this is not reproducible anymore when building from commit 1f68d9d5bcfda6ce6b7ff6e86733faf835247242
