### ISSUE TITLE
Loading an IFC file after Blender crashes produces some strange behavior

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#3361]
I am not sure exactly what caused this issue, but I will try and explain what happened.

Blender crashed when I tried to undo an action that BBim generated an error for. Then I re-opened Blender and loaded my last saved IFC file. At first Blender wouldn't open a drawing camera but after a few times of loading the same file it would let me open the drawing (which is weird because I didn't make any changes to the file). However, Blender was still crashing when I tried to print a drawing. I then duplicated and renamed my IFC file in the system file browser and loaded the renamed file and everything was restored.

So there might be more than one issue here. As a user, the first bug I experienced was BBim throwing out an error for an action I can't remember, it could have been trying to add a dimension when while in the edit mode of another dimension, but I can't be sure.

The second bug, was that Blender crashed when I tried to undo an action immediately after BBim posted an error.

The third bug, was Blender crashing when I tried to open or print a drawing. This issue completely went away when loaded a renamed version of my IFC file. Maybe it was a caching issue to do with the undo??

I was going to attach my file, but when I renamed it, my issue went away so there didn't seem much point.

**Comment by Moult** [comment]
I think your analysis is spot on. The root cause is the first error. Unfortunately without knowing the error, we can't fix it.

Depending on the error, it could leave the undo stack in a bit of a weird state, and therefore undo would lead to a crash. This is not something we'd tackle in alpha, we'd tackle the underlying root cause, which unfortunately we don't know.

Then when you tried to open or print a drawing, by default there is a geometry cache in use which is paired to the filename, which is why renaming the IFC fixed it. You can manually clear this geometry cache by pressing the "Purge HDF5 Cache" button in Scene Properties > IFC Quality Control > IFC Debug.
