### ISSUE TITLE
Segfault on buidlingElementProxy (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#338]
Steps to reproduce:

1. Convert [338--buildingElementProxy--segfault.ifc](https://github.com/IfcOpenShell/files/blob/master/338--buildingElementProxy--segfault.ifc) with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0 or OCCT 7.1.0)
2. Experience segfault: 
```FATAL: An error occured, status code 139.```
3. Expected geometry from SimpleBIM (however neither DDS nor Solibri seem to render any geometry):
<img width="250" alt="screen shot 2018-09-20 at 00 19 27" src="https://user-images.githubusercontent.com/4601554/45784993-f81cea80-bc6a-11e8-8d2c-7f8808193222.png">

The issue may not be very important (ref. the behavior of Solibri and DDS), however the segfault may be worth looking into nevertheless.

**Comment by aothms** [comment]
There's actually quite a bit of complicated stuff going on here. Faces on resolved circular arc segments (IFC didn't have a spherical or toroidal surface till IFC4 Add2). So I'm not surprised other viewers don't make much sense of it. On the other hand there's a quite a bit of flaws in this file as well, edge vertices that don't project onto the edge curve, etc.

There is a fundamental problem with the way non-elementary surfaces are handled in IfcOpenShell because there is a not a clear mapping to OCCT surfaces (for example a extrusion of a non continuous polyline) is a surface in IFC, but this is either an adaptor surface or a shell in OCCT.

As much as I'd like for IfcOpenShell to handle all kinds of advanced concepts, I don't think it is worth the effort currently to work on this file. Also, considering its flaws.

**Comment by aothms** [comment]
The segfault is resolved and we now get somewhat similar geometry as the picture above. It's a BBQ!

![afbeelding](https://user-images.githubusercontent.com/1096535/50538887-61b86900-0b77-11e9-995a-3bf79be96e4c.png)
