### ISSUE TITLE
Error after `bpy.ops.bim.activate_model()`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3383]
If you open [this](https://gitlab.com/openingdesign/milwaukee_st_4429/-/blob/ade5dd4b8a54a5076bb952c7dc2d4d05689d0e8a/Models%20and%20CAD/Milwaukee_st_4429.ifc) file, and `bpy.ops.bim.activate_model()`
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/46950a6a-dd92-497e-b026-919a8e6daf6b)
on a drawing like `OPTION 1` it gives the following error. 

How does one track down, and delete the offending object(s)?

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1279, in execute
    blenderbim.core.geometry.switch_representation(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\core\geometry.py", line 102, in switch_representation
    data = geometry.import_representation(obj, representation, apply_openings=apply_openings)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\tool\geometry.py", line 282, in import_representation
    shape = ifcopenshell.geom.create_shape(settings, element)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 2378, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process shape

```

**Comment by Andrej730** [comment]
Added more descriptive error message
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/74759fa7-6490-4132-9a98-11cc22454712)

**Comment by Moult** [comment]
Sorry, not a fan of this fix. I don't think we should be putting try catches everywhere whilst we're in alpha (later as we move to beta a more robust error catching strategy needs to be in place but not in alpha).

I'd rather find and fix the fundamental problems first.

**Comment by Moult** [comment]
So the root cause seems to be that the covering with id 497002 has an extrusion direction perpendicular to the Z axis which is not allowed. We don't know exactly how it happened, but one suspiciously likely possibility is that the X angle was set to 90 degrees (>=90 is invalid). I say it's likely because it'll generate the vectors very similar to what is causing the problem and there aren't really many other ways to adjust that value.

The appropriate way to do a general check for broken geometry is to run the "Test All Shapes" button in the IFC Debug panel. This works for all scenarios when you suspect something is funky. Check the console and you'll see a list of failures at the end. In this case your file has two failures, an opening (which doesn't harm anybody right now, it's not linked to anything, but definitely invalid) and that covering (which I'd say is safe to delete).

https://github.com/IfcOpenShell/IfcOpenShell/commit/3126db342dd6063eadebf6b925b8942eab99984d

**Comment by Andrej730** [comment]
But shouldn't we give info to user what shape they should investigate to finish performing the current action?
I just thought new users wouldn't know what to do if they just met "RuntimeError: Failed to process shape".

**Comment by Moult** [comment]
In the future, yes. Whilst in alpha, I'd prefer not to. The reason is that I've seen users actually not report bugs (or report it too late) in alpha if the bugs seem too much like "normal behaviour" and not severe enough. This can harm stability in the long term when we don't catch the root causes of bugs earlier. I've unfortunately first hand experienced some of this in FreeCAD's BIM implementation which was a little too accommodating of invalid states too early and led to a lot of weird behaviour.

**Comment by theoryshaw** [comment]
Is it worth having something in the debug panel then?

**Comment by theoryshaw** [comment]
The other argrument would be knowing which is the offending object, i as a user can recollect better what i maybe did differently when creating object, and thus can report the bug better.

**Comment by Moult** [comment]
@theoryshaw yes, the "Test All Shapes" in the IFC Debug panel. The added benefit is you can run that anytime, even before you've hit a bug, or if you hit a bug on any other possible operation that says something related to "unable to process shape".
