### ISSUE TITLE
Generate space fails

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#3391]
# Issue description
Users report that sometimes space generation fails for unknown reasons

# Step to reproduce
1. Import [cube.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11970745/cube.zip)
2. Delete current space
3. Make sure that the IfcBuildingStorey collection is active
4. Place 3D cursor inside the 4 walls and try to generate space
5. On tested systems it fails without error message

# System infos
* OS: Windows | Linux
* Blender version: 3.4, 3.6
* BlenderBIM version: v0.0.230701 |  https://github.com/IfcOpenShell/IfcOpenShell/commit/9c4fa666c99c10fd6b2cf09e416764a8254d5a81

**Comment by maxfb87** [comment]
@CyrilWaechter i found the problem.
It is caused by the the wall called "IfcWall", it isn't typed like the others so it hasn't the LayerSetDirection = AXIS2 like the other walls.
The script "generate_space" considers only IfcWall that has the usage type = LAYER2  see [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/844cc629607bbd02488334310cf0df9e034b860c/src/blenderbim/blenderbim/bim/module/model/space.py#L93)
If you try to delete the second part of the if statement in that line (and tool.Model.get_usage_type(subelement) == "LAYER2") "generate_space" works ok...

I don't actually know why it checks it so let's ask to @Moult : why "generate_space" checks if the IfcWall has the usage type = LAYER2?

**Comment by Moult** [comment]
It checks for LAYER2 because that's the only time we can assume that the wall is actually a prismatic extrusion based on an axis line. Any other non-LAYER2 wall can be an arbitrary wonky funky shaped wall and therefore we cannot use our heuristics to determine the wall boundaries.

A more complex, expensive method would need to be used, which we have yet to build support for. This might involve:

 1. Determining a calculation cutting plane to figure out a closed 2.5D polygon, similar to how we generate drawings.
 2. Using voxels to work out complex 3D shapes.
 3. Requiring the user to specifically draw a simple VirtualElement boundary to close uncertain or complex forms.

**Comment by CyrilWaechter** [comment]
So why `Generate Spaces From Walls` works ? It uses a more expensive way ? If so cannot we use it as fallback ?

**Comment by maxfb87** [comment]
@CyrilWaechter it works because when i wrote the script i didn't assumed it :-)

**Comment by maxfb87** [comment]
@CyrilWaechter you can check the code in the same file "space.py", simply i didn't wrote the type layer2 check when looking for the walls...

**Comment by maxfb87** [comment]
@Moult thanks for the explanation, it makes sense.
I was thinking btw that we could remove the "layer2 check" for now just because all the procedure is based on the fact that walls are prismatic and it is actually the only automatic procedure for generate spaces...
If we had different procedures for different wall shape (prismatic, curved, etc...) we should check but for now maybe it's redundant...

We should also improve btw the actual script in order to support more wall shapes, at least the more common ones like curved walls or sloped roofs

I would like to better understand the n.1 method you suggested (because voxel is too much complex for me right now and i don't like that user could model the boundary).
Could you point me the code to better understand the n.1 approach? Thanks...
