### ISSUE TITLE
Drawing contains extra coplanar edges and incorrect fills

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3421]
These issues might be known already, but wanted to share a few drawing glitches from a specific project. 

Files: https://gitlab.com/openingdesign/restaurant_livingston/-/archive/40cdb2cf5764ece346fbfb564a1cbb01ce5254b0/restaurant_livingston-40cdb2cf5764ece346fbfb564a1cbb01ce5254b0.zip?path=Models%20and%20CAD/BB%20Model

Glitches, noted in red:
https://www.tldraw.com/v/FBWD1KHTbzKIS0pVts0of?viewport=-14665%2C-2670%2C11104%2C5419&page=page%3ANzqGhTebPyOtY7wrs68hP

**Comment by Moult** [comment]
One of these shapes seem weird. I've checked and the shape is manifold and sane, so I've simplified it and was able to recreate the issue. Ping @aothms to take a look at this. This is the shape:

[untitled2.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12046263/untitled2.ifc.txt)

Here's the cut I'm doing through the shape:

![2023-07-14-144209_744x223_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/c0cb8684-cfb9-4fb1-a8f9-16dafba3b563)

Here's the shape I've got (simplified and extracted from your file):

![2023-07-14-144218_767x536_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/643ccb68-e45e-4ac2-a9d2-8828617d8d75)

@aothms as you can see IfcOpenShell actually returns two paths in the product group instead of one:

![2023-07-14-144234_1129x242_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/91345370-fe96-4048-a04e-747c16d3b80f)

This causes the fill artifacts that @theoryshaw is reporting:

![2023-07-14-144246_1158x348_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/03fc522b-22cd-473a-819c-1742514c4132)

Shouldn't it only return one closed path?

**Comment by Moult** [comment]
@aothms another thing I noticed is that in build 8f41ae0 (prior to the prefilter build) the tables projection drawing shows up fine. However in the fc50bdd build (prefilter enabled) the tables disappear (this then causes other artifacts like spillover fills but ignore that - the primary cause is the invisible tables).

Here is 8f41ae0 - things look good:

![2023-07-14-172402_1133x898_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/fdf5f0b0-09e5-41d9-a189-89093574235f)

Here is fc50bdd - prefiltering is enabled:

![2023-07-14-172408_1106x835_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/a38d03ec-0a7e-4618-90d6-ed1cb254e35e)

**Comment by Moult** [comment]
OK, I've fixed the filled bugs (well [one of the fixes](https://github.com/IfcOpenShell/IfcOpenShell/commit/69fa12423dd2a9a2a40634ea90400ca7bd3cb2dd) ideally can be solved at the C++ level by @aothms but for now there is some postprocessing).

For the extra edge bug I think it's a duplicate of #3158 which @aothms needs to investigate. Basically these types of coplanar edges on tessellations shouldn't show up in drawings. I however find it odd because only one is a tessellation, whereas the other seating element seems to be a swept solid with a bunch of booleans. Maybe IfcOpenShell tessellates it too due to the booleans? Dunno.

![2023-07-14-173411_711x469_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/d2ab833e-cb54-4fef-a2bf-589d40f12017)

Here's the solid one:

![2023-07-14-173820_1014x375_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/a2520265-3cba-49a0-9a50-291d725d3e55)

**Comment by Moult** [comment]
Removing my assignment in the project because that's the limit of my capabilities :)

**Comment by Moult** [comment]
Ah whoops closed this prematurely I thought it was only a duplicate but there is actually the issue of the two paths instead of a single closed path that @aothms might need to investigate.

**Comment by theoryshaw** [comment]
closed via https://github.com/IfcOpenShell/IfcOpenShell/commit/dadcbe61ea432ffde3c46a943e9cac2476f39e69!
