### ISSUE TITLE
Easy way to create a new ifc material at typical dropdowns

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3452]
Would be nice, anywhere this material dropdown occurs, that there's a button to create a new IFC material as well. 

![2023-07-14_16-11-52_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/4fe2b354-ecc3-4c7b-8483-859bc4134499)

**Comment by Gorgious56** [comment]
This is a general purpose popup panel that is displayed every time the number of potential items in an enumerator is > 10. 

https://github.com/IfcOpenShell/IfcOpenShell/blob/a101f46478a3ceb6aab0f491c7f2a363c8090365/src/blenderbim/blenderbim/bim/helper.py#L190-L201

I don't think it's a good idea to add functionality to this panel since it's already a [very hacky feature](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/operator.py#L814-L870) (my own creation, not my proudest achievement :p).

So maybe we can brainstorm how to add this feature gracefully. Just so I understand, you want to be able to add a new MaterialLayerSet with a new IfcMaterial using a single click in this interface ? Because right now, you can add a new MaterialLayerSet but you have to use an existing material, and then you have to click several times in the interface to be able to change the underlying IfcMaterial ?

**Comment by theoryshaw** [comment]
>Just so I understand, you want to be able to add a new MaterialLayerSet with a new IfcMaterial using a single click in this interface?

Correct. 

But also from other areas where this material search pops up... 

That is, to create a new IfcMaterial when in the following modes as well...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/ce16a52a-7105-4aca-9454-a777c8196497)

**Comment by Moult** [comment]
I think let's hold off from investigating this further until the new material and styles UI is designed.

**Comment by Moult** [comment]
Closing because you can now easily create new materials, and the material manager is directly below object material assignments.
