### ISSUE TITLE
BlenderBIM version does not update in settings -> edit -> addons -> BlenderBIM

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#3462]
When using the Live development environment, the verision remains the same in the settings -> edit -> addons -> BlenderBIM after git pull executed on IfcOpenShell.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/docs/devs/installation.rst#live-development-environment

Is this something that can be easily fixed?

**Comment by theoryshaw** [comment]
+1
@Andrej730 had a similar sentiment. 
https://github.com/IfcOpenShell/IfcOpenShell/issues/3356#issuecomment-1622326378

**Comment by Andrej730** [comment]
Currently there is commit hash in blender status bar added in dd0a015ec3e3dbf37de9a4cf0139c9ff22bc872c
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/55f34114-837a-4e16-84bb-740fcc54e7be)

**Comment by Gorgious56** [comment]
Maybe instead of v0.0.999999 we could display "Live build" or something like that + the last commit hash ?

**Comment by theoryshaw** [comment]
...and also, maybe, the version of the .make file.  As often, I'll pull without updating the libs.  As quite often, I'm not sure when they've changed.

**Comment by Moult** [comment]
The 0.0.999999 reflects the "base build" prior to any git shenanigans. For example, someone who downloads a daily build then symlinks to git will not show 0.0.999999 and instead show whatever the date of that daily build. So the version number is meaningful.

So I'd prefer it shouldn't be changed in the settings (which reads from the BlenderBIM Add-on init) because that reflects the base build.
