### ISSUE TITLE
Put representation tools in 'Geometry and Materials' tab. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3465]
This was probably in the intention eventually, but would be nice to put the following under the 'Geometry and Materials' tab. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d0ab7fc6-4a4f-40c3-b8f4-bc5fa032b789)

**Comment by Gorgious56** [comment]
I think we have to be a bit careful here since each one of these buttons will alter the underlying geometry without an immediate feedback for the user. We don't want newbies to click everything thinking the buttons don't do anything when they're in fact messing up their objects irremediably. 

It's also exposing parts of the ifc schema that's IMO not immediately useful or legible for profanes. I doubt they'll instinctly click on "Get Representation IFC Parameters" and tweak the fields that pop up to reduce the radius of their cylinder or the width of their column. Or understand that a "Circle Extrusion" is in fact a Cylinder.

Currently this panel is hidden in the mesh properties so people don't go there and click things by mistake. Maybe this just needs a bit of lifting up so that people understand what are the stakes ? 

So here's a few ideas

- Move "Copy representation"  to the debug panel ?
- Tweak the code so we don't have to manually "Update Representation" ?
- Move "Get Representation IFC Parameters" to the Debug panel, and always display these fields in the 3D viewport N panel like for wall height or length ?
- Add icons to "Update Mesh as XXX" ?

**Comment by Moult** [comment]
Agreed, this panel needs quite a bit of work before it migrates. The "Update Mesh as XXX" probably need to go into a "Convert Representation Type" panel or something and detect things like whether or not it actually is a mesh, or compatible thing or if it's just going to break.

> Tweak the code so we don't have to manually "Update Representation"

When was the last time you had to manually Update Representation? Is it still a concern or have we managed to solve it?

**Comment by Gorgious56** [comment]
The lasty and only time I do is after using the "Set Origin" operator

**Comment by Moult** [comment]
So I'm not entirely happy with this, the representation conversion functions need a fresh set of eyes, and ideally be part of a new set of panels (or perhaps a new workspace tool? A Geometry Tool? in Edit Mode?) that focuses purely on geometry modeling and lets you reconstruct tessellations into multiple extrusions, or model directly with extruded solids, but that's a whole entire project in itself so... it'll come when the time is right :)

Also readded #2626 to the todo list (for the third time... hopefully I achieve it in this release cycle!)
