### ISSUE TITLE
Error when creating IfcDistributionElementType type

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3466]
Error when creating type...

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/b3c237bf-fd13-4545-b5ff-241c82e8c23c

**Comment by Andrej730** [comment]
Same errors happens also for 'IfcDistributionElementType', 'IfcFurnishingElementType' and 'IfcBuiltElement' (in IFC4x3)
I think we had the similar issue with IfcCivilElementType and it was fixed by manually adding it to the mapping 3ce010d, related to https://github.com/buildingSMART/IFC4.3.x-development/issues/583. Can fix it the same way.

Also noted that IfcTypeProduct is also not present in the entity to type mapping, don't know if there is any issue with that.
