### ISSUE TITLE
Autofill predefined type

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3478]
Provide a way to autofill both the class and predefined type from suggestion list listed [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/963ffa39b763226839c5efd7727e7d64fefc0593/src/blenderbim/blenderbim/bim/module/root/data.py#L112-L126), as discussed [here](https://community.osarch.org/discussion/comment/16572/#Comment_16572)

**Comment by Gorgious56** [comment]
Hey so I've managed something. Not very pretty and didn't know if it fits very well there but we can always go back if it sucks.

You can hack away at https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/schema/ifc_classes_suggestions.json if you have any idea. It's a json file so if you follow the existing structure there shouldn't be any problem.

I've set NOTDEFINED for existing suggestions because I don't really know what to set it to, but it can be changed.

Cheers

**Comment by theoryshaw** [comment]
sweet!

**Comment by theoryshaw** [comment]
@Gorgious56, I added a couple.

As you can see from the following, adding Types and occurrences separately would be pretty verbose. 
Is there a way to consolidate the data down, a little?

https://github.com/IfcOpenShell/IfcOpenShell/commit/0ef141447b3e1fb54385c75dbd58e071a9dc922b

**Comment by Gorgious56** [comment]
@theoryshaw Thank you ! 

Ah, right, I understand. I think to shorten the file we can
- remove the `"predefined_type"` entry when we want to default to `NOTDEFINED`
- systematically add `IfcProductType`  instead of `IfcProduct` and search for the occurence when we select the type. 

Are there any cases where we'd have separate synonyms for occurence and type ?

**Comment by Moult** [comment]
In IFC2X3 there are notoriously significantly less occurrences for MEP elements compared to types.

You could also just uh change the json formatting to be less pretty and condense it to one line ;) like you know those people who write their css rules all on one line

**Comment by Moult** [comment]
> Are there any cases where we'd have separate synonyms for occurence and type ?

I'd prefer to keep them separate because in IFC2X3 it is 1:many for type:occurrence, except for annotations and other uses of IfcTypeProduct where it is N:N potentially.

**Comment by Gorgious56** [comment]
[51c78a8](https://github.com/IfcOpenShell/IfcOpenShell/commit/51c78a89bdcc7203ae954dc6e119b1af5a81bb24)

I removed predefined type and auto-filled it with "NOTDEFINED" when it is not in the json file. I kept the first one so if anyone wants to chime in they know what to modifiy (hopefully) 

@Moult hehe I think I prefer the multi-line approach. I kept element / type separate then.
