### ISSUE TITLE
Description when hovering over the icons

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#3480]
I think it would be helpful to display the proper name of the tab when hovering over the icon in this menu:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/0db83a21-b2a5-45cc-9cfa-a2ea3356ee6c)

**Comment by BIMvoice** [comment]
That was quick. Thank you @Gorgious56! I can confirm that now it works
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/9ea36000-053b-48bb-98b8-47195e05995f)
Since it's a menu, I don't know if it makes any sense to have the "." at the end :)

**Comment by BIMvoice** [comment]
To be honest I think that even the text "Set Current Tab" is redundant. If should be quite self-explanatory that you can click on that. Especially when you see what you are switching to. 

Something that could help the case for this could be the way the active tab is highlighted. That pale blue is not cutting it. Maybe use another more obvious color instead, and maybe even add the same color to the icon of the active tab itself if that is possible. Just some random thoughts.

**Comment by Gorgious56** [comment]
Hehe ok I'll try and answer everything based on my knowledge. I'll reopen this issue since it seems this UI region can still be improved a bit.

- The dot is unfortunately hardcoded, I can't remove it (AFAIK).
- Yeah I guess the "Set Current Tab" is redundant, since we're kind of masquerading operators (buttons) as panel headers and users don't care about this detail. 
- I agree the blue line is pretty (and devilishly hacky :p) but in terms of contrast and readability it's not perfect. Something like that ?

![Animation3](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/db886d8e-4010-4bce-b4dc-ca063b65f66b)

Or that ?

![Animation3](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/d03e11e1-c572-4552-b8d8-5adff2f69e12)

Versus how it is now

![Animation3](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/d3a3ee77-6c06-46b2-9e03-706428a3e89e)

**Comment by bluecondor** [comment]
I don't understand what's the difference between the two proposals but both look good. Regarding the colour, why not use a greenish boy ace like on ifcopenshell and bbim homepages?

Ty, your doing amazing work!

**Comment by Gorgious56** [comment]
In the second proposal, the blue tick on the bottom of the tabs is removed.

AFAIK the only available colors are blue or redish (with `alert=True`), although I think the blue one can be changed in the preferences, we don't really want to mess with user themes do we ?

**Comment by BIMvoice** [comment]
Oh, you’re right, now I see it. I think it’s okay to have the line too. And I understand the remark about the colours. It is what it is then.

**Comment by Moult** [comment]
@Gorgious56 go for it :) Go for whichever you find looks best!

(Might want to check if the IFC icon needs to be scaled down a bit so it looks natural when highlighted too)

**Comment by Gorgious56** [comment]
I took the bulldozer approach and enabled both. Feel free to give additional feedback. I personally like the IFC icon to appear a bit bigger, it emphasizes that it's the main panel with the project level settings. It might clash with blender's UI paradaigm which uses padding in its icon but their a bit inconsstent so I don't think it's a problem.

Cheers
