### ISSUE TITLE
UI for IfcTester not working on my end

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#3487]
Hi @c4rlosdias,

Very nice job with that update man, thank you very much.

Unfortunately I cannot see it on my end.

Here is a video with the description of the issue: https://bit.ly/3NU4oOU

Let me know if the link is not working.

This refers to your PR #3467

**Comment by Andrej730** [comment]
The way it currently works - you need to open the IFC project in blender as you do normally and then you'd be able to check "Load from Memory" in "IFC Tester" and more detailed tester UI will show up.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/d10d6c83-717d-4ed0-96d1-950956dd8d15)

**Comment by Andrej730** [comment]
It is a bit confusing - I've made this checkbox always visible and now it has some tooltip description to recognize what it does.

I don't think there are some hard techincal limitations for that but tester UI does allows you to select in Blender some object that has IDS test failing and we also don't need to store separate ifc file in blender so it will be available for tester UI, so there are some benefits to this.

**Comment by Moult** [comment]
No, this fix doesn't make sense. The checkbox shouldn't be be shown if there is no IFC project since there is nothing to load from memory.

The proper fix is to read and write from an agnostic report output format (e.g. json which already is supported). If the project is not loaded, the UI will show just the test results. If the project is loaded, the UI will show whatever extra features it has to select the objects in the scene. Ping @c4rlosdias - he's probably the most qualified to fix this and knows what the workflow should be.

**Comment by c4rlosdias** [comment]
I agree with @Moult , I will try to implement this improvement.

**Comment by Andrej730** [comment]
> No, this fix doesn't make sense. The checkbox shouldn't be be shown if there is no IFC project since there is nothing to load from memory.

I mean it doesn't fix the problem - it just indicates that there is more UI to it but it's currenly available only if you open ifc in blender.
