### ISSUE TITLE
Wrong subtraction on wall (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#349]
**Steps to reproduce:**
1. Convert [wall--segfault-regression.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1793864/wall--segfault-regression.ifc.zip) with 5d0c04a0770be81fc8efe2f39cda440d0550284d (OCCT v7.2.0)
2. Experience segfault: 
```FATAL: An error occured, status code 139.```

There are no errors when converting with 8d0c95a9391f887e262e95cec646dca2c59ceadf (OCCT v7.2.0), so this is seemingly a regression. However, there are some obvious hints of where the problem areas are from the results of 8d0c95a9391f887e262e95cec646dca2c59ceadf:

![wall--segfault-regression](https://user-images.githubusercontent.com/4601554/37161689-a9ad8712-22f3-11e8-96ef-0ed6c98356c3.gif)

The file is rendered quite differently in other IFC software, so I guess the model quality is not that good in the first place (However it should not produce a segfault, though)

DDS:
<img width="200" alt="basic_wall_dds" src="https://user-images.githubusercontent.com/4601554/37166892-9a78f97c-2300-11e8-91db-f9d06e23e513.png">
SimpleBIM:
<img width="200" alt="basic_wall_simplebim" src="https://user-images.githubusercontent.com/4601554/37166893-9a955996-2300-11e8-93ff-dc458a907ab8.png">
Solibri:
<img width="200" alt="basic_wall_solibri" src="https://user-images.githubusercontent.com/4601554/37166894-9ab31544-2300-11e8-98d4-dc820645b42a.png">

**Comment by aothms** [comment]
If I change the precision on the `IFCGEOMETRICREPRESENTATIONCONTEXT` to `1.E-1`, the file converts successfully for me. You can always try that in your system, if you get failures for a file, try to mess with the precision.

I can see this potentially being fixed by a more careful investigation of boolean operations involving half spaces. To try and see where the polygonal boundary of the half space overlaps with faces of the other operand and create more margin there to prevent issues when applying the boolean op. This is kind of a known problem, not always resulting in crashes (on Windows it doens't for me for this particular file) but sometimes in thin slices of geometry remaining. A blanket fix could probably also be having a higher tolerance for halfspace operations in general.

**Comment by johanrd** [comment]
Update: this does not segfault anymore when building from 6c1ad47481de5d2ffae1c9c24e49366f380db5ca (OCCT 7.3.0), however the subtraction still seems to be conflicted in the output geometry:

<img width="671" alt="screen shot 2018-06-04 at 13 35 39" src="https://user-images.githubusercontent.com/4601554/40915469-80c788d6-67fc-11e8-9322-32b075273ff7.png">

**Comment by johanrd** [comment]
Closing, as this is not reproducible anymore when building from commit 6d25047 :tada:
