### ISSUE TITLE
Drawing shapely fill region glitches

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3512]
Drawing glitches. 

Using `calculate_shapely_surfaces`

Files: https://gitlab.com/openingdesign/milwaukee_st_4429/-/tree/2c0826684c6175f386f52d9a4d7ca68ba694ab03/Models/BlenderBIM

![2023-07-26_23-25-24_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/7d83dab2-c9c0-4bf4-9625-71fe658e3a1a)
![2023-07-26_23-25-37_NORTH_ELEVATION svg_-_Google_Chrome_chrome](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d491b0f1-09e9-46ee-bd17-645aa2e1808e)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3c7235df-676e-46d3-b947-f2653c94c1b8)

**Comment by Moult** [comment]
So this is a bit weird and I don't understand it but basically we do a ray cast on the IfcOpenShell geom tree from some point in the polygon. This is a 2D point so first we reproject the point back into 3D at the location of the camera view. This is point A.

The ray cast happens in a straight line so you'd assume that all results from select_ray have positions along the ray (e.g. point B, our intended result). However it turns out this is not the case and we're getting results where `result.position` has XYZ coordinates like point C.

I assume this is because of how either the geom tree or select_ray is implemented in C++, perhaps it casts rays on bounding boxes first and then moves the point to the nearest surface or something? Dunno. Ping @aothms. Is this intended behaviour?

![2023-07-28-124154_1065x774_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/2026d147-d3f6-41ad-85b3-9695241d18ce)

**Comment by Moult** [comment]
Although it would be nice to get some clarification on whether this is intended behaviour it's a fairly simple check to see whether or not a ray cast result position is on the ray or not, so I've added that check. Here's the fixed drawing:

Note there are still a few issues like the missing windows (which you can downgrade) and the extra coplanar edges on mesh geometry (which @aothms needs to peek at I believe) that are already documented in other issues.

![2023-07-28-125218_1512x568_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/5cf59275-5fb2-4ddc-8ec1-2bb336f81e95)

**Comment by Moult** [comment]
See #3158 #3510 #3002
