### ISSUE TITLE
Drawing error/question

### ISSUE THREAD

**Issue by DutchSailor** [IfcOpenShell/IfcOpenShell#3539]
What is BlenderBIM a fantastic BIM-tool!!

Currently working on my first test project. Please don't judge it on IFC-details ;-)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/30430941/cd5fec92-d114-45f5-8907-557fca2ec418)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/30430941/adc9c9b3-e612-4d14-b611-55e8c6a1316a)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/30430941/4f98b6ad-51ee-4df5-88c3-72c5c0cc7bf5)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/30430941/10db7be8-44c3-49cf-85f5-d112b9e5a33b)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/30430941/a280cc2b-d070-40eb-b5c6-4e7e92a7fe96)

I have some problems with drawings:
1) When I delete 'Roofplan 2', 'Roofplan' is also deleted.
2) When I delete a duplicate 'North Elevation', the original is also deleted.
3) This error is sometimes displayed.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/30430941/80f279ec-63a6-49a9-8207-ec46241d9f34)
4) When opening the sheet. This error is displayed. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/30430941/f4fbe751-cb1b-40a1-812e-cb1b9989bc1b)

The model can be downloaded here: https://github.com/DutchSailor/FOSS-BIM-Experiments/blob/main/BlenderBIM/Steel%20Structure%20Experiment.ifc

**Comment by Moult** [comment]
It seems you're using the "stable" release which is now a month old. In this case the "unstable" release is actually more ... stable :) Some of those bugs it fixes are ones you're experiencing. So the first step is to upgrade: https://blenderbim.org/docs/devs/installation.html#unstable-installation

The second is that unfortunately although the bug is fixed, the data is still invalid (because you were using a buggy version to create the data). The good news is that IFC data is almost always fixable so just run this script (change input and output filename):

```
import ifcopenshell
import blenderbim.tool as tool

f = ifcopenshell.open("/home/dion/steelmodel.ifc")

groups = [g for g in f.by_type("IfcGroup") if g.ObjectType == "DRAWING"]

for group in groups:
    drawings = [e for e in ifcopenshell.util.element.get_grouped_by(group) if e.ObjectType == "DRAWING"]
    while len(drawings) > 1:
        drawing = drawings.pop()
        ifcopenshell.api.run("root.remove_product", f, product=drawing)
        
f.write("/home/dion/updated.ifc")
```

This will fix your duplicated plans / elevations and fix problems 1, 2, 3.

As for your 4th issue, I'm not sure how to replicate since you've only shared your IFC and not the corresponding drawings/ sheets/ layouts/ etc folders. Maybe it's already fixed? Dunno :)

**Comment by DutchSailor** [comment]
Thanks a lot for the quick response and the fix! I will let you know is no 4 is still there in newer version!

**Comment by DutchSailor** [comment]
Sheet error doesn't appear anymore! So all are problems are solved!
