### ISSUE TITLE
ModuleNotFoundError: No module named 'ifcopenshell.util.shape'

### ISSUE THREAD

**Issue by KY2292** [IfcOpenShell/IfcOpenShell#3558]
Hello, I was trying to follow the geometry processing example:[]( https://blenderbim.org/docs-python/ifcopenshell-python/geometry_processing.html). However, I checked my installed package and I found that no module is namoed shape.py, although it is in the src in github. I removed the package from my virtual conda environment and followed the instructions by updating the latest daily build version using: conda install -c ifcopenshell -c conda-forge ifcopenshell. However, this also did not work and the installed package did not contain shape.py module.

Best Regards
Karim

**Comment by Moult** [comment]
I guess the conda builds are outdated. I'm not sure who handles this one, ping @krande @aothms

**Comment by Krande** [comment]
@KY2292 are you using Linux? If so that might explain it. The daily conda builds have been failing on github actions for Linux due to insufficient memory on the vm. I might look into reducing the features we compile for Linux on the daily builds. 

If you're not on Linux. Please try `conda list` in the python environment you have installed IfcOpenShell.

This could also be related: https://github.com/IfcOpenShell/IfcOpenShell/issues/2920#issuecomment-1494597924

**Comment by Moult** [comment]
Bump @KY2292
