### ISSUE TITLE
Pset_.*Common.Status not printing correctly

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3562]
At one point the `DEMO-PLAN', in [this](https://gitlab.com/openingdesign/mineral_point_residence/-/tree/7d391ffb4415ebdedf557b16e78d2f0864675972/BlenderBIM ) file, printed like this...

![2023-08-09_16-08-03_DEMO_-_PLAN svg_-_Google_Chrome_chrome](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/263e2def-9766-4163-b053-a643172a655c)

Now it prints like this...

![2023-08-09_16-06-57_DEMO_-_PLAN svg_-_Google_Chrome_chrome](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f1079520-d167-4dcc-b336-31bafb91c6af)

**Comment by Moult** [comment]
This is an interesting one. Basically since you're cheating and calling these walls, and also extruding them up, it _thinks_ that you can draw a closed polygon around these shapes and since they comply with your join criteria (e.g. they are the same material, status, class ...) they get merged into what you see there.

However I think it's safer to instead say that anything that is non-manifold (e.g. you can't say what's inside or outside because it's open) simply should be excluded in the join criteria.

![2023-08-13-230340_730x648_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/88681e33-c766-48b0-8bd6-b49196519968)
