### ISSUE TITLE
How to import IFC files in blender？

### ISSUE THREAD

**Issue by CCCCTX** [IfcOpenShell/IfcOpenShell#3563]
I have already installed the ifcopenshell plugin in Blender. How can I import ifc files through Python scripts? I have reviewed the API documentation you provided, and it may be due to my carelessness, but I did not find the relevant code.

**Comment by CCCCTX** [comment]
My goal is to convert ifc into glb. Or are there any other methods to implement using Python scripts?

**Comment by aothms** [comment]
Other people can answer the question better than me. Just a sidenote that for this you could also simply use the IfcConvert executable. But if you need to do more scripting/pre or post processing it might help to have more api to work with.

**Comment by CCCCTX** [comment]
Thank you, your answer was very helpful, but I want to achieve automated workflows through Python.

**Comment by Moult** [comment]
I'd second that recommendation to use IfcConvert (which you can call via Python via subprocess, or run it in an entirely different process via shell /bat script etc). You can use IfcOpenShell-python prior or post the call to IfcConvert to manipulate the data.

The only advantage I see to using Blender as an intermediary to glb/gltf is that you can do more fancy material setups in Blender or funky geometry processing purely in Blender. If that's really what you're after you can call `bpy.ops.bim.load_project(...)`.

**Comment by Moult** [comment]
Note that we generally do not document Blender operators since they interact with the UI which is generally slow and only suitable for simple automation / macros, not a proper programming API. You can enable Developer > Python Tooltips in the Blender settings and hovering over any button / field / dropdown / whatever in Blender can show you the exact command to run (or you can show the info window which shows live what commands you're executing so you can turn it into a script).

The BlenderBIM Add-on does have a non-UI layer which we also don't document (since it isn't exactly meant to be a public API) but at least it's collated together in core/tool.py.

**Comment by CCCCTX** [comment]
I tried IfcConvert, your suggestions are useful. Thanks！
