### ISSUE TITLE
import ifcopenshell brings up ModulNotFoundError

### ISSUE THREAD

**Issue by Clara203** [IfcOpenShell/IfcOpenShell#3579]
I tried to import an ifc-Model to my pyhton/jupyter notebook but jupyter keeps telling me that there is no module named 'ifcopenshell'. I logged out a couple of times and restarted the kernel but the error is still there even though it worked yesterday. What can I do now?
![Screenshot 2023-08-12 131033](https://github.com/IfcOpenShell/IfcOpenShell/assets/142092095/96edf606-f7d7-435a-95da-51a25830b0b2)

also after i code the reload, it shows me the same error
![Screenshot 2023-08-12 131042](https://github.com/IfcOpenShell/IfcOpenShell/assets/142092095/a397e6ab-c6c2-4412-9bf4-39cbaa8edce8)

**Comment by Moult** [comment]
How did you set up your notebook?

**Comment by cvillagrasa** [comment]
Hi @Clara203 , it looks like `ifcopenshell` is not installed into the Python environment from which you're launching the notebook.

There are a bunch of ways to manage envs in Python. For instance, I tend to use [mambaforge](https://github.com/conda-forge/miniforge#mambaforge). As @Moult was wondering, how did you set it up?

In case you just want a method that works, I suggest to install `mambaforge` from the previous link and then run the following:

```bash
mamba env create -n ifcopenshell_tests
mamba install -c ifcopenshell ifcopenshell
mamba install -c conda-forge jupyterlab
jupyter lab
```

You should then have Jupyter Lab up and running with the latest `ifcopenshell` available ;).

You'll know you're launching Jupyter from the correct env, because the prompt will look like:
`(ifcopenshell_tests) username@machine:~$`
(at least in Unix, I guess it'll be something similar in Windows)

If you want to resume your work in that environment after a restart or some other day, then it's just:
```bash
conda activate ifcopenshell_tests
jupyter lab
```

Lastly, you may want to check out [this example](https://cvillagrasa.github.io/IfcOpenHouse/) I set up a while ago with the usage of Jupyter and IfcOpenShell, with IFC.js viz. It is still experimental, so take everything with a grain of salt, but you may find something useful in there. Note also that it uses vanilla Jupyter Notebook instead of Jupyter Lab, since there are a couple of formatting things I couldn't make to work on Lab, but that's only for the viz part. You can still use 100% of `ifcopenshell` from Jupyter Lab if you prefer it ;)

**Comment by Clara203** [comment]
> Hi @Clara203 , it looks like `ifcopenshell` is not installed into the Python environment from which you're launching the notebook.
> 
> There are a bunch of ways to manage envs in Python. For instance, I tend to use [mambaforge](https://github.com/conda-forge/miniforge#mambaforge). As @Moult was wondering, how did you set it up?
> 
> In case you just want a method that works, I suggest to install `mambaforge` from the previous link and then run the following:
> 
> ```shell
> mamba env create -n ifcopenshell_tests
> mamba install -c ifcopenshell ifcopenshell
> mamba install -c conda-forge jupyterlab
> jupyter lab
> ```
> 
> You should then have Jupyter Lab up and running with the latest `ifcopenshell` available ;).
> 
> You'll know you're launching Jupyter from the correct env, because the prompt will look like: `(ifcopenshell_tests) username@machine:~$` (at least in Unix, I guess it'll be something similar in Windows)
> 
> If you want to resume your work in that environment after a restart or some other day, then it's just:
> 
> ```shell
> conda activate ifcopenshell_tests
> jupyter lab
> ```
> 
> Lastly, you may want to check out [this example](https://cvillagrasa.github.io/IfcOpenHouse/) I set up a while ago with the usage of Jupyter and IfcOpenShell, with IFC.js viz. It is still experimental, so take everything with a grain of salt, but you may find something useful in there. Note also that it uses vanilla Jupyter Notebook instead of Jupyter Lab, since there are a couple of formatting things I couldn't make to work on Lab, but that's only for the viz part. You can still use 100% of `ifcopenshell` from Jupyter Lab if you prefer it ;)




Thank you! Luckily  I already found a solution (or better ChatGPT helped me): As you said, `ifcopenshell` was not installed so I only had to type in `pip install ifcopenshell` . Because apparently, I didn't have the library anymore.

**Comment by Moult** [comment]
Cheers, I did some digging and found out that @jakob-beetz 's binder https://github.com/jakob-beetz/ifcopenshell-binder/ unfortunately seems to be on IfcOpenShell v0.6.0, and also uses conda (it would be nice to have a pip variant). Also it seems to use a custom threejs solution to visualise things whereas @cvillagrasa 's ifcjs based approach might also be a good alternative, or maybe an ifcopenshell-wasm approach might also be better (as IFCJS's geometry coverage isn't as comprehensive or battle-tested as IfcOpenShell). Also a few things have changed since then - including a new util.doc module that mean fetching docs is now much easier.

In any case I've added a link to the docs for Google Colab which contains a very minimal setup and sample file so at least there is some form of "official" click here to get started for Jupyter fans.

I also tried to get https://github.com/IfcOpenShell/ifcopenshell-binder/ working with https://mybinder.org/ but failed horribly (note that we can't use pip directly there as their Ubuntu version is too old with a very old glibc, similar problem with AWS Lambda - hence the Dockerfile).

If anybody is interested (ping @jakob-beetz @cvillagrasa ) in helping create a more sophisticated Jupyter setup, please don't hesitate, and we can add it to the official installation guide!
