### ISSUE TITLE
Help Segmentation fault for  qty.Name

### ISSUE THREAD

**Issue by bbrangeo** [IfcOpenShell/IfcOpenShell#364]
```
for qty in quantities:
    if qty.is_a("IfcQuantityArea"):
      obj_info = qty.AreaValue
      print(qty.Name)
      print(obj_info)
```

**Error : Segmentation fault for  qty.Name
Result:
`????????𐁳????a瑮????罞????`
2.45920001295
Segmentation fault**

My config 4.13.0-1-amd64 Debian 4.13.10-1 (2017-10-30) x86_64 GNU/Linux
Lib : ifcopenshell-python27-master-9ad68db-linux64.zip

Help me?
Thanks

**Comment by aothms** [comment]
Versions of Python prior to 3.3 have a compile-time config setting whether to use 2-byte or 4-byte unicode. This settings also affects the IfcOpenShell module and they could be incompatible. For the next release I will upload both versions.

Since this is a segfault on a string attribute with weird garbled characters my guess is this is related.

For the time being. Is there anyway you could use the python3.5 package (I think you're on debian sid?)? Or use the anaconda distribution with: https://anaconda.org/ifcopenshell/ifcopenshell

Sorry for the inconvenience.

**Comment by bbrangeo** [comment]
Thank you Thomas
Best regards
Boris

**Comment by aothms** [comment]
New builds available here https://github.com/IfcOpenBot/IfcOpenShell/commit/ba5049a7ebac112d540f752dad67309da9f47b0f#commitcomment-30047068

**Comment by bbrangeo** [comment]
Thank you
Best Regards
