### ISSUE TITLE
Visual Studio environment variables not set- cannot proceed.

### ISSUE THREAD

**Issue by 9lovingly** [IfcOpenShell/IfcOpenShell#365]
when I run:
D:\soft\IfcOpenShell_CGAL-cgal\win>build-deps.cmd
The error show:
Visual Studio environment variables not set- cannot proceed.

Requirements for a successful execution:
 1. Install PowerShell (preinstalled in Windows >= 7) and make sure 'powershell' is accessible from PATH.
  - https://support.microsoft.com/en-us/kb/968929
 2. Install Git and make sure 'git' is accessible from PATH.
  - http://code.google.com/p/tortoisegit/
 3. Install CMake and make sure 'cmake' is accessible from PATH.
  - http://www.cmake.org/
 4. Visual Studio 2008 or newer (2013 or newer recommended) with C++ toolset.
  - https://www.visualstudio.com/
 5. Run this batch script with Visual Studio environment variables set.
  - https://msdn.microsoft.com/en-us/library/ms229859(v=vs.110).aspx

and I install these software from step1 to step5,but also can't resolve,anyone can help me?

**Comment by thorade** [comment]
What version of Visual Studio did you install? VS2015 and VS2017 also install a "Developer Command Prompt", accessible from the start menu. It is identical to the normal command prompt, but has all the environment variables set.

This way you can use different VS versions on the same machine, because the variables are not set globally, but from the startup script of the command prompt.

**Comment by Stinkfist0** [comment]
Yes, you are most likely missing the step 5, it's not an installation but instructions how to open the dev cmd prompt.
