### ISSUE TITLE
Cmake: unused (and unsetable) CONVERT_PRECISION variable

### ISSUE THREAD

**Issue by dirkolbrich** [IfcOpenShell/IfcOpenShell#3672]
In the `CMakeLists.txt` is an unused `CONVERT_PRECISION` variabel which is set for the `Serializers` and `IfcConvert` target. Yet this variable is not specified as an option to cmake. 

https://github.com/IfcOpenShell/IfcOpenShell/blob/73d77b8382910183a4f5b329aa92f6fc0d35aa5d/cmake/CMakeLists.txt#L888
https://github.com/IfcOpenShell/IfcOpenShell/blob/73d77b8382910183a4f5b329aa92f6fc0d35aa5d/cmake/CMakeLists.txt#L898
https://github.com/IfcOpenShell/IfcOpenShell/blob/73d77b8382910183a4f5b329aa92f6fc0d35aa5d/cmake/CMakeLists.txt#L911

**Comment by aothms** [comment]
This indeed was an old setting that I removed somewhere in 0.7 if I'm not mistaken. It turned Iterator into a C++ template class parametrizing the number type, which wasn't that meaningful anyway, because it's only the very very end of the process. Not like CGAL where the number type is meaningfully parametrized throughout the entire computation. OCCT is hardcoded to use double (which is necessary for robustness)

**Comment by dirkolbrich** [comment]
Ok, will remove that variable from my PR #2393, if you agree.
