### ISSUE TITLE
Shift C in BlenderBim not working

### ISSUE THREAD

**Issue by WeenDwijler** [IfcOpenShell/IfcOpenShell#3676]
BlenderBim 0.0.230828
Blender 3.6.2

When in the BIM tab, shift C crashes python, i.e. doesn't work. It works when in the Layout tab.

**Comment by myoualid** [comment]
I guess you're trying to zoom into an object?

In your BIM workspace, do you have a BIM tool active from the Toolbar menu on the left? If so, you get a bug because some blender hotkeys are overridden when a BIM Tool is active. Shitf +C will align your selected objects to the active object's centerline.

Could you provide the error you're getting or confirm you had a BIM tool active?

**Comment by WeenDwijler** [comment]
Correct. I had the dimension tool open. Reproduced it. Sorry, didn't know that.

**Comment by WeenDwijler** [comment]
So I guess I close this one?
