### ISSUE TITLE
New UI tabs tooltips text "Set Current Tab" distracts from the actual tab name

### ISSUE THREAD

**Issue by zhukoven** [IfcOpenShell/IfcOpenShell#3704]
It's probably not a bug, neither it's a big issue. But for me it's kinda distracting to see the "Set Current Tab" text instead of the tab name when hovering over the tabs in the new UI (BBim v0.0.230902) - see the screeshot attached for reference. 

I think it's safe to completely remove this text if possible, because it does not make much sense for the end user.

![изображение](https://github.com/IfcOpenShell/IfcOpenShell/assets/27201628/3292ccc5-b68d-432f-8219-17bf4e45acd2)

**Comment by Andrej730** [comment]
Those "set current tab" buttons don't have any labels, only icons. In Blender if button has no text then description is forced to have the operator's name at the top.

But... there is a bit weird to achieve it by removing operator's name which I implemented. Which shouldn't be a problem since this operator is not intended to be called outside UI from F3 menu anyway.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/34dab518-f180-4746-b246-28a690255d5f)

If it's too hacky we can just add some line separator in the description, then operator's name should get out of the way too.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/9bed4404-eb4f-4aa4-be42-2fadc3895fa7)
