### ISSUE TITLE
BlenderBIM- add/modify PropertySet of IfcGroup

### ISSUE THREAD

**Issue by c-mellueh** [IfcOpenShell/IfcOpenShell#3756]
IfcGroups can have PropertySets, so far there is no way to add/modify PropertySets of IfcGroups in BlenderBIM.

**Comment by Moult** [comment]
Absolutely :) Would you be interested in writing code to implement this?

**Comment by Andrej730** [comment]
@c-mellueh perhaps this can help familiarizing with Blender Python API https://wiki.osarch.org/index.php?title=Create_your_first_Blender_add-on

**Comment by c-mellueh** [comment]
@Moult @Andrej730 
Phew, there was a lot to learn for me but i got it working!
I implemented ifcgroups into the scene collection:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/74136980/67c4bcfe-eb8c-4d3d-8858-cd3ccabc29ca)
so now you can edit their Pset and other information in the Object Information tab:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/74136980/eddc2183-0011-4bed-a3a0-e344d20742ca)

I also deleted the functionality to edit groups in the project Overview Tab because you can change all attributes in the Object Information Tab

Please keep in mind, that this is my first time working with blender. If there are some things i did wrong or wrote in the wrong file, please let me know and i will happily change them.

**Comment by Moult** [comment]
Wow, that's a great effort! The unfortunate issue is that groups in the collection tree aren't appropriate right now for a few reasons:

 1. Many collections in Blender cause a slowdown. There may be easily be thousands of IfcGroups.
 2. Many objects in Blender cause a slowdown (i.e. one per group). For this reason, we only use objects for things that actually have a coordinate placement or geometric representation. Other things where possible are only exposed through the properties panel instead of the 3D viewport. I'm talking for huge projects here, not small ones.
 3. The collection tree currently represents the spatial tree. This means that an element may be in one collection and one collection only. A lot of the code is based on this assumption and this needs more refactoring to allow for more flexible collection tree "flavours". Certainly one flavour in the future could very well be groups as you propose, but it's not quite there yet. Right now there are two "flavours", a DECOMPOSITION flavour and a SPATIAL_DECOMPOSITION flavour.

So what I'd recommend is to implement psets the same way it's implemented for other non-geometric entities (e.g. materials, material sets, tasks, resources, cost items, etc). I.e. in the properties panel. In the future, when the code has matured a bit a new (optional) flavour can be added.

**Comment by c-mellueh** [comment]
well that's a pitty but understandable. I'll try to refactor this. Thanks for your feedback and explanation. As i mentioned i am new to blenderbim and (so far) don't know all the little details on how it's structured. 
I also have a question regarding where to put the functions:
The demo module says:
``` python
 # Every operator should do one thing only: execute a core function. In
 # order to execute a core function, the operator's responsibility is to
 # pass in all of the inputs the core needs to do its job.
```
but i noticed for example in the groups module that the operator.py file does all the calculation etc and a tool/group.py doesn't even exist, Why is that? Should this style be kept or rewritten to follow the instructions in the demo module?

**Comment by Moult** [comment]
Ideally everything should use core/tools so they can be tested in isolation. Sometimes this isn't followed because:

 1. The code was written before the architecture came about
 2. The code was just a prototype to test out an idea.
 3. The developer was lazy or didn't know how to write tests / structure it. Messy code is better than no code :) Code that works before the deadline to get the job done is better than code that never gets the job done :)
 
Feel free to incrementally refactor whenever you touch a module. Don't feel pressured to "waterfall refactor".

**Comment by c-mellueh** [comment]
@Moult 
now it should work like you described it 🎉

**Comment by Moult** [comment]
Awesome! Thanks so much!
