### ISSUE TITLE
BlenderBim - error when attempting to Delete older drawing

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3767]
I have an older ifc file with older drawings that no longer print,

When attempting to delete the drawings it gives this error:

Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1557, in invoke
    return self.execute(context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 75, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 1573, in _execute
    sheet_references = tool.Drawing.get_sheet_references(drawing)
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\drawing.py", line 1854, in get_sheet_references
    if reference.Location == drawing_reference.Location:
AttributeError: 'NoneType' object has no attribute 'Location'

**Comment by Andrej730** [comment]
Hello! Can you please share the .ifc example?

**Comment by Plae-Blue-Dot** [comment]
Hi @Andrej730 it's a private file is there an email I can share it with your directly?

**Comment by Moult** [comment]
Also does this help https://github.com/IfcOpenShell/IfcOpenShell/issues/2978#issuecomment-1510374693

**Comment by Plae-Blue-Dot** [comment]
Thanks Doin I have shared the file via email,

I have actually run that script on this file before but these issues accumulate as things change, would running it again make a difference?

**Comment by Moult** [comment]
See https://github.com/IfcOpenShell/IfcOpenShell/commit/9240518066d3fec1b6d5c4cafb7fc12348918816

There isn't really something I can do since this is due to an outdated model, but I can advise how to purge this old drawing. In short you can see it already detects that it is an "orphaned / broken" drawing because it displays in the outliner when you first load the project:

![2023-09-18-234040_341x129_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/cf070279-c137-4f65-82c0-7d5e6547b2cf)

Simply change the object type from DRAWING to whatever (so it no longer considers it a drawing) then just delete it like any other object (x / delete button):

![2023-09-18-234051_296x237_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/755272e9-8b03-47d9-89ba-8a0cc37d2457)

To be safe, then save as a fresh IFC / keep a backup ;)

**Comment by Plae-Blue-Dot** [comment]
I'll give this a go thanks Dion, thanks ya I figured the drawings aren't recoverable but was hoping to atleast use the model itself

**Comment by Plae-Blue-Dot** [comment]
That has definitely worked and recovered my file, thanks Dion!
