### ISSUE TITLE
Fix build scripts to known good revisions of OpenCOLLADA and OCE

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#38]
These libraries introduce breaking changes from time to time.

**Comment by berndhahnebach** [comment]
Just tried a clean build with latest master branch, which is commit 480 (https://github.com/IfcOpenShell/IfcOpenShell/commit/90f72c4b2c3981f6bcfaa1fc1614a4de764f3fa8) and it builds like a charm on windows !!!

again thanks for all the afford you did stinkfist !

**Comment by Stinkfist0** [comment]
Any opinions on OCE revision to use? It would appear that 0.18 should be out in the near future so maybe the release would a good point to use?

**Comment by aothms** [comment]
Maybe just checkout a tag and make this configurable with parameters?

Alternatively, wonder whether it would be feasible to automatically checkout the latest tag conforming to some naming scheme. Would be possible using bash, but not sure if windows shell scripting is sufficient.

**Comment by Stinkfist0** [comment]
What kind of bash trick you have in mind? Something like `git rev-list --tags --max-count=1` could work for getting the latest tag.

**Comment by aothms** [comment]
I thought more magic was needed (like `grep | sort | head -n1` ), but it
seems `rev-list` comes batteries included. Only thing to add would be to
filter out the tags made in the process of merging OCCT official releases
such as [1]. I guess that can be accomplished with `--tags=OCE-*`. Neat.

[1] https://github.com/tpaviot/oce/tree/official/6.8.0

**Comment by Stinkfist0** [comment]
Will you want to handle this or should I? Oh and it seems that 0.17.1 was just recently released so 0.18 won't be out soon.

**Comment by aothms** [comment]
That's odd. None of the git version I tried on Windows (apparently I had 3) have this `--max-count` option for `rev-parse`. Does yours have it? Apparently `git describe --tags --abbrev=0` would do the same. That is, find the closest tag reachable from HEAD.

Does the following makes sense to you? Capturing stdout into a variable seems to be rather awkward in a bat file.

~~~
:: GitCloneAndCheckoutRevision - Clones a Git repository and checks out the latest tag reachable from HEAD
:: Params: %1 gitUrl, %2 destDir
:: F.ex. call :GitCloneAndCheckoutRevision https://github.com/tpaviot/oce.git "%DEPENDENCY_DIR%"
:GitCloneOrPullRepositoryAndCheckoutLatestTag
call cecho.cmd 0 13 "GitCloneOrPullRepositoryAndCheckoutLatestTag"
call :GitCloneOrPullRepository "%1" "%2"
pushd %2
for /f "tokens=*" %%i in ('git describe --tags --abbrev^=0') do set RECENT_TAG=%%i
call cecho.cmd 0 13 "Checking out %RECENT_TAG%"
call git checkout "%RECENT_TAG%"
popd
set RET=%ERRORLEVEL%
exit /b %RET%
~~~

**Comment by Stinkfist0** [comment]
For Git, I'm using what comes with TortoiseGit (just updated to the latest 2.0.0.0):
```
C:\Dev\GitHub\Tridify\IfcOpenShell-New\deps\oce>where git
C:\Program Files\Git\bin\git.exe

C:\Dev\GitHub\Tridify\IfcOpenShell-New\deps\oce>git --version
git version 2.6.2.windows.1
```

Both commands seem to work for me, the latter givin the name of the tag instead of the commit ID:
```
C:\Dev\GitHub\Tridify\IfcOpenShell-New\deps\oce>git rev-list --tags --max-count=1
ee62115c103aa1aef274a2c6b6c4caa2a53d903c

C:\Dev\GitHub\Tridify\IfcOpenShell-New\deps\oce>git describe --tags --abbrev=0
OCE-0.17.1
```

**Comment by aothms** [comment]
@Stinkfist0 see https://github.com/KhronosGroup/OpenCOLLADA/issues/339 there are tags available now in OpenCOLLADA.

**Comment by Stinkfist0** [comment]
Great. For OpenCOLLADA I'd think we can we pretty conservative what tag to use (simply pick something that works and set that for the build scripts) as the long term plan is probably not to use the library at all. For OCE however we probably want to use the latest tag from the build scripts.

**Comment by Stinkfist0** [comment]
I wonder if we want to go with OCE or OCCT for the 0.5.0 release?

**Comment by aothms** [comment]
I haven't looked into OCCT 7 in great detail. 

My take on this is that the segfaults here and there [https://github.com/IfcOpenShell/IfcOpenShell/issues/110, your reported crash] with OCCT 6.9+ need to get fixed regardless of the decision to ship with OCE or OCCT.

Then we can assess the benefits of OCCT 6.9+:

- Fidelity of boolean ops due to "fuzziness" e.g: [https://github.com/IfcOpenShell/IfcOpenShell/issues/6]
- Improvement of boolean op performance due to multiple arguments. [there are some pathological cases where IfcOpenShell performs terrible due to the sequential application of binary boolean ops]
 
My tentative stance on this is that these features are worth it to be included. There might still be an OCE release of 6.9.1 which would be a nice transition option for the 0.5.0 release. But I also feel we cannot keep waiting for this.

**Comment by berndhahnebach** [comment]
Just wanted to mention. If I'm on Linux I only use occt 7.0.0 ifcopenshell python interface to import ifc files into FreeCAD. No problems so far. On Windows I stick to the version from Alis build script. 

We had a few discussions o FreeCAD forum in the regard of oce and occt. Seams oce is at the moment far behind occt. The main reason for making or using oce was the cmake build system. Since occt has started to use cmake as well the main reason for using oce is gone. Most people on FreeCAD have been switched to occt7. I'm curious what the distributions will do.

**Comment by Stinkfist0** [comment]
OCE 0.18 was just released/tagged: https://github.com/tpaviot/oce/commit/262af2acf7f26ad5402908513e867889d86b8c4b

**Comment by aothms** [comment]
Ok, with 0.18 released, I went ahead and fixed in the build scripts 9ad68db0dccabcf337fd05ba8fa8950e59e7fbb5

Probably deps should also be postfixed with a version to make it easier to have multiple of them installed, leaving the issue open for that

**Comment by Stinkfist0** [comment]
Great, also a co-worker noticed that there's currently a pending problem with OCE 0.18 is using latest macOS, https://github.com/tpaviot/oce/issues/643

**Comment by aothms** [comment]
Yeah, I think this change in OSX affects a lot of code bases. There is always sth on OSX that needs additional work.

**Comment by Stinkfist0** [comment]
Yup, this one in particular is pretty classic: every C or C++ project I remotely follow have broke because of this. :)

**Comment by aothms** [comment]
Ok, I think this can be closed. Both build scripts can build with OCE or OCCT. For the 0.5 release I gravitate towards using 7.1.

**Comment by Stinkfist0** [comment]
Should we update the build scripts to USE_OCCT=TRUE by default now?

**Comment by aothms** [comment]
> Should we update the build scripts to USE_OCCT=TRUE by default now?

Let's do that. Reopening.
