### ISSUE TITLE
A ton of redundant profiles in file.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3810]
I have a ton of redundant profiles in this file.  Unfortunately, i'm not sure how they got there. 

I've been using 'duplicate aggregate' quite a bit, so that might be it, but I've done some isolated tests, and can't seem to replicate the problem. 

File, [here](https://gitlab.com/openingdesign/highland_haven/-/blob/0653a9f2ad4d51d9389f876e7664ee28133713c3/Models_and_CAD/BlenderBIM/Highland_Haven.ifc).

![2023-09-26_14-16-08_Blender_blender](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/86df61d4-e4ed-4897-8443-231a3cbddd49)

**Comment by theoryshaw** [comment]
I've also tried to use `bim.purge_unused_profiles`, but that doesn't work.

**Comment by Andrej730** [comment]
Investigated using profile name `RECTANGULAR - 2x6`.
It's used 597 times. And only 1 time in IfcMaterialProfile by id `#1186165`, so I guess it's the original profile.
All other 596 profiles this profile is used it's part of `IfcSweptAreaSolid` that's part of `IfcBooleanClippingResult`. For example beam `#1261955`.

The way to reproduce the issue
1) Create a beam and a slab
2) place them like on the image below
3) join them with shift+t in bim tool
4) duplicate the beam, profile also will be duplicated even though it shouldn't
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/f40aa1be-c3db-428f-b4a1-8ffd6e99f7be)

Simpler way to reproduce this - download the file and duplicate the beam.
[boolean_clipping_duplicating_profiles.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12738711/boolean_clipping_duplicating_profiles.ifc.txt)

Haven't looked into how to solve it yet but after the issue is fixed it will be possible to clean the project with the script below.
```python
import blenderbim.tool as tool
import ifcopenshell
import bpy

ifc_file = tool.Ifc.get()

def replace_in_inverses(old, new):
    for inverse in ifc_file.get_inverse(old):
        ifcopenshell.util.element.replace_attribute(inverse, old, new)

def merge_identical_profiles():
    unique_profiles = dict()
    for profile in ifc_file.by_type('IfcProfileDef'):
        if not profile.ProfileName:
            continue
        profile_data = profile.get_info()
        del profile_data['id']
        profile_data = tuple(profile_data.items())
        unique_profiles.setdefault(profile_data, []).append(profile)
            
    print(f'Unique profiles found - {len(unique_profiles)}')

    profiles_merged = 0
    for profile_data in unique_profiles:
        profiles = unique_profiles[profile_data]
        if len(profiles) == 1:
            continue

        main_profile = profiles[0]
        for profile in profiles[1:]:
            replace_in_inverses(profile, main_profile)

        print(f"ProfileName: {main_profile.ProfileName} - merged {len(profiles)} profiles")
        profiles_merged += 1
    
    print(f'{profiles_merged} profiles merged.')

merge_identical_profiles()
bpy.ops.bim.purge_unused_profiles()
```

**Comment by theoryshaw** [comment]
Thanks @Andrej730! Will try and run the script in the meantime, and see if there's any repercussions with the file.
