### ISSUE TITLE
Child aggregate disappears with `bim.refresh_aggregate`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3817]
If I `bim.refresh_aggregate` either child aggregate, I get the following error and the child aggregate disappears.

File: 

[Highland_Haven_aggregate.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12744831/Highland_Haven_aggregate.ifc.txt)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c0605ef6-7a0b-4a7a-b790-7cf97ebb2742)

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1168, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1287, in _execute
    duplicate_children(parent)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1210, in duplicate_children
    new_part = duplicate_objects(part_obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 1231, in duplicate_objects
    new_entity = blenderbim.core.root.copy_class(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\core\root.py", line 34, in copy_class
    root.link_object_data(ifc.get_object(relating_type), obj)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\tool\root.py", line 135, in link_object_data
    destination_obj.data = source_obj.data
AttributeError: 'NoneType' object has no attribute 'data'

```

**Comment by theoryshaw** [comment]
If I delete this context for that highlighted door, `bim.refresh_aggregate` works. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c546c0fb-7875-4fce-9ec9-598ce4f27973)

**Comment by Andrej730** [comment]
Investigated, found a couple things:
1) Why errors occurs:
- door type mesh is in Body/Model_view context (mesh_1), when door occurence is in Body/Plan_view (mesh_2)
- because of that discrepancy and `switch_representation` assuming that all mesh representations are in the same context, `switch_representation` replaces all `mesh_2` occurences with updated version of `mesh_1` and then removes `mesh_1`, resulting in the object removal in this error.
I'll investigate further why the discrepancy occurs in the first plane. But I don't know whether we support having different occurences to have different active context currently (then it would be just a bug of `switch_representation`) or there is another bug that caused that contexts discrepancy.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/c5c4a1ca-7295-4002-8fe9-39e028b1a3df)

2) Noticed another issue - when there are 2 walls, both share the same non-material based type, just a cube mesh, and opening is added to the entire type instead of occurences.

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/4aa20c7f-6ed8-4f51-a859-848a99a9e9e9

**Comment by Andrej730** [comment]
I commited fix for another issue in a847b8f4e which kind of solves this one too.

**Comment by theoryshaw** [comment]
Thanks @Andrej730 !

> Noticed another issue - when there are 2 walls, both share the same non-material based type, just a cube mesh, and opening is added to the entire type instead of occurrences.

I could be wrong, but i think this is how non-material based types, work... that is, all the instances will have the same geometry.

**Comment by Andrej730** [comment]
> I could be wrong, but i think this is how non-material based types, work... that is, all the instances will have the same geometry.

Oh, true, can't redefine representation if type already has one. Still have similar problem with annotations..
So it wouldn't be possible in IFC to create an opening in occurence with non material based geometry or there is some workaround?

**Comment by theoryshaw** [comment]
I guess the only way i can think, is to not make it a type, that is, a IfcWall without an associated Type... if i'm understanding correctly.
