### ISSUE TITLE
Switching to semver for v0.8.0

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#3927]
One of the confusing aspects of IOS is the versioning scheme. The C++ core is broadly grouped into a version number 0.X.0 which represents at least to me mostly major architectural design changes. Within the 0.X.0 version there are many -sha1 versions which represent a rolling release of features and fixes.

Then in ifcopenshell-python this is combined with yet another rolling release ... but the rolling release depends on which package you're getting. Pip is a monthly "point in time". BBIM stable is a every 2 months "point in time". I'm not entirely sure what Conda is. And there is also IfcOpenBot which matches the point in time of the last C++ -sha1 version.

I guess v0.8.0 is an opportunity to clean this up a tad. I'd like to propose to follow semver (not the major.minor.patch semver but what semver calls the "0.y.z initial development phase") - see https://semver.org/ . Here's a loose proposal that follows the rules of semver:

 - C++'s first 0.8.0 official release is called 0.8.0
 - Subsequent IfcOpenBot builds are 0.8.1, 0.8.2, 0.8.3, etc.
 - Somehow make it so that when an IfcOpenBot build is done (and succeeds), it also bumps PyPI. This makes their "point in time" equal.
 - If PyPI's workflow runs independently of IfcOpenBot, it also increment the patch number. E.g. 0.8.4, 0.8.5, 0.8.6, etc.
 - BBIM daily builds continue using its own semver e.g. 0.0.YYMMDD as it's still in alpha
 - The PyPI release date is adjusted so that every two months it also coincides with the BBIM stable release date. This way BBIM's stable point in time matches PyPI's point in time and there is a consistent simple ascending name for versions without having to lookup sha codes.

It would be nice if this could also be consolidated with docker/conda.

**Comment by Moult** [comment]
> We set the version number in git, which triggers a build.

You mean you create a tag, which then triggers an IfcOpenBot / workflow run? That sounds really nice and explicit.

> I think we should move out the [BBIM daily build] tags of the repo though.

Agreed. Perhaps only tag the stable release every 2 months?

**Comment by aothms** [comment]
Yes, or create a separate repo blenderbim-releases if it's convenient. That just mirrors IfcOpenShell. Or maybe the repository would be the built artefacts (don't know).

Something else is the branching. Do you think a single active branch is still ok, i.e we can't fix old features without introducing the new ones?

**Comment by Moult** [comment]
Agreed, a common source of complaints has been the build noise.

For branching, were you considering something like https://nvie.com/posts/a-successful-git-branching-model/ git flow? I think a single active branch is still OK. If people are working on a more major feature or would prefer a review, feature branches also work. We're still a relatively small team.

**Comment by aothms** [comment]
Yeah I wasn't very clear. I don't even really know myself any more what my line of thought was. In practice nobody has also ever asked us to fix or backport anything on 0.6.

How about branch protection rules for (the new) main? Tests have been failing for quite some time now.

**Comment by Krande** [comment]
>  I'm not entirely sure what Conda is.

The conda-forge releases are currently a mess :) For now I created tags 0.7.0a1, 0.7.0a2, etc. whenever I saw a need to update the conda-forge release. The conda-forge machinery will automatically create a PR in the conda-forge feedstock repo for ifcopenshell whenever it detects a new tagged release. 

With that in mind, do you think I should skip the alpha suffix on conda-forge and instead use a 0.7.1? I was planning on bumping the conda-forge release again now, so I might as well give use a more descriptive version if you have any suggestions. If not I'll just bump it to 0.7.0a11 :) 

> (so let's say a separate repo with OCC that has workflows to build that).

Just a thought. Why not use conda-forge as the source for all the dependencies like OCC, CGAL, HDF5 etc?

> How about branch protection rules for (the new) main? Tests have been failing for quite some time now.

That sounds like a good idea.

> For branching, were you considering something like https://nvie.com/posts/a-successful-git-branching-model/ git flow?

I liked the "git flow" setup. That would be for us a "main" branch protected branch that serves as the source for all official releases.  And our default  "develop" branch could be "v0.8.0" without branch protection where people can commit directly and it would keep the daily builds rolling at the pace it does today? 

We could also ensure that PR's against "main" requires certain labels to be set for the PR (feature, bug etc.) so that we also automatically generate a changelog?

**Comment by aothms** [comment]
> Just a thought. Why not use conda-forge as the source for all the dependencies like OCC, CGAL, HDF5 etc?

Interesting thought. Currently the openbot releases are all with statically compiled libs. Has anybody ever tried to do a performance comparison of ifcopenshell as statically linked vs the conda forge distribution? I always expected that in some scenarios the dynamic linking would be less performant, you can imagine gp_Pnt::X() as a function call across dll boundaries to be a lot less performant than an inline call to just read the memory address directly. But this depends of course on the granularity of calls and the amount of aggressive inlining (we don't use link time optimization on linux) that happens in the compilation for the statically linked variant.

**Comment by Moult** [comment]
So just before I forget, the recent issues around the compatibility of the IfcOpenShell-Python API change raises an interesting issue. It sounds as though IfcOpenShell needs its own semver, and then IfcOpenShell-Python needs its own semver since it can independently make major and minor changes. This probably also means that IfcClash, IfcCSV, et all also in theory have their own semver numbers.

This is both good and bad - bad because there are more things to keep track of (e.g. IfcCSV v1.2.5 requires IfcOpenShell-Python v20.4.3 which requires IfcOpenShell v0.8.1) but we can keep track of it in pyproject tomls and so on, but good because it means more stability when other people lock their deps and can rely on the API and things like IfcCSV's API and so on.

**Comment by Krande** [comment]
Hey @Moult, I can update IOS conda-forge recipe to automatically trigger on tags matching the url string

https://github.com/IfcOpenShell/IfcOpenShell/archive/refs/tags/ifcopenshell-python-0.7.9.tar.gz

I am assuming that we'll follow semver for `ifcopenshell-python-X.X.X.tar.gz` going forward?

**Comment by brunopostle** [comment]
It's a bit confusing that all these packages are 0.7.9, but the IfcOpenShell VERSION in `cmake/CMakeLists.txt` is 0.8.0

**Comment by Moult** [comment]
@brunopostle yeah the C++ hasn't yet been updated to read from `VERSION`. 0.7.9 is just a placeholder while I do test runs of the Github workflows (and I might do a few more test runs for 0.7.10, 0.7.11, until I get the "on tag" event working correctly). The actual 0.8.0 will happen in a couple months in line with the every-2-month release cycle (inspired by BBIM's rhythm). Then in the next 2 months after that there will be 0.8.1, etc.

@Krande Yes please, can you update Conda so that it reads from `VERSION` and only updates on either `workflow_dispatch` (so we can manually run for testing / urgent hotfix) or on tag like this: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/.github/workflows/ci-ifcopenshell-docker.yml#L5-L7 so that every 2 months we can tag say `v0.8.0` or `v0.8.1`, etc and that'll trigger all the workflows.

If there is a daily Conda, that should read from `VERSION` too and then have `.YYMMDD` suffixed to it.

It's not semver, because in theory if we followed semver strictly every time we added features to IfcOpenShell-Python we'd need to bump the major number. However, it is an improvement over the current situation where everything has different version numbers and every distribution channel has different release cycles so the state is always a bit different depending on where you downloaded it from and it's impossible to know what combination of versions across all the CLIs and Blenders and channels and Sphinx docs line up. So it's purely bringing a bit of consistency across channels, and strictly incrementing numbers to the version identifier.

**Comment by Krande** [comment]
@Moult Sure, I can fix a dispatch for the conda daily builds. Regarding conda-forge, I believe it will automatically scan for new tag versions using that particular name ("ifcopenshell-python") and create a PR in the ifcopenshell conda-forge feedstock repository. So that should simply work out-of-the-box without any rigging.

**Comment by Moult** [comment]
A little status update - all the Python stuff now follows the VERSION file and is standardised across channels. Just need to do choco (ping @ay-ex ?) and tweak the C++ build scripts.

**Comment by Krande** [comment]
@Moult I just remembered that the conda channel for our daily builds `-c ifcopenshell` has limited storage space. So  `VERSION.YYMMDD` will not work. We will quickly run out of space and it will simply not allow us to upload more packages. 

So what we've done so far is that we've overwritten the same v0.7.0 build name for each conda daily build. Should we continue that practice? We could in the future evaluate adding some kind of cleanup cron script that would remove all packages beyond a certain number of days old.

**Comment by Moult** [comment]
Ideally there should be some indication of the version on the website / conda interface so that users don't get confused about what version is what. That said, users can check `print(ifcopenshell.version)` to see exactly what they've installed, but maybe users might not know they can check that.

One option is to release less frequently (e.g. once every 2 weeks?) or as you say a cleanup cron script to cycle through the latest N days. I'm fine with either option, users would probably prefer the latter to get bugfixes quickly, but that's more work for you...

Awesome that the stable channel is up! When the rest is updated i'll do a tag of 0.7.10 to see if everything works :)

**Comment by Krande** [comment]
yes, I agree. I'll merge the PR with the daily builds appending the date as `VERSION.YYMMDD`. Then I'll make make another PR to create a cron-job for maintenance of the conda-packages. We have around 3gb of storage. So that should in principle be sufficient for a couple of days. I wonder if the daily build should only support python 3.12. And how about the following schema?
`-DSCHEMA_VERSIONS="2x3;4;4x1;4x3_add2"`

**Comment by Krande** [comment]
@Moult Daily (unstable) conda is up and running. I used the workflow dispatch to trigger a build now and it seems to work fine. I'll look into making a clean-up cron job for old conda packages next

**Comment by aothms** [comment]
> but wanted some typing / features in 3.9 so we jumped the gun

https://github.com/IfcOpenShell/IfcOpenShell/issues/4447

**Comment by Moult** [comment]
How could I forget poor Wally the Walrus!

**Comment by Krande** [comment]
@Moult Yeah, it was mostly to save space for the daily builds. The build matrix is rather large given that we support `occt` compiled With/Without VTK. We could also consider not supporting the builds with occt compiled with vtk. The only package I can think of that needs opencascade with the VTK compilation is cadquery. And I don't know the overlap of users between cadquery and ifcopenshell.

But if we wanted to support 3 versions of python, 3 platforms and 2 variants we are talking about 18 products, which all are about 50mb each. So that will eat up a lot of space quickly!

In the future we might want to do a multiple output conda build, were we consider separating ifcopenshell in a pure python wrapper package and c++ package and update the 2 independently. Obviously that's only if the number of daily changes on the python side exceeds the c++ side by a significant margin?

**Comment by Moult** [comment]
3 Versions (310, 311, 312) x 4 Platforms (Win64, Linux64, Mac x86_64, Mac Arm) = 12? 12*50=600 (well, on PyPI the Win64 is only 25mb?) so perhaps we can fit 5 days at least?

**Comment by Krande** [comment]
Sure, then I assume we skip the occt variant compiled with VTK. And we include conda build for arm. I haven't added ARM to the daily builds though (it is only being built on conda-forge).

**Comment by aothms** [comment]
The ifcopenbot builds are up https://github.com/IfcOpenBot/IfcOpenShell/commit/39cd980008100162ab469505524e40c4bde16489

Both .zip filename and internally reported version should now conform to the `VERSION` file in the repo. Only the Windows builds keep stubbornly reporting `0.8.0` because for some reason CMake is no longer able to find git on the build machines. This has been an issue for a bit longer. The .zip filename is ok.

**Comment by Moult** [comment]
@Krande I just did a test release to 0.7.10 and everything seems to have nicely bumped including docs (hooray!) except for the stable Anaconda release which is still on 0.7.9. Any ideas why it hasn't updated? https://github.com/IfcOpenShell/IfcOpenShell?tab=readme-ov-file#contents

**Comment by Krande** [comment]
@Moult Conda-forge automatically picked up your release and made a PR with it. The reason for the delay was that I had to make a fix to the osx arm conda builds (which I hope I managed to fix now). The stable conda version 0.7.10 is now released!

**Comment by Moult** [comment]
AWESOME! @Andrej730 helped point out that apparently 0.0.0.000000 is not a valid semver. Semver only allows 3 (major, minor, patch). So to be valid semver we should do 0.0.0-000000 (i.e. a dash instead with a "prerelease" number). The way precedence works is that 0.7.9 < 0.7.9-123456 < 0.7.10 < 0.7.10-123456

So that means that for daily builds, to be truly correct for semver, we should actually have the upcoming version prior to the prerelease number. Everybody OK with this?

**Comment by aothms** [comment]
Ok. Should we add a letter to the "prerelease number" though? In order to prevent confusion among people with the lexicographic ordering. Like `0.7.10-alpha123456` or `rc`.

**Comment by brunopostle** [comment]
Note that the cmake package_source target produces a tarball called IfcOpenShell-0.8.0.tar.gz even though it looks like it is supposed to track the number in VERSION.

Also release candidates are different, you create a 0.8.0 package without any trailing numbers, then rename the file to 0.8.0_rc1 etc.. this way when you do the final release you are literally shipping the same file as the last release candidate.

**Comment by Andrej730** [comment]
So, this can be closed now?
