### ISSUE TITLE
IfcTest-BlenderBIM-Results not correct

### ISSUE THREAD

**Issue by bsmithuk** [IfcOpenShell/IfcOpenShell#3953]
Hi I've created a simple IDS using [xBIM ](http://[www.xbim.it](http://www.xbim.it/xids)/xids) and [IFC Werkzeug](https://ifcdev.baseapps.net/viewer) and it loads into both platforms without issue, I run the IDS in BB and the output fails. All the IDS is checking is whether IfcBuilding has any values in the LongName Attribute. This attribute is present in the [Arc Dormitory Project](https://img1.wsimg.com/blobby/go/764e07b0-b77d-4b5f-9f0a-6a87ddef5514/downloads/Dormitory-ARC-v12-IFC.zip?ver=1697649663517).

Examples of results and model:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/70c472a1-1dc6-4027-adc4-4c8acc9f3e98)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/1ecfd0a2-fea8-430e-b683-57098cae7e22)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/a635e8b6-57ca-4871-a4fa-ac2a653bf2d8)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/cd264b60-8c1b-4531-8c06-1ab07ec1baf9)

Unable to upload IDS but can be emailed if required.

**Comment by BIMvoice** [comment]
Did you try any other simpler rule to confirm if anything at all works? I'd recommend checking something very simple, see if that works and then expand to more advanced things. With simple I mean, check a wall or slab if it is there, or if it matches any present properties.

**Comment by bsmithuk** [comment]
I can do some further testing, maybe it's just the IDS editor that is doing something weird, but I tried with IfcWindow and searching Pset_WindowCommon and Property 'IsExternal' and this equally resulted with a pass online but fail in BB. Maybe it's user error!
IFC Werkzaeug:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/4656f9e7-4b54-468d-89a7-b5972c3eef94)

BlenderBIM
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/e082e313-9648-4bd1-a05f-3c549083939d)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/63299d84-6f78-4743-86ff-6c9e3a6742ee)

Looks like the IfcClass is found but it's not validating the property that exists in the model:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/e4d20da3-3fda-4ada-a805-bbb1356b19c4)

**Comment by Moult** [comment]
So the first one is a bit weird because you don't specify any requirements so there's nothing to check so here is something that's more appropriate: 
[ids-test.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13223758/ids-test.txt)

That said there was a bug where an enumeration with only a single value (IFCBUILDING in your case) didn't work. Admittedly this defeats the purpose of an enumeration but it's a bug so it's fixed now.

As for your second issue it's hard to say, at a guess I'd say it is working just that the data type isn't what you expect. Can you click the requirements row and see what it expands out with?

**Comment by bsmithuk** [comment]
Hi Dion, agree bit odd I know but I'm not necessarily bothered about 'what' the value is in this instance more that a value exists for that attribute or property (dependant on project stage I may not need to valid the Fire Rating just that they have included something in early development vs pre-handover where I want to validate specific values for Entities/Predefined Types).

Yep I've only got a couple of niche use cases where I'll need to check things like IfcProject, IfcBuilding etc so yep kind of defeats the purpose of enumeration in this scenario. Will re-download latest build and try running again. 

Regarding second issue here is the expanded requirements (didn't realise you could do that but boy it's neat!):
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/16b10851-8d3a-4462-9a09-0f36df5ba84e)
Although not sure why it is picking up a random IfcWall in there...
Looks like there is an issue with the data type "IfcBoolean" - but within blender it is a boolean? 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/68438529/b6f5ff05-2e69-48cf-b1b9-8afacebebb12)

**Comment by Moult** [comment]
Yeah it's saying the property is an IfcBoolean but your IDS requires... something else, not a boolean. I've updated it so that the error report is clearer rather than just saying "it's wrong" it'll now tell you what you're requiring.

https://github.com/IfcOpenShell/IfcOpenShell/commit/7bf8d58cde3f0b35d4b3f2b0287081bb7d677bca
