### ISSUE TITLE
IfcPatch Migrate Error

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#3964]
Hi,

I get an error when I try to migrate IFC4 model to IFC2X3:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/1e079849-5db4-4f42-a60f-691c6cfa1944)

I get this repeating error:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/9fc67834-3230-4a06-8341-69a47ed6a54c)

**Comment by Andrej730** [comment]
Example of .ifc?

**Comment by Moult** [comment]
The problem is that migration assumes compatibility. IFC4 contains geometry that simply does not exist in IFC2X3. Any geometry that exists in IFC4 but not in IFC2X3 needs to be probably tessellated as a generic way to downgrade geometry. This code hasn't yet been written.

I can perhaps put together a first pass at implementation but it needs a lot of battle testing.
