### ISSUE TITLE
'cecho.cmd' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by yafimski** [IfcOpenShell/IfcOpenShell#400]
Hi,
I'm trying to re-build ifcopenshell with OPTION for IFC4, and after installing boost 1.65.1 dependencies I run into the following errors in the installation process prompt (through the VS2017 development cmd) :

```
'cecho.cmd' is not recognized as an internal or external command,
operable program or batch file.
'7za' is not recognized as an internal or external command,
operable program or batch file.
```

I'm using Windows 10 and the MSVC2017 toolchain.

I've tried looking in build-deps.cmd file that is in the ifcopenshell-master directory, or another file or another approach to solve this but haven't been able to figure this out.

Why isn't IfcOpenShell building and how do I fix it?

**Comment by aothms** [comment]
I never seen this issue. Is there anything particular about your setup (spaces in your path perhaps, which I thought ought to work though)? What steps did you perform precisely?

`utils\` is supposed to be added to your path:
https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/vs-cfg.cmd#L152

But on the other hand cecho is references as:
* `cecho.cmd` https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-ifcopenshell.bat#L55
* `utils\cecho.cmd` https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-deps.cmd#L28
* `"%~dp0\utils\cecho.cmd"` https://github.com/IfcOpenShell/IfcOpenShell/blob/master/win/build-ifcopenshell.bat#L70

Perhaps you can see if a find and replace (to the 3rd) resolves the first error message?

@Stinkfist0 contributed most of the build script, perhaps he has some insights on this, if he's still listening in on this.

**Comment by Stinkfist0** [comment]
Yeah, sounds peculiar. So you have built the dependencies before successfully? No pressing need to build them again, unless you're interested e.g. in newer OCCT/OCE. What one should be for a IFC4 rebuild is:
```cmd
:: Open VS cmd prompt, "x86 Native Tools Command Prompt for VS 2017" or "x64 Native Tools Command Prompt for VS 2017" (I'm using the latter pretty much always)
cd C:\Path\To\IfcOpenShell\win
del ..\build-vs2017-x64\CMakeCache.txt
run-cmake.bat vs2017-x64 -DUSE_IFC4=1
build-ifcopenshell.bat
```

**Comment by yafimski** [comment]
Hi! 
Thanks a lot for the replies! I am trying to follow the solution @Stinkfist0 suggests, directly implementing it.
What I've done so far is to install dependencies, and then try to follow the build instructions for VS and python from the ifcopenshell git page.

So according to Stinkfist0, I went to VS2017, went to `C:\IfcOpenShell-master\win` which is my folder.
Then I don't need to delete anything because I don't yet have a CMakeCache.txt file there.
Then I ran `run-cmake.bat vs2017-x64 -DUSE_IFC4=1` but it didn't compile properly because of
 `-- Looking for pthread.h - not found`  error.

I'm attaching a screenshot of the CMD to give an indication of what went wrong.
So i'm wondering what to do now...
![capture3](https://user-images.githubusercontent.com/20420760/41306172-8559c588-6e75-11e8-9c50-2b207e1a3ee4.JPG)

**Comment by Stinkfist0** [comment]
Sorry, I misinterpreted, so you are actually building for the first time. In that case, simply follow the instructions in the README files. Basically you need to run ` build-deps.cmd` (it will take a while, a good time for a snack perhaps) before `run-cmake.bat vs2015-x64 -DUSE_IFC4=1`.

**Comment by yafimski** [comment]
I'm not building it for the first time... I wanted to rebuild it with IFC4 options. Right now I am using the library with IFC2x3 options.

I ran `run-cmake.bat vs2017-x64 -DUSE_IFC4=1` and the attached screenshot is what came up.

When I `build-deps.cmd`, the original error in this post comes up, regarding `cecho.cmd`

**Comment by aothms** [comment]
> because I don't yet have a CMakeCache.txt file there

Keep in mind that `CMakeCache.txt` would be in `C:\IfcOpenShell-master\build-vs2017-x64` `win\` is the directory in which the scripts are stored, but the working directory is set to something else.

> but it didn't compile properly because of `-- Looking for pthread.h - not found` error.

That's not the reason for aborting. The reason is one line underneath, failing to find boost and OCCT.

Does `C:\IfcOpenShell-master\deps\boost` still exist?

The build script is quite idempotent and all, but does not go through great length verifying or restoring outputs of previous steps in case they went missing.

For future reference, what I typically end up doing is just editing the CMakeCache using a text editor and 'recompile' CMakeLists from within Visual Studio. You can also try the 0.6 branch btw, which has support for both schemas at runtime.

**Comment by yafimski** [comment]
@aothms 
Hi, thanks for replying.

> Does C:\IfcOpenShell-master\deps\boost still exist?
No, it isn't there. 

@Stinkfist0 
After deleting `deps` completely, attached is the output from `build-deps.cmd` :

[build-deps-run.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/2098918/build-deps-run.txt)

**Comment by Stinkfist0** [comment]
Ah, you appear to be using the wrong VS cmd prompt and tools?
```
Generator not passed but VisualStudioVersion=14.0 environment variable detected:
using `Visual Studio 14 2015` as the generator.
build-type-cfg.cmd: Warning: BUILD_CFG not specified - using the default RelWithDebInfo

Script configuration:
* CMake Generator       = `Visual Studio 14 2015`
```

Make sure to either "x86 Native Tools Command Prompt for VS 2017" or "x64 Native Tools Command Prompt for VS 2017" (recommended), for VS 2015 x86 it's called something like "Developer Command Prompt for VS 2015"

**Comment by yafimski** [comment]
I tried both "x86 Native Tools Command Prompt for VS 2017" or "x64 Native Tools Command Prompt for VS 2017" now, and with both it didn't work. I get the following, despite using a 2017 VS cmd..

```
Generator not passed but VisualStudioVersion=15.0 environment variable detected:
using `Visual Studio 15 2017` as the generator.
build-type-cfg.cmd: Warning: BUILD_CFG not specified - using the default RelWithDebInfo

Script configuration:
* CMake Generator       = `Visual Studio 15 2017`
  - Passed to CMake -G option.
* Target Architecture   = x86
  - Whether were doing 32-bit (x86) or 64-bit (x64) build.
```

**Comment by Stinkfist0** [comment]
Okay. Having the project in C root might be a problem as it might require admin rights IIRC. Have you tried cloning and building in other directory? Here's what a clean clone and build looks for me:
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.7.2
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
19:26>cd\

C:\
19:26>git clone https://github.com/IfcOpenShell/IfcOpenShell.git IfcOpenShell-master
Cloning into 'IfcOpenShell-master'...
remote: Counting objects: 9309, done.
remote: Total 9309 (delta 0), reused 0 (delta 0), pack-reused 9309
Receiving objects: 100% (9309/9309), 17.84 MiB | 1.51 MiB/s, done.
Resolving deltas: 100% (7035/7035), done.

C:\
19:26>cd IfcOpenShell-master\win

C:\IfcOpenShell-master\win
19:27>build-deps.cmd

This script fetches and builds all IfcOpenShell dependencies

Generator not passed but VisualStudioVersion=15.0 environment variable detected:
using `Visual Studio 15 2017` as the generator.
build-type-cfg.cmd: Warning: BUILD_CFG not specified - using the default RelWithDebInfo

Script configuration:
* CMake Generator       = `Visual Studio 15 2017`
  - Passed to CMake -G option.
* Target Architecture   = x86
  - Whether were doing 32-bit (x86) or 64-bit (x64) build.
* Dependency Directory  = C:\IfcOpenShell-master\deps
  - The directory where IfcOpenShell dependencies are fetched and built.
* Installation Directory = C:\IfcOpenShell-master\deps-vs2017-x86-installed
  - The directory where IfcOpenShell dependencies are installed.
* Build Config Type     = RelWithDebInfo
  - The used build configuration type for the dependencies.
    Defaults to RelWithDebInfo if not specified.
* Build Type            = Build
  - The used build type for the dependencies (Build, Rebuild, Clean).
    Defaults to Build if not specified. Rebuild/Clean also uninstalls Python (if it was installed by this script).
* IFCOS_USE_OCCT        = TRUE
  - Use the official Open CASCADE instead of the community edition.
* IFCOS_INSTALL_PYTHON  = TRUE
  - Download and install Python.
    Set to something other than TRUE if you wish to use an already installed version of Python.
* IFCOS_USE_PYTHON2     = FALSE
  - Use Python 2 instead of 3.
    Set to TRUE if you wish to use Python 2 instead of 3. Has no effect if IFCOS_INSTALL_PYTHON is not TRUE.
* IFCOS_NUM_BUILD_PROCS = 4
  - How many MSBuild.exe processes may be run in parallel.
    Defaults to NUMBER_OF_PROCESSORS. Used also by other IfcOpenShell build scripts.

Requirements for a successful execution:
 1. Install PowerShell (preinstalled in Windows >= 7) and make sure 'powershell' is accessible from PATH.
  - https://support.microsoft.com/en-us/kb/968929
 2. Install Git and make sure 'git' is accessible from PATH.
  - https://git-for-windows.github.io/
 3. Install CMake and make sure 'cmake' is accessible from PATH.
  - http://www.cmake.org/
 4. Visual Studio 2008 or newer (2013 or newer recommended) with C++ toolset.
  - https://www.visualstudio.com/
 5. Run this batch script with Visual Studio environment variables set.
  - https://msdn.microsoft.com/en-us/library/ms229859(v=vs.110).aspx

Warning: You will need roughly 8 GB of disk space to proceed (VS 2015 x64 RelWithDebInfo).

If you are not ready with the above: type 'n' in the prompt below. Build proceeds on all other inputs
>

Build started at 19:27:17.78.

Downloading Boost 1.65.1 into C:\IfcOpenShell-master\deps.
Extracting Boost 1.65.1 into C:\IfcOpenShell-master\deps.

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: boost_1_65_1.7z

Extracting  boost_1_65_1\libs\program_options\doc\alternatives
...

**Comment by yafimski** [comment]
Sorry I don't understand what you mean... do you suggest to copy `IfcOpenShell-master` from `C:\` to another drive?

**Comment by Stinkfist0** [comment]
Simply perform `git clone` to some other other directory, e.g. `git clone https://github.com/IfcOpenShell/IfcOpenShell.git C:\MyStuff\IfcOpenShell`

**Comment by yafimski** [comment]
Okay yes you're right it's building now so it must have been the root. I am running the x86 2017 VS cmd in administrator mode.

But how can we understand what the problem was?

**Comment by Stinkfist0** [comment]
Are you using an admin account? We could try to verify that admin rights were the problem if you start the VS command prompt form Start Menu by holding shift and right-click and choose "Run as administrator" and try running the build script at the original location.

**Comment by yafimski** [comment]
> I am running the x86 2017 VS cmd in administrator mode.

already did...

**Comment by yafimski** [comment]
Oh no, I ran in admin mode and then I ran in admin mode from a new root and it worked. So I wonder why it didn't work the first time..

**Comment by Stinkfist0** [comment]
That remains still a bit of mystery.

**Comment by yafimski** [comment]
Okay :)
Well, i'll update in case I run into issues with the rest of the IFC build.

Thank you for all the help.

**Comment by onizu-db** [comment]
> Hi,
> I'm trying to re-build ifcopenshell with OPTION for IFC4, and after installing boost 1.65.1 dependencies I run into the following errors in the installation process prompt (through the VS2017 development cmd) :
> 
> ```
> 'cecho.cmd' is not recognized as an internal or external command,
> operable program or batch file.
> '7za' is not recognized as an internal or external command,
> operable program or batch file.
> ```
> 
> I'm using Windows 10 and the MSVC2017 toolchain.
> 
> I've tried looking in build-deps.cmd file that is in the ifcopenshell-master directory, or another file or another approach to solve this but haven't been able to figure this out.
> 
> Why isn't IfcOpenShell building and how do I fix it?

For some reason, build-deps.cmd is not looking into the 'utils' sub-dir in 'win', which has both of these tools (7za.exe and cecho.cmd)..

**Comment by HHammerite** [comment]
I'm having the same issue where I cannot build. Does anyone have any suggestions? I've followed steps above as well. Thanks :)

> 
> 
> > Hi,
> > I'm trying to re-build ifcopenshell with OPTION for IFC4, and after installing boost 1.65.1 dependencies I run into the following errors in the installation process prompt (through the VS2017 development cmd) :
> > ```
> > 'cecho.cmd' is not recognized as an internal or external command,
> > operable program or batch file.
> > '7za' is not recognized as an internal or external command,
> > operable program or batch file.
> > ```
> > 
> > 
> > I'm using Windows 10 and the MSVC2017 toolchain.
> > I've tried looking in build-deps.cmd file that is in the ifcopenshell-master directory, or another file or another approach to solve this but haven't been able to figure this out.
> > Why isn't IfcOpenShell building and how do I fix it?
> 
> For some reason, build-deps.cmd is not looking into the 'utils' sub-dir in 'win', which has both of these tools (7za.exe and cecho.cmd)..
