### ISSUE TITLE
Questions about the IFC file parsing process

### ISSUE THREAD

**Issue by protectione055** [IfcOpenShell/IfcOpenShell#4009]
I really appreciate that the IfcOpenShell community is making great IFC development tools. I am trying to develop some new features on the open-source code, but I don't quite understand some parts of the code.

I found that the IFC entities in the model are indexed through some hash tables in the IfcFile class, but I can't figure out what some of the mappings mean, such as the following:

```
entity_by_iden_t byidentity;  //What is the difference between id and identity?
entities_by_ref_excl_t byref_excl;  //Why is the inverse property represented via a ternary? And what does excl mean?
```

I noticed that the inverse attribute is registered through a function `register_inverse` ,  does it mean here that the inverse attribute will not only record the referenced entity, but will also add all the parents of the referenced entity as well?

```
void IfcParse::IfcFile::register_inverse(unsigned id_from, const IfcParse::entity* from_entity, Token t, int attribute_index) {
	// Assume a check on token type has already been performed
	auto e = from_entity;
	byref_excl[t.value_int].push_back(id_from);
	while (e) {
		byref[{t.value_int, e->index_in_schema(), attribute_index}].push_back(id_from);
		e = e->supertype();
	}
}
```

**Comment by aothms** [comment]
Great questions. We don't get that many eyes on the C++ internals. Any help in improvement or documentation is highly appreciated.

`byid`: a mapping from the file's local entity instance name / step numeric ids.
`byidentity`: a mapping from the global incrementing integer in the C++ code base

byidentity is currently only used for the use case of copying instances from one file to another. Once you copy (addEntity()) from one file to the other, a copy is made, and the mapping from old to new is stored in the byidentity map. So that if you add that same entity instance again. It will use the earlier copy. This mapping cannot be made using e.g pointers because in the meantime the original file might have been deleted from memory.

> Why is the inverse property represented via a ternary?

```
typedef std::tuple<int, int, int> inverse_attr_record;
enum INVERSE_ATTR {
    INSTANCE_ID,
    INSTANCE_TYPE,
    ATTRIBUTE_INDEX
};
```

Consider the following example:

```
#29=IFCPOLYLINE((#30,#31));
#30=IFCCARTESIANPOINT((0.,0.));
#31=IFCCARTESIANPOINT((7900.,0.));
```

The mapping would then be:

```
{
   <30, 574, 0>: [29],
   <31, 574, 0>: [29]
}
```

`574` is the schema declaration index of IFCPOLYLINE https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/Ifc2x3-schema.cpp#L4939

Based on the std::less semantics of std::tuple, we can use the range query to either get all inverse relationships (only first component), or filtered based on type (1+2) or based on type with a specific role (attribute) (1+2+3). The last one is what is used to resolve the schema based inverse relationships.

> And what does excl mean?

In the non-`_excl` version, the mapping would also be populated with tuples for all supertypes of IfcPolyline.

> but will also add all the parents of the referenced entity as well

So if you mean supertypes, yes.

**Comment by protectione055** [comment]
> Great questions. We don't get that many eyes on the C++ internals. Any help in improvement or documentation is highly appreciated.
> 
> `byid`: a mapping from the file's local entity instance name / step numeric ids. `byidentity`: a mapping from the global incrementing integer in the C++ code base
> 
> byidentity is currently only used for the use case of copying instances from one file to another. Once you copy (addEntity()) from one file to the other, a copy is made, and the mapping from old to new is stored in the byidentity map. So that if you add that same entity instance again. It will use the earlier copy. This mapping cannot be made using e.g pointers because in the meantime the original file might have been deleted from memory.
> 
> > Why is the inverse property represented via a ternary?
> 
> ```
> typedef std::tuple<int, int, int> inverse_attr_record;
> enum INVERSE_ATTR {
>     INSTANCE_ID,
>     INSTANCE_TYPE,
>     ATTRIBUTE_INDEX
> };
> ```
> 
> Consider the following example:
> 
> ```
> #29=IFCPOLYLINE((#30,#31));
> #30=IFCCARTESIANPOINT((0.,0.));
> #31=IFCCARTESIANPOINT((7900.,0.));
> ```
> 
> The mapping would then be:
> 
> ```
> {
>    <30, 574, 0>: [29],
>    <31, 574, 0>: [29]
> }
> ```
> 
> `574` is the schema declaration index of IFCPOLYLINE https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcparse/Ifc2x3-schema.cpp#L4939
> 
> Based on the std::less semantics of std::tuple, we can use the range query to either get all inverse relationships (only first component), or filtered based on type (1+2) or based on type with a specific role (attribute) (1+2+3). The last one is what is used to resolve the schema based inverse relationships.
> 
> > And what does excl mean?
> 
> In the non-`_excl` version, the mapping would also be populated with tuples for all supertypes of IfcPolyline.
> 
> > but will also add all the parents of the referenced entity as well
> 
> So if you mean supertypes, yes.

Thank you very much, Dr. Krijnen! I've read several of your papers and I'm delighted to receive your response. I will take another look at this part of the code.

**Comment by aothms** [comment]
Thanks for the kind words :)

**Comment by Moult** [comment]
Bump @protectione055 :) is this issue resolved?

**Comment by protectione055** [comment]
> Bump @protectione055 :) is this issue resolved?

Yes, I'll close this issue. Thanks a lot :)
