### ISSUE TITLE
Have 'alt+click' work when assigning products

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4015]
Generic blender has the ability to 'Alt+click' a bunch of objects and it prompts a user with a dropdown menu asking which objects to select specifically. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/d41b69fb-e99d-4427-9aa7-1d9f559ae517)

Would be nice when running the eyedropper, via the 'product assignments' tool, that this 'alt+click' would work as well. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9747e469-37e7-4d42-bc4a-f55bf46e4d64)

**Comment by Andrej730** [comment]
I've met this issue before with similar eyedropper fields...

To do it we would need to edit:
1) eyedropper ui operator (to invoke select_menu operator on alt click)
2) select_menu operator since it's not connected to pointer properties by itself, it's just selecting the objects, not changing properties.
And both those operators are in blender core, so we won't be able to change them. Though it's possible suggest to Blender to add such feature.

I've added a button to assign product from the second selected object as a workaround. Can you try it out?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/0ca26a7b-e0d8-48de-80bd-0a8df9d378fa)

And any idea what would be the benefits of the eyedropper vs using other selected object workflow? At the end it seems to be the same amount of clicks.

**Comment by theoryshaw** [comment]
Awesome, love this better than the my suggested FR!
