### ISSUE TITLE
Type properties

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4034]
I am having trouble creating a IFC Type, specifically “IFCTransportElementType”. 

1. When editing the Type I cannot add Psets for the selected IFCType.
2. The “Userdefined Type” value is not displayed after saving and re-opening the “IFC project”
3. When I want to add the attached file into a new IFC Project, I get 2-4 attachment options, before the last update the selected file did become a Type option but now it gives an error message as per the attached screen shot: `Unabled to add instance from IFC2X3 schema to file with IFC4 schema`

Thanks for your time and effort.

1. No Pset options as per the slected Type:
![Skermskoot (49)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/1c59de13-5718-43af-bc3a-9fcd2f8a6840)

2. UserdefinedType value lost
![Skermskoot (48)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/d599a625-8f50-4dc6-aba5-10ef3836c556)

3. Error message:
![Skermskoot (47)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/1f8fa283-3416-434b-b5e9-9314d2f38961)

[2130 AIR BAG LEVELER IFC (2).txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13429626/2130.AIR.BAG.LEVELER.IFC.2.txt)

**Comment by Andrej730** [comment]
@Ave-5D 
> 1. No Pset options as per the slected Type:

What property sets are missing?

> 2. UserdefinedType value lost

If you mean Userdefined Type during the class reassignment (first arrow) then it's just a temporary field used only during the class reassignment, data is not really gone as you can see in object attributes (second arrow). Though I'll add update for this temporary field too, so it will be less confusing.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/22446fb4-7fb6-4971-909c-e622e9bb2326)

**Comment by Andrej730** [comment]
> 3. Unabled to add instance from IFC4 schema to file with IFC2X3 schema

I guess currently we don't support appending elements from different schemas directly. But you can upgrade your IFC2X3 file to IFC4 before appending it:

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/166f92a8-fdcb-49a2-a40e-ccbd0e33a641)

@aothms any ideas if it's possible to append elements from different schemas directly (e.g. from IFC2X3 to IFC4 file)?

**Comment by Ave-5D** [comment]
Thank you, Andrej.
I learnt how to upgrade a IFC2X3 file to IFC4 before appending it, now I am not getting an error.
I am still stuck with the Pset options when editing a Type. 

It would be good if the user only updates the selected Psets (Manufacture info, Maintenance requirements, Guarantee…) once and then when it is loaded into the library it includes all the Pset properties.

Sorry for the crude images apologies but I am still learning.
 
![Skermskoot (50)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/f75e55da-8ff8-428d-be28-44923828c2d2)

![Skermskoot (51)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/72826028-41e9-48a2-a91f-f3ee467af193)

**Comment by Andrej730** [comment]
@Ave-5D then it's the some problem you've mentioned on [OSArch](https://community.osarch.org/discussion/1801/object-properties-lost-with-project-library-import).

You can lookup the psets you're referring to in the IFC documentation - they are all applicable _only to IfcElement, not IfcElementType_, therefore you can't add them for IfcTransportElementType as it's a type class and not an occurence class.

For example, Pset_ManufacturerTypeInformation on [IFC4 documentation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcsharedfacilitieselements/pset/pset_manufacturertypeinformation.htm) at the title mentioning that's applicable only for IfcElement, IfcElementType is not mentioned:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/0f79be58-0ea0-45a5-864a-df52487f1216)

**Comment by Ave-5D** [comment]
@Andrej730 
Thanks yes it is the same as OSArch but some things have been solved :-) thanks.
Due to my lack of understanding I don’t know why it doesn’t work.

I tried to see what the difference is between a type class and an occurrence class. Could you please explain? 
I thought anything is a Type class until it is loaded into the model (occurrence) and then it becomes an Element (part of Project/Site/Building/Floor/Zone…). It is not very user-friendly if you need to re-enter all the Pset information every time you load it into your project.

Your assistance is truly appreciated.

**Comment by Andrej730** [comment]
@Ave-5D the difference is very simple - by "type class" I mean that the entity's class inherits from IfcElementType, "occurence classes" inherit from IfcElement.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/b578714c-1d25-4c85-88fa-278badffdaed)

The psets you wanted to add for type are not applicable for the types in IFC4, therefore you can't add them to the type, only to the occurences.

I agree that it makes total sense to have those psets available on types and it's possible to do so in IFC4X3 because they've added IfcElementType to the applicable classes. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/84f1ae3a-af12-4005-afee-2b346f84ff9f)

In IFC4 I guess the only option is to create custom psets to store this kind of information on types.
https://user-images.githubusercontent.com/507113/282260316-b6d5519a-bcf1-438a-896d-1937a8391fc6.mp4

**Comment by Moult** [comment]
I just re-read this and I think you're right, there was an implementer agreement where although the IFC specification (back in IFC4) didn't state so explicitly, type psets that mention the occurrence only should apply to the type. This is a bug upstream in IFC4 which we backport for practicality and has been fixed in IFC4X3.

It should now work.
