### ISSUE TITLE
Blender freezes up after changing position of IfcBuildingStory in a large project and saving it

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4035]
Blender freezes up after changing the z-value of a IfcBuildingStory empty, and then trying to activate a drawing. 

file: https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/c3b6884be0b5f4a695ca6d1cd969f32d0495e7ca/Open/Models_and_CAD/BlenderBIM/Highland_Haven.ifc

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/c2654d1c-e251-4de4-910d-7a76b3717b77

**Comment by Andrej730** [comment]
It also can be reproduced by changing IfcBuildingStory position and saving the project.

**Comment by Andrej730** [comment]
@Moult hi! Can you please take a look also? Wanted a second opinion on this, not sure if my solution doesn't cover some case.


In Ryan's example project IfcBuildingStory has 4000 children (including 79 children and 3921 subchildren) and given that we also use `should_transform_children` for all the children settings `geometry.edit_object_placement` ends up changing 10540 placements - we change position for the same objects 2 or more times because of `should_transform_children == True` for children settings: e.g. first time position for object A is changed as a subchild of subchild of IfcBuildingStory, then as a subchild of a IfcBuildingStory... 


Small example changing IfcBuilding position:
```
moved #36=IfcBuilding('2_ZBtxBgb3BgsAVCDP9JK7',$,'My Building',$,$,#1432,$,$,$,$,$,$) it was (0.0, 0.0, 0.0) now it is (0.0, 0.0, 592.6876068115234)
children: 2
    moved #42=IfcBuildingStorey('0G2PWO6R1ADw5jDR9IuZye',$,'My Storey',$,$,#1437,$,$,$,$) it was (0.0, 0.0, 0.0) now it is (0.0, 0.0, -592.6876068115234)
    children: 1
        moved #1222=IfcWindow('03VwKQhIL3D8gIyRfq3VYg',$,'Window',$,$,#1442,#1255,$,$,$,$,$,$) it was (0.0, 0.0, 1639.16373252869) now it is (0.0, 0.0, 2231.8513393402136)
        children: 0
    moved #1222=IfcWindow('03VwKQhIL3D8gIyRfq3VYg',$,'Window',$,$,#1447,#1255,$,$,$,$,$,$) it was (0.0, 0.0, 2231.8513393402136) now it is (0.0, 0.0, 1639.16373252869)
    children: 0
```


So I assume there's no need for `should_transform_children` to be `True` for children as we already adjusted their parent.
Setting it to `False` will leave us with 4001 edits of placements instead of 10540.

Another thing I've noticed after disabling `should_transform_children` for children - it seems there is also no need to update subchildren position at all. Since we already adjust their parent position, subchildren world position will stay intact anyway.

Here's the similar example of changing IfcBuilding position - IfcWindow position ends up being the same after the change.

```
moved #36=IfcBuilding('2_ZBtxBgb3BgsAVCDP9JK7',$,'My Building',$,$,#1432,$,$,$,$,$,$) it was (0.0, 0.0, 0.0) now it is (0.0, 0.0, 592.6876068115234)
children: 2
    moved #42=IfcBuildingStorey('0G2PWO6R1ADw5jDR9IuZye',$,'My Storey',$,$,#1437,$,$,$,$) it was (0.0, 0.0, 0.0) now it is (0.0, 0.0, -592.6876068115234)
    moved #1222=IfcWindow('03VwKQhIL3D8gIyRfq3VYg',$,'Window',$,$,#1482,#1255,$,$,$,$,$,$) it was (0.0, 0.0, 1639.16373252869) now it is (0.0, 0.0, 1639.16373252869)
```

So the final change is below, passes all tests we have.

```diff
diff --git a/src/ifcopenshell-python/ifcopenshell/api/geometry/edit_object_placement.py b/src/ifcopenshell-python/ifcopenshell/api/geometry/edit_object_placement.py
index 2dcf22662..7e2270a90 100644
--- a/src/ifcopenshell-python/ifcopenshell/api/geometry/edit_object_placement.py
+++ b/src/ifcopenshell-python/ifcopenshell/api/geometry/edit_object_placement.py
@@ -100,6 +100,8 @@ class Usecase:
         if not placement:
             return []
         results = []
+        # NOTE: we ignore subchildren as we already adjust position for their parent
+        # therefore they're not present in `results` and `should_transform_children` should be `True`
         for referenced_placement in placement.ReferencedByPlacements:
             matrix = ifcopenshell.util.placement.get_local_placement(referenced_placement)
             for obj in referenced_placement.PlacesObject:
@@ -111,8 +113,7 @@ class Usecase:
                     # Feature elements affect the geometry of their parent, and
                     # so logically should always move with the parent.
                     continue
-                results.append({"product": obj, "matrix": matrix, "is_si": False, "should_transform_children": False})
-            results.extend(self.get_children_settings(referenced_placement))
+                results.append({"product": obj, "matrix": matrix, "is_si": False, "should_transform_children": True})
         return results
 
     def get_relative_placement(self, placement_rel_to):
```

**Comment by Moult** [comment]
You are 100% correct. We only need to transform children, _not_ subchildren. It's very reassuring that the tests pass! What an incredible oversight!

**Comment by theoryshaw** [comment]
Thanks Guys!
