### ISSUE TITLE
IfcOpenShell Python 3.12 support

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#4045]
Not sure how important it is right now, just creating this to keep track of it.

**Comment by Krande** [comment]
@Andrej730 

FYI:
I recently bumped the daily IfcOpenShell conda builds to compile python 3.12 which seems to work fine. I will also bump the conda-forge release

**Comment by brunopostle** [comment]
I'm running IfcOpenShell, BlenderBIM etc.. on python 3.12 for the last week or so and it all seems fine. I pushed 1d972a6 (and reverted with 8f650c5) because of an annoying deprecation warning, but this doesn't affect running code.

**Comment by zaczhuozhang** [comment]
I would suggest we quickly have a beta version (which could be unstable) that at least let users run the package in `python 3.12` rather than just get the exception.

**Comment by khuongtran78** [comment]
Hi,

I got these errors when trying to build IfcOpenshell on Windows using Python 3.12 on Visual Studio 2022. I wanted to confirm if this is because we have not support Python 3.12 in which case I will install a older version of python.

`Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK1120	86 unresolved externals	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\RelWithDebInfo\_ifcopenshell_wrapper.pyd	1		
Error	LNK2019	unresolved external symbol __imp__PyBool_Type referenced in function __wrap_entity_instance_setArgumentAsLogical	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyType_Type referenced in function _SwigPyClientData_New	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp___Py_NotImplementedStruct referenced in function __wrap_SwigPyIterator___sub__	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp___Py_TrueStruct referenced in function __wrap_entity_instance_setArgumentAsLogical	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyFloat_Type referenced in function "void * __cdecl get_python_type<double>(void)" (??$get_python_type@N@@YAPAXXZ)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PySlice_Type referenced in function __wrap_line_segment___getitem__	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_StopIteration referenced in function __catch$__wrap_SwigPyIterator_value$2	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_OverflowError referenced in function __wrap_polygon_2_inner_boundaries_get	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_RuntimeError referenced in function __catch$__wrap_SwigPyIterator_distance$4	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_NotImplementedError referenced in function __wrap_new_HdfSerializer	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_TypeError referenced in function _SwigPyObject_append	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyType_IsSubtype referenced in function "int __cdecl SWIG_AsVal_double(struct _object *,double *)" (?SWIG_AsVal_double@@YAHPAU_object@@PAN@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyType_Ready referenced in function _SwigPyObject_TypeOnce	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_Str referenced in function "void __cdecl SWIG_Python_AddErrorMsg(char const *)" (?SWIG_Python_AddErrorMsg@@YAXPBD@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_GetAttrString referenced in function _SwigPyClientData_New	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_GetAttr referenced in function _SWIG_Python_GetSwigThis	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_SetAttr referenced in function _SWIG_Python_NewShadowInstance	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_GenericGetAttr referenced in function _SwigPyObject_TypeOnce	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_IsTrue referenced in function __wrap_entity_set_attributes	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp___Py_Dealloc referenced in function "public: virtual void * __thiscall swig::SwigPyIteratorClosed_T<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class std::vector<class std::array<double,2>,class std::allocator<class std::array<double,2> > > > > >,class std::vector<class std::array<double,2>,class std::allocator<class std::array<double,2> > >,struct swig::from_oper<class std::vector<class std::array<double,2>,class std::allocator<class std::array<double,2> > > > >::`scalar deleting destructor'(unsigned int)" (??_G?$SwigPyIteratorClosed_T@V?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@V?$vector@V?$array@N$01@std@@V?$allocator@V?$array@N$01@std@@@2@@std@@@std@@@std@@@std@@V?$vector@V?$array@N$01@std@@V?$allocator@V?$array@N$01@std@@@2@@2@U?$from_oper@V?$vector@V?$array@N$01@std@@V?$allocator@V?$array@N$01@std@@@2@@std@@@swig@@@swig@@UAEPAXI@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__Py_DecRef referenced in function _SwigPyObject_repr	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_Free referenced in function _SwigPyObject_dealloc	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp___PyObject_New referenced in function _SWIG_Python_NewPointerObj	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyBytes_AsStringAndSize referenced in function "int __cdecl SWIG_AsCharPtrAndSize(struct _object *,char * *,unsigned int *,int *)" (?SWIG_AsCharPtrAndSize@@YAHPAU_object@@PAPADPAIPAH@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyUnicode_FromString referenced in function "struct _object * __cdecl SWIG_Python_str_FromChar(char const *)" (?SWIG_Python_str_FromChar@@YAPAU_object@@PBD@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyUnicode_FromFormat referenced in function _SwigPyObject_repr	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyUnicode_InternFromString referenced in function _swig_varlink_repr	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyUnicode_DecodeUTF8 referenced in function __wrap_version	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyUnicode_AsUTF8String referenced in function "int __cdecl SWIG_AsCharPtrAndSize(struct _object *,char * *,unsigned int *,int *)" (?SWIG_AsCharPtrAndSize@@YAHPAU_object@@PAPADPAIPAH@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyUnicode_Concat referenced in function _SwigPyObject_repr	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyLong_FromLong referenced in function __wrap_svg_line_segments_size	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyLong_FromUnsignedLong referenced in function __wrap_svg_line_segments_size	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyLong_FromSize_t referenced in function __wrap_file_FreshId	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyLong_AsLong referenced in function "int __cdecl cast_pyobject<int>(struct _object *)" (??$cast_pyobject@H@@YAHPAU_object@@@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyLong_AsUnsignedLong referenced in function "int __cdecl SWIG_AsVal_unsigned_SS_long(struct _object *,unsigned long *)" (?SWIG_AsVal_unsigned_SS_long@@YAHPAU_object@@PAK@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyLong_AsDouble referenced in function "int __cdecl SWIG_AsVal_double(struct _object *,double *)" (?SWIG_AsVal_double@@YAHPAU_object@@PAN@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyLong_FromVoidPtr referenced in function _SwigPyObject_long	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2001	unresolved external symbol __imp__PyLong_FromLongLong	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyLong_FromUnsignedLongLong referenced in function __wrap_IteratorSettings_get_raw	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2001	unresolved external symbol __imp__PyLong_AsLongLong	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyLong_AsUnsignedLongLong referenced in function "int __cdecl SWIG_AsVal_unsigned_SS_long_SS_long(struct _object *,unsigned __int64 *)" (?SWIG_AsVal_unsigned_SS_long_SS_long@@YAHPAU_object@@PA_K@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyBool_FromLong referenced in function __wrap_IteratorSettings_get	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyFloat_FromDouble referenced in function __wrap_ElementSettings_unit_magnitude	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyFloat_AsDouble referenced in function "double __cdecl cast_pyobject<double>(struct _object *)" (??$cast_pyobject@N@@YANPAU_object@@@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyTuple_New referenced in function __wrap_file_instances_by_reference	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyTuple_SetItem referenced in function __wrap_file_instances_by_reference	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyDict_New referenced in function "struct _object * __cdecl get_info_cpp(class IfcUtil::IfcBaseClass *)" (?get_info_cpp@@YAPAU_object@@PAVIfcBaseClass@IfcUtil@@@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyDict_SetItem referenced in function "struct _object * __cdecl get_info_cpp(class IfcUtil::IfcBaseClass *)" (?get_info_cpp@@YAPAU_object@@PAVIfcBaseClass@IfcUtil@@@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyDict_SetItemString referenced in function "void __cdecl SWIG_Python_SetConstant(struct _object *,char const *,struct _object *)" (?SWIG_Python_SetConstant@@YAXPAU_object@@PBD0@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyModule_GetDict referenced in function _PyInit__ifcopenshell_wrapper	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyInstanceMethod_New referenced in function _SWIG_PyInstanceMethod_New	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyCapsule_New referenced in function _SWIG_Python_SetModule	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyCapsule_GetPointer referenced in function _SWIG_Python_DestroyModule	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyCapsule_Import referenced in function _SWIG_Python_GetModule	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PySlice_GetIndices referenced in function "void __cdecl std_array_Sl_double_Sc_2_Sg____delitem____SWIG_1(class std::array<double,2> *,struct PySliceObject *)" (?std_array_Sl_double_Sc_2_Sg____delitem____SWIG_1@@YAXPAV?$array@N$01@std@@PAUPySliceObject@@@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyErr_SetObject referenced in function "void __cdecl SWIG_Python_SetErrorObj(struct _object *,struct _object *)" (?SWIG_Python_SetErrorObj@@YAXPAU_object@@0@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyErr_SetString referenced in function __wrap_polygon_2_inner_boundaries_get	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyErr_Occurred referenced in function __catch$??B?$SwigPySequence_Ref@N@swig@@QBENXZ$0	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyErr_Clear referenced in function "int __cdecl SWIG_AsVal_double(struct _object *,double *)" (?SWIG_AsVal_double@@YAHPAU_object@@PAN@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyErr_Fetch referenced in function "void __cdecl SWIG_Python_AddErrorMsg(char const *)" (?SWIG_Python_AddErrorMsg@@YAXPBD@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyErr_Restore referenced in function _SwigPyObject_dealloc	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyErr_Format referenced in function "void __cdecl SWIG_Python_AddErrorMsg(char const *)" (?SWIG_Python_AddErrorMsg@@YAXPBD@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyErr_WriteUnraisable referenced in function _SwigPyObject_dealloc	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyArg_ParseTuple referenced in function __wrap_IteratorSettings_get	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyArg_UnpackTuple referenced in function _SwigPyObject_own	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__Py_BuildValue referenced in function _SWIG_Py_None	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyModule_AddObject referenced in function _SWIG_Python_SetModule	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyModule_Create2 referenced in function _PyInit__ifcopenshell_wrapper	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyImport_AddModule referenced in function _SWIG_Python_SetModule	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_Call referenced in function _SWIG_Python_NewShadowInstance	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_CallFunctionObjArgs referenced in function _SWIG_Python_ConvertPtrAndOwn	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_Size referenced in function __wrap_new_HdfSerializer	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PySequence_Check referenced in function __wrap_entity_instance_setArgumentAsAggregateOfEntityInstance	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PySequence_Size referenced in function __wrap_entity_instance_setArgumentAsAggregateOfEntityInstance	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PySequence_GetItem referenced in function __wrap_entity_instance_setArgumentAsAggregateOfEntityInstance	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyObject_IsInstance referenced in function _SwigPyClientData_New	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyLong_Type referenced in function "void * __cdecl get_python_type<int>(void)" (??$get_python_type@H@@YAPAXXZ)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyUnicode_Type referenced in function "void * __cdecl get_python_type<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(void)" (??$get_python_type@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@YAPAXXZ)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_AttributeError referenced in function "struct _object * __cdecl SWIG_Python_ErrorType(int)" (?SWIG_Python_ErrorType@@YAPAU_object@@H@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_IndexError referenced in function "struct _object * __cdecl SWIG_Python_ErrorType(int)" (?SWIG_Python_ErrorType@@YAPAU_object@@H@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_MemoryError referenced in function "struct _object * __cdecl SWIG_Python_ErrorType(int)" (?SWIG_Python_ErrorType@@YAPAU_object@@H@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_SyntaxError referenced in function "struct _object * __cdecl SWIG_Python_ErrorType(int)" (?SWIG_Python_ErrorType@@YAPAU_object@@H@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_SystemError referenced in function "struct _object * __cdecl SWIG_Python_ErrorType(int)" (?SWIG_Python_ErrorType@@YAPAU_object@@H@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_ValueError referenced in function "struct _object * __cdecl SWIG_Python_ErrorType(int)" (?SWIG_Python_ErrorType@@YAPAU_object@@H@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_ZeroDivisionError referenced in function "struct _object * __cdecl SWIG_Python_ErrorType(int)" (?SWIG_Python_ErrorType@@YAPAU_object@@H@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
Error	LNK2019	unresolved external symbol __imp__PyExc_IOError referenced in function "struct _object * __cdecl SWIG_Python_ErrorType(int)" (?SWIG_Python_ErrorType@@YAPAU_object@@H@Z)	_ifcopenshell_wrapper	C:\Users\trank\source\repos\IfcOpenshell\_build-vs2022-Win32\ifcwrap\IfcPythonPYTHON_wrap.obj	1		
`

**Comment by Moult** [comment]
BTW IfcOpenBot builds for 3.12 are now available for Linux and MacOS Silicon https://github.com/IfcOpenBot/IfcOpenShell/commit/742a9ecd810b7d29b726660485e18e5ae53e755b#comments

It seems to fail on Windows (and probably not available for MacOS Intel)

**Comment by aothms** [comment]
> I got these errors when trying to build IfcOpenshell on Windows using Python 3.12 on Visual Studio 2022.

How did you get the project configured in vs2022? It seems like the linker cannot find the symbols related to the python library itself.
