### ISSUE TITLE
Adding a Type to Project Object Metadata changes double naming.

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4049]
When opening the Element, once it is in the Project, it does not have the same Object Metadata as the Type.
![Skermskoot (54)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/5052a872-a8c0-47c9-9139-7c959e2d7320)
Metadata once loaded into the Project.

![Skermskoot (55)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/73e4a6b7-f51b-4c25-a234-9586b2d70036)
Type Metadata.

Would it also be possible to change the name to IFCTransportElement/AIR BAG LEVELER?
I have attahched the file for review.

Thanks in advance for your efforts.
Kind regards
Roel

[untitled - Kopieer.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13473692/untitled.-.Kopieer.txt)

**Comment by theoryshaw** [comment]
I think this could work, as long as there's no bidirectional change between the type and instances. 

That is, when you change the type name, I feel the instance name should not change. Since a lot of time, the object's name is used to identify the object. 

For example if you had this type name...
`IfcDoorType/DT01`


But renamed these instances to...
`IfcDoor/D101`
`IfcDoor/D102`
`IfcDoor/D103`

and you renamed `IfcDoorType/DT01` to `IfcDoorType/DT02`, the instance names should remain unchanged.

...

There could, however, be utility function created that a user could use to change these instance names, if they wanted.

**Comment by Ave-5D** [comment]
How about, 
If you had this type name... IfcDoorType/DT01

But renamed these instances to...
IfcDoor/**DT01**-D101
IfcDoor/**DT01**-D102
IfcDoor/**DT01**-D103

and you renamed one or more IfcDoorType/DT01 to IfcDoorType/DT02, the instance names should remain unchanged.
IfcDoor/DT01-D101
**IfcDoor/DT02-D102**
IfcDoor/DT01-D103
After the “-“does not change with the Change in Type, the vale after the “-“ should be automatically generated instance name 1,2,3… or custom entry D101…
Very easy to write not so easy to programme. 😊

**Comment by Gorgious56** [comment]
Is there some kind of ISO standard way to name types and occurrences or is it a convention ? I feel like enforcing a naming convention is not the right way to go, because it may vary so much between every party that's going to use the software, but maybe adding a tool to let users create, share and enforce one might be a solution ? Something like Autocad's DWS files

**Comment by theoryshaw** [comment]
@Ave-5D,
For the following...
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9c1d0279-d3ef-4f48-96ab-24c27e8d9a3b)

Did you mean to say... 
```
IfcDoor/DT02-D101
IfcDoor/DT02-D102
IfcDoor/DT02-D103
```

...instead?

...

I'd be okay with the approach you suggest, but would only suggest changing it to the following instead...

`IfcDoor/DT02/D101`
that is...
`{IfcClass Name}/{Type Name}/(Instance Name}`

...

Would like to hear other's opinions as well.

**Comment by theoryshaw** [comment]
> Is there some kind of ISO standard way to name types and occurrences or is it a convention ? I feel like enforcing a naming convention is not the right way to go, because it may vary so much between every party that's going to use the software, but maybe adding a tool to let users create, share and enforce one might be a solution ? Something like Autocad's DWS files

Yes, i agree.  I don't think we should force automation of a predefined convention for how these instances are named.
