### ISSUE TITLE
Converting IFC model to DAE missing/broken mesh elements

### ISSUE THREAD

**Issue by Xylexis** [IfcOpenShell/IfcOpenShell#406]
When converting an ifc model of concrete reinforcements I run into some problems.
I'm using the following arguments "--use-element-guids --use-world-coords --center-model"
When loading the DAE in Unity some of the mesh information is broken or missing.
What could be causing this issue? are the elements to small perhaps?
Images attached show the issue. 
In Bimvision the IFC seems correct, but after conversion to DAE import in Unity the file misses mesh parts.
I also checked the file in blender and there the meshes are also missing. So Unity import is not the cause.
![bimvision](https://user-images.githubusercontent.com/197950/41747824-a623c926-75af-11e8-9168-677c6316af53.PNG)
![unity](https://user-images.githubusercontent.com/197950/41747825-a63b9c18-75af-11e8-8477-0eda6f094e32.PNG)

**Comment by aothms** [comment]
Looking at the images there is a good chance this has been fixed in e87a1a0b32cacbbecb7b3cc428bdb2d3f362e148 Without a look at the file it's hard to tell for sure.

You'll have to compile a newer version of IfcConvert yourself though (which is trivial with the build scripts, but takes a while for your pc to churn through them due to the big dependencies).

**Comment by aothms** [comment]
Recent builds available here: https://github.com/IfcOpenBot/IfcOpenShell/commit/ba5049a7ebac112d540f752dad67309da9f47b0f#commitcomment-30047068

Closing for now, feel free to reopen and provide more information later.
