### ISSUE TITLE
Conversion of geometry not correct

### ISSUE THREAD

**Issue by pbbr** [IfcOpenShell/IfcOpenShell#4168]
Attached an IFC file where some geometry are not correctly converted with [IfcConvert](https://blenderbim.org/docs-python/ifcconvert.html). Do anyone have an idea how to improve the conversion in this case?

Conversion:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79220314/586f8a6d-8fad-4aaf-9234-155269455488)

BIMcollab Zoom:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79220314/a4442639-e0c4-4066-805c-cbd4ca2b7050)

IFC:
[Test Model.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13817627/Test.Model.zip)

Thanks for your support!

**Comment by aothms** [comment]
face boundary `#46` looks like this

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/3e1422b8-a88f-436c-9cfe-625c267f8467)

This is not valid as it is a self intersection of the face boundary. I think most brep-based implementation will have issues with this (but a lot of viewers are mesh-based which tend to be a bit more forgiving in these cases).

There are some things that ifopsh will try like breaking this up into cycles, but this has never really been implemented as completely to the extent that it results in a proper manifold shell. It just works for a single face basically (for example as the basis of an extrusion). And a manifold shell is basically a precondition in order to use it as a boolean operand.

I also tried v0.8 with CGAL, which also didn't work. But that results in:

- Ignoring triangulated facet with novel point likely due to self-intersections
- Subtraction of openings not supported for non-closed geometry

But looking at the source code there are still some avenues to explore:

https://github.com/IfcOpenShell/IfcOpenShell/blame/142b15e3322a366818166832573636a486f4d120/src/ifcgeom/kernels/cgal/CgalKernel.cpp#L2129

**Comment by pbbr** [comment]
@aothms Thanks alot for you investigation. 

This model is an export of Archicad. Do you see any export option which improve / fix the exported geometry?

**Comment by aothms** [comment]
I'm not very familiar with the commercial bim tools, but it's something I see often indeed with models from archicad, that the wall is defined as a simple rectangle in combination with very complex boolean subtraction operands.

**Comment by pbbr** [comment]
@aothms Thanks for your feedback. We saw, that the conversion in web-ifc works like expected ([Demo Viewer](https://ifcjs.github.io/web-ifc/demo/)). Is web-ifc a mesh-based implementation?

**Comment by aothms** [comment]
@pbbr yes it is

**Comment by pbbr** [comment]
@aothms Thanks. Do you see any chance to support non-manifold / non-closed geometry in the future?

**Comment by Moult** [comment]
> Because it's unlikely that tools like Archicad and other will have a better IFC export in the future :-)

Do you have a channel to talk to ArchiCAD? This would be great to bring up with their developers and I'm sure they would really appreciate the test files.

**Comment by pbbr** [comment]
> Do you have a channel to talk to ArchiCAD? This would be great to bring up with their developers and I'm sure they would really appreciate the test files.

@Moult Unfortunately not. Do you see any other possibility? We saw that this is a common problem with IFC exports (which depends on various factors like modelling, exporter, export settings, ...). To have a more robust conversion would be a great benefit! Thanks a lot for your effort!

**Comment by Moult** [comment]
I assume in theory CGAL or the "microkernel" approach @aothms is thinking of in the future can sort out these types of issues, but I'm not an expert and suspect there will always be hidden problems. The geometry might be look OK in a viewer, but it's definitely not mathematically correct and may have issues with QTO perhaps? Not sure what the other disadvantages or advantages might be.
