### ISSUE TITLE
Segfault / IndexError when exporting to xml

### ISSUE THREAD

**Issue by femesq** [IfcOpenShell/IfcOpenShell#419]
I've got a `segfault` (on `0.5.0.p2` release) and `IndexError` (on `master`) exception when exporting the IFC below to xml (remove `.txt`):

[LakesideRestaurant.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/2207579/LakesideRestaurant.ifc.txt)

Investigating the cause, I've discovered that happens (here)[https://github.com/femesq/IfcOpenShell/commit/e27d7a7b2594431b46a48039ebb92673ca9b0996#diff-80da8c2080af3e87a888ebc500a77ec7L141] and made a `try..catch` to workaround it.

It seems that `instance->getArgumentCount()` is returning an argument-count higher than the instance really have, but couldn't imagine where to start to fix it (I'm new to the code base).

Can I have some direction to contribute on this?

**Comment by aothms** [comment]
Sorry for the late reply. I am currently travelling. I can confirm this. The issue is encountered on this instance (and perhaps others):

~~~
#19287=IFCCURTAINWALLTYPE('22QW0$_7fB1BXBwWhI__EC',#41,'Curtain Wall:_CurtainWall_Exterior Glazing in Masonry',$,$,(#12259,#12261,#12263,#12265,#12267,#12269,#12271),$,'368866',$);
~~~

Indeed, if we annotate this with the attribute names from the schema [1] we see one attribute valuation is missing.

~~~
#19287=IFCCURTAINWALLTYPE(
    /* GlobalId             */  '22QW0$_7fB1BXBwWhI__EC',
    /* OwnerHistory         */  #41,
    /* Name                 */  'Curtain Wall:_CurtainWall_Exterior Glazing in Masonry',
    /* Description          */  $,
    /* ApplicableOccurrence */  $,
    /* HasPropertySets      */  (#12259, #12261, #12263, #12265, #12267, #12269, #12271),
    /* RepresentationMaps   */  $,
    /* Tag                  */  '368866',
    /* ElementType          */  $
    /* PredefinedType           missing */  
);
~~~

[1] http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcsharedbldgelements/lexical/ifccurtainwalltype.htm

IfcOpenShell v5 codebase two notion of attribute counts (a) from the schema and (b) from the untyped parsed data encountered in the file. These do not match in these case. These errors are quite rare as most tools generate their code from the schema.

Before entering the for loop, you likely do not now length (b) yet as it is dynamically loaded upon the first call the getArgument() in this case. For that reason a try catch is not an unreasonable fix. You might want to add an error message, e.g. `Logger::Error("Expected " + boost::lexical_cast<std::string>(instance->getArgumentCount()) + " attributes for:", instance->entity);` and then breaking out of the loop. It would be great if you'd create a pull request for this.

Many thanks for looking into this.

**Comment by femesq** [comment]
Thanks for your feedback and directions.
Nice to know that it is that simple and I was kind of in the right direction. Will make a PR with your proposal.

Thanks again, and enjoy your trip!
