### ISSUE TITLE
Error when adding a ifctype

### ISSUE THREAD

**Issue by Davidegaz** [IfcOpenShell/IfcOpenShell#4242]
Can't add any of ifctypes: it always popup this phyton error.

Anyone can help me? Tks

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/123664938/31fd6367-a054-4034-a234-f6c1259be0e6)

**Comment by theoryshaw** [comment]
@kjell-arne did you find the resolution to #3550?

**Comment by Moult** [comment]
As a short term fix, unhide any hidden objects.

**Comment by Andrej730** [comment]
How do I reproduce this? 
Can you please share .ifc+.blend example?

**Comment by Gorgious56** [comment]
You would need to show the entirety of you outliner either one of your collections is hidden, disabled or excluded from the view layer.

**Comment by Moult** [comment]
I'm struggling to recreate this. The error message suggests that it is due to collection being hidden or disabled or excluded or otherwise.

One way I managed to recreate it was to take the IfcProject/My Project collection (or whatever your project is called) and rename it, then try to add a slab. Did you do that by any chance? Or somehow remove your IfcProject empty object or similar?

If so, I'd like to know why you did it and how you did it, because in short: you're not meant to be able to do that. The project object is special. It must stay. Maybe in the future we should prevent it from existing as an object, but hey.
