### ISSUE TITLE
IDS reporting incorrect results

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#4250]
The attached IDS file is checking whether applicable entities have a "NSO" Pset with property name "Systemy instalacji".  Some entities definitely have this pset and property yet the results indicate that all entities fail.

[IDS_NSO_TM_KM3_test of 1 param.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/14038971/IDS_NSO_TM_KM3_test.of.1.param.txt)
[NSO_21_PB_AB_TM_MED_MI_WI_22901_Model wyp med stałego AB.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/14038972/NSO_21_PB_AB_TM_MED_MI_WI_22901_Model.wyp.med.stalego.AB.txt)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/83825269/376c94cd-29c4-4cd7-9951-4afb5e4ecec1)

**Comment by Moult** [comment]
Your model is invalid and has the same property set name twice (e.g. NSO is defined twice), see https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcObject.htm#5.1.3.6.4-Formal-propositions

This is not something I'd like to support since we use the get_pset utility function and the purpose of the `get_pset` function is to efficiently grab the pset (so it stops searching after it finds one).

**Comment by vulevukusej** [comment]
Uff that's a nasty one.  Thanks for the help @Moult 🙏
