### ISSUE TITLE
BBIM - SVG cut elements rounding issue

### ISSUE THREAD

**Issue by elschilling** [IfcOpenShell/IfcOpenShell#4336]
While working on the dxf exporter I noticed that walls with mitre joints generates svg with cut elements that mismatches the wall contour. 

![Screenshot from 2024-02-18 21-23-56](https://github.com/IfcOpenShell/IfcOpenShell/assets/35701560/d9df1fca-edbd-44ad-8265-bcdd4accab2e)

I found out it's a rounding issue when creating these svg elements, will make a PR to fixing it.

**Comment by Moult** [comment]
The rounding is necessary because shapely relies on exact numbers and doesn't consider tolerance. However the rounding is probably excessive, it looks as though it rounds to the nearest 0.1mm. Can you see if 0.01mm is OK?

**Comment by elschilling** [comment]
> The rounding is necessary because shapely relies on exact numbers and doesn't consider tolerance.
I've tested and for the Sandbox.ifc file
`coords = [[round(float(o), 1) for o in co[1:].split(",")] for co in subpath.split()]`
gives the same result as just 
`coords = [[o for o in co[1:].split(",")] for co in subpath.split()]`

I don't know if I am understanding it right, but if we remove the rounding it will not operate within the python float precision limit?

**Comment by Moult** [comment]
Huh, I just realised these were on paperspace paths (i.e. in mm) so maybe they're already down to 0.0001mm which is potentially OK? (i.e. no random Python float precision issues)

The correct solution would be to consider the modelspace precision (say 1e-5), adjust based on drawing scale to mm, then round to that. I'll need to take a closer look because these rounds were definitely necessary elsewhere, just need to double check whether there is a problem with removing them here (I might've been too conservative and setup rounding everywhere)

**Comment by aothms** [comment]
I'm probably missing some context, but when rounding there are still tolerance issues around the halves, e.g 2.499999999 rounds down 2.5 rounds up. If you truncate it's 2.99999999999 vs 3.0 etc. In my experience this causes issues especially in AEC because we often model in nice dimensions. But maybe you have already countered this in some way.

**Comment by elschilling** [comment]
I don't think this round is necessary because as this cut element is being generated from the svg element that already has been rounded, it will follow the same precision set by the svg previously generated. Any round afterwards with different precision will cause a mismatch between the elements. 
I tried without success to find where in the code  the first rounding happens when the first svg paths are generated from the ifc. Maybe its hardcoded within the serializer? The thing is, after the `serializer.finalize()` is called and `results = self.svg_buffer.get_value()` stored the svg wall information, the round already happened, as the path coordinates are trunked to 0.0001 precision. These svg path coordinates will then be used afterwards to create the cut elements.

**Comment by Moult** [comment]
Sorry for the delay, I was caught up with other work. The reason I delayed is because I wanted to track down the original situation where rounding was added - because you're right, logically it's not necessary since the SVG paths are already to a particular precision. FYI this is the starting point which added that code: https://github.com/IfcOpenShell/IfcOpenShell/issues/3512

I removed all the rounding and retested against the original bugreport and it still works so I don't know what I was thinking when I added that :) Thank you for correcting me and sorry it took so long to get around to this :)

![2024-03-03-153249_1060x370_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/85467c16-4910-47ec-9b19-72decd761e42)
