### ISSUE TITLE
IfcConvert can't find geometrical elements

### ISSUE THREAD

**Issue by jgs-fhnw** [IfcOpenShell/IfcOpenShell#4382]
Hello, I'm trying to understand why I can't generate some of the geometries using the attached model. First it seemed to work fine, but some elements are missing. There are two IfcCoverings that are not converted at all.

This is the model i use: [model.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14459709/model.zip)

I tried to open the file in [BimVision](https://bimvision.eu/de/), an ifc model viewer and surprisingly the IfcCoverings were displayed,
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/159908763/28277155-6e6f-4659-a8b4-41d0e22db7e7)

So this is the way i use the IfcConvert executable:
`./IfcConvert.exe model.ifc out.glb --include=attribute GlobalId 13pHDhNLH2zwo3_srB0FKw -vv`
where the GlobalId parameter is the id of one of the IfcCoverings. (See the attached screenshot of BIMVision)

This is the output:
```
IfcOpenShell IfcConvert v0.7.0-f0e03c79d (OCC 7.5.3)
[Notice] [2024-03-01 11:23:50] exclude entities IfcOpeningElement IfcSpace
[Notice] [2024-03-01 11:23:50] include GlobalId values "13pHDhNLH2zwo3_srB0FKw"
Scanning file...
Done scanning file
Parsing input file took 0 seconds
[Notice] [2024-03-01 11:23:50] No geometrical elements found or none succesfully converted`
```

Is there any problems with the Ifc? Do you know the problem?

Thanks in advance!

**Comment by jgs-fhnw** [comment]
Additon: The geometries that cannot be displayed were generated by using pythonOCC and added to the Ifc with IfcOpenShell.

**Comment by aothms** [comment]
When you validate your model with `python -m ifcopenshell.validate model.ifc` you'll see various references to:

```
For instance:
    #1607=IfcShapeRepresentation($,'Facetation','SurfaceModel',(#1606))
                                 ^
With attribute:
    <attribute ContextOfItems: <entity IfcRepresentationContext>>
Not optional
```

Replace all occurrences of:

```
IFCSHAPEREPRESENTATION($
```

with

```
IFCSHAPEREPRESENTATION(#10
```

Ideally the logging would be handled better here. I think in previous versions, IfcConvert might have also accepted this schema violation actually. Could be something to look into, but for now the solution is relatively easily applied in the model.

When you use the serialization function in ifcopenshell it doesn't know about the representation contexts, because the file instance is not passed as a parameter. In the newer high level python API methods this is handled much better, but I don't think there is a method to create a shape representation from pythonocc geometry. All help is welcome!

**Comment by jgs-fhnw** [comment]
Thank you for your help! We addressed the issue by adding the context manually to the IfcShapeRepresentations like this:

for rep in representation.Representations:
  rep.ContextOfItems = context
