### ISSUE TITLE
some entitys of ifc file aren't accessible

### ISSUE THREAD

**Issue by DaJansenGit** [IfcOpenShell/IfcOpenShell#442]
I'm trying to load an ifc file to python with ifcopenshell but have the problem that some entitys aren't found by ifcopenshell. For example in my ifc file i have the following lines:
`#395= IFCBOILERTYPE('06m5ENao926Avl6KnCa2rd',#42,'Standard',$,$,(#434,#445,#461,#484,#500),(#391),'1128791',$,.WATER.);`
`...`
`...`
`#414= IFCBOILER('0LMbjl8XfFaui1YxJs_D66',#42,'Boiler:Standard:908018',$,'Standard',#413,#407,'908018',$);`
When i try to access the boiler by 
`boiler = IfcFile.by_id(414)` or by `boiler = IfcFile.by_type('ifcboiler')`
i get the following error message:
> Traceback (most recent call last):
  File "C:/Users/dja/PycharmProjects/Bim2Sim3.5/examples/example_1.py", line 24, in <module>
    boiler = IfcFile.by_id(414)
  File "C:\Users\dja\AppData\Local\Continuum\anaconda2\envs\Bim2Sim3.5\lib\site-packages\ifcopenshell\file.py", line 45, in by_id
    def by_id(self, id): return self[id]
  File "C:\Users\dja\AppData\Local\Continuum\anaconda2\envs\Bim2Sim3.5\lib\site-packages\ifcopenshell\file.py", line 42, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key))
  File "C:\Users\dja\AppData\Local\Continuum\anaconda2\envs\Bim2Sim3.5\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 1250, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
RuntimeError: Entity not found

When i try to access the type element with 
`boilertype = IfcFile.by_id(395)` or boilertype = IfcFile.by_tyoe('ifcboilertype')
i get the type element. **BUT** when i try to access the boiler now via the boilertype by looking for 
boilertype.ObjectTypeOf[0].RelatedObjects the RelatedObjects attribute holds again an error and entity not found.

The same error occurs with the following elements: (just the ones i found by now)
- ifctank
- ifcvalve
- ifcspaceheater
The ifcfile is created with Revit 2019 by using the "IfcExportAs" parameter.

Do you have any idea what's going on here and why the elements aren't accessible via ifcopenshell?

Edit:
when manipulating the original ifc file and changing IFCBOILER to e.g. IFCLOCALPLACEMENT everything works fine... So it seems like ifcopenshell doesn't work for ifcboiler, ifctank ...

**Comment by femesq** [comment]
Haven't checked the code, but my guess is that it's probably because of IFC schema version which your `IfcOpenShell` was built against.

It looks like it was `IFC 2x3`, in which there [was the type definition already](http://www.buildingsmart-tech.org/ifc/IFC4/Add1/html/schema/ifchvacdomain/lexical/ifcboilertype.htm):
![image](https://user-images.githubusercontent.com/1899668/44481554-7d858e80-a61c-11e8-9c81-247433a85081.png)

...but there wasn't the IFC element `IfcBoiler` yet, which was added on `IFC 4`, according to the [change-log](http://www.buildingsmart-tech.org/ifc/IFC4/Add1/html/schema/ifchvacdomain/lexical/ifcboiler.htm):
![image](https://user-images.githubusercontent.com/1899668/44481535-6ba3eb80-a61c-11e8-8fc6-4eb552eb184d.png)

If you build the library yourself, you could try re-building it against `IFC4`...

**Comment by DaJansenGit** [comment]
Thanks for your reply. You are right, the scheme for ifcopenschell is set to IFC2x3. I'm now trying to build it on my own, my first install was via conda but there seems to be no option to change from IFC2x3 to IFC4.

**Comment by aothms** [comment]
The releases on conda (0.6 branch) support both schemas at runtime. E.g. you can say something like the following. Also when parsing the schema should be picked up from the header.

~~~
>>> import ifcopenshell
>>> ifcopenshell.file().schema
'IFC4'
>>> ifcopenshell.file(schema='IFC2X3').schema
'IFC2X3'
>>> ifcopenshell.file(schema='IFC4').schema
'IFC4'
~~~

Otherwise 0.5 branch is compile time setting dependent

~~~
>>> import ifcopenshell
>>> ifcopenshell.schema_identifier
'IFC2X3'
~~~

What does `ifcopenshell.version` report?

**Comment by DaJansenGit** [comment]
Hey aothms,
sorry for my late reply i was on vacation. I installed the new ifc version in a python 3.6 environment with:
conda install -c conda-forge -c oce -c dlr-sc -c ifcopenshell ifcopenshell`
and everything seems to work. 
Thanks again for the fast reply and the nice work you do with IfcOpenShell!

**Comment by aothms** [comment]
> and everything seems to work

Good to hear, thanks for reporting.
