### ISSUE TITLE
Assigning to an aggregate by selecting a part

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4434]
Currently when using the 'eyedropper' when assigning the aggregate, you have to pick the aggregate empty to assign.  

I would propose to allow the user just to select a 'part' of the target aggregate, as well.  

Reason being, parts are more readily available and easier to spot in the scene, verse tracking down the empty.

Or both, either the part or the empty, would probably be best. 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/39ff0fb5-f8d1-4704-84f7-c1a5cc7bec60)

**Comment by Andrej730** [comment]
I've noticed an issue with this assigning to newly created aggregates.

Imagine if you have 2 storeys on building A and then you created a new building B and want to assign one of the storeys to it, then you'll end up assigning it to IfcSite because `element.IsDecomposedBy` is empty when you just created an aggregating element.

Or other case, 2 elements created and you will try to assign one to another. Then it will fail with `assembly = element.Decomposes[0].RelatingObject # IndexError: tuple index out of range`.

https://github.com/IfcOpenShell/IfcOpenShell/blob/02fd78df1433cb2dc465838fd5a0f29907c7158d/src/blenderbim/blenderbim/bim/module/aggregate/operator.py#L48-L52

**Comment by Moult** [comment]
You're correct there is no way to automatically tell, so I've added an interface for the user to choose from instead.
