### ISSUE TITLE
Slab edit profile creates an error in Blender BIM

### ISSUE THREAD

**Issue by Gunner90** [IfcOpenShell/IfcOpenShell#4438]
I have tried on several projects and the results are the same.  I add a slab but when I select edit profile I get an error report with a Python traceback.  This disappears, the profile is shown but you cannot move the edges.  I am new to Blender, if I knew where the traceback report is stored I would attach it.
I am a Revit user looking at Blender BIM as a replacement so this is frustrating!

**Comment by Gunner90** [comment]
I found the traceback:
[Python Traceback .txt] (https://github.com/IfcOpenShell/IfcOpenShell/files/14628788/Python.Traceback.txt)

**Comment by Gorgious56** [comment]
Hello, I think you're using an outdated BlenderBIM version, this is an error that would pop up if an operator is overriden with the legacy method instead of the new temp_override one. Either downgrade Blender to V3.6 or upgrade to the latest BlenderBIM dev build https://github.com/IfcOpenShell/IfcOpenShell/releases

**Comment by Gunner90** [comment]
Thank you, that solved the problem.
