### ISSUE TITLE
ifcopenshell.open() not threadsave?

### ISSUE THREAD

**Issue by c-mellueh** [IfcOpenShell/IfcOpenShell#4452]
I tried running `ifcopenshell.open(xxx)` in a  [QRunnable](https://doc.qt.io/qtforpython-6/PySide6/QtCore/QRunnable.html#qrunnable) using [QThreadPool](https://doc.qt.io/qtforpython-6/PySide6/QtCore/QThreadPool.html#qthreadpool) and it still freezes my GUI. 
After some research i found sources saying that this could be because the function i was calling isn't threadsave.

When calling `ifcopenshell.open(xxx,should_stream = True)` with the same method  it works fine but crashes  afterwards (see #4448)
is this a known problem? 
Is there a workaround to run `ifcopenshell.open(xxx)` without freezing your script/program for the whole import process?

I have files that are >500MB. With an import time of >15s a user could think the program is crashed because there is no visible feedback and the GUI is frozen

**Comment by aothms** [comment]
This has likely nothing to do with thread safety, but just with the Python GIL. Regardless of threads, in general, only a single python instruction is executed at a time. Unless you tell python it's safe to executed another instruction in parallel.

So see below, whether we use 3 threads simultaneously or limit to 1, the time required to parse all three files is the same:

```
import ifcopenshell
import timeit
from concurrent.futures import ThreadPoolExecutor
fns = ["1.ifc", "2.ifc", "3.ifc"]
```

``` 
>>> timeit.timeit(lambda: list(ThreadPoolExecutor(max_workers=3).map(ifcopenshell.open, fns)), number=1)
14.672509300056845
>>> timeit.timeit(lambda: list(ThreadPoolExecutor(max_workers=1).map(ifcopenshell.open, fns)), number=1)
14.533609699923545
```

But with the change I committed here 4f53d8c5f19ff5990f1297e26c7322c0b0acbf88

The results are:

```
>>> timeit.timeit(lambda: list(ThreadPoolExecutor(max_workers=3).map(ifcopenshell.open, fns)), number=1)
8.956122800009325
>>> timeit.timeit(lambda: list(ThreadPoolExecutor(max_workers=1).map(ifcopenshell.open, fns)), number=1)
14.448163800057955
```

(My laptop doesn't multi-thread very well...)

I previously never enabled this, because the GIL is a nice feature to make sure your underlying C++ code doesn't need to be threadsafe. But at least ifcopenshell.open() should be so we can safely release the GIL. I'm less sure for example about ifcopenshell.geom.create_shape() although in reality that should also be fine.
