### ISSUE TITLE
Bcf client has not convient way to add snapshot

### ISSUE THREAD

**Issue by sharon-br** [IfcOpenShell/IfcOpenShell#4453]
Hello,
When creating `VisualizationInfoHandler`, one can provide a snapshot data that will be added to the topic, however even after attaching it using `topic.add_visinfo_handler(viewpoint_handler)`, the said snapshot is not in the output file.
After some looking around I found that `add_visinfo_handler` creates the `mdl.ViewPoint` object, which does support providing a snapshot filename but the wrapper function does not provide any proper way of setting it.
I ended up writing code that looks something like this:
```
viewpoint_handler = bcf_visinfo.VisualizationInfoHandler(visualization_info=viewpoint_info, snapshot=snapshot_data)
topic.add_visinfo_handler(viewpoint_handler)
topic.markup.viewpoints[-1].snapshot = f'{viewpoint_info.guid}.jpg'
```
I think that `add_visinfo_handler` should add a parameter or something of that sort to set the snapshot name, and maybe assert that if one is given, the VisualizationInfoHandler does indeed contain snapshot data

**Comment by Andrej730** [comment]
Thank you for the report.

I've added return value to `add_visinfo_handler` so it will be easier to edit the viewpoint if needed and I've added `snapshot_filename` argument.

>maybe assert that if one is given, the VisualizationInfoHandler does indeed contain snapshot data

It sounds good but since this API is kind of low-level I'm not sure that it's necessary that users will set up `VisualizationInfoHandler.snapshot` before setting up `ViewPoint.snapshot` and vice versa. I've added a warning though in `BcfXml.save` if only either snapshot data or snapshot filename is set as this case may lead to data loss.
