### ISSUE TITLE
Ifcopenshell: assignments not constant in time

### ISSUE THREAD

**Issue by jsammer-ode** [IfcOpenShell/IfcOpenShell#4474]
Hey everyone,
I am using ifcopenshell (python) to write an ifc file. I have seen that whenever I create a reference between two objects, the operation is non-constant in time.

My code looks something like this:

```python
model = ifcopenshell.file()

# Create an ifcProject, and a geometric context and subcontext...

site = run("root.create_entity", model, ifc_class = "IfcSite", name="Foo")
for _ in range(20000):
    element = run("root.create_entity", model, ifc_class=IfcBuildingElementProxy")
    run("spatial.assign_container", model, relativ_structure=site, product=element)
```

When omitting the last line, the operation is constant in time.
But when using `spatial.assign_container`, the operation becomes non-constant, and I get iteration times like this:
![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/135320118/7eb84e22-5e43-4a79-9034-2132bd6adc6f)

At iteration 12.000, it already takes 6 seconds to complete 100 iterations! I have seen the same behaviour when using `type.assign_type` to the IfcBuildingElementProxy. 

It appears that the creation of references has some dependency on the file size, which makes no sense to me since I am passing both `site` and `element` directly into the function.

Does anyone know if this problem also exists in C++? Has anyone observed the same behaviour?

**Comment by Andrej730** [comment]
I've narrowed down the slowest part:

```python
import ifcopenshell
from ifcopenshell.api import run
from time import time

model = ifcopenshell.file()

site = run("root.create_entity", model, ifc_class="IfcSite", name="Foo")
t0 = time()

element = run("root.create_entity", model, ifc_class="IfcBuildingElementProxy")
rel = run("spatial.assign_container", model, relating_structure=site, product=element)

for i in range(12000):
    if i % 100 == 0:
        print(f"{i}: {time() - t0}")
        t0 = time()
    element = run("root.create_entity", model, ifc_class="IfcBuildingElementProxy")
    # VVVVV slowest part VVVVV
    rel.RelatedElements = list(rel.RelatedElements) + [element]
```

**Comment by Moult** [comment]
This may be related to a similar phenomenon here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/element.py#L1123-L1131

See #3052. Ping @aothms perhaps?

**Comment by Andrej730** [comment]
If it helps, found that stripping away all python logic and using the most available low level methods can speed it up 2 times but bottle neck is in `entity_instance.setArgumentAsAggregateOfEntityInstance`.

```python
import ifcopenshell
from ifcopenshell import ifcopenshell_wrapper
from ifcopenshell.api import run
from time import time

model = ifcopenshell.file()

site = run("root.create_entity", model, ifc_class="IfcSite", name="Foo")
t0 = time()

element = run("root.create_entity", model, ifc_class="IfcBuildingElementProxy")
rel: ifcopenshell_wrapper.entity_instance = run(
    "spatial.assign_container", model, relating_structure=site, product=element
).wrapped_data

for i in range(2000):
    if i % 100 == 0:
        print(f"{i}: {time() - t0}")
        t0 = time()
    element = run("root.create_entity", model, ifc_class="IfcBuildingElementProxy")
    data = rel.get_argument(4) + (element.wrapped_data,)
    rel.setArgumentAsAggregateOfEntityInstance(4, data)

```

**Comment by aothms** [comment]
On the fundamental level, there is something we can do:

When reassigning an aggregate attribute, we first naively unregister all the inverses, and then register them back. When the two aggregates being assigned overlap significantly, this is a rather silly activity.

The best approach there would be if we implement a dedicated operator for `+=` because then the intent is actually clear, only instances need to be registered, but that's too much of an undertaking right now. Even in C++ we can't add to an aggregate, only reassign.

But even with a more intelligent handling of the inverses, when replacing an attribute value, (un)register based on the set difference, there isn't a major difference.  See commented code in commit, I'm not enabling it now, because I feel it's another buggy code path in a messy plate of spaghetti. 

The reason is that after this fix still the majority of time is spent in the C++ pythonize() call which makes the C++ data accessible to python. This remains a linear operation based on the aggregate size (and keeps creating new wrapper instances btw talking to the same C++ pointer so the python gc is also very busy!)

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/0e850076-433f-43a6-a0ad-b20a08226c3d)

There is no way doing this incrementally, pinging back from python to C++ is going to be constant time.

So I recommend instead that we somehow adapt `spatial.assign_container` to also accept a list/tuple of products.

**Comment by Moult** [comment]
Yes indeed one of the "big changes" I'd like to make to the API is to make it support multiple elements by default. This doesn't need to be done all in one go, it can be done incrementally.

The only reason they were implemented to accept 1 element was because I was learning IFC as I went and it was just simpler. Now that we have test cases there is no reason for it to be that way anymore.

@jsammer-ode is this academic or do you have a real usecase of needing to assign many elements to a container? Would you be interested in contributing?

**Comment by Moult** [comment]
OK that sounds good. Can you make a list of the API calls that you use? We can convert those first to help you, or alternatively if you need a fix immediately we can show you how to write the lower level code.

Dion Moult

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Moult** [comment]
@jsammer-ode BTW in case you missed it @Andrej730 has implemented the assign_container batch assignment. It'd be awesome if you could help test - I assume the assign_type will also be implemented soon.

**Comment by Andrej730** [comment]
> For completeness, passing a single element (instead of a list of elements) to a function that now supports batch assignment will result in an AttributeError. To avoid future tickets addressing this issue, it might be helpful to already address this issue right away? e.g. typecast to list, update docs asap,...

I don't think it should cast to list - since it's a new argument and it's name suggests that user should provide it as a list / some kind of iterable. Though there is still support for old arguments without batching (like `product`, `relating_object` etc) but it prints warning message that this argument is deprecated (#4531).

Changing api to support batching is still in progress, we'll update docs right after we finish it.
