### ISSUE TITLE
Specifying a standard `__version__` string

### ISSUE THREAD

**Issue by swiss-knight** [IfcOpenShell/IfcOpenShell#4511]
Hello,

what about specifying a `__version__` string for `ifcopenshell`?

I donwloaded the latest `ifcopenshell` from pypi.org and currently:

```
import ifcopenshell

ifcopenshell.__version__

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ifcopenshell' has no attribute '__version__'
```

See also:
https://packaging.python.org/en/latest/guides/single-sourcing-package-version/    
https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers

Thanks 🙏!

**Comment by aothms** [comment]
We have `ifcopenshell.version` but not __version__. That's an easy fix.

```
>>> import ifcopenshell
>>> ifcopenshell.version
'v0.7.0-6c9e130ca'
```

However as per your document:

> Many build tools integrate with distributed version control systems like Git and Mercurial in order to add an identifying hash to the version identifier. As hashes cannot be ordered reliably such versions are not permitted in the public version field.

So there is still something to do to maintain a lexicographically ordered field. 

```
$ git merge-base v0.6.0 v0.7.0
b8d36a63a29f37193f52027b421607f7c37434ce
$ git rev-list --count b8d36a63a29f3..ac7f2aeb6217
5388
```

So?  `0.7.0.5388` ? Any ideas? @swiss-knight any capacity to contribute to this perhaps? Basically means creating a variant of https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/cmake/CMakeLists.txt#L69

**Comment by Moult** [comment]
See #3927 - perhaps now is a time to set a ballpark date for when v0.8.0 will be ready so we can work backwards to figure out the steps leading up to it to rejig the build systems?

**Comment by aothms** [comment]
> when v0.8.0 will be ready 

I think the question is more when we (the community) are ready to make the jump. It will be rough around the edges for some time, but not in a way that it will be the major cause of frustration I would say. And there is some things we still need to iron out (I want the geometry settings to be independent of step file ids so that they're portable for example, so we still need to rework the context selection using attributes, but we have a more versatile strongly typed settings module now). There's a handful of deeply obscure things not implemented (yet / or will never be), such is IfcCenterLineProfileDef. But we get also get some things in return, such as the alignment geometry by @RickBrice (I think blenderbim would be an absolutely awesome tool with 4.3 support) and a more light weight mesh importer.

**Comment by Moult** [comment]
Yep let's wait until the next BBIM release which will clean up the clash code and probably focus more on bugs than new features.

**Comment by RickBrice** [comment]
I would love to have people start using the alignment code. It really needs to be put to the test.
