### ISSUE TITLE
ifcopenshell pypi release for blenderbim release version 240402 ?

### ISSUE THREAD

**Issue by ay-ex** [IfcOpenShell/IfcOpenShell#4512]
would be great if we could have a matching ifcopenshell python package on pypi for blenderbim release 240402.  🙂 
this would allow to package non-bbim/ifcos-dependent applications with the same ifcopenshell version with updates, 
like the recent ids upgrade. 
currently pypi shows `0.7.0.231218` as latest version. 

@Moult ^^ as discussed in chat.

I assume this is the github action responsible for the pypi:
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/.github/workflows/ci-ifcopenshell-pypi.yml

last successful run was 6months ago:
https://github.com/IfcOpenShell/IfcOpenShell/actions/workflows/ci-ifcopenshell-pypi.yml

so far I was not a able to spot anything problematic.
as side note: we could probably reduce the python versions L38 from:
`pyver: [py36, py37, py38, py39, py310, py311]` to `pyver: [py39, py310, py311]`

**Comment by ay-ex** [comment]
I checked the failed actions and found errors on most py versions. 
it sounds like we reached a size limit on pypi?: 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/127405908/b9d4e137-8831-4a2d-b654-a268ebc42851)

**Comment by Moult** [comment]
Cheers yeah it was a size limit. https://github.com/IfcOpenShell/IfcOpenShell/issues/2932#issuecomment-1614176728 - I thought we'd last longer but hey time flies. Basically once a year I need to remember (probably the hard way) to clear up the cruft. Since it's only once a year it's probably not worth bothering them with an issue request. Also last I checked there wasn't a way to automate via the API but maybe it'll change in the future.

**Comment by ay-ex** [comment]
Thank you!! 😄
