### ISSUE TITLE
Python docs return 404 error

### ISSUE THREAD

**Issue by piotr-smolira** [IfcOpenShell/IfcOpenShell#4519]
BlenderBIM documentation works: https://docs.blenderbim.org/
Primary IfcOpenshell docs works: https://ifcopenshell.github.io/docs/

Python documentation doesn't work: example: https://blenderbim.org/docs-python/ifcopenshell-python/geometry_tree.html

**Comment by Moult** [comment]
It's moved to https://ios-docs.blenderbim.org/ - the goal is for it to migrate to https://docs.ifcopenshell.org/ when @aothms gets a chance.

**Comment by Andrej730** [comment]
Can we setup a redirect that would redirect from old links to the new ones? So that all those links on OSArch won't get invalid.

blenderbim.org/docs-python/ifcopenshell-python/geometry_tree.html -> ios-docs.blenderbim.org/ifcopenshell-python/geometry_tree.html
blenderbim.org/docs/devs/hello_world.html -> docs.blenderbim.org/devs/hello_world.html

**Comment by aothms** [comment]
> when @aothms gets a chance.

done just now

```
>nslookup docs.ifcopenshell.org
Server:  home
Address:  192.168.1.1

Non-authoritative answer:
Name:    ifcopenshell.github.io
Addresses:  2606:50c0:8002::153
          2606:50c0:8000::153
          2606:50c0:8003::153
          2606:50c0:8001::153
          185.199.110.153
          185.199.111.153
          185.199.109.153
          185.199.108.153
Aliases:  docs.ifcopenshell.org
```

**Comment by Moult** [comment]
Unfortunately I don't think we can do a redirect because it's now hosted on github pages, which can't actually do full rewriting: https://stackoverflow.com/questions/9276817/301-redirect-for-site-hosted-at-github
