### ISSUE TITLE
IfcProductType instances not updating

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4528]
IfcProductType instances not updating....

https://community.osarch.org/discussion/2057/instances-of-an-ifctypeproduct-not-linked-from-one-drawing-to-the-other#latest

**Comment by Moult** [comment]
I think this is because prior to the bugfix, any update to the geometry would actually break the type representation mapping. This means that annotations which existed and were edited prior to the bugfix would still exhibit weirdness.

After the bugfix, all new product type instances should be ok.

Try this patch to repair the file:

```python
import ifcopenshell
import ifcopenshell.util.element

f = ifcopenshell.open('/home/dion/tmp/linkedtypeproductbug/ifcproducttype2.ifc')
for element_type in f.by_type("IfcTypeProduct", include_subtypes=False):
    for element in ifcopenshell.util.element.get_types(element_type):
        ifcopenshell.api.run("type.map_type_representations", f,
            related_object=element, relating_type=element_type)
            
f.write('/home/dion/tmp/linkedtypeproductbug/ifcproducttype2-fixed.ifc')
```

**Comment by theoryshaw** [comment]
That seemed to work!
Thanks Dion.
