### ISSUE TITLE
Conversion never finishes on wall (example file) – infinite loop?

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#455]
1. Convert [455--wall--infiniteLoop--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/455--wall--infiniteLoop--augmented.ifc) with 6c1ad47 (OCCT 7.3.0)
2. Experience that the conversion never finishes (at least not finished after 16h)
3. File opens without warnings in Solibri and SimpleBIM:
<img width="500" alt="screen shot 2018-09-08 at 18 07 33" src="https://user-images.githubusercontent.com/4601554/45267352-08fb7e00-b46b-11e8-88b1-cee8617ff956.png">

**Comment by aothms** [comment]
This seems like a rather benign wall, but there is this weird internal thing consisting of over 10 000 faces.

<img width="903" alt="2018-09-12 1" src="https://user-images.githubusercontent.com/1096535/45431078-24eb6380-b6a7-11e8-9599-560af2075109.png">

Because there are also boolean operations applied to this wall the edges need to be glued to form a topological volume and that would indeed take ages on this amount of faces.

There is already some logic to disable these operations on overly detailed geometries. I extended that a bit. A boolean operation on this particular shape would likely give errors as well, due to additional overlapping faces, even though we didn't even get to that point.

**Comment by johanrd** [comment]
Thanks! Seems to work - The file seems to run nicely through now. Even the boolean operations seems to be applied correctly when building from commit 08557c2

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this converts successfully on 808ef1a (OCCT 7.5.0)
