### ISSUE TITLE
Shade color is changed, but color is not changed in the viewport, upon re-opening of the file. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4567]
Shade color is changed, but color is not changed in the viewport, upon re-opening of the file. 

file: https://www.dropbox.com/scl/fi/ec25dk1rtskf3xyt7fiu0/Restaurant_Pewaukee_shading-test.ifc?rlkey=t93rpawibfs9e0bslcmm3d7ac&dl=1

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f5af8d26-e20d-44a6-b417-5f06bf0ffb39

**Comment by theoryshaw** [comment]
i think i get why this is so. 

Is it because when a material is run by external shader, the following styles are overridden, from the definitions in the external file?
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/40abfab0-1edc-4970-9621-fe30fce7e763)

If so, does it makes sense, to have the UI, turn these options off, if there's an external shader definition?

**Comment by Tudjack** [comment]
I discovered a similar problem when duplicating an object which has IfcOpeningElement's. 
If you want to apply a different material style to the duplicate it won't change on model reload.

**Comment by theoryshaw** [comment]
> I discovered a similar problem when duplicating an object which has IfcOpeningElement's. If you want to apply a different material style to the duplicate it won't change on model reload.

not sure, but try this, might help... 
see video: https://community.osarch.org/discussion/comment/19036/#Comment_19036

**Comment by Tudjack** [comment]
I know how to circumvent the bug, but it's still a bug. :)

**Comment by Andrej730** [comment]
I don't think it's a bug, it's just confusing UX... 
Basically now we always prioritize external style (if it's present) over other style components (shading, rendering, textures).

Currently, the only way to make sure it will prioritize "Shading" style and not "External" is to either not to add external style at all or to make sure it's Location is either null or not a blend file:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/e10485ed-209d-427b-986b-bf821e65074b)



> If so, does it makes sense, to have the UI, turn these options off, if there's an external shader definition?

I'm not sure we can, since IFC allows having all those components defined simultaneously, so it should be possible to edit them.


I've changed it a bit, so it now should be more clear - when you finish editing shading properties it will fallback to external style (if external style is active).

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/5402d9b4-676a-4726-97d5-e4338f681f89


> I discovered a similar problem when duplicating an object which has IfcOpeningElement's.
If you want to apply a different material style to the duplicate it won't change on model reload.

@Tudjack can you please show an example how to reproduce this? 
In case if it's similar to what Ryan mentioned in https://community.osarch.org/discussion/comment/19036/#Comment_19036, then it's not a bug - back then there was no UI to unassign style from representation items,and since those styles takes the highest priority they always reappeared on reloading the representation.

**Comment by Tudjack** [comment]
Sorry, I had no time to replicate the issue this week.
But basically, model a cube, add a style to it, add an IfcOpeningElement to it, duplicate it. 
To the duplicated object can't be assigned any other style, on file reload or entering edit mode and exit back to object mode, only the style from the original remains applied.

**Comment by Tudjack** [comment]
[Surface_Style_Test.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15274658/Surface_Style_Test.zip)

**Comment by Tudjack** [comment]
Try adding a style to any of the cubes in the ifc I sent above.

**Comment by Andrej730** [comment]
@Tudjack issue is resolved now, maybe it was part of #4843.

https://github.com/user-attachments/assets/d29cf9e4-48f9-4c22-bd48-72cca54ddecd
