### ISSUE TITLE
failing to import util.selector

### ISSUE THREAD

**Issue by epeter-** [IfcOpenShell/IfcOpenShell#4570]
i don't know what happened.
my code up to now was like:
`import ifcopenshell`
`import ifcopenshell.api`
`import ifcopenshell.util`
`from ifcopenshell.util.selector import Selector`

i installed a new system (python) and now i get an error message:
Module not found error: no module named 'unicodedata' in module ........ ifcopenshell\\util\\selector.py' line 20 in module

what am i missing. till recently ifcopenhell ran in my system without 'unicodedata' 
remark: unicodedata2 is installed as pyd module 
tx

**Comment by Andrej730** [comment]
@epeter- 

Can you please copy here the full traceback?

> ifcopenshell\util\selector.py' line 20 in module

Is it failing during `lark` import? What version of `lark` do you have?

**Comment by epeter-** [comment]
![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/6928491/9384e9ac-12ed-4845-a016-6c1bdc0a13ce)
lark version is 1.1.9.

**Comment by epeter-** [comment]
unicodedata version is unicodedata2-15.1.0.

**Comment by Andrej730** [comment]
@epeter- 

It looks like you previously used older version of `lark` and now it's requiring `unicodedata` - https://github.com/lark-parser/lark/commit/74c94bb3695453e13ba540587e6d308b5f9de827

I'm not sure if `unicodedata2` helps if `unicodedata` module is missing.

Do you have `unicodedata.pyd` module somewhere in your system? I have it in `Python 3.11\DLLs\unicodedata.pyd`. If it's missing maybe it's something about the python installation? Or if it's present then it's something about the system paths since python couldn't locate it.

**Comment by epeter-** [comment]
i do not have the unicodedata.pyd on the system, and cannot find it on the net. all i have is unicodedata2.pyd

**Comment by epeter-** [comment]
@Andrej730 thank you for guiding me in the right direction!
as you suggested lark is now 1.1.9 as current version. when installing lark 1.1.8 the code worked again.
