### ISSUE TITLE
Inquire about the LOD related matters of IFC

### ISSUE THREAD

**Issue by jingyangking** [IfcOpenShell/IfcOpenShell#4591]
Hello developer, I would like to inquire if there is a tool that can automatically grade IFC models without the need for format conversion. If no such tools are currently available, can we manually grade the IFC model directly? How to operate it specifically? Thank you.

**Comment by Moult** [comment]
What do you mean by grade?

**Comment by Moult** [comment]
There is no agreed standard on how to automatically grade the LOD, since people provide different definitions. However with IfcOpenShell python and IfcTester you can check a number of things:

 - Use IfcTester along with your own IDS to check level of information provided in the model, such as checking whether properties exist, materials are assigned, and so on.
 - Use ifcopenshell python to check whether or not things like walls are still designed using parametric layer sets, or broken down into assemblies.
 - For some scenarios, you can calculate a bounding box using ifcopenshell.geom and ifcopenshell.util.shape and compare total vertex counts.
 - You can check for the usage of generic classes or generic materials via their names.
 - If you use classification systems and require it on the project, you can check the depth of the classification which may correlate to LODs.

**Comment by jingyangking** [comment]
Sorry, I have some questions about the meaning expressed earlier. What I want to say is, is there a tool that can automatically subtract the number of faces from the IFC model to form an IFC model with different levels of detail, just like the image below, but what I need is to do the overall reduction.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/112468121/613cc8d6-d0cb-43b6-a10d-5429c4745a20)

**Comment by Moult** [comment]
There are general strategies that can do this, like using merge vertices by distance, or by getting OBBs, or using voxelisation.

**Comment by aothms** [comment]
See for ex: https://doc.cgal.org/latest/Surface_mesh_simplification/index.html

In the v0.8 branch it's more straight forward to integrate this since we can use CGAL there. But there is currently no effort on this.

Note that IFC geometry is likely more semantic and procedural then just plain meshes, so it isn't necessarily so straight forward / universal. Your example (a) can be a pure IfcCircle in IFC which is most efficient and semantic. Does that count as high or low LOD? LOD concepts in IFC are rather different from GIS.

**Comment by jingyangking** [comment]
> See for ex: https://doc.cgal.org/latest/Surface_mesh_simplification/index.html
> 
> In the v0.8 branch it's more straight forward to integrate this since we can use CGAL there. But there is currently no effort on this.
> 
> Note that IFC geometry is likely more semantic and procedural then just plain meshes, so it isn't necessarily so straight forward / universal. Your example (a) can be a pure IfcCircle in IFC which is most efficient and semantic. Does that count as high or low LOD? LOD concepts in IFC are rather different from GIS.

Thank you for your reply. At present, I plan to apply IFC to BIM, so the lower the number of faces, the lower the LOD level. But currently, I haven't found any tools for automatic noodle reduction, which is very frustrating for me!

**Comment by jingyangking** [comment]
> > which is very frustrating for me
> 
> IFC is well established as a construction coordination format. Together with neighbouring standards IDS (for information requiremenets) and BCF (for communication) there are well established workflows on how IFC is used in the construction sector. What you're trying to do is interesting/relevant/necessary but rather far outside of how IFC is typically used. If you want to advance on this front there are great toolboxes out there (IfcOpenShell included) that can act as a starting point, but you have to be ready to form the pieces of the puzzle into working solution **yourself** with guidance from the community where possible.

Thank you for your reply! I think I know what I should do now
