### ISSUE TITLE
ifc -> cityjson inquiry using ifccovert

### ISSUE THREAD

**Issue by Pdongjaelee** [IfcOpenShell/IfcOpenShell#4705]
Why is it that ifc -> cityjson files cannot be converted using ifccovert?

Is it because the capacity is large?

**Comment by Moult** [comment]
There is nothing stopping a direct conversion of IFC -> CityJSON. CityJSON can support the full tessellated geometry of IFC. However as described in https://github.com/IfcOpenShell/ifc-to-cityjson this geometry might be semantically not very useful or too detailed. So that particular repo attempts to accommodate this by doing expensive computation to union shapes together.

This is completely optional. Depending on your usecase, if you had an appropriate IFC model with some heuristics, you could use bounding boxes or just IfcSpace elements to get you what you need. But right now the vanilla IfcConvert does not have CityJSON serialisation built into it. This could be a lot faster but sacrifice the "generalisation" of the algorithm.
