### ISSUE TITLE
IfcHeader "Authorization"

### ISSUE THREAD

**Issue by epeter-** [IfcOpenShell/IfcOpenShell#4717]
i am trying to parse and modify ifc-files for "FILE_NAME"."authorization" and fail
i tried it using ifc.wrapped_data.header.file_name.authorization but failed
all other wrapped_data.header entries are read as expected.
any suggestions?
attached bSI table
![grafik](https://github.com/IfcOpenShell/IfcOpenShell/assets/6928491/2ee091e4-5404-4acb-84b6-08dba20fc3aa)

**Comment by aothms** [comment]
can you share the model (or at least the header part of it)?

**Comment by Andrej730** [comment]
> i tried it using ifc.wrapped_data.header.file_name.authorization but failed
@epeter- could please provide example header of .ifc file or provide an error you've met?

It's probably something invalid about current authorization value.
In the [IFC spec](https://standards.buildingsmart.org/documents/Implementation/ImplementationGuide_IFCHeaderData_Version_1.0.2.pdf) every attribute in file_name is not optional and has some type to it.
```express
ENTITY file_name;
    name : STRING (256);
    time_stamp : time_stamp_text;
    author : LIST [ 1 : ? ] OF STRING (256);
    organization : LIST [ 1 : ? ] OF STRING (256);
    preprocessor_version : STRING (256);
    originating_system : STRING (256);
    authorization : STRING (256);
END_ENTITY;
TYPE time_stamp_text = STRING(256);
END_TYPE
```

I'm not sure if there is need to retrieve the actual value if it's invalid since it's just a header but I guess current error message indeed could be confusing (e.g. `RuntimeError: Token $ at offset 60 invalid string`) and may looks like some internal IfcOpenShell error and not the problem with the provided file and it can be impoved: `RuntimeError: Current header attribute "authorization" value is invalid: "$", expected a string value."

```python
import ifcopenshell

ifc_file_str = """ISO-10303-21;
HEADER;
FILE_DESCRIPTION((),'2;1');
FILE_NAME($,$,$,$,$,$,$);
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
ENDSEC;
END-ISO-10303-21;
"""
ifc_file = ifcopenshell.file.from_string(ifc_file_str)

# ('Token $ at offset 60 invalid string',)
try:
    ifc_file.wrapped_data.header.file_name.name
except Exception as e:
    print(e.args)
# ('Token $ at offset 62 invalid string',)
try:
    ifc_file.wrapped_data.header.file_name.time_stamp
except Exception as e:
    print(e.args)
# ('Argument is not a list of strings',)
try:
    ifc_file.wrapped_data.header.file_name.author
except Exception as e:
    print(e.args)
# ('Argument is not a list of strings',)
try:
    ifc_file.wrapped_data.header.file_name.organization
except Exception as e:
    print(e.args)
# ('Token $ at offset 68 invalid string',)
try:
    ifc_file.wrapped_data.header.file_name.preprocessor_version
except Exception as e:
    print(e.args)
# ('Token $ at offset 70 invalid string',)
try:
    ifc_file.wrapped_data.header.file_name.originating_system
except Exception as e:
    print(e.args)
# ('Token $ at offset 70 invalid string',)
try:
    ifc_file.wrapped_data.header.file_name.authorization
except Exception as e:
    print(e.args)
```

**Comment by Moult** [comment]
Bump @epeter-

**Comment by aothms** [comment]
Maybe it's also a bit unfortunate that the header entities don't inherit from entity_instance in Python (they do to some extent in C++) so you can't call things like get_info() or get_attribute_names() so it reads all a bit repetitive if you need to try catch everything. Maybe this is something to look into for 0.8 but probably not a really high prio thing.

**Comment by Moult** [comment]
@epeter- feel free to reopen if you have an example :)
