### ISSUE TITLE
Material application error 

### ISSUE THREAD

**Issue by Dayo9174** [IfcOpenShell/IfcOpenShell#4755]
Hello everyone, 
I encountered an error whenever I try to add a material category or edit the name of a material.

See images below, might be i don't know what i am doing but it does not hurt to ask.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/129775059/d2de126b-d194-451c-a0ff-2b84c6f45c30)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/129775059/0c3cead1-65d6-4ea6-b113-a2bc968ad111)

Error code

```
os: Windows
os_version: 10.0.22631
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
blender_version: 4.1.0
blenderbim_version: 0.0.240527
last_actions: 
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 53100, "Name": null}}
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 53647, "Name": "Footing"}, "pset": {"cast_type": "entity_instance", "value": 53669, "Name": "EPset_Parametric"}}
# ifcopenshell.api: material.unassign_material
>>> {"products": [{"cast_type": "entity_instance", "value": 53647, "Name": "Footing"}]}
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_edit_assigned_material
# ifcopenshell.api: material.edit_assigned_material
>>> {"element": {"cast_type": "entity_instance", "value": 51368, "Name": null}, "attributes": "{'LayerSetName': None, 'Description': None}"}
# ifcopenshell.api: material.edit_layer_usage
>>> {"usage": {"cast_type": "entity_instance", "value": 51708, "Name": null}, "attributes": "{'LayerSetDirection': 'AXIS2', 'DirectionSense': 'POSITIVE', 'OffsetFromReferenceLine': 0.0, 'ReferenceExtent': None}"}
# operator: BIM_OT_enable_editing_material
# operator: BIM_OT_edit_material
# ifcopenshell.api: material.edit_material
>>> {"material": {"cast_type": "entity_instance", "value": 51361, "Name": "Div - 03 00 00"}, "attributes": "{'Name': 'Div - 03 00 00-02', 'Description': 'Concrete', 'Category': 'SJCES - PM'}"}
last_error: Traceback (most recent call last):
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\ifc.py", line 360, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\material\operator.py", line 80, in _execute
    core.edit_material(tool.Ifc, tool.Material, material=tool.Ifc.get().by_id(self.material))
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\core\material.py", line 88, in edit_material
    material_tool.sync_blender_material_name(material)
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\material.py", line 246, in sync_blender_material_name
    style = tool.Style.get_style(obj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dayo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\style.py", line 107, in get_style
    if obj.BIMMaterialProperties.ifc_style_id:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'BIMMaterialProperties'

ifc: 00.SJCES - Main Building.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell v0.7.0-f7c03db75
originating_system: BlenderBIM 0.0.240512-aca26c7
```

**Comment by Andrej730** [comment]
@Dayo9174 can you please share .ifc file to reproduce the issue?
From the logs it seems that material "Div - 03 00 00" doesn't have a corresponding blender material which shouldn't occur.

**Comment by Dayo9174** [comment]
I have added both the .blend and IFC files. From my testing, it appears that the error only occurs when working within the .blend file. Files are Zip'd below
[Error file.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/15491406/Error.file.zip)

Additionally, while I am working in the .blend file that saves the project simultaneously to an IFC file, the image below shows that the IFC file and the .blend file are generating different objects.

.blend File
![Screenshot - blend file ](https://github.com/IfcOpenShell/IfcOpenShell/assets/129775059/739609a9-bd28-4255-b2ee-8ea0a0009572)

IFC file 
![Screenshot - IFC file -2](https://github.com/IfcOpenShell/IfcOpenShell/assets/129775059/26549f2f-45bd-4ca4-945f-0894748d38b5)

Don't know if this is the same error or something different 

Thanks for the help

**Comment by Andrej730** [comment]
The problem is that .blend file got out of sync with .ifc, you might have also met errors like `RuntimeError: Instance # 1234 not found` using it, see [common issues](https://docs.blenderbim.org/users/troubleshooting.html#common-issues):

1) material "Div - 03 00 00" is indeed missing corresponding blender material which shouldn't happen.

2) missing elements in IFC, e.g. this object is internally linked to the ifc element with id `# 55697` but this id is not present in IFC file anymore.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/67ce0db8-3f5c-4dd4-972a-4c7fc2590be3)

3) some objects are present in IFC but not present in .blend file. E.g. this element with guid `1xVKSv2Nf5UhPPwKIpGjBK` is not present in the .blend file. Could happen if you unlink element without removing it from IFC.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/5bf289de-5789-46b7-ad39-046c8764d478)

It's hard to tell what's happened, we can fix these kind of issues only when we know the way to reproduce them with freshly loaded .ifc file. It's generally recommended to use just .ifc without .blend but using .blend file does has it's benefits so please report if you find any way to reproduce those issues. To continue working with this file the best option for you probably is to reload IFC project to a new Blender session.

**Comment by Dayo9174** [comment]
Noted, I will go .IFC for this project. But I will be on the look out when ever I do a .blend/.IFC project 
Thanks

**Comment by Andrej730** [comment]
Sure, feel free to reopen this if there will be a new information.
