### ISSUE TITLE
How to add extended new entities(with *.exp) into the ifcopenshell-python?

### ISSUE THREAD

**Issue by shungeer** [IfcOpenShell/IfcOpenShell#4814]
I extended the IFC4x3_ADD2 schema with a new entity, "IfcTunnel". How can I add this new entity into the ifcopenshell-python for parsing this entity?

### Current Steps:
1. Added "IfcTunnel" into IFC4X3_ADD2_EXTN.exp
```
TYPE IfcTunnelTypeEnum = ENUMERATION OF  
	(USERDEFINED
	, NOTDEFINED); 
END_TYPE;

ENTITY IfcTunnel
	SUBTYPE OF (IfcFacility); 
	PredefinedType:OPTIONAL IfcTunnelTypeEnum; 
END_ENTITY;
```

2. Generating code. https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/ifcopenshell-python/ifcopenshell/express#command-line-usage-for-code-generation 
```
>>> python3 bootstrap.py express.bnf > express_parser.py
>>> python3 express_parser.py IFC4X3_ADD2_EXTN.exp header implementation schema_class definitions
```

3. Used.
```
import ifcopenshell
from ifcopenshell.api import run
from ifcopenshell.api import owner
import ifcopenshell.api
import ifcopenshell.guid
import ifcopenshell.express
schema = ifcopenshell.express.parse(r'IFC4X3_ADD2_EXTN.exp')
ifcopenshell.register_schema(schema)
model = ifcopenshell.file(schema=schema.schema.name())

project = run("root.create_entity", model, ifc_class="IfcProject", name="test")

model3d = run("context.add_context", model, context_type="Model")
body = run("context.add_context", model,
    context_type="Model", context_identifier="Body", target_view="MODEL_VIEW", parent=model3d)
axis = run("context.add_context", model,
    context_type="Model", context_identifier="Axis", target_view="MODEL_VIEW", parent=model3d)

site = run("root.create_entity", model, ifc_class="IfcSite", name="Test Site")

################## create IfcTunnel entity ##################
tunnel = run("root.create_entity", model, ifc_class="IfcTunnel", name="Test Tunnel")
#####################################################

run("aggregate.assign_object", model, relating_object=project, products=[site])
run("aggregate.assign_object", model, relating_object=site, products=[tunnel])

run("geometry.edit_object_placement", model, product=tunnel)
representation = run("geometry.add_wall_representation", model, context=body, length=5, height=3, thickness=0.2)
run("geometry.assign_representation", model, product=tunnel, representation=representation)

model.write(r'G:\test-exp1.ifc')
```

### But Exception has occurred: 
ModuleNotFoundError: No module named **'ifcopenshell.express.rules.IFC4X3_ADD2_EXTN'**

May I miss some steps? How can I generate this **'ifcopenshell.express.rules.IFC4X3_ADD2_EXTN'**？

**Comment by aothms** [comment]
A couple of things:

1.

> ModuleNotFoundError: No module named 'ifcopenshell.express.rules.IFC4X3_ADD2_EXTN'

Maybe we try catch this import. This is only for the evaluation of derived attributes, which depends on generated python code.

2.

    python3 express_parser.py IFC4X3_ADD2_EXTN.exp header implementation schema_class definitions

This command generates the C++ classes for 'early-bound' interaction with the schema. (Which is necessary for evaluating geometry). 

> schema = ifcopenshell.express.parse(r'IFC4X3_ADD2_EXTN.exp')
> ifcopenshell.register_schema(schema)

But if you use the following way to interact with the schema you're using the 'late-bound' interaction. So C++ code generation would not be necessary.

3.

You actually need to use:

    python -m ifcopenshell.express.rule_compiler IFC4X3_ADD2_EXTN.exp

This will generate the missing ifcopenshell.express.rules.IFC4X3_ADD2_EXTN module.

4.

Keep in mind that Express is not very suitable for this kind of usage. In the end, (as far as I can tell) no tool is able to read your model, because it doesn't understand the schema as it has no notion of the core part vs the addition.

If you're only adding some building element classes. You might want to consider just using vanilla IfcBuiltElement with a custom IfcClassificationReference.

5.

IFC4.4 will be around IfcTunnel. There is an existing schema you could find for this, but it's not really harmonized yet (maybe) with everything in 4.3.

6.

Documentation and code is a bit spotty for this kind of usage. All contributions to code and documentation are very welcome! :)

**Comment by shungeer** [comment]
Thank you very much!!!

It's work well!

"Keep in mind that Express is not very suitable for this kind of usage. In the end, (as far as I can tell) no tool is able to read your model, because it doesn't understand the schema as it has no notion of the core part vs the addition." 
Thank for your advice. We use it in the standardization application of traffic with IFC4X3_ADD2 and we will provide some tool for it.

Thank you very much again!
