### ISSUE TITLE
[BlenderBIM] Bulk adding properties

### ISSUE THREAD

**Issue by olbull** [IfcOpenShell/IfcOpenShell#4816]
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/91160391/97843f5a-cfc8-4519-905e-284f0302fc44)

when bulk adding psets to objects, a ifcpropertysinglevalue is created for each object, instead of having all objects reference the same propertyset. Does this have a specific reason? Bulk adding properties on many elements considerably increases the size of the file with this way.

**Comment by Moult** [comment]
Yes, this is intentional, because:

 1. Contrary to most impressions, it is actually rare in practice to bulk set properties on many objects. Good model management typically means appropriately using types. Type properties are inherited by occurrences, so it is often sufficient to set the property once on the type, which is then inherited. When they are set per-occurrence, this usually means that the property should vary.
 2. Not sharing the same reference means that it is more efficient later on to make edits as you don't need to keep on checking for inverse relationships and cleaning up orphans. You can treat that portion of the subgraph as isolated. Especially if you're cooking up your own script, this makes life easier.
 3. Of course, later on you can "optimise" the file to recycle these entities. Preferably this is done centralised and automated and is more comprehensive than any UI attempting to be clever and doing it beforehand.
