### ISSUE TITLE
Import IFC from 12D not working for IFC4

### ISSUE THREAD

**Issue by JarmynT** [IfcOpenShell/IfcOpenShell#4867]
I tried search for this specific issue but to no avail.

Applying patches to 12D exports for use in Revit.
IFC2v3 works perfectly fine
IFC4 throws this error when opening the file in BlenderBIM

Can link the IFC4 file into another file via Project Setup > Links > Link IFC

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.0.240526
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\jarmyn.tschirpig\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 691, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\jarmyn.tschirpig\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\module\project\operator.py", line 771, in execute
    ifc_importer.execute()
  File "C:\Users\jarmyn.tschirpig\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 271, in execute
    self.parse_native_elements()
  File "C:\Users\jarmyn.tschirpig\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 484, in parse_native_elements
    if self.is_native(element):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jarmyn.tschirpig\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 516, in is_native
    if len(rep.Items) == 1 and rep.Items[0].is_a("IfcMappedItem"):
           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Items'
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109


ifc: HCD546-BGE-CIV-MOD-CSB-R23.ifc
schema: IFC4
preprocessor_version: IFC Engine rev 1062
originating_system: 12d Model 14.0C2k
```

**Comment by Moult** [comment]
Can you attach the file? dion@thinkmoult.com if private.

**Comment by Moult** [comment]
Thanks for sending the file. There are a few bugs in your model.

Firstly, on lines like `#193953 = IFCREPRESENTATIONMAP(#193954, $);` and `#227323 = IFCREPRESENTATIONMAP(#227324, $);`, you will notice it is missing a [mandatory second attribute](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcRepresentationMap.htm).

Secondly, the spatial decomposition is invalid. Your model aggregates an IfcSystem into the IfcSite: 

```
#22 = IFCRELAGGREGATES('2hCU4x8RL6dulXY7b0BpIE', #2, 'SiteContainer', 'SiteContainer For All Models', #19, (#21, #29653, #162245, #164327));
#164327 = IFCSYSTEM('0BI9JGH2LFNR2xfCPInlcg', #2, 'Stormwater alternative', 'Drainage network', $);
```

This is undefined behaviour and has recently been reclarified by Nick Nisbet during IDS discussion that this is invalid. Only spatial elements are allowed in the spatial composition (and a project): https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Object_Composition/Aggregation/Spatial_Composition/content.html

I'd recommend reporting a bug to 12D. You can link them to this post to help explain to them.

That said, because 12D is pretty commonly used, I've included a workaround to accomodate this type of invalid IFC data. Note that we're currently upgrading a bunch of stuff so the current unstable builds are more unstable than usual, so I'd recommend waiting a week until you update to get the fix. (Alternatively if it is urgent you can patch the commit - happy to guide you on this).
