### ISSUE TITLE
When duplicating a material, and renaming, it seems to rename materials that already assigned in the project.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4898]
When duplicating a material, and renaming, it seems to rename materials that already assigned in the project...

Video best describes it...

bb 240602

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/2a404de0-6ff8-4715-933d-ca462056a558

**Comment by Andrej730** [comment]
Can you please attach an ifc example?
Though issue probably was part of #4843 bugs and is resolved in the current version.

**Comment by theoryshaw** [comment]
cool, here's one... 

[testfile.ifc.txt](https://github.com/user-attachments/files/16111702/testfile.ifc.txt)

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/ce4697a8-4934-4ef7-87b5-e99262bb745f

**Comment by theoryshaw** [comment]
i'm still on 240605

**Comment by Andrej730** [comment]
Tested on 240602 - it was indeed an issue with materials linked to blender materials. Renaming a copy would rename it's Blender material and accidentally rename the original material because it was still connected to the original material by sharing the same style...

But your file helped uncovering a bug loading external styles on v0.8.0 which also helped uncover a bug with infinite loading of IFC project in BBIM 😁
Though ifcopenshell build in bbim daily build is not yet updated and still has this problem - I'll keep the issue opened until we bump build to 355cca3.

**Comment by Moult** [comment]
I think this can be closed?
