### ISSUE TITLE
Dropdown menus for active workspace tool options

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4956]
When a tool is active (e.g the wall tool), it shows options in two locations: in the top bar as a horizontal line of options, as well as in the sidebar as a vertical list of options.

The options never fit in the top bar so the top bar is basically useless. The user has to unintuitively scroll the top bar (drag MMB) so they end up toggling the side panel. I want to take all the non-critical options and group them into menus similar to how Blender already does this in their own top bar (e.g. View / Select / Add / Object).

Anybody tackling this give me a buzz before starting so we can chat :)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/447e84e3-e12c-44a4-b5d0-a26586f7ab01)

**Comment by Vanuan** [comment]
There's a third place, properties editor > tools. Though, I've just noticed it's hidden in BIM workspace. Hm, Blender icon also pushed from the subtab into dropdown. Lots of small changes.

**Comment by trhyder** [comment]
@Moult I would like to have a go at this one, if no one else is working on it.

**Comment by Moult** [comment]
Go for it!

**Comment by trhyder** [comment]
> Anybody tackling this give me a buzz before starting so we can chat :)

@Moult do you have any additional info?

**Comment by Moult** [comment]
The chat was to help point at which source code dirs should be used. Also as a discussion on what these menus should be titled. I feel as though the current grouping should be preserved, so an `Modify` menu for all the stuff like extend / butt / mitre, then an `Align` menu for alignment, `Mode` for toggling various modes, and `Aggregation` for the aggregation stuff. This'll continue to evolve over time but it's a start.

**Comment by trhyder** [comment]
@Moult Once I have live dev environment setup, a few pointers to the key files would be helpful to get me started. Currently, I am waiting for an update to `dev_environment.sh`

**Comment by trhyder** [comment]
Hey @Moult, I wanted to share some thoughts on this issue. What I really like about the existing setup is how, when you select an object, the available tools are right there, immediately visible. It’s a great feature that keeps things intuitive and efficient.

However, as this issue has identified, it is not quite working in its current format. The buttons are quite long, which can be a bit cumbersome. Plus, using the mouse wheel to scroll to the buttons that are off-screen isn’t very practical because it often breaks the scroll and ends up zooming in on the viewport instead.

I understand that the current proposal is to move these buttons into a new dropdown menu. While this change might help reduce clutter, it also means that the tools won't be as immediately visible when you select an object. Sure, the side panel can serve this purpose, but it has its own drawbacks—it takes up quite a bit of space and isn’t visible by default. New users might find it a bit tricky to locate, as they have to open the sidebar (shortcut: 'N') and then switch to the Tool tab. This process isn’t the most intuitive, especially for those just getting started with BlenderBIM.

With all that in mind, I’d like to propose keeping the tools in their current location but replacing the long labels with small graphical icons. We could add a hover state that displays the tool name, its shortcut, and its description, making it user-friendly and accessible.

This way, we can maintain the immediate visibility of tools when an object is selected while keeping the interface clean and user-friendly. What do you think? I've done a test to see how it could look.

![Screenshot 2024-08-07 085236](https://github.com/user-attachments/assets/6339c3a1-db35-407d-a14d-6f24b677119b)

**Comment by Moult** [comment]
That's an incredible idea! Did you design those icons? Can we add them to the icon pack?

**Comment by trhyder** [comment]
Thanks, I am glad you like it. If you want to see it in action here is my branch: https://github.com/trhyder/IfcOpenShell-trhyder/tree/tool-menu

I did design the icons and would be delighted for them to be added to the icon pack. I used the blenderbim_icons.blend file (sorry not in the branch) and just rendered out png's for my test layout. I need to do a bit more work on them and you may have some feedback, but how should I share them? There were also a few that I didn't know how to use (Decomposition, Mirror, Qty take-off) so if I understand them better I will be able to make clearer icons.

Would we be able to do a screen share sometime? I would probably benefit on some direction on how to better structure my code for integration into the main branch. I also had some other thoughts on simplifying the UI for voids and regen, which would be good to discuss.

**Comment by Moult** [comment]
Happy to meet anytime just ping me in the chat.

**Comment by Moult** [comment]
Bump @trhyder :) Just a friendly reminder that there will be a release next week in case you'd like this merged in prior to that.

**Comment by trhyder** [comment]
Sure, it's been a bit hard to be available for our timezones to overlap.

My main questions are to do with the icons within the repo.
1. What format should they be - and what workflow does that require? - currently, they are pngs rendered from a blend file
2. Where should they live in the repo? I've dumped them here `/IfcOpenShell/src/bonsai/bonsai/bim/module/model/icons` but I assume that is wrong
3. Should I separate `class BimToolUI` into two - one for the top bar, and one for the sidebar? - currently, it is one class and I added context input that it treats conditionally

Other things that are holding me up but I can probably figure out are that I don't know how to use the Mirror, Select Decomposition, and Qto Tools

**Comment by Moult** [comment]
1. I _think_ they can only be raster, so PNG. So whatever produces a PNG is fine, whether that's a SVG, or a Blender file, etc. Ideally it should be exported from a master icon SVG file, that way icon artists can work on it easily.
2. `src/bonsai/bonsai/bim/data/icons`
3. Best to split into two functions / classes / etc not conditionals since they are continuing to diverge.

Icons for mirror, select decomp and qto looks good.

Icons for align ext/int/center look misleading, that looks like a text align whereas this alignment should be along the axis, not perpendicular.

**Comment by manuvarkey** [comment]
The icons do not have proper contrast on light themes.

![Screenshot from 2024-08-27 11-28-47](https://github.com/user-attachments/assets/00b9504e-ff02-4256-b7d8-e02e125124f1)

**Comment by manuvarkey** [comment]
Any idea how blender handles icon modifications for light/ dark theme ?

Btw @trhyder the icons look great!

**Comment by Moult** [comment]
I'm personally only aware of using rasters, not vectors with dynamic colours.

I think a good solution would be to:

 1. Put all our custom icons into a master SVG file that is gridded - each grid cell contains a single icon
 2. Have a script that auto exports this SVG file into many rasters. It may also change colours to toggle a dark / light mode.
 3. Offer dark / light mode toggle in settings.

**Comment by trhyder** [comment]
I have been working on the cad tools icon, and have run into some questions. Here is my progress
<img width="872" alt="image" src="https://github.com/user-attachments/assets/6a7ed976-fd87-434c-b4dc-ed30914ff8a5">

1.  I am having trouble getting the "Extend" CAD tool to work as anticipated. My expectation is, that when I select two nodes (or one edge), clicking "Extend" should move the node closest to the 3D cursor along the direction defined by the two nodes, positioning it at a new point perpendicular to the 3D cursor. However, this isn't happening as expected. Instead, it doesn't seem to do anything and there is no error message. I noticed in IfcOpenShell/blob/profile-axis-ui/src/bonsai/bonsai/bim/module/cad/operator.py#L37  there has been an attempt to jump out and back into edit mode, but I don't think it works. Should I hide the button for now?
2. I have noticed that there are two ways to apply changes made in Edit Mode. Because I usually shortcut into edit mode using the TAB shortcut (long-time blender user) I always just TAB out. Is there a reason behind creating an additional hotkey combo? I would prefer to just show and use the tab method.
3. I also don't see the need for the disable edit button and would like to propose removing it. Vanilla Blender doesn't have this way of working. Again as a long-time blender user, I expect all changes I make in Edit Mode to be permanent and savable and I rely heavily on the undo shortcut.  I have also never been a fan of the disable vs remove/unassign "x" icons as to me they look too similar. I would prefer to either not have a disable edit button and just have the apply button, or maybe it could be possible to use the Esc as a shortcut to cancel editing and disregard changes?

**Comment by trhyder** [comment]
Two more underway Edit Railing Path and Edit Roof Path and another question
<img width="796" alt="Screenshot 2024-09-11 at 10 12 50 PM" src="https://github.com/user-attachments/assets/f11a4e8d-c434-4110-97d5-db85dddae806">
<img width="799" alt="Screenshot 2024-09-11 at 10 12 36 PM" src="https://github.com/user-attachments/assets/85efbd9a-7a59-4845-ae65-f6e997166856">
<img width="911" alt="Screenshot 2024-09-11 at 8 56 53 PM" src="https://github.com/user-attachments/assets/5cccc056-6c88-4525-b85c-e5b6f401f529">

1. I don't really understand what 2-Point Arc is meant to do. It seems to create 3 additional points - is it a 5-Point Arc tool? Also, depending on the direction of the path, the operation can break a path. It does something in Edit Railing Path mode, however in Edit Roof Path Mode, it breaks the continuous path which results in an error. I am a bit stumped on this one, what is it intended to do?

**Comment by trhyder** [comment]
Hey @Moult it's still a work in progress but I would appreciate your feedback on my branch

https://github.com/trhyder/IfcOpenShell/tree/profile-axis-ui

**Comment by Moult** [comment]
> I am having trouble getting the "Extend" CAD tool to work as anticipated

Select two edges and Shift-E and it'll extend one to another like in AutoCAD. The 3D cursor plays no role.

![2024-09-20-223124_249x157_scrot](https://github.com/user-attachments/assets/fa692927-feef-4963-a0fd-c2791ce48c4c)

> I have noticed that there are two ways to apply changes made in Edit Mode.

This is historic. You are right that it should be consolidated. I've restored it temporarily because there are ongoing large changes right now in this area.

> I also don't see the need for the disable edit button and would like to propose removing it.

This is needed, please don't remove it. Changes in IFC are not as efficient as changes in Blender, especially for dense meshes. Being able to discard changes ensures you don't make any unintended changes. Undoing after the fact is pretty inconvenient on complex or large models. It is also important if you've messed up the profile and created an invalid profile loop and don't want to clean it up.

> I don't really understand what 2-Point Arc is meant to do

In contrast to the 3 point arc (defined by 3 points which lie on the arc), the 2 point arc is defined by 2 points (vertices) on the arc, and a centerpoint (3D cursor). Pretty unintuitively, it does not work in profile mode (which is silly because that's like the most important mode) but it does work in regular mesh editing mode and creates a faceted arc not a true IFC arc.

Work needs to be done to make it actually do something useful in a profile mode and create a true arc.

![2024-09-20-223654_428x313_scrot](https://github.com/user-attachments/assets/d4ea73b3-6d25-44f4-8817-400749018fc7)

... after running operator ...

![2024-09-20-223713_504x425_scrot](https://github.com/user-attachments/assets/03c97ead-4d0a-465c-9e20-afa7ff6c044d)

Is there a reason why you've created our own checkmark icon instead of using the built in `CHECKMARK` that we already consistently use elsewhere?

**Comment by trhyder** [comment]
Thanks for the feedback and explanations.

> Work needs to be done to make it actually do something useful in a profile mode and create a true arc.
Maybe, rather than using the 3d cursor there should be an input for the radius?

> Is there a reason why you've created our own checkmark icon instead of using the built in CHECKMARK that we already consistently use elsewhere?
Because I am an idiot - I'll remove them

> This is needed, please don't remove it.
Thanks for your explanation - I will add this back into the UI, sorry about that.

**Comment by theoryshaw** [comment]
> Maybe, rather than using the 3d cursor there should be an input for the radius?

I like 3d cursor approach, because a lot of times you're drawing relative to something in the scene.  It would be somewhat painful to enter in the radius. imho.

**Comment by trhyder** [comment]
What confused me about the 3d cursor approach is that it moves one of the input points and breaks a path. I was thinking to produce a more expected outcome a radius input could solve this. The input could be by mouse click or keyboard. Also, a radius value would be necessary for making it an IfcArc, wouldn't it? It sounds like you use this more than me, so maybe you have a more insightful take?

**Comment by theoryshaw** [comment]
> What confused me about the 3d cursor approach is that it moves one of the input points and breaks a path. I was thinking to produce a more expected outcome a radius input could solve this. The input could be by mouse click or keyboard. Also, a radius value would be necessary for making it an IFC arc, wouldn't it? It sounds like you use this more than me, so maybe you have a more insightful take?

yes this sounds good to me.

**Comment by Moult** [comment]
Keep the text label. Icons are not as explanatory as people assume. Everything else agree. Agree with moving the name of the wall type to the front, and agree with making it a regular label and making the type manager button a separate button.

I'd hold off any work with the 2-point arc right now, it definitely needs work but it's quite a bit of effort and we can address it separately.

**Comment by Moult** [comment]
Closing as this is well underway.
