### ISSUE TITLE
`ifcopenshell` 0.7.9 missing `set_context_ids` on `ifcopenshell.geom.settings`

### ISSUE THREAD

**Issue by YaroslavKormushyn** [IfcOpenShell/IfcOpenShell#4970]
Migrating from `0.7.0` to `0.7.9`: has `ifcopenshell.geom.settings.set_context_ids` been deprecated?

**Comment by YaroslavKormushyn** [comment]
I haven't worked with CGAL yet, sounds interesting.
I got you, I'll wait until 0.8 is out, to reap all the benefits.
@aothms Do you plan on having a migration guide with a changelog of what's changing/getting better?

**Comment by aothms** [comment]
>  @aothms Do you plan on having a migration guide with a changelog of what's changing/getting better?

Yes we should do that. Also write a bit about the rationale and long term plans. For v0.8 we now have this intermediate layer so instead of `IFC` -> `OCCT` we have `IFC` -> `Taxonomy` -> `{CGAL, OCCT}`. This taxonomy speeds up geometry library implementation because it folds redundant and domain-specific defitions into well-understood principles, but is also hashable, serializable, so we run geometry interpretation in a separate process so that it is resilient against crashes or find geometrical elements that are duplicates when they are not modelled as such in IFC. And also, last but not least, it could be that IFC5 uses some rather different fundamental principles for serialization and schema, but we can still map those to our taxonomy so that we can immediately leverage our work on geometry libraries even in the context of IFC5.

If we communicate a bit better, maybe we can get more people on board on these initiatives, but all these things take up already so much time I don't really have that it's difficult to on top of that also spend time on writing things down.

**Comment by YaroslavKormushyn** [comment]
I like what you're doing with this library, so hopefully it all comes around nicely.
Thanks for the explanation, I'm closing this as a non-issue.

P.S.: Let's hope that this is not how new people will enter this library in the future :)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/11539004/eaf087f6-becf-4681-9e08-7ffc5325855b)
