### ISSUE TITLE
How to get * in IfcSIUnit and IfcGeometricRepresentationSubcontext instead of $?

### ISSUE THREAD

**Issue by RickBrice** [IfcOpenShell/IfcOpenShell#4998]
I'm not quite sure of the terminology in order to ask this question properly, but here is the gist of it. I created the FHWA_Bridge_Geometry_Alignment_Example.ifc file from the IfcAlignment.cpp example program and ran it through the validation service. Starting with VS 0.6.4, it no longer validates. See https://github.com/buildingSMART/validate/issues/77.

I've narrowed the problem and solution down to IfcSIUnit and IfcGeometricRepresentationSubcontext have '$' in fields where it should be '*'

Fails
~~~
#2=IFCSIUNIT($,.LENGTHUNIT.,.MILLI.,.METRE.);
#3=IFCSIUNIT($,.PLANEANGLEUNIT.,$,.RADIAN.);
#17=IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Axis','Model',$,$,$,$,#16,$,.MODEL_VIEW.,$);
~~~

Passes
~~~
#2=IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.);
#3=IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.);
#17=IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Axis','Model',*,*,*,*,#16,$,.MODEL_VIEW.,$);
~~~

Question 1 - what's the difference between '$' and '*'?

Question 2 - how do I get IFCOS to output '*' instead of '$' for these entities?

Maybe the internals on the C++ side need to be revised?

Ping @aothms @civilx64

**Comment by civilx64** [comment]
From the docs for [IfcSIUnit](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcSIUnit.htm) -

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/26513472/608fbfa3-abd9-427d-ae40-db76aee7f01d)

For Question 1 - `*` means that the exponents are automatically derived by a function.  `$` means that this attribute is blank which violates the schema because `Dimenstions` is a required attribute.

For Question 2 - TBH I have no idea how to make it happen in code, but I know how to make it happen with a text editor. :grinning:.  In other words I'd recommend creating a few basic IFC files to use as templates versus re-creating everything from scratch every time.  On the python side we have `ifcopenshell.template.create()` to handle this automagically - see [generate.py](https://github.com/buildingSMART/ifc-gherkin-rules/blob/main/test/files/pjs002/generate.py) for an example usage.

We use templates and seed files for our CAD and BIM platforms... why not do the same with IFCOS?  Every model is going to have units and a geometric representation context.  Might as well write it once and re-use it form there.

**Comment by RickBrice** [comment]
Templates are a good way to go in same cases.

On the C++ side there is an `IfcHierarchyHelper<>` class that does all the setup for units and representation context. It should work correctly without intervention. It now produces an IFC file that doesn't pass the validation service for the reasons discussed above. I would classify this as a bug.

@aothms point me in the right direction and I'll take a stab at fixing this. Though I suspect it's far more complicated that simply replacing `$` with `*` - The change needs to be made for "Formally derived attributes" which is likely coming from the express (EXP) file and changes are needed in the C++ code generator.

**Comment by RickBrice** [comment]
Fixed? See https://github.com/IfcOpenShell/IfcOpenShell/commit/585eeb283ace100c7f4e90be9f41c2013ba0b86b
