### ISSUE TITLE
Cannot get Placement

### ISSUE THREAD

**Issue by Channelal2001** [IfcOpenShell/IfcOpenShell#5007]
I'm trying to get de Placement attribute from my IfcSite, but it says it doesn't exist. I'm trying it with this line: direction = site[0].Placement.RelativePlacement.RefDirection.DirectionRatios. I looked at the ifc file and it's there. Do I have any error in my code?
By the way, if I don't treat the site as an array, I can't get any of its attributes

**Comment by Moult** [comment]
There is no such thing as a placement attribute. Where did you read that there was such an attribute?

See: https://docs.ifcopenshell.org/ifcopenshell-python/code_examples.html#get-the-xyz-coordinates-of-a-element

You probably are doing `site[0]` because you asked for a list of all sites (e.g. `by_type("IfcSite")`, so that sounds normal. If you haven't checked it out already I recommend reading https://docs.ifcopenshell.org/ifcopenshell-python/hello_world.html

**Comment by Channelal2001** [comment]
I want to get to the IfcLocalPlacement

**Comment by Channelal2001** [comment]
I need to get the IfcLocalPlacement

**Comment by Moult** [comment]
Please see the link in my previous comment. The attribute is called "ObjectPlacement", not "Placement". I'm interested to why you thought it was "Placement" - if it was our documentation, we should fix that mistake. Also, I highly recommend not navigating the placement manually as you are doing, because the placement may be relative or not a local placement at all. Using the utility functions takes care of this for you and returns a matrix.

**Comment by Channelal2001** [comment]
> Please see the link in my previous comment. The attribute is called "ObjectPlacement", not "Placement". I'm interested to why you thought it was "Placement" - if it was our documentation, we should fix that mistake. Also, I highly recommend not navigating the placement manually as you are doing, because the placement may be relative or not a local placement at all. Using the utility functions takes care of this for you and returns a matrix.

I'm using a tool called GeometryGym to see how the tree is done, but it seems to have some errors

**Comment by Moult** [comment]
Ping @geometrygym - any ideas?
