### ISSUE TITLE
Upgrade to the IFC4Add2 schema

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#503]

**Comment by SS-TT** [comment]
Hi there.
I'm not seeing any progress on this, is this issue being worked on?
I need to convert some IFC4x2 files but I can't with the current release.

**Comment by aothms** [comment]
IFC4Add2 is a small addendum to IFC4, it's not the same as IFC4X2, which includes infrastructure entities. Support for the IFC4X2 geometries is currently not planned, but might be if there is significant interest.

**Comment by hlg** [comment]
There is a minor issue with `IfcIndexedPolyCurve`, which was already introduced in IFC4Add1. I am leaving this issue here as a reminder to be addressed during the upgrade.

According to the standard, the `Segments` attribute of `IndexedPolyCurve` is optional, but currently it is treated as mandatory in IfcOpenShell, such that representation items without the attribute set will be ignored. Apparently there was an error in the [html documentation](http://www.buildingsmart-tech.org/ifc/IFC4/Add1/html/link/ifcindexedpolycurve.htm) of the entity type, omitting the ? in the attribute table. This documentation error has been fixed in subsequent IFC4 releases, but it really was only a typo. The Express specification for this entity type has not changed and the verbal documentation of semantics when `Segments` is omitted seems also unaltered.

Here is a test file, a modified version of the [IFC4 slab example](http://www.buildingsmart-tech.org/ifc/IFC4/Add1/html/link/slab-standard-case.htm) with segments removed: 
[IfcIndexedPolyCurve.ifc](https://github.com/IfcOpenShell/IfcOpenShell/files/2763119/IfcIndexedPolyCurve.ifc.txt).

**Comment by aothms** [comment]
> There is a minor issue with IfcIndexedPolyCurve, which was already introduced in IFC4Add1. I am leaving

Thanks. Great catch, I wasn't aware.

From the docs:

> In the case that the list of Segments is not provided, all points in the IfcCartesianPointList are connected by straight line segments in the order they appear in the IfcCartesianPointList.

Is this something you want to work on, since you already identified the issue? It's not really dependent on upgrading to Add2 am I right?

**Comment by hlg** [comment]
No, it is not dependent, just thought that it would be easy to solve along the way when upgrading.

I am not so much into C++ and don't have the development environment set up, but in case I find time before you do the upgrade, I will just extract this as a new issue and solve it separately. Do you have any plans for the Add2 upgrade?

**Comment by aothms** [comment]
> Do you have any plans for the Add2 upgrade?

Seems there is a Add2TC1 now as well. @rubendel just pointed me to that.

http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/

I will try to have the regenerated sources by Monday.
