### ISSUE TITLE
OCCT 7.7 Doughnut / snail in advanced brep bends

### ISSUE THREAD

**Issue by aothms** [IfcOpenShell/IfcOpenShell#5064]
Another issue I experienced in 7.7 are these fantastic doughnuts every time where was a bend.

I find that odd because I was expecting some sort of revolved area solid or something but these are advanced breps. No issue in 7.5.

![2023-08-11-134441_451x658_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/af6d876e-6817-4ae0-afb9-fbc6f6c198e7)
![2023-08-11-134143_581x515_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/f4af78d9-42bb-4fb2-9617-290fcdd66fee)
![2023-08-11-134037_838x506_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/d0da6f06-9802-4872-9454-e8ec54881b3c)

_Originally posted by @Moult in https://github.com/IfcOpenShell/IfcOpenShell/issues/3559#issuecomment-1676254722_

**Comment by Moult** [comment]
Is 7.7 now used by IfcOpenBot and now the "officially" supported OCC version? If so, there are a few places in the docs that need updating to mention that.

That also makes this snail bug as a higher priory instead of a curious artefact to something that turns up... well, almost everywhere at least in the models I work with day to day :)

Here's another sample file if it helps.

[racchair.ifc.txt](https://github.com/user-attachments/files/16429143/racchair.ifc.txt)

![2024-07-31-000003_385x520_scrot](https://github.com/user-attachments/assets/1620e2d9-f003-4afb-a1a7-8b2ff25bef04)

**Comment by aothms** [comment]
Ok, I studied this a bit further and got some sense of understanding the problem. These bends have base surfaces as revolutions over open profile defs. We us an OCCT api to construct the revolution and it is smart enough to convert this for us into a toroidal surface, but for some reason the orientation is reversed (either because it doesn't matter because the revolution occt creates is a valid topology in itself, or because we somehow overlook to apply some orientation). When we then apply the wire to the face, it is no longer consistent with the surface normal and OCCT is even kind enough to fix this for us, however the fix constitutes reversing the loop, not reversing the surface. Because the toroidal surface is periodic in both directions we get exactly the part on the surface we don't need. I don't know why this changed, either in the construction API or the fix API and my solution is also not really elegant, rather than supplying the correct data I detect the fix applied and then try again with the opposite surface orientation. But at least the artefacts should be eliminated so that we buy some time to look into the other problems we have.

**Comment by Moult** [comment]
Confirming this is fixed :)
