### ISSUE TITLE
 IFC File in IfcConvert works on Windows, but on Linux it kills the process

### ISSUE THREAD

**Issue by csritter** [IfcOpenShell/IfcOpenShell#5077]
Hi, this project converts fine in Windows, although the generated file size is much larger than IFC:
![image](https://github.com/user-attachments/assets/48cfd6b6-417c-4098-8853-8bb9f2425f09)

And here's the terminal on Linux shows for me:
![image](https://github.com/user-attachments/assets/612c226d-328f-4685-8359-3c8502a6e413)

I don't know how to debug in Linux, but I am sure @aothms can investigate that.

IfcConvert version 0.8.0, commit 8b29e50f11da2730a19d21327c22a257d0434c9e

I will send an email with the project.
I hope you don't mind.

**Comment by aothms** [comment]
`Killed` probably means out of memory which is corroborated maybe by the immense output file size. I'll have a look.

**Comment by Moult** [comment]
I noticed something weird, that on Blender if I enable multiprocessing it basically hangs / takes forever on `iterator.initialize()` whereas if I disable multiprocessing it goes ahead and does the job.

**Comment by csritter** [comment]
Interesting...
What I find strange is the amount of time to convert, and the time it takes to open in another viewer, I believe it took less than 1 minute.

**Comment by csritter** [comment]
Hi, I'm reviving this topic because I just tried to convert a file that was "killed" when I processed it with multithreading and processed normally when I didn't use it (but it took about 40 ~ 50 minutes).

Resuming:
```
IfcConvert issue_5077_2.ifc issue_5077_2.glb - work

IfcConvert -j 17 issue_5077_2.ifc issue_5077_2.glb - doesn't work
```

FYI: I only tested on Ubuntu, I didn't try on Windows.

IfcConvert version 0.8.0, commit 2ad601ed3459ff310d3ba48a0c2123e1aa72a431

I will send an email with the project (issue_5077_2.ifc).
I hope you don't mind.

**Comment by csritter** [comment]
@Moult, the file issue_5077_2.ifc works with cgal now and makes it in 4 minutes

the file issue_5077.ifc works too, but the file size is still huge, and it's because it has repeated objects.

Is there a way to detect if some object is repeated on serializer @aothms?

**Comment by aothms** [comment]
> Is there a way to detect if some object is repeated on serializer @aothms?

Well it depends on the exact mechanics. Only if the representation of a product consists of 1 mapped item, and both its transforms are identity matrices, then the 'iterator' will reuse the same mesh in serializations that support that (such as collada).

One possible improvement (especially now that we have this intermediate taxonomy layer in v0.8) is to move placements from the mapped item layer up to the product placement, and to potentially split multiple mapped items into distinct products, so that more geometry can be reused even if at the representation level there are placement differences.

This is also something you could do as a pre-processing step in IFC though using python.
