### ISSUE TITLE
GeomServer builds at s3.amazonaws.com

### ISSUE THREAD

**Issue by hlg** [IfcOpenShell/IfcOpenShell#5135]
It seems that the GeomServer builds that used to live at https://s3.amazonaws.com/ifcopenshell-builds have disappeared. Not just that there are no new builds published anymore, but also the older builds that had been there are gone. Commit 3bbdc3f ist the latest I have on record. I assume this distribution channel is still active, because there are rather recent IfcConvert builds (from June 2024). Would it be possible to bring back those builds? Or are there opposing plans or reasons?

**Comment by aothms** [comment]
We have a bit of a different versioning schema going on now.  That most likely explains it, because these builds are indeed still alive. The latest builds are a bit more experimental because we're building up to a first release candidate of 0.8 which has some architectural changes in geometry handling.

https://github.com/IfcOpenBot/IfcOpenShell/commit/d51fa2c5f77fa5494302a77f2f19b04fce4e9855#comments

https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.7.11-d51fa2c-linux64.zip

**Comment by hlg** [comment]
Ah, I see - sorry, my bad. I was just looking at the ListBucketResult xml that is served as index file. It seems to be truncated at 1000 entries and those 1000 first entries happen to be IfcConvert builds exclusively. The XML with the bucket content can be filtered with the "prefix" and paged through with the "marker" query parameter, e.g. https://s3.amazonaws.com/ifcopenshell-builds?prefix=IfcGeomServer-v0.7.11. Thank you for the clarification! Would you recommend to use the latest version as a default for the BIMserver plugin or is there some "last stable" version?

**Comment by aothms** [comment]
I would use the latest build for 0.7.0 as a default https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.7.0-c7830e9-linux64.zip

Once we bump to 0.8.0 things should be fairly stable (and you get support for ifc4.3 infra geometries) but still a little bit more experimental than 0.7.0

When we get to 0.8.1 (we plan to have a 2 month release cycle) there doesn't need to be any hesitation to update.
