### ISSUE TITLE
Opening subtractions failed on wall (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#516]
1. Convert [516--opening-subtractions-failed.ifc](https://github.com/IfcOpenShell/files/blob/master/516--opening-subtractions-failed.ifc) with 747ddeb
2. Experience error when converting, and that the output file contains no openings:

```
[Error] {2AD2sgUn19$xdaFQyyDdsq} Opening subtraction failed:
#58882=IfcWallStandardCase('2AD2sgUn19$xdaFQyyDdsq',#41,'Basic Wall:YV 01:1734076',$,'Basic Wall:YV 01:5596783',#58709,#58880,'1734076')
```
<img width="216" alt="screenshot 2018-12-07 at 15 07 48" src="https://user-images.githubusercontent.com/4601554/49652282-e6f5a580-fa31-11e8-9312-6b1c6fa6f660.png">

3. Expected geometry from Solibri:
<img width="216" alt="screenshot 2018-12-07 at 15 14 39" src="https://user-images.githubusercontent.com/4601554/49652617-d98ceb00-fa32-11e8-9c0e-260bff34d548.png">

**Comment by aothms** [comment]
IfcOpenShell does a manifoldness check after the boolean operation and that failed due to a shared edge between two shells. So now manifoldness is checked on a per-shell basis.


See three of the four faces connected to this edge:

![afbeelding](https://user-images.githubusercontent.com/1096535/49684479-caf71000-fad4-11e8-8062-851e2fc65cf8.png)
