### ISSUE TITLE
Default Project template startup

### ISSUE THREAD

**Issue by R2naizr** [IfcOpenShell/IfcOpenShell#5202]
Should the default template be based on IFC4 or IFC4X3

currently the default is IFC4
![image](https://github.com/user-attachments/assets/c842e7b1-26f6-4c79-93b0-a25a6389b3ac)
![image](https://github.com/user-attachments/assets/83216e16-f509-44e3-bb1c-f7149625d4ce)

I'm not sure if IFC4 should be the template base for new projects, but I've created a library with the IFC4X3 schema and when creating a new project using the Bonsai template in the File tab, I get defaulted to the IFC4 schema (I know that I can use the "Project info" tab to specify the schema for new projects, but I am specifically talking about the default templates), so when I try to import the IFC4X3 library there doesn't seem to be any interoperability from IFC4 in importing IFC4X3 (which I assume, would mean, me having to manually change the ifc file in the text editor prior to importing).

Thanks

**Comment by Moult** [comment]
This is by design. The project wizard as you've seen allows you to customise the schema and so on, but for the basic menu settings, Bonsai defaults to IFC4. This is intentional because IFC2X3 is too old and missing many good features, IFC4X3 is too new and not yet extensively supported, so for the time being IFC4 is still the recommended default.

Project libraries are not compatible across versions and need to be explicitly upgraded or downgraded.
