### ISSUE TITLE
underlay link broken with web UI

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5219]
![image](https://github.com/user-attachments/assets/cd8982cf-3da2-466d-b746-fc71015fc325)

files if you need them: https://hub.openingdesign.com/OpeningDesign/Highland_Haven/src/commit/476edaceea65e35165a82578d0896189776a15c9/Open/Models_and_CAD/BlenderBIM

Highland_Haven.ifc

**Comment by Ziad-I** [comment]
@theoryshaw Ah, okay. Thanks!
this is happening because the web UI is expecting the whole sheet/drawing SVG so when there are external links with the xlink:href it tries to request but will not resolve due to how the server is set up

One solution I am currently trying out is to ensure all external links are encoded in the SVG before sending it to the web UI for display. However, this requires the external files to be in a known directory, such as the same directory as the sheet/drawing itself.
