### ISSUE TITLE
Visibility of whole-part structures in an object (in this case BIPV)

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#5230]
As part of a project on building-integrated photovoltaics (BIM4BIPV), I am currently investigating the possibility of modelling the arrangement and interconnection of PV cells in IFC in such a way that it is possible to identify cells that are so shaded by surrounding elements that they no longer generate electricity.
From my point of view, the PV module in IFC must be structured in such a way that when evaluating the model, it is possible to recognise in which circle of which module at which spatial position in the georeferenced model a PV cell is contained that is temporarily shaded during the course of the day and thus ‘deactivates’ the entire circle of this module.

With the flattening of the structure in the Blender outliner, much of this IFC structuring is no longer as visible as it was before the flattening.

Am I missing something and is it visible in a different way in BonsaiBIM?

To make it easier to understand, I have added the IFC used, a screenshot from BonsaiBIM and a screenshot from BIMcollab.

[Concept of SinglePvModule with parts.ifc.txt](https://github.com/user-attachments/files/16759610/Concept.of.SinglePvModule.with.parts.ifc.txt)

![Screenshot 2024-08-27 at 09 16 27](https://github.com/user-attachments/assets/36d03403-b12a-4176-8515-a9bc51f150ea)
![Screenshot 2024-08-27 at 09 24 27](https://github.com/user-attachments/assets/efa0a76d-b672-4f60-bac9-dbc2c5cc8f51)

**Comment by Moult** [comment]
This is one of the really nice things about the new spatial decomposition panel. Because we're no longer coupled to the outliner or Blender's collection hierarchy, we can on the fly change between hierarchies strategies.

You can now change between the current default of a 3 level breakdown (Class > Type > Occurrence) to the previous default (decomposition, including containment, aggregation, nesting, etc). It's really quick and easy to build :)
