### ISSUE TITLE
Geometry loaded without a style (profile / layer sets)

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5238]
An external styles doesn't seem to be coming through. 

That beam, should take on the 'corten' style

4.2.1 Bonsai vo.7.l I-alpha240828-99e67d5

files: 
[20240613 - printing materials.zip](https://github.com/user-attachments/files/16784146/20240613.-.printing.materials.zip)

![image](https://github.com/user-attachments/assets/5878f664-0e2d-4423-9838-c59403cb59d6)

**Comment by theoryshaw** [comment]
These troubleshooting file, is probably a better test...

[20240828 - external styles.zip](https://github.com/user-attachments/files/16791216/20240828.-.external.styles.zip)

![2024-08-28_21-44-51_blender_(Unsaved)_-_Blender_4 2 1_LTSblender](https://github.com/user-attachments/assets/850fccdc-386a-4da6-ad54-4faf81847d34)

**Comment by Andrej730** [comment]
The issues are unrelated to the external styles, they are generales styles issues.

> files: [20240613 - printing materials.zip](https://github.com/user-attachments/files/16784146/20240613.-.printing.materials.zip)

This one seems to be resovled in https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/bonsai-0.7.11-alpha240829. I guess it was some issue with inherited profile set usages in the previous build.

> 20240828 - external styles.zip

This one doesn't work as it's IfcMaterialLayerSet with multiple layers and since we don't have a proper multilayer geometry we can't correctly represent the assigned styles.

We can just use 'layerset-first' geometry setting so it would use the style from the first layer - it still will be confusing but I guess it could be better than nothing. What do you think? @theoryshaw @Moult

**Comment by Moult** [comment]
Happy to use the first layer style for now which matches the convention we have in place already.

**Comment by theoryshaw** [comment]
Agreed :)
