### ISSUE TITLE
Error when adding IFC object after deleting multiple objects by box selection mode

### ISSUE THREAD

**Issue by manuvarkey** [IfcOpenShell/IfcOpenShell#5318]
On adding an IFC object after deleting multiple objects by box selection mode, error is shown.

Steps to reproduce

1. Open new ifc project.
2. Select wall tool.
3. Create new type.
4. Add two walls at same location.
5. Select both walls by box selection.
6. Delete objects by pressing `Delete` / `X`.
7. Add another wall.

On step 7, following error is shown.

```
Python: Traceback (most recent call last):
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/product.py", line 161, in _execute
    if self.generate_layered_element(ifc_class, relating_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/product.py", line 293, in generate_layered_element
    obj = wall.DumbWallGenerator(relating_type).generate()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 703, in generate
    return self.derive_from_cursor()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 849, in derive_from_cursor
    return self.create_wall()
           ^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 864, in create_wall
    element = bonsai.core.root.assign_class(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/core/root.py", line 94, in assign_class
    collector.assign(obj)
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/collector.py", line 94, in assign
    collection = cls._create_project_child_collection("Unsorted")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/collector.py", line 103, in _create_project_child_collection
    project_obj = tool.Ifc.get_object(tool.Ifc.get().by_type("IfcProject")[0])
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```

Screencast:

[Screencast from 05-09-24 03:10:53 PM IST.webm](https://github.com/user-attachments/assets/40fc6867-3d95-41d3-90e2-15b6f3ca7d34)

**Comment by Gorgious56** [comment]
You inadvertently also deleted The IfcProject, IfcSite, IfcBuilding and IfcBuildingStorey empties from the project. Notice the outliner on the left of the screen empties after you deleted the walls.

**Comment by manuvarkey** [comment]
> You inadvertently also deleted The IfcProject, IfcSite, IfcBuilding and IfcBuildingStorey empties from the project. Notice the outliner on the left of the screen empties after you deleted the walls.

Damn... You are right. I think now that the outliner is here these objects can not be made non-selectable by default such that such mistakes can be avoided.

**Comment by Gorgious56** [comment]
It was indeed the default behaviour in previous versions, for precisely that reason if I'm not mistaken. :)

**Comment by manuvarkey** [comment]
@Moult after https://github.com/IfcOpenShell/IfcOpenShell/commit/a4396ee76644e03018d3755bea86f6f50861813a , the room space elements are not deletable from workspace. Is this intended ?

Sometimes it is difficult to locate the room space elements from the spatial decomposition editor. Selecting and deleting from workspace is simpler.

**Comment by manuvarkey** [comment]
@Moult Please ignore previous comment. Found the lock button.

**Comment by Moult** [comment]
@manuvarkey yes, this is intended. The logic is that there are:

1. Some elements that should never be deleted / copied. Such as IfcProject.
2. Some elements that are rarely or sometimes deleted / copied / edited. Such as spatial elements, grid elements, or in IFC4X3 positional elements. These are mostly locked, except for periods of time when you want to explicitly edit them.
3. Elements which you always want to edit. These are all your physical products. Walls, doors, slabs, etc.

Previously, we had some inconsistency where grids were locked on project load, but not on creation. Similarly, users would accidentally copy the site. We had the selection disabled in the past, but that was not a complete solution, since users now found it difficult to select basic things, also you could delete the collection of the thing in the outliner and leave your model in a broken state.

So the new concept is that these "rarely edited" things are locked in that you can select them, but not copy, edit, delete, unless you explicitly unlock them. Kinda like pinned elements perhaps in Revit.
