### ISSUE TITLE
Show the wall preview while using polyline tool

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#5324]

**Comment by Moult** [comment]
Btw we have a 2d offset function already implemented in the cad tool you can reuse

**Comment by brunoperdigao** [comment]
This has been implemented in the recent commits. I'm gonna leave this open until we have more users testing it.

**Comment by brunoperdigao** [comment]
![Image](https://github.com/user-attachments/assets/09715119-6099-4e85-948c-efd691229109)

**Comment by Gorgious56** [comment]
Hello, I just tested it a bit. I have to say it feels very good, the interface is very clear and looks professionnal. Congrats and thank you. My constructive criticism :

- I like the blue color for the base polyline, it blends well with the vanilla selected item color in the menus. 
- I use the default dark theme but I think the white wall ghosts being hard to see on white themes.

I have other feedback, IDK if you'd rather I open a new issue to post them ?
- I just suffered an error when validating this monstrosity, and now the tool is stuck.
![image](https://github.com/user-attachments/assets/951ed70d-06b8-4442-8e29-c35587b9df3f)
```
Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\model\decorator.py", line 518, in draw_snap_point
    self.draw_batch("LINES", verts, decorator_color_object_active, edges)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'edges' where it is not associated with a value
```
I think i clicked twice at the same spot, maybe add a clause to make sure two points are further than x distance to create a wall ?
- I would very much like the polyline tool to appear as an icon in the Tool shelf, maybe there 
![image](https://github.com/user-attachments/assets/8c5e19ea-92c1-486f-adb0-47982a1904e3)
Blender is known for its many, many shortcuts and SHIFT + P needs to either use 2 hands or awkardly bend the left hand which disrupts the workflow, so I think a button would be a good compromise.
- Would be nice to show the units in the interface  
![image](https://github.com/user-attachments/assets/a3542e36-9095-4243-96c9-d26ffc957bb2)
- Using tab to switch between the different inputs and assign the angle or X, Y position felt very intuitive.
- It would be nice to CTRL-Z to remove the last placed point
- Usually in Blender right-clicking cancels the operation, here it validates the wall. Matter of preference I guess but it felt surprising.
- Left clicking (instead of hitting RETURN) after inputting a value blocks the cursor at the last position

**Comment by Moult** [comment]
> Blender is known for its many, many shortcuts and SHIFT + P needs to either use 2 hands

It was only meant to be a temporary shortcut. I think the time is right to make this now the default behaviour of Shift-A for all vertically layered types!

> It would be nice to CTRL-Z to remove the last placed point

Backspace - this is noted in the status bar.

**Comment by Gorgious56** [comment]
Oh man all these years using Blender daily and I didn't think to look at the status bar ! Thank you. Glad to see making it default is on the roadmap.

Cheers

**Comment by Moult** [comment]
I like Ctrl-Z too so long as Blender doesn't catch the signal.

**Comment by brunoperdigao** [comment]
@Gorgious56 Thanks for the feedback, I really appreciate it. I'll check the errors that you mentioned and I generally agree with all you remarks. I'll put them on my to do list. About the right click, I guess this is one of the things that we have to decide if we follow Blender guidelines or if we mimic the behavior of other BIM software that users might be used to. Personally I prefer the way Blender works, but I don't really have a strong opinion about this.

**Comment by Moult** [comment]
What's the right click issue?

**Comment by brunoperdigao** [comment]
> Usually in Blender right-clicking cancels the operation, here it validates the wall. Matter of preference I guess but it felt surprising.

I implemented right click as "confirm" instead of "cancel" following the first feedback that I got from users.

**Comment by Moult** [comment]
Hmm, I like the ability to draw walls without having to move my hand from the mouse (e.g. to press the Enter key). But yeah it isn't consistent with Blender's usual behaviour. I think the benefit outweights the cons right now.

**Comment by Plae-Blue-Dot** [comment]
Excellent Tool and preview Bruno!

Just a query around kinda language of previewed geometry, the only other tool that previews like this as far as I know is the roof modifier and it uses Blue as the preview geometry, green as currently selected and grey as not selected:
![image](https://github.com/user-attachments/assets/71c89daa-c132-41a9-a388-c8e7733bd315)

I don't have too much of a preference here, but I think the blue with a transparency works very well as a preview. I do think that these previews should match somewhat if possible, similar behaviour having a similar visual indication is always great.

Your wall tool currently uses white to mark selected, blue for deselected axis and white only outline for the geometry preview:
![image](https://github.com/user-attachments/assets/a37c1673-fbd8-428d-94f8-9cf2c6fb7db9)

As a third example when editing a beam Axis for instance the axis:
![image](https://github.com/user-attachments/assets/56eaa551-9dd0-43a3-b71a-99aa0a18bbca)
It also uses green for currently selected:
![image](https://github.com/user-attachments/assets/2ad452e3-9410-46cf-aabb-ce74f7e4dc01)

I think this is another example of something that could have a geometry preview in the future, so these 3 should be visually similar if possible.

**Comment by Moult** [comment]
Currently we have a number of colours in the add-on preferences that I've been trying to use consistently across all of these decorators.

 - White: drawing annotations colour - this is historic, back in the day there was a colour you could configure for all annotations (e.g. dimensions). It is not used outside of that context.
 - White: an unselected generic, decorated thing that you can interact with directly
 - Green: a selected, generic decorated thing that you are now directly interacting with
 - Blue: a "special" element, typically something that is not a real object, it is derived, or generated based on other data (e.g. true arcs, circles, parametric roofs, etc)
 - Red: something with an error or warning state
 - Dark grey: a generic element that should be muted because it is purely a temporary helper or construction line, etc.

Notably missing is Black: the hardcoded colour when a drawing cuts an object.

As you can see there are attempts at a consistent logic, but the definitions are still a bit murky and evolving :) With those current definitions, I guess the wall polyline should be white (not grey, because it actually will represent the wall axis geometry) except for the last segment which is green, and the wall preview should be blue.

**Comment by brunoperdigao** [comment]
I have updated the colors, but the decorator doesn't have the tris yet. It's a bit tricky and I'm still trying to figure out the best way to implement it.

**Comment by Moult** [comment]
Wouldn't you take the footprint, use bmesh to extrude it up, and feed the tris of that bmesh? If it helps you can see geometry/decorator.py as an example

**Comment by brunoperdigao** [comment]
I'm not sure if I was over complicating things, but the tricky part was to make sure it worked for sloped walls. But I finally implemented this in the latest commit.
