### ISSUE TITLE
Object has voids applied to it in 0.7.0, but not in 0.8.0

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5329]
file: https://hub.openingdesign.com/OpeningDesign/Rae_Living_Room_Ext/src/commit/27f77a183c34547ba73cbe72feccdb4c4833b8d3/Open/Models/BlenderBIM/Rae_Living_Room_Ext.ifc

The following object has voids applied to it in 0.7.0, but not in 0.8.0
`0jV0Rc_5T7J90nsnl1ZvUN`

https://github.com/user-attachments/assets/b1bccd3d-3093-43b5-8f3f-5dab5e43fd09

![2024-09-05_10-46-27_blender_Rae_Living_Room_Ext_ DDropboxGitea_ODRae_Living_Rblender](https://github.com/user-attachments/assets/8a624ed4-ee75-4512-81e7-2390a65876d9)

**Comment by theoryshaw** [comment]
might be related to: https://github.com/IfcOpenShell/IfcOpenShell/issues/5267

**Comment by theoryshaw** [comment]
converting this object with `bim.update_representation(ifc_representation_class="IfcTessellatedFaceSet")` doesn't seem to work either. Not sure if that's related, or not.

**Comment by aothms** [comment]
There is an invalid placement again, but that's not related I think


```
#2890502=IFCAXIS2PLACEMENT3D($,$,$);
          |
          v
#2890502=IFCAXIS2PLACEMENT3D(#289050200,$,$);
#289050200=IFCCARTESIANPOINT((0.,0.,0.));
```

The issue is indeed the same as #5267: usage of profile with voids where probably composite profile was intended:

If I change:

```
#3454469=IFCARBITRARYPROFILEDEFWITHVOIDS(.AREA.,$,#3454471,(#3454472,#3454473,#3454474,#3454475));
```

to

```
#3454469=IFCCOMPOSITEPROFILEDEF(.AREA.,$,(#345447100,#345447200,#345447300,#345447400,#345447500), $);
#345447100=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,$,#3454471);
#345447200=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,$,#3454472);
#345447300=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,$,#3454473);
#345447400=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,$,#3454474);
#345447500=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,$,#3454475);
```

it renders successfully. 

![afbeelding](https://github.com/user-attachments/assets/05d2806b-d8a9-46c7-bc70-eefee43c37ef)

Probably there is an automatic shapefix somewhere in the v0.7 face handling that got accidentally bypassed, but I think these underlying issues in the model definitely need  to be addressed at the source.
