### ISSUE TITLE
Regression in v0.6.0 – segfault on shelf (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#534]
1. Convert [534--shelf--segfault--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/534--shelf--segfault--augmented.ifc) with 9048ce4 (v.0.5.0)
2. Experience that the file converts successfully:
<img width="145" alt="screenshot 2019-01-05 at 12 48 14" src="https://user-images.githubusercontent.com/4601554/50724121-64234180-10e8-11e9-8f22-319e0625bed0.png">

3. Convert the same file with f24944b (v.0.6.0), and experience that the file now segfaults:
```FATAL: An error occurred, status code 139.```

**Comment by aothms** [comment]
Thanks for a new batch of files. However, on Travis this file and others succeed and locally on my system as well:

https://travis-ci.org/IfcOpenShell/IfcOpenShell/builds/475683204#L1603

What's going on here, any idea what can explain these differences?

**Comment by johanrd** [comment]
Hmm, indeed – I don't get the segfaults when building locally on a mac. However when building in docker i do get them. Let me have a look if i can make some more clear steps to reproduce, or find a workaround.

**Comment by hypirion** [comment]
I tried this on Debian Stretch through this Dockerfile:

```
FROM debian:stretch

ENV IFCOPENSHELL_REPO "https://github.com/IfcOpenShell/IfcOpenShell"
ENV IFCOPENSHELL_VSN "f24944be4854c2feac0d0d26f63e29ed8286319c"

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y curl git gcc g++ autoconf bison bzip2 \
                     libfreetype6-dev mesa-common-dev patch python build-essential && \
  git clone "${IFCOPENSHELL_REPO}" IfcOpenShell && \
  cd IfcOpenShell && git checkout "${IFCOPENSHELL_VSN}" && \
  cd nix && python build-all.py IfcConvert && \
  mv ../build/Linux/x86_64/install/ifcopenshell/bin/IfcConvert /bin/IfcConvert && \
  cd ../.. && rm -rf IfcOpenShell

COPY 534--shelf--segfault.ifc /534--shelf--segfault.ifc
RUN IfcConvert /534--shelf--segfault.ifc
```

And this segfaults. I will see if the same happens on Ubuntu.

**Comment by aothms** [comment]
Thanks @hypirion I'll do the same but run a debug build (`BUILD_CFG=Debug python build-all.py IfcConvert`) and look at the stack trace.

**Comment by hypirion** [comment]
Hmm... This also crashes on Ubuntu (just change the top line to `FROM ubuntu:18.04`), but only with build config set to RelWithDeb/Release, not when it's set to `Debug`.

**Comment by aothms** [comment]
Ok, turns out this is completely unrelated to geometry handling. Your test cases are special in the sense that they don't include the normal IFC hierarchy. The condition to check for this when finding the parent node was wrong

------------

Actually, if anything, I would expect this to fail **without** compiler optimizations because with optimization I had hoped this casting function to be completely inlined and not an actual function call.

For the ones interested.

Traceback:

~~~
Ifc2x3::IfcObjectDefinition* IfcUtil::IfcBaseClass::as<Ifc2x3::IfcObjectDefinition>() (IfcBaseClass.h:63)
IfcGeom::BRepElement<double, double>* IfcGeom::KernelIfc2x3::create_brep_for_representation_and_product<double, double>(IfcGeom::IteratorSettings const&, Ifc2x3::IfcRepresentation*, Ifc2x3::IfcProduct*) (IfcGeomFunctions.cpp:1533)
IfcGeom::IteratorImplementation_Ifc2x3<double, double>::create_shape_model_for_next_entity() (IfcGeomIteratorImplementation.h:479)
IfcGeom::IteratorImplementation_Ifc2x3<double, double>::create() (IfcGeomIteratorImplementation.h:659)
IfcGeom::IteratorImplementation_Ifc2x3<double, double>::initialize() (IfcGeomIteratorImplementation.h:285)
initialize (IfcGeomIterator.h:102)
main (IfcConvert.cpp:656)
~~~

Updated Dockerfile to prove the commit indeed fixes this issue:
~~~
FROM debian:stretch

ENV IFCOPENSHELL_REPO "https://github.com/IfcOpenShell/IfcOpenShell"
ENV IFCOPENSHELL_VSN "f24944be4854c2feac0d0d26f63e29ed8286319c"

RUN apt-get update && apt-get upgrade -y && apt-get install -y curl git gcc g++ autoconf bison bzip2 libfreetype6-dev mesa-common-dev patch python build-essential
RUN git clone "${IFCOPENSHELL_REPO}" IfcOpenShell && cd IfcOpenShell && git checkout "${IFCOPENSHELL_VSN}"
WORKDIR IfcOpenShell/nix
RUN python build-all.py IfcConvert
RUN mv /IfcOpenShell/build/Linux/x86_64/install/ifcopenshell/bin/IfcConvert /bin/IfcConvert

COPY 534--shelf--segfault.ifc /534--shelf--segfault.ifc

RUN apt-get update && apt-get install -y valgrind
RUN valgrind -v IfcConvert /534--shelf--segfault.ifc || true

WORKDIR /IfcOpenShell/build/Linux/x86_64/build/ifcopenshell/executables
RUN git checkout v0.6.0 && git pull
RUN make install

RUN mv /IfcOpenShell/build/Linux/x86_64/install/ifcopenshell/bin/IfcConvert /bin/IfcConvert

RUN IfcConvert /534--shelf--segfault.ifc
~~~

**Comment by johanrd** [comment]
Nice find! 

(Closing, as this seems to be fixed by 16cafb9 🎉)

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
