### ISSUE TITLE
IFC to Max, improvments

### ISSUE THREAD

**Issue by SEROOLOF** [IfcOpenShell/IfcOpenShell#54]
Hi,

I am using the 3d Studio Max importer  extensively and overall it works well but I would like to suggest some improvments:
-        Read in “Bim” data with the ifc, a settings files that controls which data to be read.
-        Create layers based on the different buildings and levels in the IFC file, (nested layers)
-        Support for "Separating elements by their material layers", by using material id´s or groups.
-        Support for instancing of objects instead of copies.

Some problems I have:
-        Some entities doesn’t import.
-        Some entities make max stop at import.

I can provide ifc files that has the problems.

Thanks,
Roger

**Comment by Stinkfist0** [comment]
Are you using the plugin download from the web page? There has probably been quite a lot of improvements since it was published. Have you tried IfcConvert (build from the latest code) for the IFC files that does not import fully?

I'm not a 3ds Max user really, but I think also that some kind of import setting configuration dialog would be nice too.

**Comment by SEROOLOF** [comment]
Hi,

Thanks for your reply.

Yes I am using the ones from the webpage, I have tried both versions.

I have tried ifcconvert but I gaven't been able to make it run. How should I write if I want to translate test.ifc to a obj file?

H?lsningar,
Roger

24 mars 2016 kl. 09:31 skrev Ali K?m?r?inen <notifications@github.com<mailto:notifications@github.com>>:


Are you using the plugin download from the web page? There has probably been quite a lot of improvements since it was published. Have you tried IfcConvert (build from the latest code) for the IFC files that does not import fully?

I'm not a 3ds Max user really, but I think also that some kind of import setting configuration dialog would be nice too.

-

**Comment by aothms** [comment]
I agree that the suggested improvements are all valid, but I don't think the 3ds max importer will be the best platform for this. IfcOpenShell focusses on providing a stable software library with other software developers as its target audience. From that point of view building user interfaces for authoring applications is not our main interest.

Issues with the conversion of IFC files should be resolved. I second the suggestion above and try to familiarize your self with IfcConvert, as it is always the most up to date and has a variety of options. I think especially the conversion to Collada (.dae) can be seamlessly imported in 3ds max. As mentioned, a lot of developments have happened since the last release and it would be good to test the files on the latest development version. Compiling IfcOpenShell is not difficult with the automatic build scripts (https://github.com/IfcOpenShell/IfcOpenShell/tree/master/win). But you can also upload or email the IFC files and I will send you back the Collada files to check.

You can run IfcConvert easily from the command line:

    \path\to\IfcConvert.exe \path\to\input.ifc

for example:

    C:\Downloads\Applications\IfcOpenShell\IfcConvert.exe C:\Downloads\test.ifc

if you want a collada file:

    C:\Downloads\Applications\IfcOpenShell\IfcConvert.exe C:\Downloads\test.ifc C:\Downloads\test.dae
