### ISSUE TITLE
Switching to Edit Mode takes very long with 

### ISSUE THREAD

**Issue by abel-NEY** [IfcOpenShell/IfcOpenShell#5416]
On a somewhat heavy file containing an object with nearly two million faces, switching to Edit Mode in Blender takes hours when Bonsai is installed. After saving the file as .blend and reopening it without Bonsai installed, the same action takes less than ten seconds.

**Comment by Gorgious56** [comment]
I don't think it's only a problem with edit mode, I'm sure you'll notice severe performance problems when you try to save the file. Is this a 3D scanned asset or something that was converted from a CAD file ? You can either try to remesh it to a lower polygon count and use that as a proxy or somehow link the mesh to the ifc in an external file. I'm not sure the ifc file format is suited for these very heavy mesh based representations.

**Comment by abel-NEY** [comment]
The file is a bridge with quite a bit of detail, modelled relatively cleanly in some unspecified CAD software and saved as an IFC into pretty much one single large mesh. I think it would be good practice to split the bridge into multiple objects, but the model is provided by an external party and we have no control over their workflow. Therefore, I'm splitting it myself.

For large infrastructure projects in the European countries where we operate, IFC has pretty much become the file format of choice for communication between project partners. The file in question is admittedly large (around 100 MB), but by no means the largest I have encountered.

Without Bonsai, Blender has no trouble dealing with the geometry. I can live with opening and saving taking some extra time, but switching to edit mode literally takes more than 1000 times longer than expected, that's why I'm reporting this specific issue.

**Comment by theoryshaw** [comment]
Hire that company to split it up for you. :)

**Comment by aothms** [comment]
I think one of the powers of Bonsai is also the scriptability of it. Because it's data model **is** IFC, you have full programmatic access to every instance of data in the model. If this representation consists of multiple distinct topological components it's a couple lines of python to isolate these into new objects (depending on the exact circumstances). That way Bonsai does not have to do its internal verification to see whether you as a user made changes in and out of edit mode.

If this is a 4.3 model with infrastructure 'sweeps' over alignment curves it could also be that we don't really have the parametric interface yet in which case you'd be editing an explicit mesh created from an intelligent parametric object.

**Comment by aothms** [comment]
See below for my script as 'promised'.

The element in question has a representation of four items, but the first item is huge (nearly 2 million triangles) and if you look at the topological components within it, it turns out there is over 30k of them. These are 'easily' isolated into new products.

```
>>> import ifcopenshell
>>> f = ifcopenshell.open(filename)
>>> elem = f['11tQGS4JfECwGczO3ehGH$']
>>> repr = elem.Representation.Representations[0]
>>> [len(tri.CoordIndex) for tri in repr.Items]
[1741371, 44467, 2368, 648]
>>> faceset = repr.Items[0]
>>>
>>> triangles = faceset.CoordIndex
>>>
>>> import networkx as nx
>>> g= nx.Graph()
>>> for i, tri in enumerate(triangles):
...   for j in range(3):
...     g.add_edge(('t', i), ('v', tri[j]))
...
>>> len(list(nx.connected_components(g)))
30588
>>> new_objects = []
>>> for comp in nx.connected_components(g):
...     selected = [c[1] for c in comp if c[0] == 't']
...     new_objects.append(f.createIfcbuildingelementproxy(
...         ifcopenshell.guid.new(),
...         elem.OwnerHistory,
...         f"{elem.Name or ''}:part{i}",
...         None,
...         None,
...         elem.ObjectPlacement,
...         f.createIfcproductdefinitionshape(
...             Representations=[f.createIfcshaperepresentation(
...                 repr.ContextOfItems,
...                 'Body',
...                 'Tessellation',
...                 [f.createIfctriangulatedfaceset(
...                     Coordinates=faceset.Coordinates,
...                     Normals=faceset.Normals,
...                     Closed=faceset.Closed,
...                     CoordIndex=[triangles[i] for i in selected]
...                 )]
...             )]
...         )
...     ))
...
>>> elem.ContainedInStructure[0].RelatedElements += tuple(new_objects)
>>>
>>> repr.Items = repr.Items[1:]
>>>
>>> f.write('splitted-model.ifc')
```

Naturally the utility of a model like this is quite limited, but looking at the style of the bridge, it's probably not something modelled recently, so you're excused ;)

**Comment by Moult** [comment]
I'm looking into the edit mode issue, because I think we shouldn't have this problem and also we're currently rebuilding the way editing works.

However loading the model with the default OpenCASCADE is almost guaranteed to be super slow. If you go into advanced mode when loading and change the geometry library to CGAL, it speeds up to 50 seconds to load the model. If you change the geometry library to CGAL-Simple or the CGAL/OCC hybrid (equivalent in this case) it loads in 13 seconds. Nice!

I'd love to see these performance improvements materialise in this release cycle.

**Comment by Moult** [comment]
I think this is now resolved, except that CGAL-Hybrid is not yet the default (some bugs still stopping it). But when it soon becomes the default, the edit mode switch should be as fast as it takes to load that mesh - so slower than vanilla Blender, but not forever. In this case on my machine 13 seconds - the additional reason is that it's a bit more complex than just "toggle edit mode" - we have to load individual items.

**Comment by aothms** [comment]
I can imagine that script I hacked together could also evolve into a full fledged IfcPatch recipe. So that it becomes generally available to these kind of workflows.
