### ISSUE TITLE
IfcConvert to XML silently failed

### ISSUE THREAD

**Issue by Babuh** [IfcOpenShell/IfcOpenShell#544]
Some files I'm trying to convert from IFC to XML are failing (no output file) but doesn't print any error as well.

Output example : 
`$ "../3rdParties/IfcConvert/win64/IfcConvert.exe" "../models/basic.ifc" "../models/basic.xml"
IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev
Scanning file...
Done scanning file
Writing XML output...
`

An IFC example is attached, I got this problem multiple times while testing many IFC files (failing ratio is about 1/20 files)

Thanks !
[basic.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/2837180/basic.zip)

**Comment by Stinkfist0** [comment]
Using the latest code there seems to be a pretty clear error message:
```
>IfcConvert.exe basic.ifc basic.xml
IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev (OCC 7.2.0)
Scanning file...
Done scanning file
Parsing input file took 1 second
Writing XML output...
Done! Conversion took 1 second

Log:
[Error] Failed to get ifc file header file_name name, error: 'Token $ at 129 invalid string'
[Error] Failed to get ifc file header file_name authorization, error: 'Token $ at 333 invalid string'
```

**Comment by Babuh** [comment]
I'm using the latest release from 16 Mar 2017

**Comment by aothms** [comment]
Unfortunately, latest release is for many open source projects not a guarantee to have an up to date version.

Please try the latest "unofficial" builds:

0.5 branch:
https://github.com/IfcOpenBot/IfcOpenShell/commit/161deeb4e057279cf80645fe1a6cd88cf911fe49#commitcomment-31768103

0.6 branch:
https://github.com/IfcOpenBot/IfcOpenShell/commit/4380e1d86ab9e5745ccea612aca7d369145e899e#commitcomment-31769117

0.6 has support for multiple schemas form the same binary.


Indeed, catching these errors in parsing the header has been added later. You'll get a error message now instead of a hard exit.

**Comment by Babuh** [comment]
It's working fine with this build ! 
I didn't see this feature,
Thank you !
