### ISSUE TITLE
The mirror and align functions go away after selecting two things

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5440]
The mirror and align functions go away after selecting two things...

I think it breaks right [here](https://github.com/IfcOpenShell/IfcOpenShell/blame/9ea44f0a891c91df4b0269e0f5c132380771b266/src/bonsai/bonsai/bim/module/model/workspace.py#L701C15-L701C15)--but i couldn't figure it out from there.

https://github.com/user-attachments/assets/a8b5e0d0-18c8-4f49-975d-e7f56ed683af

**Comment by theoryshaw** [comment]
@trhyder  This might be related to your icon work, which is awesome btw.

**Comment by trhyder** [comment]
This was my fault. When two walls are selected the UI is trying to draw an "Apply Void" button. The operator is looking for an icon that is missing from the repo. I found it difficult to track changes to png files as the repo appears to automatically omit them, so I missed this one because it was working locally on my computer.

I've created a PR for the missing png files. This is a temporary fix as I didn't have time to figure out how to only show the "apply voids" when only a voidable object and a void are selected.
