### ISSUE TITLE
No SVG version of Bonsai logo available?

### ISSUE THREAD

**Issue by sboddy** [IfcOpenShell/IfcOpenShell#5518]
I've tried to find an SVG version of the Bonsai "B" logo so I can add it as a dedicated desktop icon. As far as I can tell this is not available anywhere. I can get the low-res logo off the website, but this looks ugly when used as an icon. Could it be added as a resource somewhere in the repo.
![image](https://github.com/user-attachments/assets/ef5067ea-2849-49ba-b977-8aa52a489725)

**Comment by Moult** [comment]
This is very true, it's buried somewhere in this SVG: https://github.com/IfcOpenShell/website/blob/main/wip-design/mockup.svg (it's a multipage SVG accessible via Inkscape - Github only previews the first page)

If you have time, it would be really appreciated if you could help isolate all of the important logos in SVG format and save them out separately so that we can include them in the IfcOpenShell/website repo for others to use.

**Comment by aothms** [comment]
We might want to work towards some sort of a "press kit". Contributions welcome as always :)

**Comment by sboddy** [comment]
Do you mean all the individual program icons? I've pulled them into an Inkscape file, and I've cleaned them up a bit. Do you have any objection to some minor tweaks to get them 32x32 grid aligned for sharper rendering to smaller icon sizes? Mostly nudging points around to align. I'll do a before and after set, so if you don't like the after, you can just use the before.
 I've already made the "swoop" consistent between C++, Python, and Convert icons. Also for use on dark backgrounds I added a light fill to a couple of the icons where it made sense. i.e. the bsDD book.

**Comment by sboddy** [comment]
Tweaked main app logo... "Looking good, Billy Ray!"
![image](https://github.com/user-attachments/assets/249e58a8-7f43-45be-b7e5-873c573d8769)
I've tweaked most of the icons already. Will attach here when finished.

**Comment by Moult** [comment]
Go for it! I didn't consider your points when drawing up the icons, it sounds very logical and awesome :)

**Comment by sboddy** [comment]
![Bonsai](https://github.com/user-attachments/assets/76c7221f-f4a7-4fab-9e0c-1c5bc96c0551)
I have attached an SVG containing all the icons layed out. First row is the original icon. Second row is after I tweaked and titivated them. (32x32 grid alignment, 1/32 spacing between elements, add a light background if it made sense.) Honestly the effect is more subtle than I thought but there are noticeable improvements. If there's a third row, I've more significantly changed some aspect because I thought it improved clarity, or readability.
![IfcOpenShellLogos](https://github.com/user-attachments/assets/b159290d-782c-43cf-9586-239bf9da743a)
The file will work with the Extensions -> Export -> Export Layer Slices... menu to generate bitmap icons in all the common sizes.
I've also included a Linux bash script that exports all icons as SVG's, and runs them through the scour optimizer. [ExportLayers.zip](https://github.com/user-attachments/files/17299107/ExportLayers.zip)
If my changes are OK, I can edit it to only include those icons, and produce a "final" set of SVG's as an attachment. Just let me know.

**Comment by Moult** [comment]
Fantastic! I think your changes are sweet. I'm not a fan of the light grey fill - I know why you did it but I feel as though it sticks out compared to the rest of the icons. If you come up with a new design that doesn't rely on filled areas, I'd prefer that (the book for the bSDD icon was pure laziness on my end, just grabbing free clipart).

For example here's an option for IfcDiff that doesn't rely on the fill:

![2024-10-09-110007_347x427_scrot](https://github.com/user-attachments/assets/6429fd36-69b9-47fa-a879-df86d155dbc5)

Squinting my eyes, I feel as though the IfcPatch icon also sticks out (not in a good way) due to its aspect ratio. If you feel motivated feel free to come up with a new design for that one too :)

I also like how you swapped the colours for IfcFM - making the spanner stand out more. Happy for that to be the new icon.

Not a fan of the black snake eyes. I think it's OK for the eyes to "disappear" at smaller resolutions.

Really like the standardisation of the margins across the icons.

All in all, really great work!

**Comment by sboddy** [comment]
How about these? Ignore the Patch one, I haven't tried to find a good alternative for that yet.
![IfcOpenShellLogos](https://github.com/user-attachments/assets/bb60f366-f5a6-4bdd-9242-43de6b4ba745)

**Comment by Moult** [comment]
Mmmm, I see what you're doing there but not a fan unfortunately. The reason is that icons tend to be either of the solid style or the outline style. IfcOpenShell's suite seems to have used the outline style, so it sticks out with a block solid colour. Can I recommend completely redesign the bSDD logo? A book was just laziness on my end.

Here's some ideas playing with a dictionary code symbol (after all that's what the bSDD is - a dictionary library for developers).

![2024-10-09-152236_648x319_scrot](https://github.com/user-attachments/assets/9632557c-b470-42ab-bddc-2dd845a0f739)

And here's a way to avoid the fill on the IfcDiff logo:

![2024-10-09-152613_170x173_scrot](https://github.com/user-attachments/assets/ff743511-1b72-425d-9fa6-9c1d205d2b08)

A similar strategy of snaking the lines together could be used for IfcSverchok.

**Comment by aothms** [comment]
> Not a fan of the black snake eyes. I think it's OK for the eyes to "disappear" at smaller resolutions.

I agree, I find the snake also a bit too detailed in constrast with the other icons which are more schematic/minimalist. So if there is a way to make it even a bit more abstract I wouldn't complain.

But yes, great work indeed!

**Comment by sboddy** [comment]
So I understand your ideas for the bsDD icon as representing code dictionaries. I just wasn't sure if this icon would be presented to non-programmers, in which case the lazy book representing a reference book or "bible" may have been more intuitive. I'll start having a play with that one based on your options. Then just the patch one to go.
![IfcOpenShellLogos](https://github.com/user-attachments/assets/16c2ff20-c243-49a7-ae92-de1ba3f06510)
For the Diff and Sverchok icons I've tried to maximise snakey-ness. I like bottom-right variant of both, but your house, your rules, your choice.

**Comment by sboddy** [comment]
Can anyone actually open that image as an svg outside github? There's this whole private images thing going on which means I can't open any images or svg, only view them embedded and scaled in the comments. Same for you? If so, I guess I have to zip it up and attach it.

**Comment by Moult** [comment]
bSDD is a programmer library so it probably only needs to appeal to programmers :)

I also love the bottom-right variant for Sverchok. For IfcDiff, I'm tossing up between the one at the bottom-right and the one just above it. I love the creativity of the one in the bottom right with the inline minus sign, but also feel conflicted because I think it loses recognisability of the ± symbol ubiquitous for diffing tools. You choose - unless someone else here wants to weigh in with preferences too :)

If I click your SVG, I get a black screen. But If I right click save as, I can view the SVG (and edit in Inkscape) without issues, so probably no need to zip.

**Comment by sboddy** [comment]
On bsDD... Hmmm... There's a whole section in the Bonsai UI for connecting to bsDD and getting various dictionaries. Of course I'm still trying to grasp concepts here, so what do I know ;-) As well as some variations on your ideas I've done a couple of more wildcard versions (col 3) just in case. Take or leave them. For whatever my opinion is worth... not keen on direct reuse of the CSV construct as it confuses concepts to me. Not keen on putting things _outside_ the dictionary brackets - that seems counterintuitive. I prefer the bracket gradient in col 1. Could it be argued that bsDD is a bit a of a database? Is the more snakey book still a non starter? If both no, then I'd choose c1r5. Dictionaries are long sets of key/value pairs, and this is about as literal as it gets. Always open to more ideas.
![IfcOpenShellLogos](https://github.com/user-attachments/assets/878ffbd5-e765-45fc-a873-dbed41ce2bfb)

Sverchok locked in.

IfcDiff. Yeah, I agree with you. I just liked the way looked, but I know the familiar +/- you mean. You mentioned snakey-ness, and I just wasn't keen on the way the minus symbol broke the flow of the outline. Locking in the more familiar one.

I think I figured it out. I think only people with more rights in the project than I have can download files. I think perhaps people were misusing github so they made this change. Doesn't matter as long as the _important_ people can get it. ;-) I'll post it direct from now on.

**Comment by Moult** [comment]
Wow, those are all really good ideas for bSDD. Although I also like it, my concern about c1r5 is that the small dots at the bottom could be easily lost at smaller scales. I also like c3r3 and c3r4 (the book designs). The cylinder database design at c3r5 doesn't click with me, perhaps more due to the squashing and stretching of the line thickness than the actual shape.

You're right that Bonsai has a UI for bSDD. At this moment, the bSDD logo only represents the library, and the Bonsai logo represents the entirety of Bonsai (which happens to also interface to bSDD). So that's why right now it's only geared at devs. However, this may change in the future and in that case you're right it's probably better to have the book / db cylinder logo which is more generic and could even one day appear within the Bonsai interface. (I prefer the book compared to the db cylinder personally)

Feel free to make a call and lock something in :) It's really awesome design work you're doing!

**Comment by sboddy** [comment]
OK, so I tweaked the database and the c1r5 based on your comments. Now all three look good. So now I'll just make all three available. You can use the one that feels right, and you can keep the others in your back pocket in case a use pops up in the future.
I've done a first cut on something for IfcPatch, which I thought was going to be the hardest. I already have a favourite.
![IfcOpenShellLogos](https://github.com/user-attachments/assets/b2a7c55c-1375-4c5b-8373-e17b67b386f0)
Yes? No? Not quite there?

**Comment by Moult** [comment]
Awesome! I think we should use the book icon for bSDD. Later on when IfcDB becomes a thing or who knows what comes up I'm sure those other two options can be reused as you say :)

I love option 4 for IfcPatch! It retains the idea of "processing", resolves the aesthetic issue of aspect ratio, and also even looks like a P if you squint :D

**Comment by sboddy** [comment]
Ah-ha! That was my pick too. I'll tidy the master file up, and fix/run the script to generate the individual final icons. Then I'll zip them up and attach it all here. (Excluding the bazillion bitmapped sizes, which you can do yourself using the Inkscape plugin as explained above if you really need bitmapped icons.)
Addressing your edit...
The colours are all ones from the original icons. I used a short radial gradient distance meaning the green and orange are quite dominant. The idea being that the outer yellow corners represent the light bulb moment. One (t-r) when you realise there's an issue that needs to be fixed, and the other (b-l) when you figure out how to fix it. A bit twee maybe. Here's alternatives... And damn it! Why'd you have to mention the squinty P? So I have a variant that now has both C (continuous) and P (patching) very clearly visible. Might be "too on the nose" though.
![IfcOpenShellLogos](https://github.com/user-attachments/assets/14de07a9-39ac-469e-84fa-d4f076baf4a7)

**Comment by Moult** [comment]
They all look great. Pick your favourite :)

**Comment by sboddy** [comment]
OK. Here you go. Source SVG file, export script, and a folder of exported SVGicons.
[BonsaiIcons.zip](https://github.com/user-attachments/files/17336323/BonsaiIcons.zip)

**Comment by Moult** [comment]
Thanks so much! I've committed it to the website repo and updated the website to use SVG icons so in the future people can just right click save as.

**Comment by aothms** [comment]
Is  this also the moment to bring up something like a Press kit and  Press releases? Is there somebody in the community who is interested in maintaining that kind of public outreach? There's quite some interesting things going on that we could celebrate a bit more as a community.

**Comment by Moult** [comment]
Absolutely - I think we've hit a lot of big milestones, IfcOpenShell v0.8, Infra support, Bonsai rebrand, Bonsai 5 years anniversary, Python API refactor, and a definitely feel in my mind that in Bonsai at least things are shifting from alpha to beta.

@sboddy if you or anybody else is interested in writing up an equivalent to https://www.blender.org/about/logo/ somewhere (it can probably live as a new page in our Sphinx docs in docs.ifcopenshell.org) - that will be the precursor to doing some nice press releases.

**Comment by sboddy** [comment]
Hmmm... Have you actually registered the Bonsai and IfcOpenShell logos and names? Without that you might as well just post a link to the iconset because anything written on that page would have no teeth in law as I understand it. No, IANAL, but generally you have to register a trademark to enforce prevent anyone else from using the mark in ways you don't want.

Also... I hate to be that guy, but I just did a search... https://www.hellobonsai.com/
and I think this is them:
- https://trademarks.ipo.gov.uk/ipo-tmcase/page/Results/1/UK00003862049
- https://euipo.europa.eu/eSearch/#details/trademarks/018815511
- wierdly I can't find them on the uspto site, despite them being an American company.

There's quite a lot of other trademarks using variations on bonsai, but that one would concern me most based on my limited understanding of the 4D/5D stuff in _this_ bonsai. As I understand it, one of the criteria for trademark infringement is if it could cause confusion in customers. So, a literal producer of bonsai trees would be very unlikely to cause confusion, but these two bonsai might.
Their logo is especially a bit "Yikes!", although I haven't found evidence that the logo is trademarked in their filings. However that just might be me not knowing the right search incantation.

**Comment by Moult** [comment]
Not sure if @aothms has registered IfcOpenShell but most certainly not registered Bonsai. That hellobonsai looks very different to the 4D/5D that IFC deals with, so I'm not worried. If anything that's more CDE-type scope. If it's not a huge pain to register this stuff, it's probably a good idea to do so.

**Comment by aothms** [comment]
> Not sure if @aothms has registered IfcOpenShell 

No, it always felt weird to me to register a trademark for a class name from an open standard.

But sure, there comes a point in time we need to do these things. But I'd prefer not to register them under the name of an individual natural person. I.e we should probably first setup a real proper legal foundation to have an entity to assign trademark ownership to.
