### ISSUE TITLE
Documents reference in UI | Menu naming and URL

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5542]
when setting up a document tree in a model the first option is to create a folder:

![image](https://github.com/user-attachments/assets/0f3a62e8-eeca-47b6-9abd-c385b6332ce0)

once created it automatically adds a document reference in it:

![image](https://github.com/user-attachments/assets/826641fa-c247-4aa7-86b3-b79c6bfa2578)

to edit its properties I use the pencil to open the relevant panel, in this example I add an identification `1.1` the path to the document in `Location` and its `Name`:

![image](https://github.com/user-attachments/assets/0461853c-cb17-46bc-90d8-0ffeda3c7219)

### issue: the menu shows the path and not the name

from the documents in Project Overview:

![image](https://github.com/user-attachments/assets/a0c7b844-1fd4-4c1c-ab2d-d2023a79f877)

from the Documents in Object Information ... Misc.

![image](https://github.com/user-attachments/assets/334f578b-048d-4981-80fe-e7a0e94619fb)

### request

is it possible to show the name instead? it would be easier to understand the document reference to assign
thanks

**Comment by Andrej730** [comment]
@steverugi It used to show the name instead of description + location before this commit d1e8b4a but I think the way it is right now is correct.

IFC has a restriction for IfcDocumentReference to have a name only if it has no referenced document.

![image](https://github.com/user-attachments/assets/642cb30c-b6be-4544-a13f-219c5bf9db0a)

See https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcDocumentReference.htm#8.6.3.5.4-Formal-propositions
