### ISSUE TITLE
Bonsai dependency conflict with Home Builder 4 (cannot import name '_imaging' from 'PIL')

### ISSUE THREAD

**Issue by VeaseyB** [IfcOpenShell/IfcOpenShell#5580]
When I have Home Builder 4 installed Bonsai will not install.

**Comment by Andrej730** [comment]
@VeaseyB What Blender version? What error?

**Comment by sboddy** [comment]
Try uninstalling HB, install Bonsai, then reinstall Bonsai.

**Comment by Andrej730** [comment]
@VeaseyB

*Technical details*

Full error:
```
Traceback (most recent call last):
  File "\Blender\4.2\scripts\modules\addon_utils.py", line 488, in enable
    mod.register()
  File "\4.2\extensions\blender_org\bonsai\__init__.py", line 246, in register
    import bonsai.bim
  File "\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\__init__.py", line 24, in <module>
    from . import handler, ui, prop, operator, helper
  File "\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\handler.py", line 26, in <module>
    import bonsai.tool as tool
  File "\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\__init__.py", line 48, in <module>
    from bonsai.tool.profile import Profile
  File "\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\profile.py", line 27, in <module>
    import PIL.ImageDraw
  File "\4.2\scripts\addons\home_builder_4\python_libs\PIL\ImageDraw.py", line 37, in <module>
    from . import Image, ImageColor
  File "\4.2\scripts\addons\home_builder_4\python_libs\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (\4.2\scripts\addons\home_builder_4\python_libs\PIL\__init__.py)
```

Issue occurs only if no Blender extensions with dependencies was ever installed and `Blender\4.2\extensions\.local\lib\python3.11\site-packages` folder doesn't exist, otherwise it always takes priority over some custom libs folders such as `Blender\4.2\scripts\addons\home_builder_4\python_libs` (at least if they're appended to the path, not prepended). If Bonsai installed after Home Maker then Blender adds `python3.11\site-packages` to the path during installation but it goes after `home_builder_4\python_libs` leading to this error.

So, if Bonsai is installed first and only then installed some addon hacking into dependencies path, then Bonsai dependencies will take the priority.

---

@VeaseyB 

Anyway, all of it doesn't really matter since the problem is that import really fails only because Home Maker 4 provides PIL binaries only for Python 3.10, when Blender 4.1+ is requiring Python 3.11...

![image](https://github.com/user-attachments/assets/cdde2890-0205-4605-87bc-47d1046b5032)

But looking through Home Maker 4 code it seems they don't really use `PIL` and don't really use `reportlab` (which was using `PIL`) and they were even removed from the repo - https://github.com/CreativeDesigner3D/home_builder_4/commit/1520dcad151835b3da99405ef856cec1dde0ed33. 
So I guess you can just delete `PIL` and `reportlab` folders from `python_libs` and Bonsai will install without issues.

![image](https://github.com/user-attachments/assets/8ab09ee6-742e-4222-bd6f-8d4e1ddf7bc3)

**Comment by Andrej730** [comment]
Reported as an issue with Home Maker - https://github.com/CreativeDesigner3D/home_builder_4/issues/8.

Current workarounds are 1) Install Bonsai first and then Home Maker or 2) Install Home Maker and remove `PIL` and `reportlab` folders and then install Bonsai.
