### ISSUE TITLE
`UnicodeEncodeError` error on reading `IfcGloballyUniqueID` on Ubuntu

### ISSUE THREAD

**Issue by amrit3701** [IfcOpenShell/IfcOpenShell#562]
<q>When we read `IfcGloballyUniqueId` from IFC file on Ubuntu, it gives `UnicodeEncodeError` but on MacOSx ifcopenshell successfully parse `IfcGloballyUniqueID` (i.e. `2oAZ$Cu_aHwBkVc2Blr0Hl`).</q>

Please refer to this. https://gist.github.com/amrit3701/ebdf91fa3db5e71e7a334ef38e4dcefa

Here I created a proof of concept that how I successfully read `GlobalId` on MacOS but on Ubuntu its gives `UnicodeEncodeError`.

Also, I tried to search it about this error, but not sure is it related to IfcOpenShell (maybe some C++ library) or Ubuntu OS?

**Comment by Moult** [comment]
Haven't had time to test this, but can you check with the system python? Not ipython.

**Comment by aothms** [comment]
Thanks for the detailed report.

My guess is that this is due to the internal unicode representation setting in Python. This is unfortunately a compile time setting, but you can check it at runtime using `sys.maxunicode`. For wide (that can represent the full UCS-4) this is '0x10ffff', on builds with a narrow representation (UCS-2) this is a lower number. Whether a distribution ships narrow or wide Python builds seems pretty arbitrary.

This is the reason there are builds for `Python 27` and `Python 27u` for the newer builds of IfcOpenShell [1]. Somewhat embarrassingly I forgot whether the `u` signifies narrow or wide unicode. Since Python 3.3 there is "universal unicode", which eliminates this setting.

My advice, either switch to a more recent Python version or try the `27` and `27u` builds below. Let me know whether this resolves your issue.

[1] https://github.com/IfcOpenBot/IfcOpenShell/commit/bf1623975c6451baf3e2a1af9f32e9306d235b3f#commitcomment-32346507

**Comment by hsrai** [comment]
Python 27u i.e https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-27u-master-bf16239-linux64.zip worked fine. Thank you for the solution.

**Comment by amrit3701** [comment]
@Moult Thanks for responding. I checked with system `python` also but getting the same error. 
I will try @aothms way and share updates here.

**Comment by amrit3701** [comment]
@Moult Yeah! It works on my side also. Thanks for your answer.
