### ISSUE TITLE
Borked cylinder when extruding pipe from IfcCircleHollowProfileDef 

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#567]
1. Convert [https://github.com/IfcOpenShell/files/blob/master/567--borked-cylinder.ifc](567--borked-cylinder.ifc) extruded from `IFCCIRCLEHOLLOWPROFILEDEF(.AREA.,$,#598,125.0,2.0);`
2. Experience that the output geometry has 187 vertices and that one of the sides seemingly has a "perfectly" created area created from 26 circle segments, whereas, the other side is skewed to an unclosed geometry.

<img width="300" alt="Screenshot 2019-04-05 at 15 35 16" src="https://user-images.githubusercontent.com/4601554/55631488-6f097300-57b8-11e9-8b7b-55aae5044d8b.png">

| Side 1 | Side 2|
| ------------- | ------------- |
| <img width="200" alt="Screenshot 2019-04-05 at 15 26 11" src="https://user-images.githubusercontent.com/4601554/55631105-898f1c80-57b7-11e9-8ea6-e815ba975c2f.png"> | <img width="200" alt="Screenshot 2019-04-05 at 15 26 00" src="https://user-images.githubusercontent.com/4601554/55631128-9744a200-57b7-11e9-9960-afcc2a1ac4d2.png"> |

There is definitely something wrong going on side 2,

Further, and irrespective of this bug, it would be nice to have an option to control the amount of circle segments circles are tessellated into. For many cases, 26 segments may be more than what is needed.

**Comment by aothms** [comment]
I can't seem to reproduce this. I also don't really see from the images what's happening. A conversion to DAE imported in Blender looks like this.

![afbeelding](https://user-images.githubusercontent.com/1096535/55635705-a892ac00-57c1-11e9-9af9-3da6c9e586cc.png)

What exact settings did you use? Can it be related to the patch I think you apply?

> it would be nice to have an option to control the amount of circle segments circles are tessellated into

You have with `--deflection-tolerance` it's the approximate maximal distance between curved surface and planar approximation. E.g.

![afbeelding](https://user-images.githubusercontent.com/1096535/55635962-2951a800-57c2-11e9-90aa-0eca7e45dea9.png)

**Comment by johanrd** [comment]
Ah, ok. Thanks for checking. The resulting obj file we get is [567--borked-cylinder.obj.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/3048624/567--borked-cylinder.obj.zip)

We run with --deflection-tolerance 0.1 and [this patch](https://github.com/IfcOpenShell/IfcOpenShell/files/3048641/2016-12-12-tesselation-control.patch.zip), which very well may be the source of our bug. 

Thanks for clarifying. I will investigate a bit regarding what in our setup that creates this issue.

**Comment by johanrd** [comment]
After testing without the patch, I can still reproduce. See resulting file:  [567--borked-cylinder.obj.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/3048624/567--borked-cylinder.obj.zip)
![Apr-06-2019 13-08-44](https://user-images.githubusercontent.com/4601554/55668683-776fb580-586d-11e9-829c-daaba83939b8.gif)

**Comment by johanrd** [comment]
Update: closing this, as it turned out to be our patch inducing this bug after all. The trouble seems to come from setting `isRelative=true` on [BRepMesh_IncrementalMesh](https://www.opencascade.com/doc/occt-6.9.0/refman/html/class_b_rep_mesh___incremental_mesh.html).

Regarding `--deflection-tolerance`: It seems like IfcOpenShell caps circle segments to minimum 26:

| --deflection-tolerance | circle segments | vertices |
|---|---|---|
| 0.0001 | ≈111 | 896 |
| 0.001 | 35 | 288 |
| 0.01 | 26 | 212 |
| 0.1 | 26 | 212 |
| 1 | 26 | 212 |

This seems to be because `theAngDeflection=0.5` in `OCCT:BRepMesh_IncrementalMesh` is a second capping mechanism that kicks in whenever the linear-deflection tolerance is too big. I guess it could be nice to work towards being able to set `--angle-deflection` as a parameter as well, to override the OCCT default. (+ also perhaps `isRelative`, once we know what is creating the bug above)

**Comment by aothms** [comment]
> is a second capping mechanism that kicks in whenever the linear-deflection tolerance is too big. 

Ah yes that's a very good point. Had not realized that. Perhaps setting that to a much higher value will at least continue the linear tolerance to keep having effect.

Note it's actually nice to see the numbers to make some sense:

~~~
>>> from math import cos, pi
>>> def d(R, N):
...   return R * (1. - cos(pi / N)) * 2
>>> d(0.125, N=35), d(0.125, N=111)
(0.001006426501190233, 0.000100123220419579)
~~~

With R the circle radius and N number of segments.

Is this something you guys would want to work on? Feel free to adapt the command line so that your patch is no longer necessary. 

~~~
if TRUE deflection used for discretization of each edge will be <theLinDeflection> * <size of="" edge>="">. Deflection used for the faces will be the maximum deflection of their edges. 
~~~

So each edge will get a different deflection. Because of the incremental nature of the algorithm this may cause what we're seeing. I think it's a recursive approach to keep subdividing until the tolerance criteria are met. For the hollow cylinder the inner and outer edges have a slightly different length, but perhaps it's just enough to cause an additional recursion step and that therefore the inner edge gets a different number of segments from the outer edge. It's a bit of a guess.

What we can do, if this adaptive nature is important to you guys, we add a factor to the *global* shape deflection based on local settings such as the smallest edge length or the some characteristic of the shape bounding box.
