### ISSUE TITLE
Performance issue when parsing an IFC with 100k elements

### ISSUE THREAD

**Issue by YouYue123** [IfcOpenShell/IfcOpenShell#569]
I am facing a performance bottleneck for converting ifc into obj. It took almost 20 hours to convert. The version is IfcConvert 0.6.0a1 (OCC 7.2.0). Is there any way to make it faster?

**Comment by Stinkfist0** [comment]
One thing to consider is using DAE output instead of OBJ. If there are many instances of same objects in the file, the instancing support provided by DAE can increase the speed considerably. More in-depth analysis would require seeing the IFC file in question and processing it while running debugger/profiler. E.g. Visual Studio 2017 and newer should have a good profiler which I used to optimize performance when doing XML output a while back.

**Comment by YouYue123** [comment]
Hi I have compiled with flag` -DENABLE_BUILD_OPTIMIZATIONS`. I see VS 2017 would be a good option for optimisation. And I am now trying to use `deflection-tolerance` setting for generating less detailed mesh. I realise the default number is 1e-3 but after I change it the OBJ file is still remain the same. May I know why this parameter does not affect the final OBJ size?

**Comment by aothms** [comment]
> May I know why this parameter does not affect the final OBJ size?

It only affects geometries which are actually modelled as curved surfaces in IFC. Unfortunately a lot of detailed geometries in IFC (especially in ifc2x3) are explicit polyhedra in which case this setting has no effect.

**Comment by YouYue123** [comment]
Thanks for the information aothms. Could you give me some thought on the following 2 points? I would like to work on it and contribute back to community.

1. Parsing IFC to geometry in multi-threading or even distributed way

2. An option to simplify and decimate mesh to get on a less detail and smaller mesh file

Thanks

**Comment by aothms** [comment]
>  I would like to work on it and contribute back to community.

That's great to hear.

1. @sanderboer has been working on this, but it has been a while since we heard from him. His work is on the master branch and will need to be rebased to 0.6. It would be great if you contact him and see if you can pick up where he left and provide a pull request for 0.6

2. Starting from the 0.7 branch there is an alternative CGAL geometry implementation. It probably has more natural support for these kind of polyhedra and already comes with some simplification algorithms. https://doc.cgal.org/latest/Surface_mesh_simplification/group__PkgSurfaceMeshSimplificationRef.html

The CGAL work is not ready for production yet (most files don't process well) but I think it's our best bet for the kind of files you are dealing with. Would this be something you are interested in?

**Comment by YouYue123** [comment]
Thanks sounds great.

1. I will contact @sanderboer for this. And I saw that 0.6a1 has already been released. What is the future releasing plan for 0.6 or even upgrading to 0.7?

2. That sounds cool and I am definitely interested. 

I know libigl also has an approach for this. I have used it in my other projects. [libigl mesh decimation](https://libigl.github.io/tutorial/#mesh-decimation)

**Comment by aothms** [comment]
Great, 

> libigl

I am also fine with that, since it's header only it might be something we can provide in 0.6. I think it's dual licensed MPL2 which I think is compatible with LGPL.

> What is the future releasing plan for 0.6 or even upgrading to 0.7?

I already recommend 0.6 unless you need to link dynamically (e.g. if you want to distribute closed source software based on IfcOpenShell and want to comply with the lgpl) 0.7 is still quite far out because of the recent CGAL addition (which is not really my expertise).
