### ISSUE TITLE
Missing triangles for RIV in model 'Demohuset'

### ISSUE THREAD

**Issue by larsmoa** [IfcOpenShell/IfcOpenShell#57]
I experience some missing triangles for certain geometry in various models in the latest version of IfcOpenShell (81ee60079e0d6a27a8df0d2804082413a4a4e89d). This issue is visible in several models, but I have extracted one object from the [public available 'Demohuset' model](http://www.demohuset.no/) that hopefully will help in determining the cause. Also note that many triangles have wrong facing normals - this is not a big problem for us as we remedy this by disabling back-face culling.

In Solibri Model Viewer the model is rendered correctly:
![image](https://cloud.githubusercontent.com/assets/6741854/14523049/d8e08df2-0231-11e6-8a65-138146e32764.png)

The OBJ output from IfcOpenShell is missing some triangles (note that this is rendered without back-face culling):
![image](https://cloud.githubusercontent.com/assets/6741854/14523099/1cf7052a-0232-11e6-85aa-96f6b8a0adc2.png)

The IFC file (extracted from original): [RIV-Ventilasjon-extracted-fan.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/218771/RIV-Ventilasjon-extracted-fan.ifc.zip)
The original file IFC file is available from http://www.demohuset.no/page5321913.aspx.

I have verified that this worked with an old version of IfcOpenShell (462425f61d402a54046972c177143cbf6eb0c7e5), but have not pin-pointed when the issue was introduced. I have built IfcOpenShell with OpenCascade 6.9.1.

**Comment by aothms** [comment]
This has been introduced here: https://github.com/IfcOpenShell/IfcOpenShell/commit/40a60386c8e994dfbfa594e2d5e35b870a49842e#diff-cbd871bf25fd52ab573b12d9ae80cc3cL110 in my head I knew there still was something that needed to be ported over.

The issue is that these faces are not flat, while they should be if no underlying face surface is provided. For mesh-based applications such as Solibri this does not really matter, but in IfcOpenShell a proper BRep needs to be constructed within its tolerance limits. Prior to https://github.com/IfcOpenShell/IfcOpenShell/commit/40a60386c8e994dfbfa594e2d5e35b870a49842e the trick was to arbitrarily raise the tolerance, with https://github.com/IfcOpenShell/IfcOpenShell/commit/884b3fe850f520a1d87ca810b440988b42824cf0 offending wires are flattened onto a plane.

With regard to the surface normals. They do seem to be correct as IfcOpenShell displays them based on the winding order of the loops.

**Comment by larsmoa** [comment]
Thank you for the quick response (again). I have verified the fix - thank you.
