### ISSUE TITLE
In the UI, Pset_RoofCommon.LoadBearing is not a IfcBoolean

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5708]
![image](https://github.com/user-attachments/assets/ecf87d54-1718-44e7-8927-4c4b07e02284)

would assume it would look like this...
![image](https://github.com/user-attachments/assets/d935204c-4d40-4b01-8a03-ce8a689fb259)

**Comment by Andrej730** [comment]
It's a bug in IFC4 psets - https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.8.0/src/ifcopenshell-python/ifcopenshell/util/schema/Pset_IFC4_ADD2.ifc:
```
#3983= IFCSIMPLEPROPERTYTEMPLATE('27gGzXJgHElgJNKZaas8aH',$,'LoadBearing',$,.P_SINGLEVALUE.,$,$,$,$,$,$,.READWRITE.);
```

Fixed in IFC4X3:
```
#3612=IFCSIMPLEPROPERTYTEMPLATE('01oljf6EnDgeuspLC1XrC4',$,'LoadBearing','Indicates whether the object is intended to carry loads (TRUE) or not (FALSE).',.P_SINGLEVALUE.,'IfcBoolean',$,$,$,$,$,.READWRITE.);
```

Same issue for https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/Pset_RampCommon.htm:
![image](https://github.com/user-attachments/assets/b81cb10a-7be7-4b2a-99e5-e2b1ff8c15e3)

And https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/Pset_StairCommon.htm
