### ISSUE TITLE
 No module named 'mathutils'

### ISSUE THREAD

**Issue by swiss-knight** [IfcOpenShell/IfcOpenShell#5717]
Hello,

when installing `ifcopenshell` 0.8.0 using `pip` it seems there's a non-resolved dependency with the `mathutils` package:

```py
Python 3.12.7 (main, Oct 19 2024, 01:09:09) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import ifcopenshell
>>> import ifcopenshell.api.context
Note: API not available due to missing dependencies: geometry.add_door_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: geometry.add_railing_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: geometry.add_representation - No module named 'bpy'
Note: API not available due to missing dependencies: geometry.add_window_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: grid.create_axis_curve - No module named 'mathutils'
```

Could thhe `mathutils` package be automatically installed if missing when installing `ifcopenshell`?

Once installed manually, these messages disappear.

OS: Debian 12.7

Thank you!

Warm Regards.

**Comment by brunopostle** [comment]
This is a recent regression, `geometry.add_representation` was working without blender a few weeks ago

**Comment by Andrej730** [comment]
It's an optional dependency, therefore it's not installed with `pip install ifcopenshell`, we plan to replace it with `numpy` #5192

> This is a recent regression, `geometry.add_representation` was working without blender a few weeks ago

`geometry.add_representation` for a long time depends on Blender, it has Blender object as one of the arguments.

**Comment by brunopostle** [comment]
@Andrej730 sorry I was misremembering, this is the error I see recently (rebuilding now, so maybe this is fixed):

```
    import ifcopenshell.api.root
  File "/usr/lib64/python3.12/site-packages/ifcopenshell/api/root/__init__.py", line 30, in <module>
    from .copy_class import copy_class
  File "/usr/lib64/python3.12/site-packages/ifcopenshell/api/root/copy_class.py", line 21, in <module>
    import ifcopenshell.api.system
  File "/usr/lib64/python3.12/site-packages/ifcopenshell/api/system/__init__.py", line 31, in <module>
    from .assign_port import assign_port
  File "/usr/lib64/python3.12/site-packages/ifcopenshell/api/system/assign_port.py", line 21, in <module>
    import ifcopenshell.api.geometry
  File "/usr/lib64/python3.12/site-packages/ifcopenshell/api/geometry/__init__.py", line 47, in <module>
    from .add_slab_representation import add_slab_representation
  File "/usr/lib64/python3.12/site-packages/ifcopenshell/api/geometry/add_slab_representation.py", line 22, in <module>
    from mathutils import Vector
ModuleNotFoundError: No module named 'mathutils'

**Comment by Andrej730** [comment]
> File "/usr/lib64/python3.12/site-packages/ifcopenshell/api/geometry/add_slab_representation.py", line 22, in <module>
>     from mathutils import Vector
> ModuleNotFoundError: No module named 'mathutils'

I believe it's after 0c02255, ping @brunoperdigao

**Comment by brunoperdigao** [comment]
@brunopostle I've removed the dependency: https://github.com/IfcOpenShell/IfcOpenShell/commit/4b558604cc5c1c47fb5330b5321c0f7d0ebd2ec6

**Comment by brunopostle** [comment]
@brunoperdigao thanks, api now imports without mathutils here.

**Comment by tibohu** [comment]
I thought Mathutils was not a dependency anymore for two weeks ago. What do I miss?

">>> ifcopenshell.version
'0.8.1-alpha250103'"
">>> exec(open(path).read()) 
Note: API not available due to missing dependencies: geometry.add_door_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: geometry.add_railing_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: geometry.add_representation - No module named 'bpy'
Note: API not available due to missing dependencies: geometry.add_window_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: grid.create_axis_curve - No module named 'mathutils'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 68, in <module>
AttributeError: module 'ifcopenshell.util' has no attribute 'shape_builder'"

**Comment by tibohu** [comment]
@swiss-knight 
Could you please help with your method mentioned above on how to do the manual install of Mathutils?
