### ISSUE TITLE
error when using `bpy.ops.bim.edit_sheet()`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5769]
error when using `bpy.ops.bim.edit_sheet()`
ping @sboddy 

files if you need them
[material and styles.zip](https://github.com/user-attachments/files/17821277/material.and.styles.zip)

https://github.com/user-attachments/assets/c37daf94-6511-45e8-8b87-e826c1fa25ff

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 443, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 3064, in _execute
    sheet_builder.change_titleblock(sheet, titleblock)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\sheeter.py", line 501, in change_titleblock
    os.makedirs(os.path.dirname(titleblock_path), exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [WinError 5] Access is denied: 'layouts'

```

**Comment by sboddy** [comment]
Ack'ing. I think you're actually clicking the wrong button, but you can't click the right one because I was overzealous graying out items. It should be the same button as the edit page I think (the page and pen icon, four to the right). I'll look into that, probably a simple fix. The button you are clicking on is for changing which layout to use. That one is odd, as that is a file system permissions error. I don't use Windows as a rule, so I'm a little unsure why you are getting this. I don't get any error when replicating your steps here on Linux. I'll take a look at the code at that point, but I don't _think_ it was my stuff.

**Comment by sboddy** [comment]
Yeah, editing items can be fixed just by deleting https://github.com/IfcOpenShell/IfcOpenShell/blob/bf717622a01c4a068e44a30145fcef186f8d4394/src/bonsai/bonsai/bim/module/drawing/operator.py#L1510-L1512

I can do it, but you have direct access so that might be quicker if you push the correction. That'll allow you to edit all the sub items in Inkscape too.

**Comment by sboddy** [comment]
Hmmm. On the error when trying to change the titleblock, it seems to be trying to ensure folders exist by makedir'ing the paths it needs. This is failing with a permission issue. I know you do some funky things with your asset/texture/template folders, and I wonder if this is a symptom of something there. I definitely didn't change the change_titleblock code in the sheeter.py file, and I don't even think I touched the EditSheet class in operator.py at all... In other words... Not it!!!!

Maybe put some exploratory prints in the change_titleblock code to see what it is hunting for, then investigate your filesystem for why it cannot be done.

**Comment by Andrej730** [comment]
Hi! Can you try after the commit referenced above?

**Comment by theoryshaw** [comment]
Seems to work from my side!
