### ISSUE TITLE
Performance regression in 0.6.0

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#578]
Convert [578--washBasin.ifc](https://github.com/IfcOpenShell/files/blob/master/578--washBasin.ifc) and experience that conversion takes ca 100 times more time on v0.6.0 compared with 0.5.0:

|Branch|Commit|Conversion time|
|-|-|-|
|v0.5.0|9048ce48574f493795ad454c1832c7d9a38901f5 (OCCT 7.3.0)| ~30 s |
|v0.6.0|4792fd9efe2aafdd7b6ad4d54067328041668f10 (OCCT 7.3.0)| ~50 min |

<img width="200" alt="Screenshot 2019-04-27 at 10 19 32" src="https://user-images.githubusercontent.com/4601554/56847135-abbc1c00-68d7-11e9-9bba-b683555d0039.png">

**Comment by YouYue123** [comment]
Have you tried using --merge-boolean-operands

**Comment by aothms** [comment]
Yes I understand your frustration. This sink contains 80000 explicit faces and there is simply a lot of overhead in the Open CASCADE data model and algorithms for these cases. I think what you can see from the screenshot is that the orientation of these faces is not correct in the other viewer. IfcOpenShell tries to correct the orientation (the old `--sew-shells` in 0.5) and this is turned on now in 0.6 because the performance of this generally has improved, `--sew-shells` in 0.5 would probably have taken weeks. The CGAL implementation in 0.7 will likely handle this more gracefully. Due to the extreme nature of this input it does not have very high priority for me, but if you want you can add back a command line flag or something to disable correcting the orientation for overly dense meshes like was the case before.

**Comment by johanrd** [comment]
Ok, thanks for the reply. We've got quite some cases recently where the conversion time has been an issue (>16h), so we are indeed considering to add the command back.

You were thinking of something like reverting 13d2cf33575b13382efb574f0d6c879095bcdbca, just with the defaults inverted?

**Comment by aothms** [comment]
> You were thinking of something like reverting 13d2cf3, just with the defaults inverted?

Good observation. Essentially that would be it. There are a couple of things going on:

* There is `faceset_helper` now which creates proper pairs of edges so that `BRepOffsetAPI_Sewing` is not needed anymore for proper IfcConnectedFaceSets. You can probably keep that enabled in all cases.
* There was different behaviour of triangulating faces instead of reprojecting on a plane. This is probably not significant in your cases. So you might want to keep that as well. Both ensure that a proper solid can still be constructed if it is needed for boolean operations.
* The major difference is in `convert(IfcConnectedFaceSet*)` where the call to `create_solid...()` is now unconditional. Before it would create a compound of unrelated faces which is quicker. We need to make sure that `ensure_fit_for_subtraction()` still works to still convert the compound of faces into a solid on-demand when the faceset is part of a boolean operation. 

> (this file takes 40 min on 0.7.0, btw)

Any differences currently between v0.6 and v0.7 are accidental and probably due to some unmerged changes. There should not be any significant differences in the occt implementation code paths. There could be changes though due to a different distribution over different static/dynamic libraries causing different compiler optimization results.

Thanks in advance for your help with this.

**Comment by aothms** [comment]
@johanrd I think you are right actually. The performance difference is too significant to enable this by default. Can you let me know if you are still planning to work on this from your end, otherwise I will do the changes as indicated. Thanks.

(I will rename the `--sew-shells` option to `--orient-shells` because that's much more related to what the user can observe)

**Comment by johanrd** [comment]
Hi, OK, I was considering to give it a try next week. But if you have a
clear idea on how to proceed, I guess that may be quicker (and more
hygienic, to be honest). Thanks – sounds reasonable!

**Comment by aothms** [comment]
Have a look https://github.com/IfcOpenShell/IfcOpenShell/commit/901e805d244a289fbfb33adb1d9db2853b12c6c9

It turns out the `--orient-shells` options doesn't do anything for this particular file anyway, probably due to the exorbitant distance.

**Comment by johanrd** [comment]
Thanks, 901e805d244a289fbfb33adb1d9db2853b12c6c9 seems to have done the trick. There are fewer timouts now, indeed. 

That said, we still find 42e00581cd187309ebea1aba585fae06dd7dd13f the most stable as of now  (considering the segfault regressions #597, #598, #599, #600, and #601 – plus the more recent #595 and #596, of course)
