### ISSUE TITLE
Bug: IfcStructuralCurveMembers no longer display after Bonsai v0.8.0 update

### ISSUE THREAD

**Issue by Crowder44** [IfcOpenShell/IfcOpenShell#5788]
**Issue Description:**

The `IfcStructuralCurveMembers` from the bSI IFC4 `structural-curve-member.ifc` example file no longer display after the Bonsai v0.8.0 update.

**Link to bSI Example File:** [bSI IFC4 Structural Curve Member](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/annex_e/structural-analysis-model/structural-curve-member.html)

**Observations:**

1. **Successful Display (Before Update):**
   - **BlenderBIM Add-on**: v0.0.240602-47704b1
   - **Blender Version**: 4.1.1
   - ![image](https://github.com/user-attachments/assets/b1480b23-f88e-43b8-9bca-c06431a2b6ab)

2. **Failed Display (After Update):**
   - **Bonsai Version**: v0.8.0
   - **Blender Version**: 4.2.1
   - ![image](https://github.com/user-attachments/assets/5a297083-8d74-4b2d-ad9b-a1c8735e2e4b)

**Impact:**
BlenderBIM used to be my preferred program for viewing any IFC file, especially those containing `IfcStructuralAnalysisModels` and `IfcStructuralMembers`. However, Bonsai v0.8.0 now fails to display any `IfcStructuralMember`.

**Request:**
I wish to use and recommend Bonsai as the go-to program for viewing and exploring `IfcStructuralAnalysisModels`, but I cannot do so until this bug is fixed. Thank you.

**Comment by Andrej730** [comment]
@Crowder44 structural members are hidden by default, you need to just uncheck their visibility:
![image](https://github.com/user-attachments/assets/3e6ad8a6-085e-44b3-9751-d4dbe5c403c7)

From your screenshot it seems you already have their visibility enabled but they still don't appear probably due to the disabled visibility in the viewport (monitor icon). Not sure if it was a thing in v0.8.0 release, in the latest release it doesn't work that way anymore.
![image](https://github.com/user-attachments/assets/f95cc2db-ee1b-4d3e-991f-9227512beca8)
![image](https://github.com/user-attachments/assets/b199293f-a7cb-4ed3-b626-7e648497f5b6)

**Comment by Crowder44** [comment]
@Andrej730 This solution worked! The "Disable in Viewport" toggle is not enabled in the "Filters" dropdown menu by default in my current configuration for some reason. I believe I have the latest version of Bonsai installed, but anyway, it seems that this wasn't a bug after all. 

Thanks for the help! I will close this issue now.
