### ISSUE TITLE
a mode that indicated which storey was the default story. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5817]
Would be nice to have some mode that indicated which storey was the default story. 

![image](https://github.com/user-attachments/assets/13364fa6-144f-4f50-bb77-779c031b318a)

**Comment by sboddy** [comment]
Isn't the label at the top enough? I mean one _or_ the other, ok, but both? Seems to be unnecessary clutter. Speaking in a hypothetical, a project with many buildings/storeys, I think the label at the top is more usable because it is always visible. An indicator as you describe may often not be visible, so would be bad if it were the only indicator. Also, what if the building is collapsed. Now you'd have to expand everything trying to find the default container.
(Right now that top label is a little glitchy for me, and not updating when I set a new default although this _was_ working, but that is a separate issue.)

**Comment by theoryshaw** [comment]
I see my confusion, it seems the field is not being updated as intended.

https://github.com/user-attachments/assets/6e151a92-f14a-4ef0-93ef-e0f2cb3c6ba0
