### ISSUE TITLE
Have things like `location="My Building"` or `parent="My Aggregate"` work with `bim.append_library_element_by_query()`

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5901]
Would be awesome if things like `location="My Building"` or `parent="My Aggregate"` worked with `bim.append_library_element_by_query()`

**Comment by steverugi** [comment]
@theoryshaw 
as mentioned in my post on OSArch, it workss fine with my version (4.3.0 - 241211)
see video where I use a query like `IfcElement, location="My Building", parent="My Aggregate"`


https://github.com/user-attachments/assets/1984d4c3-4fd8-4b53-aa20-e6550e8dee61

Since append does not import the container all elements go in "Unsorted" as shown in the video
please advise, cheers

**Comment by steverugi** [comment]
is it a problem to import elements in the same original container name instead of using the "Unsorted" one?
I think It would make the `append` process complete
thanks

**Comment by theoryshaw** [comment]
Sorry, meant using `location="My Building"` or `parent="My Aggregate` just by itself, without preceding it with a product, like `IfcElement`.   


https://github.com/user-attachments/assets/405dc415-1449-441c-886c-d1ffe05834bd

**Comment by Andrej730** [comment]
It's a general issue with queries - if you type in query `parent="My Aggregate"` in Search UI and then open the query again it will automatically add `IfcProduct, IfcTypeProduct` to it. 
I'll add a general fallback to use products/product types as a base elements for the query if neither ifc class and guid are not provided.
