### ISSUE TITLE
`bim.perform_quantity_take_off()` doesn't seem to work with certain object

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5905]
`bim.perform_quantity_take_off()` doesn't seem to work with certain object...

file: 
[quanitiy takeoff not working - Copy.ifc.txt](https://github.com/user-attachments/files/18232026/quanitiy.takeoff.not.working.-.Copy.ifc.txt)

https://github.com/user-attachments/assets/cd622566-8a86-454c-97c3-b72dd94b4e1d

**Comment by theoryshaw** [comment]
For what its worth, if you change the type's class, it works...

https://github.com/user-attachments/assets/d36eb674-b6ef-4dec-a03b-4cecf79f5852

**Comment by Andrej730** [comment]
I've added an info message, so at least it won't go silently but yes, there's currently no method defined for IfcRoof quantification using IfcOpenShell quantification:
https://github.com/IfcOpenShell/IfcOpenShell/blob/a4aaf9b4c3aa107dcffa925d84f59196fc266382/src/ifc5d/ifc5d/IFC4QtoBaseQuantities.json#L485-L491

But there are some methods defined for quantification using Blender quantification instead of IOS:
https://github.com/IfcOpenShell/IfcOpenShell/blob/a4aaf9b4c3aa107dcffa925d84f59196fc266382/src/ifc5d/ifc5d/IFC4QtoBaseQuantitiesBlender.json#L485-L490
