### ISSUE TITLE
Using ifcConvert stucks

### ISSUE THREAD

**Issue by orashkenazi** [IfcOpenShell/IfcOpenShell#603]
Hello, while trying to convert a quite small IFC file to a collada or OBJ file, the process get stucks.
(im using the" 0.5.0 preview 2" from http://www.ifcopenshell.org/ifcconvert.html, are there any newer version of it?)

when I try to upload it to a bimserver that is using the bimserver plugin, the geometry is generated quite fast on the check-in. (But, i don't know what actually happen inside bimserver's ifcopenshell plugin... I just wanted to mention that i can browse it in Bimviews with no problem)

I assume the bimserver plugin is newer? 

thanks
Or

**Comment by aothms** [comment]
> I assume the bimserver plugin is newer?

Correct.

> the geometry is generated quite fast on the check-in

The BIMserver plug-in does indeed a little bit more. It splits the IFC file in chunks and passes it to multiple IfcOpenShell processes simultaneously, because IfcOpenShell itself is not multi-threaded yet.

> are there any newer version of it?

Definately

https://github.com/IfcOpenBot/IfcOpenShell/commit/9a85fbc2250e7626aac49bdd525614f4e7e405d7#comments

**Comment by Moult** [comment]
IfcOpenShell is now multithreaded, so can this be closed?
