### ISSUE TITLE
Regression: segfault on reinforcingBar (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#674]
1. Convert [674--reinforcingBar--segfault.ifc](https://github.com/IfcOpenShell/files/blob/master/674--reinforcingBar--segfault.ifc) with 32588c6 (OCCT 7.3.0p3) and experience segfault:
```FATAL: An error occurred, status code 139.```

2. Convert the same file with 42e0058 and experience that although the file does not segfault, there is a weird twist happening on one of the segments:
<img width="295" alt="Screenshot 2019-09-17 at 13 44 23" src="https://user-images.githubusercontent.com/4601554/65039207-ffe09f00-d951-11e9-8aeb-0833ddb20cc0.png">

3. Expected geometry from Solibri:
<img width="295" alt="Screenshot 2019-09-17 at 13 44 47" src="https://user-images.githubusercontent.com/4601554/65039228-0b33ca80-d952-11e9-8b44-a2511e9677ae.png">

**Comment by aothms** [comment]
Hm, interesting, there is tiny linear segment at the place of this weird twist. This is linear segment is eliminated by the composite curve builder, but for some reason the OCCT pipe builder crashes on the input. I have seen weird results before on pipes along multiple adjacent circular segments, so I have decided to break up the wire in case of adjacent non-linear segments.

![afbeelding](https://user-images.githubusercontent.com/1096535/68029900-8958f000-fcb8-11e9-929c-14e94721c330.png)

This means, as visible above, that there are some intermediate internal cap surfaces and in case the segments are not continuous there would not be nice a corner. I think we can live with that, but using these shapes in boolean operations might be troublesome due to the co-planar internal caps.

159ce931b4dc9cc8a4841f142baed759bc41462d

**Comment by johanrd** [comment]
Nice, thanks! I can verify that this no longer segfaults after 159ce93

**Comment by johanrd** [comment]
Reopening, as the twist seems to be back when converting from 4320888d9dd82eb6c9b2de7cae4b9eae530e2f79:

![Jan-11-2020 18-33-08](https://user-images.githubusercontent.com/4601554/72208238-e1725680-34a0-11ea-9707-be098d9ef638.gif)

**Comment by johanrd** [comment]
Closing, as this converts successfully when converting from 71f836d🎉
