### ISSUE TITLE
Precompiled binaries for Windows and Linux for Python 3.7

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#680]
I'd like to give out some precompiled binaries for Windows and Linux of IfcOpenShell that are compiled with Python 3.7 64-bit. This is because Blender works with Python 3.7 and so the IfcOpenShell must be compiled for it. This allows other people to test the Blender export script that I've been developing. I have compiled it from source on my own machine, but I'd like to distribute the compiled version to another machine.

I have no experience with packaging a precompiled binary. I tried copying over the Python site-packages/ifcopenshell directory to a fresh computer, but that seems to be insufficient. What are all the files I need to provide to a fresh computer so that their Python can `import ifcopenshell`?

**Comment by aothms** [comment]
Regular builds are provided in this repository
https://github.com/IfcOpenBot/IfcOpenShell/commit/b4ce5be86d293246dd84f59891e2d5d7f2240284#comments

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op do 26 sep. 2019 02:43 schreef Dion Moult <notifications@github.com>:

**Comment by Moult** [comment]
Absolutely beautiful! It works perfectly!

**Comment by Moult** [comment]
Actually, quick question - where are the build instructions, so that I can start including the Blender IFC exporter as part of this build? Also, what triggers the build?

**Comment by aothms** [comment]
It's still on my list to write about this. https://github.com/IfcOpenShell/IfcOpenShell/issues/583#issuecomment-491588776

> Also, what triggers the build?

The trigger is manual currently. But the process is automated. It contains a full rebuild of the C++ sources so takes a couple of hours. And more often then not it encounters errors.

For the time being due to your rapid iterations it's probably better if you don't depend on this process.

Over time I hope for the two Blender addons to get merged and your work to be included also in the automated builds.

**Comment by Moult** [comment]
Makes sense. I will definitely merge the two plugins in the future. For now I will do a manual "packaging" for those who want to play with it! Thanks again!
