### ISSUE TITLE
Access attribute types of an entity type with Python

### ISSUE THREAD

**Issue by hlg** [IfcOpenShell/IfcOpenShell#718]
With the Python wrapper, when creating an IFC entity instance, there is apparently no type checking for specific entity data types of its attributes, such that it is very easy to create invalid IFC and go unnoticed. There is only checking for simple data types. I wonder whether I missed some function that helps in creating valid IFC or it would be easy to add it.

I am not very familiar with C++, SWIG and IfcOpenShell internals, but naively poked around a bit in the source code and Python interface. I found that if I have an `entity_instance e`, created or read from a file, and call `getArgumentEntity` on its wrapped data i eventually could get type information. However it seems that this not implemented in the glue/wrapper layer between C++ and Python. I am getting the following errors:

    >>> e.wrapped_data.getArgumentEntity(0)
    <Swig Object of type 'IfcSchema::Type::Enum *' at 0x7fb30a55fc60>
    >>> e.wrapped_data.getArgumentEntity(1)
    swig/python detected a memory leak of type 'IfcSchema::Type::Enum *', no destructor found.
    <Swig Object of type 'IfcSchema::Type::Enum *' at 0x7fb2ffabde70>
    >>> e.wrapped_data.getArgumentEntity(0)
    swig/python detected a memory leak of type 'IfcSchema::Type::Enum *', no destructor found.
    <Swig Object of type 'IfcSchema::Type::Enum *' at 0x7fb30a55fc60>

Using this route, wouldn't it be possible with little effort, to expose the supposed IFC entity type of an attribute as a String? I assume this would already help a bit to ensure valid IFC generation.  No need to include the whole schema and do static typing.

I stumbled over a method called `is_valid` which properly checked an entity_instance against optionality of the attributes, but I can't find it anymore. Maybe this would also be a possible place to include some form of type checking.

**Comment by aothms** [comment]
In the v0.6.0 branch it's possible to validate an entire file post-hoc https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/validate.py

I guess similar function can be combined to type check at instantiation in Python. Or it can also be implemented in C++ of course, using basically the same data model.

For select valued attributes a little bit more work is needed than equality checking on the old `getArgumentEntity()`. For that reason I suggest v0.6.0 because that's the version where a complete in-memory representation of the schema is present. In v0.5.0 this was not yet complete for select types.

**Comment by hlg** [comment]
Great, that's even better! And, yes, indeed, schema validation would not be possible anyway just based on simple equality checks.
