### ISSUE TITLE
How to parse geometry with DISABLE_TRIANGULATION?

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#733]
As Blender supports ngons and quad meshes quite happily, I thought it would be nice to export an IFC from Blender and re-import it with the quads retained.

Currently, geometry can be extracted like so:

```
shape = ifcopenshell.geom.create_shape(self.settings, element)
f = shape.geometry.faces
```

However, if I set:

```
self.settings.set(self.settings.USE_BREP_DATA, True)
self.settings.set(self.settings.DISABLE_TRIANGULATION, True)
```

Then `shape.geometry.faces` no longer exists. I get `shape.geometry.brep_data`, which contains a plaintext serialisation which I assume I can parse (is there documentation for this plaintext syntax?), but seems a bit inefficient. Is there a better / easier approach to get untriangulated geometry? Ideally, I'd love to just continue using `shape.geometry.faces`.

(Note: setting DISABLE_TRIANGULATION by itself doesn't seem to trigger any change, I think USE_BREP_DATA is needed to let PythonOCC kick in)

**Comment by aothms** [comment]
The brep data is Open CASCADE's internal format. It's not incomprehensible, but it's indeed not documented for external use.

Also note that Blender would not be able to use it if the surfaces are not planar or the edges are not linear.

Ideally there would be an output option in between Triangle mesh and Full BRep. But it's not completely trivial to define. For example Blender supports NGons, but not internal boundaries. Different software also might have different tolerances for how planar an NGon has to be.

You can also reconstruct a higher order representation from the triangles. If you disable `WELD_VERTICES`, vertices will not get shared by different faces. This means only the internal triangles from the triangulation get used twice. You can reconstruct edge uses from the geometry.faces, e.g. for a rectangle `(1,2,3,1,3,4)` you follow the triangle edges and get `[{1,2}, {2,3}, {3,1}, {1,3}, {3,4}, {4,1}]`. Since `{3,1} == {1,3}`, as they are sets (in fact the order is supposed to be reversed), that one edge can be eliminated. You need to be careful not to do this for curved faces, so probably check if the normals are identical.

You can also experiment with Blender's Limited Dissolve, which more or less does this.

**Comment by Moult** [comment]
I see. I didn't realise that the OpenCascade internal format contained things like internal boundaries which Blender wouldn't support.

Currently I am using Blender's merge vertices (basically weld verts), tris to quads, and limited dissolve, which generally gets a very clean mesh out of a triangulate import. I hoped that DISABLE TRIANGULATION would be close enough to what Blender supported to be used directly to prevent to cleanup step, especially for geometry originally exported from Blender to begin with :)

I'll close this issue! :)
