### ISSUE TITLE
blenderBIM: Applying IfcSensorType on IfcDistributionControlElement

### ISSUE THREAD

**Issue by maxenceryan** [IfcOpenShell/IfcOpenShell#761]
Hey guys,

First off, thank you for all the great work you are doing! I recently came across blenderBIM and was playing around with it. I set a regular box to be an IfcDistributionControlElement. Now I want to assign it an IfcSensorType but it is not listed under the PredefinedType where I was expecting. I also tried this with IfcDoor, which does have the PredefinedType but how would add an IfcDoorStyle to access, for instance, the IfcDoorOperationEnum?

Thank you!

![image](https://user-images.githubusercontent.com/53180223/72218649-88a4cb80-353d-11ea-8d5f-0f2b2f9dd37b.png)

**Comment by Moult** [comment]
An IfcDistributionControlElement does not have any predefined type fields according to the IFC standard. Perhaps you want to assign it to be an IfcSensor instead?

The IfcDoorStyle element has been deprecated by buildingSMART and is not allowed to be exported any more. The `OperationType` is now a regular object attribute, which you can set in the object properties tab in Blender when selecting an IfcDoor element. You will have to manually type in the enum value though, since there isn't yet support for enums in the attributes menu :) (I'll add it to the todo list!)

Hope it helps.

**Comment by maxenceryan** [comment]
Hey, sorry it took me so long to write back. Thank you for the response and clarification, I am working with IFC2x3 mainly so I am not familiar with all the changes to IFC4.  Enum support would be a good idea :) I will go ahead and close this.
