### ISSUE TITLE
IfcConvert 0.6.0: "No geometry iterator registered for IFC4X2"

### ISSUE THREAD

**Issue by jrojoCI3** [IfcOpenShell/IfcOpenShell#770]
Hello, I'm trying to convert a Ifc file in 4x2 specification (bridge) into an obj, and IfcConvert throws this error:

```
IfcOpenShell IfcConvert 0.6.0b0 (OCC 6.9.1.oce-0.18)
Scanning file...
Done scanning file   
Parsing input file took 0 seconds
terminate called after throwing an instance of 'IfcParse::IfcException'
  what():  No geometry iterator registered for IFC4X2
```
Why could this be happening? I'm using an Ubuntu 18.04 distribution. Unfortunately I cannot share the model. It's probably a very simple thing that I'm not seeing right now, but it's been three days trying to (unsuccessfully) solve this issue, so any help will be welcomed.

**Comment by Moult** [comment]
Try opening the IFC file in a text editor and check what the header schema value is. If it says IFC4X2  rename it to just IFC4 and try again.

**Comment by jrojoCI3** [comment]
First of all, thank you for the quick answer. I've just tried that. Although there seems to be a geometry iterator this time, there are missing elements in the geometry from the 4X2 schema. This is the error thrown:

```
IfcOpenShell IfcConvert 0.6.0b0 (OCC 6.9.1.oce-0.18)
Scanning file...
Done scanning file   
Parsing input file took 0 seconds
Creating geometry...
Done creating geometry (10 objects)                                

Log:
[Error] Entity with 'IFCBRIDGE' not found
[Error] Entity with 'IFCBRIDGEPART' not found
[Error] Entity with 'IFCBRIDGEPART' not found
[Error] Entity with 'IFCBEARING' not found
[Error] Entity with 'IFCBEARING' not found
[Error] Entity with 'IFCVIBRATIONDAMPER' not found
[Error] Entity with 'IFCVIBRATIONDAMPER' not found
[Error] Entity with 'IFCBRIDGEPART' not found
[Error] Entity with 'IFCVIBRATIONDAMPER' not found
[Error] Entity with 'IFCBEARING' not found
[Error] Entity with 'IFCBRIDGEPART' not found
[Error] Entity with 'IFCVIBRATIONDAMPER' not found
[Error] Entity with 'IFCBEARING' not found
[Error] {1u3eo6ksvCu9hh_UAkRpd0} Instance #30 not found
[Error] {0LP$xJSjvBaAgFYg4Q9c3q} Instance #37 not found
[Error] {0LP$xJSjvBaAgFYg4Q9c3q} Instance #37 not found
[Error] {1KDwOX9GrBHge4pnF5o$W0} Instance #37 not found
[Error] {1KDwOX9GrBHge4pnF5o$W0} Instance #37 not found
[Error] {2ERPJuaUn3EfW3CAtUv11y} Instance #37 not found
[Error] {2ERPJuaUn3EfW3CAtUv11y} Instance #37 not found
[Error] {35Ulh7ckv039pwmaxJQz$u} Instance #4275 not found
[Error] {35Ulh7ckv039pwmaxJQz$u} Instance #3692 not found
[Error] {0hiSf3j2vAHOtaVbDWbU6f} Instance #4275 not found
[Error] {0hiSf3j2vAHOtaVbDWbU6f} Instance #3692 not found
[Error] {0NlnVQnVP2Uuxk4FbqphY0} Instance #4275 not found
[Error] {0NlnVQnVP2Uuxk4FbqphY0} Instance #3692 not found
[Error] {0qvtsmU$X9U9WEuh1Ts1It} Instance #4275 not found
[Error] {0qvtsmU$X9U9WEuh1Ts1It} Instance #3692 not found
[Error] {0lhTakLijD4RQwOd7lUqKy} Instance #4275 not found
[Error] {0lhTakLijD4RQwOd7lUqKy} Instance #3692 not found
[Error] {2mQhCgZybFv9HC8hf4wtnX} Instance #4275 not found
[Error] {2mQhCgZybFv9HC8hf4wtnX} Instance #3692 not found
[Error] Instance #4275 not found
```
I've checked it up and it looks like those Instances not found (30, 37,4275,...) correspond to IFCBRIDGE, IFCBRIDGEPART,  etc.

**Comment by Moult** [comment]
I suspect IfcOpenShell that's because IfcOpenShell supports IFC4 Add2 TC1 (see readme file) where those entities don't exist yet.

Perhaps @aothms can suggest how to support these newer schemas. I cannot help here, sorry :(

As a temporary workaround I wonder if you could just change them into IfcBuilding.

**Comment by AdriScho** [comment]
Hi @jrojoCI3 

I had the same issue (#734) and I submitted a fix back in december : https://github.com/IfcOpenShell/IfcOpenShell/pull/743.

In 0.6.0 branch, IfcOpenShell does support multiple schemas at runtime. So, if you overwrite FILE_SCHEMA from IFC4X2 to IFC4, then it will get the IFC4 schema, so that's normal if you get missing elements.

Which version of IfcOpenShell are you using ?

**Comment by jrojoCI3** [comment]
Hello @AdriScho 
I've tried with master, v0.6.0 and v0.7.0 but this was the furthest I could get. Which one should be the one working? (I mean I saw the commits ahead of master of these two and it looked like 0.6.0 was more active and its commits were more recent).

> if you overwrite FILE_SCHEMA from IFC4X2 to IFC4, then it will get the IFC4 schema, so that's normal if you get missing elements during conversion of your IFC4X2 file

That's what I thought, but as lost as I was/am with this, I couldn't just not try :). Also, thank you for all your help. I really appreciate it.

**Comment by AdriScho** [comment]
You can find more details about branch strategy and IfcOpenShell development activity [here](http://blog.ifcopenshell.org/2019/12/v060.html).

Normally, if you compile from the latest commit of 0.6.0 branch, it should be working. The merge happened [back in december](https://github.com/IfcOpenShell/IfcOpenShell/commit/05a5c3c)

Let me know if you're still having issues.

**Comment by EAzari** [comment]
Hi @jrojoCI3 and @AdriScho I know that some of you want work and test IFC4.2, but it seems that IfcOpenShell doesn't support it, and I think it's obvious because IFC4.2 still is a proposal and not a release 
However, if @aothms and IfcOpenShell team want can work on it 

I don't know about the bridge and other specs, but in the building schema IFC4.2 has 7 Enumeration Types, 15 Entities, and 2 Property Sets more than IFC4.1

**Comment by jrojoCI3** [comment]
I see. Thank you @AdriScho  again for all this! I will try with the 0.6.0 branch this morning with all the new commits and give you feedback. Also, thank you for sharing the link to the [development activity](http://blog.ifcopenshell.org/2019/12/v060.html). It's interesting and clarifying.

**Comment by jrojoCI3** [comment]
Ok. So I tried and the same message appeared:

> IfcOpenShell IfcConvert 0.6.0b0 (OCC 6.9.1.oce-0.18)
Scanning file...
Done scanning file   
Parsing input file took 1 seconds
terminate called after throwing an instance of 'IfcParse::IfcException'
  what():  No geometry iterator registered for IFC4X2

:(

**Comment by jrojoCI3** [comment]
I understand that IFC4x2 is still a proposal and not a standard release. However, I will leave the  issue open as it hasn't been solved. Is this ok?

**Comment by AdriScho** [comment]
Hi ! I've just checked, and [my fix is incomplete](https://github.com/IfcOpenShell/IfcOpenShell/commit/05a5c3c3f9a82ff2a2d74d0b0704b10478bdd3eb). I didn't make changes on ifcgeom_schema_agnostic... The error you are seeing is "normal".
Ok, I will work on it this week. @aothms FYI

IFC4x2 is a [Candidate Standard release] at the moment (https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/). Obviously, it is not ready for production use (_as far as i know, I don't know any BIM Authoring tool exporting IFC4x2 files_).

**Comment by aothms** [comment]
Thanks for picking this up @AdriScho !

@jrojoCI3 when the geometry handling is registered, success still depends on whether the file uses geometry specific to the bridge/alignment schemas, since no support for those entities is currently implemented. If the file on uses the bridge product labels and uses conventional ifc4 geometry your file will convert fine. From the entity errors it seems that might be the case as the unrecognized entities look like products and not geometries, but I could be wrong.

**Comment by jrojoCI3** [comment]
I see. Thank you very much, @aothms :). With your consent I will close the issue with this final clarification. I understand that that support will come with the final standard release. So good luck and congratulations for such an amazing tool!
