### ISSUE TITLE
Why roofs have different colors when the same color is used in ifc file?

### ISSUE THREAD

**Issue by JanoSlivka** [IfcOpenShell/IfcOpenShell#780]
Hello,

I have question about load color of element from ifc file. Both ifc files have defined same color for element.

This ifc file load color from file.
[roof_color.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4149350/roof_color.zip)
![roof_color](https://user-images.githubusercontent.com/44858488/73678346-80f9c200-46b8-11ea-9d69-385759a4f861.png)

This ifc file use default color.
[roof_default_color.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4149355/roof_default_color.zip)
![roof_default_color](https://user-images.githubusercontent.com/44858488/73678386-91aa3800-46b8-11ea-8606-4c37589a9c1d.png)

Why?

Thanks for help.

**Comment by Moult** [comment]
A note that for the `roof_color.ifc` file, using `IfcMaterialList` is [deprecated](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/link/ifcmaterialselect.htm) in IFC4. You are using IFC2X3, but just thought I'd highlight it.

Otherwise, your file looks valid. I only assume that the viewer does not handle IfcMaterialLayerSetUsage and therefore won't show colour since it can't show the layers of materials.
