### ISSUE TITLE
build-deps.cmd not working when ran from parent dir

### ISSUE THREAD

**Issue by StefanSkrobanski** [IfcOpenShell/IfcOpenShell#804]
Hi,

I'm attempting to build IfcOpenShell on Windows 10, using the vs2017-x64 toolset.

As per the ReadMe and following suggestions from this forum I'm running the x64 Native Tools Command Prompt for VS 2017, and running `build-deps.cmd`. However it does not seem to be installing OpenCascade, and therefore 'run-cmake.bat' does not seem to work.

Am I doing something wrong?

**Comment by StefanSkrobanski** [comment]
It seems the problem was in the build-deps.cmd script, "cecho.cmd" and "7za.exe" were being being called in numerous places without the correct relative path e.g "%~dp0\utils\cecho.cmd"

**Comment by aothms** [comment]
Yes, I recall there have been strange issues before with complaints about the script not being able to call cecho or 7za.

It should be the case that the PATH is augmented with the utils path here https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/win/vs-cfg.cmd#L152 as `%~dp0utils;%PATH%`

I don;t know why that would be failing. Maybe because there is no slash (`%~dp0\utils;%PATH%`?) are you running in a different director from the .cmd files, are there spaces in your path? I've never understood what caused these issues for some users.

**Comment by StefanSkrobanski** [comment]
Thankyou for your response.

I was running build-deps.cmd from its parent directory, with no spaces in the path.

**Comment by aothms** [comment]
> I was running build-deps.cmd from its parent directory, with no spaces in the path.

Ok, **parent directory**, that explains it then perhaps. Let's relabel the issue and keep it open. If you have a working solution (fully qualifying all util paths) it would also be great if you can turn that into a Pull Request.

**Comment by Stinkfist0** [comment]
Ah yes, I'm pretty sure this was a known limitation of the script from the get-go. I think I documented it (at least implicitly in the instructions), but if not, it would be nice to be mentioned.

**Comment by aothms** [comment]
Thanks for confirming @Stinkfist0 I added a check in builds-deps to see if `%~dp0` matches `%CD%`. I think that should do the trick.
