### ISSUE TITLE
normal vector detection

### ISSUE THREAD

**Issue by DaJansenGit** [IfcOpenShell/IfcOpenShell#808]
First of all, thanks for the great work you are doing with this project!
I'm trying to get the rotational orientation `alpha_1` of the normal vector `n_1` (facing outside of the building) of wall elements in a project. (see image below)
![image](https://user-images.githubusercontent.com/27726960/76147498-1c59ca80-609d-11ea-9e1c-216b559a8695.png)

- I get the rotational angle between true north and global coordination system with the information stored in `project.RepresentationContexts.TrueNorth.DirectionRatios`.
- I also get the rotational angle between local coordination system of the walls and the global coordination system.
- **But** I'm not sure whats the best way to get the rotational angle between the normal vectors facing outside of the building and the local coordination system of the wall elements.

I found that there is an information stored in the `LayerSetDirection` and `DirectionSense` attribute of the IfcMaterial, but I'm not sure if this is always pointing outside... Do you have an idea how to get this normal vector in a robust way? Thanks for you help!

**Comment by Moult** [comment]
By the way, for geolocated projects, I would not use `project.RepresentationContexts.TrueNorth`, as it has been deprecated. It should be stored in the `IfcMapConversion` entity as `XAxisAbscissa` and `XAxisOrdinate`. In IFC2X3, there is an `EPset_MapConversion`.

Also, note that in addition to the rotations you have already gotten, you will need to go jump through the spatial tree to the world coordinate, and then apply the map conversion, since object positions are usually relative to one another. I.E you will need the wall extrusion axis, then ifc product object placement, then usually its building storey placement, then building placement, then site placement, then project world coordinates, and then map conversion (this tree is a generalisation - it depends on the exact hierarchy in your model).

Getting the wall direction itself is quite tricky, as any IFC product can be represented in many different ways. It may have a material layer set as you've noted, but it equally may not. It may be an extrusion, or a BRep, or CSG, or otherwise. Each has to be handled differently.

A good first pass might be to check the `IsExternal` property to isolate external walls.

**Comment by aothms** [comment]
> Getting the wall direction itself is quite tricky, as any IFC product can be represented in many different ways. It may have a material layer set as you've noted, but it equally may not. It may be an extrusion, or a BRep, or CSG, or otherwise. Each has to be handled differently.

You could use IfcOpenShell to evaluate the full BRep of the geometry and look (for example) at the normal direction of the largest face surface. Also regardless of the Body representation (CSG/BRep/Extrusion) there should/could be an additional Axis representation that more or less gives this direction (often a polyline or trimmed curve)

**Comment by Moult** [comment]
Ping @DaJansenGit did our answers help? Will close this bug in 2 weeks if no further activity.

**Comment by DaJansenGit** [comment]
Sorry for the late reply. Your answers helped and we were able to get the proper information. I will close the issue.
