### ISSUE TITLE
OCC 7.4 Windows

### ISSUE THREAD

**Issue by ninichki** [IfcOpenShell/IfcOpenShell#813]
Is it possible to use OCC 7.4 in vs2017-x64?
If I check out 7.4 Version it gives me a linkere error. OCC is compiled with MD Option and IfcOpenshell with MT.

**Comment by aothms** [comment]
This is not related to the OCCT version. IfcOpenShell is compiled with MT (mostly for historical reasons, since the precompiled ICU we used on Windows was compiled with MT). If you use the build script and change the OCCT_VERSION there you can use 7.4.0 https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/win/build-deps.cmd#L230

**Comment by CyrilWaechter** [comment]
@ninichki feel free to reopen with fresher informations but I think the question has been answered therefore this old issue should be closed.
