### ISSUE TITLE
BlenderBIM. Bug exporting IFC

### ISSUE THREAD

**Issue by GOBA-esp** [IfcOpenShell/IfcOpenShell#851]
Hi, I have imported an IFC, I have modified a column (location Z), I have tried to export the new IFC, but this error has been generated:

Traceback (most recent call last):
  File "C:\Users\xx\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\operator.py", line 67, in execute
    ifc_exporter.export(context.selected_objects)
  File "C:\Users\xx\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\export_ifc.py", line 1121, in export
    self.ifc_parser.parse(selected_objects)
  File "C:\Users\xx\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\export_ifc.py", line 147, in parse
    self.classification_references = self.get_classification_references()
  File "C:\Users\xx\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\export_ifc.py", line 660, in get_classification_references
    'raw_element': self.classification_reference_maps[reference.referenced_source][reference.name]
KeyError: ''

location: <unknown location>:-1

**Comment by Moult** [comment]
Thanks for reporting - just a heads up that the importer and exporter were built at different times, originally by different people, with different priorities, and at different speeds, and therefore the BlenderBIM Add-on does not currently support round-tripping an IFC with itself. It was also not a high priority, since people either used Blender to import, or to export, but not really to round-trip. In short, please expect errors with a round-trip :)

Nonetheless, with each release, the data model within Blender used to store imports and export for IFC are converging, which will fix this problem over time.

But why wait! Let's fix this! I think it's because the BlenderBIM Add-on only exports IFC4 classifications, but will happily read IFC2X3 classifications... will keep you posted...

**Comment by Moult** [comment]
All fixed :) Please replace your `import_ifc.py` with this: https://raw.githubusercontent.com/IfcOpenShell/IfcOpenShell/v0.6.0/src/ifcblenderexport/blenderbim/bim/import_ifc.py

and also replace your `export_ifc.py` with this https://raw.githubusercontent.com/IfcOpenShell/IfcOpenShell/v0.6.0/src/ifcblenderexport/blenderbim/bim/export_ifc.py

Hope it helps!

**Comment by GOBA-esp** [comment]
It works, thanks a lot! You're so fast :)
