### ISSUE TITLE
Standardise interface for all IFC formats (IFCXML + IFC-SPF at the moment)

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#854]
I've tested out the experimental IFC XML support and I found that the interface for accessing IFC data differs significantly from a regular IFC SPF file.

For instance after I `foo = ifcopenshell.ifcopenshell_wrapper.parse_ifcxml('/home/dion/brep-model.ifcxml')` (by the way, why is it under `ifcopenshell_wrapper` and not just in `ifcopenshell` out of curiosity?), then I see `foo.header`, whereas in IFC SPF it is `foo.wrapped_data.header`.

For an element, in IFCXML I have to do `element.get_argument` whereas in IFCSPF I can just do `element.Name`, for instance.

I completely understand that IFCXML is a long way away from proper use, but I am curious if this is symptomatic of part of the IfcOpenShell code architecture - it would be good to have an identical interface, so that code written for IFCSPF works identically for IFCXML... or do the data transports really differ so much that it is not possible?

**Comment by aothms** [comment]
That's simply because we only added it to the wrapper code and not the handwritten python module https://github.com/IfcOpenShell/IfcOpenShell/commit/42fedf81c4e49f1cb4f3934a0ed9dd2049fad84b#diff-64d910603262e9f0a9f6c26e328c4db7

See for example `from_string()` that wraps the SWIG-generated wrapper (`ifcopenshell.ifcopenshell_wrapper.file`) call by a the handwritten  `ifcopenshell.file` class. So when you call something from `ifcopenshell.ifcopenshell_wrapper` directly you're missing all the handwritten functionality.

It's just a matter of implementing something similar as we have in from_string() but I thought maybe you had ideas on good usage (like autodetecting based on extension or read the first couple of bytes to see whether it's a XML or ZIP header, ...). So I didn't take that step.

**Comment by Moult** [comment]
Sorry, yes, you're absolutely right! Thanks very much! Consider this solved.

**Comment by CyrilWaechter** [comment]
Hi,
I have carefully read this issue and related commits and reference. I have implemented a function to handle this in my FreeCAD importer for IfcRelSpaceBoundary without extracting file to a temporary directory like in blenderbim : 
```python
    def open(ifc_path: str) -> ifcopenshell.file:
        ext = os.path.splitext(ifc_path)[1]
        if ext.lower() in (".ifczip", ".zip"):
            zip_path = zipfile.Path(ifc_path)
            for member in zip_path.iterdir():
                zipped_ext = os.path.splitext(member.name)[1].lower()
                if zipped_ext == ".ifc":
                    return ifcopenshell.file.from_string(member.read_text())
                if zipped_ext == ".ifcxml":
                    # TODO: How to do this as ifcopenshell.ifcopenshell_wrapper has no parse_ifcxml ?
                    raise NotImplementedError("No support for .ifcXML yet")
            else:
                raise NotImplementedError("""Supported files :
            - unzipped : *.ifc | *.ifcXML
            - zipped : *.ifczip | *.zip containing un unzipped type""")
        return ifcopenshell.open(ifc_path)
```
What I don't understand is that I have no `ifcopenshell.ifcopenshell_wrapper.parse_ifcxml` method. I checked that my `IFCXML_SUPPORT` is not set to off in my compile script.
