### ISSUE TITLE
BlenderBim: Error when importing IFC exported from Renga Architecture

### ISSUE THREAD

**Issue by EsbenZeuthen** [IfcOpenShell/IfcOpenShell#859]
When I try to import a n .ifc file exported from Renga Architecture,  the import ends prematurely, and I get the following error message: 
![image](https://user-images.githubusercontent.com/65496316/82148534-eb440600-9854-11ea-8654-7195b3a927bb.png)

I tracked the issue in line 641 of import_ifc.py. It seems that the script assumes that the element is a IfcGeometricRepresentationSubContext, when it is in fact a IfcGeometricRepresentationContext that has no TargetView attribute. I tried modifying the following code snippet:

    def add_product_representation_contexts(self, element, obj):
        subcontexts = []
        if element.is_a('IfcProduct'):
            if not element.Representation:
                return
            for r in element.Representation.Representations:
                subcontexts.append('{}/{}/{}'.format(
                    r.ContextOfItems.ContextType,
                    r.ContextOfItems.ContextIdentifier,
                    r.ContextOfItems.TargetView))
    ...

into:

    def add_product_representation_contexts(self, element, obj):
        subcontexts = []
        if element.is_a('IfcProduct'):
            if not element.Representation:
                return
            for r in element.Representation.Representations:
                if r.ContextOfItems.is_a('IfcGeometricRepresentationContext'):
                    for s in r.ContextOfItems.HasSubContexts:				
                        subcontexts.append('{}/{}/{}'.format(
                            s.ContextType,
                            s.ContextIdentifier,
                            s.TargetView))
                else:
                        subcontexts.append('{}/{}/{}'.format(
                            r.ContextOfItems.ContextType,
                            r.ContextOfItems.ContextIdentifier,
                            r.ContextOfItems.TargetView))
    ...

and now I can import the model without any issues. The fix is quick and dirty and should probably be improved, but it got me past this issue.

I use BlenderBIM 0.0.200511.

**Comment by Moult** [comment]
The fix is almost valid ;) Thanks for the report! This was actually fixed 4 days ago: https://github.com/IfcOpenShell/IfcOpenShell/commit/dd525d8a30beed88ec018e05c6e7475ab64ca25c - by the way, if you hit other import or export issues skim through the recent commits as a series of bugs were already discovered and fixed - it may save you doing hacks ;)

... I guess this is what happens when I don't have a comprehensive integration test suite and introduce too many features for a release ;) Would you be interested in donating a test file from Renga Architecture to https://ci.blenderbim.org/ so that we can automatically test a sample from that vendor to prevent regressions?
