### ISSUE TITLE
[BlenderBIM] Clicking 'fetch object passport' yields error

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#871]
<img width="261" alt="Screen Shot 2020-06-04 at 09 53 03" src="https://user-images.githubusercontent.com/505366/83700100-3c236f00-a649-11ea-9281-c0c6e429e6c5.png">

<img width="854" alt="Screen Shot 2020-06-04 at 09 52 56" src="https://user-images.githubusercontent.com/505366/83700105-3f1e5f80-a649-11ea-91d4-1f618b8b9a33.png">

**Comment by Moult** [comment]
This is highly experimental currently and requires a documentation association. Needs to be completely redesigned in terms of UI. Will not fix as I plan to completely redo the way this feature operates.

Will keep this bug open as a reminder.

**Comment by Moult** [comment]
Fixed so that it actually _does_ something now instead of spewing out error messages. Basically the idea is that a referenced document may contain extra parametric metadata or proxy objects in something that Blender can consume. For now, it'll parse a Blend file and import a mesh with the given identifier.
