### ISSUE TITLE
[BlenderBIM] Error creating sections (can't discover correct workflow)

### ISSUE THREAD

**Issue by globalcitizen** [IfcOpenShell/IfcOpenShell#878]
Trying to rediscover the correct workflow demonstrated for sections, I have done the following.

- Perform project __Quick Setup__
- Create a series of objects suitable for a test section
- Assign all objects an Ifc identity as ElectricalActuators
- Change to __Output__ tab, __Section Planes__ pane and __Add section plane__. The object appears fine and I can move it around. I seem to remember there was a camera in the demonstration however and I do not have one.

<img width="264" alt="Screen Shot 2020-06-05 at 06 21 09" src="https://user-images.githubusercontent.com/505366/83806676-3e430780-a6f5-11ea-9bbc-a2df64b3226b.png">

- In __Documentation__ create unique strings in fields __View name__ and __Sheet name__ then click __Add view to sheet__

I get an error like this.

<img width="904" alt="Screen Shot 2020-06-05 at 06 20 52" src="https://user-images.githubusercontent.com/505366/83806687-426f2500-a6f5-11ea-902e-0cd4b133a701.png">

Some things that are unclear to me:
 - What is a view preset? Why are there apparently only two of them?
 - What is a view (same as a camera?)
 - What is a sheet (same as a camera? Something related to IFC documents?) 
 - What is a 'digital twin'?

Here is the test scene showing the positioning of two sample section objects.

<img width="750" alt="Screen Shot 2020-06-05 at 06 45 10" src="https://user-images.githubusercontent.com/505366/83808470-2ae56b80-a6f8-11ea-8c98-a0db9297ee1d.png">

Excluding dimensions and with gray in place of hatches, this is a rough example of what I am looking for as an SVG output.

<img width="443" alt="Screen Shot 2020-06-05 at 06 57 11" src="https://user-images.githubusercontent.com/505366/83809504-de029480-a6f9-11ea-8462-f8dbbfbb7d02.png">

**Comment by Moult** [comment]
The section plane feature is not the same as creating a view - they are two separate features. Misleading, I know. The section plane is used for temporary model cutting for model inspection, not for documentation cutting.

In the documentation panel, the plus button next to view name adds a  new view camera. The camera and view is one and the same. The camera object then has a cut section button. By default the cut section button will not actually perform any vector cuts, until one or more IFC files have been added in the "Add IFC File" button in the documentation panel. All output is in the diagrams folder in the data dir of the addons folder, then, `blenderbim/bim/data/`.

A view preset is like setting a series of render settings to get a certain style of graphical output: preset 1 sets a kind of shaded view, usually used for architectural elevations, and preset 2 sets a black and white view, usually used at construction phase drawings. They are a one-way change and do not remember your previous settings so are destructive. I built them as a temporary feature to "get drawings out" :) In the future, they will need to be removed and a new feature built to remember  render settings per view.

A sheet is simply a blank titleblock, which you can then place views on by selecting the desired sheet and view in the dropdowns. The create sheets button will then auto process the views on the sheets to give them automatic naming, automatic scale factor, automatic view numbering, revision control, and so on. I did not demo these to you, but hopefully with these clues you can work it out.

You get that error because you have created a view but haven't yet cut a section in the camera.

Hope it makes sense. Looking forward to the 200 bugreports related to making this whole process less bad :)

**Comment by globalcitizen** [comment]
Thanks for quick response, I have to run right now but will test this later today. 200 bug reports coming.

**Comment by globalcitizen** [comment]
Well, minor success. I have managed to create a view, and this has created a camera object, and I can see roughly the expected view, or even alter it with translation on the Z axis to move through the example structure.

<img width="806" alt="Screen Shot 2020-06-05 at 21 29 14" src="https://user-images.githubusercontent.com/505366/83871690-da135880-a773-11ea-82e2-bf8d299ad12d.png">

Now I wish to generate a drawing (which is apparently called a sheet and may comprise multiple views, according to your comments at #879).

I click __Add view to sheet__ and receive no error. I then click __Open sheet__ and can see the view on the sheet, without dimensions and located outside of the boxed area.

This is great progress. More bug reports coming.
