### ISSUE TITLE
create_shape has duplicate vertices when processing a curve

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#887]
The following code snippet is practically unchanged from when you originally wrote the Blender importer.

```
        shape = ifcopenshell.geom.create_shape(self.settings, item)
        geometry = shape.geometry
        f = geometry.faces
        e = geometry.edges
        v = geometry.verts
        vertices = [[v[i], v[i + 1], v[i + 2]]
                 for i in range(0, len(v), 3)]
        faces = [[f[i], f[i + 1], f[i + 2]]
                 for i in range(0, len(f), 3)]
        if faces:
            edges = []
        else:
            edges = [[e[i], e[i + 1]]
                     for i in range(0, len(e), 2)]
```

I discovered that when I create_shape on an IfcPolyline, like so:

```
#2567= IFCCARTESIANPOINT((0.,-0.17922234));
#2568= IFCCARTESIANPOINT((-0.21635306,-0.074987969));
#2569= IFCCARTESIANPOINT((-0.11810696,-0.35844468));
#2570= IFCCARTESIANPOINT((0.,-0.3175088));
#2571= IFCCARTESIANPOINT((0.11810696,-0.35844468));
#2572= IFCCARTESIANPOINT((0.21635306,-0.074987969));
#2573= IFCCARTESIANPOINT((0.,0.));
#2574= IFCPOLYLINE((#2568,#2569,#2570,#2571,#2572,#2573,#2568));
```

... then I will get this result ...

```
vertices: [[-0.21635306, -0.074987969, 0.0], [-0.11810696, -0.35844468, 0.0], [-0.11810696, -0.35844468, 0.0], [0.0, -0.3175088, 0.0], [0.0, -0.3175088, 0.0], [0.11810696, -0.35844468, 0.0], [0.11810696, -0.35844468, 0.0], [0.21635306, -0.07498796899999999, 0.0], [0.21635306, -0.074987969, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [-0.21635306, -0.074987969, 0.0]]
edges: [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]
faces: []
```

As you can see, there is a double up of vertices, and instead of a joined polyline, I get each individual edge. In particular, I would expect the exact same number of vertices as IfcCartesianPoint, and the edges should read `[0, 1], [1, 2], [2, 3], [3, 4]...`

Is there a problem with the way I am expecting this function to work?

**Comment by aothms** [comment]
Hm yes I think what you describe is analogous to the way faces are being processed. So vertices are not shared between distinct faces, but when a curved face is approximated into triangles, those vertices will be shared. So you can identify which were separate faces.

In the case of a polyline these are separate edges, so distinct vertices.

The above applies UNLESS `settings.WELD_VERTICES` is set, and I think you're right that this is not properly applied in the case for line segments. So that should indeed probably be updated https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcgeom/IfcGeomRepresentation.h#L328

Can you confirm this related to `settings.WELD_VERTICES`?

**Comment by Moult** [comment]
Hmm, I tried setting `settings.WELD_VERTICES` to True but the output is still the same.

**Comment by aothms** [comment]
Sorry, I was indeed very vague. I just pushed https://github.com/IfcOpenShell/IfcOpenShell/commit/95c953fd52a64c1b638e3c79f490304f63d2a713 to make it consistent with what I was describing.

So without WELD_VERTICES: I get shared vertices on the duplex door arcs for example, because they part of the same IfcTrimmedCurve/IfcCircle
*with* WELD_VERTICES you do get shared vertices when part of different edge (A polyline is multiple edges).

**Comment by Moult** [comment]
Thanks :) I'll wait for the bot build then test again :)
