### ISSUE TITLE
Blender BIM. Automatic quantities calculated at IFC export

### ISSUE THREAD

**Issue by GOBA-esp** [IfcOpenShell/IfcOpenShell#898]
Hi, it would be great if automatic quantities were calculated at an IFC export.

**Comment by aothms** [comment]
@Moult this appears something we can solve on the IfcOpenShell level. There is already code to calculate the quantities for validation purposes. Incl projections and all.

Can we use this issue to create (a) a list of quantities to be exported based on building element classes (b) define the API call in IfcOpenShell to do this calculation (file-based or element based).

**Comment by Moult** [comment]
@aothms that would be a very good solution.

When I first implemented quantities, I had to make assumptions on how to deal with doing things like getting the length of an IfcWall, because in Blender, an IfcWall is a brep, and unlike other BIM programs which split an IFC wall every time it changes direction, that rule doesn't apply in Blender. What are your thoughts on that? How would the IfcOpenShell utility know how to handle it?

Volume is straightforward. Area for a wall has the same issue as length, though.

**Comment by aothms** [comment]
Ultimately I think it's not only a question of the quantities but also mapping to the expected representation types. So for a wall this is Body: Extrusion with one or more clipping half space + Axis: Polyline or trimmed curve. Once we have the Axis representation for a wall it gives us the context to calculate area and length.

How would you see that in BlenderBIM? I guess we could derive the Axis direction from connectivity to other walls (not sure whether that would always work). We could assume the largest face is parallel to the Axis. You could require users to tag the longitudinal faces.

How useful are Axis representations in BlenderBIM? They are the base for the material layerset at least. But I guess that could be encoded implicitly.

Do you ever use the ifcopenshell.geom.serialize or ifcopenshell.geom.tesselate functions? I guess we could provide additional context to these so that they can emit extrusions instead. Or turn them into product-level operations.

On other hand, perhaps we need connectivity information, so a gobal `file`-based call can perhaps make more sense. Then we can even automatically emit properties like `IsExternal`.

**Comment by Moult** [comment]
In Blender, people can just model meshes rapidly without caring about an axis. As a result, an axis may not exist at all upon export. Maybe the safe thing to do is to only calculate length if an axis representation is given, and not make any assumptions on the body representation. Maybe some decoupled functions to potentially generate axis geometry from a body representation given some assumptions would be a good starting point. These functions may exist in Blender, which may be more useful to the user as they don't need to export to IFC first.

I have not used ifcopenshell.geom.serialize or tesselate. How might it be useful? Have you got any sample code?

Object connectivity is not currently supported in the BlenderBIM Add-on, since inherently the modeling paradigm doesn't require it. It is on the to-do list for me to figure out how to best support it.

**Comment by aothms** [comment]
> These functions may exist in Blender, which may be more useful to the user as they don't need to export to IFC first.

Good point, hadn't considered that.

> I have not used ifcopenshell.geom.serialize or tesselate. How might it be useful? Have you got any sample code?

They allow to directly emit a OCCT TopoDS_Shape to a ifc file. But yeah you don't really use PyOCC. 

Hm maybe my idea wasn't so useful, maybe it shouldn't be in ifcopenshell after all... On the other hand you could still use IFC as a light weight tagging mechanism to interact with the geometrical processing functionality of IfcOpenShell (like figuring out element connections using the spatial querying functionality and then figuring out element axes) even if the user is not interested in exporting to IFC.

**Comment by JanFilipec** [comment]
Well generally speaking a length of a wall is a very problematic property, even in a software, where most walls are defined parametrically with an axis and variables for width and height (i.e. Archicad, Revit) it doesn't work very well, since there are always at least a few cases modeled with meshes, nonparallel faces, etc., where the length doesn't have any meaningful value.
I do not believe there is any reliable general solution for this. A very simple way to get an approximately correct result would be calculating the length of wall face/floor intersection as a separate property, or an analysis considering the adjacent room geometry. However, in my opinion the only way to allow for a professionally reliable quantity take-off is to force the user to define all the walls parametrically and report only the length property of such properly defined geometry.
This is one of the reasons why I'm trying to model walls in Blender with curves with bevel geometry, which does not work very well yet.

**Comment by Moult** [comment]
@JanFilipec I am generally in favour of software design that minimises "magic". I agree that it is problematic, and so I would try to find a design that does the best it can, but doesn't hide the fact that some walls simply are too hard to figure out, and that the user should step in.

Off the top of my head, here is series of general solutions, with a fallback to the next one:

 1. If an IfcMaterialLayerSetUsage is provided, then an Axis is also provided, and so calculate based on that, perhaps with some smarts around offsets for measuring walls by the structural layer?
 2. Otherwise, if an axis representation is still provided, calculate the length of that. (At my level of conservatism, I would stop here... but I can think of a few possible more general solutions, no idea if any good or not...)
 3. If the wall consists of a single extruded area solid, we assume it is an extrusion from the ground upwards (as opposed to some rotated wall extrusion), project the profile to the Z axis, and collapse verts by 600mm (heuristically, very few walls thicker than that). This will form an axis, which can perhaps be calculated?
 4.If the wall is some more complex geometry, perhaps a similar technique will work - project to Z axis, collapse verts, and uh, maybe some cleanup is required to get to an axis.
 5. Ask the user :)

And as always, let the user check and audit results.

**Comment by Moult** [comment]
Far from perfect, but basic operators are in place - you press the little icon and it'll spit out the answer it thinks based on some heuristics.

![image](https://user-images.githubusercontent.com/88302/87638738-a28ec780-c787-11ea-9ebd-e2d5f7f38688.png)

I'll hook it up to the export soon so that it can do this automatically on export (as a user option, disabled by default) to close out this bug, and then we can refine it over time.

**Comment by Moult** [comment]
Closing out bug :)

![image](https://user-images.githubusercontent.com/88302/87844631-4603e780-c902-11ea-91dc-7e066e92dbbb.png)
