### ISSUE TITLE
BlenderBIM Beveled curve export

### ISSUE THREAD

**Issue by JanFilipec** [IfcOpenShell/IfcOpenShell#900]
Exporting geometry from Blender created by using "Bevel" on a curve object in curve object properties does not work as expected. Only part of the profile is exported and the bevel does not have the correct proportions.

Model:
![Model](https://user-images.githubusercontent.com/67052298/84889059-84ef1500-b098-11ea-8ef0-20acd9539ddd.JPG)

Export (Viewed by BIM Vision):
![Export](https://user-images.githubusercontent.com/67052298/84889124-a223e380-b098-11ea-8606-383de31c1d90.JPG)

This also results in an incorrect svg sections generated by the documentation tool:
![Svg cut](https://user-images.githubusercontent.com/67052298/84889364-0e9ee280-b099-11ea-925e-e8645fee7aca.JPG)
(The monkey is a mesh and is cut properly, the walls are beveled curves and are rendered properly but cut incorrectly)

**Comment by Moult** [comment]
Thank you @JanFilipec :) Can you please also upload a small .blend file with your walls for me to replicate?

**Comment by JanFilipec** [comment]
Here you go:
[Monkey walls.blend.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4792183/Monkey.walls.blend.ifc.zip)
[Monkey walls.blend.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/4792184/Monkey.walls.blend.zip)

**Comment by Moult** [comment]
@JanFilipec the first issue is that the bevel object had a scale applied to it. I've just fixed that.

The next issue is that the current implementation doesn't support sweeping a profile (i.e. your bevel object) along a directrix (i.e. the spline of your curve). It only supports splines that are 1 segment long (i.e. representing a single extrusion).

@aothms - I'd like to support extruding a profile along a directrix. IFC seems to have a fixed reference sweep, as well as a surface sweep. I _don't_ think the fixed reference sweep works here, since the directrix goes around in 90 degree corners so, the reference can't be fixed...

![image](https://user-images.githubusercontent.com/88302/86586989-2f899200-bfcc-11ea-8304-332bba466a20.png)

I've also tried a surface one with a basic IfcPlane just for testing, but it always ends up being this shape regardless of how I try to tweak the IfcPlane's axes - what surface should I investigate for this? I've attached my test IFC file.

[test.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/4878472/test.ifc.txt)

... here's what I end up with:

![image](https://user-images.githubusercontent.com/88302/86587073-51831480-bfcc-11ea-8860-b2e5dbf68000.png)

If it helps, Blender just has a directrix, and it has a "tilt" angle stored at each vertex (select one, and press Ctrl-T to see) along the directrix which defines the orientation of the profile.

**Comment by Moult** [comment]
Ping @aothms

**Comment by aothms** [comment]
@Moult these kind of sweeps are not very well implemented in software and also IfcOpenShell is a bit lacking in the surface curve swept area (plane should work though). I would say, if there are discontinuities in your sweep you better export them as different parts (can still be one object), as you say as extrusions, it'd greatly improve interoperability. IfcWall actually are actually **not allowed** to have discontinuities. You can still add an Axis representation perhaps with the full polyline. Theoretically, with surface curve swept area you can represent the tilts if you can somehow get them to correspond to a continuous surface, like a cylinder or nurbs, but that wouldn't be a general solution and expect lot's of flaws during import in other tools. The other way around should be possible though. Create the spine, sample normal at surface and you have your tilts.

**Comment by Moult** [comment]
Closing as the refactor makes this form of editing obsolete. It will be replaced with gizmo-based native IFC editing.
