### ISSUE TITLE
BlenderBIM: add a second ifc file?

### ISSUE THREAD

**Issue by lalberts** [IfcOpenShell/IfcOpenShell#911]
Hello,

I can open my first ifc Object. Add an stl for the terrain..  but I can not add (import) a second ifc Building?
Site collision? Do I need to edit myfiles to adapt ifcproject or so?

can I then export the wohle thing as a single ifc? 
How to declare the terrain as ifc object?

Thanks
Lukas

Traceback (most recent call last):
  File "C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\operator.py", line 88, in execute
    ifc_importer.execute()
  File "C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 284, in execute
    self.create_aggregates()
  File "C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 1372, in create_aggregates
    self.create_aggregate(rel_aggregate)
  File "C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 1386, in create_aggregate
    self.add_defines_by_type_relation(element, obj)
  File "C:\Users\alberts\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blenderbim\bim\import_ifc.py", line 1142, in add_defines_by_type_relation
    obj.BIMObjectProperties.relating_type = self.type_products[related_type.GlobalId]
KeyError: '3bwM3TsFfBrPuWULpeaa6B'

location: <unknown location>:-1

**Comment by Moult** [comment]
Can you provide the two IFC files you are trying to import? That would help in the debugging process.

Send to dion@thinkmoult.com - you can use https://send.firefox.com/ - I will not share your model and will only use it to fix this bug.

**Comment by lalberts** [comment]
Sorry,
it is the seconfd file which is corrupted.. it won't load alone neither..

Lukas

**Comment by Moult** [comment]
@lalberts the second file does not import due to invalid IFC data. I've reported this as a bug to Autodesk, but given that their bugfixes can take some time to be available to users, I've added a workaround to allow this invalid behaviour in the BlenderBIM Add-on.

Will now investigate round-trip import / export, and merging files. By the way, I will soon be providing an IfcPatch recipe for merging IFCs which would be a better approach, if that is your end-goal.

**Comment by Moult** [comment]
A little recommendation to enable import multiprocessing in the scene properties experimental properties - that'll make your imports go much, much faster.

I've fixed a bunch of issues which now let you export it as-is for the smaller file (will investigate big file soon). However, some colours are not properly retained on export on certain curtain wall panels. To properly fix this requires a bit of work ... but hopefully the improvements are always useful for you ...

Also, the big file has multiple objects that are not grids exported as IfcGrid (they are named `IfcGrid/ZZZ_do not use_PF_ST_grating for Profiline_ACO:std` ). I don't think this is illegal as far as IFC is concerned, but I highly recommend fixing that in your export settings, since it makes round-tripping more difficult, when I expect to find valid Grid objects in the code :)

**Comment by lalberts** [comment]
Thanks a lot Dion,

 

I have no control about the ifc coming from the architecture partner. I can only recommend him to cross check his  revit exports.

But even there I am not an expert, what can I recommend? What tool would do as a ifc checker?

BlenderBim of course.. Is there something from Autodesk?  

I can recommend him: https://wiki.osarch.org/index.php?title=Revit_setup

 

You do not have to worry about my files..  

If sometimes this merging of ifc will work out of Blender this would be perfect..but this has not be tomorrow or next month.. keep cool.

 

A good help to educate Revit users to create good ifc’s is much more important.

A kind of Tutorial for Revit users..

Check this, change that, use this plug-in. Crosscheck with that tool..  

This would be really helpful.

 

Then this description change from BRP to Extruded-room and the other way round would be nice.  But if I followed tihe talks on OSARCH, this is already possible.

This is still a feature problem fort he DDS-CAD software.. it wants the extruded description.. Revit saves the BRP-description.  (or the other way round)

Well Room-lists are not compatible between this 2 softwares.

 

It is surprising how much efforts those software makers are spending on BIM, but none is as fast a reliable as BlenderBIM.

I do not understand why they do not build their tools on this open-source Tools that are to my mind ready to surpass all these proprietary packages.

DialuxEVo (lightning designtool) is another candidate that would benefit of the BIM possibilities of opensource software.

 

Take care of yourself.

 

Lukas

Esslingen

 

Von: Dion Moult <notifications@github.com> 
Gesendet: Samstag, 11. Juli 2020 14:37
An: IfcOpenShell/IfcOpenShell <IfcOpenShell@noreply.github.com>
Cc: lalberts <lukas_alberts@web.de>; Mention <mention@noreply.github.com>
Betreff: Re: [IfcOpenShell/IfcOpenShell] BlenderBIM: add a second ifc file? (#911)

 

A little recommendation to enable import multiprocessing in the scene properties experimental properties - that'll make your imports go much, much faster.

I've fixed a bunch of issues which now let you export it as-is for the smaller file (will investigate big file soon). However, some colours are not properly retained on export on certain curtain wall panels. To properly fix this requires a bit of work ... but hopefully the improvements are always useful for you ...

Also, the big file has multiple objects that are not grids exported as IfcGrid (they are named IfcGrid/ZZZ_do not use_PF_ST_grating for Profiline_ACO:std ). I don't think this is illegal as far as IFC is concerned, but I highly recommend fixing that in your export settings, since it makes round-tripping more difficult, when I expect to find valid Grid objects in the code :)

**Comment by Moult** [comment]
I have developed quite a comprehensive IFC checker called BIMTester. Right now, it requires some training to operate,  but I am planning to build it into the BlenderBIM Add-on UI so that everybody can use it very easily. I will keep you posted.

The wiki has a series of articles (including that Revit Setup one you linked to) - I highly recommend reading them in detail.

Supporting native extrusions is a work in progress :)

Vi-Suite is a good open source alternative to DialuxEVo, and works with Blender.

**Comment by Moult** [comment]
New fixes are in, so that both files (both big and small) can export without errors from the BlenderBIM Add-on. Hooray! Closing bug :)
