### ISSUE TITLE
Exception when relating multiple spatial structures via IfcHierarchyHelper

### ISSUE THREAD

**Issue by Jo-Meer** [IfcOpenShell/IfcOpenShell#924]
Hello,

I found an error when you want to relate multiple spatial structures to one (e.g. 2 BuildingStoreys to 1 Building). The relation is a IfcRelAggregates and was done with the IfcHierarchyHelper.

To reproduce add `file.addBuildingStorey()` just below the `file.addBuildingProduct(south_wall);` ([here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/examples/IfcOpenHouse.cpp#L84))

The exception originates from the 'get_children_of_relation' method in the IfcHierarchyHelper. There the IfcRelAggregate will be searched for the attribute with the name `RelatedElements`. This works fine with an IfcRelContainedInSpatialStructure as this has such an attribute. But IfcRelAggregate has `RelatedObjects`.

Is it discouraged to use the IfcHierachyHelper as this seems not be used by the python wrapper and therefore it is not tested enough by the users?

**Comment by aothms** [comment]
Thanks, fixed in https://github.com/IfcOpenShell/IfcOpenShell/commit/f92d1708f2c6dfab59662830a043c0b6e244f006

> Is it discouraged to use the IfcHierachyHelper as this seems not be used by the python wrapper and therefore it is not tested enough by the users?

That's a good and honest question. The group of users using IfcOpenShell Python is more visible (and yes, probably larger) but the C++ API is used as well. Due to the usage of templates it's not really possible to use the hierarchy helper in Python (but it also uses late bound interfaces a lot, so perhaps we should rewrite it to use only latebound and then interface it in Python as well). Issues with hierarchy helper are easy to fix, so I wouldn't consider it a risk. I have long term plans to put in extra modules (for example to calculate quantities and e.g. wall connectivity information) that can be real productivity boosts.

**Comment by Moult** [comment]
Seems to be fixed, so closing.
