### ISSUE TITLE
[Geom iterator class] progress() and size

### ISSUE THREAD

**Issue by e3dEF** [IfcOpenShell/IfcOpenShell#929]
Hi,

I have two questions regarding the IfcGeom::Iterator<real_t> iterator.
1) How can I get the number of IfcGeom::Elements in the iterator.
2) iterator.progress() always outputs "50" with my test building, while printing within the loop. I'm using todays code base.

Kind regards

**Comment by aothms** [comment]
> How can I get the number of IfcGeom::Elements in the iterator.

I don't think this is currently exposed in the API. It's also not really known, because when products after selection turn out not to have suitable representations (or error) no IfcGeom::Elements is returned from them. Feel free though to add an indication to this based on `ifcproducts` or `tasks` or whatever.

2. I guess you're using multi threads? Progress handling is not really great in that case. In that case initialize() does most of the heavy lifting. And the iteration itself is just passing over the finalized representations. Also I think it runs in 0..50 for the silly reason that the default progress bar in IfcConvert is 50 characters wide. Improvements welcome :)

**Comment by e3dEF** [comment]
Thank you for your quick reply!
I want to save geometry in a vector and before, resize it according to iterator length. I solved this by using instances_by_type for classes to include and declaration().is() for classes to exclude to get the maximum possible length. I shrink the populated vector capacity afterwards.

**Comment by aothms** [comment]
Ok, guess std::list would also be an option. Performance difference with
vector likely not significant wrt geometry processing time and no need for
guessing capacity

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op za 25 jul. 2020 13:26 schreef bim <notifications@github.com>:
