### ISSUE TITLE
--include option not working

### ISSUE THREAD

**Issue by jdimyadi** [IfcOpenShell/IfcOpenShell#93]
We tried to extract IfcSpace objects from an IFC model using --include --entities IfcSpace options to dae or obj, but the process could not start and no error was returned. We tried both PC and OSX versions with the same result.

**Comment by aothms** [comment]
Since `--entities` is a multi-valued argument, the positional arguments, i.e. filename(s), need to precede it. The following will work: `IfcConvert Duplex_A_20110907_optimized.ifc --include --entities IfcSpace` whereas you probably did the following:  `IfcConvert --include --entities IfcSpace Duplex_A_20110907_optimized.ifc`. In the latter case `Duplex_A_20110907_optimized.ifc` is seen as another entity type to ignore. This is a bit silly, but it stems from the fact we use the generic boost program options to do the command line parsing, but I guess it could be improved.

**Comment by jdimyadi** [comment]
Excellent. Thank you. Will try putting the --include and --entities options last.
Yes, the same question (#92) was posted by my colleague. Thank you.

**Comment by pump-kin** [comment]
Thank you, yes it works with the options after both file input and output.

**Comment by aothms** [comment]
Good to hear!

**Comment by AngryCarrot** [comment]
The help of the tool, IfcConvert, is wrong。 It says "IfcConvert [options] input.ifc output". However, the ral order is "IfcConvert Duplex_A_20110907_optimized.ifc --include --entities IfcSpace". It drives my colleague and me almost mad...
If you could update the help message in "http://ifcopenshell.org/ifcconvert.html" and the tooltips, maybe others would not take a wrong way.
Thanks.
