### ISSUE TITLE
Logical vs Boolean: ".U." token breaks parsing

### ISSUE THREAD

**Issue by stgatilov** [IfcOpenShell/IfcOpenShell#94]
Parsing of file [ADT-FZK-Haus-2005-2006.ifc](https://github.com/opensourceBIM/TestFiles/blob/master/TestData/data/ADT-FZK-Haus-2005-2006.ifc) is broken after the latest changes, mainly including my changes in the tokenizer [#82](https://github.com/IfcOpenShell/IfcOpenShell/pull/82).

It stops on the first line with ".U." token, which is:
`#72=IFCCOMPOSITECURVE((#47,#55,#63,#71),.U.);`
with error:
`Token .U. at 3388 invalid boolean`
It seems that this ".U." stands for UNKNOWN value of LOGICAL type, meaning that the author didn't know whether this curve was self-intersecting or not.

As far as I see, method IfcCompositeCurve::SelfIntersect() returns a bool. I suppose that previously UNKNOWN logical value was being silently converted into FALSE boolean value, and now it is not. Should this behavior be restored?

**Comment by aothms** [comment]
You're right. It seems the IfcConvert never actually even reads any logical value, so it slipped through the cracks. I implemented a quick hack, have a look. I propose we implement it properly using boost::tribool in 0.6.0.

**Comment by stgatilov** [comment]
Yes, the file is parsed successfully now.

P.S. I doubt anyone really uses the SelfIntersect property.

**Comment by aothms** [comment]
I agree. Since it can be unknown anyway it is hard to rely on it in implementations. Sometimes you even encounter `optional logical` attributes in the schema, in which case the semantics are even more unclear, i.e what is the difference between null and unknown?

In other express schemas these attributes are sometimes references. E.g [1] but also then unknown is treated the same as false.

[1] http://www.steptools.com/support/stdev_docs/express/step_irs/html/t_gbsf_-02.html
