### ISSUE TITLE
shebang issues

### ISSUE THREAD

**Issue by tpaviot** [IfcOpenShell/IfcOpenShell#940]
A recent commit 0cc816922cc6e1cc0654f252e13b07cdb1d54e4c added/modified python scripts shebangs, from
```python
#!python
```
to
```python
#!/usr/bin/python3
```
This change prevents the scripts to be run from virtual environments, you @Moult @brunopostle should leave the user choose which python has to be used.

**Comment by Moult** [comment]
You are correct :) @brunopostle would you mind?

**Comment by brunopostle** [comment]
Go ahead, though I query the rationale behind this. There are various opinions about what the shebang should be:

`#!/usr/bin/python`
`#!/usr/bin/python3`
`#!/usr/bin/env python`
etc..

..but I'm not familiar with the idea that there should be no shebang at all. If your usage doesn't require a shebang, then it will be harmlessly ignored as a comment.

Have to tried the scripts with `#!/usr/bin/python3` in this virtual environment? because `#!python` doesn't seem to work here (and only one of the six scripts in the patch actually uses this form).

**Comment by aothms** [comment]
I always thought that shebangs has to be absolute so `#!python` is not preferred. I think ` #!/usr/bin/env python` is preferred to lookup the absolute path based on the path env var. That ought to work with all virtual env kind of setups that prefix the path.

**Comment by Moult** [comment]
I think that makes sense @aothms - thoughts @tpaviot ?

**Comment by brunopostle** [comment]
Consider settling on `#!/usr/bin/env python3`, as any python 3 installation will always have a `python3` executable, but `python` could be python 2 depending on how the system has been set up.

**Comment by tpaviot** [comment]
yes, ```#!/usr/bin/env python``` is ok

**Comment by Moult** [comment]
@tpaviot just double checking, `python3`, not just `python` is OK?

**Comment by tpaviot** [comment]
@Moult yes, ```#!/usr/bin/env python3``` is better, sorry I posted my previous comment at the same time @brunopostle did
