### ISSUE TITLE
IfcUtil::IfcBaseEntity to attribute

### ISSUE THREAD

**Issue by e3dEF** [IfcOpenShell/IfcOpenShell#943]
Hi,

how can I access the product attributes like IsDefinedBy, when having an IfcUtil::IfcBaseEntity using entity = geom_object->product()?
I thought of something like this: if(entity.declararion.is("IfcProduct")) print(entity.data().Attribute)

Best

**Comment by aothms** [comment]
> if(entity.declararion.is("IfcProduct")) print(entity.data().Attribute)

This is C++, there isn't a structural typing mechanism (cfr TypeScript) where an if-statement will infer extra type information. Also keep in mind that IfcProduct can be from 5 different schemas, (which are all different types).

If you are sure about the exact type you can cast. IfcOpenShell also has a dynamic typing mechanism:

~~~
auto ifc_product = entity->as<Ifc4::IfcProduct>();
if (ifc_product) {
ifc_product->IsDefinedBy();
}
~~~

But this creates schema dependent code.

You can also use a latebound approach.

~~~
auto rels = entity->get_inverse("IsDefinedBy");
// or
std::string guid = *entity->get("GlobalId");
~~~

You can read more here http://blog.ifcopenshell.org/2019/12/v060.html

**Comment by e3dEF** [comment]
Thank you very much for your answer, I'm a bit spoiled by the fantastic Python version :)

I have a subsequent question, when using the schema independent code.  
```
boost::shared_ptr<IfcEntityList> os = entity->get_inverse("FillsVoids")
for (auto it = os->begin(); it != os->end(); ++it) {
            IfcUtil::IfcBaseClass * IfcRelFillsElement = *it;
```
How can I access the Opening Element to store it in a const IfcSchema::IfcOpeningElement * opening?

IfcRelFillsElement->data().getInverse("RelatingOpeningElement") can not work, because I need a const IfcParse::declaration* type and the attribute_index. 
Also, why do I get a boost::shared_ptr<IfcEntityList> os, when there is a cardinality of S[0:1] for the FillsVoids Attribute. In Python I would expect to get a single object.

I appreciate your help!

**Comment by e3dEF** [comment]
Thank you very much for your answer, I'm a bit spoiled by the fantastic Python version :)

I have a subsequent question, when using the schema independent code.

boost::shared_ptr<IfcEntityList> os = entity->get_inverse("FillsVoids") will give a list, but the cardinality is S[0:1] for the FillsVoids attribute. In Python I would expect to get a single object.

        for (auto it_fill = os->begin(); it_fill != os->end(); ++it_fill) {

            IfcSchema::IfcRelFillsElement *rel = (IfcSchema::IfcRelFillsElement *) (*it_fill);
            opening = rel->RelatingOpeningElement();

Is this the correct way to get the OpeningElement schema independent? I oriented on this example [link](https://github.com/IfcOpenShell/IfcOpenShell/blob/e283b51dbcced6d8121c55fafd49c9ee1f954b74/src/ifcgeom_schema_agnostic/Kernel.cpp#L74)

I appreciate your help!

**Comment by aothms** [comment]
> S[0:1] ... I would expect to get a single object

That's true. But both in Python and C++, inverse attributes are always a sequence. The reason is that these inverse cardinality constraints are not always respected on export.

> Is this the correct way to get the OpeningElement schema independent? I oriented on this example link

It really depends on what IfcSchema is. If it's a preprocessor directive, it will be undefined behaviour when IfcSchema does not match the schema of the file. Instead of casting with `(IfcSchema::IfcRelFillsElement *)` you can also cast with `->as<IfcSchema::IfcRelFillsElement>()`.

> I'm a bit spoiled by the fantastic Python version

It's just the difference between static typing and dynamic typing. But once you get the hang of it and have chosen an approach (templates or preprocessor) to handle the multiple schemas, the static typing in C++ will get you much better type safety and will help you catch subtle differences between the schemas that you would not have found in dynamically typed python.

**Comment by e3dEF** [comment]
Thank you very much for your answer!
