### ISSUE TITLE
[BlenderBIM] Using IfcSpace results in errors on import (even with "Import spaces" checked)

### ISSUE THREAD

**Issue by Krande** [IfcOpenShell/IfcOpenShell#964]
Hello!

I am not sure if this is a BlenderBIM specific issue or if its my lack of understanding of "legal" entities for spatial grouping in the IFC format.

In short; I am unable to successfully import ifc files relying on IfcSpace as a spatial group using BlenderBIM (even with the "import Spaces" checked). The same file is imported successfully using XBim. See my attached test files below. I am using BlenderBim v200829.

**Background**

So my goal is to create an IFC file containing spatial groups that are not buildings nor buildingstoreys. So I figured the "IfcSpace" serves as a "neutral" spatial group entity (please correct me if I'm wrong?). 

So, I created 2 ifc files; The first file "my_plx1.ifc" using IfcSpace and another "my_plx1_using_building_storey.ifc" using IfcBuildingStorey's as the spatial groups.

In the test files I am using 3 levels of IfcSpace "MyTopSpatialLavel", "MySecondLevel" and "MyThirdLevel".

**Using IfcSpace**

So this works as I intended\expected using XBim:
![image](https://user-images.githubusercontent.com/9642232/91656840-5e981d80-eabc-11ea-8950-347af5ee7de9.png)

However, it causes an error message in BlenderBIM and will not import any geometry:
![image](https://user-images.githubusercontent.com/9642232/91656835-50e29800-eabc-11ea-9f69-35153e478df3.png)
Using the "Validate IFC file" option in BlenderBIM generates the following error messages 

	2020-08-30 12:56:13,201    ERROR validate.py 91 In #53=IfcRelContainedInSpatialStructure('1LeibKwgyHwgBHw2f4ZOUQ',#5,'Physical model',$,(),#51)
	() not valid for <attribute RelatedElements: <set [1:?] of <entity IfcProduct>>>
	2020-08-30 12:56:13,202    ERROR validate.py 91 In #45=IfcRelContainedInSpatialStructure('1Leg99wgyHwgx5w2f4ZOUQ',#5,'Physical model',$,(),#43)
	() not valid for <attribute RelatedElements: <set [1:?] of <entity IfcProduct>>>
	2020-08-30 12:56:13,204    ERROR validate.py 91 In #37=IfcRelContainedInSpatialStructure('1Leg96wgyHwg03w2f4ZOUQ',#5,'Physical model',$,(),#26)
	() not valid for <attribute RelatedElements: <set [1:?] of <entity IfcProduct>>>

Note that the same error messages are present with\without using IfcSpace. So it might not explain whats causing the issue with importing IfcSpace.

The imported hierarchy and lack of geometry imported
![image](https://user-images.githubusercontent.com/9642232/91656848-6f489380-eabc-11ea-9221-5c70653007e6.png)

**Without IfcSpace**

When I substitute IfcSpace with IfcBuildingStorey everything seems to work as expected when importing using BlenderBIM:

![image](https://user-images.githubusercontent.com/9642232/91656923-2513e200-eabd-11ea-90dd-157e7b3bf141.png)

Here are the two sample files (with and without the use of IfcSpace)

Using IfcSpace
[my_plx1.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5146645/my_plx1.zip)

Using IfcBuildingStorey
[my_plx1_using_building_storey.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/5146658/my_plx1_using_building_storey.zip)

Any help with this issue is much appreciated!

Best Regards
Kristoffer

**Comment by Moult** [comment]
I'll check this out tomorrow as it's getting quite late here in Sydney time, but _awesome_ bugreport by the way - you've provided all the information I could possible think of! You rock!

**Comment by Moult** [comment]
This is a fairy interesting scenario which is relatively uncharted territory for BIM programs. I've fixed the import issue, as there is nothing illegal about creating a space of which there are partial spaces within it. However, to answer your more semantic question, the IfcSpace may or may not be used for your your building.

The ISO definition states:

> Spaces are areas or volumes that provide for certain functions within a building.

If there is no building involved, perhaps you should not use it.

Maybe if you're after flexibility, IfcSpatialZone might be the way to go? Not entirely sure without knowing the background of the project semantics.

Hope it helps.

By the way, if you're wondering why after the fix you still have no spaces showing up - that's because Blender treats spaces specially - spaces in IFC should be hierarchical, and therefore non-overlapping - so for the spaces to show, they need geometry. Otherwise they won't show up in the Blender project tree.
