### ISSUE TITLE
BlenderBIM: export out IfcSpaces as vector SVG

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#979]
Possible to export out IfcSpaces as vector SVGs?

video: https://www.dropbox.com/s/l5nk7eubl4345mb/2020-09-05_13-16-30.mp4?dl=0

files: https://github.com/OpeningDesign/OD_Library/tree/1705b4cc3582d2fc072e26601705203b93898db6/BIM/BlenderBIM

**Comment by Moult** [comment]
The "cut objects" setting is what determines what is cut and not cut in the SVG. There is a preset for an overall plan / section, with the intention that for 90% of overall plans and sections, you're only cutting through some objects, not all - e.g. you're not cutting through furniture or pipes. I forgot to include spaces in this preset list :) I've now added it, but also added a default CSS style of transparent, otherwise you're going to see a big black box.

By the way, the "Custom" cut objects setting lets you specify it manually, so you could write in ".IfcSpace" there, if you wanted it to only cut spaces and nothing else.

![image](https://user-images.githubusercontent.com/88302/92364436-6a2bba00-f136-11ea-90c8-64b415d96edc.png)
